container[0].bin= 8
container[0].i= 118
container[0].j= 219
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 118
container[1].j= 220
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 119
container[2].j= 218
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 120
container[3].j= 218
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 120
container[4].j= 221
container[4].angle= 135
container[4].value= 255


container[5].bin= 18
container[5].i= 120
container[5].j= 222
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 120
container[6].j= 228
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 121
container[7].j= 218
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 121
container[8].j= 223
container[8].angle= 135
container[8].value= 255


container[9].bin= 3
container[9].i= 121
container[9].j= 227
container[9].angle= 18
container[9].value= 255


container[10].bin= 32
container[10].i= 121
container[10].j= 229
container[10].angle= 161
container[10].value= 255


container[11].bin= 0
container[11].i= 122
container[11].j= 218
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 122
container[12].j= 223
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 122
container[13].j= 227
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 122
container[14].j= 229
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 123
container[15].j= 219
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 123
container[16].j= 220
container[16].angle= 270
container[16].value= 255


container[17].bin= 27
container[17].i= 123
container[17].j= 224
container[17].angle= 135
container[17].value= 255


container[18].bin= 18
container[18].i= 123
container[18].j= 225
container[18].angle= 90
container[18].value= 255


container[19].bin= 18
container[19].i= 123
container[19].j= 226
container[19].angle= 90
container[19].value= 255


container[20].bin= 8
container[20].i= 123
container[20].j= 227
container[20].angle= 44
container[20].value= 255


container[21].bin= 18
container[21].i= 123
container[21].j= 228
container[21].angle= 90
container[21].value= 255


container[22].bin= 27
container[22].i= 123
container[22].j= 229
container[22].angle= 135
container[22].value= 255


container[23].bin= 18
container[23].i= 123
container[23].j= 230
container[23].angle= 90
container[23].value= 255


container[24].bin= 63
container[24].i= 124
container[24].j= 221
container[24].angle= 315
container[24].value= 255


container[25].bin= 27
container[25].i= 124
container[25].j= 231
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 125
container[26].j= 221
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 125
container[27].j= 231
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 126
container[28].j= 221
container[28].angle= 0
container[28].value= 255


container[29].bin= 27
container[29].i= 126
container[29].j= 232
container[29].angle= 135
container[29].value= 255


container[30].bin= 18
container[30].i= 126
container[30].j= 233
container[30].angle= 90
container[30].value= 255


container[31].bin= 0
container[31].i= 127
container[31].j= 221
container[31].angle= 0
container[31].value= 255


container[32].bin= 27
container[32].i= 127
container[32].j= 234
container[32].angle= 135
container[32].value= 255


container[33].bin= 0
container[33].i= 128
container[33].j= 221
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 128
container[34].j= 234
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 129
container[35].j= 222
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 129
container[36].j= 235
container[36].angle= 135
container[36].value= 255


container[37].bin= 63
container[37].i= 130
container[37].j= 223
container[37].angle= 315
container[37].value= 255


container[38].bin= 27
container[38].i= 130
container[38].j= 236
container[38].angle= 135
container[38].value= 255


container[39].bin= 0
container[39].i= 131
container[39].j= 223
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 131
container[40].j= 236
container[40].angle= 180
container[40].value= 255


container[41].bin= 66
container[41].i= 132
container[41].j= 224
container[41].angle= 333
container[41].value= 255


container[42].bin= 27
container[42].i= 132
container[42].j= 237
container[42].angle= 135
container[42].value= 255


container[43].bin= 66
container[43].i= 133
container[43].j= 224
container[43].angle= 333
container[43].value= 255


container[44].bin= 27
container[44].i= 133
container[44].j= 238
container[44].angle= 135
container[44].value= 255


container[45].bin= 0
container[45].i= 134
container[45].j= 224
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 134
container[46].j= 238
container[46].angle= 180
container[46].value= 255


container[47].bin= 63
container[47].i= 135
container[47].j= 225
container[47].angle= 315
container[47].value= 255


container[48].bin= 30
container[48].i= 135
container[48].j= 239
container[48].angle= 153
container[48].value= 255


container[49].bin= 63
container[49].i= 136
container[49].j= 226
container[49].angle= 315
container[49].value= 255


container[50].bin= 30
container[50].i= 136
container[50].j= 239
container[50].angle= 153
container[50].value= 255


container[51].bin= 0
container[51].i= 137
container[51].j= 226
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 137
container[52].j= 239
container[52].angle= 180
container[52].value= 255


container[53].bin= 66
container[53].i= 138
container[53].j= 227
container[53].angle= 333
container[53].value= 255


container[54].bin= 30
container[54].i= 138
container[54].j= 240
container[54].angle= 153
container[54].value= 255


container[55].bin= 66
container[55].i= 139
container[55].j= 227
container[55].angle= 333
container[55].value= 255


container[56].bin= 27
container[56].i= 139
container[56].j= 240
container[56].angle= 135
container[56].value= 255


container[57].bin= 27
container[57].i= 139
container[57].j= 241
container[57].angle= 135
container[57].value= 255


container[58].bin= 0
container[58].i= 140
container[58].j= 227
container[58].angle= 0
container[58].value= 255


container[59].bin= 30
container[59].i= 140
container[59].j= 241
container[59].angle= 153
container[59].value= 255


container[60].bin= 63
container[60].i= 141
container[60].j= 228
container[60].angle= 315
container[60].value= 255


container[61].bin= 54
container[61].i= 141
container[61].j= 229
container[61].angle= 270
container[61].value= 255


container[62].bin= 54
container[62].i= 141
container[62].j= 230
container[62].angle= 270
container[62].value= 255


container[63].bin= 36
container[63].i= 141
container[63].j= 241
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 142
container[64].j= 231
container[64].angle= 315
container[64].value= 255


container[65].bin= 36
container[65].i= 142
container[65].j= 241
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 143
container[66].j= 231
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 143
container[67].j= 241
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 144
container[68].j= 232
container[68].angle= 315
container[68].value= 255


container[69].bin= 54
container[69].i= 144
container[69].j= 233
container[69].angle= 270
container[69].value= 255


container[70].bin= 36
container[70].i= 144
container[70].j= 241
container[70].angle= 180
container[70].value= 255


container[71].bin= 63
container[71].i= 145
container[71].j= 234
container[71].angle= 315
container[71].value= 255


container[72].bin= 30
container[72].i= 145
container[72].j= 242
container[72].angle= 153
container[72].value= 255


container[73].bin= 0
container[73].i= 146
container[73].j= 234
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 146
container[74].j= 242
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 147
container[75].j= 234
container[75].angle= 0
container[75].value= 255


container[76].bin= 41
container[76].i= 147
container[76].j= 242
container[76].angle= 206
container[76].value= 255


container[77].bin= 0
container[77].i= 148
container[77].j= 234
container[77].angle= 0
container[77].value= 255


container[78].bin= 44
container[78].i= 148
container[78].j= 239
container[78].angle= 224
container[78].value= 255


container[79].bin= 63
container[79].i= 148
container[79].j= 240
container[79].angle= 315
container[79].value= 255


container[80].bin= 36
container[80].i= 148
container[80].j= 242
container[80].angle= 180
container[80].value= 255


container[81].bin= 0
container[81].i= 149
container[81].j= 234
container[81].angle= 0
container[81].value= 255


container[82].bin= 36
container[82].i= 149
container[82].j= 238
container[82].angle= 180
container[82].value= 255


container[83].bin= 36
container[83].i= 149
container[83].j= 242
container[83].angle= 180
container[83].value= 255


container[84].bin= 0
container[84].i= 150
container[84].j= 234
container[84].angle= 0
container[84].value= 255


container[85].bin= 44
container[85].i= 150
container[85].j= 238
container[85].angle= 224
container[85].value= 255


container[86].bin= 54
container[86].i= 150
container[86].j= 241
container[86].angle= 270
container[86].value= 255


container[87].bin= 39
container[87].i= 150
container[87].j= 242
container[87].angle= 198
container[87].value= 255


container[88].bin= 0
container[88].i= 151
container[88].j= 234
container[88].angle= 0
container[88].value= 255


container[89].bin= 44
container[89].i= 151
container[89].j= 237
container[89].angle= 224
container[89].value= 255


container[90].bin= 66
container[90].i= 152
container[90].j= 235
container[90].angle= 333
container[90].value= 255


container[91].bin= 63
container[91].i= 153
container[91].j= 235
container[91].angle= 315
container[91].value= 255


