container[0].bin= 18
container[0].i= 375
container[0].j= 610
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 375
container[1].j= 611
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 376
container[2].j= 609
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 376
container[3].j= 612
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 377
container[4].j= 608
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 377
container[5].j= 612
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 378
container[6].j= 608
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 378
container[7].j= 612
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 379
container[8].j= 608
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 379
container[9].j= 613
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 380
container[10].j= 608
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 380
container[11].j= 613
container[11].angle= 153
container[11].value= 255


container[12].bin= 8
container[12].i= 381
container[12].j= 608
container[12].angle= 44
container[12].value= 255


container[13].bin= 27
container[13].i= 381
container[13].j= 614
container[13].angle= 135
container[13].value= 255


container[14].bin= 8
container[14].i= 382
container[14].j= 607
container[14].angle= 44
container[14].value= 255


container[15].bin= 27
container[15].i= 382
container[15].j= 615
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 383
container[16].j= 606
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 383
container[17].j= 615
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 384
container[18].j= 607
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 384
container[19].j= 608
container[19].angle= 270
container[19].value= 255


container[20].bin= 36
container[20].i= 384
container[20].j= 615
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 385
container[21].j= 609
container[21].angle= 315
container[21].value= 255


container[22].bin= 36
container[22].i= 385
container[22].j= 615
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 386
container[23].j= 609
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 386
container[24].j= 615
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 387
container[25].j= 609
container[25].angle= 0
container[25].value= 255


container[26].bin= 54
container[26].i= 387
container[26].j= 612
container[26].angle= 270
container[26].value= 255


container[27].bin= 54
container[27].i= 387
container[27].j= 613
container[27].angle= 270
container[27].value= 255


container[28].bin= 27
container[28].i= 387
container[28].j= 616
container[28].angle= 135
container[28].value= 255


container[29].bin= 18
container[29].i= 387
container[29].j= 617
container[29].angle= 90
container[29].value= 255


container[30].bin= 0
container[30].i= 388
container[30].j= 609
container[30].angle= 0
container[30].value= 255


container[31].bin= 44
container[31].i= 388
container[31].j= 611
container[31].angle= 224
container[31].value= 255


container[32].bin= 63
container[32].i= 388
container[32].j= 614
container[32].angle= 315
container[32].value= 255


container[33].bin= 23
container[33].i= 388
container[33].j= 618
container[33].angle= 116
container[33].value= 255


container[34].bin= 23
container[34].i= 388
container[34].j= 619
container[34].angle= 116
container[34].value= 255


container[35].bin= 21
container[35].i= 388
container[35].j= 620
container[35].angle= 108
container[35].value= 255


container[36].bin= 0
container[36].i= 389
container[36].j= 609
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 389
container[37].j= 611
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 389
container[38].j= 614
container[38].angle= 0
container[38].value= 255


container[39].bin= 68
container[39].i= 390
container[39].j= 609
container[39].angle= 341
container[39].value= 255


container[40].bin= 54
container[40].i= 390
container[40].j= 610
container[40].angle= 270
container[40].value= 255


container[41].bin= 39
container[41].i= 390
container[41].j= 611
container[41].angle= 198
container[41].value= 255


container[42].bin= 0
container[42].i= 390
container[42].j= 614
container[42].angle= 0
container[42].value= 255


container[43].bin= 32
container[43].i= 390
container[43].j= 620
container[43].angle= 161
container[43].value= 255


container[44].bin= 0
container[44].i= 391
container[44].j= 614
container[44].angle= 0
container[44].value= 255


container[45].bin= 27
container[45].i= 391
container[45].j= 621
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 392
container[46].j= 614
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 392
container[47].j= 621
container[47].angle= 180
container[47].value= 255


container[48].bin= 63
container[48].i= 393
container[48].j= 615
container[48].angle= 315
container[48].value= 255


container[49].bin= 27
container[49].i= 393
container[49].j= 622
container[49].angle= 135
container[49].value= 255


container[50].bin= 18
container[50].i= 393
container[50].j= 623
container[50].angle= 90
container[50].value= 255


container[51].bin= 63
container[51].i= 394
container[51].j= 616
container[51].angle= 315
container[51].value= 255


container[52].bin= 27
container[52].i= 394
container[52].j= 624
container[52].angle= 135
container[52].value= 255


container[53].bin= 0
container[53].i= 395
container[53].j= 616
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 395
container[54].j= 624
container[54].angle= 180
container[54].value= 255


container[55].bin= 66
container[55].i= 396
container[55].j= 617
container[55].angle= 333
container[55].value= 255


container[56].bin= 36
container[56].i= 396
container[56].j= 624
container[56].angle= 180
container[56].value= 255


container[57].bin= 66
container[57].i= 397
container[57].j= 617
container[57].angle= 333
container[57].value= 255


container[58].bin= 36
container[58].i= 397
container[58].j= 624
container[58].angle= 180
container[58].value= 255


container[59].bin= 0
container[59].i= 398
container[59].j= 617
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 398
container[60].j= 624
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 399
container[61].j= 618
container[61].angle= 315
container[61].value= 255


container[62].bin= 36
container[62].i= 399
container[62].j= 624
container[62].angle= 180
container[62].value= 255


container[63].bin= 63
container[63].i= 400
container[63].j= 619
container[63].angle= 315
container[63].value= 255


container[64].bin= 54
container[64].i= 400
container[64].j= 622
container[64].angle= 270
container[64].value= 255


container[65].bin= 54
container[65].i= 400
container[65].j= 623
container[65].angle= 270
container[65].value= 255


container[66].bin= 41
container[66].i= 400
container[66].j= 624
container[66].angle= 206
container[66].value= 255


container[67].bin= 0
container[67].i= 401
container[67].j= 619
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 401
container[68].j= 624
container[68].angle= 180
container[68].value= 255


container[69].bin= 63
container[69].i= 402
container[69].j= 620
container[69].angle= 315
container[69].value= 255


container[70].bin= 50
container[70].i= 402
container[70].j= 621
container[70].angle= 251
container[70].value= 255


container[71].bin= 30
container[71].i= 402
container[71].j= 624
container[71].angle= 153
container[71].value= 255


container[72].bin= 63
container[72].i= 403
container[72].j= 622
container[72].angle= 315
container[72].value= 255


container[73].bin= 0
container[73].i= 404
container[73].j= 622
container[73].angle= 0
container[73].value= 255


container[74].bin= 63
container[74].i= 405
container[74].j= 623
container[74].angle= 315
container[74].value= 255


container[75].bin= 44
container[75].i= 405
container[75].j= 624
container[75].angle= 224
container[75].value= 255


