container[0].bin= 14
container[0].i= 113
container[0].j= 167
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 113
container[1].j= 168
container[1].angle= 90
container[1].value= 255


container[2].bin= 21
container[2].i= 113
container[2].j= 169
container[2].angle= 108
container[2].value= 255


container[3].bin= 0
container[3].i= 114
container[3].j= 166
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 114
container[4].j= 169
container[4].angle= 180
container[4].value= 255


container[5].bin= 57
container[5].i= 115
container[5].j= 167
container[5].angle= 288
container[5].value= 255


container[6].bin= 54
container[6].i= 115
container[6].j= 168
container[6].angle= 270
container[6].value= 255


container[7].bin= 50
container[7].i= 115
container[7].j= 169
container[7].angle= 251
container[7].value= 255


