container[0].bin= 0
container[0].i= 0
container[0].j= 215
container[0].angle= 0
container[0].value= 255


container[1].bin= 36
container[1].i= 0
container[1].j= 220
container[1].angle= 180
container[1].value= 255


container[2].bin= 0
container[2].i= 1
container[2].j= 215
container[2].angle= 0
container[2].value= 255


container[3].bin= 36
container[3].i= 1
container[3].j= 220
container[3].angle= 180
container[3].value= 255


container[4].bin= 0
container[4].i= 2
container[4].j= 215
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 2
container[5].j= 221
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 3
container[6].j= 215
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 3
container[7].j= 221
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 4
container[8].j= 216
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 4
container[9].j= 222
container[9].angle= 153
container[9].value= 255


container[10].bin= 63
container[10].i= 5
container[10].j= 216
container[10].angle= 315
container[10].value= 255


container[11].bin= 59
container[11].i= 5
container[11].j= 217
container[11].angle= 296
container[11].value= 255


container[12].bin= 30
container[12].i= 5
container[12].j= 222
container[12].angle= 153
container[12].value= 255


container[13].bin= 59
container[13].i= 6
container[13].j= 218
container[13].angle= 296
container[13].value= 255


container[14].bin= 59
container[14].i= 6
container[14].j= 219
container[14].angle= 296
container[14].value= 255


container[15].bin= 41
container[15].i= 6
container[15].j= 222
container[15].angle= 206
container[15].value= 255


container[16].bin= 59
container[16].i= 7
container[16].j= 220
container[16].angle= 296
container[16].value= 255


container[17].bin= 54
container[17].i= 7
container[17].j= 221
container[17].angle= 270
container[17].value= 255


container[18].bin= 44
container[18].i= 7
container[18].j= 222
container[18].angle= 224
container[18].value= 255


