container[0].bin= 18
container[0].i= 138
container[0].j= 387
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 139
container[1].j= 386
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 139
container[2].j= 388
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 140
container[3].j= 385
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 140
container[4].j= 388
container[4].angle= 180
container[4].value= 255


container[5].bin= 66
container[5].i= 141
container[5].j= 386
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 141
container[6].j= 389
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 141
container[7].j= 390
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 141
container[8].j= 391
container[8].angle= 90
container[8].value= 255


container[9].bin= 66
container[9].i= 142
container[9].j= 386
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 142
container[10].j= 392
container[10].angle= 135
container[10].value= 255


container[11].bin= 5
container[11].i= 143
container[11].j= 386
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 143
container[12].j= 392
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 144
container[13].j= 386
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 144
container[14].j= 393
container[14].angle= 135
container[14].value= 255


container[15].bin= 66
container[15].i= 145
container[15].j= 386
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 145
container[16].j= 394
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 146
container[17].j= 386
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 146
container[18].j= 395
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 147
container[19].j= 386
container[19].angle= 0
container[19].value= 255


container[20].bin= 27
container[20].i= 147
container[20].j= 395
container[20].angle= 135
container[20].value= 255


container[21].bin= 23
container[21].i= 147
container[21].j= 396
container[21].angle= 116
container[21].value= 255


container[22].bin= 0
container[22].i= 148
container[22].j= 386
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 148
container[23].j= 397
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 149
container[24].j= 386
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 149
container[25].j= 397
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 150
container[26].j= 387
container[26].angle= 315
container[26].value= 255


container[27].bin= 30
container[27].i= 150
container[27].j= 398
container[27].angle= 153
container[27].value= 255


container[28].bin= 63
container[28].i= 151
container[28].j= 388
container[28].angle= 315
container[28].value= 255


container[29].bin= 30
container[29].i= 151
container[29].j= 398
container[29].angle= 153
container[29].value= 255


container[30].bin= 0
container[30].i= 152
container[30].j= 388
container[30].angle= 0
container[30].value= 255


container[31].bin= 30
container[31].i= 152
container[31].j= 399
container[31].angle= 153
container[31].value= 255


container[32].bin= 63
container[32].i= 153
container[32].j= 389
container[32].angle= 315
container[32].value= 255


container[33].bin= 27
container[33].i= 153
container[33].j= 399
container[33].angle= 135
container[33].value= 255


container[34].bin= 23
container[34].i= 153
container[34].j= 400
container[34].angle= 116
container[34].value= 255


container[35].bin= 18
container[35].i= 153
container[35].j= 401
container[35].angle= 90
container[35].value= 255


container[36].bin= 18
container[36].i= 153
container[36].j= 402
container[36].angle= 90
container[36].value= 255


container[37].bin= 59
container[37].i= 154
container[37].j= 390
container[37].angle= 296
container[37].value= 255


container[38].bin= 63
container[38].i= 154
container[38].j= 391
container[38].angle= 315
container[38].value= 255


container[39].bin= 27
container[39].i= 154
container[39].j= 403
container[39].angle= 135
container[39].value= 255


container[40].bin= 66
container[40].i= 155
container[40].j= 391
container[40].angle= 333
container[40].value= 255


container[41].bin= 36
container[41].i= 155
container[41].j= 403
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 156
container[42].j= 391
container[42].angle= 0
container[42].value= 255


container[43].bin= 30
container[43].i= 156
container[43].j= 404
container[43].angle= 153
container[43].value= 255


container[44].bin= 68
container[44].i= 157
container[44].j= 391
container[44].angle= 341
container[44].value= 255


container[45].bin= 57
container[45].i= 157
container[45].j= 393
container[45].angle= 288
container[45].value= 255


container[46].bin= 36
container[46].i= 157
container[46].j= 404
container[46].angle= 180
container[46].value= 255


container[47].bin= 68
container[47].i= 158
container[47].j= 393
container[47].angle= 341
container[47].value= 255


container[48].bin= 36
container[48].i= 158
container[48].j= 404
container[48].angle= 180
container[48].value= 255


container[49].bin= 0
container[49].i= 159
container[49].j= 393
container[49].angle= 0
container[49].value= 255


container[50].bin= 27
container[50].i= 159
container[50].j= 404
container[50].angle= 135
container[50].value= 255


container[51].bin= 27
container[51].i= 159
container[51].j= 405
container[51].angle= 135
container[51].value= 255


container[52].bin= 0
container[52].i= 160
container[52].j= 393
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 160
container[53].j= 405
container[53].angle= 153
container[53].value= 255


container[54].bin= 66
container[54].i= 161
container[54].j= 394
container[54].angle= 333
container[54].value= 255


container[55].bin= 36
container[55].i= 161
container[55].j= 405
container[55].angle= 180
container[55].value= 255


container[56].bin= 63
container[56].i= 162
container[56].j= 394
container[56].angle= 315
container[56].value= 255


container[57].bin= 59
container[57].i= 162
container[57].j= 395
container[57].angle= 296
container[57].value= 255


container[58].bin= 30
container[58].i= 162
container[58].j= 406
container[58].angle= 153
container[58].value= 255


container[59].bin= 63
container[59].i= 163
container[59].j= 396
container[59].angle= 315
container[59].value= 255


container[60].bin= 30
container[60].i= 163
container[60].j= 406
container[60].angle= 153
container[60].value= 255


container[61].bin= 63
container[61].i= 164
container[61].j= 397
container[61].angle= 315
container[61].value= 255


container[62].bin= 36
container[62].i= 164
container[62].j= 406
container[62].angle= 180
container[62].value= 255


container[63].bin= 63
container[63].i= 165
container[63].j= 398
container[63].angle= 315
container[63].value= 255


container[64].bin= 36
container[64].i= 165
container[64].j= 406
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 166
container[65].j= 398
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 166
container[66].j= 406
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 167
container[67].j= 398
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 167
container[68].j= 406
container[68].angle= 180
container[68].value= 255


container[69].bin= 66
container[69].i= 168
container[69].j= 399
container[69].angle= 333
container[69].value= 255


container[70].bin= 36
container[70].i= 168
container[70].j= 406
container[70].angle= 180
container[70].value= 255


container[71].bin= 66
container[71].i= 169
container[71].j= 399
container[71].angle= 333
container[71].value= 255


container[72].bin= 36
container[72].i= 169
container[72].j= 406
container[72].angle= 180
container[72].value= 255


container[73].bin= 0
container[73].i= 170
container[73].j= 399
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 170
container[74].j= 406
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 171
container[75].j= 399
container[75].angle= 0
container[75].value= 255


container[76].bin= 36
container[76].i= 171
container[76].j= 406
container[76].angle= 180
container[76].value= 255


container[77].bin= 0
container[77].i= 172
container[77].j= 399
container[77].angle= 0
container[77].value= 255


container[78].bin= 36
container[78].i= 172
container[78].j= 406
container[78].angle= 180
container[78].value= 255


container[79].bin= 0
container[79].i= 173
container[79].j= 399
container[79].angle= 0
container[79].value= 255


container[80].bin= 36
container[80].i= 173
container[80].j= 406
container[80].angle= 180
container[80].value= 255


container[81].bin= 63
container[81].i= 174
container[81].j= 400
container[81].angle= 315
container[81].value= 255


container[82].bin= 41
container[82].i= 174
container[82].j= 406
container[82].angle= 206
container[82].value= 255


container[83].bin= 59
container[83].i= 175
container[83].j= 401
container[83].angle= 296
container[83].value= 255


container[84].bin= 63
container[84].i= 175
container[84].j= 402
container[84].angle= 315
container[84].value= 255


container[85].bin= 41
container[85].i= 175
container[85].j= 406
container[85].angle= 206
container[85].value= 255


container[86].bin= 66
container[86].i= 176
container[86].j= 402
container[86].angle= 333
container[86].value= 255


container[87].bin= 36
container[87].i= 176
container[87].j= 405
container[87].angle= 180
container[87].value= 255


container[88].bin= 63
container[88].i= 177
container[88].j= 403
container[88].angle= 315
container[88].value= 255


container[89].bin= 54
container[89].i= 177
container[89].j= 404
container[89].angle= 270
container[89].value= 255


container[90].bin= 44
container[90].i= 177
container[90].j= 405
container[90].angle= 224
container[90].value= 255


