container[0].bin= 18
container[0].i= 721
container[0].j= 456
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 722
container[1].j= 452
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 722
container[2].j= 453
container[2].angle= 135
container[2].value= 255


container[3].bin= 32
container[3].i= 722
container[3].j= 457
container[3].angle= 161
container[3].value= 255


container[4].bin= 0
container[4].i= 723
container[4].j= 451
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 723
container[5].j= 457
container[5].angle= 180
container[5].value= 255


container[6].bin= 66
container[6].i= 724
container[6].j= 452
container[6].angle= 333
container[6].value= 255


container[7].bin= 27
container[7].i= 724
container[7].j= 454
container[7].angle= 135
container[7].value= 255


container[8].bin= 8
container[8].i= 724
container[8].j= 455
container[8].angle= 44
container[8].value= 255


container[9].bin= 18
container[9].i= 724
container[9].j= 456
container[9].angle= 90
container[9].value= 255


container[10].bin= 27
container[10].i= 724
container[10].j= 457
container[10].angle= 135
container[10].value= 255


container[11].bin= 66
container[11].i= 725
container[11].j= 452
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 725
container[12].j= 458
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 726
container[13].j= 452
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 726
container[14].j= 458
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 727
container[15].j= 452
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 727
container[16].j= 458
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 728
container[17].j= 452
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 728
container[18].j= 458
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 729
container[19].j= 452
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 729
container[20].j= 458
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 730
container[21].j= 452
container[21].angle= 0
container[21].value= 255


container[22].bin= 44
container[22].i= 730
container[22].j= 458
container[22].angle= 224
container[22].value= 255


container[23].bin= 0
container[23].i= 731
container[23].j= 452
container[23].angle= 0
container[23].value= 255


container[24].bin= 44
container[24].i= 731
container[24].j= 457
container[24].angle= 224
container[24].value= 255


container[25].bin= 0
container[25].i= 732
container[25].j= 452
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 732
container[26].j= 456
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 733
container[27].j= 453
container[27].angle= 315
container[27].value= 255


container[28].bin= 36
container[28].i= 733
container[28].j= 456
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 734
container[29].j= 454
container[29].angle= 315
container[29].value= 255


container[30].bin= 0
container[30].i= 735
container[30].j= 454
container[30].angle= 0
container[30].value= 255


container[31].bin= 0
container[31].i= 736
container[31].j= 454
container[31].angle= 0
container[31].value= 255


container[32].bin= 0
container[32].i= 737
container[32].j= 454
container[32].angle= 0
container[32].value= 255


container[33].bin= 0
container[33].i= 738
container[33].j= 454
container[33].angle= 0
container[33].value= 255


container[34].bin= 63
container[34].i= 739
container[34].j= 455
container[34].angle= 315
container[34].value= 255


container[35].bin= 44
container[35].i= 739
container[35].j= 456
container[35].angle= 224
container[35].value= 255


