container[0].bin= 8
container[0].i= 427
container[0].j= 511
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 427
container[1].j= 512
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 428
container[2].j= 510
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 429
container[3].j= 510
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 429
container[4].j= 513
container[4].angle= 135
container[4].value= 255


container[5].bin= 18
container[5].i= 429
container[5].j= 514
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 430
container[6].j= 510
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 430
container[7].j= 515
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 431
container[8].j= 510
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 431
container[9].j= 515
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 432
container[10].j= 510
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 432
container[11].j= 515
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 433
container[12].j= 510
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 433
container[13].j= 515
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 434
container[14].j= 510
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 434
container[15].j= 515
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 435
container[16].j= 510
container[16].angle= 0
container[16].value= 255


container[17].bin= 54
container[17].i= 435
container[17].j= 514
container[17].angle= 270
container[17].value= 255


container[18].bin= 44
container[18].i= 435
container[18].j= 515
container[18].angle= 224
container[18].value= 255


container[19].bin= 0
container[19].i= 436
container[19].j= 510
container[19].angle= 0
container[19].value= 255


container[20].bin= 44
container[20].i= 436
container[20].j= 513
container[20].angle= 224
container[20].value= 255


container[21].bin= 0
container[21].i= 437
container[21].j= 510
container[21].angle= 0
container[21].value= 255


container[22].bin= 0
container[22].i= 438
container[22].j= 510
container[22].angle= 0
container[22].value= 255


container[23].bin= 0
container[23].i= 439
container[23].j= 510
container[23].angle= 0
container[23].value= 255


container[24].bin= 66
container[24].i= 440
container[24].j= 511
container[24].angle= 333
container[24].value= 255


container[25].bin= 63
container[25].i= 441
container[25].j= 511
container[25].angle= 315
container[25].value= 255


