container[0].bin= 18
container[0].i= 561
container[0].j= 212
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 562
container[1].j= 211
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 562
container[2].j= 213
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 563
container[3].j= 211
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 563
container[4].j= 213
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 564
container[5].j= 211
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 564
container[6].j= 213
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 565
container[7].j= 211
container[7].angle= 26
container[7].value= 255


container[8].bin= 0
container[8].i= 566
container[8].j= 210
container[8].angle= 0
container[8].value= 255


container[9].bin= 66
container[9].i= 567
container[9].j= 211
container[9].angle= 333
container[9].value= 255


container[10].bin= 66
container[10].i= 568
container[10].j= 211
container[10].angle= 333
container[10].value= 255


container[11].bin= 36
container[11].i= 568
container[11].j= 213
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 569
container[12].j= 211
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 569
container[13].j= 213
container[13].angle= 180
container[13].value= 255


container[14].bin= 68
container[14].i= 570
container[14].j= 211
container[14].angle= 341
container[14].value= 255


container[15].bin= 54
container[15].i= 570
container[15].j= 212
container[15].angle= 270
container[15].value= 255


container[16].bin= 39
container[16].i= 570
container[16].j= 213
container[16].angle= 198
container[16].value= 255


