container[0].bin= 18
container[0].i= 93
container[0].j= 313
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 94
container[1].j= 312
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 94
container[2].j= 314
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 95
container[3].j= 312
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 95
container[4].j= 314
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 96
container[5].j= 312
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 96
container[6].j= 313
container[6].angle= 90
container[6].value= 255


container[7].bin= 27
container[7].i= 96
container[7].j= 314
container[7].angle= 135
container[7].value= 255


container[8].bin= 5
container[8].i= 97
container[8].j= 312
container[8].angle= 26
container[8].value= 255


container[9].bin= 27
container[9].i= 97
container[9].j= 315
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 98
container[10].j= 311
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 98
container[11].j= 315
container[11].angle= 180
container[11].value= 255


container[12].bin= 66
container[12].i= 99
container[12].j= 312
container[12].angle= 333
container[12].value= 255


container[13].bin= 36
container[13].i= 99
container[13].j= 315
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 100
container[14].j= 312
container[14].angle= 333
container[14].value= 255


container[15].bin= 30
container[15].i= 100
container[15].j= 316
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 101
container[16].j= 312
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 101
container[17].j= 316
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 102
container[18].j= 313
container[18].angle= 315
container[18].value= 255


container[19].bin= 41
container[19].i= 102
container[19].j= 316
container[19].angle= 206
container[19].value= 255


container[20].bin= 63
container[20].i= 103
container[20].j= 314
container[20].angle= 315
container[20].value= 255


container[21].bin= 36
container[21].i= 103
container[21].j= 316
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 104
container[22].j= 314
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 104
container[23].j= 316
container[23].angle= 180
container[23].value= 255


container[24].bin= 68
container[24].i= 105
container[24].j= 314
container[24].angle= 341
container[24].value= 255


container[25].bin= 54
container[25].i= 105
container[25].j= 315
container[25].angle= 270
container[25].value= 255


container[26].bin= 39
container[26].i= 105
container[26].j= 316
container[26].angle= 198
container[26].value= 255


