container[0].bin= 18
container[0].i= 291
container[0].j= 180
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 292
container[1].j= 179
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 292
container[2].j= 181
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 293
container[3].j= 178
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 293
container[4].j= 181
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 294
container[5].j= 178
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 294
container[6].j= 181
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 295
container[7].j= 178
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 295
container[8].j= 181
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 296
container[9].j= 178
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 296
container[10].j= 181
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 297
container[11].j= 178
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 297
container[12].j= 182
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 298
container[13].j= 178
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 298
container[14].j= 183
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 299
container[15].j= 178
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 299
container[16].j= 183
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 300
container[17].j= 179
container[17].angle= 315
container[17].value= 255


container[18].bin= 54
container[18].i= 300
container[18].j= 180
container[18].angle= 270
container[18].value= 255


container[19].bin= 54
container[19].i= 300
container[19].j= 181
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 300
container[20].j= 182
container[20].angle= 270
container[20].value= 255


container[21].bin= 44
container[21].i= 300
container[21].j= 183
container[21].angle= 224
container[21].value= 255


