container[0].bin= 18
container[0].i= 522
container[0].j= 522
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 523
container[1].j= 521
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 523
container[2].j= 523
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 524
container[3].j= 521
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 524
container[4].j= 523
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 525
container[5].j= 521
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 525
container[6].j= 522
container[6].angle= 90
container[6].value= 255


container[7].bin= 30
container[7].i= 525
container[7].j= 523
container[7].angle= 153
container[7].value= 255


container[8].bin= 5
container[8].i= 526
container[8].j= 521
container[8].angle= 26
container[8].value= 255


container[9].bin= 30
container[9].i= 526
container[9].j= 523
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 527
container[10].j= 520
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 527
container[11].j= 523
container[11].angle= 180
container[11].value= 255


container[12].bin= 8
container[12].i= 528
container[12].j= 520
container[12].angle= 44
container[12].value= 255


container[13].bin= 36
container[13].i= 528
container[13].j= 523
container[13].angle= 180
container[13].value= 255


container[14].bin= 8
container[14].i= 529
container[14].j= 519
container[14].angle= 44
container[14].value= 255


container[15].bin= 36
container[15].i= 529
container[15].j= 523
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 530
container[16].j= 518
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 530
container[17].j= 523
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 531
container[18].j= 519
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 531
container[19].j= 520
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 531
container[20].j= 521
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 531
container[21].j= 522
container[21].angle= 270
container[21].value= 255


container[22].bin= 44
container[22].i= 531
container[22].j= 523
container[22].angle= 224
container[22].value= 255


