container[0].bin= 14
container[0].i= 321
container[0].j= 381
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 321
container[1].j= 382
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 321
container[2].j= 383
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 321
container[3].j= 384
container[3].angle= 90
container[3].value= 255


container[4].bin= 3
container[4].i= 322
container[4].j= 381
container[4].angle= 18
container[4].value= 255


container[5].bin= 27
container[5].i= 322
container[5].j= 385
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 323
container[6].j= 381
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 323
container[7].j= 385
container[7].angle= 180
container[7].value= 255


container[8].bin= 68
container[8].i= 324
container[8].j= 381
container[8].angle= 341
container[8].value= 255


container[9].bin= 57
container[9].i= 324
container[9].j= 382
container[9].angle= 288
container[9].value= 255


container[10].bin= 27
container[10].i= 324
container[10].j= 386
container[10].angle= 135
container[10].value= 255


container[11].bin= 18
container[11].i= 324
container[11].j= 387
container[11].angle= 90
container[11].value= 255


container[12].bin= 18
container[12].i= 324
container[12].j= 388
container[12].angle= 90
container[12].value= 255


container[13].bin= 18
container[13].i= 324
container[13].j= 389
container[13].angle= 90
container[13].value= 255


container[14].bin= 63
container[14].i= 325
container[14].j= 383
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 325
container[15].j= 390
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 326
container[16].j= 383
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 326
container[17].j= 390
container[17].angle= 180
container[17].value= 255


container[18].bin= 68
container[18].i= 327
container[18].j= 383
container[18].angle= 341
container[18].value= 255


container[19].bin= 54
container[19].i= 327
container[19].j= 385
container[19].angle= 270
container[19].value= 255


container[20].bin= 63
container[20].i= 327
container[20].j= 386
container[20].angle= 315
container[20].value= 255


container[21].bin= 36
container[21].i= 327
container[21].j= 390
container[21].angle= 180
container[21].value= 255


container[22].bin= 66
container[22].i= 328
container[22].j= 386
container[22].angle= 333
container[22].value= 255


container[23].bin= 36
container[23].i= 328
container[23].j= 390
container[23].angle= 180
container[23].value= 255


container[24].bin= 66
container[24].i= 329
container[24].j= 387
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 329
container[25].j= 390
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 330
container[26].j= 387
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 330
container[27].j= 388
container[27].angle= 315
container[27].value= 255


container[28].bin= 36
container[28].i= 330
container[28].j= 390
container[28].angle= 180
container[28].value= 255


container[29].bin= 66
container[29].i= 331
container[29].j= 388
container[29].angle= 333
container[29].value= 255


container[30].bin= 0
container[30].i= 332
container[30].j= 388
container[30].angle= 0
container[30].value= 255


container[31].bin= 63
container[31].i= 333
container[31].j= 389
container[31].angle= 315
container[31].value= 255


container[32].bin= 44
container[32].i= 333
container[32].j= 390
container[32].angle= 224
container[32].value= 255


