container[0].bin= 8
container[0].i= 521
container[0].j= 516
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 521
container[1].j= 517
container[1].angle= 108
container[1].value= 255


container[2].bin= 68
container[2].i= 522
container[2].j= 516
container[2].angle= 341
container[2].value= 255


