container[0].bin= 8
container[0].i= 710
container[0].j= 387
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 710
container[1].j= 388
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 711
container[2].j= 386
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 712
container[3].j= 386
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 713
container[4].j= 386
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 714
container[5].j= 386
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 715
container[6].j= 386
container[6].angle= 0
container[6].value= 255


container[7].bin= 41
container[7].i= 715
container[7].j= 388
container[7].angle= 206
container[7].value= 255


container[8].bin= 0
container[8].i= 716
container[8].j= 386
container[8].angle= 0
container[8].value= 255


container[9].bin= 41
container[9].i= 716
container[9].j= 388
container[9].angle= 206
container[9].value= 255


container[10].bin= 68
container[10].i= 717
container[10].j= 386
container[10].angle= 341
container[10].value= 255


container[11].bin= 39
container[11].i= 717
container[11].j= 388
container[11].angle= 198
container[11].value= 255


