container[0].bin= 8
container[0].i= 852
container[0].j= 278
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 852
container[1].j= 279
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 853
container[2].j= 277
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 854
container[3].j= 277
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 854
container[4].j= 279
container[4].angle= 206
container[4].value= 255


container[5].bin= 0
container[5].i= 855
container[5].j= 277
container[5].angle= 0
container[5].value= 255


container[6].bin= 41
container[6].i= 855
container[6].j= 279
container[6].angle= 206
container[6].value= 255


container[7].bin= 0
container[7].i= 856
container[7].j= 277
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 856
container[8].j= 279
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 857
container[9].j= 277
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 857
container[10].j= 279
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 858
container[11].j= 277
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 858
container[12].j= 279
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 859
container[13].j= 277
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 859
container[14].j= 279
container[14].angle= 180
container[14].value= 255


container[15].bin= 5
container[15].i= 860
container[15].j= 277
container[15].angle= 26
container[15].value= 255


container[16].bin= 18
container[16].i= 860
container[16].j= 278
container[16].angle= 90
container[16].value= 255


container[17].bin= 30
container[17].i= 860
container[17].j= 279
container[17].angle= 153
container[17].value= 255


container[18].bin= 5
container[18].i= 861
container[18].j= 277
container[18].angle= 26
container[18].value= 255


container[19].bin= 30
container[19].i= 861
container[19].j= 279
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 862
container[20].j= 276
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 862
container[21].j= 279
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 863
container[22].j= 276
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 863
container[23].j= 279
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 864
container[24].j= 276
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 864
container[25].j= 279
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 865
container[26].j= 276
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 865
container[27].j= 279
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 866
container[28].j= 276
container[28].angle= 0
container[28].value= 255


container[29].bin= 27
container[29].i= 866
container[29].j= 280
container[29].angle= 135
container[29].value= 255


container[30].bin= 18
container[30].i= 866
container[30].j= 281
container[30].angle= 90
container[30].value= 255


container[31].bin= 18
container[31].i= 866
container[31].j= 282
container[31].angle= 90
container[31].value= 255


container[32].bin= 21
container[32].i= 866
container[32].j= 283
container[32].angle= 108
container[32].value= 255


container[33].bin= 0
container[33].i= 867
container[33].j= 276
container[33].angle= 0
container[33].value= 255


container[34].bin= 0
container[34].i= 868
container[34].j= 276
container[34].angle= 0
container[34].value= 255


container[35].bin= 39
container[35].i= 868
container[35].j= 282
container[35].angle= 198
container[35].value= 255


container[36].bin= 66
container[36].i= 869
container[36].j= 277
container[36].angle= 333
container[36].value= 255


container[37].bin= 27
container[37].i= 869
container[37].j= 282
container[37].angle= 135
container[37].value= 255


container[38].bin= 23
container[38].i= 869
container[38].j= 283
container[38].angle= 116
container[38].value= 255


container[39].bin= 66
container[39].i= 870
container[39].j= 277
container[39].angle= 333
container[39].value= 255


container[40].bin= 27
container[40].i= 870
container[40].j= 284
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 871
container[41].j= 277
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 871
container[42].j= 284
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 872
container[43].j= 278
container[43].angle= 315
container[43].value= 255


container[44].bin= 27
container[44].i= 872
container[44].j= 285
container[44].angle= 135
container[44].value= 255


container[45].bin= 63
container[45].i= 873
container[45].j= 279
container[45].angle= 315
container[45].value= 255


container[46].bin= 27
container[46].i= 873
container[46].j= 286
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 874
container[47].j= 279
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 874
container[48].j= 286
container[48].angle= 180
container[48].value= 255


container[49].bin= 0
container[49].i= 875
container[49].j= 279
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 875
container[50].j= 286
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 876
container[51].j= 279
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 876
container[52].j= 286
container[52].angle= 180
container[52].value= 255


container[53].bin= 0
container[53].i= 877
container[53].j= 279
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 877
container[54].j= 286
container[54].angle= 180
container[54].value= 255


container[55].bin= 66
container[55].i= 878
container[55].j= 280
container[55].angle= 333
container[55].value= 255


container[56].bin= 36
container[56].i= 878
container[56].j= 286
container[56].angle= 180
container[56].value= 255


container[57].bin= 66
container[57].i= 879
container[57].j= 280
container[57].angle= 333
container[57].value= 255


container[58].bin= 36
container[58].i= 879
container[58].j= 286
container[58].angle= 180
container[58].value= 255


container[59].bin= 0
container[59].i= 880
container[59].j= 280
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 880
container[60].j= 286
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 881
container[61].j= 280
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 881
container[62].j= 286
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 882
container[63].j= 280
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 882
container[64].j= 286
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 883
container[65].j= 280
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 883
container[66].j= 286
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 884
container[67].j= 280
container[67].angle= 0
container[67].value= 255


container[68].bin= 30
container[68].i= 884
container[68].j= 287
container[68].angle= 153
container[68].value= 255


container[69].bin= 0
container[69].i= 885
container[69].j= 280
container[69].angle= 0
container[69].value= 255


container[70].bin= 30
container[70].i= 885
container[70].j= 287
container[70].angle= 153
container[70].value= 255


container[71].bin= 0
container[71].i= 886
container[71].j= 280
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 886
container[72].j= 287
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 887
container[73].j= 281
container[73].angle= 315
container[73].value= 255


container[74].bin= 27
container[74].i= 887
container[74].j= 288
container[74].angle= 135
container[74].value= 255


container[75].bin= 18
container[75].i= 887
container[75].j= 289
container[75].angle= 90
container[75].value= 255


container[76].bin= 18
container[76].i= 887
container[76].j= 290
container[76].angle= 90
container[76].value= 255


container[77].bin= 59
container[77].i= 888
container[77].j= 282
container[77].angle= 296
container[77].value= 255


container[78].bin= 63
container[78].i= 888
container[78].j= 283
container[78].angle= 315
container[78].value= 255


container[79].bin= 27
container[79].i= 888
container[79].j= 291
container[79].angle= 135
container[79].value= 255


container[80].bin= 63
container[80].i= 889
container[80].j= 283
container[80].angle= 315
container[80].value= 255


container[81].bin= 63
container[81].i= 889
container[81].j= 284
container[81].angle= 315
container[81].value= 255


container[82].bin= 36
container[82].i= 889
container[82].j= 291
container[82].angle= 180
container[82].value= 255


container[83].bin= 66
container[83].i= 890
container[83].j= 284
container[83].angle= 333
container[83].value= 255


container[84].bin= 30
container[84].i= 890
container[84].j= 292
container[84].angle= 153
container[84].value= 255


container[85].bin= 0
container[85].i= 891
container[85].j= 284
container[85].angle= 0
container[85].value= 255


container[86].bin= 30
container[86].i= 891
container[86].j= 292
container[86].angle= 153
container[86].value= 255


container[87].bin= 0
container[87].i= 892
container[87].j= 284
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 892
container[88].j= 292
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 893
container[89].j= 285
container[89].angle= 315
container[89].value= 255


container[90].bin= 54
container[90].i= 893
container[90].j= 286
container[90].angle= 270
container[90].value= 255


container[91].bin= 27
container[91].i= 893
container[91].j= 293
container[91].angle= 135
container[91].value= 255


container[92].bin= 18
container[92].i= 893
container[92].j= 294
container[92].angle= 90
container[92].value= 255


container[93].bin= 63
container[93].i= 894
container[93].j= 287
container[93].angle= 315
container[93].value= 255


container[94].bin= 27
container[94].i= 894
container[94].j= 295
container[94].angle= 135
container[94].value= 255


container[95].bin= 0
container[95].i= 895
container[95].j= 287
container[95].angle= 0
container[95].value= 255


container[96].bin= 30
container[96].i= 895
container[96].j= 296
container[96].angle= 153
container[96].value= 255


container[97].bin= 66
container[97].i= 896
container[97].j= 288
container[97].angle= 333
container[97].value= 255


container[98].bin= 27
container[98].i= 896
container[98].j= 296
container[98].angle= 135
container[98].value= 255


container[99].bin= 23
container[99].i= 896
container[99].j= 297
container[99].angle= 116
container[99].value= 255


container[100].bin= 18
container[100].i= 896
container[100].j= 298
container[100].angle= 90
container[100].value= 255


container[101].bin= 66
container[101].i= 897
container[101].j= 288
container[101].angle= 333
container[101].value= 255


container[102].bin= 27
container[102].i= 897
container[102].j= 299
container[102].angle= 135
container[102].value= 255


container[103].bin= 0
container[103].i= 898
container[103].j= 288
container[103].angle= 0
container[103].value= 255


container[104].bin= 36
container[104].i= 898
container[104].j= 299
container[104].angle= 180
container[104].value= 255


container[105].bin= 63
container[105].i= 899
container[105].j= 289
container[105].angle= 315
container[105].value= 255


container[106].bin= 54
container[106].i= 899
container[106].j= 290
container[106].angle= 270
container[106].value= 255


container[107].bin= 54
container[107].i= 899
container[107].j= 291
container[107].angle= 270
container[107].value= 255


container[108].bin= 30
container[108].i= 899
container[108].j= 300
container[108].angle= 153
container[108].value= 255


container[109].bin= 59
container[109].i= 900
container[109].j= 292
container[109].angle= 296
container[109].value= 255


container[110].bin= 63
container[110].i= 900
container[110].j= 293
container[110].angle= 315
container[110].value= 255


container[111].bin= 30
container[111].i= 900
container[111].j= 300
container[111].angle= 153
container[111].value= 255


container[112].bin= 0
container[112].i= 901
container[112].j= 293
container[112].angle= 0
container[112].value= 255


container[113].bin= 36
container[113].i= 901
container[113].j= 300
container[113].angle= 180
container[113].value= 255


container[114].bin= 68
container[114].i= 902
container[114].j= 293
container[114].angle= 341
container[114].value= 255


container[115].bin= 57
container[115].i= 902
container[115].j= 294
container[115].angle= 288
container[115].value= 255


container[116].bin= 54
container[116].i= 902
container[116].j= 295
container[116].angle= 270
container[116].value= 255


container[117].bin= 36
container[117].i= 902
container[117].j= 300
container[117].angle= 180
container[117].value= 255


container[118].bin= 63
container[118].i= 903
container[118].j= 296
container[118].angle= 315
container[118].value= 255


container[119].bin= 36
container[119].i= 903
container[119].j= 300
container[119].angle= 180
container[119].value= 255


container[120].bin= 0
container[120].i= 904
container[120].j= 296
container[120].angle= 0
container[120].value= 255


container[121].bin= 36
container[121].i= 904
container[121].j= 300
container[121].angle= 180
container[121].value= 255


container[122].bin= 0
container[122].i= 905
container[122].j= 296
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 905
container[123].j= 300
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 906
container[124].j= 296
container[124].angle= 0
container[124].value= 255


container[125].bin= 36
container[125].i= 906
container[125].j= 300
container[125].angle= 180
container[125].value= 255


container[126].bin= 0
container[126].i= 907
container[126].j= 296
container[126].angle= 0
container[126].value= 255


container[127].bin= 36
container[127].i= 907
container[127].j= 300
container[127].angle= 180
container[127].value= 255


container[128].bin= 63
container[128].i= 908
container[128].j= 297
container[128].angle= 315
container[128].value= 255


container[129].bin= 54
container[129].i= 908
container[129].j= 299
container[129].angle= 270
container[129].value= 255


container[130].bin= 41
container[130].i= 908
container[130].j= 300
container[130].angle= 206
container[130].value= 255


container[131].bin= 63
container[131].i= 909
container[131].j= 298
container[131].angle= 315
container[131].value= 255


container[132].bin= 41
container[132].i= 909
container[132].j= 300
container[132].angle= 206
container[132].value= 255


container[133].bin= 0
container[133].i= 910
container[133].j= 298
container[133].angle= 0
container[133].value= 255


container[134].bin= 36
container[134].i= 910
container[134].j= 300
container[134].angle= 180
container[134].value= 255


container[135].bin= 68
container[135].i= 911
container[135].j= 298
container[135].angle= 341
container[135].value= 255


container[136].bin= 54
container[136].i= 911
container[136].j= 299
container[136].angle= 270
container[136].value= 255


container[137].bin= 39
container[137].i= 911
container[137].j= 300
container[137].angle= 198
container[137].value= 255


