container[0].bin= 18
container[0].i= 798
container[0].j= 299
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 799
container[1].j= 298
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 799
container[2].j= 300
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 800
container[3].j= 298
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 800
container[4].j= 300
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 801
container[5].j= 298
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 801
container[6].j= 300
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 802
container[7].j= 298
container[7].angle= 0
container[7].value= 255


container[8].bin= 63
container[8].i= 803
container[8].j= 299
container[8].angle= 315
container[8].value= 255


container[9].bin= 18
container[9].i= 803
container[9].j= 302
container[9].angle= 90
container[9].value= 255


container[10].bin= 27
container[10].i= 804
container[10].j= 303
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 805
container[11].j= 300
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 805
container[12].j= 303
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 806
container[13].j= 301
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 806
container[14].j= 303
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 807
container[15].j= 301
container[15].angle= 333
container[15].value= 255


container[16].bin= 0
container[16].i= 808
container[16].j= 301
container[16].angle= 0
container[16].value= 255


container[17].bin= 63
container[17].i= 809
container[17].j= 302
container[17].angle= 315
container[17].value= 255


container[18].bin= 44
container[18].i= 809
container[18].j= 303
container[18].angle= 224
container[18].value= 255


