container[0].bin= 18
container[0].i= 767
container[0].j= 607
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 768
container[1].j= 606
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 768
container[2].j= 608
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 769
container[3].j= 606
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 769
container[4].j= 608
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 770
container[5].j= 606
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 770
container[6].j= 608
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 771
container[7].j= 606
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 771
container[8].j= 608
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 772
container[9].j= 606
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 772
container[10].j= 608
container[10].angle= 180
container[10].value= 255


container[11].bin= 5
container[11].i= 773
container[11].j= 606
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 773
container[12].j= 608
container[12].angle= 180
container[12].value= 255


container[13].bin= 5
container[13].i= 774
container[13].j= 606
container[13].angle= 26
container[13].value= 255


container[14].bin= 0
container[14].i= 775
container[14].j= 605
container[14].angle= 0
container[14].value= 255


container[15].bin= 63
container[15].i= 776
container[15].j= 606
container[15].angle= 315
container[15].value= 255


container[16].bin= 44
container[16].i= 776
container[16].j= 607
container[16].angle= 224
container[16].value= 255


