container[0].bin= 18
container[0].i= 192
container[0].j= 229
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 192
container[1].j= 230
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 193
container[2].j= 228
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 193
container[3].j= 231
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 194
container[4].j= 227
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 194
container[5].j= 231
container[5].angle= 180
container[5].value= 255


container[6].bin= 5
container[6].i= 195
container[6].j= 227
container[6].angle= 26
container[6].value= 255


container[7].bin= 41
container[7].i= 195
container[7].j= 231
container[7].angle= 206
container[7].value= 255


container[8].bin= 5
container[8].i= 196
container[8].j= 227
container[8].angle= 26
container[8].value= 255


container[9].bin= 44
container[9].i= 196
container[9].j= 230
container[9].angle= 224
container[9].value= 255


container[10].bin= 44
container[10].i= 196
container[10].j= 231
container[10].angle= 224
container[10].value= 255


container[11].bin= 0
container[11].i= 197
container[11].j= 226
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 197
container[12].j= 230
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 198
container[13].j= 227
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 198
container[14].j= 228
container[14].angle= 270
container[14].value= 255


container[15].bin= 50
container[15].i= 198
container[15].j= 229
container[15].angle= 251
container[15].value= 255


