container[0].bin= 8
container[0].i= 556
container[0].j= 363
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 556
container[1].j= 364
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 557
container[2].j= 362
container[2].angle= 0
container[2].value= 255


container[3].bin= 63
container[3].i= 558
container[3].j= 363
container[3].angle= 315
container[3].value= 255


container[4].bin= 27
container[4].i= 559
container[4].j= 366
container[4].angle= 135
container[4].value= 255


container[5].bin= 68
container[5].i= 560
container[5].j= 364
container[5].angle= 341
container[5].value= 255


