container[0].bin= 8
container[0].i= 737
container[0].j= 466
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 737
container[1].j= 467
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 738
container[2].j= 465
container[2].angle= 0
container[2].value= 255


container[3].bin= 8
container[3].i= 739
container[3].j= 465
container[3].angle= 44
container[3].value= 255


container[4].bin= 41
container[4].i= 739
container[4].j= 467
container[4].angle= 206
container[4].value= 255


container[5].bin= 8
container[5].i= 740
container[5].j= 464
container[5].angle= 44
container[5].value= 255


container[6].bin= 41
container[6].i= 740
container[6].j= 467
container[6].angle= 206
container[6].value= 255


container[7].bin= 66
container[7].i= 741
container[7].j= 464
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 741
container[8].j= 466
container[8].angle= 180
container[8].value= 255


container[9].bin= 68
container[9].i= 742
container[9].j= 464
container[9].angle= 341
container[9].value= 255


container[10].bin= 57
container[10].i= 742
container[10].j= 465
container[10].angle= 288
container[10].value= 255


container[11].bin= 44
container[11].i= 742
container[11].j= 466
container[11].angle= 224
container[11].value= 255


container[12].bin= 3
container[12].i= 743
container[12].j= 463
container[12].angle= 18
container[12].value= 255


container[13].bin= 0
container[13].i= 744
container[13].j= 463
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 744
container[14].j= 465
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 745
container[15].j= 463
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 745
container[16].j= 465
container[16].angle= 180
container[16].value= 255


container[17].bin= 68
container[17].i= 746
container[17].j= 463
container[17].angle= 341
container[17].value= 255


container[18].bin= 54
container[18].i= 746
container[18].j= 464
container[18].angle= 270
container[18].value= 255


container[19].bin= 39
container[19].i= 746
container[19].j= 465
container[19].angle= 198
container[19].value= 255


