container[0].bin= 18
container[0].i= 794
container[0].j= 602
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 795
container[1].j= 601
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 795
container[2].j= 603
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 796
container[3].j= 601
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 796
container[4].j= 603
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 797
container[5].j= 601
container[5].angle= 341
container[5].value= 255


container[6].bin= 3
container[6].i= 798
container[6].j= 602
container[6].angle= 18
container[6].value= 255


container[7].bin= 27
container[7].i= 798
container[7].j= 604
container[7].angle= 135
container[7].value= 255


container[8].bin= 5
container[8].i= 799
container[8].j= 602
container[8].angle= 26
container[8].value= 255


container[9].bin= 36
container[9].i= 799
container[9].j= 604
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 800
container[10].j= 601
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 800
container[11].j= 605
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 801
container[12].j= 601
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 801
container[13].j= 605
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 802
container[14].j= 601
container[14].angle= 0
container[14].value= 255


container[15].bin= 41
container[15].i= 802
container[15].j= 605
container[15].angle= 206
container[15].value= 255


container[16].bin= 68
container[16].i= 803
container[16].j= 601
container[16].angle= 341
container[16].value= 255


container[17].bin= 54
container[17].i= 803
container[17].j= 603
container[17].angle= 270
container[17].value= 255


container[18].bin= 54
container[18].i= 803
container[18].j= 604
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 803
container[19].j= 605
container[19].angle= 224
container[19].value= 255


