container[0].bin= 8
container[0].i= 244
container[0].j= 350
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 244
container[1].j= 351
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 244
container[2].j= 352
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 245
container[3].j= 349
container[3].angle= 0
container[3].value= 255


container[4].bin= 68
container[4].i= 246
container[4].j= 349
container[4].angle= 341
container[4].value= 255


container[5].bin= 48
container[5].i= 246
container[5].j= 351
container[5].angle= 243
container[5].value= 255


