container[0].bin= 14
container[0].i= 890
container[0].j= 347
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 890
container[1].j= 348
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 890
container[2].j= 349
container[2].angle= 90
container[2].value= 255


container[3].bin= 21
container[3].i= 890
container[3].j= 350
container[3].angle= 108
container[3].value= 255


container[4].bin= 0
container[4].i= 891
container[4].j= 346
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 891
container[5].j= 350
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 892
container[6].j= 346
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 892
container[7].j= 349
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 892
container[8].j= 351
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 893
container[9].j= 346
container[9].angle= 0
container[9].value= 255


container[10].bin= 8
container[10].i= 893
container[10].j= 349
container[10].angle= 44
container[10].value= 255


container[11].bin= 27
container[11].i= 893
container[11].j= 351
container[11].angle= 135
container[11].value= 255


container[12].bin= 18
container[12].i= 893
container[12].j= 352
container[12].angle= 90
container[12].value= 255


container[13].bin= 18
container[13].i= 893
container[13].j= 353
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 893
container[14].j= 354
container[14].angle= 90
container[14].value= 255


container[15].bin= 57
container[15].i= 894
container[15].j= 347
container[15].angle= 288
container[15].value= 255


container[16].bin= 63
container[16].i= 894
container[16].j= 348
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 894
container[17].j= 355
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 895
container[18].j= 348
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 895
container[19].j= 355
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 896
container[20].j= 348
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 896
container[21].j= 356
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 897
container[22].j= 348
container[22].angle= 0
container[22].value= 255


container[23].bin= 30
container[23].i= 897
container[23].j= 356
container[23].angle= 153
container[23].value= 255


container[24].bin= 0
container[24].i= 898
container[24].j= 348
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 898
container[25].j= 356
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 899
container[26].j= 349
container[26].angle= 315
container[26].value= 255


container[27].bin= 54
container[27].i= 899
container[27].j= 350
container[27].angle= 270
container[27].value= 255


container[28].bin= 27
container[28].i= 899
container[28].j= 357
container[28].angle= 135
container[28].value= 255


container[29].bin= 63
container[29].i= 900
container[29].j= 351
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 900
container[30].j= 358
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 901
container[31].j= 351
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 901
container[32].j= 358
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 902
container[33].j= 352
container[33].angle= 315
container[33].value= 255


container[34].bin= 36
container[34].i= 902
container[34].j= 358
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 903
container[35].j= 353
container[35].angle= 315
container[35].value= 255


container[36].bin= 36
container[36].i= 903
container[36].j= 358
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 904
container[37].j= 353
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 904
container[38].j= 358
container[38].angle= 180
container[38].value= 255


container[39].bin= 63
container[39].i= 905
container[39].j= 354
container[39].angle= 315
container[39].value= 255


container[40].bin= 54
container[40].i= 905
container[40].j= 355
container[40].angle= 270
container[40].value= 255


container[41].bin= 54
container[41].i= 905
container[41].j= 356
container[41].angle= 270
container[41].value= 255


container[42].bin= 54
container[42].i= 905
container[42].j= 357
container[42].angle= 270
container[42].value= 255


container[43].bin= 44
container[43].i= 905
container[43].j= 358
container[43].angle= 224
container[43].value= 255


