container[0].bin= 18
container[0].i= 812
container[0].j= 517
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 813
container[1].j= 516
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 813
container[2].j= 518
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 814
container[3].j= 516
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 814
container[4].j= 518
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 815
container[5].j= 516
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 815
container[6].j= 518
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 816
container[7].j= 516
container[7].angle= 26
container[7].value= 255


container[8].bin= 0
container[8].i= 817
container[8].j= 515
container[8].angle= 0
container[8].value= 255


container[9].bin= 63
container[9].i= 818
container[9].j= 516
container[9].angle= 315
container[9].value= 255


container[10].bin= 44
container[10].i= 818
container[10].j= 517
container[10].angle= 224
container[10].value= 255


