container[0].bin= 18
container[0].i= 196
container[0].j= 0
container[0].angle= 90
container[0].value= 255


container[1].bin= 30
container[1].i= 197
container[1].j= 1
container[1].angle= 153
container[1].value= 255


container[2].bin= 27
container[2].i= 198
container[2].j= 1
container[2].angle= 135
container[2].value= 255


container[3].bin= 23
container[3].i= 198
container[3].j= 2
container[3].angle= 116
container[3].value= 255


container[4].bin= 27
container[4].i= 199
container[4].j= 3
container[4].angle= 135
container[4].value= 255


container[5].bin= 30
container[5].i= 200
container[5].j= 4
container[5].angle= 153
container[5].value= 255


container[6].bin= 30
container[6].i= 201
container[6].j= 4
container[6].angle= 153
container[6].value= 255


container[7].bin= 30
container[7].i= 202
container[7].j= 5
container[7].angle= 153
container[7].value= 255


container[8].bin= 30
container[8].i= 203
container[8].j= 5
container[8].angle= 153
container[8].value= 255


container[9].bin= 30
container[9].i= 204
container[9].j= 6
container[9].angle= 153
container[9].value= 255


container[10].bin= 30
container[10].i= 205
container[10].j= 6
container[10].angle= 153
container[10].value= 255


container[11].bin= 30
container[11].i= 206
container[11].j= 7
container[11].angle= 153
container[11].value= 255


container[12].bin= 30
container[12].i= 207
container[12].j= 7
container[12].angle= 153
container[12].value= 255


container[13].bin= 30
container[13].i= 208
container[13].j= 8
container[13].angle= 153
container[13].value= 255


container[14].bin= 27
container[14].i= 209
container[14].j= 8
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 209
container[15].j= 9
container[15].angle= 135
container[15].value= 255


container[16].bin= 30
container[16].i= 210
container[16].j= 9
container[16].angle= 153
container[16].value= 255


container[17].bin= 30
container[17].i= 211
container[17].j= 10
container[17].angle= 153
container[17].value= 255


container[18].bin= 27
container[18].i= 212
container[18].j= 10
container[18].angle= 135
container[18].value= 255


container[19].bin= 27
container[19].i= 212
container[19].j= 11
container[19].angle= 135
container[19].value= 255


container[20].bin= 30
container[20].i= 213
container[20].j= 11
container[20].angle= 153
container[20].value= 255


container[21].bin= 54
container[21].i= 214
container[21].j= 0
container[21].angle= 270
container[21].value= 255


container[22].bin= 36
container[22].i= 214
container[22].j= 11
container[22].angle= 180
container[22].value= 255


container[23].bin= 59
container[23].i= 215
container[23].j= 1
container[23].angle= 296
container[23].value= 255


container[24].bin= 63
container[24].i= 215
container[24].j= 2
container[24].angle= 315
container[24].value= 255


container[25].bin= 30
container[25].i= 215
container[25].j= 12
container[25].angle= 153
container[25].value= 255


container[26].bin= 63
container[26].i= 216
container[26].j= 2
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 216
container[27].j= 3
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 216
container[28].j= 12
container[28].angle= 153
container[28].value= 255


container[29].bin= 63
container[29].i= 217
container[29].j= 3
container[29].angle= 315
container[29].value= 255


container[30].bin= 59
container[30].i= 217
container[30].j= 4
container[30].angle= 296
container[30].value= 255


container[31].bin= 36
container[31].i= 217
container[31].j= 12
container[31].angle= 180
container[31].value= 255


container[32].bin= 59
container[32].i= 218
container[32].j= 5
container[32].angle= 296
container[32].value= 255


container[33].bin= 59
container[33].i= 218
container[33].j= 6
container[33].angle= 296
container[33].value= 255


container[34].bin= 30
container[34].i= 218
container[34].j= 13
container[34].angle= 153
container[34].value= 255


container[35].bin= 59
container[35].i= 219
container[35].j= 7
container[35].angle= 296
container[35].value= 255


container[36].bin= 63
container[36].i= 219
container[36].j= 8
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 219
container[37].j= 13
container[37].angle= 153
container[37].value= 255


container[38].bin= 63
container[38].i= 220
container[38].j= 8
container[38].angle= 315
container[38].value= 255


container[39].bin= 63
container[39].i= 220
container[39].j= 9
container[39].angle= 315
container[39].value= 255


container[40].bin= 36
container[40].i= 220
container[40].j= 13
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 221
container[41].j= 9
container[41].angle= 315
container[41].value= 255


container[42].bin= 63
container[42].i= 221
container[42].j= 10
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 221
container[43].j= 14
container[43].angle= 153
container[43].value= 255


container[44].bin= 66
container[44].i= 222
container[44].j= 10
container[44].angle= 333
container[44].value= 255


container[45].bin= 30
container[45].i= 222
container[45].j= 14
container[45].angle= 153
container[45].value= 255


container[46].bin= 66
container[46].i= 223
container[46].j= 11
container[46].angle= 333
container[46].value= 255


container[47].bin= 36
container[47].i= 223
container[47].j= 14
container[47].angle= 180
container[47].value= 255


container[48].bin= 63
container[48].i= 224
container[48].j= 11
container[48].angle= 315
container[48].value= 255


container[49].bin= 63
container[49].i= 224
container[49].j= 12
container[49].angle= 315
container[49].value= 255


container[50].bin= 36
container[50].i= 224
container[50].j= 14
container[50].angle= 180
container[50].value= 255


container[51].bin= 66
container[51].i= 225
container[51].j= 12
container[51].angle= 333
container[51].value= 255


container[52].bin= 0
container[52].i= 226
container[52].j= 12
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 226
container[53].j= 15
container[53].angle= 153
container[53].value= 255


container[54].bin= 0
container[54].i= 227
container[54].j= 12
container[54].angle= 0
container[54].value= 255


container[55].bin= 27
container[55].i= 227
container[55].j= 15
container[55].angle= 135
container[55].value= 255


container[56].bin= 27
container[56].i= 227
container[56].j= 16
container[56].angle= 135
container[56].value= 255


container[57].bin= 0
container[57].i= 228
container[57].j= 12
container[57].angle= 0
container[57].value= 255


container[58].bin= 30
container[58].i= 228
container[58].j= 16
container[58].angle= 153
container[58].value= 255


container[59].bin= 0
container[59].i= 229
container[59].j= 12
container[59].angle= 0
container[59].value= 255


container[60].bin= 27
container[60].i= 229
container[60].j= 17
container[60].angle= 135
container[60].value= 255


container[61].bin= 0
container[61].i= 230
container[61].j= 12
container[61].angle= 0
container[61].value= 255


container[62].bin= 23
container[62].i= 230
container[62].j= 18
container[62].angle= 116
container[62].value= 255


container[63].bin= 23
container[63].i= 230
container[63].j= 19
container[63].angle= 116
container[63].value= 255


container[64].bin= 66
container[64].i= 231
container[64].j= 13
container[64].angle= 333
container[64].value= 255


container[65].bin= 23
container[65].i= 231
container[65].j= 20
container[65].angle= 116
container[65].value= 255


container[66].bin= 27
container[66].i= 231
container[66].j= 21
container[66].angle= 135
container[66].value= 255


container[67].bin= 63
container[67].i= 232
container[67].j= 13
container[67].angle= 315
container[67].value= 255


container[68].bin= 63
container[68].i= 232
container[68].j= 14
container[68].angle= 315
container[68].value= 255


container[69].bin= 30
container[69].i= 232
container[69].j= 21
container[69].angle= 153
container[69].value= 255


container[70].bin= 63
container[70].i= 233
container[70].j= 14
container[70].angle= 315
container[70].value= 255


container[71].bin= 59
container[71].i= 233
container[71].j= 15
container[71].angle= 296
container[71].value= 255


container[72].bin= 30
container[72].i= 233
container[72].j= 22
container[72].angle= 153
container[72].value= 255


container[73].bin= 59
container[73].i= 234
container[73].j= 16
container[73].angle= 296
container[73].value= 255


container[74].bin= 63
container[74].i= 234
container[74].j= 17
container[74].angle= 315
container[74].value= 255


container[75].bin= 30
container[75].i= 234
container[75].j= 22
container[75].angle= 153
container[75].value= 255


container[76].bin= 63
container[76].i= 235
container[76].j= 17
container[76].angle= 315
container[76].value= 255


container[77].bin= 59
container[77].i= 235
container[77].j= 18
container[77].angle= 296
container[77].value= 255


container[78].bin= 36
container[78].i= 235
container[78].j= 22
container[78].angle= 180
container[78].value= 255


container[79].bin= 59
container[79].i= 236
container[79].j= 19
container[79].angle= 296
container[79].value= 255


container[80].bin= 59
container[80].i= 236
container[80].j= 20
container[80].angle= 296
container[80].value= 255


container[81].bin= 54
container[81].i= 236
container[81].j= 21
container[81].angle= 270
container[81].value= 255


container[82].bin= 44
container[82].i= 236
container[82].j= 22
container[82].angle= 224
container[82].value= 255


