container[0].bin= 18
container[0].i= 297
container[0].j= 147
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 297
container[1].j= 148
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 297
container[2].j= 151
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 297
container[3].j= 152
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 298
container[4].j= 146
container[4].angle= 44
container[4].value= 255


container[5].bin= 23
container[5].i= 298
container[5].j= 149
container[5].angle= 116
container[5].value= 255


container[6].bin= 21
container[6].i= 298
container[6].j= 150
container[6].angle= 108
container[6].value= 255


container[7].bin= 8
container[7].i= 298
container[7].j= 153
container[7].angle= 44
container[7].value= 255


container[8].bin= 27
container[8].i= 298
container[8].j= 154
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 299
container[9].j= 145
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 299
container[10].j= 151
container[10].angle= 135
container[10].value= 255


container[11].bin= 8
container[11].i= 299
container[11].j= 152
container[11].angle= 44
container[11].value= 255


container[12].bin= 63
container[12].i= 300
container[12].j= 146
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 300
container[13].j= 147
container[13].angle= 270
container[13].value= 255


container[14].bin= 54
container[14].i= 300
container[14].j= 148
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 300
container[15].j= 149
container[15].angle= 270
container[15].value= 255


container[16].bin= 27
container[16].i= 300
container[16].j= 155
container[16].angle= 135
container[16].value= 255


container[17].bin= 63
container[17].i= 301
container[17].j= 150
container[17].angle= 315
container[17].value= 255


container[18].bin= 27
container[18].i= 301
container[18].j= 156
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 302
container[19].j= 150
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 302
container[20].j= 156
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 303
container[21].j= 150
container[21].angle= 0
container[21].value= 255


container[22].bin= 54
container[22].i= 303
container[22].j= 153
container[22].angle= 270
container[22].value= 255


container[23].bin= 54
container[23].i= 303
container[23].j= 154
container[23].angle= 270
container[23].value= 255


container[24].bin= 54
container[24].i= 303
container[24].j= 155
container[24].angle= 270
container[24].value= 255


container[25].bin= 39
container[25].i= 303
container[25].j= 156
container[25].angle= 198
container[25].value= 255


container[26].bin= 0
container[26].i= 304
container[26].j= 150
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 304
container[27].j= 157
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 305
container[28].j= 150
container[28].angle= 0
container[28].value= 255


container[29].bin= 39
container[29].i= 305
container[29].j= 157
container[29].angle= 198
container[29].value= 255


container[30].bin= 0
container[30].i= 306
container[30].j= 150
container[30].angle= 0
container[30].value= 255


container[31].bin= 44
container[31].i= 306
container[31].j= 154
container[31].angle= 224
container[31].value= 255


container[32].bin= 44
container[32].i= 306
container[32].j= 155
container[32].angle= 224
container[32].value= 255


container[33].bin= 0
container[33].i= 307
container[33].j= 150
container[33].angle= 0
container[33].value= 255


container[34].bin= 44
container[34].i= 307
container[34].j= 152
container[34].angle= 224
container[34].value= 255


container[35].bin= 54
container[35].i= 307
container[35].j= 153
container[35].angle= 270
container[35].value= 255


container[36].bin= 0
container[36].i= 308
container[36].j= 150
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 308
container[37].j= 152
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 309
container[38].j= 150
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 309
container[39].j= 152
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 310
container[40].j= 150
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 310
container[41].j= 152
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 311
container[42].j= 150
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 311
container[43].j= 152
container[43].angle= 180
container[43].value= 255


container[44].bin= 68
container[44].i= 312
container[44].j= 150
container[44].angle= 341
container[44].value= 255


container[45].bin= 54
container[45].i= 312
container[45].j= 151
container[45].angle= 270
container[45].value= 255


container[46].bin= 39
container[46].i= 312
container[46].j= 152
container[46].angle= 198
container[46].value= 255


