container[0].bin= 8
container[0].i= 154
container[0].j= 575
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 154
container[1].j= 576
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 155
container[2].j= 574
container[2].angle= 0
container[2].value= 255


container[3].bin= 30
container[3].i= 155
container[3].j= 577
container[3].angle= 153
container[3].value= 255


container[4].bin= 63
container[4].i= 156
container[4].j= 575
container[4].angle= 315
container[4].value= 255


container[5].bin= 27
container[5].i= 156
container[5].j= 578
container[5].angle= 135
container[5].value= 255


container[6].bin= 18
container[6].i= 156
container[6].j= 579
container[6].angle= 90
container[6].value= 255


container[7].bin= 14
container[7].i= 156
container[7].j= 580
container[7].angle= 71
container[7].value= 255


container[8].bin= 21
container[8].i= 156
container[8].j= 581
container[8].angle= 108
container[8].value= 255


container[9].bin= 18
container[9].i= 156
container[9].j= 582
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 156
container[10].j= 583
container[10].angle= 90
container[10].value= 255


container[11].bin= 63
container[11].i= 157
container[11].j= 576
container[11].angle= 315
container[11].value= 255


container[12].bin= 30
container[12].i= 157
container[12].j= 578
container[12].angle= 153
container[12].value= 255


container[13].bin= 3
container[13].i= 157
container[13].j= 580
container[13].angle= 18
container[13].value= 255


container[14].bin= 32
container[14].i= 157
container[14].j= 584
container[14].angle= 161
container[14].value= 255


container[15].bin= 0
container[15].i= 158
container[15].j= 576
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 158
container[16].j= 584
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 159
container[17].j= 577
container[17].angle= 333
container[17].value= 255


container[18].bin= 27
container[18].i= 159
container[18].j= 584
container[18].angle= 135
container[18].value= 255


container[19].bin= 18
container[19].i= 159
container[19].j= 585
container[19].angle= 90
container[19].value= 255


container[20].bin= 18
container[20].i= 159
container[20].j= 586
container[20].angle= 90
container[20].value= 255


container[21].bin= 18
container[21].i= 159
container[21].j= 587
container[21].angle= 90
container[21].value= 255


container[22].bin= 18
container[22].i= 159
container[22].j= 588
container[22].angle= 90
container[22].value= 255


container[23].bin= 66
container[23].i= 160
container[23].j= 577
container[23].angle= 333
container[23].value= 255


container[24].bin= 27
container[24].i= 160
container[24].j= 589
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 161
container[25].j= 577
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 161
container[26].j= 589
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 162
container[27].j= 578
container[27].angle= 315
container[27].value= 255


container[28].bin= 54
container[28].i= 162
container[28].j= 579
container[28].angle= 270
container[28].value= 255


container[29].bin= 57
container[29].i= 162
container[29].j= 580
container[29].angle= 288
container[29].value= 255


container[30].bin= 27
container[30].i= 162
container[30].j= 590
container[30].angle= 135
container[30].value= 255


container[31].bin= 18
container[31].i= 162
container[31].j= 591
container[31].angle= 90
container[31].value= 255


container[32].bin= 27
container[32].i= 163
container[32].j= 592
container[32].angle= 135
container[32].value= 255


container[33].bin= 3
container[33].i= 164
container[33].j= 579
container[33].angle= 18
container[33].value= 255


container[34].bin= 41
container[34].i= 164
container[34].j= 592
container[34].angle= 206
container[34].value= 255


container[35].bin= 68
container[35].i= 165
container[35].j= 579
container[35].angle= 341
container[35].value= 255


container[36].bin= 63
container[36].i= 165
container[36].j= 580
container[36].angle= 315
container[36].value= 255


container[37].bin= 32
container[37].i= 165
container[37].j= 592
container[37].angle= 161
container[37].value= 255


container[38].bin= 54
container[38].i= 166
container[38].j= 581
container[38].angle= 270
container[38].value= 255


container[39].bin= 63
container[39].i= 166
container[39].j= 582
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 166
container[40].j= 594
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 167
container[41].j= 582
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 167
container[42].j= 594
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 168
container[43].j= 583
container[43].angle= 315
container[43].value= 255


container[44].bin= 27
container[44].i= 168
container[44].j= 595
container[44].angle= 135
container[44].value= 255


container[45].bin= 63
container[45].i= 169
container[45].j= 584
container[45].angle= 315
container[45].value= 255


container[46].bin= 27
container[46].i= 169
container[46].j= 596
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 170
container[47].j= 584
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 170
container[48].j= 596
container[48].angle= 180
container[48].value= 255


container[49].bin= 0
container[49].i= 171
container[49].j= 584
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 171
container[50].j= 596
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 172
container[51].j= 584
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 172
container[52].j= 596
container[52].angle= 180
container[52].value= 255


container[53].bin= 0
container[53].i= 173
container[53].j= 584
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 173
container[54].j= 596
container[54].angle= 180
container[54].value= 255


container[55].bin= 0
container[55].i= 174
container[55].j= 584
container[55].angle= 0
container[55].value= 255


container[56].bin= 30
container[56].i= 174
container[56].j= 597
container[56].angle= 153
container[56].value= 255


container[57].bin= 0
container[57].i= 175
container[57].j= 584
container[57].angle= 0
container[57].value= 255


container[58].bin= 30
container[58].i= 175
container[58].j= 597
container[58].angle= 153
container[58].value= 255


container[59].bin= 0
container[59].i= 176
container[59].j= 584
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 176
container[60].j= 597
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 177
container[61].j= 584
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 177
container[62].j= 597
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 178
container[63].j= 584
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 178
container[64].j= 597
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 179
container[65].j= 584
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 179
container[66].j= 597
container[66].angle= 180
container[66].value= 255


container[67].bin= 63
container[67].i= 180
container[67].j= 585
container[67].angle= 315
container[67].value= 255


container[68].bin= 54
container[68].i= 180
container[68].j= 586
container[68].angle= 270
container[68].value= 255


container[69].bin= 41
container[69].i= 180
container[69].j= 597
container[69].angle= 206
container[69].value= 255


container[70].bin= 63
container[70].i= 181
container[70].j= 587
container[70].angle= 315
container[70].value= 255


container[71].bin= 41
container[71].i= 181
container[71].j= 597
container[71].angle= 206
container[71].value= 255


container[72].bin= 0
container[72].i= 182
container[72].j= 587
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 182
container[73].j= 596
container[73].angle= 180
container[73].value= 255


container[74].bin= 0
container[74].i= 183
container[74].j= 587
container[74].angle= 0
container[74].value= 255


container[75].bin= 30
container[75].i= 183
container[75].j= 597
container[75].angle= 153
container[75].value= 255


container[76].bin= 0
container[76].i= 184
container[76].j= 587
container[76].angle= 0
container[76].value= 255


container[77].bin= 30
container[77].i= 184
container[77].j= 597
container[77].angle= 153
container[77].value= 255


container[78].bin= 0
container[78].i= 185
container[78].j= 587
container[78].angle= 0
container[78].value= 255


container[79].bin= 36
container[79].i= 185
container[79].j= 597
container[79].angle= 180
container[79].value= 255


container[80].bin= 0
container[80].i= 186
container[80].j= 587
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 186
container[81].j= 597
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 187
container[82].j= 587
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 187
container[83].j= 597
container[83].angle= 180
container[83].value= 255


container[84].bin= 66
container[84].i= 188
container[84].j= 588
container[84].angle= 333
container[84].value= 255


container[85].bin= 36
container[85].i= 188
container[85].j= 597
container[85].angle= 180
container[85].value= 255


container[86].bin= 63
container[86].i= 189
container[86].j= 588
container[86].angle= 315
container[86].value= 255


container[87].bin= 63
container[87].i= 189
container[87].j= 589
container[87].angle= 315
container[87].value= 255


container[88].bin= 36
container[88].i= 189
container[88].j= 597
container[88].angle= 180
container[88].value= 255


container[89].bin= 66
container[89].i= 190
container[89].j= 589
container[89].angle= 333
container[89].value= 255


container[90].bin= 36
container[90].i= 190
container[90].j= 597
container[90].angle= 180
container[90].value= 255


container[91].bin= 0
container[91].i= 191
container[91].j= 589
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 191
container[92].j= 597
container[92].angle= 180
container[92].value= 255


container[93].bin= 66
container[93].i= 192
container[93].j= 590
container[93].angle= 333
container[93].value= 255


container[94].bin= 27
container[94].i= 192
container[94].j= 598
container[94].angle= 135
container[94].value= 255


container[95].bin= 66
container[95].i= 193
container[95].j= 590
container[95].angle= 333
container[95].value= 255


container[96].bin= 27
container[96].i= 193
container[96].j= 599
container[96].angle= 135
container[96].value= 255


container[97].bin= 0
container[97].i= 194
container[97].j= 590
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 194
container[98].j= 599
container[98].angle= 180
container[98].value= 255


container[99].bin= 63
container[99].i= 195
container[99].j= 591
container[99].angle= 315
container[99].value= 255


container[100].bin= 27
container[100].i= 195
container[100].j= 600
container[100].angle= 135
container[100].value= 255


container[101].bin= 18
container[101].i= 195
container[101].j= 601
container[101].angle= 90
container[101].value= 255


container[102].bin= 59
container[102].i= 196
container[102].j= 592
container[102].angle= 296
container[102].value= 255


container[103].bin= 63
container[103].i= 196
container[103].j= 593
container[103].angle= 315
container[103].value= 255


container[104].bin= 27
container[104].i= 196
container[104].j= 602
container[104].angle= 135
container[104].value= 255


container[105].bin= 0
container[105].i= 197
container[105].j= 593
container[105].angle= 0
container[105].value= 255


container[106].bin= 36
container[106].i= 197
container[106].j= 602
container[106].angle= 180
container[106].value= 255


container[107].bin= 0
container[107].i= 198
container[107].j= 593
container[107].angle= 0
container[107].value= 255


container[108].bin= 36
container[108].i= 198
container[108].j= 602
container[108].angle= 180
container[108].value= 255


container[109].bin= 66
container[109].i= 199
container[109].j= 593
container[109].angle= 333
container[109].value= 255


container[110].bin= 36
container[110].i= 199
container[110].j= 602
container[110].angle= 180
container[110].value= 255


container[111].bin= 0
container[111].i= 200
container[111].j= 593
container[111].angle= 0
container[111].value= 255


container[112].bin= 36
container[112].i= 200
container[112].j= 602
container[112].angle= 180
container[112].value= 255


container[113].bin= 63
container[113].i= 201
container[113].j= 594
container[113].angle= 315
container[113].value= 255


container[114].bin= 27
container[114].i= 201
container[114].j= 603
container[114].angle= 135
container[114].value= 255


container[115].bin= 18
container[115].i= 201
container[115].j= 604
container[115].angle= 90
container[115].value= 255


container[116].bin= 63
container[116].i= 202
container[116].j= 595
container[116].angle= 315
container[116].value= 255


container[117].bin= 27
container[117].i= 202
container[117].j= 605
container[117].angle= 135
container[117].value= 255


container[118].bin= 0
container[118].i= 203
container[118].j= 595
container[118].angle= 0
container[118].value= 255


container[119].bin= 36
container[119].i= 203
container[119].j= 605
container[119].angle= 180
container[119].value= 255


container[120].bin= 68
container[120].i= 204
container[120].j= 595
container[120].angle= 341
container[120].value= 255


container[121].bin= 54
container[121].i= 204
container[121].j= 597
container[121].angle= 270
container[121].value= 255


container[122].bin= 63
container[122].i= 204
container[122].j= 598
container[122].angle= 315
container[122].value= 255


container[123].bin= 36
container[123].i= 204
container[123].j= 605
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 205
container[124].j= 598
container[124].angle= 0
container[124].value= 255


container[125].bin= 36
container[125].i= 205
container[125].j= 605
container[125].angle= 180
container[125].value= 255


container[126].bin= 68
container[126].i= 206
container[126].j= 598
container[126].angle= 341
container[126].value= 255


container[127].bin= 36
container[127].i= 206
container[127].j= 605
container[127].angle= 180
container[127].value= 255


container[128].bin= 59
container[128].i= 207
container[128].j= 599
container[128].angle= 296
container[128].value= 255


container[129].bin= 63
container[129].i= 207
container[129].j= 600
container[129].angle= 315
container[129].value= 255


container[130].bin= 27
container[130].i= 207
container[130].j= 606
container[130].angle= 135
container[130].value= 255


container[131].bin= 18
container[131].i= 207
container[131].j= 607
container[131].angle= 90
container[131].value= 255


container[132].bin= 18
container[132].i= 207
container[132].j= 608
container[132].angle= 90
container[132].value= 255


container[133].bin= 66
container[133].i= 208
container[133].j= 600
container[133].angle= 333
container[133].value= 255


container[134].bin= 27
container[134].i= 208
container[134].j= 609
container[134].angle= 135
container[134].value= 255


container[135].bin= 0
container[135].i= 209
container[135].j= 600
container[135].angle= 0
container[135].value= 255


container[136].bin= 41
container[136].i= 209
container[136].j= 609
container[136].angle= 206
container[136].value= 255


container[137].bin= 63
container[137].i= 210
container[137].j= 601
container[137].angle= 315
container[137].value= 255


container[138].bin= 54
container[138].i= 210
container[138].j= 602
container[138].angle= 270
container[138].value= 255


container[139].bin= 32
container[139].i= 210
container[139].j= 609
container[139].angle= 161
container[139].value= 255


container[140].bin= 63
container[140].i= 211
container[140].j= 603
container[140].angle= 315
container[140].value= 255


container[141].bin= 23
container[141].i= 211
container[141].j= 610
container[141].angle= 116
container[141].value= 255


container[142].bin= 23
container[142].i= 211
container[142].j= 611
container[142].angle= 116
container[142].value= 255


container[143].bin= 21
container[143].i= 211
container[143].j= 612
container[143].angle= 108
container[143].value= 255


container[144].bin= 0
container[144].i= 212
container[144].j= 603
container[144].angle= 0
container[144].value= 255


container[145].bin= 36
container[145].i= 212
container[145].j= 610
container[145].angle= 180
container[145].value= 255


container[146].bin= 0
container[146].i= 213
container[146].j= 603
container[146].angle= 0
container[146].value= 255


container[147].bin= 36
container[147].i= 213
container[147].j= 610
container[147].angle= 180
container[147].value= 255


container[148].bin= 21
container[148].i= 213
container[148].j= 613
container[148].angle= 108
container[148].value= 255


container[149].bin= 18
container[149].i= 213
container[149].j= 614
container[149].angle= 90
container[149].value= 255


container[150].bin= 66
container[150].i= 214
container[150].j= 604
container[150].angle= 333
container[150].value= 255


container[151].bin= 21
container[151].i= 214
container[151].j= 611
container[151].angle= 108
container[151].value= 255


container[152].bin= 18
container[152].i= 214
container[152].j= 612
container[152].angle= 90
container[152].value= 255


container[153].bin= 27
container[153].i= 214
container[153].j= 615
container[153].angle= 135
container[153].value= 255


container[154].bin= 63
container[154].i= 215
container[154].j= 604
container[154].angle= 315
container[154].value= 255


container[155].bin= 63
container[155].i= 215
container[155].j= 605
container[155].angle= 315
container[155].value= 255


container[156].bin= 36
container[156].i= 215
container[156].j= 615
container[156].angle= 180
container[156].value= 255


container[157].bin= 63
container[157].i= 216
container[157].j= 605
container[157].angle= 315
container[157].value= 255


container[158].bin= 59
container[158].i= 216
container[158].j= 606
container[158].angle= 296
container[158].value= 255


container[159].bin= 57
container[159].i= 216
container[159].j= 607
container[159].angle= 288
container[159].value= 255


container[160].bin= 30
container[160].i= 216
container[160].j= 616
container[160].angle= 153
container[160].value= 255


container[161].bin= 63
container[161].i= 217
container[161].j= 607
container[161].angle= 315
container[161].value= 255


container[162].bin= 63
container[162].i= 217
container[162].j= 608
container[162].angle= 315
container[162].value= 255


container[163].bin= 30
container[163].i= 217
container[163].j= 616
container[163].angle= 153
container[163].value= 255


container[164].bin= 0
container[164].i= 218
container[164].j= 606
container[164].angle= 0
container[164].value= 255


container[165].bin= 36
container[165].i= 218
container[165].j= 616
container[165].angle= 180
container[165].value= 255


container[166].bin= 63
container[166].i= 219
container[166].j= 607
container[166].angle= 315
container[166].value= 255


container[167].bin= 27
container[167].i= 219
container[167].j= 617
container[167].angle= 135
container[167].value= 255


container[168].bin= 18
container[168].i= 219
container[168].j= 618
container[168].angle= 90
container[168].value= 255


container[169].bin= 18
container[169].i= 219
container[169].j= 619
container[169].angle= 90
container[169].value= 255


container[170].bin= 18
container[170].i= 219
container[170].j= 620
container[170].angle= 90
container[170].value= 255


container[171].bin= 66
container[171].i= 220
container[171].j= 608
container[171].angle= 333
container[171].value= 255


container[172].bin= 23
container[172].i= 220
container[172].j= 621
container[172].angle= 116
container[172].value= 255


container[173].bin= 18
container[173].i= 220
container[173].j= 622
container[173].angle= 90
container[173].value= 255


container[174].bin= 21
container[174].i= 220
container[174].j= 623
container[174].angle= 108
container[174].value= 255


container[175].bin= 0
container[175].i= 221
container[175].j= 608
container[175].angle= 0
container[175].value= 255


container[176].bin= 32
container[176].i= 221
container[176].j= 623
container[176].angle= 161
container[176].value= 255


container[177].bin= 66
container[177].i= 222
container[177].j= 609
container[177].angle= 333
container[177].value= 255


container[178].bin= 54
container[178].i= 222
container[178].j= 613
container[178].angle= 270
container[178].value= 255


container[179].bin= 30
container[179].i= 222
container[179].j= 624
container[179].angle= 153
container[179].value= 255


container[180].bin= 66
container[180].i= 223
container[180].j= 609
container[180].angle= 333
container[180].value= 255


container[181].bin= 30
container[181].i= 223
container[181].j= 624
container[181].angle= 153
container[181].value= 255


container[182].bin= 0
container[182].i= 224
container[182].j= 609
container[182].angle= 0
container[182].value= 255


container[183].bin= 44
container[183].i= 224
container[183].j= 611
container[183].angle= 224
container[183].value= 255


container[184].bin= 36
container[184].i= 224
container[184].j= 624
container[184].angle= 180
container[184].value= 255


container[185].bin= 68
container[185].i= 225
container[185].j= 609
container[185].angle= 341
container[185].value= 255


container[186].bin= 44
container[186].i= 225
container[186].j= 611
container[186].angle= 224
container[186].value= 255


container[187].bin= 66
container[187].i= 225
container[187].j= 613
container[187].angle= 333
container[187].value= 255


container[188].bin= 36
container[188].i= 225
container[188].j= 624
container[188].angle= 180
container[188].value= 255


container[189].bin= 0
container[189].i= 226
container[189].j= 613
container[189].angle= 0
container[189].value= 255


container[190].bin= 36
container[190].i= 226
container[190].j= 624
container[190].angle= 180
container[190].value= 255


container[191].bin= 0
container[191].i= 227
container[191].j= 613
container[191].angle= 0
container[191].value= 255


container[192].bin= 36
container[192].i= 227
container[192].j= 624
container[192].angle= 180
container[192].value= 255


container[193].bin= 0
container[193].i= 228
container[193].j= 613
container[193].angle= 0
container[193].value= 255


container[194].bin= 36
container[194].i= 228
container[194].j= 624
container[194].angle= 180
container[194].value= 255


container[195].bin= 0
container[195].i= 229
container[195].j= 613
container[195].angle= 0
container[195].value= 255


container[196].bin= 36
container[196].i= 229
container[196].j= 624
container[196].angle= 180
container[196].value= 255


container[197].bin= 66
container[197].i= 230
container[197].j= 614
container[197].angle= 333
container[197].value= 255


container[198].bin= 36
container[198].i= 230
container[198].j= 624
container[198].angle= 180
container[198].value= 255


container[199].bin= 63
container[199].i= 231
container[199].j= 614
container[199].angle= 315
container[199].value= 255


container[200].bin= 59
container[200].i= 231
container[200].j= 615
container[200].angle= 296
container[200].value= 255


container[201].bin= 36
container[201].i= 231
container[201].j= 624
container[201].angle= 180
container[201].value= 255


container[202].bin= 63
container[202].i= 232
container[202].j= 616
container[202].angle= 315
container[202].value= 255


container[203].bin= 36
container[203].i= 232
container[203].j= 624
container[203].angle= 180
container[203].value= 255


container[204].bin= 0
container[204].i= 233
container[204].j= 616
container[204].angle= 0
container[204].value= 255


container[205].bin= 36
container[205].i= 233
container[205].j= 624
container[205].angle= 180
container[205].value= 255


container[206].bin= 66
container[206].i= 234
container[206].j= 617
container[206].angle= 333
container[206].value= 255


container[207].bin= 36
container[207].i= 234
container[207].j= 624
container[207].angle= 180
container[207].value= 255


container[208].bin= 0
container[208].i= 235
container[208].j= 617
container[208].angle= 0
container[208].value= 255


container[209].bin= 36
container[209].i= 235
container[209].j= 624
container[209].angle= 180
container[209].value= 255


container[210].bin= 0
container[210].i= 236
container[210].j= 617
container[210].angle= 0
container[210].value= 255


container[211].bin= 36
container[211].i= 236
container[211].j= 624
container[211].angle= 180
container[211].value= 255


container[212].bin= 63
container[212].i= 237
container[212].j= 617
container[212].angle= 315
container[212].value= 255


container[213].bin= 59
container[213].i= 237
container[213].j= 618
container[213].angle= 296
container[213].value= 255


container[214].bin= 36
container[214].i= 237
container[214].j= 624
container[214].angle= 180
container[214].value= 255


container[215].bin= 63
container[215].i= 238
container[215].j= 619
container[215].angle= 315
container[215].value= 255


container[216].bin= 36
container[216].i= 238
container[216].j= 624
container[216].angle= 180
container[216].value= 255


container[217].bin= 0
container[217].i= 239
container[217].j= 619
container[217].angle= 0
container[217].value= 255


container[218].bin= 36
container[218].i= 239
container[218].j= 624
container[218].angle= 180
container[218].value= 255


container[219].bin= 63
container[219].i= 240
container[219].j= 620
container[219].angle= 315
container[219].value= 255


container[220].bin= 54
container[220].i= 240
container[220].j= 621
container[220].angle= 270
container[220].value= 255


container[221].bin= 36
container[221].i= 240
container[221].j= 624
container[221].angle= 180
container[221].value= 255


container[222].bin= 63
container[222].i= 241
container[222].j= 622
container[222].angle= 315
container[222].value= 255


container[223].bin= 0
container[223].i= 242
container[223].j= 622
container[223].angle= 0
container[223].value= 255


container[224].bin= 66
container[224].i= 243
container[224].j= 623
container[224].angle= 333
container[224].value= 255


container[225].bin= 63
container[225].i= 244
container[225].j= 623
container[225].angle= 315
container[225].value= 255


