container[0].bin= 18
container[0].i= 360
container[0].j= 233
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 361
container[1].j= 232
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 361
container[2].j= 234
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 362
container[3].j= 232
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 362
container[4].j= 234
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 363
container[5].j= 231
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 363
container[6].j= 232
container[6].angle= 44
container[6].value= 255


container[7].bin= 36
container[7].i= 363
container[7].j= 234
container[7].angle= 180
container[7].value= 255


container[8].bin= 8
container[8].i= 364
container[8].j= 230
container[8].angle= 44
container[8].value= 255


container[9].bin= 0
container[9].i= 365
container[9].j= 229
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 365
container[10].j= 233
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 366
container[11].j= 230
container[11].angle= 315
container[11].value= 255


container[12].bin= 36
container[12].i= 366
container[12].j= 233
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 367
container[13].j= 231
container[13].angle= 315
container[13].value= 255


container[14].bin= 0
container[14].i= 368
container[14].j= 231
container[14].angle= 0
container[14].value= 255


container[15].bin= 66
container[15].i= 369
container[15].j= 232
container[15].angle= 333
container[15].value= 255


container[16].bin= 66
container[16].i= 370
container[16].j= 232
container[16].angle= 333
container[16].value= 255


container[17].bin= 36
container[17].i= 370
container[17].j= 234
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 371
container[18].j= 232
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 371
container[19].j= 234
container[19].angle= 180
container[19].value= 255


container[20].bin= 68
container[20].i= 372
container[20].j= 232
container[20].angle= 341
container[20].value= 255


container[21].bin= 54
container[21].i= 372
container[21].j= 233
container[21].angle= 270
container[21].value= 255


container[22].bin= 39
container[22].i= 372
container[22].j= 234
container[22].angle= 198
container[22].value= 255


