container[0].bin= 18
container[0].i= 797
container[0].j= 338
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 798
container[1].j= 337
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 798
container[2].j= 339
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 799
container[3].j= 337
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 799
container[4].j= 339
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 800
container[5].j= 337
container[5].angle= 341
container[5].value= 255


container[6].bin= 32
container[6].i= 800
container[6].j= 339
container[6].angle= 161
container[6].value= 255


container[7].bin= 68
container[7].i= 801
container[7].j= 338
container[7].angle= 341
container[7].value= 255


container[8].bin= 27
container[8].i= 801
container[8].j= 340
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 802
container[9].j= 338
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 802
container[10].j= 340
container[10].angle= 180
container[10].value= 255


container[11].bin= 68
container[11].i= 803
container[11].j= 338
container[11].angle= 341
container[11].value= 255


container[12].bin= 57
container[12].i= 803
container[12].j= 339
container[12].angle= 288
container[12].value= 255


container[13].bin= 44
container[13].i= 803
container[13].j= 340
container[13].angle= 224
container[13].value= 255


