container[0].bin= 18
container[0].i= 312
container[0].j= 276
container[0].angle= 90
container[0].value= 255


container[1].bin= 21
container[1].i= 312
container[1].j= 277
container[1].angle= 108
container[1].value= 255


container[2].bin= 8
container[2].i= 313
container[2].j= 275
container[2].angle= 44
container[2].value= 255


container[3].bin= 0
container[3].i= 314
container[3].j= 274
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 314
container[4].j= 277
container[4].angle= 206
container[4].value= 255


container[5].bin= 63
container[5].i= 315
container[5].j= 275
container[5].angle= 315
container[5].value= 255


container[6].bin= 44
container[6].i= 315
container[6].j= 276
container[6].angle= 224
container[6].value= 255


