container[0].bin= 14
container[0].i= 531
container[0].j= 355
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 531
container[1].j= 356
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 532
container[2].j= 354
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 533
container[3].j= 354
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 533
container[4].j= 356
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 534
container[5].j= 354
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 534
container[6].j= 356
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 535
container[7].j= 354
container[7].angle= 0
container[7].value= 255


container[8].bin= 0
container[8].i= 536
container[8].j= 354
container[8].angle= 0
container[8].value= 255


container[9].bin= 63
container[9].i= 537
container[9].j= 355
container[9].angle= 315
container[9].value= 255


container[10].bin= 44
container[10].i= 537
container[10].j= 356
container[10].angle= 224
container[10].value= 255


