container[0].bin= 8
container[0].i= 544
container[0].j= 423
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 544
container[1].j= 424
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 545
container[2].j= 422
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 546
container[3].j= 422
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 546
container[4].j= 425
container[4].angle= 153
container[4].value= 255


container[5].bin= 18
container[5].i= 546
container[5].j= 429
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 547
container[6].j= 422
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 547
container[7].j= 425
container[7].angle= 153
container[7].value= 255


container[8].bin= 3
container[8].i= 547
container[8].j= 428
container[8].angle= 18
container[8].value= 255


container[9].bin= 32
container[9].i= 547
container[9].j= 430
container[9].angle= 161
container[9].value= 255


container[10].bin= 0
container[10].i= 548
container[10].j= 422
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 548
container[11].j= 425
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 548
container[12].j= 428
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 548
container[13].j= 430
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 549
container[14].j= 422
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 549
container[15].j= 426
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 549
container[16].j= 427
container[16].angle= 90
container[16].value= 255


container[17].bin= 8
container[17].i= 549
container[17].j= 428
container[17].angle= 44
container[17].value= 255


container[18].bin= 36
container[18].i= 549
container[18].j= 430
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 550
container[19].j= 422
container[19].angle= 0
container[19].value= 255


container[20].bin= 0
container[20].i= 551
container[20].j= 422
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 551
container[21].j= 429
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 552
container[22].j= 422
container[22].angle= 0
container[22].value= 255


container[23].bin= 44
container[23].i= 552
container[23].j= 429
container[23].angle= 224
container[23].value= 255


container[24].bin= 0
container[24].i= 553
container[24].j= 422
container[24].angle= 0
container[24].value= 255


container[25].bin= 44
container[25].i= 553
container[25].j= 428
container[25].angle= 224
container[25].value= 255


container[26].bin= 0
container[26].i= 554
container[26].j= 422
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 554
container[27].j= 427
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 555
container[28].j= 423
container[28].angle= 315
container[28].value= 255


container[29].bin= 54
container[29].i= 555
container[29].j= 424
container[29].angle= 270
container[29].value= 255


container[30].bin= 54
container[30].i= 555
container[30].j= 425
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 555
container[31].j= 426
container[31].angle= 270
container[31].value= 255


container[32].bin= 44
container[32].i= 555
container[32].j= 427
container[32].angle= 224
container[32].value= 255


