container[0].bin= 18
container[0].i= 210
container[0].j= 199
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 211
container[1].j= 198
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 211
container[2].j= 200
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 212
container[3].j= 198
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 212
container[4].j= 200
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 213
container[5].j= 197
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 213
container[6].j= 198
container[6].angle= 44
container[6].value= 255


container[7].bin= 36
container[7].i= 213
container[7].j= 200
container[7].angle= 180
container[7].value= 255


container[8].bin= 8
container[8].i= 214
container[8].j= 196
container[8].angle= 44
container[8].value= 255


container[9].bin= 0
container[9].i= 215
container[9].j= 195
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 215
container[10].j= 199
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 216
container[11].j= 196
container[11].angle= 315
container[11].value= 255


container[12].bin= 27
container[12].i= 216
container[12].j= 200
container[12].angle= 135
container[12].value= 255


container[13].bin= 63
container[13].i= 217
container[13].j= 197
container[13].angle= 315
container[13].value= 255


container[14].bin= 27
container[14].i= 217
container[14].j= 201
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 218
container[15].j= 197
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 218
container[16].j= 201
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 219
container[17].j= 197
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 219
container[18].j= 201
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 220
container[19].j= 197
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 220
container[20].j= 201
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 221
container[21].j= 197
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 221
container[22].j= 201
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 222
container[23].j= 198
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 222
container[24].j= 199
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 222
container[25].j= 200
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 222
container[26].j= 201
container[26].angle= 224
container[26].value= 255


