container[0].bin= 18
container[0].i= 237
container[0].j= 180
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 239
container[1].j= 178
container[1].angle= 18
container[1].value= 255


container[2].bin= 68
container[2].i= 240
container[2].j= 178
container[2].angle= 341
container[2].value= 255


