container[0].bin= 8
container[0].i= 190
container[0].j= 134
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 190
container[1].j= 135
container[1].angle= 108
container[1].value= 255


container[2].bin= 0
container[2].i= 191
container[2].j= 134
container[2].angle= 0
container[2].value= 255


container[3].bin= 30
container[3].i= 191
container[3].j= 136
container[3].angle= 153
container[3].value= 255


container[4].bin= 63
container[4].i= 192
container[4].j= 134
container[4].angle= 315
container[4].value= 255


container[5].bin= 57
container[5].i= 192
container[5].j= 135
container[5].angle= 288
container[5].value= 255


