container[0].bin= 18
container[0].i= 516
container[0].j= 117
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 516
container[1].j= 118
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 517
container[2].j= 116
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 517
container[3].j= 119
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 518
container[4].j= 115
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 518
container[5].j= 119
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 519
container[6].j= 116
container[6].angle= 315
container[6].value= 255


container[7].bin= 27
container[7].i= 519
container[7].j= 120
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 519
container[8].j= 121
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 519
container[9].j= 122
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 519
container[10].j= 123
container[10].angle= 90
container[10].value= 255


container[11].bin= 59
container[11].i= 520
container[11].j= 117
container[11].angle= 296
container[11].value= 255


container[12].bin= 63
container[12].i= 520
container[12].j= 118
container[12].angle= 315
container[12].value= 255


container[13].bin= 27
container[13].i= 520
container[13].j= 124
container[13].angle= 135
container[13].value= 255


container[14].bin= 66
container[14].i= 521
container[14].j= 118
container[14].angle= 333
container[14].value= 255


container[15].bin= 36
container[15].i= 521
container[15].j= 124
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 522
container[16].j= 119
container[16].angle= 315
container[16].value= 255


container[17].bin= 36
container[17].i= 522
container[17].j= 124
container[17].angle= 180
container[17].value= 255


container[18].bin= 59
container[18].i= 523
container[18].j= 120
container[18].angle= 296
container[18].value= 255


container[19].bin= 63
container[19].i= 523
container[19].j= 121
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 523
container[20].j= 124
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 524
container[21].j= 121
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 524
container[22].j= 124
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 525
container[23].j= 121
container[23].angle= 341
container[23].value= 255


container[24].bin= 57
container[24].i= 525
container[24].j= 122
container[24].angle= 288
container[24].value= 255


container[25].bin= 54
container[25].i= 525
container[25].j= 123
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 525
container[26].j= 124
container[26].angle= 224
container[26].value= 255


