container[0].bin= 18
container[0].i= 712
container[0].j= 199
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 712
container[1].j= 200
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 713
container[2].j= 198
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 713
container[3].j= 201
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 714
container[4].j= 197
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 714
container[5].j= 201
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 715
container[6].j= 197
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 715
container[7].j= 201
container[7].angle= 180
container[7].value= 255


container[8].bin= 14
container[8].i= 716
container[8].j= 196
container[8].angle= 71
container[8].value= 255


container[9].bin= 8
container[9].i= 716
container[9].j= 197
container[9].angle= 44
container[9].value= 255


container[10].bin= 36
container[10].i= 716
container[10].j= 201
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 717
container[11].j= 195
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 717
container[12].j= 201
container[12].angle= 180
container[12].value= 255


container[13].bin= 57
container[13].i= 718
container[13].j= 196
container[13].angle= 288
container[13].value= 255


container[14].bin= 59
container[14].i= 718
container[14].j= 197
container[14].angle= 296
container[14].value= 255


container[15].bin= 63
container[15].i= 718
container[15].j= 198
container[15].angle= 315
container[15].value= 255


container[16].bin= 36
container[16].i= 718
container[16].j= 201
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 719
container[17].j= 198
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 719
container[18].j= 201
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 720
container[19].j= 198
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 720
container[20].j= 201
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 721
container[21].j= 199
container[21].angle= 315
container[21].value= 255


container[22].bin= 30
container[22].i= 721
container[22].j= 202
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 722
container[23].j= 200
container[23].angle= 315
container[23].value= 255


container[24].bin= 30
container[24].i= 722
container[24].j= 202
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 723
container[25].j= 200
container[25].angle= 0
container[25].value= 255


container[26].bin= 63
container[26].i= 724
container[26].j= 201
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 724
container[27].j= 202
container[27].angle= 224
container[27].value= 255


