container[0].bin= 18
container[0].i= 872
container[0].j= 494
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 872
container[1].j= 500
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 873
container[2].j= 493
container[2].angle= 18
container[2].value= 255


container[3].bin= 32
container[3].i= 873
container[3].j= 495
container[3].angle= 161
container[3].value= 255


container[4].bin= 3
container[4].i= 873
container[4].j= 499
container[4].angle= 18
container[4].value= 255


container[5].bin= 32
container[5].i= 873
container[5].j= 501
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 874
container[6].j= 493
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 874
container[7].j= 495
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 874
container[8].j= 499
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 874
container[9].j= 501
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 875
container[10].j= 493
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 875
container[11].j= 495
container[11].angle= 135
container[11].value= 255


container[12].bin= 23
container[12].i= 875
container[12].j= 496
container[12].angle= 116
container[12].value= 255


container[13].bin= 18
container[13].i= 875
container[13].j= 497
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 875
container[14].j= 498
container[14].angle= 90
container[14].value= 255


container[15].bin= 8
container[15].i= 875
container[15].j= 499
container[15].angle= 44
container[15].value= 255


container[16].bin= 36
container[16].i= 875
container[16].j= 501
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 876
container[17].j= 493
container[17].angle= 0
container[17].value= 255


container[18].bin= 0
container[18].i= 877
container[18].j= 493
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 877
container[19].j= 500
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 878
container[20].j= 493
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 878
container[21].j= 501
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 879
container[22].j= 493
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 879
container[23].j= 502
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 880
container[24].j= 493
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 880
container[25].j= 502
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 881
container[26].j= 494
container[26].angle= 315
container[26].value= 255


container[27].bin= 54
container[27].i= 881
container[27].j= 495
container[27].angle= 270
container[27].value= 255


container[28].bin= 30
container[28].i= 881
container[28].j= 503
container[28].angle= 153
container[28].value= 255


container[29].bin= 18
container[29].i= 881
container[29].j= 514
container[29].angle= 90
container[29].value= 255


container[30].bin= 14
container[30].i= 881
container[30].j= 517
container[30].angle= 71
container[30].value= 255


container[31].bin= 21
container[31].i= 881
container[31].j= 518
container[31].angle= 108
container[31].value= 255


container[32].bin= 63
container[32].i= 882
container[32].j= 496
container[32].angle= 315
container[32].value= 255


container[33].bin= 30
container[33].i= 882
container[33].j= 503
container[33].angle= 153
container[33].value= 255


container[34].bin= 8
container[34].i= 882
container[34].j= 513
container[34].angle= 44
container[34].value= 255


container[35].bin= 23
container[35].i= 882
container[35].j= 515
container[35].angle= 116
container[35].value= 255


container[36].bin= 18
container[36].i= 882
container[36].j= 516
container[36].angle= 90
container[36].value= 255


container[37].bin= 0
container[37].i= 883
container[37].j= 496
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 883
container[38].j= 503
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 883
container[39].j= 512
container[39].angle= 0
container[39].value= 255


container[40].bin= 44
container[40].i= 883
container[40].j= 518
container[40].angle= 224
container[40].value= 255


container[41].bin= 63
container[41].i= 884
container[41].j= 497
container[41].angle= 315
container[41].value= 255


container[42].bin= 27
container[42].i= 884
container[42].j= 504
container[42].angle= 135
container[42].value= 255


container[43].bin= 0
container[43].i= 884
container[43].j= 512
container[43].angle= 0
container[43].value= 255


container[44].bin= 41
container[44].i= 884
container[44].j= 517
container[44].angle= 206
container[44].value= 255


container[45].bin= 63
container[45].i= 885
container[45].j= 498
container[45].angle= 315
container[45].value= 255


container[46].bin= 27
container[46].i= 885
container[46].j= 505
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 885
container[47].j= 512
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 885
container[48].j= 516
container[48].angle= 180
container[48].value= 255


container[49].bin= 66
container[49].i= 886
container[49].j= 499
container[49].angle= 333
container[49].value= 255


container[50].bin= 36
container[50].i= 886
container[50].j= 505
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 886
container[51].j= 512
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 886
container[52].j= 516
container[52].angle= 180
container[52].value= 255


container[53].bin= 66
container[53].i= 887
container[53].j= 499
container[53].angle= 333
container[53].value= 255


container[54].bin= 36
container[54].i= 887
container[54].j= 505
container[54].angle= 180
container[54].value= 255


container[55].bin= 5
container[55].i= 887
container[55].j= 512
container[55].angle= 26
container[55].value= 255


container[56].bin= 36
container[56].i= 887
container[56].j= 516
container[56].angle= 180
container[56].value= 255


container[57].bin= 0
container[57].i= 888
container[57].j= 499
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 888
container[58].j= 505
container[58].angle= 180
container[58].value= 255


container[59].bin= 0
container[59].i= 888
container[59].j= 512
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 888
container[60].j= 516
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 889
container[61].j= 500
container[61].angle= 315
container[61].value= 255


container[62].bin= 36
container[62].i= 889
container[62].j= 505
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 889
container[63].j= 512
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 889
container[64].j= 516
container[64].angle= 180
container[64].value= 255


container[65].bin= 63
container[65].i= 890
container[65].j= 501
container[65].angle= 315
container[65].value= 255


container[66].bin= 36
container[66].i= 890
container[66].j= 505
container[66].angle= 180
container[66].value= 255


container[67].bin= 5
container[67].i= 890
container[67].j= 512
container[67].angle= 26
container[67].value= 255


container[68].bin= 44
container[68].i= 890
container[68].j= 516
container[68].angle= 224
container[68].value= 255


container[69].bin= 0
container[69].i= 891
container[69].j= 501
container[69].angle= 0
container[69].value= 255


container[70].bin= 36
container[70].i= 891
container[70].j= 505
container[70].angle= 180
container[70].value= 255


container[71].bin= 0
container[71].i= 891
container[71].j= 511
container[71].angle= 0
container[71].value= 255


container[72].bin= 44
container[72].i= 891
container[72].j= 515
container[72].angle= 224
container[72].value= 255


container[73].bin= 0
container[73].i= 892
container[73].j= 501
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 892
container[74].j= 505
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 892
container[75].j= 511
container[75].angle= 0
container[75].value= 255


container[76].bin= 36
container[76].i= 892
container[76].j= 514
container[76].angle= 180
container[76].value= 255


container[77].bin= 63
container[77].i= 893
container[77].j= 502
container[77].angle= 315
container[77].value= 255


container[78].bin= 54
container[78].i= 893
container[78].j= 503
container[78].angle= 270
container[78].value= 255


container[79].bin= 30
container[79].i= 893
container[79].j= 506
container[79].angle= 153
container[79].value= 255


container[80].bin= 8
container[80].i= 893
container[80].j= 511
container[80].angle= 44
container[80].value= 255


container[81].bin= 36
container[81].i= 893
container[81].j= 514
container[81].angle= 180
container[81].value= 255


container[82].bin= 63
container[82].i= 894
container[82].j= 504
container[82].angle= 315
container[82].value= 255


container[83].bin= 30
container[83].i= 894
container[83].j= 506
container[83].angle= 153
container[83].value= 255


container[84].bin= 8
container[84].i= 894
container[84].j= 510
container[84].angle= 44
container[84].value= 255


container[85].bin= 36
container[85].i= 894
container[85].j= 514
container[85].angle= 180
container[85].value= 255


container[86].bin= 0
container[86].i= 895
container[86].j= 504
container[86].angle= 0
container[86].value= 255


container[87].bin= 0
container[87].i= 895
container[87].j= 509
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 895
container[88].j= 514
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 896
container[89].j= 505
container[89].angle= 315
container[89].value= 255


container[90].bin= 18
container[90].i= 896
container[90].j= 508
container[90].angle= 90
container[90].value= 255


container[91].bin= 8
container[91].i= 896
container[91].j= 509
container[91].angle= 44
container[91].value= 255


container[92].bin= 36
container[92].i= 896
container[92].j= 514
container[92].angle= 180
container[92].value= 255


container[93].bin= 36
container[93].i= 897
container[93].j= 514
container[93].angle= 180
container[93].value= 255


container[94].bin= 0
container[94].i= 898
container[94].j= 506
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 898
container[95].j= 514
container[95].angle= 180
container[95].value= 255


container[96].bin= 63
container[96].i= 899
container[96].j= 507
container[96].angle= 315
container[96].value= 255


container[97].bin= 54
container[97].i= 899
container[97].j= 508
container[97].angle= 270
container[97].value= 255


container[98].bin= 36
container[98].i= 899
container[98].j= 514
container[98].angle= 180
container[98].value= 255


container[99].bin= 59
container[99].i= 900
container[99].j= 509
container[99].angle= 296
container[99].value= 255


container[100].bin= 63
container[100].i= 900
container[100].j= 510
container[100].angle= 315
container[100].value= 255


container[101].bin= 36
container[101].i= 900
container[101].j= 514
container[101].angle= 180
container[101].value= 255


container[102].bin= 0
container[102].i= 901
container[102].j= 510
container[102].angle= 0
container[102].value= 255


container[103].bin= 36
container[103].i= 901
container[103].j= 514
container[103].angle= 180
container[103].value= 255


container[104].bin= 68
container[104].i= 902
container[104].j= 510
container[104].angle= 341
container[104].value= 255


container[105].bin= 57
container[105].i= 902
container[105].j= 511
container[105].angle= 288
container[105].value= 255


container[106].bin= 27
container[106].i= 902
container[106].j= 515
container[106].angle= 135
container[106].value= 255


container[107].bin= 63
container[107].i= 903
container[107].j= 512
container[107].angle= 315
container[107].value= 255


container[108].bin= 27
container[108].i= 903
container[108].j= 516
container[108].angle= 135
container[108].value= 255


container[109].bin= 0
container[109].i= 904
container[109].j= 512
container[109].angle= 0
container[109].value= 255


container[110].bin= 36
container[110].i= 904
container[110].j= 516
container[110].angle= 180
container[110].value= 255


container[111].bin= 63
container[111].i= 905
container[111].j= 513
container[111].angle= 315
container[111].value= 255


container[112].bin= 27
container[112].i= 905
container[112].j= 517
container[112].angle= 135
container[112].value= 255


container[113].bin= 63
container[113].i= 906
container[113].j= 514
container[113].angle= 315
container[113].value= 255


container[114].bin= 27
container[114].i= 906
container[114].j= 518
container[114].angle= 135
container[114].value= 255


container[115].bin= 0
container[115].i= 907
container[115].j= 514
container[115].angle= 0
container[115].value= 255


container[116].bin= 36
container[116].i= 907
container[116].j= 518
container[116].angle= 180
container[116].value= 255


container[117].bin= 66
container[117].i= 908
container[117].j= 515
container[117].angle= 333
container[117].value= 255


container[118].bin= 27
container[118].i= 908
container[118].j= 519
container[118].angle= 135
container[118].value= 255


container[119].bin= 18
container[119].i= 908
container[119].j= 520
container[119].angle= 90
container[119].value= 255


container[120].bin= 66
container[120].i= 909
container[120].j= 515
container[120].angle= 333
container[120].value= 255


container[121].bin= 27
container[121].i= 909
container[121].j= 521
container[121].angle= 135
container[121].value= 255


container[122].bin= 0
container[122].i= 910
container[122].j= 515
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 910
container[123].j= 521
container[123].angle= 180
container[123].value= 255


container[124].bin= 63
container[124].i= 911
container[124].j= 516
container[124].angle= 315
container[124].value= 255


container[125].bin= 27
container[125].i= 911
container[125].j= 522
container[125].angle= 135
container[125].value= 255


container[126].bin= 18
container[126].i= 911
container[126].j= 523
container[126].angle= 90
container[126].value= 255


container[127].bin= 63
container[127].i= 912
container[127].j= 517
container[127].angle= 315
container[127].value= 255


container[128].bin= 27
container[128].i= 912
container[128].j= 524
container[128].angle= 135
container[128].value= 255


container[129].bin= 0
container[129].i= 913
container[129].j= 517
container[129].angle= 0
container[129].value= 255


container[130].bin= 36
container[130].i= 913
container[130].j= 524
container[130].angle= 180
container[130].value= 255


container[131].bin= 0
container[131].i= 914
container[131].j= 517
container[131].angle= 0
container[131].value= 255


container[132].bin= 36
container[132].i= 914
container[132].j= 524
container[132].angle= 180
container[132].value= 255


