container[0].bin= 18
container[0].i= 156
container[0].j= 546
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 157
container[1].j= 545
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 157
container[2].j= 547
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 158
container[3].j= 544
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 158
container[4].j= 547
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 159
container[5].j= 535
container[5].angle= 90
container[5].value= 255


container[6].bin= 66
container[6].i= 159
container[6].j= 545
container[6].angle= 333
container[6].value= 255


container[7].bin= 27
container[7].i= 159
container[7].j= 548
container[7].angle= 135
container[7].value= 255


container[8].bin= 3
container[8].i= 160
container[8].j= 534
container[8].angle= 18
container[8].value= 255


container[9].bin= 32
container[9].i= 160
container[9].j= 536
container[9].angle= 161
container[9].value= 255


container[10].bin= 66
container[10].i= 160
container[10].j= 545
container[10].angle= 333
container[10].value= 255


container[11].bin= 27
container[11].i= 160
container[11].j= 549
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 161
container[12].j= 534
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 161
container[13].j= 536
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 161
container[14].j= 545
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 161
container[15].j= 549
container[15].angle= 180
container[15].value= 255


container[16].bin= 8
container[16].i= 162
container[16].j= 534
container[16].angle= 44
container[16].value= 255


container[17].bin= 18
container[17].i= 162
container[17].j= 535
container[17].angle= 90
container[17].value= 255


container[18].bin= 27
container[18].i= 162
container[18].j= 536
container[18].angle= 135
container[18].value= 255


container[19].bin= 18
container[19].i= 162
container[19].j= 537
container[19].angle= 90
container[19].value= 255


container[20].bin= 0
container[20].i= 162
container[20].j= 545
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 162
container[21].j= 549
container[21].angle= 180
container[21].value= 255


container[22].bin= 8
container[22].i= 163
container[22].j= 533
container[22].angle= 44
container[22].value= 255


container[23].bin= 27
container[23].i= 163
container[23].j= 538
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 163
container[24].j= 545
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 163
container[25].j= 549
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 164
container[26].j= 532
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 164
container[27].j= 538
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 164
container[28].j= 545
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 164
container[29].j= 549
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 165
container[30].j= 533
container[30].angle= 315
container[30].value= 255


container[31].bin= 30
container[31].i= 165
container[31].j= 539
container[31].angle= 153
container[31].value= 255


container[32].bin= 0
container[32].i= 165
container[32].j= 545
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 165
container[33].j= 549
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 166
container[34].j= 534
container[34].angle= 315
container[34].value= 255


container[35].bin= 32
container[35].i= 166
container[35].j= 539
container[35].angle= 161
container[35].value= 255


container[36].bin= 14
container[36].i= 166
container[36].j= 540
container[36].angle= 71
container[36].value= 255


container[37].bin= 12
container[37].i= 166
container[37].j= 541
container[37].angle= 63
container[37].value= 255


container[38].bin= 23
container[38].i= 166
container[38].j= 542
container[38].angle= 116
container[38].value= 255


container[39].bin= 27
container[39].i= 166
container[39].j= 543
container[39].angle= 135
container[39].value= 255


container[40].bin= 0
container[40].i= 166
container[40].j= 545
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 166
container[41].j= 549
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 167
container[42].j= 534
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 167
container[43].j= 538
container[43].angle= 180
container[43].value= 255


container[44].bin= 32
container[44].i= 167
container[44].j= 543
container[44].angle= 161
container[44].value= 255


container[45].bin= 5
container[45].i= 167
container[45].j= 545
container[45].angle= 26
container[45].value= 255


container[46].bin= 36
container[46].i= 167
container[46].j= 549
container[46].angle= 180
container[46].value= 255


container[47].bin= 0
container[47].i= 168
container[47].j= 534
container[47].angle= 0
container[47].value= 255


container[48].bin= 27
container[48].i= 168
container[48].j= 539
container[48].angle= 135
container[48].value= 255


container[49].bin= 8
container[49].i= 168
container[49].j= 545
container[49].angle= 44
container[49].value= 255


container[50].bin= 36
container[50].i= 168
container[50].j= 549
container[50].angle= 180
container[50].value= 255


container[51].bin= 63
container[51].i= 169
container[51].j= 535
container[51].angle= 315
container[51].value= 255


container[52].bin= 57
container[52].i= 169
container[52].j= 536
container[52].angle= 288
container[52].value= 255


container[53].bin= 18
container[53].i= 169
container[53].j= 541
container[53].angle= 90
container[53].value= 255


container[54].bin= 18
container[54].i= 169
container[54].j= 542
container[54].angle= 90
container[54].value= 255


container[55].bin= 36
container[55].i= 169
container[55].j= 549
container[55].angle= 180
container[55].value= 255


container[56].bin= 0
container[56].i= 170
container[56].j= 534
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 170
container[57].j= 549
container[57].angle= 180
container[57].value= 255


container[58].bin= 3
container[58].i= 171
container[58].j= 535
container[58].angle= 18
container[58].value= 255


container[59].bin= 8
container[59].i= 171
container[59].j= 536
container[59].angle= 44
container[59].value= 255


container[60].bin= 36
container[60].i= 171
container[60].j= 549
container[60].angle= 180
container[60].value= 255


container[61].bin= 66
container[61].i= 172
container[61].j= 535
container[61].angle= 333
container[61].value= 255


container[62].bin= 36
container[62].i= 172
container[62].j= 549
container[62].angle= 180
container[62].value= 255


container[63].bin= 66
container[63].i= 173
container[63].j= 536
container[63].angle= 333
container[63].value= 255


container[64].bin= 36
container[64].i= 173
container[64].j= 549
container[64].angle= 180
container[64].value= 255


container[65].bin= 63
container[65].i= 174
container[65].j= 536
container[65].angle= 315
container[65].value= 255


container[66].bin= 63
container[66].i= 174
container[66].j= 537
container[66].angle= 315
container[66].value= 255


container[67].bin= 27
container[67].i= 174
container[67].j= 550
container[67].angle= 135
container[67].value= 255


container[68].bin= 66
container[68].i= 175
container[68].j= 537
container[68].angle= 333
container[68].value= 255


container[69].bin= 27
container[69].i= 175
container[69].j= 551
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 176
container[70].j= 537
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 176
container[71].j= 551
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 177
container[72].j= 537
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 177
container[73].j= 551
container[73].angle= 180
container[73].value= 255


container[74].bin= 68
container[74].i= 178
container[74].j= 537
container[74].angle= 341
container[74].value= 255


container[75].bin= 57
container[75].i= 178
container[75].j= 539
container[75].angle= 288
container[75].value= 255


container[76].bin= 36
container[76].i= 178
container[76].j= 551
container[76].angle= 180
container[76].value= 255


container[77].bin= 0
container[77].i= 179
container[77].j= 537
container[77].angle= 0
container[77].value= 255


container[78].bin= 36
container[78].i= 179
container[78].j= 551
container[78].angle= 180
container[78].value= 255


container[79].bin= 3
container[79].i= 180
container[79].j= 538
container[79].angle= 18
container[79].value= 255


container[80].bin= 8
container[80].i= 180
container[80].j= 539
container[80].angle= 44
container[80].value= 255


container[81].bin= 36
container[81].i= 180
container[81].j= 551
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 181
container[82].j= 538
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 181
container[83].j= 551
container[83].angle= 180
container[83].value= 255


container[84].bin= 0
container[84].i= 182
container[84].j= 538
container[84].angle= 0
container[84].value= 255


container[85].bin= 36
container[85].i= 182
container[85].j= 551
container[85].angle= 180
container[85].value= 255


container[86].bin= 63
container[86].i= 183
container[86].j= 538
container[86].angle= 315
container[86].value= 255


container[87].bin= 63
container[87].i= 183
container[87].j= 539
container[87].angle= 315
container[87].value= 255


container[88].bin= 36
container[88].i= 183
container[88].j= 551
container[88].angle= 180
container[88].value= 255


container[89].bin= 66
container[89].i= 184
container[89].j= 539
container[89].angle= 333
container[89].value= 255


container[90].bin= 36
container[90].i= 184
container[90].j= 551
container[90].angle= 180
container[90].value= 255


container[91].bin= 0
container[91].i= 185
container[91].j= 539
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 185
container[92].j= 551
container[92].angle= 180
container[92].value= 255


container[93].bin= 66
container[93].i= 186
container[93].j= 540
container[93].angle= 333
container[93].value= 255


container[94].bin= 36
container[94].i= 186
container[94].j= 551
container[94].angle= 180
container[94].value= 255


container[95].bin= 66
container[95].i= 187
container[95].j= 540
container[95].angle= 333
container[95].value= 255


container[96].bin= 36
container[96].i= 187
container[96].j= 551
container[96].angle= 180
container[96].value= 255


container[97].bin= 0
container[97].i= 188
container[97].j= 540
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 188
container[98].j= 551
container[98].angle= 180
container[98].value= 255


container[99].bin= 0
container[99].i= 189
container[99].j= 540
container[99].angle= 0
container[99].value= 255


container[100].bin= 54
container[100].i= 189
container[100].j= 549
container[100].angle= 270
container[100].value= 255


container[101].bin= 0
container[101].i= 190
container[101].j= 540
container[101].angle= 0
container[101].value= 255


container[102].bin= 44
container[102].i= 190
container[102].j= 548
container[102].angle= 224
container[102].value= 255


container[103].bin= 63
container[103].i= 190
container[103].j= 550
container[103].angle= 315
container[103].value= 255


container[104].bin= 36
container[104].i= 190
container[104].j= 552
container[104].angle= 180
container[104].value= 255


container[105].bin= 0
container[105].i= 191
container[105].j= 540
container[105].angle= 0
container[105].value= 255


container[106].bin= 36
container[106].i= 191
container[106].j= 547
container[106].angle= 180
container[106].value= 255


container[107].bin= 0
container[107].i= 191
container[107].j= 550
container[107].angle= 0
container[107].value= 255


container[108].bin= 36
container[108].i= 191
container[108].j= 552
container[108].angle= 180
container[108].value= 255


container[109].bin= 63
container[109].i= 192
container[109].j= 541
container[109].angle= 315
container[109].value= 255


container[110].bin= 36
container[110].i= 192
container[110].j= 547
container[110].angle= 180
container[110].value= 255


container[111].bin= 68
container[111].i= 192
container[111].j= 550
container[111].angle= 341
container[111].value= 255


container[112].bin= 54
container[112].i= 192
container[112].j= 551
container[112].angle= 270
container[112].value= 255


container[113].bin= 39
container[113].i= 192
container[113].j= 552
container[113].angle= 198
container[113].value= 255


container[114].bin= 63
container[114].i= 193
container[114].j= 542
container[114].angle= 315
container[114].value= 255


container[115].bin= 36
container[115].i= 193
container[115].j= 547
container[115].angle= 180
container[115].value= 255


container[116].bin= 0
container[116].i= 194
container[116].j= 542
container[116].angle= 0
container[116].value= 255


container[117].bin= 36
container[117].i= 194
container[117].j= 547
container[117].angle= 180
container[117].value= 255


container[118].bin= 63
container[118].i= 195
container[118].j= 543
container[118].angle= 315
container[118].value= 255


container[119].bin= 36
container[119].i= 195
container[119].j= 547
container[119].angle= 180
container[119].value= 255


container[120].bin= 63
container[120].i= 196
container[120].j= 544
container[120].angle= 315
container[120].value= 255


container[121].bin= 36
container[121].i= 196
container[121].j= 547
container[121].angle= 180
container[121].value= 255


container[122].bin= 0
container[122].i= 197
container[122].j= 544
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 197
container[123].j= 547
container[123].angle= 180
container[123].value= 255


container[124].bin= 66
container[124].i= 198
container[124].j= 545
container[124].angle= 333
container[124].value= 255


container[125].bin= 54
container[125].i= 198
container[125].j= 546
container[125].angle= 270
container[125].value= 255


container[126].bin= 41
container[126].i= 198
container[126].j= 547
container[126].angle= 206
container[126].value= 255


container[127].bin= 66
container[127].i= 199
container[127].j= 545
container[127].angle= 333
container[127].value= 255


container[128].bin= 41
container[128].i= 199
container[128].j= 547
container[128].angle= 206
container[128].value= 255


container[129].bin= 0
container[129].i= 200
container[129].j= 545
container[129].angle= 0
container[129].value= 255


container[130].bin= 36
container[130].i= 200
container[130].j= 547
container[130].angle= 180
container[130].value= 255


container[131].bin= 0
container[131].i= 201
container[131].j= 545
container[131].angle= 0
container[131].value= 255


container[132].bin= 36
container[132].i= 201
container[132].j= 547
container[132].angle= 180
container[132].value= 255


container[133].bin= 3
container[133].i= 202
container[133].j= 537
container[133].angle= 18
container[133].value= 255


container[134].bin= 14
container[134].i= 202
container[134].j= 538
container[134].angle= 71
container[134].value= 255


container[135].bin= 27
container[135].i= 202
container[135].j= 539
container[135].angle= 135
container[135].value= 255


container[136].bin= 0
container[136].i= 202
container[136].j= 545
container[136].angle= 0
container[136].value= 255


container[137].bin= 36
container[137].i= 202
container[137].j= 547
container[137].angle= 180
container[137].value= 255


container[138].bin= 0
container[138].i= 203
container[138].j= 537
container[138].angle= 0
container[138].value= 255


container[139].bin= 30
container[139].i= 203
container[139].j= 539
container[139].angle= 153
container[139].value= 255


container[140].bin= 0
container[140].i= 203
container[140].j= 545
container[140].angle= 0
container[140].value= 255


container[141].bin= 36
container[141].i= 203
container[141].j= 547
container[141].angle= 180
container[141].value= 255


container[142].bin= 0
container[142].i= 204
container[142].j= 537
container[142].angle= 0
container[142].value= 255


container[143].bin= 27
container[143].i= 204
container[143].j= 540
container[143].angle= 135
container[143].value= 255


container[144].bin= 18
container[144].i= 204
container[144].j= 541
container[144].angle= 90
container[144].value= 255


container[145].bin= 18
container[145].i= 204
container[145].j= 542
container[145].angle= 90
container[145].value= 255


container[146].bin= 18
container[146].i= 204
container[146].j= 543
container[146].angle= 90
container[146].value= 255


container[147].bin= 18
container[147].i= 204
container[147].j= 544
container[147].angle= 90
container[147].value= 255


container[148].bin= 8
container[148].i= 204
container[148].j= 545
container[148].angle= 44
container[148].value= 255


container[149].bin= 36
container[149].i= 204
container[149].j= 547
container[149].angle= 180
container[149].value= 255


container[150].bin= 0
container[150].i= 205
container[150].j= 537
container[150].angle= 0
container[150].value= 255


container[151].bin= 0
container[151].i= 206
container[151].j= 537
container[151].angle= 0
container[151].value= 255


container[152].bin= 36
container[152].i= 206
container[152].j= 546
container[152].angle= 180
container[152].value= 255


container[153].bin= 63
container[153].i= 207
container[153].j= 538
container[153].angle= 315
container[153].value= 255


container[154].bin= 27
container[154].i= 207
container[154].j= 547
container[154].angle= 135
container[154].value= 255


container[155].bin= 18
container[155].i= 207
container[155].j= 548
container[155].angle= 90
container[155].value= 255


container[156].bin= 63
container[156].i= 208
container[156].j= 539
container[156].angle= 315
container[156].value= 255


container[157].bin= 27
container[157].i= 208
container[157].j= 549
container[157].angle= 135
container[157].value= 255


container[158].bin= 0
container[158].i= 209
container[158].j= 539
container[158].angle= 0
container[158].value= 255


container[159].bin= 36
container[159].i= 209
container[159].j= 549
container[159].angle= 180
container[159].value= 255


container[160].bin= 0
container[160].i= 210
container[160].j= 539
container[160].angle= 0
container[160].value= 255


container[161].bin= 27
container[161].i= 210
container[161].j= 550
container[161].angle= 135
container[161].value= 255


container[162].bin= 0
container[162].i= 211
container[162].j= 539
container[162].angle= 0
container[162].value= 255


container[163].bin= 27
container[163].i= 211
container[163].j= 551
container[163].angle= 135
container[163].value= 255


container[164].bin= 0
container[164].i= 212
container[164].j= 539
container[164].angle= 0
container[164].value= 255


container[165].bin= 36
container[165].i= 212
container[165].j= 551
container[165].angle= 180
container[165].value= 255


container[166].bin= 66
container[166].i= 213
container[166].j= 540
container[166].angle= 333
container[166].value= 255


container[167].bin= 30
container[167].i= 213
container[167].j= 552
container[167].angle= 153
container[167].value= 255


container[168].bin= 66
container[168].i= 214
container[168].j= 540
container[168].angle= 333
container[168].value= 255


container[169].bin= 27
container[169].i= 214
container[169].j= 552
container[169].angle= 135
container[169].value= 255


container[170].bin= 27
container[170].i= 214
container[170].j= 553
container[170].angle= 135
container[170].value= 255


container[171].bin= 0
container[171].i= 215
container[171].j= 540
container[171].angle= 0
container[171].value= 255


container[172].bin= 32
container[172].i= 215
container[172].j= 553
container[172].angle= 161
container[172].value= 255


container[173].bin= 27
container[173].i= 215
container[173].j= 554
container[173].angle= 135
container[173].value= 255


container[174].bin= 63
container[174].i= 216
container[174].j= 541
container[174].angle= 315
container[174].value= 255


container[175].bin= 36
container[175].i= 216
container[175].j= 552
container[175].angle= 180
container[175].value= 255


container[176].bin= 27
container[176].i= 216
container[176].j= 554
container[176].angle= 135
container[176].value= 255


container[177].bin= 63
container[177].i= 217
container[177].j= 542
container[177].angle= 315
container[177].value= 255


container[178].bin= 30
container[178].i= 217
container[178].j= 555
container[178].angle= 153
container[178].value= 255


container[179].bin= 0
container[179].i= 218
container[179].j= 542
container[179].angle= 0
container[179].value= 255


container[180].bin= 30
container[180].i= 218
container[180].j= 555
container[180].angle= 153
container[180].value= 255


container[181].bin= 0
container[181].i= 219
container[181].j= 542
container[181].angle= 0
container[181].value= 255


container[182].bin= 27
container[182].i= 219
container[182].j= 556
container[182].angle= 135
container[182].value= 255


container[183].bin= 63
container[183].i= 220
container[183].j= 543
container[183].angle= 315
container[183].value= 255


container[184].bin= 27
container[184].i= 220
container[184].j= 557
container[184].angle= 135
container[184].value= 255


container[185].bin= 63
container[185].i= 221
container[185].j= 544
container[185].angle= 315
container[185].value= 255


container[186].bin= 36
container[186].i= 221
container[186].j= 557
container[186].angle= 180
container[186].value= 255


container[187].bin= 66
container[187].i= 222
container[187].j= 545
container[187].angle= 333
container[187].value= 255


container[188].bin= 36
container[188].i= 222
container[188].j= 557
container[188].angle= 180
container[188].value= 255


container[189].bin= 66
container[189].i= 223
container[189].j= 545
container[189].angle= 333
container[189].value= 255


container[190].bin= 36
container[190].i= 223
container[190].j= 557
container[190].angle= 180
container[190].value= 255


container[191].bin= 0
container[191].i= 224
container[191].j= 545
container[191].angle= 0
container[191].value= 255


container[192].bin= 36
container[192].i= 224
container[192].j= 557
container[192].angle= 180
container[192].value= 255


container[193].bin= 0
container[193].i= 225
container[193].j= 545
container[193].angle= 0
container[193].value= 255


container[194].bin= 36
container[194].i= 225
container[194].j= 557
container[194].angle= 180
container[194].value= 255


container[195].bin= 0
container[195].i= 226
container[195].j= 545
container[195].angle= 0
container[195].value= 255


container[196].bin= 36
container[196].i= 226
container[196].j= 557
container[196].angle= 180
container[196].value= 255


container[197].bin= 0
container[197].i= 227
container[197].j= 545
container[197].angle= 0
container[197].value= 255


container[198].bin= 36
container[198].i= 227
container[198].j= 557
container[198].angle= 180
container[198].value= 255


container[199].bin= 0
container[199].i= 228
container[199].j= 545
container[199].angle= 0
container[199].value= 255


container[200].bin= 44
container[200].i= 228
container[200].j= 557
container[200].angle= 224
container[200].value= 255


container[201].bin= 0
container[201].i= 229
container[201].j= 545
container[201].angle= 0
container[201].value= 255


container[202].bin= 44
container[202].i= 229
container[202].j= 556
container[202].angle= 224
container[202].value= 255


container[203].bin= 0
container[203].i= 230
container[203].j= 545
container[203].angle= 0
container[203].value= 255


container[204].bin= 36
container[204].i= 230
container[204].j= 555
container[204].angle= 180
container[204].value= 255


container[205].bin= 0
container[205].i= 231
container[205].j= 545
container[205].angle= 0
container[205].value= 255


container[206].bin= 36
container[206].i= 231
container[206].j= 555
container[206].angle= 180
container[206].value= 255


container[207].bin= 0
container[207].i= 232
container[207].j= 545
container[207].angle= 0
container[207].value= 255


container[208].bin= 36
container[208].i= 232
container[208].j= 555
container[208].angle= 180
container[208].value= 255


container[209].bin= 0
container[209].i= 233
container[209].j= 545
container[209].angle= 0
container[209].value= 255


container[210].bin= 36
container[210].i= 233
container[210].j= 555
container[210].angle= 180
container[210].value= 255


container[211].bin= 63
container[211].i= 234
container[211].j= 546
container[211].angle= 315
container[211].value= 255


container[212].bin= 36
container[212].i= 234
container[212].j= 555
container[212].angle= 180
container[212].value= 255


container[213].bin= 63
container[213].i= 235
container[213].j= 547
container[213].angle= 315
container[213].value= 255


container[214].bin= 36
container[214].i= 235
container[214].j= 555
container[214].angle= 180
container[214].value= 255


container[215].bin= 0
container[215].i= 236
container[215].j= 547
container[215].angle= 0
container[215].value= 255


container[216].bin= 36
container[216].i= 236
container[216].j= 555
container[216].angle= 180
container[216].value= 255


container[217].bin= 0
container[217].i= 237
container[217].j= 547
container[217].angle= 0
container[217].value= 255


container[218].bin= 36
container[218].i= 237
container[218].j= 555
container[218].angle= 180
container[218].value= 255


container[219].bin= 0
container[219].i= 238
container[219].j= 547
container[219].angle= 0
container[219].value= 255


container[220].bin= 36
container[220].i= 238
container[220].j= 555
container[220].angle= 180
container[220].value= 255


container[221].bin= 0
container[221].i= 239
container[221].j= 547
container[221].angle= 0
container[221].value= 255


container[222].bin= 36
container[222].i= 239
container[222].j= 555
container[222].angle= 180
container[222].value= 255


container[223].bin= 0
container[223].i= 240
container[223].j= 547
container[223].angle= 0
container[223].value= 255


container[224].bin= 36
container[224].i= 240
container[224].j= 555
container[224].angle= 180
container[224].value= 255


container[225].bin= 0
container[225].i= 241
container[225].j= 547
container[225].angle= 0
container[225].value= 255


container[226].bin= 36
container[226].i= 241
container[226].j= 555
container[226].angle= 180
container[226].value= 255


container[227].bin= 0
container[227].i= 242
container[227].j= 547
container[227].angle= 0
container[227].value= 255


container[228].bin= 36
container[228].i= 242
container[228].j= 555
container[228].angle= 180
container[228].value= 255


container[229].bin= 0
container[229].i= 243
container[229].j= 547
container[229].angle= 0
container[229].value= 255


container[230].bin= 27
container[230].i= 243
container[230].j= 556
container[230].angle= 135
container[230].value= 255


container[231].bin= 0
container[231].i= 244
container[231].j= 547
container[231].angle= 0
container[231].value= 255


container[232].bin= 27
container[232].i= 244
container[232].j= 557
container[232].angle= 135
container[232].value= 255


container[233].bin= 0
container[233].i= 245
container[233].j= 547
container[233].angle= 0
container[233].value= 255


container[234].bin= 36
container[234].i= 245
container[234].j= 557
container[234].angle= 180
container[234].value= 255


container[235].bin= 66
container[235].i= 246
container[235].j= 548
container[235].angle= 333
container[235].value= 255


container[236].bin= 54
container[236].i= 246
container[236].j= 553
container[236].angle= 270
container[236].value= 255


container[237].bin= 54
container[237].i= 246
container[237].j= 554
container[237].angle= 270
container[237].value= 255


container[238].bin= 54
container[238].i= 246
container[238].j= 555
container[238].angle= 270
container[238].value= 255


container[239].bin= 54
container[239].i= 246
container[239].j= 556
container[239].angle= 270
container[239].value= 255


container[240].bin= 44
container[240].i= 246
container[240].j= 557
container[240].angle= 224
container[240].value= 255


container[241].bin= 66
container[241].i= 247
container[241].j= 548
container[241].angle= 333
container[241].value= 255


container[242].bin= 44
container[242].i= 247
container[242].j= 552
container[242].angle= 224
container[242].value= 255


container[243].bin= 0
container[243].i= 248
container[243].j= 548
container[243].angle= 0
container[243].value= 255


container[244].bin= 36
container[244].i= 248
container[244].j= 551
container[244].angle= 180
container[244].value= 255


container[245].bin= 63
container[245].i= 249
container[245].j= 549
container[245].angle= 315
container[245].value= 255


container[246].bin= 54
container[246].i= 249
container[246].j= 550
container[246].angle= 270
container[246].value= 255


container[247].bin= 44
container[247].i= 249
container[247].j= 551
container[247].angle= 224
container[247].value= 255


