container[0].bin= 18
container[0].i= 357
container[0].j= 413
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 358
container[1].j= 412
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 358
container[2].j= 414
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 359
container[3].j= 412
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 359
container[4].j= 414
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 360
container[5].j= 412
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 360
container[6].j= 414
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 361
container[7].j= 412
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 361
container[8].j= 414
container[8].angle= 153
container[8].value= 255


container[9].bin= 3
container[9].i= 362
container[9].j= 412
container[9].angle= 18
container[9].value= 255


container[10].bin= 3
container[10].i= 363
container[10].j= 410
container[10].angle= 18
container[10].value= 255


container[11].bin= 14
container[11].i= 363
container[11].j= 411
container[11].angle= 71
container[11].value= 255


container[12].bin= 27
container[12].i= 363
container[12].j= 415
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 363
container[13].j= 416
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 363
container[14].j= 417
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 363
container[15].j= 418
container[15].angle= 90
container[15].value= 255


container[16].bin= 18
container[16].i= 363
container[16].j= 419
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 363
container[17].j= 420
container[17].angle= 90
container[17].value= 255


container[18].bin= 18
container[18].i= 363
container[18].j= 421
container[18].angle= 90
container[18].value= 255


container[19].bin= 0
container[19].i= 364
container[19].j= 410
container[19].angle= 0
container[19].value= 255


container[20].bin= 27
container[20].i= 364
container[20].j= 422
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 365
container[21].j= 410
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 365
container[22].j= 422
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 366
container[23].j= 411
container[23].angle= 315
container[23].value= 255


container[24].bin= 36
container[24].i= 366
container[24].j= 422
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 367
container[25].j= 412
container[25].angle= 315
container[25].value= 255


container[26].bin= 36
container[26].i= 367
container[26].j= 422
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 368
container[27].j= 412
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 368
container[28].j= 422
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 369
container[29].j= 412
container[29].angle= 0
container[29].value= 255


container[30].bin= 41
container[30].i= 369
container[30].j= 422
container[30].angle= 206
container[30].value= 255


container[31].bin= 0
container[31].i= 370
container[31].j= 412
container[31].angle= 0
container[31].value= 255


container[32].bin= 41
container[32].i= 370
container[32].j= 422
container[32].angle= 206
container[32].value= 255


container[33].bin= 0
container[33].i= 371
container[33].j= 412
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 371
container[34].j= 421
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 372
container[35].j= 413
container[35].angle= 315
container[35].value= 255


container[36].bin= 36
container[36].i= 372
container[36].j= 421
container[36].angle= 180
container[36].value= 255


container[37].bin= 63
container[37].i= 373
container[37].j= 414
container[37].angle= 315
container[37].value= 255


container[38].bin= 36
container[38].i= 373
container[38].j= 421
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 374
container[39].j= 414
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 374
container[40].j= 421
container[40].angle= 180
container[40].value= 255


container[41].bin= 66
container[41].i= 375
container[41].j= 415
container[41].angle= 333
container[41].value= 255


container[42].bin= 36
container[42].i= 375
container[42].j= 421
container[42].angle= 180
container[42].value= 255


container[43].bin= 66
container[43].i= 376
container[43].j= 415
container[43].angle= 333
container[43].value= 255


container[44].bin= 36
container[44].i= 376
container[44].j= 421
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 377
container[45].j= 415
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 377
container[46].j= 421
container[46].angle= 180
container[46].value= 255


container[47].bin= 63
container[47].i= 378
container[47].j= 416
container[47].angle= 315
container[47].value= 255


container[48].bin= 54
container[48].i= 378
container[48].j= 417
container[48].angle= 270
container[48].value= 255


container[49].bin= 36
container[49].i= 378
container[49].j= 421
container[49].angle= 180
container[49].value= 255


container[50].bin= 63
container[50].i= 379
container[50].j= 418
container[50].angle= 315
container[50].value= 255


container[51].bin= 36
container[51].i= 379
container[51].j= 421
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 380
container[52].j= 418
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 380
container[53].j= 421
container[53].angle= 180
container[53].value= 255


container[54].bin= 63
container[54].i= 381
container[54].j= 419
container[54].angle= 315
container[54].value= 255


container[55].bin= 54
container[55].i= 381
container[55].j= 420
container[55].angle= 270
container[55].value= 255


container[56].bin= 44
container[56].i= 381
container[56].j= 421
container[56].angle= 224
container[56].value= 255


