container[0].bin= 8
container[0].i= 325
container[0].j= 176
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 325
container[1].j= 177
container[1].angle= 135
container[1].value= 255


container[2].bin= 3
container[2].i= 326
container[2].j= 175
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 327
container[3].j= 174
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 327
container[4].j= 178
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 328
container[5].j= 176
container[5].angle= 341
container[5].value= 255


container[6].bin= 36
container[6].i= 328
container[6].j= 178
container[6].angle= 180
container[6].value= 255


container[7].bin= 68
container[7].i= 329
container[7].j= 176
container[7].angle= 341
container[7].value= 255


container[8].bin= 54
container[8].i= 329
container[8].j= 177
container[8].angle= 270
container[8].value= 255


container[9].bin= 39
container[9].i= 329
container[9].j= 178
container[9].angle= 198
container[9].value= 255


