container[0].bin= 14
container[0].i= 429
container[0].j= 286
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 429
container[1].j= 287
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 430
container[2].j= 285
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 431
container[3].j= 285
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 431
container[4].j= 287
container[4].angle= 206
container[4].value= 255


container[5].bin= 68
container[5].i= 432
container[5].j= 285
container[5].angle= 341
container[5].value= 255


container[6].bin= 39
container[6].i= 432
container[6].j= 287
container[6].angle= 198
container[6].value= 255


