container[0].bin= 3
container[0].i= 214
container[0].j= 362
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 214
container[1].j= 363
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 214
container[2].j= 364
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 215
container[3].j= 362
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 215
container[4].j= 364
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 216
container[5].j= 362
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 217
container[6].j= 362
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 218
container[7].j= 362
container[7].angle= 0
container[7].value= 255


container[8].bin= 63
container[8].i= 219
container[8].j= 363
container[8].angle= 315
container[8].value= 255


container[9].bin= 44
container[9].i= 219
container[9].j= 364
container[9].angle= 224
container[9].value= 255


