container[0].bin= 8
container[0].i= 267
container[0].j= 37
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 267
container[1].j= 38
container[1].angle= 135
container[1].value= 255


container[2].bin= 5
container[2].i= 268
container[2].j= 36
container[2].angle= 26
container[2].value= 255


container[3].bin= 30
container[3].i= 268
container[3].j= 39
container[3].angle= 153
container[3].value= 255


container[4].bin= 5
container[4].i= 269
container[4].j= 36
container[4].angle= 26
container[4].value= 255


container[5].bin= 27
container[5].i= 269
container[5].j= 39
container[5].angle= 135
container[5].value= 255


container[6].bin= 27
container[6].i= 269
container[6].j= 40
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 270
container[7].j= 35
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 270
container[8].j= 40
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 271
container[9].j= 35
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 271
container[10].j= 41
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 272
container[11].j= 35
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 272
container[12].j= 41
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 273
container[13].j= 35
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 273
container[14].j= 41
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 274
container[15].j= 35
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 274
container[16].j= 42
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 275
container[17].j= 36
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 275
container[18].j= 42
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 276
container[19].j= 36
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 276
container[20].j= 43
container[20].angle= 153
container[20].value= 255


container[21].bin= 63
container[21].i= 277
container[21].j= 37
container[21].angle= 315
container[21].value= 255


container[22].bin= 54
container[22].i= 277
container[22].j= 38
container[22].angle= 270
container[22].value= 255


container[23].bin= 54
container[23].i= 277
container[23].j= 39
container[23].angle= 270
container[23].value= 255


container[24].bin= 30
container[24].i= 277
container[24].j= 43
container[24].angle= 153
container[24].value= 255


container[25].bin= 59
container[25].i= 278
container[25].j= 40
container[25].angle= 296
container[25].value= 255


container[26].bin= 63
container[26].i= 278
container[26].j= 41
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 278
container[27].j= 43
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 279
container[28].j= 41
container[28].angle= 315
container[28].value= 255


container[29].bin= 59
container[29].i= 279
container[29].j= 42
container[29].angle= 296
container[29].value= 255


container[30].bin= 44
container[30].i= 279
container[30].j= 43
container[30].angle= 224
container[30].value= 255


