container[0].bin= 18
container[0].i= 878
container[0].j= 116
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 879
container[1].j= 115
container[1].angle= 0
container[1].value= 255


