container[0].bin= 8
container[0].i= 219
container[0].j= 137
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 219
container[1].j= 138
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 219
container[2].j= 139
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 220
container[3].j= 136
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 220
container[4].j= 137
container[4].angle= 44
container[4].value= 255


container[5].bin= 30
container[5].i= 220
container[5].j= 140
container[5].angle= 153
container[5].value= 255


container[6].bin= 8
container[6].i= 221
container[6].j= 135
container[6].angle= 44
container[6].value= 255


container[7].bin= 8
container[7].i= 221
container[7].j= 136
container[7].angle= 44
container[7].value= 255


container[8].bin= 27
container[8].i= 221
container[8].j= 140
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 221
container[9].j= 141
container[9].angle= 135
container[9].value= 255


container[10].bin= 5
container[10].i= 222
container[10].j= 135
container[10].angle= 26
container[10].value= 255


container[11].bin= 27
container[11].i= 222
container[11].j= 141
container[11].angle= 135
container[11].value= 255


container[12].bin= 27
container[12].i= 222
container[12].j= 142
container[12].angle= 135
container[12].value= 255


container[13].bin= 66
container[13].i= 223
container[13].j= 135
container[13].angle= 333
container[13].value= 255


container[14].bin= 30
container[14].i= 223
container[14].j= 142
container[14].angle= 153
container[14].value= 255


container[15].bin= 66
container[15].i= 224
container[15].j= 135
container[15].angle= 333
container[15].value= 255


container[16].bin= 30
container[16].i= 224
container[16].j= 143
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 225
container[17].j= 135
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 225
container[18].j= 143
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 226
container[19].j= 136
container[19].angle= 333
container[19].value= 255


container[20].bin= 36
container[20].i= 226
container[20].j= 143
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 227
container[21].j= 136
container[21].angle= 315
container[21].value= 255


container[22].bin= 59
container[22].i= 227
container[22].j= 137
container[22].angle= 296
container[22].value= 255


container[23].bin= 30
container[23].i= 227
container[23].j= 144
container[23].angle= 153
container[23].value= 255


container[24].bin= 59
container[24].i= 228
container[24].j= 138
container[24].angle= 296
container[24].value= 255


container[25].bin= 63
container[25].i= 228
container[25].j= 139
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 228
container[26].j= 144
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 229
container[27].j= 139
container[27].angle= 315
container[27].value= 255


container[28].bin= 63
container[28].i= 229
container[28].j= 140
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 229
container[29].j= 144
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 230
container[30].j= 140
container[30].angle= 315
container[30].value= 255


container[31].bin= 63
container[31].i= 230
container[31].j= 141
container[31].angle= 315
container[31].value= 255


container[32].bin= 36
container[32].i= 230
container[32].j= 144
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 231
container[33].j= 141
container[33].angle= 315
container[33].value= 255


container[34].bin= 63
container[34].i= 231
container[34].j= 142
container[34].angle= 315
container[34].value= 255


container[35].bin= 36
container[35].i= 231
container[35].j= 144
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 232
container[36].j= 142
container[36].angle= 315
container[36].value= 255


container[37].bin= 59
container[37].i= 232
container[37].j= 143
container[37].angle= 296
container[37].value= 255


container[38].bin= 44
container[38].i= 232
container[38].j= 144
container[38].angle= 224
container[38].value= 255


