container[0].bin= 8
container[0].i= 190
container[0].j= 13
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 190
container[1].j= 14
container[1].angle= 116
container[1].value= 255


container[2].bin= 23
container[2].i= 190
container[2].j= 15
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 190
container[3].j= 16
container[3].angle= 90
container[3].value= 255


container[4].bin= 5
container[4].i= 191
container[4].j= 12
container[4].angle= 26
container[4].value= 255


container[5].bin= 23
container[5].i= 191
container[5].j= 17
container[5].angle= 116
container[5].value= 255


container[6].bin= 27
container[6].i= 191
container[6].j= 18
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 192
container[7].j= 12
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 192
container[8].j= 18
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 192
container[9].j= 19
container[9].angle= 135
container[9].value= 255


container[10].bin= 66
container[10].i= 193
container[10].j= 12
container[10].angle= 333
container[10].value= 255


container[11].bin= 30
container[11].i= 193
container[11].j= 19
container[11].angle= 153
container[11].value= 255


container[12].bin= 66
container[12].i= 194
container[12].j= 13
container[12].angle= 333
container[12].value= 255


container[13].bin= 36
container[13].i= 194
container[13].j= 19
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 195
container[14].j= 13
container[14].angle= 333
container[14].value= 255


container[15].bin= 36
container[15].i= 195
container[15].j= 19
container[15].angle= 180
container[15].value= 255


container[16].bin= 66
container[16].i= 196
container[16].j= 14
container[16].angle= 333
container[16].value= 255


container[17].bin= 36
container[17].i= 196
container[17].j= 19
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 197
container[18].j= 14
container[18].angle= 315
container[18].value= 255


container[19].bin= 63
container[19].i= 197
container[19].j= 15
container[19].angle= 315
container[19].value= 255


container[20].bin= 30
container[20].i= 197
container[20].j= 20
container[20].angle= 153
container[20].value= 255


container[21].bin= 18
container[21].i= 197
container[21].j= 28
container[21].angle= 90
container[21].value= 255


container[22].bin= 66
container[22].i= 198
container[22].j= 15
container[22].angle= 333
container[22].value= 255


container[23].bin= 30
container[23].i= 198
container[23].j= 20
container[23].angle= 153
container[23].value= 255


container[24].bin= 3
container[24].i= 198
container[24].j= 27
container[24].angle= 18
container[24].value= 255


container[25].bin= 32
container[25].i= 198
container[25].j= 29
container[25].angle= 161
container[25].value= 255


container[26].bin= 66
container[26].i= 199
container[26].j= 16
container[26].angle= 333
container[26].value= 255


container[27].bin= 36
container[27].i= 199
container[27].j= 20
container[27].angle= 180
container[27].value= 255


container[28].bin= 5
container[28].i= 199
container[28].j= 27
container[28].angle= 26
container[28].value= 255


container[29].bin= 36
container[29].i= 199
container[29].j= 29
container[29].angle= 180
container[29].value= 255


container[30].bin= 66
container[30].i= 200
container[30].j= 16
container[30].angle= 333
container[30].value= 255


container[31].bin= 36
container[31].i= 200
container[31].j= 20
container[31].angle= 180
container[31].value= 255


container[32].bin= 8
container[32].i= 200
container[32].j= 26
container[32].angle= 44
container[32].value= 255


container[33].bin= 8
container[33].i= 200
container[33].j= 27
container[33].angle= 44
container[33].value= 255


container[34].bin= 30
container[34].i= 200
container[34].j= 29
container[34].angle= 153
container[34].value= 255


container[35].bin= 0
container[35].i= 201
container[35].j= 16
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 201
container[36].j= 20
container[36].angle= 180
container[36].value= 255


container[37].bin= 5
container[37].i= 201
container[37].j= 26
container[37].angle= 26
container[37].value= 255


container[38].bin= 30
container[38].i= 201
container[38].j= 29
container[38].angle= 153
container[38].value= 255


container[39].bin= 66
container[39].i= 202
container[39].j= 17
container[39].angle= 333
container[39].value= 255


container[40].bin= 30
container[40].i= 202
container[40].j= 21
container[40].angle= 153
container[40].value= 255


container[41].bin= 5
container[41].i= 202
container[41].j= 25
container[41].angle= 26
container[41].value= 255


container[42].bin= 36
container[42].i= 202
container[42].j= 29
container[42].angle= 180
container[42].value= 255


container[43].bin= 66
container[43].i= 203
container[43].j= 17
container[43].angle= 333
container[43].value= 255


container[44].bin= 27
container[44].i= 203
container[44].j= 21
container[44].angle= 135
container[44].value= 255


container[45].bin= 23
container[45].i= 203
container[45].j= 22
container[45].angle= 116
container[45].value= 255


container[46].bin= 18
container[46].i= 203
container[46].j= 23
container[46].angle= 90
container[46].value= 255


container[47].bin= 12
container[47].i= 203
container[47].j= 24
container[47].angle= 63
container[47].value= 255


container[48].bin= 8
container[48].i= 203
container[48].j= 25
container[48].angle= 44
container[48].value= 255


container[49].bin= 30
container[49].i= 203
container[49].j= 30
container[49].angle= 153
container[49].value= 255


container[50].bin= 66
container[50].i= 204
container[50].j= 18
container[50].angle= 333
container[50].value= 255


container[51].bin= 30
container[51].i= 204
container[51].j= 30
container[51].angle= 153
container[51].value= 255


container[52].bin= 66
container[52].i= 205
container[52].j= 18
container[52].angle= 333
container[52].value= 255


container[53].bin= 36
container[53].i= 205
container[53].j= 30
container[53].angle= 180
container[53].value= 255


container[54].bin= 66
container[54].i= 206
container[54].j= 19
container[54].angle= 333
container[54].value= 255


container[55].bin= 30
container[55].i= 206
container[55].j= 31
container[55].angle= 153
container[55].value= 255


container[56].bin= 63
container[56].i= 207
container[56].j= 19
container[56].angle= 315
container[56].value= 255


container[57].bin= 63
container[57].i= 207
container[57].j= 20
container[57].angle= 315
container[57].value= 255


container[58].bin= 30
container[58].i= 207
container[58].j= 31
container[58].angle= 153
container[58].value= 255


container[59].bin= 63
container[59].i= 208
container[59].j= 20
container[59].angle= 315
container[59].value= 255


container[60].bin= 59
container[60].i= 208
container[60].j= 21
container[60].angle= 296
container[60].value= 255


container[61].bin= 54
container[61].i= 208
container[61].j= 22
container[61].angle= 270
container[61].value= 255


container[62].bin= 54
container[62].i= 208
container[62].j= 23
container[62].angle= 270
container[62].value= 255


container[63].bin= 54
container[63].i= 208
container[63].j= 24
container[63].angle= 270
container[63].value= 255


container[64].bin= 36
container[64].i= 208
container[64].j= 31
container[64].angle= 180
container[64].value= 255


container[65].bin= 59
container[65].i= 209
container[65].j= 25
container[65].angle= 296
container[65].value= 255


container[66].bin= 59
container[66].i= 209
container[66].j= 26
container[66].angle= 296
container[66].value= 255


container[67].bin= 54
container[67].i= 209
container[67].j= 27
container[67].angle= 270
container[67].value= 255


container[68].bin= 54
container[68].i= 209
container[68].j= 28
container[68].angle= 270
container[68].value= 255


container[69].bin= 54
container[69].i= 209
container[69].j= 29
container[69].angle= 270
container[69].value= 255


container[70].bin= 54
container[70].i= 209
container[70].j= 30
container[70].angle= 270
container[70].value= 255


container[71].bin= 44
container[71].i= 209
container[71].j= 31
container[71].angle= 224
container[71].value= 255


