container[0].bin= 18
container[0].i= 414
container[0].j= 273
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 414
container[1].j= 274
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 414
container[2].j= 278
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 415
container[3].j= 272
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 415
container[4].j= 275
container[4].angle= 135
container[4].value= 255


container[5].bin= 32
container[5].i= 415
container[5].j= 279
container[5].angle= 161
container[5].value= 255


container[6].bin= 66
container[6].i= 416
container[6].j= 272
container[6].angle= 333
container[6].value= 255


container[7].bin= 36
container[7].i= 416
container[7].j= 275
container[7].angle= 180
container[7].value= 255


container[8].bin= 36
container[8].i= 416
container[8].j= 279
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 417
container[9].j= 272
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 417
container[10].j= 276
container[10].angle= 135
container[10].value= 255


container[11].bin= 8
container[11].i= 417
container[11].j= 277
container[11].angle= 44
container[11].value= 255


container[12].bin= 18
container[12].i= 417
container[12].j= 278
container[12].angle= 90
container[12].value= 255


container[13].bin= 27
container[13].i= 417
container[13].j= 279
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 417
container[14].j= 280
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 417
container[15].j= 281
container[15].angle= 90
container[15].value= 255


container[16].bin= 12
container[16].i= 417
container[16].j= 282
container[16].angle= 63
container[16].value= 255


container[17].bin= 18
container[17].i= 417
container[17].j= 283
container[17].angle= 90
container[17].value= 255


container[18].bin= 27
container[18].i= 417
container[18].j= 284
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 418
container[19].j= 272
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 418
container[20].j= 284
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 419
container[21].j= 272
container[21].angle= 0
container[21].value= 255


container[22].bin= 41
container[22].i= 419
container[22].j= 284
container[22].angle= 206
container[22].value= 255


container[23].bin= 0
container[23].i= 420
container[23].j= 272
container[23].angle= 0
container[23].value= 255


container[24].bin= 54
container[24].i= 420
container[24].j= 275
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 420
container[25].j= 276
container[25].angle= 270
container[25].value= 255


container[26].bin= 36
container[26].i= 420
container[26].j= 283
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 421
container[27].j= 272
container[27].angle= 0
container[27].value= 255


container[28].bin= 44
container[28].i= 421
container[28].j= 274
container[28].angle= 224
container[28].value= 255


container[29].bin= 59
container[29].i= 421
container[29].j= 277
container[29].angle= 296
container[29].value= 255


container[30].bin= 54
container[30].i= 421
container[30].j= 278
container[30].angle= 270
container[30].value= 255


container[31].bin= 57
container[31].i= 421
container[31].j= 279
container[31].angle= 288
container[31].value= 255


container[32].bin= 36
container[32].i= 421
container[32].j= 283
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 422
container[33].j= 272
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 422
container[34].j= 274
container[34].angle= 180
container[34].value= 255


container[35].bin= 68
container[35].i= 422
container[35].j= 279
container[35].angle= 341
container[35].value= 255


container[36].bin= 36
container[36].i= 422
container[36].j= 283
container[36].angle= 180
container[36].value= 255


container[37].bin= 68
container[37].i= 423
container[37].j= 272
container[37].angle= 341
container[37].value= 255


container[38].bin= 54
container[38].i= 423
container[38].j= 273
container[38].angle= 270
container[38].value= 255


container[39].bin= 39
container[39].i= 423
container[39].j= 274
container[39].angle= 198
container[39].value= 255


container[40].bin= 66
container[40].i= 423
container[40].j= 280
container[40].angle= 333
container[40].value= 255


container[41].bin= 36
container[41].i= 423
container[41].j= 283
container[41].angle= 180
container[41].value= 255


container[42].bin= 66
container[42].i= 424
container[42].j= 280
container[42].angle= 333
container[42].value= 255


container[43].bin= 36
container[43].i= 424
container[43].j= 283
container[43].angle= 180
container[43].value= 255


container[44].bin= 0
container[44].i= 425
container[44].j= 280
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 425
container[45].j= 283
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 426
container[46].j= 280
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 426
container[47].j= 283
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 427
container[48].j= 280
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 427
container[49].j= 283
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 428
container[50].j= 280
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 428
container[51].j= 283
container[51].angle= 180
container[51].value= 255


container[52].bin= 5
container[52].i= 429
container[52].j= 280
container[52].angle= 26
container[52].value= 255


container[53].bin= 36
container[53].i= 429
container[53].j= 283
container[53].angle= 180
container[53].value= 255


container[54].bin= 14
container[54].i= 430
container[54].j= 278
container[54].angle= 71
container[54].value= 255


container[55].bin= 12
container[55].i= 430
container[55].j= 279
container[55].angle= 63
container[55].value= 255


container[56].bin= 8
container[56].i= 430
container[56].j= 280
container[56].angle= 44
container[56].value= 255


container[57].bin= 36
container[57].i= 430
container[57].j= 283
container[57].angle= 180
container[57].value= 255


container[58].bin= 3
container[58].i= 431
container[58].j= 277
container[58].angle= 18
container[58].value= 255


container[59].bin= 8
container[59].i= 431
container[59].j= 278
container[59].angle= 44
container[59].value= 255


container[60].bin= 36
container[60].i= 431
container[60].j= 283
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 432
container[61].j= 277
container[61].angle= 0
container[61].value= 255


container[62].bin= 0
container[62].i= 432
container[62].j= 280
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 432
container[63].j= 283
container[63].angle= 180
container[63].value= 255


container[64].bin= 0
container[64].i= 433
container[64].j= 277
container[64].angle= 0
container[64].value= 255


container[65].bin= 18
container[65].i= 433
container[65].j= 279
container[65].angle= 90
container[65].value= 255


container[66].bin= 8
container[66].i= 433
container[66].j= 280
container[66].angle= 44
container[66].value= 255


container[67].bin= 36
container[67].i= 433
container[67].j= 283
container[67].angle= 180
container[67].value= 255


container[68].bin= 0
container[68].i= 434
container[68].j= 277
container[68].angle= 0
container[68].value= 255


container[69].bin= 30
container[69].i= 434
container[69].j= 284
container[69].angle= 153
container[69].value= 255


container[70].bin= 63
container[70].i= 435
container[70].j= 278
container[70].angle= 315
container[70].value= 255


container[71].bin= 54
container[71].i= 435
container[71].j= 279
container[71].angle= 270
container[71].value= 255


container[72].bin= 27
container[72].i= 435
container[72].j= 284
container[72].angle= 135
container[72].value= 255


container[73].bin= 23
container[73].i= 435
container[73].j= 285
container[73].angle= 116
container[73].value= 255


container[74].bin= 63
container[74].i= 436
container[74].j= 280
container[74].angle= 315
container[74].value= 255


container[75].bin= 27
container[75].i= 436
container[75].j= 286
container[75].angle= 135
container[75].value= 255


container[76].bin= 0
container[76].i= 437
container[76].j= 280
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 437
container[77].j= 286
container[77].angle= 180
container[77].value= 255


container[78].bin= 18
container[78].i= 438
container[78].j= 278
container[78].angle= 90
container[78].value= 255


container[79].bin= 0
container[79].i= 438
container[79].j= 280
container[79].angle= 0
container[79].value= 255


container[80].bin= 30
container[80].i= 438
container[80].j= 287
container[80].angle= 153
container[80].value= 255


container[81].bin= 3
container[81].i= 439
container[81].j= 277
container[81].angle= 18
container[81].value= 255


container[82].bin= 32
container[82].i= 439
container[82].j= 279
container[82].angle= 161
container[82].value= 255


container[83].bin= 30
container[83].i= 439
container[83].j= 287
container[83].angle= 153
container[83].value= 255


container[84].bin= 0
container[84].i= 440
container[84].j= 277
container[84].angle= 0
container[84].value= 255


container[85].bin= 36
container[85].i= 440
container[85].j= 279
container[85].angle= 180
container[85].value= 255


container[86].bin= 36
container[86].i= 440
container[86].j= 287
container[86].angle= 180
container[86].value= 255


container[87].bin= 0
container[87].i= 441
container[87].j= 277
container[87].angle= 0
container[87].value= 255


container[88].bin= 27
container[88].i= 441
container[88].j= 279
container[88].angle= 135
container[88].value= 255


container[89].bin= 8
container[89].i= 441
container[89].j= 280
container[89].angle= 44
container[89].value= 255


container[90].bin= 36
container[90].i= 441
container[90].j= 287
container[90].angle= 180
container[90].value= 255


container[91].bin= 0
container[91].i= 442
container[91].j= 277
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 442
container[92].j= 287
container[92].angle= 180
container[92].value= 255


container[93].bin= 18
container[93].i= 443
container[93].j= 275
container[93].angle= 90
container[93].value= 255


container[94].bin= 0
container[94].i= 443
container[94].j= 277
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 443
container[95].j= 287
container[95].angle= 180
container[95].value= 255


container[96].bin= 3
container[96].i= 444
container[96].j= 274
container[96].angle= 18
container[96].value= 255


container[97].bin= 32
container[97].i= 444
container[97].j= 276
container[97].angle= 161
container[97].value= 255


container[98].bin= 54
container[98].i= 444
container[98].j= 285
container[98].angle= 270
container[98].value= 255


container[99].bin= 54
container[99].i= 444
container[99].j= 286
container[99].angle= 270
container[99].value= 255


container[100].bin= 44
container[100].i= 444
container[100].j= 287
container[100].angle= 224
container[100].value= 255


container[101].bin= 0
container[101].i= 445
container[101].j= 274
container[101].angle= 0
container[101].value= 255


container[102].bin= 36
container[102].i= 445
container[102].j= 276
container[102].angle= 180
container[102].value= 255


container[103].bin= 44
container[103].i= 445
container[103].j= 284
container[103].angle= 224
container[103].value= 255


container[104].bin= 0
container[104].i= 446
container[104].j= 274
container[104].angle= 0
container[104].value= 255


container[105].bin= 36
container[105].i= 446
container[105].j= 276
container[105].angle= 180
container[105].value= 255


container[106].bin= 36
container[106].i= 446
container[106].j= 283
container[106].angle= 180
container[106].value= 255


container[107].bin= 0
container[107].i= 447
container[107].j= 274
container[107].angle= 0
container[107].value= 255


container[108].bin= 27
container[108].i= 447
container[108].j= 276
container[108].angle= 135
container[108].value= 255


container[109].bin= 8
container[109].i= 447
container[109].j= 277
container[109].angle= 44
container[109].value= 255


container[110].bin= 44
container[110].i= 447
container[110].j= 283
container[110].angle= 224
container[110].value= 255


container[111].bin= 0
container[111].i= 448
container[111].j= 274
container[111].angle= 0
container[111].value= 255


container[112].bin= 44
container[112].i= 448
container[112].j= 282
container[112].angle= 224
container[112].value= 255


container[113].bin= 0
container[113].i= 449
container[113].j= 274
container[113].angle= 0
container[113].value= 255


container[114].bin= 36
container[114].i= 449
container[114].j= 281
container[114].angle= 180
container[114].value= 255


container[115].bin= 18
container[115].i= 450
container[115].j= 273
container[115].angle= 90
container[115].value= 255


container[116].bin= 8
container[116].i= 450
container[116].j= 274
container[116].angle= 44
container[116].value= 255


container[117].bin= 36
container[117].i= 450
container[117].j= 281
container[117].angle= 180
container[117].value= 255


container[118].bin= 8
container[118].i= 451
container[118].j= 272
container[118].angle= 44
container[118].value= 255


container[119].bin= 44
container[119].i= 451
container[119].j= 276
container[119].angle= 224
container[119].value= 255


container[120].bin= 63
container[120].i= 451
container[120].j= 277
container[120].angle= 315
container[120].value= 255


container[121].bin= 36
container[121].i= 451
container[121].j= 281
container[121].angle= 180
container[121].value= 255


container[122].bin= 0
container[122].i= 452
container[122].j= 271
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 452
container[123].j= 275
container[123].angle= 180
container[123].value= 255


container[124].bin= 36
container[124].i= 452
container[124].j= 281
container[124].angle= 180
container[124].value= 255


container[125].bin= 14
container[125].i= 453
container[125].j= 268
container[125].angle= 71
container[125].value= 255


container[126].bin= 18
container[126].i= 453
container[126].j= 269
container[126].angle= 90
container[126].value= 255


container[127].bin= 18
container[127].i= 453
container[127].j= 270
container[127].angle= 90
container[127].value= 255


container[128].bin= 54
container[128].i= 453
container[128].j= 273
container[128].angle= 270
container[128].value= 255


container[129].bin= 63
container[129].i= 453
container[129].j= 278
container[129].angle= 315
container[129].value= 255


container[130].bin= 54
container[130].i= 453
container[130].j= 279
container[130].angle= 270
container[130].value= 255


container[131].bin= 54
container[131].i= 453
container[131].j= 280
container[131].angle= 270
container[131].value= 255


container[132].bin= 44
container[132].i= 453
container[132].j= 281
container[132].angle= 224
container[132].value= 255


container[133].bin= 3
container[133].i= 454
container[133].j= 268
container[133].angle= 18
container[133].value= 255


container[134].bin= 59
container[134].i= 454
container[134].j= 274
container[134].angle= 296
container[134].value= 255


container[135].bin= 66
container[135].i= 455
container[135].j= 268
container[135].angle= 333
container[135].value= 255


container[136].bin= 36
container[136].i= 455
container[136].j= 271
container[136].angle= 180
container[136].value= 255


container[137].bin= 63
container[137].i= 456
container[137].j= 269
container[137].angle= 315
container[137].value= 255


container[138].bin= 54
container[138].i= 456
container[138].j= 270
container[138].angle= 270
container[138].value= 255


container[139].bin= 44
container[139].i= 456
container[139].j= 271
container[139].angle= 224
container[139].value= 255


