container[0].bin= 18
container[0].i= 267
container[0].j= 505
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 268
container[1].j= 504
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 268
container[2].j= 506
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 269
container[3].j= 503
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 269
container[4].j= 507
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 270
container[5].j= 503
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 270
container[6].j= 507
container[6].angle= 135
container[6].value= 255


container[7].bin= 23
container[7].i= 270
container[7].j= 508
container[7].angle= 116
container[7].value= 255


container[8].bin= 0
container[8].i= 271
container[8].j= 503
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 271
container[9].j= 509
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 272
container[10].j= 503
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 272
container[11].j= 509
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 273
container[12].j= 503
container[12].angle= 0
container[12].value= 255


container[13].bin= 54
container[13].i= 273
container[13].j= 506
container[13].angle= 270
container[13].value= 255


container[14].bin= 63
container[14].i= 273
container[14].j= 507
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 273
container[15].j= 509
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 274
container[16].j= 503
container[16].angle= 0
container[16].value= 255


container[17].bin= 0
container[17].i= 274
container[17].j= 507
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 274
container[18].j= 509
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 275
container[19].j= 503
container[19].angle= 0
container[19].value= 255


container[20].bin= 18
container[20].i= 275
container[20].j= 506
container[20].angle= 90
container[20].value= 255


container[21].bin= 8
container[21].i= 275
container[21].j= 507
container[21].angle= 44
container[21].value= 255


container[22].bin= 36
container[22].i= 275
container[22].j= 509
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 276
container[23].j= 503
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 276
container[24].j= 509
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 277
container[25].j= 503
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 277
container[26].j= 509
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 278
container[27].j= 503
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 278
container[28].j= 509
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 279
container[29].j= 504
container[29].angle= 315
container[29].value= 255


container[30].bin= 54
container[30].i= 279
container[30].j= 505
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 279
container[31].j= 506
container[31].angle= 270
container[31].value= 255


container[32].bin= 27
container[32].i= 279
container[32].j= 510
container[32].angle= 135
container[32].value= 255


container[33].bin= 63
container[33].i= 280
container[33].j= 507
container[33].angle= 315
container[33].value= 255


container[34].bin= 27
container[34].i= 280
container[34].j= 511
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 281
container[35].j= 507
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 281
container[36].j= 511
container[36].angle= 180
container[36].value= 255


container[37].bin= 63
container[37].i= 282
container[37].j= 508
container[37].angle= 315
container[37].value= 255


container[38].bin= 54
container[38].i= 282
container[38].j= 509
container[38].angle= 270
container[38].value= 255


container[39].bin= 30
container[39].i= 282
container[39].j= 512
container[39].angle= 153
container[39].value= 255


container[40].bin= 63
container[40].i= 283
container[40].j= 510
container[40].angle= 315
container[40].value= 255


container[41].bin= 30
container[41].i= 283
container[41].j= 512
container[41].angle= 153
container[41].value= 255


container[42].bin= 0
container[42].i= 284
container[42].j= 510
container[42].angle= 0
container[42].value= 255


container[43].bin= 63
container[43].i= 285
container[43].j= 511
container[43].angle= 315
container[43].value= 255


container[44].bin= 18
container[44].i= 285
container[44].j= 514
container[44].angle= 90
container[44].value= 255


container[45].bin= 27
container[45].i= 286
container[45].j= 515
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 287
container[46].j= 512
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 287
container[47].j= 515
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 288
container[48].j= 512
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 288
container[49].j= 515
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 289
container[50].j= 512
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 289
container[51].j= 515
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 290
container[52].j= 512
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 290
container[53].j= 515
container[53].angle= 180
container[53].value= 255


container[54].bin= 66
container[54].i= 291
container[54].j= 513
container[54].angle= 333
container[54].value= 255


container[55].bin= 54
container[55].i= 291
container[55].j= 514
container[55].angle= 270
container[55].value= 255


container[56].bin= 41
container[56].i= 291
container[56].j= 515
container[56].angle= 206
container[56].value= 255


container[57].bin= 66
container[57].i= 292
container[57].j= 513
container[57].angle= 333
container[57].value= 255


container[58].bin= 41
container[58].i= 292
container[58].j= 515
container[58].angle= 206
container[58].value= 255


container[59].bin= 0
container[59].i= 293
container[59].j= 513
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 293
container[60].j= 515
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 294
container[61].j= 513
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 294
container[62].j= 515
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 295
container[63].j= 513
container[63].angle= 0
container[63].value= 255


container[64].bin= 30
container[64].i= 295
container[64].j= 515
container[64].angle= 153
container[64].value= 255


container[65].bin= 0
container[65].i= 296
container[65].j= 513
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 296
container[66].j= 515
container[66].angle= 180
container[66].value= 255


container[67].bin= 68
container[67].i= 297
container[67].j= 513
container[67].angle= 341
container[67].value= 255


container[68].bin= 57
container[68].i= 297
container[68].j= 514
container[68].angle= 288
container[68].value= 255


container[69].bin= 44
container[69].i= 297
container[69].j= 515
container[69].angle= 224
container[69].value= 255


