container[0].bin= 18
container[0].i= 165
container[0].j= 154
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 165
container[1].j= 155
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 166
container[2].j= 153
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 166
container[3].j= 156
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 167
container[4].j= 152
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 167
container[5].j= 156
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 168
container[6].j= 153
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 168
container[7].j= 154
container[7].angle= 270
container[7].value= 255


container[8].bin= 63
container[8].i= 169
container[8].j= 155
container[8].angle= 315
container[8].value= 255


container[9].bin= 36
container[9].i= 169
container[9].j= 157
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 170
container[10].j= 155
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 170
container[11].j= 157
container[11].angle= 180
container[11].value= 255


container[12].bin= 8
container[12].i= 171
container[12].j= 155
container[12].angle= 44
container[12].value= 255


container[13].bin= 36
container[13].i= 171
container[13].j= 157
container[13].angle= 180
container[13].value= 255


container[14].bin= 8
container[14].i= 172
container[14].j= 154
container[14].angle= 44
container[14].value= 255


container[15].bin= 0
container[15].i= 173
container[15].j= 153
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 173
container[16].j= 156
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 174
container[17].j= 154
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 174
container[18].j= 156
container[18].angle= 180
container[18].value= 255


container[19].bin= 68
container[19].i= 175
container[19].j= 154
container[19].angle= 341
container[19].value= 255


container[20].bin= 3
container[20].i= 176
container[20].j= 153
container[20].angle= 18
container[20].value= 255


container[21].bin= 8
container[21].i= 176
container[21].j= 154
container[21].angle= 44
container[21].value= 255


container[22].bin= 36
container[22].i= 176
container[22].j= 157
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 177
container[23].j= 153
container[23].angle= 341
container[23].value= 255


container[24].bin= 63
container[24].i= 177
container[24].j= 154
container[24].angle= 315
container[24].value= 255


container[25].bin= 36
container[25].i= 177
container[25].j= 157
container[25].angle= 180
container[25].value= 255


container[26].bin= 59
container[26].i= 178
container[26].j= 155
container[26].angle= 296
container[26].value= 255


container[27].bin= 50
container[27].i= 178
container[27].j= 156
container[27].angle= 251
container[27].value= 255


