container[0].bin= 18
container[0].i= 872
container[0].j= 508
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 873
container[1].j= 507
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 873
container[2].j= 509
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 873
container[3].j= 510
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 874
container[4].j= 506
container[4].angle= 0
container[4].value= 255


container[5].bin= 63
container[5].i= 875
container[5].j= 507
container[5].angle= 315
container[5].value= 255


container[6].bin= 48
container[6].i= 875
container[6].j= 508
container[6].angle= 243
container[6].value= 255


container[7].bin= 48
container[7].i= 875
container[7].j= 509
container[7].angle= 243
container[7].value= 255


