container[0].bin= 18
container[0].i= 146
container[0].j= 234
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 146
container[1].j= 235
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 147
container[2].j= 232
container[2].angle= 44
container[2].value= 255


container[3].bin= 12
container[3].i= 147
container[3].j= 233
container[3].angle= 63
container[3].value= 255


container[4].bin= 27
container[4].i= 147
container[4].j= 236
container[4].angle= 135
container[4].value= 255


container[5].bin= 5
container[5].i= 148
container[5].j= 232
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 148
container[6].j= 236
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 149
container[7].j= 231
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 149
container[8].j= 237
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 150
container[9].j= 231
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 150
container[10].j= 237
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 151
container[11].j= 232
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 151
container[12].j= 238
container[12].angle= 153
container[12].value= 255


container[13].bin= 63
container[13].i= 152
container[13].j= 232
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 152
container[14].j= 233
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 152
container[15].j= 238
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 152
container[16].j= 239
container[16].angle= 135
container[16].value= 255


container[17].bin= 66
container[17].i= 153
container[17].j= 233
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 153
container[18].j= 239
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 154
container[19].j= 234
container[19].angle= 333
container[19].value= 255


container[20].bin= 36
container[20].i= 154
container[20].j= 239
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 155
container[21].j= 234
container[21].angle= 315
container[21].value= 255


container[22].bin= 63
container[22].i= 155
container[22].j= 235
container[22].angle= 315
container[22].value= 255


container[23].bin= 30
container[23].i= 155
container[23].j= 240
container[23].angle= 153
container[23].value= 255


container[24].bin= 63
container[24].i= 156
container[24].j= 235
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 156
container[25].j= 236
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 156
container[26].j= 240
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 157
container[27].j= 236
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 157
container[28].j= 237
container[28].angle= 296
container[28].value= 255


container[29].bin= 36
container[29].i= 157
container[29].j= 240
container[29].angle= 180
container[29].value= 255


container[30].bin= 59
container[30].i= 158
container[30].j= 238
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 158
container[31].j= 239
container[31].angle= 315
container[31].value= 255


container[32].bin= 63
container[32].i= 159
container[32].j= 239
container[32].angle= 315
container[32].value= 255


