container[0].bin= 18
container[0].i= 848
container[0].j= 225
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 849
container[1].j= 224
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 849
container[2].j= 226
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 850
container[3].j= 223
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 850
container[4].j= 226
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 851
container[5].j= 223
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 851
container[6].j= 226
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 852
container[7].j= 223
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 852
container[8].j= 226
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 853
container[9].j= 223
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 853
container[10].j= 226
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 854
container[11].j= 223
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 854
container[12].j= 226
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 855
container[13].j= 223
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 855
container[14].j= 226
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 856
container[15].j= 223
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 856
container[16].j= 226
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 857
container[17].j= 224
container[17].angle= 333
container[17].value= 255


container[18].bin= 27
container[18].i= 857
container[18].j= 227
container[18].angle= 135
container[18].value= 255


container[19].bin= 18
container[19].i= 857
container[19].j= 228
container[19].angle= 90
container[19].value= 255


container[20].bin= 18
container[20].i= 857
container[20].j= 229
container[20].angle= 90
container[20].value= 255


container[21].bin= 18
container[21].i= 857
container[21].j= 230
container[21].angle= 90
container[21].value= 255


container[22].bin= 18
container[22].i= 857
container[22].j= 231
container[22].angle= 90
container[22].value= 255


container[23].bin= 0
container[23].i= 858
container[23].j= 224
container[23].angle= 0
container[23].value= 255


container[24].bin= 23
container[24].i= 858
container[24].j= 232
container[24].angle= 116
container[24].value= 255


container[25].bin= 27
container[25].i= 858
container[25].j= 233
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 859
container[26].j= 224
container[26].angle= 0
container[26].value= 255


container[27].bin= 30
container[27].i= 859
container[27].j= 233
container[27].angle= 153
container[27].value= 255


container[28].bin= 66
container[28].i= 860
container[28].j= 224
container[28].angle= 333
container[28].value= 255


container[29].bin= 36
container[29].i= 860
container[29].j= 233
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 861
container[30].j= 224
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 861
container[31].j= 233
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 862
container[32].j= 224
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 862
container[33].j= 233
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 863
container[34].j= 225
container[34].angle= 315
container[34].value= 255


container[35].bin= 36
container[35].i= 863
container[35].j= 233
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 864
container[36].j= 226
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 864
container[37].j= 233
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 865
container[38].j= 226
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 865
container[39].j= 233
container[39].angle= 180
container[39].value= 255


container[40].bin= 66
container[40].i= 866
container[40].j= 227
container[40].angle= 333
container[40].value= 255


container[41].bin= 44
container[41].i= 866
container[41].j= 233
container[41].angle= 224
container[41].value= 255


container[42].bin= 66
container[42].i= 867
container[42].j= 227
container[42].angle= 333
container[42].value= 255


container[43].bin= 44
container[43].i= 867
container[43].j= 232
container[43].angle= 224
container[43].value= 255


container[44].bin= 0
container[44].i= 868
container[44].j= 227
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 868
container[45].j= 231
container[45].angle= 180
container[45].value= 255


container[46].bin= 63
container[46].i= 869
container[46].j= 228
container[46].angle= 315
container[46].value= 255


container[47].bin= 54
container[47].i= 869
container[47].j= 229
container[47].angle= 270
container[47].value= 255


container[48].bin= 54
container[48].i= 869
container[48].j= 230
container[48].angle= 270
container[48].value= 255


container[49].bin= 44
container[49].i= 869
container[49].j= 231
container[49].angle= 224
container[49].value= 255


