container[0].bin= 18
container[0].i= 556
container[0].j= 201
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 557
container[1].j= 200
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 557
container[2].j= 202
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 558
container[3].j= 200
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 558
container[4].j= 202
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 559
container[5].j= 200
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 559
container[6].j= 202
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 560
container[7].j= 200
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 560
container[8].j= 202
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 561
container[9].j= 200
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 561
container[10].j= 202
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 562
container[11].j= 200
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 562
container[12].j= 202
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 563
container[13].j= 200
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 563
container[14].j= 202
container[14].angle= 180
container[14].value= 255


container[15].bin= 68
container[15].i= 564
container[15].j= 200
container[15].angle= 341
container[15].value= 255


container[16].bin= 54
container[16].i= 564
container[16].j= 201
container[16].angle= 270
container[16].value= 255


container[17].bin= 39
container[17].i= 564
container[17].j= 202
container[17].angle= 198
container[17].value= 255


