container[0].bin= 14
container[0].i= 237
container[0].j= 150
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 237
container[1].j= 151
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 238
container[2].j= 149
container[2].angle= 18
container[2].value= 255


container[3].bin= 68
container[3].i= 239
container[3].j= 149
container[3].angle= 341
container[3].value= 255


container[4].bin= 68
container[4].i= 240
container[4].j= 150
container[4].angle= 341
container[4].value= 255


container[5].bin= 32
container[5].i= 240
container[5].j= 152
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 241
container[6].j= 150
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 241
container[7].j= 152
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 242
container[8].j= 150
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 242
container[9].j= 152
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 243
container[10].j= 150
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 243
container[11].j= 152
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 244
container[12].j= 150
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 244
container[13].j= 152
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 245
container[14].j= 150
container[14].angle= 0
container[14].value= 255


container[15].bin= 18
container[15].i= 246
container[15].j= 144
container[15].angle= 90
container[15].value= 255


container[16].bin= 18
container[16].i= 246
container[16].j= 145
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 246
container[17].j= 146
container[17].angle= 90
container[17].value= 255


container[18].bin= 12
container[18].i= 246
container[18].j= 147
container[18].angle= 63
container[18].value= 255


container[19].bin= 18
container[19].i= 246
container[19].j= 148
container[19].angle= 90
container[19].value= 255


container[20].bin= 23
container[20].i= 246
container[20].j= 149
container[20].angle= 116
container[20].value= 255


container[21].bin= 8
container[21].i= 246
container[21].j= 150
container[21].angle= 44
container[21].value= 255


container[22].bin= 27
container[22].i= 246
container[22].j= 153
container[22].angle= 135
container[22].value= 255


container[23].bin= 8
container[23].i= 247
container[23].j= 143
container[23].angle= 44
container[23].value= 255


container[24].bin= 27
container[24].i= 247
container[24].j= 154
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 248
container[25].j= 142
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 248
container[26].j= 154
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 249
container[27].j= 142
container[27].angle= 0
container[27].value= 255


container[28].bin= 54
container[28].i= 249
container[28].j= 148
container[28].angle= 270
container[28].value= 255


container[29].bin= 54
container[29].i= 249
container[29].j= 149
container[29].angle= 270
container[29].value= 255


container[30].bin= 48
container[30].i= 249
container[30].j= 150
container[30].angle= 243
container[30].value= 255


container[31].bin= 54
container[31].i= 249
container[31].j= 151
container[31].angle= 270
container[31].value= 255


container[32].bin= 59
container[32].i= 249
container[32].j= 152
container[32].angle= 296
container[32].value= 255


container[33].bin= 54
container[33].i= 249
container[33].j= 153
container[33].angle= 270
container[33].value= 255


container[34].bin= 44
container[34].i= 249
container[34].j= 154
container[34].angle= 224
container[34].value= 255


container[35].bin= 0
container[35].i= 250
container[35].j= 142
container[35].angle= 0
container[35].value= 255


container[36].bin= 44
container[36].i= 250
container[36].j= 147
container[36].angle= 224
container[36].value= 255


container[37].bin= 0
container[37].i= 251
container[37].j= 142
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 251
container[38].j= 146
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 252
container[39].j= 142
container[39].angle= 0
container[39].value= 255


container[40].bin= 27
container[40].i= 252
container[40].j= 147
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 253
container[41].j= 142
container[41].angle= 0
container[41].value= 255


container[42].bin= 44
container[42].i= 253
container[42].j= 144
container[42].angle= 224
container[42].value= 255


container[43].bin= 59
container[43].i= 253
container[43].j= 145
container[43].angle= 296
container[43].value= 255


container[44].bin= 23
container[44].i= 253
container[44].j= 148
container[44].angle= 116
container[44].value= 255


container[45].bin= 27
container[45].i= 253
container[45].j= 149
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 254
container[46].j= 142
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 254
container[47].j= 144
container[47].angle= 180
container[47].value= 255


container[48].bin= 68
container[48].i= 254
container[48].j= 146
container[48].angle= 341
container[48].value= 255


container[49].bin= 30
container[49].i= 254
container[49].j= 149
container[49].angle= 153
container[49].value= 255


container[50].bin= 68
container[50].i= 255
container[50].j= 142
container[50].angle= 341
container[50].value= 255


container[51].bin= 54
container[51].i= 255
container[51].j= 143
container[51].angle= 270
container[51].value= 255


container[52].bin= 39
container[52].i= 255
container[52].j= 144
container[52].angle= 198
container[52].value= 255


container[53].bin= 8
container[53].i= 255
container[53].j= 146
container[53].angle= 44
container[53].value= 255


container[54].bin= 27
container[54].i= 255
container[54].j= 150
container[54].angle= 135
container[54].value= 255


container[55].bin= 0
container[55].i= 256
container[55].j= 145
container[55].angle= 0
container[55].value= 255


container[56].bin= 27
container[56].i= 256
container[56].j= 151
container[56].angle= 135
container[56].value= 255


container[57].bin= 0
container[57].i= 257
container[57].j= 145
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 257
container[58].j= 151
container[58].angle= 180
container[58].value= 255


container[59].bin= 0
container[59].i= 258
container[59].j= 145
container[59].angle= 0
container[59].value= 255


container[60].bin= 54
container[60].i= 258
container[60].j= 150
container[60].angle= 270
container[60].value= 255


container[61].bin= 44
container[61].i= 258
container[61].j= 151
container[61].angle= 224
container[61].value= 255


container[62].bin= 0
container[62].i= 259
container[62].j= 145
container[62].angle= 0
container[62].value= 255


container[63].bin= 44
container[63].i= 259
container[63].j= 149
container[63].angle= 224
container[63].value= 255


container[64].bin= 5
container[64].i= 260
container[64].j= 145
container[64].angle= 26
container[64].value= 255


container[65].bin= 36
container[65].i= 260
container[65].j= 148
container[65].angle= 180
container[65].value= 255


container[66].bin= 68
container[66].i= 261
container[66].j= 145
container[66].angle= 341
container[66].value= 255


container[67].bin= 54
container[67].i= 261
container[67].j= 147
container[67].angle= 270
container[67].value= 255


container[68].bin= 44
container[68].i= 261
container[68].j= 148
container[68].angle= 224
container[68].value= 255


