container[0].bin= 18
container[0].i= 276
container[0].j= 236
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 277
container[1].j= 235
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 277
container[2].j= 237
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 278
container[3].j= 235
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 278
container[4].j= 237
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 279
container[5].j= 235
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 279
container[6].j= 237
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 280
container[7].j= 235
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 280
container[8].j= 238
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 281
container[9].j= 235
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 281
container[10].j= 238
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 282
container[11].j= 236
container[11].angle= 315
container[11].value= 255


container[12].bin= 30
container[12].i= 282
container[12].j= 239
container[12].angle= 153
container[12].value= 255


container[13].bin= 63
container[13].i= 283
container[13].j= 237
container[13].angle= 315
container[13].value= 255


container[14].bin= 30
container[14].i= 283
container[14].j= 239
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 284
container[15].j= 237
container[15].angle= 0
container[15].value= 255


container[16].bin= 63
container[16].i= 285
container[16].j= 238
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 285
container[17].j= 239
container[17].angle= 224
container[17].value= 255


