container[0].bin= 8
container[0].i= 822
container[0].j= 277
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 822
container[1].j= 278
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 823
container[2].j= 276
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 824
container[3].j= 277
container[3].angle= 333
container[3].value= 255


container[4].bin= 27
container[4].i= 824
container[4].j= 279
container[4].angle= 135
container[4].value= 255


container[5].bin= 12
container[5].i= 824
container[5].j= 280
container[5].angle= 63
container[5].value= 255


container[6].bin= 18
container[6].i= 824
container[6].j= 281
container[6].angle= 90
container[6].value= 255


container[7].bin= 23
container[7].i= 824
container[7].j= 282
container[7].angle= 116
container[7].value= 255


container[8].bin= 18
container[8].i= 824
container[8].j= 283
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 824
container[9].j= 284
container[9].angle= 90
container[9].value= 255


container[10].bin= 66
container[10].i= 825
container[10].j= 277
container[10].angle= 333
container[10].value= 255


container[11].bin= 23
container[11].i= 825
container[11].j= 285
container[11].angle= 116
container[11].value= 255


container[12].bin= 27
container[12].i= 825
container[12].j= 286
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 826
container[13].j= 277
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 826
container[14].j= 286
container[14].angle= 153
container[14].value= 255


container[15].bin= 63
container[15].i= 827
container[15].j= 278
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 827
container[16].j= 279
container[16].angle= 270
container[16].value= 255


container[17].bin= 57
container[17].i= 827
container[17].j= 280
container[17].angle= 288
container[17].value= 255


container[18].bin= 27
container[18].i= 827
container[18].j= 287
container[18].angle= 135
container[18].value= 255


container[19].bin= 18
container[19].i= 827
container[19].j= 288
container[19].angle= 90
container[19].value= 255


container[20].bin= 27
container[20].i= 828
container[20].j= 289
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 829
container[21].j= 280
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 829
container[22].j= 289
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 830
container[23].j= 280
container[23].angle= 315
container[23].value= 255


container[24].bin= 59
container[24].i= 830
container[24].j= 281
container[24].angle= 296
container[24].value= 255


container[25].bin= 30
container[25].i= 830
container[25].j= 290
container[25].angle= 153
container[25].value= 255


container[26].bin= 63
container[26].i= 831
container[26].j= 282
container[26].angle= 315
container[26].value= 255


container[27].bin= 30
container[27].i= 831
container[27].j= 290
container[27].angle= 153
container[27].value= 255


container[28].bin= 0
container[28].i= 832
container[28].j= 282
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 832
container[29].j= 290
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 833
container[30].j= 283
container[30].angle= 315
container[30].value= 255


container[31].bin= 30
container[31].i= 833
container[31].j= 291
container[31].angle= 153
container[31].value= 255


container[32].bin= 63
container[32].i= 834
container[32].j= 284
container[32].angle= 315
container[32].value= 255


container[33].bin= 30
container[33].i= 834
container[33].j= 291
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 835
container[34].j= 284
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 835
container[35].j= 291
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 836
container[36].j= 285
container[36].angle= 315
container[36].value= 255


container[37].bin= 54
container[37].i= 836
container[37].j= 286
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 836
container[38].j= 287
container[38].angle= 270
container[38].value= 255


container[39].bin= 54
container[39].i= 836
container[39].j= 288
container[39].angle= 270
container[39].value= 255


container[40].bin= 54
container[40].i= 836
container[40].j= 289
container[40].angle= 270
container[40].value= 255


container[41].bin= 63
container[41].i= 837
container[41].j= 290
container[41].angle= 315
container[41].value= 255


container[42].bin= 36
container[42].i= 837
container[42].j= 292
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 838
container[43].j= 290
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 838
container[44].j= 292
container[44].angle= 180
container[44].value= 255


container[45].bin= 68
container[45].i= 839
container[45].j= 290
container[45].angle= 341
container[45].value= 255


container[46].bin= 54
container[46].i= 839
container[46].j= 291
container[46].angle= 270
container[46].value= 255


container[47].bin= 39
container[47].i= 839
container[47].j= 292
container[47].angle= 198
container[47].value= 255


