container[0].bin= 18
container[0].i= 741
container[0].j= 610
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 742
container[1].j= 609
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 742
container[2].j= 611
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 743
container[3].j= 609
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 743
container[4].j= 611
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 744
container[5].j= 609
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 744
container[6].j= 611
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 745
container[7].j= 609
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 745
container[8].j= 611
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 746
container[9].j= 609
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 746
container[10].j= 611
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 747
container[11].j= 609
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 747
container[12].j= 611
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 748
container[13].j= 609
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 748
container[14].j= 611
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 749
container[15].j= 609
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 749
container[16].j= 611
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 750
container[17].j= 609
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 750
container[18].j= 611
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 751
container[19].j= 609
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 751
container[20].j= 611
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 752
container[21].j= 609
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 752
container[22].j= 611
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 753
container[23].j= 609
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 753
container[24].j= 611
container[24].angle= 135
container[24].value= 255


container[25].bin= 27
container[25].i= 753
container[25].j= 612
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 754
container[26].j= 609
container[26].angle= 0
container[26].value= 255


container[27].bin= 30
container[27].i= 754
container[27].j= 612
container[27].angle= 153
container[27].value= 255


container[28].bin= 0
container[28].i= 755
container[28].j= 609
container[28].angle= 0
container[28].value= 255


container[29].bin= 41
container[29].i= 755
container[29].j= 612
container[29].angle= 206
container[29].value= 255


container[30].bin= 0
container[30].i= 756
container[30].j= 609
container[30].angle= 0
container[30].value= 255


container[31].bin= 0
container[31].i= 757
container[31].j= 609
container[31].angle= 0
container[31].value= 255


container[32].bin= 0
container[32].i= 758
container[32].j= 609
container[32].angle= 0
container[32].value= 255


container[33].bin= 39
container[33].i= 758
container[33].j= 611
container[33].angle= 198
container[33].value= 255


container[34].bin= 44
container[34].i= 758
container[34].j= 612
container[34].angle= 224
container[34].value= 255


container[35].bin= 0
container[35].i= 759
container[35].j= 609
container[35].angle= 0
container[35].value= 255


container[36].bin= 41
container[36].i= 759
container[36].j= 611
container[36].angle= 206
container[36].value= 255


container[37].bin= 0
container[37].i= 760
container[37].j= 609
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 760
container[38].j= 611
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 761
container[39].j= 609
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 761
container[40].j= 611
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 762
container[41].j= 609
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 762
container[42].j= 611
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 763
container[43].j= 609
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 763
container[44].j= 611
container[44].angle= 180
container[44].value= 255


container[45].bin= 5
container[45].i= 764
container[45].j= 609
container[45].angle= 26
container[45].value= 255


container[46].bin= 18
container[46].i= 764
container[46].j= 610
container[46].angle= 90
container[46].value= 255


container[47].bin= 27
container[47].i= 764
container[47].j= 611
container[47].angle= 135
container[47].value= 255


container[48].bin= 5
container[48].i= 765
container[48].j= 609
container[48].angle= 26
container[48].value= 255


container[49].bin= 27
container[49].i= 765
container[49].j= 612
container[49].angle= 135
container[49].value= 255


container[50].bin= 0
container[50].i= 766
container[50].j= 608
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 766
container[51].j= 612
container[51].angle= 180
container[51].value= 255


container[52].bin= 66
container[52].i= 767
container[52].j= 609
container[52].angle= 333
container[52].value= 255


container[53].bin= 54
container[53].i= 767
container[53].j= 610
container[53].angle= 270
container[53].value= 255


container[54].bin= 44
container[54].i= 767
container[54].j= 612
container[54].angle= 224
container[54].value= 255


container[55].bin= 66
container[55].i= 768
container[55].j= 609
container[55].angle= 333
container[55].value= 255


container[56].bin= 44
container[56].i= 768
container[56].j= 611
container[56].angle= 224
container[56].value= 255


container[57].bin= 0
container[57].i= 769
container[57].j= 609
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 769
container[58].j= 611
container[58].angle= 180
container[58].value= 255


container[59].bin= 0
container[59].i= 770
container[59].j= 609
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 770
container[60].j= 611
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 771
container[61].j= 609
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 771
container[62].j= 611
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 772
container[63].j= 609
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 772
container[64].j= 611
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 773
container[65].j= 609
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 773
container[66].j= 611
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 774
container[67].j= 609
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 774
container[68].j= 611
container[68].angle= 180
container[68].value= 255


container[69].bin= 0
container[69].i= 775
container[69].j= 609
container[69].angle= 0
container[69].value= 255


container[70].bin= 36
container[70].i= 775
container[70].j= 611
container[70].angle= 180
container[70].value= 255


container[71].bin= 68
container[71].i= 776
container[71].j= 609
container[71].angle= 341
container[71].value= 255


container[72].bin= 54
container[72].i= 776
container[72].j= 610
container[72].angle= 270
container[72].value= 255


container[73].bin= 39
container[73].i= 776
container[73].j= 611
container[73].angle= 198
container[73].value= 255


