container[0].bin= 18
container[0].i= 128
container[0].j= 16
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 129
container[1].j= 14
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 129
container[2].j= 15
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 129
container[3].j= 17
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 130
container[4].j= 13
container[4].angle= 44
container[4].value= 255


container[5].bin= 8
container[5].i= 130
container[5].j= 14
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 130
container[6].j= 17
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 131
container[7].j= 13
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 131
container[8].j= 17
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 132
container[9].j= 12
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 132
container[10].j= 17
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 133
container[11].j= 13
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 133
container[12].j= 17
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 134
container[13].j= 13
container[13].angle= 333
container[13].value= 255


container[14].bin= 41
container[14].i= 134
container[14].j= 17
container[14].angle= 206
container[14].value= 255


container[15].bin= 0
container[15].i= 135
container[15].j= 13
container[15].angle= 0
container[15].value= 255


container[16].bin= 41
container[16].i= 135
container[16].j= 17
container[16].angle= 206
container[16].value= 255


container[17].bin= 66
container[17].i= 136
container[17].j= 14
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 136
container[18].j= 17
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 137
container[19].j= 14
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 137
container[20].j= 17
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 138
container[21].j= 14
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 138
container[22].j= 17
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 139
container[23].j= 14
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 139
container[24].j= 18
container[24].angle= 153
container[24].value= 255


container[25].bin= 8
container[25].i= 139
container[25].j= 26
container[25].angle= 44
container[25].value= 255


container[26].bin= 23
container[26].i= 139
container[26].j= 27
container[26].angle= 116
container[26].value= 255


container[27].bin= 27
container[27].i= 139
container[27].j= 28
container[27].angle= 135
container[27].value= 255


container[28].bin= 66
container[28].i= 140
container[28].j= 15
container[28].angle= 333
container[28].value= 255


container[29].bin= 30
container[29].i= 140
container[29].j= 18
container[29].angle= 153
container[29].value= 255


container[30].bin= 5
container[30].i= 140
container[30].j= 25
container[30].angle= 26
container[30].value= 255


container[31].bin= 30
container[31].i= 140
container[31].j= 28
container[31].angle= 153
container[31].value= 255


container[32].bin= 66
container[32].i= 141
container[32].j= 15
container[32].angle= 333
container[32].value= 255


container[33].bin= 36
container[33].i= 141
container[33].j= 18
container[33].angle= 180
container[33].value= 255


container[34].bin= 5
container[34].i= 141
container[34].j= 25
container[34].angle= 26
container[34].value= 255


container[35].bin= 30
container[35].i= 141
container[35].j= 29
container[35].angle= 153
container[35].value= 255


container[36].bin= 66
container[36].i= 142
container[36].j= 16
container[36].angle= 333
container[36].value= 255


container[37].bin= 30
container[37].i= 142
container[37].j= 19
container[37].angle= 153
container[37].value= 255


container[38].bin= 0
container[38].i= 142
container[38].j= 24
container[38].angle= 0
container[38].value= 255


container[39].bin= 27
container[39].i= 142
container[39].j= 29
container[39].angle= 135
container[39].value= 255


container[40].bin= 27
container[40].i= 142
container[40].j= 30
container[40].angle= 135
container[40].value= 255


container[41].bin= 63
container[41].i= 143
container[41].j= 16
container[41].angle= 315
container[41].value= 255


container[42].bin= 63
container[42].i= 143
container[42].j= 17
container[42].angle= 315
container[42].value= 255


container[43].bin= 27
container[43].i= 143
container[43].j= 19
container[43].angle= 135
container[43].value= 255


container[44].bin= 27
container[44].i= 143
container[44].j= 20
container[44].angle= 135
container[44].value= 255


container[45].bin= 5
container[45].i= 143
container[45].j= 24
container[45].angle= 26
container[45].value= 255


container[46].bin= 27
container[46].i= 143
container[46].j= 30
container[46].angle= 135
container[46].value= 255


container[47].bin= 27
container[47].i= 143
container[47].j= 31
container[47].angle= 135
container[47].value= 255


container[48].bin= 66
container[48].i= 144
container[48].j= 17
container[48].angle= 333
container[48].value= 255


container[49].bin= 30
container[49].i= 144
container[49].j= 20
container[49].angle= 153
container[49].value= 255


container[50].bin= 5
container[50].i= 144
container[50].j= 24
container[50].angle= 26
container[50].value= 255


container[51].bin= 30
container[51].i= 144
container[51].j= 31
container[51].angle= 153
container[51].value= 255


container[52].bin= 63
container[52].i= 145
container[52].j= 18
container[52].angle= 315
container[52].value= 255


container[53].bin= 0
container[53].i= 145
container[53].j= 23
container[53].angle= 0
container[53].value= 255


container[54].bin= 30
container[54].i= 145
container[54].j= 32
container[54].angle= 153
container[54].value= 255


container[55].bin= 59
container[55].i= 146
container[55].j= 19
container[55].angle= 296
container[55].value= 255


container[56].bin= 18
container[56].i= 146
container[56].j= 22
container[56].angle= 90
container[56].value= 255


container[57].bin= 8
container[57].i= 146
container[57].j= 23
container[57].angle= 44
container[57].value= 255


container[58].bin= 30
container[58].i= 146
container[58].j= 32
container[58].angle= 153
container[58].value= 255


container[59].bin= 68
container[59].i= 147
container[59].j= 20
container[59].angle= 341
container[59].value= 255


container[60].bin= 8
container[60].i= 147
container[60].j= 21
container[60].angle= 44
container[60].value= 255


container[61].bin= 30
container[61].i= 147
container[61].j= 33
container[61].angle= 153
container[61].value= 255


container[62].bin= 66
container[62].i= 148
container[62].j= 21
container[62].angle= 333
container[62].value= 255


container[63].bin= 30
container[63].i= 148
container[63].j= 33
container[63].angle= 153
container[63].value= 255


container[64].bin= 63
container[64].i= 149
container[64].j= 21
container[64].angle= 315
container[64].value= 255


container[65].bin= 63
container[65].i= 149
container[65].j= 22
container[65].angle= 315
container[65].value= 255


container[66].bin= 30
container[66].i= 149
container[66].j= 34
container[66].angle= 153
container[66].value= 255


container[67].bin= 66
container[67].i= 150
container[67].j= 22
container[67].angle= 333
container[67].value= 255


container[68].bin= 27
container[68].i= 150
container[68].j= 34
container[68].angle= 135
container[68].value= 255


container[69].bin= 27
container[69].i= 150
container[69].j= 35
container[69].angle= 135
container[69].value= 255


container[70].bin= 63
container[70].i= 151
container[70].j= 23
container[70].angle= 315
container[70].value= 255


container[71].bin= 30
container[71].i= 151
container[71].j= 35
container[71].angle= 153
container[71].value= 255


container[72].bin= 59
container[72].i= 152
container[72].j= 24
container[72].angle= 296
container[72].value= 255


container[73].bin= 63
container[73].i= 152
container[73].j= 25
container[73].angle= 315
container[73].value= 255


container[74].bin= 30
container[74].i= 152
container[74].j= 36
container[74].angle= 153
container[74].value= 255


container[75].bin= 63
container[75].i= 153
container[75].j= 25
container[75].angle= 315
container[75].value= 255


container[76].bin= 63
container[76].i= 153
container[76].j= 26
container[76].angle= 315
container[76].value= 255


container[77].bin= 30
container[77].i= 153
container[77].j= 36
container[77].angle= 153
container[77].value= 255


container[78].bin= 63
container[78].i= 154
container[78].j= 26
container[78].angle= 315
container[78].value= 255


container[79].bin= 63
container[79].i= 154
container[79].j= 27
container[79].angle= 315
container[79].value= 255


container[80].bin= 30
container[80].i= 154
container[80].j= 37
container[80].angle= 153
container[80].value= 255


container[81].bin= 66
container[81].i= 155
container[81].j= 27
container[81].angle= 333
container[81].value= 255


container[82].bin= 30
container[82].i= 155
container[82].j= 37
container[82].angle= 153
container[82].value= 255


container[83].bin= 66
container[83].i= 156
container[83].j= 28
container[83].angle= 333
container[83].value= 255


container[84].bin= 36
container[84].i= 156
container[84].j= 37
container[84].angle= 180
container[84].value= 255


container[85].bin= 63
container[85].i= 157
container[85].j= 28
container[85].angle= 315
container[85].value= 255


container[86].bin= 63
container[86].i= 157
container[86].j= 29
container[86].angle= 315
container[86].value= 255


container[87].bin= 36
container[87].i= 157
container[87].j= 37
container[87].angle= 180
container[87].value= 255


container[88].bin= 63
container[88].i= 158
container[88].j= 29
container[88].angle= 315
container[88].value= 255


container[89].bin= 63
container[89].i= 158
container[89].j= 30
container[89].angle= 315
container[89].value= 255


container[90].bin= 36
container[90].i= 158
container[90].j= 37
container[90].angle= 180
container[90].value= 255


container[91].bin= 63
container[91].i= 159
container[91].j= 30
container[91].angle= 315
container[91].value= 255


container[92].bin= 63
container[92].i= 159
container[92].j= 31
container[92].angle= 315
container[92].value= 255


container[93].bin= 36
container[93].i= 159
container[93].j= 37
container[93].angle= 180
container[93].value= 255


container[94].bin= 63
container[94].i= 160
container[94].j= 31
container[94].angle= 315
container[94].value= 255


container[95].bin= 59
container[95].i= 160
container[95].j= 32
container[95].angle= 296
container[95].value= 255


container[96].bin= 54
container[96].i= 160
container[96].j= 33
container[96].angle= 270
container[96].value= 255


container[97].bin= 30
container[97].i= 160
container[97].j= 38
container[97].angle= 153
container[97].value= 255


container[98].bin= 59
container[98].i= 161
container[98].j= 34
container[98].angle= 296
container[98].value= 255


container[99].bin= 63
container[99].i= 161
container[99].j= 35
container[99].angle= 315
container[99].value= 255


container[100].bin= 30
container[100].i= 161
container[100].j= 38
container[100].angle= 153
container[100].value= 255


container[101].bin= 66
container[101].i= 162
container[101].j= 35
container[101].angle= 333
container[101].value= 255


container[102].bin= 36
container[102].i= 162
container[102].j= 38
container[102].angle= 180
container[102].value= 255


container[103].bin= 66
container[103].i= 163
container[103].j= 36
container[103].angle= 333
container[103].value= 255


container[104].bin= 36
container[104].i= 163
container[104].j= 38
container[104].angle= 180
container[104].value= 255


container[105].bin= 66
container[105].i= 164
container[105].j= 36
container[105].angle= 333
container[105].value= 255


container[106].bin= 66
container[106].i= 165
container[106].j= 37
container[106].angle= 333
container[106].value= 255


container[107].bin= 30
container[107].i= 165
container[107].j= 39
container[107].angle= 153
container[107].value= 255


container[108].bin= 66
container[108].i= 166
container[108].j= 37
container[108].angle= 333
container[108].value= 255


container[109].bin= 27
container[109].i= 166
container[109].j= 39
container[109].angle= 135
container[109].value= 255


container[110].bin= 27
container[110].i= 166
container[110].j= 40
container[110].angle= 135
container[110].value= 255


container[111].bin= 0
container[111].i= 167
container[111].j= 37
container[111].angle= 0
container[111].value= 255


container[112].bin= 27
container[112].i= 167
container[112].j= 40
container[112].angle= 135
container[112].value= 255


container[113].bin= 27
container[113].i= 167
container[113].j= 41
container[113].angle= 135
container[113].value= 255


container[114].bin= 0
container[114].i= 168
container[114].j= 37
container[114].angle= 0
container[114].value= 255


container[115].bin= 30
container[115].i= 168
container[115].j= 41
container[115].angle= 153
container[115].value= 255


container[116].bin= 0
container[116].i= 169
container[116].j= 37
container[116].angle= 0
container[116].value= 255


container[117].bin= 30
container[117].i= 169
container[117].j= 42
container[117].angle= 153
container[117].value= 255


container[118].bin= 0
container[118].i= 170
container[118].j= 37
container[118].angle= 0
container[118].value= 255


container[119].bin= 30
container[119].i= 170
container[119].j= 42
container[119].angle= 153
container[119].value= 255


container[120].bin= 66
container[120].i= 171
container[120].j= 38
container[120].angle= 333
container[120].value= 255


container[121].bin= 36
container[121].i= 171
container[121].j= 42
container[121].angle= 180
container[121].value= 255


container[122].bin= 66
container[122].i= 172
container[122].j= 38
container[122].angle= 333
container[122].value= 255


container[123].bin= 30
container[123].i= 172
container[123].j= 43
container[123].angle= 153
container[123].value= 255


container[124].bin= 0
container[124].i= 173
container[124].j= 38
container[124].angle= 0
container[124].value= 255


container[125].bin= 30
container[125].i= 173
container[125].j= 43
container[125].angle= 153
container[125].value= 255


container[126].bin= 66
container[126].i= 174
container[126].j= 39
container[126].angle= 333
container[126].value= 255


container[127].bin= 36
container[127].i= 174
container[127].j= 43
container[127].angle= 180
container[127].value= 255


container[128].bin= 63
container[128].i= 175
container[128].j= 39
container[128].angle= 315
container[128].value= 255


container[129].bin= 63
container[129].i= 175
container[129].j= 40
container[129].angle= 315
container[129].value= 255


container[130].bin= 41
container[130].i= 175
container[130].j= 43
container[130].angle= 206
container[130].value= 255


container[131].bin= 63
container[131].i= 176
container[131].j= 40
container[131].angle= 315
container[131].value= 255


container[132].bin= 59
container[132].i= 176
container[132].j= 41
container[132].angle= 296
container[132].value= 255


container[133].bin= 48
container[133].i= 176
container[133].j= 42
container[133].angle= 243
container[133].value= 255


container[134].bin= 44
container[134].i= 176
container[134].j= 43
container[134].angle= 224
container[134].value= 255


