container[0].bin= 18
container[0].i= 782
container[0].j= 610
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 783
container[1].j= 609
container[1].angle= 18
container[1].value= 255


container[2].bin= 27
container[2].i= 783
container[2].j= 611
container[2].angle= 135
container[2].value= 255


container[3].bin= 18
container[3].i= 783
container[3].j= 612
container[3].angle= 90
container[3].value= 255


container[4].bin= 0
container[4].i= 784
container[4].j= 609
container[4].angle= 0
container[4].value= 255


container[5].bin= 68
container[5].i= 785
container[5].j= 609
container[5].angle= 341
container[5].value= 255


container[6].bin= 44
container[6].i= 785
container[6].j= 611
container[6].angle= 224
container[6].value= 255


