container[0].bin= 8
container[0].i= 376
container[0].j= 593
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 376
container[1].j= 594
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 377
container[2].j= 592
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 378
container[3].j= 592
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 379
container[4].j= 592
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 380
container[5].j= 592
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 381
container[6].j= 592
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 382
container[7].j= 592
container[7].angle= 0
container[7].value= 255


container[8].bin= 0
container[8].i= 383
container[8].j= 592
container[8].angle= 0
container[8].value= 255


container[9].bin= 66
container[9].i= 384
container[9].j= 593
container[9].angle= 333
container[9].value= 255


container[10].bin= 66
container[10].i= 385
container[10].j= 593
container[10].angle= 333
container[10].value= 255


container[11].bin= 36
container[11].i= 385
container[11].j= 595
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 386
container[12].j= 593
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 386
container[13].j= 595
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 387
container[14].j= 593
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 387
container[15].j= 595
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 388
container[16].j= 593
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 388
container[17].j= 595
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 389
container[18].j= 593
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 389
container[19].j= 595
container[19].angle= 180
container[19].value= 255


container[20].bin= 68
container[20].i= 390
container[20].j= 593
container[20].angle= 341
container[20].value= 255


container[21].bin= 54
container[21].i= 390
container[21].j= 594
container[21].angle= 270
container[21].value= 255


container[22].bin= 39
container[22].i= 390
container[22].j= 595
container[22].angle= 198
container[22].value= 255


