container[0].bin= 3
container[0].i= 809
container[0].j= 214
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 809
container[1].j= 215
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 809
container[2].j= 216
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 809
container[3].j= 217
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 809
container[4].j= 218
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 809
container[5].j= 219
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 810
container[6].j= 214
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 810
container[7].j= 220
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 811
container[8].j= 214
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 811
container[9].j= 220
container[9].angle= 180
container[9].value= 255


container[10].bin= 63
container[10].i= 812
container[10].j= 215
container[10].angle= 315
container[10].value= 255


container[11].bin= 54
container[11].i= 812
container[11].j= 216
container[11].angle= 270
container[11].value= 255


container[12].bin= 54
container[12].i= 812
container[12].j= 217
container[12].angle= 270
container[12].value= 255


container[13].bin= 27
container[13].i= 812
container[13].j= 221
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 812
container[14].j= 222
container[14].angle= 90
container[14].value= 255


container[15].bin= 63
container[15].i= 813
container[15].j= 218
container[15].angle= 315
container[15].value= 255


container[16].bin= 27
container[16].i= 813
container[16].j= 223
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 814
container[17].j= 218
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 814
container[18].j= 223
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 815
container[19].j= 218
container[19].angle= 0
container[19].value= 255


container[20].bin= 27
container[20].i= 815
container[20].j= 224
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 815
container[21].j= 225
container[21].angle= 90
container[21].value= 255


container[22].bin= 18
container[22].i= 815
container[22].j= 226
container[22].angle= 90
container[22].value= 255


container[23].bin= 18
container[23].i= 815
container[23].j= 227
container[23].angle= 90
container[23].value= 255


container[24].bin= 0
container[24].i= 816
container[24].j= 218
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 816
container[25].j= 228
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 817
container[26].j= 218
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 817
container[27].j= 228
container[27].angle= 180
container[27].value= 255


container[28].bin= 66
container[28].i= 818
container[28].j= 219
container[28].angle= 333
container[28].value= 255


container[29].bin= 27
container[29].i= 818
container[29].j= 229
container[29].angle= 135
container[29].value= 255


container[30].bin= 18
container[30].i= 818
container[30].j= 230
container[30].angle= 90
container[30].value= 255


container[31].bin= 18
container[31].i= 818
container[31].j= 231
container[31].angle= 90
container[31].value= 255


container[32].bin= 18
container[32].i= 818
container[32].j= 232
container[32].angle= 90
container[32].value= 255


container[33].bin= 66
container[33].i= 819
container[33].j= 219
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 819
container[34].j= 233
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 820
container[35].j= 219
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 820
container[36].j= 233
container[36].angle= 180
container[36].value= 255


container[37].bin= 63
container[37].i= 821
container[37].j= 220
container[37].angle= 315
container[37].value= 255


container[38].bin= 54
container[38].i= 821
container[38].j= 221
container[38].angle= 270
container[38].value= 255


container[39].bin= 54
container[39].i= 821
container[39].j= 222
container[39].angle= 270
container[39].value= 255


container[40].bin= 36
container[40].i= 821
container[40].j= 233
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 822
container[41].j= 223
container[41].angle= 315
container[41].value= 255


container[42].bin= 36
container[42].i= 822
container[42].j= 233
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 823
container[43].j= 223
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 823
container[44].j= 233
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 824
container[45].j= 223
container[45].angle= 0
container[45].value= 255


container[46].bin= 30
container[46].i= 824
container[46].j= 234
container[46].angle= 153
container[46].value= 255


container[47].bin= 0
container[47].i= 825
container[47].j= 223
container[47].angle= 0
container[47].value= 255


container[48].bin= 30
container[48].i= 825
container[48].j= 234
container[48].angle= 153
container[48].value= 255


container[49].bin= 0
container[49].i= 826
container[49].j= 223
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 826
container[50].j= 234
container[50].angle= 180
container[50].value= 255


container[51].bin= 66
container[51].i= 827
container[51].j= 224
container[51].angle= 333
container[51].value= 255


container[52].bin= 36
container[52].i= 827
container[52].j= 234
container[52].angle= 180
container[52].value= 255


container[53].bin= 0
container[53].i= 828
container[53].j= 224
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 828
container[54].j= 234
container[54].angle= 180
container[54].value= 255


container[55].bin= 5
container[55].i= 829
container[55].j= 224
container[55].angle= 26
container[55].value= 255


container[56].bin= 36
container[56].i= 829
container[56].j= 234
container[56].angle= 180
container[56].value= 255


container[57].bin= 66
container[57].i= 830
container[57].j= 224
container[57].angle= 333
container[57].value= 255


container[58].bin= 27
container[58].i= 830
container[58].j= 235
container[58].angle= 135
container[58].value= 255


container[59].bin= 66
container[59].i= 831
container[59].j= 224
container[59].angle= 333
container[59].value= 255


container[60].bin= 27
container[60].i= 831
container[60].j= 236
container[60].angle= 135
container[60].value= 255


container[61].bin= 0
container[61].i= 832
container[61].j= 224
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 832
container[62].j= 236
container[62].angle= 180
container[62].value= 255


container[63].bin= 63
container[63].i= 833
container[63].j= 225
container[63].angle= 315
container[63].value= 255


container[64].bin= 36
container[64].i= 833
container[64].j= 236
container[64].angle= 180
container[64].value= 255


container[65].bin= 63
container[65].i= 834
container[65].j= 226
container[65].angle= 315
container[65].value= 255


container[66].bin= 36
container[66].i= 834
container[66].j= 236
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 835
container[67].j= 226
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 835
container[68].j= 236
container[68].angle= 180
container[68].value= 255


container[69].bin= 66
container[69].i= 836
container[69].j= 227
container[69].angle= 333
container[69].value= 255


container[70].bin= 36
container[70].i= 836
container[70].j= 236
container[70].angle= 180
container[70].value= 255


container[71].bin= 66
container[71].i= 837
container[71].j= 227
container[71].angle= 333
container[71].value= 255


container[72].bin= 36
container[72].i= 837
container[72].j= 236
container[72].angle= 180
container[72].value= 255


container[73].bin= 0
container[73].i= 838
container[73].j= 227
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 838
container[74].j= 236
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 839
container[75].j= 227
container[75].angle= 0
container[75].value= 255


container[76].bin= 39
container[76].i= 839
container[76].j= 233
container[76].angle= 198
container[76].value= 255


container[77].bin= 50
container[77].i= 839
container[77].j= 234
container[77].angle= 251
container[77].value= 255


container[78].bin= 59
container[78].i= 839
container[78].j= 235
container[78].angle= 296
container[78].value= 255


container[79].bin= 44
container[79].i= 839
container[79].j= 236
container[79].angle= 224
container[79].value= 255


container[80].bin= 0
container[80].i= 840
container[80].j= 227
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 840
container[81].j= 233
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 841
container[82].j= 227
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 841
container[83].j= 233
container[83].angle= 180
container[83].value= 255


container[84].bin= 63
container[84].i= 842
container[84].j= 228
container[84].angle= 315
container[84].value= 255


container[85].bin= 44
container[85].i= 842
container[85].j= 233
container[85].angle= 224
container[85].value= 255


container[86].bin= 63
container[86].i= 843
container[86].j= 229
container[86].angle= 315
container[86].value= 255


container[87].bin= 44
container[87].i= 843
container[87].j= 232
container[87].angle= 224
container[87].value= 255


container[88].bin= 0
container[88].i= 844
container[88].j= 229
container[88].angle= 0
container[88].value= 255


container[89].bin= 63
container[89].i= 845
container[89].j= 230
container[89].angle= 315
container[89].value= 255


container[90].bin= 44
container[90].i= 845
container[90].j= 231
container[90].angle= 224
container[90].value= 255


