container[0].bin= 18
container[0].i= 132
container[0].j= 584
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 132
container[1].j= 585
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 132
container[2].j= 586
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 132
container[3].j= 587
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 133
container[4].j= 583
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 133
container[5].j= 588
container[5].angle= 135
container[5].value= 255


container[6].bin= 18
container[6].i= 133
container[6].j= 591
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 134
container[7].j= 582
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 134
container[8].j= 588
container[8].angle= 180
container[8].value= 255


container[9].bin= 32
container[9].i= 134
container[9].j= 592
container[9].angle= 161
container[9].value= 255


container[10].bin= 0
container[10].i= 135
container[10].j= 582
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 135
container[11].j= 589
container[11].angle= 135
container[11].value= 255


container[12].bin= 8
container[12].i= 135
container[12].j= 590
container[12].angle= 44
container[12].value= 255


container[13].bin= 30
container[13].i= 135
container[13].j= 592
container[13].angle= 153
container[13].value= 255


container[14].bin= 18
container[14].i= 135
container[14].j= 605
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 135
container[15].j= 606
container[15].angle= 90
container[15].value= 255


container[16].bin= 0
container[16].i= 136
container[16].j= 582
container[16].angle= 0
container[16].value= 255


container[17].bin= 30
container[17].i= 136
container[17].j= 592
container[17].angle= 153
container[17].value= 255


container[18].bin= 8
container[18].i= 136
container[18].j= 604
container[18].angle= 44
container[18].value= 255


container[19].bin= 27
container[19].i= 136
container[19].j= 607
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 137
container[20].j= 582
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 137
container[21].j= 592
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 137
container[22].j= 603
container[22].angle= 0
container[22].value= 255


container[23].bin= 39
container[23].i= 137
container[23].j= 607
container[23].angle= 198
container[23].value= 255


container[24].bin= 63
container[24].i= 138
container[24].j= 583
container[24].angle= 315
container[24].value= 255


container[25].bin= 57
container[25].i= 138
container[25].j= 584
container[25].angle= 288
container[25].value= 255


container[26].bin= 54
container[26].i= 138
container[26].j= 585
container[26].angle= 270
container[26].value= 255


container[27].bin= 54
container[27].i= 138
container[27].j= 586
container[27].angle= 270
container[27].value= 255


container[28].bin= 27
container[28].i= 138
container[28].j= 593
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 138
container[29].j= 603
container[29].angle= 0
container[29].value= 255


container[30].bin= 44
container[30].i= 138
container[30].j= 607
container[30].angle= 224
container[30].value= 255


container[31].bin= 0
container[31].i= 139
container[31].j= 582
container[31].angle= 0
container[31].value= 255


container[32].bin= 68
container[32].i= 139
container[32].j= 587
container[32].angle= 341
container[32].value= 255


container[33].bin= 27
container[33].i= 139
container[33].j= 594
container[33].angle= 135
container[33].value= 255


container[34].bin= 0
container[34].i= 139
container[34].j= 603
container[34].angle= 0
container[34].value= 255


container[35].bin= 0
container[35].i= 140
container[35].j= 582
container[35].angle= 0
container[35].value= 255


container[36].bin= 68
container[36].i= 140
container[36].j= 587
container[36].angle= 341
container[36].value= 255


container[37].bin= 36
container[37].i= 140
container[37].j= 594
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 140
container[38].j= 603
container[38].angle= 0
container[38].value= 255


container[39].bin= 57
container[39].i= 141
container[39].j= 583
container[39].angle= 288
container[39].value= 255


container[40].bin= 54
container[40].i= 141
container[40].j= 584
container[40].angle= 270
container[40].value= 255


container[41].bin= 57
container[41].i= 141
container[41].j= 585
container[41].angle= 288
container[41].value= 255


container[42].bin= 54
container[42].i= 141
container[42].j= 586
container[42].angle= 270
container[42].value= 255


container[43].bin= 59
container[43].i= 141
container[43].j= 588
container[43].angle= 296
container[43].value= 255


container[44].bin= 54
container[44].i= 141
container[44].j= 589
container[44].angle= 270
container[44].value= 255


container[45].bin= 54
container[45].i= 141
container[45].j= 590
container[45].angle= 270
container[45].value= 255


container[46].bin= 54
container[46].i= 141
container[46].j= 591
container[46].angle= 270
container[46].value= 255


container[47].bin= 27
container[47].i= 141
container[47].j= 595
container[47].angle= 135
container[47].value= 255


container[48].bin= 18
container[48].i= 141
container[48].j= 596
container[48].angle= 90
container[48].value= 255


container[49].bin= 8
container[49].i= 141
container[49].j= 603
container[49].angle= 44
container[49].value= 255


container[50].bin= 44
container[50].i= 141
container[50].j= 606
container[50].angle= 224
container[50].value= 255


container[51].bin= 63
container[51].i= 142
container[51].j= 592
container[51].angle= 315
container[51].value= 255


container[52].bin= 27
container[52].i= 142
container[52].j= 597
container[52].angle= 135
container[52].value= 255


container[53].bin= 8
container[53].i= 142
container[53].j= 601
container[53].angle= 44
container[53].value= 255


container[54].bin= 12
container[54].i= 142
container[54].j= 602
container[54].angle= 63
container[54].value= 255


container[55].bin= 36
container[55].i= 142
container[55].j= 605
container[55].angle= 180
container[55].value= 255


container[56].bin= 0
container[56].i= 143
container[56].j= 592
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 143
container[57].j= 597
container[57].angle= 180
container[57].value= 255


container[58].bin= 5
container[58].i= 143
container[58].j= 601
container[58].angle= 26
container[58].value= 255


container[59].bin= 36
container[59].i= 143
container[59].j= 605
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 144
container[60].j= 592
container[60].angle= 0
container[60].value= 255


container[61].bin= 27
container[61].i= 144
container[61].j= 598
container[61].angle= 135
container[61].value= 255


container[62].bin= 18
container[62].i= 144
container[62].j= 599
container[62].angle= 90
container[62].value= 255


container[63].bin= 8
container[63].i= 144
container[63].j= 600
container[63].angle= 44
container[63].value= 255


container[64].bin= 41
container[64].i= 144
container[64].j= 605
container[64].angle= 206
container[64].value= 255


container[65].bin= 0
container[65].i= 145
container[65].j= 592
container[65].angle= 0
container[65].value= 255


container[66].bin= 41
container[66].i= 145
container[66].j= 605
container[66].angle= 206
container[66].value= 255


container[67].bin= 0
container[67].i= 146
container[67].j= 592
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 146
container[68].j= 604
container[68].angle= 180
container[68].value= 255


container[69].bin= 63
container[69].i= 147
container[69].j= 593
container[69].angle= 315
container[69].value= 255


container[70].bin= 54
container[70].i= 147
container[70].j= 594
container[70].angle= 270
container[70].value= 255


container[71].bin= 54
container[71].i= 147
container[71].j= 599
container[71].angle= 270
container[71].value= 255


container[72].bin= 54
container[72].i= 147
container[72].j= 600
container[72].angle= 270
container[72].value= 255


container[73].bin= 36
container[73].i= 147
container[73].j= 604
container[73].angle= 180
container[73].value= 255


container[74].bin= 63
container[74].i= 148
container[74].j= 595
container[74].angle= 315
container[74].value= 255


container[75].bin= 44
container[75].i= 148
container[75].j= 598
container[75].angle= 224
container[75].value= 255


container[76].bin= 63
container[76].i= 148
container[76].j= 601
container[76].angle= 315
container[76].value= 255


container[77].bin= 36
container[77].i= 148
container[77].j= 604
container[77].angle= 180
container[77].value= 255


container[78].bin= 0
container[78].i= 149
container[78].j= 595
container[78].angle= 0
container[78].value= 255


container[79].bin= 0
container[79].i= 149
container[79].j= 601
container[79].angle= 0
container[79].value= 255


container[80].bin= 36
container[80].i= 149
container[80].j= 604
container[80].angle= 180
container[80].value= 255


container[81].bin= 63
container[81].i= 150
container[81].j= 596
container[81].angle= 315
container[81].value= 255


container[82].bin= 44
container[82].i= 150
container[82].j= 597
container[82].angle= 224
container[82].value= 255


container[83].bin= 5
container[83].i= 150
container[83].j= 601
container[83].angle= 26
container[83].value= 255


container[84].bin= 30
container[84].i= 150
container[84].j= 605
container[84].angle= 153
container[84].value= 255


container[85].bin= 5
container[85].i= 151
container[85].j= 601
container[85].angle= 26
container[85].value= 255


container[86].bin= 30
container[86].i= 151
container[86].j= 605
container[86].angle= 153
container[86].value= 255


container[87].bin= 0
container[87].i= 152
container[87].j= 600
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 152
container[88].j= 605
container[88].angle= 180
container[88].value= 255


container[89].bin= 66
container[89].i= 153
container[89].j= 601
container[89].angle= 333
container[89].value= 255


container[90].bin= 36
container[90].i= 153
container[90].j= 605
container[90].angle= 180
container[90].value= 255


container[91].bin= 66
container[91].i= 154
container[91].j= 601
container[91].angle= 333
container[91].value= 255


container[92].bin= 36
container[92].i= 154
container[92].j= 605
container[92].angle= 180
container[92].value= 255


container[93].bin= 0
container[93].i= 155
container[93].j= 601
container[93].angle= 0
container[93].value= 255


container[94].bin= 36
container[94].i= 155
container[94].j= 605
container[94].angle= 180
container[94].value= 255


container[95].bin= 63
container[95].i= 156
container[95].j= 602
container[95].angle= 315
container[95].value= 255


container[96].bin= 36
container[96].i= 156
container[96].j= 605
container[96].angle= 180
container[96].value= 255


container[97].bin= 63
container[97].i= 157
container[97].j= 603
container[97].angle= 315
container[97].value= 255


container[98].bin= 0
container[98].i= 158
container[98].j= 603
container[98].angle= 0
container[98].value= 255


container[99].bin= 63
container[99].i= 159
container[99].j= 604
container[99].angle= 315
container[99].value= 255


container[100].bin= 44
container[100].i= 159
container[100].j= 605
container[100].angle= 224
container[100].value= 255


