container[0].bin= 8
container[0].i= 256
container[0].j= 407
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 256
container[1].j= 408
container[1].angle= 135
container[1].value= 255


container[2].bin= 5
container[2].i= 257
container[2].j= 406
container[2].angle= 26
container[2].value= 255


container[3].bin= 0
container[3].i= 258
container[3].j= 406
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 258
container[4].j= 409
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 259
container[5].j= 406
container[5].angle= 333
container[5].value= 255


container[6].bin= 30
container[6].i= 259
container[6].j= 409
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 260
container[7].j= 406
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 260
container[8].j= 409
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 261
container[9].j= 407
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 261
container[10].j= 410
container[10].angle= 135
container[10].value= 255


container[11].bin= 66
container[11].i= 262
container[11].j= 407
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 262
container[12].j= 411
container[12].angle= 135
container[12].value= 255


container[13].bin= 68
container[13].i= 263
container[13].j= 407
container[13].angle= 341
container[13].value= 255


container[14].bin= 63
container[14].i= 263
container[14].j= 408
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 263
container[15].j= 411
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 264
container[16].j= 408
container[16].angle= 315
container[16].value= 255


container[17].bin= 63
container[17].i= 264
container[17].j= 409
container[17].angle= 315
container[17].value= 255


container[18].bin= 27
container[18].i= 264
container[18].j= 412
container[18].angle= 135
container[18].value= 255


container[19].bin= 27
container[19].i= 265
container[19].j= 413
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 266
container[20].j= 410
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 266
container[21].j= 414
container[21].angle= 153
container[21].value= 255


container[22].bin= 63
container[22].i= 267
container[22].j= 410
container[22].angle= 315
container[22].value= 255


container[23].bin= 59
container[23].i= 267
container[23].j= 411
container[23].angle= 296
container[23].value= 255


container[24].bin= 27
container[24].i= 267
container[24].j= 414
container[24].angle= 135
container[24].value= 255


container[25].bin= 23
container[25].i= 267
container[25].j= 415
container[25].angle= 116
container[25].value= 255


container[26].bin= 63
container[26].i= 268
container[26].j= 412
container[26].angle= 315
container[26].value= 255


container[27].bin= 27
container[27].i= 268
container[27].j= 416
container[27].angle= 135
container[27].value= 255


container[28].bin= 0
container[28].i= 269
container[28].j= 412
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 269
container[29].j= 416
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 270
container[30].j= 413
container[30].angle= 315
container[30].value= 255


container[31].bin= 54
container[31].i= 270
container[31].j= 414
container[31].angle= 270
container[31].value= 255


container[32].bin= 54
container[32].i= 270
container[32].j= 415
container[32].angle= 270
container[32].value= 255


container[33].bin= 44
container[33].i= 270
container[33].j= 416
container[33].angle= 224
container[33].value= 255


