container[0].bin= 18
container[0].i= 201
container[0].j= 183
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 201
container[1].j= 184
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 201
container[2].j= 185
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 201
container[3].j= 186
container[3].angle= 90
container[3].value= 255


container[4].bin= 21
container[4].i= 201
container[4].j= 187
container[4].angle= 108
container[4].value= 255


container[5].bin= 8
container[5].i= 202
container[5].j= 182
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 202
container[6].j= 187
container[6].angle= 135
container[6].value= 255


container[7].bin= 66
container[7].i= 203
container[7].j= 182
container[7].angle= 333
container[7].value= 255


container[8].bin= 0
container[8].i= 203
container[8].j= 186
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 203
container[9].j= 188
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 204
container[10].j= 182
container[10].angle= 333
container[10].value= 255


container[11].bin= 21
container[11].i= 204
container[11].j= 184
container[11].angle= 108
container[11].value= 255


container[12].bin= 18
container[12].i= 204
container[12].j= 185
container[12].angle= 90
container[12].value= 255


container[13].bin= 14
container[13].i= 204
container[13].j= 186
container[13].angle= 71
container[13].value= 255


container[14].bin= 0
container[14].i= 205
container[14].j= 182
container[14].angle= 0
container[14].value= 255


container[15].bin= 39
container[15].i= 205
container[15].j= 187
container[15].angle= 198
container[15].value= 255


container[16].bin= 0
container[16].i= 206
container[16].j= 182
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 206
container[17].j= 186
container[17].angle= 180
container[17].value= 255


container[18].bin= 27
container[18].i= 206
container[18].j= 189
container[18].angle= 135
container[18].value= 255


container[19].bin= 63
container[19].i= 207
container[19].j= 183
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 207
container[20].j= 187
container[20].angle= 135
container[20].value= 255


container[21].bin= 27
container[21].i= 207
container[21].j= 189
container[21].angle= 135
container[21].value= 255


container[22].bin= 63
container[22].i= 208
container[22].j= 184
container[22].angle= 315
container[22].value= 255


container[23].bin= 32
container[23].i= 208
container[23].j= 189
container[23].angle= 161
container[23].value= 255


container[24].bin= 0
container[24].i= 209
container[24].j= 184
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 209
container[25].j= 189
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 210
container[26].j= 185
container[26].angle= 315
container[26].value= 255


container[27].bin= 54
container[27].i= 210
container[27].j= 186
container[27].angle= 270
container[27].value= 255


container[28].bin= 54
container[28].i= 210
container[28].j= 188
container[28].angle= 270
container[28].value= 255


container[29].bin= 41
container[29].i= 210
container[29].j= 189
container[29].angle= 206
container[29].value= 255


container[30].bin= 63
container[30].i= 211
container[30].j= 187
container[30].angle= 315
container[30].value= 255


container[31].bin= 41
container[31].i= 211
container[31].j= 189
container[31].angle= 206
container[31].value= 255


container[32].bin= 0
container[32].i= 212
container[32].j= 187
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 212
container[33].j= 189
container[33].angle= 180
container[33].value= 255


container[34].bin= 68
container[34].i= 213
container[34].j= 187
container[34].angle= 341
container[34].value= 255


container[35].bin= 54
container[35].i= 213
container[35].j= 188
container[35].angle= 270
container[35].value= 255


container[36].bin= 39
container[36].i= 213
container[36].j= 189
container[36].angle= 198
container[36].value= 255


