container[0].bin= 18
container[0].i= 902
container[0].j= 178
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 902
container[1].j= 179
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 902
container[2].j= 180
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 903
container[3].j= 177
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 903
container[4].j= 181
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 904
container[5].j= 176
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 904
container[6].j= 181
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 905
container[7].j= 177
container[7].angle= 315
container[7].value= 255


container[8].bin= 54
container[8].i= 905
container[8].j= 178
container[8].angle= 270
container[8].value= 255


container[9].bin= 27
container[9].i= 905
container[9].j= 182
container[9].angle= 135
container[9].value= 255


container[10].bin= 18
container[10].i= 905
container[10].j= 183
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 905
container[11].j= 184
container[11].angle= 90
container[11].value= 255


container[12].bin= 18
container[12].i= 905
container[12].j= 185
container[12].angle= 90
container[12].value= 255


container[13].bin= 18
container[13].i= 905
container[13].j= 186
container[13].angle= 90
container[13].value= 255


container[14].bin= 21
container[14].i= 905
container[14].j= 187
container[14].angle= 108
container[14].value= 255


container[15].bin= 63
container[15].i= 906
container[15].j= 179
container[15].angle= 315
container[15].value= 255


container[16].bin= 0
container[16].i= 907
container[16].j= 179
container[16].angle= 0
container[16].value= 255


container[17].bin= 32
container[17].i= 907
container[17].j= 187
container[17].angle= 161
container[17].value= 255


container[18].bin= 63
container[18].i= 908
container[18].j= 180
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 908
container[19].j= 181
container[19].angle= 270
container[19].value= 255


container[20].bin= 23
container[20].i= 908
container[20].j= 188
container[20].angle= 116
container[20].value= 255


container[21].bin= 27
container[21].i= 908
container[21].j= 189
container[21].angle= 135
container[21].value= 255


container[22].bin= 63
container[22].i= 909
container[22].j= 182
container[22].angle= 315
container[22].value= 255


container[23].bin= 30
container[23].i= 909
container[23].j= 189
container[23].angle= 153
container[23].value= 255


container[24].bin= 18
container[24].i= 909
container[24].j= 191
container[24].angle= 90
container[24].value= 255


container[25].bin= 0
container[25].i= 910
container[25].j= 182
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 910
container[26].j= 189
container[26].angle= 180
container[26].value= 255


container[27].bin= 32
container[27].i= 910
container[27].j= 192
container[27].angle= 161
container[27].value= 255


container[28].bin= 63
container[28].i= 911
container[28].j= 183
container[28].angle= 315
container[28].value= 255


container[29].bin= 32
container[29].i= 911
container[29].j= 189
container[29].angle= 161
container[29].value= 255


container[30].bin= 27
container[30].i= 911
container[30].j= 192
container[30].angle= 135
container[30].value= 255


container[31].bin= 18
container[31].i= 911
container[31].j= 193
container[31].angle= 90
container[31].value= 255


container[32].bin= 18
container[32].i= 911
container[32].j= 194
container[32].angle= 90
container[32].value= 255


container[33].bin= 63
container[33].i= 912
container[33].j= 184
container[33].angle= 315
container[33].value= 255


container[34].bin= 27
container[34].i= 912
container[34].j= 195
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 913
container[35].j= 184
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 913
container[36].j= 195
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 914
container[37].j= 184
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 914
container[38].j= 195
container[38].angle= 180
container[38].value= 255


