container[0].bin= 0
container[0].i= 0
container[0].j= 2
container[0].angle= 0
container[0].value= 255


container[1].bin= 0
container[1].i= 0
container[1].j= 3
container[1].angle= 0
container[1].value= 255


container[2].bin= 8
container[2].i= 1
container[2].j= 1
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 1
container[3].j= 4
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 2
container[4].j= 0
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 2
container[5].j= 5
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 3
container[6].j= 0
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 3
container[7].j= 5
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 3
container[8].j= 6
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 4
container[9].j= 0
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 4
container[10].j= 6
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 5
container[11].j= 0
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 5
container[12].j= 6
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 6
container[13].j= 0
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 6
container[14].j= 7
container[14].angle= 135
container[14].value= 255


container[15].bin= 18
container[15].i= 6
container[15].j= 8
container[15].angle= 90
container[15].value= 255


container[16].bin= 0
container[16].i= 7
container[16].j= 0
container[16].angle= 0
container[16].value= 255


container[17].bin= 27
container[17].i= 7
container[17].j= 9
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 8
container[18].j= 0
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 8
container[19].j= 9
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 9
container[20].j= 0
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 9
container[21].j= 10
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 10
container[22].j= 0
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 10
container[23].j= 10
container[23].angle= 135
container[23].value= 255


container[24].bin= 27
container[24].i= 10
container[24].j= 11
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 11
container[25].j= 0
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 11
container[26].j= 11
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 12
container[27].j= 0
container[27].angle= 0
container[27].value= 255


container[28].bin= 27
container[28].i= 12
container[28].j= 12
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 13
container[29].j= 0
container[29].angle= 0
container[29].value= 255


container[30].bin= 27
container[30].i= 13
container[30].j= 13
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 14
container[31].j= 0
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 14
container[32].j= 13
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 15
container[33].j= 1
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 15
container[34].j= 14
container[34].angle= 135
container[34].value= 255


container[35].bin= 66
container[35].i= 16
container[35].j= 1
container[35].angle= 333
container[35].value= 255


container[36].bin= 27
container[36].i= 16
container[36].j= 15
container[36].angle= 135
container[36].value= 255


container[37].bin= 0
container[37].i= 17
container[37].j= 1
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 17
container[38].j= 15
container[38].angle= 180
container[38].value= 255


container[39].bin= 63
container[39].i= 18
container[39].j= 2
container[39].angle= 315
container[39].value= 255


container[40].bin= 54
container[40].i= 18
container[40].j= 4
container[40].angle= 270
container[40].value= 255


container[41].bin= 27
container[41].i= 18
container[41].j= 16
container[41].angle= 135
container[41].value= 255


container[42].bin= 18
container[42].i= 18
container[42].j= 17
container[42].angle= 90
container[42].value= 255


container[43].bin= 63
container[43].i= 19
container[43].j= 3
container[43].angle= 315
container[43].value= 255


container[44].bin= 44
container[44].i= 19
container[44].j= 5
container[44].angle= 224
container[44].value= 255


container[45].bin= 63
container[45].i= 19
container[45].j= 6
container[45].angle= 315
container[45].value= 255


container[46].bin= 23
container[46].i= 19
container[46].j= 18
container[46].angle= 116
container[46].value= 255


container[47].bin= 27
container[47].i= 19
container[47].j= 19
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 20
container[48].j= 3
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 20
container[49].j= 5
container[49].angle= 180
container[49].value= 255


container[50].bin= 36
container[50].i= 20
container[50].j= 19
container[50].angle= 180
container[50].value= 255


container[51].bin= 68
container[51].i= 21
container[51].j= 3
container[51].angle= 341
container[51].value= 255


container[52].bin= 54
container[52].i= 21
container[52].j= 4
container[52].angle= 270
container[52].value= 255


container[53].bin= 39
container[53].i= 21
container[53].j= 5
container[53].angle= 198
container[53].value= 255


container[54].bin= 63
container[54].i= 21
container[54].j= 7
container[54].angle= 315
container[54].value= 255


container[55].bin= 32
container[55].i= 21
container[55].j= 19
container[55].angle= 161
container[55].value= 255


container[56].bin= 21
container[56].i= 21
container[56].j= 20
container[56].angle= 108
container[56].value= 255


container[57].bin= 63
container[57].i= 22
container[57].j= 8
container[57].angle= 315
container[57].value= 255


container[58].bin= 27
container[58].i= 22
container[58].j= 21
container[58].angle= 135
container[58].value= 255


container[59].bin= 0
container[59].i= 23
container[59].j= 8
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 23
container[60].j= 21
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 24
container[61].j= 9
container[61].angle= 315
container[61].value= 255


container[62].bin= 54
container[62].i= 24
container[62].j= 10
container[62].angle= 270
container[62].value= 255


container[63].bin= 27
container[63].i= 24
container[63].j= 22
container[63].angle= 135
container[63].value= 255


container[64].bin= 18
container[64].i= 24
container[64].j= 23
container[64].angle= 90
container[64].value= 255


container[65].bin= 18
container[65].i= 24
container[65].j= 24
container[65].angle= 90
container[65].value= 255


container[66].bin= 63
container[66].i= 25
container[66].j= 11
container[66].angle= 315
container[66].value= 255


container[67].bin= 54
container[67].i= 25
container[67].j= 14
container[67].angle= 270
container[67].value= 255


container[68].bin= 63
container[68].i= 25
container[68].j= 15
container[68].angle= 315
container[68].value= 255


container[69].bin= 27
container[69].i= 25
container[69].j= 25
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 26
container[70].j= 11
container[70].angle= 0
container[70].value= 255


container[71].bin= 0
container[71].i= 26
container[71].j= 15
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 26
container[72].j= 25
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 27
container[73].j= 12
container[73].angle= 315
container[73].value= 255


container[74].bin= 50
container[74].i= 27
container[74].j= 13
container[74].angle= 251
container[74].value= 255


container[75].bin= 57
container[75].i= 27
container[75].j= 15
container[75].angle= 288
container[75].value= 255


container[76].bin= 54
container[76].i= 27
container[76].j= 16
container[76].angle= 270
container[76].value= 255


container[77].bin= 27
container[77].i= 27
container[77].j= 26
container[77].angle= 135
container[77].value= 255


container[78].bin= 54
container[78].i= 28
container[78].j= 14
container[78].angle= 270
container[78].value= 255


container[79].bin= 63
container[79].i= 28
container[79].j= 17
container[79].angle= 315
container[79].value= 255


container[80].bin= 23
container[80].i= 28
container[80].j= 27
container[80].angle= 116
container[80].value= 255


container[81].bin= 27
container[81].i= 28
container[81].j= 28
container[81].angle= 135
container[81].value= 255


container[82].bin= 0
container[82].i= 29
container[82].j= 17
container[82].angle= 0
container[82].value= 255


container[83].bin= 30
container[83].i= 29
container[83].j= 28
container[83].angle= 153
container[83].value= 255


container[84].bin= 63
container[84].i= 30
container[84].j= 18
container[84].angle= 315
container[84].value= 255


container[85].bin= 54
container[85].i= 30
container[85].j= 19
container[85].angle= 270
container[85].value= 255


container[86].bin= 54
container[86].i= 30
container[86].j= 20
container[86].angle= 270
container[86].value= 255


container[87].bin= 54
container[87].i= 30
container[87].j= 21
container[87].angle= 270
container[87].value= 255


container[88].bin= 36
container[88].i= 30
container[88].j= 28
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 31
container[89].j= 22
container[89].angle= 315
container[89].value= 255


container[90].bin= 30
container[90].i= 31
container[90].j= 29
container[90].angle= 153
container[90].value= 255


container[91].bin= 63
container[91].i= 32
container[91].j= 23
container[91].angle= 315
container[91].value= 255


container[92].bin= 30
container[92].i= 32
container[92].j= 29
container[92].angle= 153
container[92].value= 255


container[93].bin= 59
container[93].i= 33
container[93].j= 24
container[93].angle= 296
container[93].value= 255


container[94].bin= 59
container[94].i= 33
container[94].j= 25
container[94].angle= 296
container[94].value= 255


container[95].bin= 54
container[95].i= 33
container[95].j= 26
container[95].angle= 270
container[95].value= 255


container[96].bin= 54
container[96].i= 33
container[96].j= 27
container[96].angle= 270
container[96].value= 255


container[97].bin= 54
container[97].i= 33
container[97].j= 28
container[97].angle= 270
container[97].value= 255


container[98].bin= 44
container[98].i= 33
container[98].j= 29
container[98].angle= 224
container[98].value= 255


