container[0].bin= 18
container[0].i= 90
container[0].j= 619
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 91
container[1].j= 618
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 91
container[2].j= 620
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 92
container[3].j= 617
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 92
container[4].j= 620
container[4].angle= 180
container[4].value= 255


container[5].bin= 66
container[5].i= 93
container[5].j= 618
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 93
container[6].j= 621
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 93
container[7].j= 622
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 93
container[8].j= 623
container[8].angle= 90
container[8].value= 255


container[9].bin= 66
container[9].i= 94
container[9].j= 618
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 94
container[10].j= 624
container[10].angle= 135
container[10].value= 255


container[11].bin= 66
container[11].i= 95
container[11].j= 619
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 95
container[12].j= 624
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 96
container[13].j= 619
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 96
container[14].j= 624
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 97
container[15].j= 620
container[15].angle= 315
container[15].value= 255


container[16].bin= 57
container[16].i= 97
container[16].j= 621
container[16].angle= 288
container[16].value= 255


container[17].bin= 36
container[17].i= 97
container[17].j= 624
container[17].angle= 180
container[17].value= 255


container[18].bin= 36
container[18].i= 98
container[18].j= 624
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 99
container[19].j= 620
container[19].angle= 44
container[19].value= 255


container[20].bin= 8
container[20].i= 99
container[20].j= 621
container[20].angle= 44
container[20].value= 255


container[21].bin= 36
container[21].i= 99
container[21].j= 624
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 100
container[22].j= 620
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 100
container[23].j= 624
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 101
container[24].j= 620
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 101
container[25].j= 621
container[25].angle= 315
container[25].value= 255


container[26].bin= 36
container[26].i= 101
container[26].j= 624
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 102
container[27].j= 621
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 102
container[28].j= 622
container[28].angle= 296
container[28].value= 255


container[29].bin= 54
container[29].i= 102
container[29].j= 623
container[29].angle= 270
container[29].value= 255


container[30].bin= 44
container[30].i= 102
container[30].j= 624
container[30].angle= 224
container[30].value= 255


