container[0].bin= 18
container[0].i= 369
container[0].j= 178
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 369
container[1].j= 179
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 370
container[2].j= 177
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 370
container[3].j= 180
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 371
container[4].j= 176
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 371
container[5].j= 180
container[5].angle= 180
container[5].value= 255


container[6].bin= 18
container[6].i= 372
container[6].j= 175
container[6].angle= 90
container[6].value= 255


container[7].bin= 3
container[7].i= 372
container[7].j= 176
container[7].angle= 18
container[7].value= 255


container[8].bin= 30
container[8].i= 372
container[8].j= 181
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 373
container[9].j= 174
container[9].angle= 0
container[9].value= 255


container[10].bin= 8
container[10].i= 373
container[10].j= 176
container[10].angle= 44
container[10].value= 255


container[11].bin= 30
container[11].i= 373
container[11].j= 181
container[11].angle= 153
container[11].value= 255


container[12].bin= 68
container[12].i= 374
container[12].j= 175
container[12].angle= 341
container[12].value= 255


container[13].bin= 36
container[13].i= 374
container[13].j= 181
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 375
container[14].j= 176
container[14].angle= 333
container[14].value= 255


container[15].bin= 39
container[15].i= 375
container[15].j= 178
container[15].angle= 198
container[15].value= 255


container[16].bin= 50
container[16].i= 375
container[16].j= 179
container[16].angle= 251
container[16].value= 255


container[17].bin= 59
container[17].i= 375
container[17].j= 180
container[17].angle= 296
container[17].value= 255


container[18].bin= 44
container[18].i= 375
container[18].j= 181
container[18].angle= 224
container[18].value= 255


container[19].bin= 66
container[19].i= 376
container[19].j= 176
container[19].angle= 333
container[19].value= 255


container[20].bin= 0
container[20].i= 377
container[20].j= 176
container[20].angle= 0
container[20].value= 255


container[21].bin= 63
container[21].i= 378
container[21].j= 177
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 378
container[22].j= 178
container[22].angle= 224
container[22].value= 255


