container[0].bin= 18
container[0].i= 604
container[0].j= 260
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 605
container[1].j= 259
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 605
container[2].j= 261
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 606
container[3].j= 259
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 606
container[4].j= 261
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 607
container[5].j= 258
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 607
container[6].j= 259
container[6].angle= 44
container[6].value= 255


container[7].bin= 36
container[7].i= 607
container[7].j= 261
container[7].angle= 180
container[7].value= 255


container[8].bin= 8
container[8].i= 608
container[8].j= 257
container[8].angle= 44
container[8].value= 255


container[9].bin= 0
container[9].i= 609
container[9].j= 256
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 609
container[10].j= 260
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 610
container[11].j= 256
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 610
container[12].j= 260
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 611
container[13].j= 256
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 611
container[14].j= 260
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 612
container[15].j= 256
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 612
container[16].j= 260
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 613
container[17].j= 257
container[17].angle= 315
container[17].value= 255


container[18].bin= 54
container[18].i= 613
container[18].j= 258
container[18].angle= 270
container[18].value= 255


container[19].bin= 63
container[19].i= 614
container[19].j= 259
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 614
container[20].j= 261
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 615
container[21].j= 259
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 615
container[22].j= 261
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 616
container[23].j= 259
container[23].angle= 341
container[23].value= 255


container[24].bin= 54
container[24].i= 616
container[24].j= 260
container[24].angle= 270
container[24].value= 255


container[25].bin= 39
container[25].i= 616
container[25].j= 261
container[25].angle= 198
container[25].value= 255


