container[0].bin= 18
container[0].i= 113
container[0].j= 135
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 114
container[1].j= 134
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 114
container[2].j= 136
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 115
container[3].j= 134
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 115
container[4].j= 136
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 116
container[5].j= 134
container[5].angle= 0
container[5].value= 255


container[6].bin= 44
container[6].i= 117
container[6].j= 136
container[6].angle= 224
container[6].value= 255


