container[0].bin= 18
container[0].i= 303
container[0].j= 424
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 304
container[1].j= 423
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 304
container[2].j= 425
container[2].angle= 135
container[2].value= 255


container[3].bin= 66
container[3].i= 305
container[3].j= 423
container[3].angle= 333
container[3].value= 255


container[4].bin= 36
container[4].i= 305
container[4].j= 425
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 306
container[5].j= 423
container[5].angle= 315
container[5].value= 255


container[6].bin= 59
container[6].i= 306
container[6].j= 424
container[6].angle= 296
container[6].value= 255


container[7].bin= 27
container[7].i= 307
container[7].j= 427
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 308
container[8].j= 425
container[8].angle= 0
container[8].value= 255


container[9].bin= 0
container[9].i= 309
container[9].j= 425
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 309
container[10].j= 428
container[10].angle= 135
container[10].value= 255


container[11].bin= 18
container[11].i= 309
container[11].j= 429
container[11].angle= 90
container[11].value= 255


container[12].bin= 0
container[12].i= 310
container[12].j= 425
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 310
container[13].j= 430
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 311
container[14].j= 425
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 311
container[15].j= 430
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 312
container[16].j= 426
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 312
container[17].j= 427
container[17].angle= 270
container[17].value= 255


container[18].bin= 27
container[18].i= 312
container[18].j= 431
container[18].angle= 135
container[18].value= 255


container[19].bin= 63
container[19].i= 313
container[19].j= 428
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 313
container[20].j= 432
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 314
container[21].j= 428
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 314
container[22].j= 433
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 315
container[23].j= 429
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 315
container[24].j= 430
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 315
container[25].j= 431
container[25].angle= 270
container[25].value= 255


