container[0].bin= 14
container[0].i= 240
container[0].j= 282
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 240
container[1].j= 283
container[1].angle= 108
container[1].value= 255


container[2].bin= 8
container[2].i= 241
container[2].j= 277
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 241
container[3].j= 278
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 241
container[4].j= 281
container[4].angle= 44
container[4].value= 255


container[5].bin= 8
container[5].i= 241
container[5].j= 282
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 241
container[6].j= 283
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 242
container[7].j= 276
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 242
container[8].j= 284
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 243
container[9].j= 277
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 243
container[10].j= 279
container[10].angle= 135
container[10].value= 255


container[11].bin= 14
container[11].i= 243
container[11].j= 280
container[11].angle= 71
container[11].value= 255


container[12].bin= 8
container[12].i= 243
container[12].j= 281
container[12].angle= 44
container[12].value= 255


container[13].bin= 8
container[13].i= 243
container[13].j= 282
container[13].angle= 44
container[13].value= 255


container[14].bin= 27
container[14].i= 243
container[14].j= 284
container[14].angle= 135
container[14].value= 255


container[15].bin= 18
container[15].i= 243
container[15].j= 285
container[15].angle= 90
container[15].value= 255


container[16].bin= 66
container[16].i= 244
container[16].j= 277
container[16].angle= 333
container[16].value= 255


container[17].bin= 27
container[17].i= 244
container[17].j= 286
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 245
container[18].j= 277
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 245
container[19].j= 286
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 246
container[20].j= 278
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 246
container[21].j= 283
container[21].angle= 270
container[21].value= 255


container[22].bin= 54
container[22].i= 246
container[22].j= 284
container[22].angle= 270
container[22].value= 255


container[23].bin= 54
container[23].i= 246
container[23].j= 285
container[23].angle= 270
container[23].value= 255


container[24].bin= 44
container[24].i= 246
container[24].j= 286
container[24].angle= 224
container[24].value= 255


container[25].bin= 63
container[25].i= 247
container[25].j= 279
container[25].angle= 315
container[25].value= 255


container[26].bin= 44
container[26].i= 247
container[26].j= 282
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 248
container[27].j= 279
container[27].angle= 0
container[27].value= 255


container[28].bin= 63
container[28].i= 249
container[28].j= 280
container[28].angle= 315
container[28].value= 255


container[29].bin= 44
container[29].i= 249
container[29].j= 281
container[29].angle= 224
container[29].value= 255


