container[0].bin= 18
container[0].i= 324
container[0].j= 261
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 324
container[1].j= 262
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 324
container[2].j= 263
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 324
container[3].j= 264
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 325
container[4].j= 260
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 325
container[5].j= 265
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 326
container[6].j= 259
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 326
container[7].j= 265
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 327
container[8].j= 259
container[8].angle= 0
container[8].value= 255


container[9].bin= 44
container[9].i= 327
container[9].j= 265
container[9].angle= 224
container[9].value= 255


container[10].bin= 0
container[10].i= 328
container[10].j= 259
container[10].angle= 0
container[10].value= 255


container[11].bin= 44
container[11].i= 328
container[11].j= 264
container[11].angle= 224
container[11].value= 255


container[12].bin= 0
container[12].i= 329
container[12].j= 259
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 329
container[13].j= 263
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 330
container[14].j= 260
container[14].angle= 315
container[14].value= 255


container[15].bin= 54
container[15].i= 330
container[15].j= 261
container[15].angle= 270
container[15].value= 255


container[16].bin= 54
container[16].i= 330
container[16].j= 262
container[16].angle= 270
container[16].value= 255


container[17].bin= 44
container[17].i= 330
container[17].j= 263
container[17].angle= 224
container[17].value= 255


