container[0].bin= 18
container[0].i= 507
container[0].j= 525
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 508
container[1].j= 524
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 508
container[2].j= 526
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 509
container[3].j= 524
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 509
container[4].j= 526
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 510
container[5].j= 524
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 510
container[6].j= 526
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 510
container[7].j= 527
container[7].angle= 90
container[7].value= 255


container[8].bin= 5
container[8].i= 511
container[8].j= 524
container[8].angle= 26
container[8].value= 255


container[9].bin= 27
container[9].i= 511
container[9].j= 528
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 512
container[10].j= 524
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 512
container[11].j= 528
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 513
container[12].j= 524
container[12].angle= 315
container[12].value= 255


container[13].bin= 59
container[13].i= 513
container[13].j= 525
container[13].angle= 296
container[13].value= 255


container[14].bin= 36
container[14].i= 513
container[14].j= 528
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 514
container[15].j= 526
container[15].angle= 315
container[15].value= 255


container[16].bin= 0
container[16].i= 515
container[16].j= 526
container[16].angle= 0
container[16].value= 255


container[17].bin= 63
container[17].i= 516
container[17].j= 527
container[17].angle= 315
container[17].value= 255


container[18].bin= 27
container[18].i= 517
container[18].j= 530
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 518
container[19].j= 528
container[19].angle= 0
container[19].value= 255


container[20].bin= 63
container[20].i= 519
container[20].j= 529
container[20].angle= 315
container[20].value= 255


container[21].bin= 44
container[21].i= 519
container[21].j= 530
container[21].angle= 224
container[21].value= 255


