container[0].bin= 18
container[0].i= 167
container[0].j= 26
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 168
container[1].j= 25
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 168
container[2].j= 27
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 169
container[3].j= 24
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 169
container[4].j= 27
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 170
container[5].j= 24
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 170
container[6].j= 27
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 171
container[7].j= 24
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 171
container[8].j= 27
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 172
container[9].j= 24
container[9].angle= 0
container[9].value= 255


container[10].bin= 41
container[10].i= 172
container[10].j= 27
container[10].angle= 206
container[10].value= 255


container[11].bin= 0
container[11].i= 173
container[11].j= 24
container[11].angle= 0
container[11].value= 255


container[12].bin= 41
container[12].i= 173
container[12].j= 27
container[12].angle= 206
container[12].value= 255


container[13].bin= 5
container[13].i= 174
container[13].j= 24
container[13].angle= 26
container[13].value= 255


container[14].bin= 30
container[14].i= 174
container[14].j= 27
container[14].angle= 153
container[14].value= 255


container[15].bin= 5
container[15].i= 175
container[15].j= 24
container[15].angle= 26
container[15].value= 255


container[16].bin= 30
container[16].i= 175
container[16].j= 27
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 176
container[17].j= 23
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 176
container[18].j= 27
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 177
container[19].j= 23
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 177
container[20].j= 28
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 178
container[21].j= 23
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 178
container[22].j= 28
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 179
container[23].j= 23
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 179
container[24].j= 29
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 180
container[25].j= 23
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 180
container[26].j= 29
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 181
container[27].j= 23
container[27].angle= 0
container[27].value= 255


container[28].bin= 27
container[28].i= 181
container[28].j= 30
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 182
container[29].j= 23
container[29].angle= 0
container[29].value= 255


container[30].bin= 23
container[30].i= 182
container[30].j= 31
container[30].angle= 116
container[30].value= 255


container[31].bin= 27
container[31].i= 182
container[31].j= 32
container[31].angle= 135
container[31].value= 255


container[32].bin= 0
container[32].i= 183
container[32].j= 23
container[32].angle= 0
container[32].value= 255


container[33].bin= 27
container[33].i= 183
container[33].j= 32
container[33].angle= 135
container[33].value= 255


container[34].bin= 27
container[34].i= 183
container[34].j= 33
container[34].angle= 135
container[34].value= 255


container[35].bin= 66
container[35].i= 184
container[35].j= 24
container[35].angle= 333
container[35].value= 255


container[36].bin= 30
container[36].i= 184
container[36].j= 33
container[36].angle= 153
container[36].value= 255


container[37].bin= 66
container[37].i= 185
container[37].j= 24
container[37].angle= 333
container[37].value= 255


container[38].bin= 30
container[38].i= 185
container[38].j= 34
container[38].angle= 153
container[38].value= 255


container[39].bin= 66
container[39].i= 186
container[39].j= 25
container[39].angle= 333
container[39].value= 255


container[40].bin= 27
container[40].i= 186
container[40].j= 34
container[40].angle= 135
container[40].value= 255


container[41].bin= 27
container[41].i= 186
container[41].j= 35
container[41].angle= 135
container[41].value= 255


container[42].bin= 63
container[42].i= 187
container[42].j= 25
container[42].angle= 315
container[42].value= 255


container[43].bin= 63
container[43].i= 187
container[43].j= 26
container[43].angle= 315
container[43].value= 255


container[44].bin= 27
container[44].i= 187
container[44].j= 35
container[44].angle= 135
container[44].value= 255


container[45].bin= 27
container[45].i= 187
container[45].j= 36
container[45].angle= 135
container[45].value= 255


container[46].bin= 66
container[46].i= 188
container[46].j= 26
container[46].angle= 333
container[46].value= 255


container[47].bin= 27
container[47].i= 188
container[47].j= 36
container[47].angle= 135
container[47].value= 255


container[48].bin= 27
container[48].i= 188
container[48].j= 37
container[48].angle= 135
container[48].value= 255


container[49].bin= 66
container[49].i= 189
container[49].j= 27
container[49].angle= 333
container[49].value= 255


container[50].bin= 30
container[50].i= 189
container[50].j= 37
container[50].angle= 153
container[50].value= 255


container[51].bin= 66
container[51].i= 190
container[51].j= 27
container[51].angle= 333
container[51].value= 255


container[52].bin= 30
container[52].i= 190
container[52].j= 38
container[52].angle= 153
container[52].value= 255


container[53].bin= 63
container[53].i= 191
container[53].j= 28
container[53].angle= 315
container[53].value= 255


container[54].bin= 54
container[54].i= 191
container[54].j= 29
container[54].angle= 270
container[54].value= 255


container[55].bin= 54
container[55].i= 191
container[55].j= 30
container[55].angle= 270
container[55].value= 255


container[56].bin= 54
container[56].i= 191
container[56].j= 31
container[56].angle= 270
container[56].value= 255


container[57].bin= 30
container[57].i= 191
container[57].j= 38
container[57].angle= 153
container[57].value= 255


container[58].bin= 59
container[58].i= 192
container[58].j= 32
container[58].angle= 296
container[58].value= 255


container[59].bin= 63
container[59].i= 192
container[59].j= 33
container[59].angle= 315
container[59].value= 255


container[60].bin= 36
container[60].i= 192
container[60].j= 38
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 193
container[61].j= 33
container[61].angle= 315
container[61].value= 255


container[62].bin= 59
container[62].i= 193
container[62].j= 34
container[62].angle= 296
container[62].value= 255


container[63].bin= 36
container[63].i= 193
container[63].j= 38
container[63].angle= 180
container[63].value= 255


container[64].bin= 59
container[64].i= 194
container[64].j= 35
container[64].angle= 296
container[64].value= 255


container[65].bin= 63
container[65].i= 194
container[65].j= 36
container[65].angle= 315
container[65].value= 255


container[66].bin= 36
container[66].i= 194
container[66].j= 38
container[66].angle= 180
container[66].value= 255


container[67].bin= 63
container[67].i= 195
container[67].j= 36
container[67].angle= 315
container[67].value= 255


container[68].bin= 59
container[68].i= 195
container[68].j= 37
container[68].angle= 296
container[68].value= 255


container[69].bin= 44
container[69].i= 195
container[69].j= 38
container[69].angle= 224
container[69].value= 255


