container[0].bin= 8
container[0].i= 659
container[0].j= 477
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 659
container[1].j= 478
container[1].angle= 116
container[1].value= 255


container[2].bin= 18
container[2].i= 659
container[2].j= 479
container[2].angle= 90
container[2].value= 255


container[3].bin= 21
container[3].i= 659
container[3].j= 480
container[3].angle= 108
container[3].value= 255


container[4].bin= 0
container[4].i= 660
container[4].j= 476
container[4].angle= 0
container[4].value= 255


container[5].bin= 32
container[5].i= 660
container[5].j= 480
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 661
container[6].j= 476
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 661
container[7].j= 481
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 661
container[8].j= 482
container[8].angle= 90
container[8].value= 255


container[9].bin= 0
container[9].i= 662
container[9].j= 476
container[9].angle= 0
container[9].value= 255


container[10].bin= 18
container[10].i= 662
container[10].j= 478
container[10].angle= 90
container[10].value= 255


container[11].bin= 8
container[11].i= 662
container[11].j= 479
container[11].angle= 44
container[11].value= 255


container[12].bin= 27
container[12].i= 662
container[12].j= 483
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 663
container[13].j= 476
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 663
container[14].j= 483
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 664
container[15].j= 476
container[15].angle= 0
container[15].value= 255


container[16].bin= 54
container[16].i= 664
container[16].j= 479
container[16].angle= 270
container[16].value= 255


container[17].bin= 36
container[17].i= 664
container[17].j= 483
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 665
container[18].j= 476
container[18].angle= 0
container[18].value= 255


container[19].bin= 44
container[19].i= 665
container[19].j= 478
container[19].angle= 224
container[19].value= 255


container[20].bin= 59
container[20].i= 665
container[20].j= 480
container[20].angle= 296
container[20].value= 255


container[21].bin= 63
container[21].i= 665
container[21].j= 481
container[21].angle= 315
container[21].value= 255


container[22].bin= 36
container[22].i= 665
container[22].j= 483
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 666
container[23].j= 476
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 666
container[24].j= 478
container[24].angle= 180
container[24].value= 255


container[25].bin= 66
container[25].i= 666
container[25].j= 481
container[25].angle= 333
container[25].value= 255


container[26].bin= 41
container[26].i= 666
container[26].j= 483
container[26].angle= 206
container[26].value= 255


container[27].bin= 68
container[27].i= 667
container[27].j= 476
container[27].angle= 341
container[27].value= 255


container[28].bin= 54
container[28].i= 667
container[28].j= 477
container[28].angle= 270
container[28].value= 255


container[29].bin= 39
container[29].i= 667
container[29].j= 478
container[29].angle= 198
container[29].value= 255


container[30].bin= 0
container[30].i= 667
container[30].j= 481
container[30].angle= 0
container[30].value= 255


container[31].bin= 41
container[31].i= 667
container[31].j= 483
container[31].angle= 206
container[31].value= 255


container[32].bin= 18
container[32].i= 667
container[32].j= 485
container[32].angle= 90
container[32].value= 255


container[33].bin= 0
container[33].i= 668
container[33].j= 481
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 668
container[34].j= 483
container[34].angle= 180
container[34].value= 255


container[35].bin= 32
container[35].i= 668
container[35].j= 486
container[35].angle= 161
container[35].value= 255


container[36].bin= 0
container[36].i= 669
container[36].j= 481
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 669
container[37].j= 483
container[37].angle= 180
container[37].value= 255


container[38].bin= 36
container[38].i= 669
container[38].j= 486
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 670
container[39].j= 481
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 670
container[40].j= 483
container[40].angle= 180
container[40].value= 255


container[41].bin= 27
container[41].i= 670
container[41].j= 486
container[41].angle= 135
container[41].value= 255


container[42].bin= 18
container[42].i= 670
container[42].j= 487
container[42].angle= 90
container[42].value= 255


container[43].bin= 0
container[43].i= 671
container[43].j= 481
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 671
container[44].j= 483
container[44].angle= 180
container[44].value= 255


container[45].bin= 27
container[45].i= 671
container[45].j= 488
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 672
container[46].j= 481
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 672
container[47].j= 483
container[47].angle= 180
container[47].value= 255


container[48].bin= 36
container[48].i= 672
container[48].j= 488
container[48].angle= 180
container[48].value= 255


container[49].bin= 18
container[49].i= 673
container[49].j= 480
container[49].angle= 90
container[49].value= 255


container[50].bin= 8
container[50].i= 673
container[50].j= 481
container[50].angle= 44
container[50].value= 255


container[51].bin= 18
container[51].i= 673
container[51].j= 482
container[51].angle= 90
container[51].value= 255


container[52].bin= 27
container[52].i= 673
container[52].j= 483
container[52].angle= 135
container[52].value= 255


container[53].bin= 8
container[53].i= 673
container[53].j= 484
container[53].angle= 44
container[53].value= 255


container[54].bin= 36
container[54].i= 673
container[54].j= 488
container[54].angle= 180
container[54].value= 255


container[55].bin= 8
container[55].i= 674
container[55].j= 479
container[55].angle= 44
container[55].value= 255


container[56].bin= 36
container[56].i= 674
container[56].j= 488
container[56].angle= 180
container[56].value= 255


container[57].bin= 0
container[57].i= 675
container[57].j= 478
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 675
container[58].j= 488
container[58].angle= 180
container[58].value= 255


container[59].bin= 63
container[59].i= 676
container[59].j= 479
container[59].angle= 315
container[59].value= 255


container[60].bin= 54
container[60].i= 676
container[60].j= 480
container[60].angle= 270
container[60].value= 255


container[61].bin= 44
container[61].i= 676
container[61].j= 488
container[61].angle= 224
container[61].value= 255


container[62].bin= 63
container[62].i= 677
container[62].j= 481
container[62].angle= 315
container[62].value= 255


container[63].bin= 44
container[63].i= 677
container[63].j= 487
container[63].angle= 224
container[63].value= 255


container[64].bin= 0
container[64].i= 678
container[64].j= 481
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 678
container[65].j= 486
container[65].angle= 180
container[65].value= 255


container[66].bin= 63
container[66].i= 679
container[66].j= 482
container[66].angle= 315
container[66].value= 255


container[67].bin= 27
container[67].i= 679
container[67].j= 487
container[67].angle= 135
container[67].value= 255


container[68].bin= 63
container[68].i= 680
container[68].j= 483
container[68].angle= 315
container[68].value= 255


container[69].bin= 27
container[69].i= 680
container[69].j= 488
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 681
container[70].j= 483
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 681
container[71].j= 488
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 682
container[72].j= 483
container[72].angle= 0
container[72].value= 255


container[73].bin= 27
container[73].i= 682
container[73].j= 489
container[73].angle= 135
container[73].value= 255


container[74].bin= 0
container[74].i= 683
container[74].j= 483
container[74].angle= 0
container[74].value= 255


container[75].bin= 27
container[75].i= 683
container[75].j= 490
container[75].angle= 135
container[75].value= 255


container[76].bin= 0
container[76].i= 684
container[76].j= 483
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 684
container[77].j= 490
container[77].angle= 180
container[77].value= 255


container[78].bin= 66
container[78].i= 685
container[78].j= 484
container[78].angle= 333
container[78].value= 255


container[79].bin= 36
container[79].i= 685
container[79].j= 490
container[79].angle= 180
container[79].value= 255


container[80].bin= 66
container[80].i= 686
container[80].j= 484
container[80].angle= 333
container[80].value= 255


container[81].bin= 36
container[81].i= 686
container[81].j= 490
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 687
container[82].j= 484
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 687
container[83].j= 490
container[83].angle= 180
container[83].value= 255


container[84].bin= 63
container[84].i= 688
container[84].j= 485
container[84].angle= 315
container[84].value= 255


container[85].bin= 54
container[85].i= 688
container[85].j= 486
container[85].angle= 270
container[85].value= 255


container[86].bin= 54
container[86].i= 688
container[86].j= 487
container[86].angle= 270
container[86].value= 255


container[87].bin= 54
container[87].i= 688
container[87].j= 488
container[87].angle= 270
container[87].value= 255


container[88].bin= 54
container[88].i= 688
container[88].j= 489
container[88].angle= 270
container[88].value= 255


container[89].bin= 44
container[89].i= 688
container[89].j= 490
container[89].angle= 224
container[89].value= 255


