container[0].bin= 8
container[0].i= 216
container[0].j= 22
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 216
container[1].j= 23
container[1].angle= 90
container[1].value= 255


container[2].bin= 23
container[2].i= 216
container[2].j= 24
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 216
container[3].j= 25
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 216
container[4].j= 26
container[4].angle= 90
container[4].value= 255


container[5].bin= 5
container[5].i= 217
container[5].j= 22
container[5].angle= 26
container[5].value= 255


container[6].bin= 23
container[6].i= 217
container[6].j= 27
container[6].angle= 116
container[6].value= 255


container[7].bin= 27
container[7].i= 217
container[7].j= 28
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 218
container[8].j= 21
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 218
container[9].j= 28
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 218
container[10].j= 29
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 219
container[11].j= 21
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 219
container[12].j= 29
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 220
container[13].j= 21
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 220
container[14].j= 30
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 221
container[15].j= 21
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 221
container[16].j= 30
container[16].angle= 135
container[16].value= 255


container[17].bin= 27
container[17].i= 221
container[17].j= 31
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 222
container[18].j= 21
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 222
container[19].j= 31
container[19].angle= 135
container[19].value= 255


container[20].bin= 27
container[20].i= 222
container[20].j= 32
container[20].angle= 135
container[20].value= 255


container[21].bin= 66
container[21].i= 223
container[21].j= 22
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 223
container[22].j= 32
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 224
container[23].j= 22
container[23].angle= 315
container[23].value= 255


container[24].bin= 63
container[24].i= 224
container[24].j= 23
container[24].angle= 315
container[24].value= 255


container[25].bin= 30
container[25].i= 224
container[25].j= 33
container[25].angle= 153
container[25].value= 255


container[26].bin= 63
container[26].i= 225
container[26].j= 23
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 225
container[27].j= 24
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 225
container[28].j= 33
container[28].angle= 153
container[28].value= 255


container[29].bin= 63
container[29].i= 226
container[29].j= 24
container[29].angle= 315
container[29].value= 255


container[30].bin= 59
container[30].i= 226
container[30].j= 25
container[30].angle= 296
container[30].value= 255


container[31].bin= 36
container[31].i= 226
container[31].j= 33
container[31].angle= 180
container[31].value= 255


container[32].bin= 59
container[32].i= 227
container[32].j= 26
container[32].angle= 296
container[32].value= 255


container[33].bin= 63
container[33].i= 227
container[33].j= 27
container[33].angle= 315
container[33].value= 255


container[34].bin= 30
container[34].i= 227
container[34].j= 34
container[34].angle= 153
container[34].value= 255


container[35].bin= 63
container[35].i= 228
container[35].j= 27
container[35].angle= 315
container[35].value= 255


container[36].bin= 63
container[36].i= 228
container[36].j= 28
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 228
container[37].j= 34
container[37].angle= 153
container[37].value= 255


container[38].bin= 66
container[38].i= 229
container[38].j= 28
container[38].angle= 333
container[38].value= 255


container[39].bin= 30
container[39].i= 229
container[39].j= 35
container[39].angle= 153
container[39].value= 255


container[40].bin= 66
container[40].i= 230
container[40].j= 29
container[40].angle= 333
container[40].value= 255


container[41].bin= 27
container[41].i= 230
container[41].j= 35
container[41].angle= 135
container[41].value= 255


container[42].bin= 27
container[42].i= 230
container[42].j= 36
container[42].angle= 135
container[42].value= 255


container[43].bin= 66
container[43].i= 231
container[43].j= 29
container[43].angle= 333
container[43].value= 255


container[44].bin= 30
container[44].i= 231
container[44].j= 36
container[44].angle= 153
container[44].value= 255


container[45].bin= 66
container[45].i= 232
container[45].j= 30
container[45].angle= 333
container[45].value= 255


container[46].bin= 36
container[46].i= 232
container[46].j= 36
container[46].angle= 180
container[46].value= 255


container[47].bin= 66
container[47].i= 233
container[47].j= 30
container[47].angle= 333
container[47].value= 255


container[48].bin= 30
container[48].i= 233
container[48].j= 37
container[48].angle= 153
container[48].value= 255


container[49].bin= 0
container[49].i= 234
container[49].j= 30
container[49].angle= 0
container[49].value= 255


container[50].bin= 30
container[50].i= 234
container[50].j= 37
container[50].angle= 153
container[50].value= 255


container[51].bin= 66
container[51].i= 235
container[51].j= 31
container[51].angle= 333
container[51].value= 255


container[52].bin= 36
container[52].i= 235
container[52].j= 37
container[52].angle= 180
container[52].value= 255


container[53].bin= 63
container[53].i= 236
container[53].j= 31
container[53].angle= 315
container[53].value= 255


container[54].bin= 63
container[54].i= 236
container[54].j= 32
container[54].angle= 315
container[54].value= 255


container[55].bin= 36
container[55].i= 236
container[55].j= 37
container[55].angle= 180
container[55].value= 255


container[56].bin= 63
container[56].i= 237
container[56].j= 32
container[56].angle= 315
container[56].value= 255


container[57].bin= 63
container[57].i= 237
container[57].j= 33
container[57].angle= 315
container[57].value= 255


container[58].bin= 36
container[58].i= 237
container[58].j= 37
container[58].angle= 180
container[58].value= 255


container[59].bin= 63
container[59].i= 238
container[59].j= 33
container[59].angle= 315
container[59].value= 255


container[60].bin= 59
container[60].i= 238
container[60].j= 34
container[60].angle= 296
container[60].value= 255


container[61].bin= 36
container[61].i= 238
container[61].j= 37
container[61].angle= 180
container[61].value= 255


container[62].bin= 59
container[62].i= 239
container[62].j= 35
container[62].angle= 296
container[62].value= 255


container[63].bin= 59
container[63].i= 239
container[63].j= 36
container[63].angle= 296
container[63].value= 255


container[64].bin= 44
container[64].i= 239
container[64].j= 37
container[64].angle= 224
container[64].value= 255


