container[0].bin= 18
container[0].i= 384
container[0].j= 165
container[0].angle= 90
container[0].value= 255


container[1].bin= 12
container[1].i= 384
container[1].j= 166
container[1].angle= 63
container[1].value= 255


container[2].bin= 21
container[2].i= 384
container[2].j= 167
container[2].angle= 108
container[2].value= 255


container[3].bin= 8
container[3].i= 385
container[3].j= 164
container[3].angle= 44
container[3].value= 255


container[4].bin= 0
container[4].i= 386
container[4].j= 163
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 386
container[5].j= 167
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 387
container[6].j= 164
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 387
container[7].j= 165
container[7].angle= 270
container[7].value= 255


container[8].bin= 54
container[8].i= 387
container[8].j= 166
container[8].angle= 270
container[8].value= 255


container[9].bin= 44
container[9].i= 387
container[9].j= 167
container[9].angle= 224
container[9].value= 255


