container[0].bin= 18
container[0].i= 391
container[0].j= 410
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 392
container[1].j= 409
container[1].angle= 0
container[1].value= 255


container[2].bin= 3
container[2].i= 393
container[2].j= 410
container[2].angle= 18
container[2].value= 255


container[3].bin= 5
container[3].i= 394
container[3].j= 410
container[3].angle= 26
container[3].value= 255


container[4].bin= 0
container[4].i= 395
container[4].j= 409
container[4].angle= 0
container[4].value= 255


container[5].bin= 8
container[5].i= 396
container[5].j= 409
container[5].angle= 44
container[5].value= 255


container[6].bin= 8
container[6].i= 397
container[6].j= 407
container[6].angle= 44
container[6].value= 255


container[7].bin= 12
container[7].i= 397
container[7].j= 408
container[7].angle= 63
container[7].value= 255


container[8].bin= 36
container[8].i= 397
container[8].j= 411
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 398
container[9].j= 407
container[9].angle= 26
container[9].value= 255


container[10].bin= 36
container[10].i= 398
container[10].j= 411
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 399
container[11].j= 407
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 399
container[12].j= 411
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 400
container[13].j= 407
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 400
container[14].j= 411
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 401
container[15].j= 407
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 401
container[16].j= 411
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 402
container[17].j= 407
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 402
container[18].j= 412
container[18].angle= 153
container[18].value= 255


container[19].bin= 68
container[19].i= 403
container[19].j= 407
container[19].angle= 341
container[19].value= 255


container[20].bin= 63
container[20].i= 403
container[20].j= 410
container[20].angle= 315
container[20].value= 255


container[21].bin= 36
container[21].i= 403
container[21].j= 412
container[21].angle= 180
container[21].value= 255


container[22].bin= 41
container[22].i= 404
container[22].j= 412
container[22].angle= 206
container[22].value= 255


container[23].bin= 0
container[23].i= 405
container[23].j= 410
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 405
container[24].j= 412
container[24].angle= 135
container[24].value= 255


container[25].bin= 21
container[25].i= 405
container[25].j= 413
container[25].angle= 108
container[25].value= 255


container[26].bin= 0
container[26].i= 406
container[26].j= 410
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 406
container[27].j= 412
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 407
container[28].j= 410
container[28].angle= 0
container[28].value= 255


container[29].bin= 44
container[29].i= 407
container[29].j= 412
container[29].angle= 224
container[29].value= 255


container[30].bin= 50
container[30].i= 407
container[30].j= 413
container[30].angle= 251
container[30].value= 255


container[31].bin= 63
container[31].i= 408
container[31].j= 410
container[31].angle= 315
container[31].value= 255


container[32].bin= 50
container[32].i= 408
container[32].j= 411
container[32].angle= 251
container[32].value= 255


