container[0].bin= 3
container[0].i= 71
container[0].j= 193
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 71
container[1].j= 194
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 71
container[2].j= 195
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 72
container[3].j= 193
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 72
container[4].j= 195
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 73
container[5].j= 193
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 73
container[6].j= 196
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 74
container[7].j= 194
container[7].angle= 333
container[7].value= 255


container[8].bin= 27
container[8].i= 74
container[8].j= 196
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 74
container[9].j= 197
container[9].angle= 135
container[9].value= 255


container[10].bin= 66
container[10].i= 75
container[10].j= 194
container[10].angle= 333
container[10].value= 255


container[11].bin= 30
container[11].i= 75
container[11].j= 197
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 76
container[12].j= 194
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 76
container[13].j= 198
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 77
container[14].j= 194
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 77
container[15].j= 198
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 77
container[16].j= 199
container[16].angle= 135
container[16].value= 255


container[17].bin= 66
container[17].i= 78
container[17].j= 195
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 78
container[18].j= 199
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 79
container[19].j= 195
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 79
container[20].j= 200
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 80
container[21].j= 196
container[21].angle= 333
container[21].value= 255


container[22].bin= 27
container[22].i= 80
container[22].j= 200
container[22].angle= 135
container[22].value= 255


container[23].bin= 27
container[23].i= 80
container[23].j= 201
container[23].angle= 135
container[23].value= 255


container[24].bin= 63
container[24].i= 81
container[24].j= 196
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 81
container[25].j= 197
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 81
container[26].j= 201
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 82
container[27].j= 197
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 82
container[28].j= 198
container[28].angle= 296
container[28].value= 255


container[29].bin= 36
container[29].i= 82
container[29].j= 201
container[29].angle= 180
container[29].value= 255


container[30].bin= 59
container[30].i= 83
container[30].j= 199
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 83
container[31].j= 200
container[31].angle= 315
container[31].value= 255


container[32].bin= 30
container[32].i= 83
container[32].j= 202
container[32].angle= 153
container[32].value= 255


container[33].bin= 63
container[33].i= 84
container[33].j= 200
container[33].angle= 315
container[33].value= 255


container[34].bin= 57
container[34].i= 84
container[34].j= 201
container[34].angle= 288
container[34].value= 255


