container[0].bin= 18
container[0].i= 2
container[0].j= 136
container[0].angle= 90
container[0].value= 255


container[1].bin= 21
container[1].i= 2
container[1].j= 137
container[1].angle= 108
container[1].value= 255


container[2].bin= 8
container[2].i= 3
container[2].j= 135
container[2].angle= 44
container[2].value= 255


container[3].bin= 0
container[3].i= 4
container[3].j= 134
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 4
container[4].j= 137
container[4].angle= 206
container[4].value= 255


container[5].bin= 63
container[5].i= 5
container[5].j= 135
container[5].angle= 315
container[5].value= 255


container[6].bin= 44
container[6].i= 5
container[6].j= 136
container[6].angle= 224
container[6].value= 255


