container[0].bin= 3
container[0].i= 306
container[0].j= 221
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 306
container[1].j= 222
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 306
container[2].j= 223
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 306
container[3].j= 224
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 306
container[4].j= 225
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 306
container[5].j= 226
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 306
container[6].j= 227
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 307
container[7].j= 221
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 307
container[8].j= 228
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 308
container[9].j= 221
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 308
container[10].j= 228
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 309
container[11].j= 221
container[11].angle= 0
container[11].value= 255


container[12].bin= 54
container[12].i= 309
container[12].j= 227
container[12].angle= 270
container[12].value= 255


container[13].bin= 44
container[13].i= 309
container[13].j= 228
container[13].angle= 224
container[13].value= 255


container[14].bin= 0
container[14].i= 310
container[14].j= 221
container[14].angle= 0
container[14].value= 255


container[15].bin= 44
container[15].i= 310
container[15].j= 226
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 311
container[16].j= 221
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 311
container[17].j= 225
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 312
container[18].j= 222
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 312
container[19].j= 223
container[19].angle= 270
container[19].value= 255


container[20].bin= 59
container[20].i= 313
container[20].j= 224
container[20].angle= 296
container[20].value= 255


