container[0].bin= 18
container[0].i= 389
container[0].j= 583
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 390
container[1].j= 582
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 390
container[2].j= 584
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 391
container[3].j= 582
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 391
container[4].j= 584
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 392
container[5].j= 582
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 392
container[6].j= 584
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 393
container[7].j= 582
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 393
container[8].j= 584
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 394
container[9].j= 582
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 394
container[10].j= 584
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 395
container[11].j= 582
container[11].angle= 0
container[11].value= 255


container[12].bin= 63
container[12].i= 396
container[12].j= 583
container[12].angle= 315
container[12].value= 255


container[13].bin= 27
container[13].i= 397
container[13].j= 586
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 398
container[14].j= 584
container[14].angle= 0
container[14].value= 255


container[15].bin= 63
container[15].i= 399
container[15].j= 585
container[15].angle= 315
container[15].value= 255


container[16].bin= 44
container[16].i= 399
container[16].j= 586
container[16].angle= 224
container[16].value= 255


