container[0].bin= 18
container[0].i= 387
container[0].j= 522
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 388
container[1].j= 521
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 388
container[2].j= 523
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 389
container[3].j= 521
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 389
container[4].j= 523
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 390
container[5].j= 521
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 390
container[6].j= 523
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 391
container[7].j= 521
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 391
container[8].j= 523
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 392
container[9].j= 521
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 392
container[10].j= 525
container[10].angle= 135
container[10].value= 255


container[11].bin= 68
container[11].i= 393
container[11].j= 521
container[11].angle= 341
container[11].value= 255


container[12].bin= 21
container[12].i= 393
container[12].j= 525
container[12].angle= 108
container[12].value= 255


container[13].bin= 18
container[13].i= 393
container[13].j= 526
container[13].angle= 90
container[13].value= 255


container[14].bin= 68
container[14].i= 394
container[14].j= 524
container[14].angle= 341
container[14].value= 255


container[15].bin= 8
container[15].i= 394
container[15].j= 525
container[15].angle= 44
container[15].value= 255


container[16].bin= 27
container[16].i= 394
container[16].j= 527
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 395
container[17].j= 524
container[17].angle= 0
container[17].value= 255


container[18].bin= 41
container[18].i= 395
container[18].j= 527
container[18].angle= 206
container[18].value= 255


container[19].bin= 0
container[19].i= 396
container[19].j= 524
container[19].angle= 0
container[19].value= 255


container[20].bin= 32
container[20].i= 396
container[20].j= 527
container[20].angle= 161
container[20].value= 255


container[21].bin= 18
container[21].i= 396
container[21].j= 529
container[21].angle= 90
container[21].value= 255


container[22].bin= 0
container[22].i= 397
container[22].j= 524
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 397
container[23].j= 530
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 398
container[24].j= 524
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 398
container[25].j= 530
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 399
container[26].j= 525
container[26].angle= 315
container[26].value= 255


container[27].bin= 30
container[27].i= 399
container[27].j= 531
container[27].angle= 153
container[27].value= 255


container[28].bin= 63
container[28].i= 400
container[28].j= 526
container[28].angle= 315
container[28].value= 255


container[29].bin= 30
container[29].i= 400
container[29].j= 531
container[29].angle= 153
container[29].value= 255


container[30].bin= 0
container[30].i= 401
container[30].j= 526
container[30].angle= 0
container[30].value= 255


container[31].bin= 32
container[31].i= 401
container[31].j= 531
container[31].angle= 161
container[31].value= 255


container[32].bin= 21
container[32].i= 401
container[32].j= 533
container[32].angle= 108
container[32].value= 255


container[33].bin= 63
container[33].i= 402
container[33].j= 527
container[33].angle= 315
container[33].value= 255


container[34].bin= 32
container[34].i= 402
container[34].j= 533
container[34].angle= 161
container[34].value= 255


container[35].bin= 63
container[35].i= 403
container[35].j= 528
container[35].angle= 315
container[35].value= 255


container[36].bin= 36
container[36].i= 403
container[36].j= 533
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 404
container[37].j= 528
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 404
container[38].j= 533
container[38].angle= 180
container[38].value= 255


container[39].bin= 66
container[39].i= 405
container[39].j= 529
container[39].angle= 333
container[39].value= 255


container[40].bin= 27
container[40].i= 405
container[40].j= 534
container[40].angle= 135
container[40].value= 255


container[41].bin= 66
container[41].i= 406
container[41].j= 529
container[41].angle= 333
container[41].value= 255


container[42].bin= 27
container[42].i= 406
container[42].j= 535
container[42].angle= 135
container[42].value= 255


container[43].bin= 0
container[43].i= 407
container[43].j= 529
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 407
container[44].j= 535
container[44].angle= 180
container[44].value= 255


container[45].bin= 66
container[45].i= 408
container[45].j= 530
container[45].angle= 333
container[45].value= 255


container[46].bin= 36
container[46].i= 408
container[46].j= 535
container[46].angle= 180
container[46].value= 255


container[47].bin= 66
container[47].i= 409
container[47].j= 530
container[47].angle= 333
container[47].value= 255


container[48].bin= 36
container[48].i= 409
container[48].j= 535
container[48].angle= 180
container[48].value= 255


container[49].bin= 3
container[49].i= 410
container[49].j= 530
container[49].angle= 18
container[49].value= 255


container[50].bin= 36
container[50].i= 410
container[50].j= 535
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 411
container[51].j= 529
container[51].angle= 0
container[51].value= 255


container[52].bin= 63
container[52].i= 411
container[52].j= 531
container[52].angle= 315
container[52].value= 255


container[53].bin= 44
container[53].i= 411
container[53].j= 535
container[53].angle= 224
container[53].value= 255


container[54].bin= 68
container[54].i= 412
container[54].j= 531
container[54].angle= 341
container[54].value= 255


container[55].bin= 44
container[55].i= 412
container[55].j= 534
container[55].angle= 224
container[55].value= 255


container[56].bin= 0
container[56].i= 413
container[56].j= 531
container[56].angle= 0
container[56].value= 255


container[57].bin= 41
container[57].i= 413
container[57].j= 533
container[57].angle= 206
container[57].value= 255


container[58].bin= 68
container[58].i= 414
container[58].j= 531
container[58].angle= 341
container[58].value= 255


container[59].bin= 44
container[59].i= 414
container[59].j= 533
container[59].angle= 224
container[59].value= 255


