container[0].bin= 18
container[0].i= 309
container[0].j= 359
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 310
container[1].j= 358
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 310
container[2].j= 360
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 311
container[3].j= 357
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 311
container[4].j= 360
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 312
container[5].j= 357
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 312
container[6].j= 360
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 313
container[7].j= 357
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 313
container[8].j= 360
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 314
container[9].j= 357
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 314
container[10].j= 360
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 315
container[11].j= 357
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 315
container[12].j= 360
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 316
container[13].j= 357
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 316
container[14].j= 360
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 317
container[15].j= 357
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 317
container[16].j= 360
container[16].angle= 180
container[16].value= 255


container[17].bin= 5
container[17].i= 318
container[17].j= 357
container[17].angle= 26
container[17].value= 255


container[18].bin= 36
container[18].i= 318
container[18].j= 360
container[18].angle= 180
container[18].value= 255


container[19].bin= 5
container[19].i= 319
container[19].j= 357
container[19].angle= 26
container[19].value= 255


container[20].bin= 36
container[20].i= 319
container[20].j= 360
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 320
container[21].j= 356
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 320
container[22].j= 360
container[22].angle= 180
container[22].value= 255


container[23].bin= 66
container[23].i= 321
container[23].j= 357
container[23].angle= 333
container[23].value= 255


container[24].bin= 36
container[24].i= 321
container[24].j= 360
container[24].angle= 180
container[24].value= 255


container[25].bin= 66
container[25].i= 322
container[25].j= 357
container[25].angle= 333
container[25].value= 255


container[26].bin= 36
container[26].i= 322
container[26].j= 360
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 323
container[27].j= 357
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 323
container[28].j= 360
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 324
container[29].j= 357
container[29].angle= 0
container[29].value= 255


container[30].bin= 44
container[30].i= 324
container[30].j= 360
container[30].angle= 224
container[30].value= 255


container[31].bin= 0
container[31].i= 325
container[31].j= 357
container[31].angle= 0
container[31].value= 255


container[32].bin= 44
container[32].i= 325
container[32].j= 359
container[32].angle= 224
container[32].value= 255


container[33].bin= 0
container[33].i= 326
container[33].j= 357
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 326
container[34].j= 359
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 327
container[35].j= 357
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 327
container[36].j= 359
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 328
container[37].j= 357
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 328
container[38].j= 359
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 329
container[39].j= 357
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 329
container[40].j= 359
container[40].angle= 180
container[40].value= 255


container[41].bin= 18
container[41].i= 330
container[41].j= 356
container[41].angle= 90
container[41].value= 255


container[42].bin= 8
container[42].i= 330
container[42].j= 357
container[42].angle= 44
container[42].value= 255


container[43].bin= 18
container[43].i= 330
container[43].j= 358
container[43].angle= 90
container[43].value= 255


container[44].bin= 27
container[44].i= 330
container[44].j= 359
container[44].angle= 135
container[44].value= 255


container[45].bin= 8
container[45].i= 331
container[45].j= 355
container[45].angle= 44
container[45].value= 255


container[46].bin= 27
container[46].i= 331
container[46].j= 360
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 332
container[47].j= 354
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 332
container[48].j= 360
container[48].angle= 180
container[48].value= 255


container[49].bin= 63
container[49].i= 333
container[49].j= 355
container[49].angle= 315
container[49].value= 255


container[50].bin= 41
container[50].i= 333
container[50].j= 360
container[50].angle= 206
container[50].value= 255


container[51].bin= 63
container[51].i= 334
container[51].j= 356
container[51].angle= 315
container[51].value= 255


container[52].bin= 36
container[52].i= 334
container[52].j= 360
container[52].angle= 180
container[52].value= 255


container[53].bin= 0
container[53].i= 335
container[53].j= 356
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 335
container[54].j= 360
container[54].angle= 180
container[54].value= 255


container[55].bin= 66
container[55].i= 336
container[55].j= 357
container[55].angle= 333
container[55].value= 255


container[56].bin= 54
container[56].i= 336
container[56].j= 358
container[56].angle= 270
container[56].value= 255


container[57].bin= 44
container[57].i= 336
container[57].j= 359
container[57].angle= 224
container[57].value= 255


container[58].bin= 44
container[58].i= 336
container[58].j= 360
container[58].angle= 224
container[58].value= 255


container[59].bin= 66
container[59].i= 337
container[59].j= 357
container[59].angle= 333
container[59].value= 255


container[60].bin= 41
container[60].i= 337
container[60].j= 359
container[60].angle= 206
container[60].value= 255


container[61].bin= 5
container[61].i= 338
container[61].j= 357
container[61].angle= 26
container[61].value= 255


container[62].bin= 36
container[62].i= 338
container[62].j= 359
container[62].angle= 180
container[62].value= 255


container[63].bin= 8
container[63].i= 339
container[63].j= 354
container[63].angle= 44
container[63].value= 255


container[64].bin= 18
container[64].i= 339
container[64].j= 355
container[64].angle= 90
container[64].value= 255


container[65].bin= 18
container[65].i= 339
container[65].j= 356
container[65].angle= 90
container[65].value= 255


container[66].bin= 8
container[66].i= 339
container[66].j= 357
container[66].angle= 44
container[66].value= 255


container[67].bin= 27
container[67].i= 339
container[67].j= 359
container[67].angle= 135
container[67].value= 255


container[68].bin= 5
container[68].i= 340
container[68].j= 354
container[68].angle= 26
container[68].value= 255


container[69].bin= 27
container[69].i= 340
container[69].j= 360
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 341
container[70].j= 353
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 341
container[71].j= 360
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 342
container[72].j= 353
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 342
container[73].j= 360
container[73].angle= 180
container[73].value= 255


container[74].bin= 0
container[74].i= 343
container[74].j= 353
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 343
container[75].j= 360
container[75].angle= 180
container[75].value= 255


container[76].bin= 0
container[76].i= 344
container[76].j= 353
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 344
container[77].j= 360
container[77].angle= 180
container[77].value= 255


container[78].bin= 63
container[78].i= 345
container[78].j= 354
container[78].angle= 315
container[78].value= 255


container[79].bin= 54
container[79].i= 345
container[79].j= 355
container[79].angle= 270
container[79].value= 255


container[80].bin= 30
container[80].i= 345
container[80].j= 361
container[80].angle= 153
container[80].value= 255


container[81].bin= 63
container[81].i= 346
container[81].j= 356
container[81].angle= 315
container[81].value= 255


container[82].bin= 27
container[82].i= 346
container[82].j= 361
container[82].angle= 135
container[82].value= 255


container[83].bin= 18
container[83].i= 346
container[83].j= 362
container[83].angle= 90
container[83].value= 255


container[84].bin= 21
container[84].i= 346
container[84].j= 363
container[84].angle= 108
container[84].value= 255


container[85].bin= 0
container[85].i= 347
container[85].j= 356
container[85].angle= 0
container[85].value= 255


container[86].bin= 32
container[86].i= 347
container[86].j= 363
container[86].angle= 161
container[86].value= 255


container[87].bin= 66
container[87].i= 348
container[87].j= 357
container[87].angle= 333
container[87].value= 255


container[88].bin= 30
container[88].i= 348
container[88].j= 364
container[88].angle= 153
container[88].value= 255


container[89].bin= 66
container[89].i= 349
container[89].j= 357
container[89].angle= 333
container[89].value= 255


container[90].bin= 30
container[90].i= 349
container[90].j= 364
container[90].angle= 153
container[90].value= 255


container[91].bin= 0
container[91].i= 350
container[91].j= 357
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 350
container[92].j= 364
container[92].angle= 180
container[92].value= 255


container[93].bin= 63
container[93].i= 351
container[93].j= 358
container[93].angle= 315
container[93].value= 255


container[94].bin= 41
container[94].i= 351
container[94].j= 364
container[94].angle= 206
container[94].value= 255


container[95].bin= 63
container[95].i= 352
container[95].j= 359
container[95].angle= 315
container[95].value= 255


container[96].bin= 41
container[96].i= 352
container[96].j= 364
container[96].angle= 206
container[96].value= 255


container[97].bin= 0
container[97].i= 353
container[97].j= 359
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 353
container[98].j= 363
container[98].angle= 180
container[98].value= 255


container[99].bin= 63
container[99].i= 354
container[99].j= 360
container[99].angle= 315
container[99].value= 255


container[100].bin= 36
container[100].i= 354
container[100].j= 363
container[100].angle= 180
container[100].value= 255


container[101].bin= 63
container[101].i= 355
container[101].j= 361
container[101].angle= 315
container[101].value= 255


container[102].bin= 0
container[102].i= 356
container[102].j= 361
container[102].angle= 0
container[102].value= 255


container[103].bin= 63
container[103].i= 357
container[103].j= 362
container[103].angle= 315
container[103].value= 255


container[104].bin= 44
container[104].i= 357
container[104].j= 363
container[104].angle= 224
container[104].value= 255


