container[0].bin= 18
container[0].i= 328
container[0].j= 435
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 329
container[1].j= 434
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 329
container[2].j= 436
container[2].angle= 161
container[2].value= 255


container[3].bin= 3
container[3].i= 330
container[3].j= 431
container[3].angle= 18
container[3].value= 255


container[4].bin= 14
container[4].i= 330
container[4].j= 432
container[4].angle= 71
container[4].value= 255


container[5].bin= 23
container[5].i= 330
container[5].j= 433
container[5].angle= 116
container[5].value= 255


container[6].bin= 8
container[6].i= 330
container[6].j= 434
container[6].angle= 44
container[6].value= 255


container[7].bin= 27
container[7].i= 330
container[7].j= 436
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 331
container[8].j= 431
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 331
container[9].j= 437
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 332
container[10].j= 431
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 332
container[11].j= 437
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 333
container[12].j= 432
container[12].angle= 315
container[12].value= 255


container[13].bin= 30
container[13].i= 333
container[13].j= 438
container[13].angle= 153
container[13].value= 255


container[14].bin= 63
container[14].i= 334
container[14].j= 433
container[14].angle= 315
container[14].value= 255


container[15].bin= 30
container[15].i= 334
container[15].j= 438
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 335
container[16].j= 433
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 335
container[17].j= 438
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 336
container[18].j= 434
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 336
container[19].j= 435
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 336
container[20].j= 436
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 336
container[21].j= 437
container[21].angle= 270
container[21].value= 255


container[22].bin= 44
container[22].i= 336
container[22].j= 438
container[22].angle= 224
container[22].value= 255


