container[0].bin= 18
container[0].i= 288
container[0].j= 621
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 288
container[1].j= 622
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 289
container[2].j= 620
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 289
container[3].j= 623
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 290
container[4].j= 619
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 290
container[5].j= 623
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 291
container[6].j= 620
container[6].angle= 315
container[6].value= 255


container[7].bin= 30
container[7].i= 291
container[7].j= 624
container[7].angle= 153
container[7].value= 255


container[8].bin= 63
container[8].i= 292
container[8].j= 621
container[8].angle= 315
container[8].value= 255


container[9].bin= 30
container[9].i= 292
container[9].j= 624
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 293
container[10].j= 621
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 293
container[11].j= 624
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 294
container[12].j= 622
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 294
container[13].j= 623
container[13].angle= 270
container[13].value= 255


container[14].bin= 44
container[14].i= 294
container[14].j= 624
container[14].angle= 224
container[14].value= 255


