container[0].bin= 14
container[0].i= 456
container[0].j= 422
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 456
container[1].j= 423
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 457
container[2].j= 422
container[2].angle= 18
container[2].value= 255


container[3].bin= 27
container[3].i= 457
container[3].j= 424
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 458
container[4].j= 422
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 458
container[5].j= 424
container[5].angle= 180
container[5].value= 255


container[6].bin= 8
container[6].i= 459
container[6].j= 421
container[6].angle= 44
container[6].value= 255


container[7].bin= 8
container[7].i= 459
container[7].j= 422
container[7].angle= 44
container[7].value= 255


container[8].bin= 36
container[8].i= 459
container[8].j= 424
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 460
container[9].j= 421
container[9].angle= 26
container[9].value= 255


container[10].bin= 36
container[10].i= 460
container[10].j= 424
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 461
container[11].j= 420
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 461
container[12].j= 424
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 462
container[13].j= 421
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 462
container[14].j= 422
container[14].angle= 270
container[14].value= 255


container[15].bin= 30
container[15].i= 462
container[15].j= 425
container[15].angle= 153
container[15].value= 255


container[16].bin= 63
container[16].i= 463
container[16].j= 423
container[16].angle= 315
container[16].value= 255


container[17].bin= 30
container[17].i= 463
container[17].j= 425
container[17].angle= 153
container[17].value= 255


container[18].bin= 0
container[18].i= 464
container[18].j= 423
container[18].angle= 0
container[18].value= 255


container[19].bin= 41
container[19].i= 464
container[19].j= 425
container[19].angle= 206
container[19].value= 255


container[20].bin= 68
container[20].i= 465
container[20].j= 423
container[20].angle= 341
container[20].value= 255


container[21].bin= 44
container[21].i= 465
container[21].j= 425
container[21].angle= 224
container[21].value= 255


