container[0].bin= 18
container[0].i= 667
container[0].j= 252
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 667
container[1].j= 253
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 667
container[2].j= 254
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 668
container[3].j= 251
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 668
container[4].j= 255
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 669
container[5].j= 250
container[5].angle= 0
container[5].value= 255


container[6].bin= 41
container[6].i= 669
container[6].j= 255
container[6].angle= 206
container[6].value= 255


container[7].bin= 66
container[7].i= 670
container[7].j= 251
container[7].angle= 333
container[7].value= 255


container[8].bin= 32
container[8].i= 670
container[8].j= 255
container[8].angle= 161
container[8].value= 255


container[9].bin= 66
container[9].i= 671
container[9].j= 251
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 671
container[10].j= 257
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 672
container[11].j= 251
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 672
container[12].j= 257
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 673
container[13].j= 252
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 673
container[14].j= 253
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 673
container[15].j= 254
container[15].angle= 270
container[15].value= 255


container[16].bin= 54
container[16].i= 673
container[16].j= 255
container[16].angle= 270
container[16].value= 255


container[17].bin= 27
container[17].i= 673
container[17].j= 258
container[17].angle= 135
container[17].value= 255


container[18].bin= 18
container[18].i= 673
container[18].j= 259
container[18].angle= 90
container[18].value= 255


container[19].bin= 63
container[19].i= 674
container[19].j= 256
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 674
container[20].j= 260
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 675
container[21].j= 256
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 675
container[22].j= 260
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 676
container[23].j= 256
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 676
container[24].j= 260
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 677
container[25].j= 256
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 677
container[26].j= 260
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 678
container[27].j= 256
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 678
container[28].j= 260
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 679
container[29].j= 257
container[29].angle= 315
container[29].value= 255


container[30].bin= 54
container[30].i= 679
container[30].j= 258
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 679
container[31].j= 259
container[31].angle= 270
container[31].value= 255


container[32].bin= 44
container[32].i= 679
container[32].j= 260
container[32].angle= 224
container[32].value= 255


