container[0].bin= 14
container[0].i= 836
container[0].j= 415
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 836
container[1].j= 416
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 837
container[2].j= 415
container[2].angle= 18
container[2].value= 255


container[3].bin= 66
container[3].i= 838
container[3].j= 415
container[3].angle= 333
container[3].value= 255


container[4].bin= 36
container[4].i= 838
container[4].j= 417
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 839
container[5].j= 415
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 839
container[6].j= 417
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 840
container[7].j= 415
container[7].angle= 26
container[7].value= 255


container[8].bin= 30
container[8].i= 840
container[8].j= 417
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 841
container[9].j= 414
container[9].angle= 0
container[9].value= 255


container[10].bin= 41
container[10].i= 841
container[10].j= 417
container[10].angle= 206
container[10].value= 255


container[11].bin= 63
container[11].i= 842
container[11].j= 415
container[11].angle= 315
container[11].value= 255


container[12].bin= 48
container[12].i= 842
container[12].j= 416
container[12].angle= 243
container[12].value= 255


container[13].bin= 44
container[13].i= 842
container[13].j= 417
container[13].angle= 224
container[13].value= 255


