container[0].bin= 14
container[0].i= 255
container[0].j= 503
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 255
container[1].j= 504
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 256
container[2].j= 503
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 257
container[3].j= 503
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 257
container[4].j= 505
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 258
container[5].j= 503
container[5].angle= 341
container[5].value= 255


