container[0].bin= 8
container[0].i= 190
container[0].j= 160
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 190
container[1].j= 161
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 190
container[2].j= 162
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 191
container[3].j= 160
container[3].angle= 26
container[3].value= 255


container[4].bin= 27
container[4].i= 191
container[4].j= 162
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 191
container[5].j= 163
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 192
container[6].j= 159
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 192
container[7].j= 163
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 193
container[8].j= 159
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 193
container[9].j= 164
container[9].angle= 153
container[9].value= 255


container[10].bin= 66
container[10].i= 194
container[10].j= 160
container[10].angle= 333
container[10].value= 255


container[11].bin= 30
container[11].i= 194
container[11].j= 164
container[11].angle= 153
container[11].value= 255


container[12].bin= 66
container[12].i= 195
container[12].j= 160
container[12].angle= 333
container[12].value= 255


container[13].bin= 30
container[13].i= 195
container[13].j= 165
container[13].angle= 153
container[13].value= 255


container[14].bin= 63
container[14].i= 196
container[14].j= 161
container[14].angle= 315
container[14].value= 255


container[15].bin= 30
container[15].i= 196
container[15].j= 165
container[15].angle= 153
container[15].value= 255


container[16].bin= 59
container[16].i= 197
container[16].j= 162
container[16].angle= 296
container[16].value= 255


container[17].bin= 59
container[17].i= 197
container[17].j= 163
container[17].angle= 296
container[17].value= 255


container[18].bin= 54
container[18].i= 197
container[18].j= 164
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 197
container[19].j= 165
container[19].angle= 224
container[19].value= 255


