container[0].bin= 18
container[0].i= 177
container[0].j= 260
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 178
container[1].j= 259
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 178
container[2].j= 261
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 179
container[3].j= 259
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 179
container[4].j= 261
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 180
container[5].j= 259
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 180
container[6].j= 261
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 181
container[7].j= 259
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 181
container[8].j= 262
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 182
container[9].j= 259
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 182
container[10].j= 262
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 183
container[11].j= 260
container[11].angle= 315
container[11].value= 255


container[12].bin= 63
container[12].i= 184
container[12].j= 261
container[12].angle= 315
container[12].value= 255


container[13].bin= 36
container[13].i= 184
container[13].j= 263
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 185
container[14].j= 261
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 185
container[15].j= 263
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 186
container[16].j= 261
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 186
container[17].j= 263
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 187
container[18].j= 261
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 187
container[19].j= 263
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 188
container[20].j= 261
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 188
container[21].j= 263
container[21].angle= 180
container[21].value= 255


container[22].bin= 68
container[22].i= 189
container[22].j= 261
container[22].angle= 341
container[22].value= 255


container[23].bin= 54
container[23].i= 189
container[23].j= 262
container[23].angle= 270
container[23].value= 255


container[24].bin= 39
container[24].i= 189
container[24].j= 263
container[24].angle= 198
container[24].value= 255


