container[0].bin= 18
container[0].i= 486
container[0].j= 429
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 487
container[1].j= 428
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 487
container[2].j= 430
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 488
container[3].j= 428
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 488
container[4].j= 430
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 489
container[5].j= 428
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 489
container[6].j= 430
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 490
container[7].j= 428
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 490
container[8].j= 430
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 491
container[9].j= 428
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 491
container[10].j= 430
container[10].angle= 180
container[10].value= 255


container[11].bin= 68
container[11].i= 492
container[11].j= 428
container[11].angle= 341
container[11].value= 255


container[12].bin= 54
container[12].i= 492
container[12].j= 429
container[12].angle= 270
container[12].value= 255


container[13].bin= 39
container[13].i= 492
container[13].j= 430
container[13].angle= 198
container[13].value= 255


