container[0].bin= 18
container[0].i= 480
container[0].j= 228
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 481
container[1].j= 227
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 481
container[2].j= 229
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 482
container[3].j= 227
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 482
container[4].j= 229
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 483
container[5].j= 227
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 483
container[6].j= 229
container[6].angle= 180
container[6].value= 255


container[7].bin= 68
container[7].i= 484
container[7].j= 227
container[7].angle= 341
container[7].value= 255


container[8].bin= 54
container[8].i= 484
container[8].j= 228
container[8].angle= 270
container[8].value= 255


container[9].bin= 39
container[9].i= 484
container[9].j= 229
container[9].angle= 198
container[9].value= 255


