container[0].bin= 18
container[0].i= 348
container[0].j= 306
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 349
container[1].j= 305
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 349
container[2].j= 307
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 350
container[3].j= 304
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 350
container[4].j= 307
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 351
container[5].j= 305
container[5].angle= 315
container[5].value= 255


container[6].bin= 63
container[6].i= 352
container[6].j= 306
container[6].angle= 315
container[6].value= 255


container[7].bin= 36
container[7].i= 352
container[7].j= 308
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 353
container[8].j= 306
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 353
container[9].j= 308
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 354
container[10].j= 306
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 354
container[11].j= 308
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 355
container[12].j= 306
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 355
container[13].j= 308
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 356
container[14].j= 306
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 356
container[15].j= 308
container[15].angle= 180
container[15].value= 255


container[16].bin= 8
container[16].i= 357
container[16].j= 306
container[16].angle= 44
container[16].value= 255


container[17].bin= 36
container[17].i= 357
container[17].j= 308
container[17].angle= 180
container[17].value= 255


container[18].bin= 8
container[18].i= 358
container[18].j= 305
container[18].angle= 44
container[18].value= 255


container[19].bin= 0
container[19].i= 359
container[19].j= 304
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 359
container[20].j= 307
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 360
container[21].j= 304
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 360
container[22].j= 307
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 361
container[23].j= 304
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 361
container[24].j= 307
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 362
container[25].j= 304
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 362
container[26].j= 307
container[26].angle= 180
container[26].value= 255


container[27].bin= 5
container[27].i= 363
container[27].j= 304
container[27].angle= 26
container[27].value= 255


container[28].bin= 30
container[28].i= 363
container[28].j= 308
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 364
container[29].j= 304
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 364
container[30].j= 308
container[30].angle= 153
container[30].value= 255


container[31].bin= 66
container[31].i= 365
container[31].j= 304
container[31].angle= 333
container[31].value= 255


container[32].bin= 36
container[32].i= 365
container[32].j= 308
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 366
container[33].j= 304
container[33].angle= 0
container[33].value= 255


container[34].bin= 27
container[34].i= 366
container[34].j= 309
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 367
container[35].j= 304
container[35].angle= 0
container[35].value= 255


container[36].bin= 27
container[36].i= 367
container[36].j= 310
container[36].angle= 135
container[36].value= 255


container[37].bin= 0
container[37].i= 368
container[37].j= 304
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 368
container[38].j= 310
container[38].angle= 180
container[38].value= 255


container[39].bin= 63
container[39].i= 369
container[39].j= 305
container[39].angle= 315
container[39].value= 255


container[40].bin= 44
container[40].i= 369
container[40].j= 310
container[40].angle= 224
container[40].value= 255


container[41].bin= 63
container[41].i= 370
container[41].j= 306
container[41].angle= 315
container[41].value= 255


container[42].bin= 44
container[42].i= 370
container[42].j= 309
container[42].angle= 224
container[42].value= 255


container[43].bin= 0
container[43].i= 371
container[43].j= 306
container[43].angle= 0
container[43].value= 255


container[44].bin= 0
container[44].i= 372
container[44].j= 306
container[44].angle= 0
container[44].value= 255


container[45].bin= 0
container[45].i= 373
container[45].j= 306
container[45].angle= 0
container[45].value= 255


container[46].bin= 66
container[46].i= 374
container[46].j= 307
container[46].angle= 333
container[46].value= 255


container[47].bin= 63
container[47].i= 375
container[47].j= 307
container[47].angle= 315
container[47].value= 255


