container[0].bin= 18
container[0].i= 279
container[0].j= 156
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 280
container[1].j= 155
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 280
container[2].j= 157
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 281
container[3].j= 155
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 281
container[4].j= 157
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 282
container[5].j= 155
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 282
container[6].j= 157
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 283
container[7].j= 155
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 283
container[8].j= 157
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 284
container[9].j= 155
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 284
container[10].j= 157
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 285
container[11].j= 155
container[11].angle= 0
container[11].value= 255


container[12].bin= 32
container[12].i= 285
container[12].j= 157
container[12].angle= 161
container[12].value= 255


container[13].bin= 14
container[13].i= 285
container[13].j= 158
container[13].angle= 71
container[13].value= 255


container[14].bin= 21
container[14].i= 285
container[14].j= 159
container[14].angle= 108
container[14].value= 255


container[15].bin= 0
container[15].i= 286
container[15].j= 155
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 286
container[16].j= 159
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 287
container[17].j= 155
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 287
container[18].j= 160
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 288
container[19].j= 155
container[19].angle= 44
container[19].value= 255


container[20].bin= 44
container[20].i= 288
container[20].j= 159
container[20].angle= 224
container[20].value= 255


container[21].bin= 8
container[21].i= 289
container[21].j= 154
container[21].angle= 44
container[21].value= 255


container[22].bin= 0
container[22].i= 290
container[22].j= 153
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 290
container[23].j= 156
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 291
container[24].j= 154
container[24].angle= 315
container[24].value= 255


container[25].bin= 54
container[25].i= 291
container[25].j= 155
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 291
container[26].j= 156
container[26].angle= 224
container[26].value= 255


