container[0].bin= 8
container[0].i= 52
container[0].j= 252
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 52
container[1].j= 253
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 52
container[2].j= 254
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 53
container[3].j= 251
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 53
container[4].j= 254
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 54
container[5].j= 251
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 54
container[6].j= 254
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 55
container[7].j= 251
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 55
container[8].j= 254
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 56
container[9].j= 251
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 56
container[10].j= 254
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 57
container[11].j= 251
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 57
container[12].j= 254
container[12].angle= 180
container[12].value= 255


container[13].bin= 5
container[13].i= 58
container[13].j= 251
container[13].angle= 26
container[13].value= 255


container[14].bin= 41
container[14].i= 58
container[14].j= 254
container[14].angle= 206
container[14].value= 255


container[15].bin= 5
container[15].i= 59
container[15].j= 251
container[15].angle= 26
container[15].value= 255


container[16].bin= 41
container[16].i= 59
container[16].j= 254
container[16].angle= 206
container[16].value= 255


container[17].bin= 66
container[17].i= 60
container[17].j= 251
container[17].angle= 333
container[17].value= 255


container[18].bin= 41
container[18].i= 60
container[18].j= 253
container[18].angle= 206
container[18].value= 255


container[19].bin= 63
container[19].i= 61
container[19].j= 251
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 61
container[20].j= 252
container[20].angle= 270
container[20].value= 255


container[21].bin= 44
container[21].i= 61
container[21].j= 253
container[21].angle= 224
container[21].value= 255


