container[0].bin= 14
container[0].i= 459
container[0].j= 516
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 459
container[1].j= 517
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 459
container[2].j= 518
container[2].angle= 90
container[2].value= 255


container[3].bin= 3
container[3].i= 460
container[3].j= 515
container[3].angle= 18
container[3].value= 255


container[4].bin= 8
container[4].i= 460
container[4].j= 516
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 460
container[5].j= 519
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 461
container[6].j= 515
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 461
container[7].j= 519
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 462
container[8].j= 515
container[8].angle= 0
container[8].value= 255


container[9].bin= 44
container[9].i= 462
container[9].j= 519
container[9].angle= 224
container[9].value= 255


container[10].bin= 0
container[10].i= 463
container[10].j= 515
container[10].angle= 0
container[10].value= 255


container[11].bin= 44
container[11].i= 463
container[11].j= 518
container[11].angle= 224
container[11].value= 255


container[12].bin= 0
container[12].i= 464
container[12].j= 515
container[12].angle= 0
container[12].value= 255


container[13].bin= 0
container[13].i= 465
container[13].j= 515
container[13].angle= 0
container[13].value= 255


container[14].bin= 0
container[14].i= 466
container[14].j= 515
container[14].angle= 0
container[14].value= 255


container[15].bin= 66
container[15].i= 467
container[15].j= 516
container[15].angle= 333
container[15].value= 255


container[16].bin= 63
container[16].i= 468
container[16].j= 516
container[16].angle= 315
container[16].value= 255


