container[0].bin= 18
container[0].i= 384
container[0].j= 181
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 385
container[1].j= 180
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 385
container[2].j= 182
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 385
container[3].j= 183
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 386
container[4].j= 179
container[4].angle= 0
container[4].value= 255


container[5].bin= 32
container[5].i= 386
container[5].j= 183
container[5].angle= 161
container[5].value= 255


container[6].bin= 63
container[6].i= 387
container[6].j= 180
container[6].angle= 315
container[6].value= 255


container[7].bin= 48
container[7].i= 387
container[7].j= 181
container[7].angle= 243
container[7].value= 255


container[8].bin= 54
container[8].i= 387
container[8].j= 182
container[8].angle= 270
container[8].value= 255


