container[0].bin= 8
container[0].i= 581
container[0].j= 156
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 581
container[1].j= 157
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 582
container[2].j= 155
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 583
container[3].j= 155
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 584
container[4].j= 155
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 585
container[5].j= 155
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 586
container[6].j= 156
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 586
container[7].j= 157
container[7].angle= 224
container[7].value= 255


