container[0].bin= 14
container[0].i= 202
container[0].j= 441
container[0].angle= 71
container[0].value= 255


container[1].bin= 12
container[1].i= 202
container[1].j= 442
container[1].angle= 63
container[1].value= 255


container[2].bin= 21
container[2].i= 202
container[2].j= 443
container[2].angle= 108
container[2].value= 255


container[3].bin= 3
container[3].i= 203
container[3].j= 441
container[3].angle= 18
container[3].value= 255


container[4].bin= 66
container[4].i= 204
container[4].j= 441
container[4].angle= 333
container[4].value= 255


container[5].bin= 27
container[5].i= 204
container[5].j= 444
container[5].angle= 135
container[5].value= 255


container[6].bin= 18
container[6].i= 204
container[6].j= 445
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 205
container[7].j= 441
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 205
container[8].j= 446
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 206
container[9].j= 441
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 206
container[10].j= 446
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 207
container[11].j= 442
container[11].angle= 333
container[11].value= 255


container[12].bin= 41
container[12].i= 207
container[12].j= 446
container[12].angle= 206
container[12].value= 255


container[13].bin= 63
container[13].i= 208
container[13].j= 442
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 208
container[14].j= 443
container[14].angle= 315
container[14].value= 255


container[15].bin= 41
container[15].i= 208
container[15].j= 446
container[15].angle= 206
container[15].value= 255


container[16].bin= 66
container[16].i= 209
container[16].j= 443
container[16].angle= 333
container[16].value= 255


container[17].bin= 63
container[17].i= 210
container[17].j= 444
container[17].angle= 315
container[17].value= 255


container[18].bin= 44
container[18].i= 210
container[18].j= 445
container[18].angle= 224
container[18].value= 255


