container[0].bin= 27
container[0].i= 100
container[0].j= 220
container[0].angle= 135
container[0].value= 255


container[1].bin= 0
container[1].i= 101
container[1].j= 218
container[1].angle= 0
container[1].value= 255


container[2].bin= 0
container[2].i= 102
container[2].j= 218
container[2].angle= 0
container[2].value= 255


container[3].bin= 32
container[3].i= 102
container[3].j= 220
container[3].angle= 161
container[3].value= 255


container[4].bin= 0
container[4].i= 103
container[4].j= 218
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 103
container[5].j= 222
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 104
container[6].j= 218
container[6].angle= 0
container[6].value= 255


container[7].bin= 41
container[7].i= 104
container[7].j= 222
container[7].angle= 206
container[7].value= 255


container[8].bin= 63
container[8].i= 105
container[8].j= 219
container[8].angle= 315
container[8].value= 255


container[9].bin= 54
container[9].i= 105
container[9].j= 220
container[9].angle= 270
container[9].value= 255


container[10].bin= 48
container[10].i= 105
container[10].j= 221
container[10].angle= 243
container[10].value= 255


container[11].bin= 44
container[11].i= 105
container[11].j= 222
container[11].angle= 224
container[11].value= 255


