container[0].bin= 8
container[0].i= 244
container[0].j= 323
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 244
container[1].j= 324
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 245
container[2].j= 322
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 246
container[3].j= 322
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 247
container[4].j= 322
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 248
container[5].j= 322
container[5].angle= 0
container[5].value= 255


container[6].bin= 8
container[6].i= 249
container[6].j= 322
container[6].angle= 44
container[6].value= 255


container[7].bin= 41
container[7].i= 249
container[7].j= 324
container[7].angle= 206
container[7].value= 255


container[8].bin= 8
container[8].i= 250
container[8].j= 321
container[8].angle= 44
container[8].value= 255


container[9].bin= 41
container[9].i= 250
container[9].j= 324
container[9].angle= 206
container[9].value= 255


container[10].bin= 0
container[10].i= 251
container[10].j= 320
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 251
container[11].j= 323
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 252
container[12].j= 321
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 252
container[13].j= 322
container[13].angle= 270
container[13].value= 255


container[14].bin= 44
container[14].i= 252
container[14].j= 323
container[14].angle= 224
container[14].value= 255


