container[0].bin= 8
container[0].i= 292
container[0].j= 235
container[0].angle= 44
container[0].value= 255


container[1].bin= 66
container[1].i= 294
container[1].j= 235
container[1].angle= 333
container[1].value= 255


container[2].bin= 27
container[2].i= 294
container[2].j= 237
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 295
container[3].j= 235
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 295
container[4].j= 238
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 296
container[5].j= 235
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 296
container[6].j= 238
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 297
container[7].j= 236
container[7].angle= 315
container[7].value= 255


container[8].bin= 54
container[8].i= 297
container[8].j= 237
container[8].angle= 270
container[8].value= 255


container[9].bin= 44
container[9].i= 297
container[9].j= 238
container[9].angle= 224
container[9].value= 255


