container[0].bin= 8
container[0].i= 157
container[0].j= 323
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 157
container[1].j= 324
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 158
container[2].j= 322
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 159
container[3].j= 322
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 160
container[4].j= 322
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 161
container[5].j= 322
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 162
container[6].j= 322
container[6].angle= 0
container[6].value= 255


container[7].bin= 41
container[7].i= 162
container[7].j= 324
container[7].angle= 206
container[7].value= 255


container[8].bin= 0
container[8].i= 163
container[8].j= 322
container[8].angle= 0
container[8].value= 255


container[9].bin= 41
container[9].i= 163
container[9].j= 324
container[9].angle= 206
container[9].value= 255


container[10].bin= 68
container[10].i= 164
container[10].j= 322
container[10].angle= 341
container[10].value= 255


container[11].bin= 39
container[11].i= 164
container[11].j= 324
container[11].angle= 198
container[11].value= 255


