container[0].bin= 8
container[0].i= 855
container[0].j= 415
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 855
container[1].j= 416
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 855
container[2].j= 417
container[2].angle= 135
container[2].value= 255


container[3].bin= 68
container[3].i= 856
container[3].j= 415
container[3].angle= 341
container[3].value= 255


container[4].bin= 32
container[4].i= 856
container[4].j= 417
container[4].angle= 161
container[4].value= 255


container[5].bin= 0
container[5].i= 857
container[5].j= 414
container[5].angle= 0
container[5].value= 255


container[6].bin= 44
container[6].i= 857
container[6].j= 417
container[6].angle= 224
container[6].value= 255


container[7].bin= 8
container[7].i= 858
container[7].j= 415
container[7].angle= 44
container[7].value= 255


container[8].bin= 0
container[8].i= 859
container[8].j= 414
container[8].angle= 0
container[8].value= 255


container[9].bin= 66
container[9].i= 860
container[9].j= 415
container[9].angle= 333
container[9].value= 255


container[10].bin= 66
container[10].i= 861
container[10].j= 415
container[10].angle= 333
container[10].value= 255


container[11].bin= 36
container[11].i= 861
container[11].j= 417
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 862
container[12].j= 415
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 862
container[13].j= 417
container[13].angle= 180
container[13].value= 255


container[14].bin= 68
container[14].i= 863
container[14].j= 415
container[14].angle= 341
container[14].value= 255


container[15].bin= 54
container[15].i= 863
container[15].j= 416
container[15].angle= 270
container[15].value= 255


container[16].bin= 39
container[16].i= 863
container[16].j= 417
container[16].angle= 198
container[16].value= 255


