container[0].bin= 8
container[0].i= 360
container[0].j= 431
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 360
container[1].j= 432
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 361
container[2].j= 431
container[2].angle= 26
container[2].value= 255


container[3].bin= 0
container[3].i= 362
container[3].j= 430
container[3].angle= 0
container[3].value= 255


container[4].bin= 63
container[4].i= 363
container[4].j= 431
container[4].angle= 315
container[4].value= 255


container[5].bin= 44
container[5].i= 363
container[5].j= 432
container[5].angle= 224
container[5].value= 255


