container[0].bin= 18
container[0].i= 183
container[0].j= 249
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 184
container[1].j= 248
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 184
container[2].j= 250
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 185
container[3].j= 248
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 185
container[4].j= 250
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 186
container[5].j= 248
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 186
container[6].j= 250
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 186
container[7].j= 251
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 187
container[8].j= 248
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 187
container[9].j= 252
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 188
container[10].j= 248
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 188
container[11].j= 252
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 189
container[12].j= 248
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 189
container[13].j= 252
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 190
container[14].j= 248
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 190
container[15].j= 252
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 191
container[16].j= 248
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 191
container[17].j= 252
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 192
container[18].j= 249
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 192
container[19].j= 250
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 192
container[20].j= 251
container[20].angle= 270
container[20].value= 255


container[21].bin= 44
container[21].i= 192
container[21].j= 252
container[21].angle= 224
container[21].value= 255


