container[0].bin= 18
container[0].i= 561
container[0].j= 234
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 561
container[1].j= 235
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 561
container[2].j= 236
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 561
container[3].j= 237
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 562
container[4].j= 233
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 562
container[5].j= 238
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 563
container[6].j= 232
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 563
container[7].j= 239
container[7].angle= 153
container[7].value= 255


container[8].bin= 63
container[8].i= 564
container[8].j= 233
container[8].angle= 315
container[8].value= 255


container[9].bin= 30
container[9].i= 564
container[9].j= 239
container[9].angle= 153
container[9].value= 255


container[10].bin= 63
container[10].i= 565
container[10].j= 234
container[10].angle= 315
container[10].value= 255


container[11].bin= 36
container[11].i= 565
container[11].j= 239
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 566
container[12].j= 234
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 566
container[13].j= 239
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 567
container[14].j= 235
container[14].angle= 333
container[14].value= 255


container[15].bin= 36
container[15].i= 567
container[15].j= 239
container[15].angle= 180
container[15].value= 255


container[16].bin= 66
container[16].i= 568
container[16].j= 235
container[16].angle= 333
container[16].value= 255


container[17].bin= 41
container[17].i= 568
container[17].j= 239
container[17].angle= 206
container[17].value= 255


container[18].bin= 0
container[18].i= 569
container[18].j= 235
container[18].angle= 0
container[18].value= 255


container[19].bin= 41
container[19].i= 569
container[19].j= 239
container[19].angle= 206
container[19].value= 255


container[20].bin= 63
container[20].i= 570
container[20].j= 236
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 570
container[21].j= 237
container[21].angle= 270
container[21].value= 255


container[22].bin= 44
container[22].i= 570
container[22].j= 238
container[22].angle= 224
container[22].value= 255


