container[0].bin= 8
container[0].i= 382
container[0].j= 477
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 382
container[1].j= 478
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 383
container[2].j= 476
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 384
container[3].j= 476
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 385
container[4].j= 476
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 386
container[5].j= 476
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 387
container[6].j= 476
container[6].angle= 0
container[6].value= 255


container[7].bin= 41
container[7].i= 387
container[7].j= 478
container[7].angle= 206
container[7].value= 255


container[8].bin= 0
container[8].i= 388
container[8].j= 476
container[8].angle= 0
container[8].value= 255


container[9].bin= 41
container[9].i= 388
container[9].j= 478
container[9].angle= 206
container[9].value= 255


container[10].bin= 0
container[10].i= 389
container[10].j= 476
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 389
container[11].j= 478
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 390
container[12].j= 476
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 390
container[13].j= 478
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 391
container[14].j= 476
container[14].angle= 0
container[14].value= 255


container[15].bin= 30
container[15].i= 391
container[15].j= 478
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 392
container[16].j= 476
container[16].angle= 0
container[16].value= 255


container[17].bin= 63
container[17].i= 393
container[17].j= 477
container[17].angle= 315
container[17].value= 255


container[18].bin= 44
container[18].i= 393
container[18].j= 478
container[18].angle= 224
container[18].value= 255


