container[0].bin= 8
container[0].i= 70
container[0].j= 220
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 70
container[1].j= 221
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 70
container[2].j= 222
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 71
container[3].j= 219
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 71
container[4].j= 222
container[4].angle= 153
container[4].value= 255


container[5].bin= 63
container[5].i= 72
container[5].j= 220
container[5].angle= 315
container[5].value= 255


container[6].bin= 30
container[6].i= 72
container[6].j= 223
container[6].angle= 153
container[6].value= 255


container[7].bin= 63
container[7].i= 73
container[7].j= 221
container[7].angle= 315
container[7].value= 255


container[8].bin= 30
container[8].i= 73
container[8].j= 223
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 74
container[9].j= 221
container[9].angle= 0
container[9].value= 255


container[10].bin= 14
container[10].i= 75
container[10].j= 220
container[10].angle= 71
container[10].value= 255


container[11].bin= 8
container[11].i= 75
container[11].j= 221
container[11].angle= 44
container[11].value= 255


container[12].bin= 0
container[12].i= 76
container[12].j= 219
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 76
container[13].j= 223
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 77
container[14].j= 219
container[14].angle= 0
container[14].value= 255


container[15].bin= 3
container[15].i= 78
container[15].j= 219
container[15].angle= 18
container[15].value= 255


container[16].bin= 14
container[16].i= 78
container[16].j= 220
container[16].angle= 71
container[16].value= 255


container[17].bin= 41
container[17].i= 78
container[17].j= 223
container[17].angle= 206
container[17].value= 255


container[18].bin= 0
container[18].i= 79
container[18].j= 219
container[18].angle= 0
container[18].value= 255


container[19].bin= 41
container[19].i= 79
container[19].j= 223
container[19].angle= 206
container[19].value= 255


container[20].bin= 0
container[20].i= 80
container[20].j= 219
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 80
container[21].j= 222
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 81
container[22].j= 220
container[22].angle= 315
container[22].value= 255


container[23].bin= 57
container[23].i= 81
container[23].j= 221
container[23].angle= 288
container[23].value= 255


container[24].bin= 0
container[24].i= 82
container[24].j= 219
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 82
container[25].j= 223
container[25].angle= 180
container[25].value= 255


container[26].bin= 3
container[26].i= 83
container[26].j= 220
container[26].angle= 18
container[26].value= 255


container[27].bin= 63
container[27].i= 84
container[27].j= 220
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 84
container[28].j= 221
container[28].angle= 296
container[28].value= 255


container[29].bin= 44
container[29].i= 84
container[29].j= 222
container[29].angle= 224
container[29].value= 255


