container[0].bin= 8
container[0].i= 31
container[0].j= 596
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 31
container[1].j= 597
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 32
container[2].j= 595
container[2].angle= 0
container[2].value= 255


container[3].bin= 63
container[3].i= 33
container[3].j= 596
container[3].angle= 315
container[3].value= 255


container[4].bin= 0
container[4].i= 36
container[4].j= 598
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 36
container[5].j= 600
container[5].angle= 180
container[5].value= 255


container[6].bin= 5
container[6].i= 37
container[6].j= 598
container[6].angle= 26
container[6].value= 255


container[7].bin= 30
container[7].i= 37
container[7].j= 600
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 38
container[8].j= 597
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 38
container[9].j= 600
container[9].angle= 180
container[9].value= 255


container[10].bin= 63
container[10].i= 39
container[10].j= 598
container[10].angle= 315
container[10].value= 255


container[11].bin= 48
container[11].i= 39
container[11].j= 599
container[11].angle= 243
container[11].value= 255


container[12].bin= 44
container[12].i= 39
container[12].j= 600
container[12].angle= 224
container[12].value= 255


