container[0].bin= 18
container[0].i= 809
container[0].j= 292
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 809
container[1].j= 293
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 809
container[2].j= 294
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 809
container[3].j= 295
container[3].angle= 90
container[3].value= 255


container[4].bin= 21
container[4].i= 809
container[4].j= 296
container[4].angle= 108
container[4].value= 255


container[5].bin= 8
container[5].i= 810
container[5].j= 291
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 810
container[6].j= 296
container[6].angle= 135
container[6].value= 255


container[7].bin= 27
container[7].i= 810
container[7].j= 297
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 811
container[8].j= 290
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 811
container[9].j= 295
container[9].angle= 180
container[9].value= 255


container[10].bin= 27
container[10].i= 811
container[10].j= 297
container[10].angle= 135
container[10].value= 255


container[11].bin= 63
container[11].i= 812
container[11].j= 291
container[11].angle= 315
container[11].value= 255


container[12].bin= 27
container[12].i= 812
container[12].j= 298
container[12].angle= 135
container[12].value= 255


container[13].bin= 59
container[13].i= 813
container[13].j= 292
container[13].angle= 296
container[13].value= 255


container[14].bin= 63
container[14].i= 813
container[14].j= 293
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 813
container[15].j= 299
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 814
container[16].j= 293
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 814
container[17].j= 299
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 815
container[18].j= 293
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 815
container[19].j= 300
container[19].angle= 135
container[19].value= 255


container[20].bin= 18
container[20].i= 815
container[20].j= 301
container[20].angle= 90
container[20].value= 255


container[21].bin= 18
container[21].i= 815
container[21].j= 302
container[21].angle= 90
container[21].value= 255


container[22].bin= 63
container[22].i= 816
container[22].j= 293
container[22].angle= 315
container[22].value= 255


container[23].bin= 54
container[23].i= 816
container[23].j= 294
container[23].angle= 270
container[23].value= 255


container[24].bin= 57
container[24].i= 816
container[24].j= 295
container[24].angle= 288
container[24].value= 255


container[25].bin= 27
container[25].i= 816
container[25].j= 303
container[25].angle= 135
container[25].value= 255


container[26].bin= 3
container[26].i= 817
container[26].j= 295
container[26].angle= 18
container[26].value= 255


container[27].bin= 36
container[27].i= 817
container[27].j= 303
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 818
container[28].j= 295
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 818
container[29].j= 303
container[29].angle= 180
container[29].value= 255


container[30].bin= 66
container[30].i= 819
container[30].j= 295
container[30].angle= 333
container[30].value= 255


container[31].bin= 36
container[31].i= 819
container[31].j= 303
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 820
container[32].j= 295
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 820
container[33].j= 303
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 821
container[34].j= 296
container[34].angle= 333
container[34].value= 255


container[35].bin= 36
container[35].i= 821
container[35].j= 303
container[35].angle= 180
container[35].value= 255


container[36].bin= 66
container[36].i= 822
container[36].j= 296
container[36].angle= 333
container[36].value= 255


container[37].bin= 32
container[37].i= 822
container[37].j= 303
container[37].angle= 161
container[37].value= 255


container[38].bin= 21
container[38].i= 822
container[38].j= 305
container[38].angle= 108
container[38].value= 255


container[39].bin= 0
container[39].i= 823
container[39].j= 296
container[39].angle= 0
container[39].value= 255


container[40].bin= 32
container[40].i= 823
container[40].j= 305
container[40].angle= 161
container[40].value= 255


container[41].bin= 0
container[41].i= 824
container[41].j= 296
container[41].angle= 0
container[41].value= 255


container[42].bin= 54
container[42].i= 824
container[42].j= 304
container[42].angle= 270
container[42].value= 255


container[43].bin= 44
container[43].i= 824
container[43].j= 305
container[43].angle= 224
container[43].value= 255


container[44].bin= 0
container[44].i= 825
container[44].j= 296
container[44].angle= 0
container[44].value= 255


container[45].bin= 44
container[45].i= 825
container[45].j= 303
container[45].angle= 224
container[45].value= 255


container[46].bin= 0
container[46].i= 826
container[46].j= 296
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 826
container[47].j= 302
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 827
container[48].j= 296
container[48].angle= 0
container[48].value= 255


container[49].bin= 44
container[49].i= 827
container[49].j= 302
container[49].angle= 224
container[49].value= 255


container[50].bin= 0
container[50].i= 828
container[50].j= 296
container[50].angle= 0
container[50].value= 255


container[51].bin= 44
container[51].i= 828
container[51].j= 301
container[51].angle= 224
container[51].value= 255


container[52].bin= 0
container[52].i= 829
container[52].j= 296
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 829
container[53].j= 300
container[53].angle= 180
container[53].value= 255


container[54].bin= 63
container[54].i= 830
container[54].j= 297
container[54].angle= 315
container[54].value= 255


container[55].bin= 36
container[55].i= 830
container[55].j= 300
container[55].angle= 180
container[55].value= 255


container[56].bin= 63
container[56].i= 831
container[56].j= 298
container[56].angle= 315
container[56].value= 255


container[57].bin= 0
container[57].i= 832
container[57].j= 298
container[57].angle= 0
container[57].value= 255


container[58].bin= 0
container[58].i= 833
container[58].j= 298
container[58].angle= 0
container[58].value= 255


container[59].bin= 0
container[59].i= 834
container[59].j= 298
container[59].angle= 0
container[59].value= 255


container[60].bin= 0
container[60].i= 835
container[60].j= 298
container[60].angle= 0
container[60].value= 255


container[61].bin= 0
container[61].i= 836
container[61].j= 298
container[61].angle= 0
container[61].value= 255


container[62].bin= 41
container[62].i= 836
container[62].j= 300
container[62].angle= 206
container[62].value= 255


container[63].bin= 0
container[63].i= 837
container[63].j= 298
container[63].angle= 0
container[63].value= 255


container[64].bin= 41
container[64].i= 837
container[64].j= 300
container[64].angle= 206
container[64].value= 255


container[65].bin= 0
container[65].i= 838
container[65].j= 298
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 838
container[66].j= 300
container[66].angle= 180
container[66].value= 255


container[67].bin= 68
container[67].i= 839
container[67].j= 298
container[67].angle= 341
container[67].value= 255


container[68].bin= 54
container[68].i= 839
container[68].j= 299
container[68].angle= 270
container[68].value= 255


container[69].bin= 39
container[69].i= 839
container[69].j= 300
container[69].angle= 198
container[69].value= 255


