container[0].bin= 18
container[0].i= 309
container[0].j= 308
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 309
container[1].j= 309
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 310
container[2].j= 307
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 310
container[3].j= 310
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 311
container[4].j= 306
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 311
container[5].j= 310
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 312
container[6].j= 306
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 312
container[7].j= 310
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 313
container[8].j= 306
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 313
container[9].j= 310
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 314
container[10].j= 306
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 314
container[11].j= 310
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 315
container[12].j= 306
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 315
container[13].j= 311
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 315
container[14].j= 312
container[14].angle= 90
container[14].value= 255


container[15].bin= 21
container[15].i= 315
container[15].j= 313
container[15].angle= 108
container[15].value= 255


container[16].bin= 0
container[16].i= 316
container[16].j= 306
container[16].angle= 0
container[16].value= 255


container[17].bin= 14
container[17].i= 316
container[17].j= 314
container[17].angle= 71
container[17].value= 255


container[18].bin= 21
container[18].i= 316
container[18].j= 315
container[18].angle= 108
container[18].value= 255


container[19].bin= 0
container[19].i= 317
container[19].j= 306
container[19].angle= 0
container[19].value= 255


container[20].bin= 44
container[20].i= 317
container[20].j= 312
container[20].angle= 224
container[20].value= 255


container[21].bin= 36
container[21].i= 317
container[21].j= 316
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 318
container[22].j= 307
container[22].angle= 315
container[22].value= 255


container[23].bin= 44
container[23].i= 318
container[23].j= 311
container[23].angle= 224
container[23].value= 255


container[24].bin= 44
container[24].i= 318
container[24].j= 312
container[24].angle= 224
container[24].value= 255


container[25].bin= 66
container[25].i= 318
container[25].j= 314
container[25].angle= 333
container[25].value= 255


container[26].bin= 36
container[26].i= 318
container[26].j= 316
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 319
container[27].j= 308
container[27].angle= 315
container[27].value= 255


container[28].bin= 41
container[28].i= 319
container[28].j= 311
container[28].angle= 206
container[28].value= 255


container[29].bin= 0
container[29].i= 319
container[29].j= 314
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 319
container[30].j= 316
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 320
container[31].j= 308
container[31].angle= 0
container[31].value= 255


container[32].bin= 0
container[32].i= 320
container[32].j= 314
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 320
container[33].j= 316
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 321
container[34].j= 309
container[34].angle= 333
container[34].value= 255


container[35].bin= 0
container[35].i= 321
container[35].j= 314
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 321
container[36].j= 316
container[36].angle= 180
container[36].value= 255


container[37].bin= 66
container[37].i= 322
container[37].j= 309
container[37].angle= 333
container[37].value= 255


container[38].bin= 36
container[38].i= 322
container[38].j= 311
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 322
container[39].j= 314
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 322
container[40].j= 316
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 323
container[41].j= 309
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 323
container[42].j= 311
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 323
container[43].j= 314
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 323
container[44].j= 316
container[44].angle= 180
container[44].value= 255


container[45].bin= 68
container[45].i= 324
container[45].j= 309
container[45].angle= 341
container[45].value= 255


container[46].bin= 54
container[46].i= 324
container[46].j= 310
container[46].angle= 270
container[46].value= 255


container[47].bin= 39
container[47].i= 324
container[47].j= 311
container[47].angle= 198
container[47].value= 255


container[48].bin= 39
container[48].i= 324
container[48].j= 316
container[48].angle= 198
container[48].value= 255


container[49].bin= 8
container[49].i= 325
container[49].j= 313
container[49].angle= 44
container[49].value= 255


container[50].bin= 0
container[50].i= 326
container[50].j= 312
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 326
container[51].j= 315
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 327
container[52].j= 312
container[52].angle= 0
container[52].value= 255


container[53].bin= 44
container[53].i= 327
container[53].j= 314
container[53].angle= 224
container[53].value= 255


container[54].bin= 44
container[54].i= 327
container[54].j= 315
container[54].angle= 224
container[54].value= 255


container[55].bin= 0
container[55].i= 328
container[55].j= 312
container[55].angle= 0
container[55].value= 255


container[56].bin= 41
container[56].i= 328
container[56].j= 314
container[56].angle= 206
container[56].value= 255


container[57].bin= 5
container[57].i= 329
container[57].j= 312
container[57].angle= 26
container[57].value= 255


container[58].bin= 36
container[58].i= 329
container[58].j= 314
container[58].angle= 180
container[58].value= 255


container[59].bin= 5
container[59].i= 330
container[59].j= 312
container[59].angle= 26
container[59].value= 255


container[60].bin= 0
container[60].i= 331
container[60].j= 311
container[60].angle= 0
container[60].value= 255


container[61].bin= 0
container[61].i= 332
container[61].j= 311
container[61].angle= 0
container[61].value= 255


container[62].bin= 66
container[62].i= 333
container[62].j= 312
container[62].angle= 333
container[62].value= 255


container[63].bin= 63
container[63].i= 334
container[63].j= 312
container[63].angle= 315
container[63].value= 255


