container[0].bin= 18
container[0].i= 396
container[0].j= 390
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 397
container[1].j= 389
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 397
container[2].j= 391
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 398
container[3].j= 389
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 398
container[4].j= 391
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 399
container[5].j= 385
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 399
container[6].j= 386
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 399
container[7].j= 389
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 399
container[8].j= 391
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 400
container[9].j= 384
container[9].angle= 44
container[9].value= 255


container[10].bin= 27
container[10].i= 400
container[10].j= 387
container[10].angle= 135
container[10].value= 255


container[11].bin= 36
container[11].i= 400
container[11].j= 391
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 401
container[12].j= 383
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 401
container[13].j= 387
container[13].angle= 180
container[13].value= 255


container[14].bin= 36
container[14].i= 401
container[14].j= 391
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 402
container[15].j= 384
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 402
container[16].j= 385
container[16].angle= 270
container[16].value= 255


container[17].bin= 5
container[17].i= 402
container[17].j= 389
container[17].angle= 26
container[17].value= 255


container[18].bin= 36
container[18].i= 402
container[18].j= 391
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 403
container[19].j= 386
container[19].angle= 315
container[19].value= 255


container[20].bin= 8
container[20].i= 403
container[20].j= 389
container[20].angle= 44
container[20].value= 255


container[21].bin= 0
container[21].i= 404
container[21].j= 386
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 404
container[22].j= 391
container[22].angle= 153
container[22].value= 255


container[23].bin= 68
container[23].i= 405
container[23].j= 386
container[23].angle= 341
container[23].value= 255


container[24].bin= 57
container[24].i= 405
container[24].j= 387
container[24].angle= 288
container[24].value= 255


container[25].bin= 54
container[25].i= 405
container[25].j= 388
container[25].angle= 270
container[25].value= 255


container[26].bin= 63
container[26].i= 405
container[26].j= 389
container[26].angle= 315
container[26].value= 255


container[27].bin= 27
container[27].i= 405
container[27].j= 391
container[27].angle= 135
container[27].value= 255


container[28].bin= 18
container[28].i= 405
container[28].j= 392
container[28].angle= 90
container[28].value= 255


container[29].bin= 21
container[29].i= 405
container[29].j= 393
container[29].angle= 108
container[29].value= 255


container[30].bin= 66
container[30].i= 406
container[30].j= 389
container[30].angle= 333
container[30].value= 255


container[31].bin= 32
container[31].i= 406
container[31].j= 393
container[31].angle= 161
container[31].value= 255


container[32].bin= 0
container[32].i= 407
container[32].j= 389
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 407
container[33].j= 393
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 408
container[34].j= 390
container[34].angle= 315
container[34].value= 255


container[35].bin= 30
container[35].i= 408
container[35].j= 394
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 409
container[36].j= 391
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 409
container[37].j= 394
container[37].angle= 153
container[37].value= 255


container[38].bin= 0
container[38].i= 410
container[38].j= 391
container[38].angle= 0
container[38].value= 255


container[39].bin= 30
container[39].i= 410
container[39].j= 395
container[39].angle= 153
container[39].value= 255


container[40].bin= 0
container[40].i= 411
container[40].j= 391
container[40].angle= 0
container[40].value= 255


container[41].bin= 0
container[41].i= 412
container[41].j= 391
container[41].angle= 0
container[41].value= 255


container[42].bin= 44
container[42].i= 412
container[42].j= 394
container[42].angle= 224
container[42].value= 255


container[43].bin= 0
container[43].i= 413
container[43].j= 391
container[43].angle= 0
container[43].value= 255


container[44].bin= 63
container[44].i= 414
container[44].j= 392
container[44].angle= 315
container[44].value= 255


container[45].bin= 44
container[45].i= 414
container[45].j= 393
container[45].angle= 224
container[45].value= 255


