container[0].bin= 18
container[0].i= 444
container[0].j= 497
container[0].angle= 90
container[0].value= 255


container[1].bin= 12
container[1].i= 444
container[1].j= 498
container[1].angle= 63
container[1].value= 255


container[2].bin= 18
container[2].i= 444
container[2].j= 499
container[2].angle= 90
container[2].value= 255


container[3].bin= 23
container[3].i= 444
container[3].j= 500
container[3].angle= 116
container[3].value= 255


container[4].bin= 8
container[4].i= 445
container[4].j= 496
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 445
container[5].j= 501
container[5].angle= 135
container[5].value= 255


container[6].bin= 66
container[6].i= 446
container[6].j= 496
container[6].angle= 333
container[6].value= 255


container[7].bin= 36
container[7].i= 446
container[7].j= 501
container[7].angle= 180
container[7].value= 255


container[8].bin= 63
container[8].i= 447
container[8].j= 496
container[8].angle= 315
container[8].value= 255


container[9].bin= 59
container[9].i= 447
container[9].j= 497
container[9].angle= 296
container[9].value= 255


container[10].bin= 54
container[10].i= 447
container[10].j= 498
container[10].angle= 270
container[10].value= 255


container[11].bin= 54
container[11].i= 447
container[11].j= 499
container[11].angle= 270
container[11].value= 255


container[12].bin= 54
container[12].i= 447
container[12].j= 500
container[12].angle= 270
container[12].value= 255


container[13].bin= 44
container[13].i= 447
container[13].j= 501
container[13].angle= 224
container[13].value= 255


