container[0].bin= 18
container[0].i= 474
container[0].j= 580
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 475
container[1].j= 579
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 475
container[2].j= 581
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 476
container[3].j= 579
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 476
container[4].j= 581
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 477
container[5].j= 579
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 477
container[6].j= 581
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 478
container[7].j= 579
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 478
container[8].j= 581
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 479
container[9].j= 579
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 479
container[10].j= 581
container[10].angle= 180
container[10].value= 255


container[11].bin= 18
container[11].i= 480
container[11].j= 578
container[11].angle= 90
container[11].value= 255


container[12].bin= 8
container[12].i= 480
container[12].j= 579
container[12].angle= 44
container[12].value= 255


container[13].bin= 36
container[13].i= 480
container[13].j= 581
container[13].angle= 180
container[13].value= 255


container[14].bin= 8
container[14].i= 481
container[14].j= 577
container[14].angle= 44
container[14].value= 255


container[15].bin= 0
container[15].i= 482
container[15].j= 576
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 482
container[16].j= 580
container[16].angle= 180
container[16].value= 255


container[17].bin= 8
container[17].i= 483
container[17].j= 576
container[17].angle= 44
container[17].value= 255


container[18].bin= 36
container[18].i= 483
container[18].j= 580
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 484
container[19].j= 575
container[19].angle= 44
container[19].value= 255


container[20].bin= 36
container[20].i= 484
container[20].j= 580
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 485
container[21].j= 574
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 485
container[22].j= 580
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 486
container[23].j= 575
container[23].angle= 315
container[23].value= 255


container[24].bin= 44
container[24].i= 486
container[24].j= 580
container[24].angle= 224
container[24].value= 255


container[25].bin= 63
container[25].i= 487
container[25].j= 576
container[25].angle= 315
container[25].value= 255


container[26].bin= 44
container[26].i= 487
container[26].j= 579
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 488
container[27].j= 576
container[27].angle= 0
container[27].value= 255


container[28].bin= 63
container[28].i= 489
container[28].j= 577
container[28].angle= 315
container[28].value= 255


container[29].bin= 44
container[29].i= 489
container[29].j= 578
container[29].angle= 224
container[29].value= 255


