container[0].bin= 18
container[0].i= 161
container[0].j= 171
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 162
container[1].j= 170
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 162
container[2].j= 172
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 162
container[3].j= 173
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 163
container[4].j= 169
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 163
container[5].j= 173
container[5].angle= 153
container[5].value= 255


container[6].bin= 66
container[6].i= 164
container[6].j= 170
container[6].angle= 333
container[6].value= 255


container[7].bin= 30
container[7].i= 164
container[7].j= 174
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 165
container[8].j= 170
container[8].angle= 333
container[8].value= 255


container[9].bin= 27
container[9].i= 165
container[9].j= 174
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 165
container[10].j= 175
container[10].angle= 135
container[10].value= 255


container[11].bin= 66
container[11].i= 166
container[11].j= 171
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 166
container[12].j= 175
container[12].angle= 153
container[12].value= 255


container[13].bin= 63
container[13].i= 167
container[13].j= 171
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 167
container[14].j= 172
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 167
container[15].j= 175
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 168
container[16].j= 172
container[16].angle= 315
container[16].value= 255


container[17].bin= 63
container[17].i= 168
container[17].j= 173
container[17].angle= 315
container[17].value= 255


container[18].bin= 30
container[18].i= 168
container[18].j= 176
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 169
container[19].j= 173
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 169
container[20].j= 176
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 170
container[21].j= 174
container[21].angle= 333
container[21].value= 255


container[22].bin= 41
container[22].i= 170
container[22].j= 176
container[22].angle= 206
container[22].value= 255


container[23].bin= 63
container[23].i= 171
container[23].j= 174
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 171
container[24].j= 175
container[24].angle= 270
container[24].value= 255


container[25].bin= 44
container[25].i= 171
container[25].j= 176
container[25].angle= 224
container[25].value= 255


