container[0].bin= 18
container[0].i= 66
container[0].j= 159
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 67
container[1].j= 158
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 67
container[2].j= 160
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 68
container[3].j= 158
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 68
container[4].j= 160
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 69
container[5].j= 158
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 69
container[6].j= 160
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 70
container[7].j= 158
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 70
container[8].j= 161
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 71
container[9].j= 158
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 71
container[10].j= 161
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 72
container[11].j= 159
container[11].angle= 315
container[11].value= 255


container[12].bin= 54
container[12].i= 72
container[12].j= 160
container[12].angle= 270
container[12].value= 255


container[13].bin= 44
container[13].i= 72
container[13].j= 161
container[13].angle= 224
container[13].value= 255


