container[0].bin= 18
container[0].i= 800
container[0].j= 262
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 801
container[1].j= 261
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 801
container[2].j= 263
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 802
container[3].j= 261
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 802
container[4].j= 263
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 803
container[5].j= 259
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 803
container[6].j= 260
container[6].angle= 90
container[6].value= 255


container[7].bin= 8
container[7].i= 803
container[7].j= 261
container[7].angle= 44
container[7].value= 255


container[8].bin= 36
container[8].i= 803
container[8].j= 263
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 804
container[9].j= 258
container[9].angle= 44
container[9].value= 255


container[10].bin= 0
container[10].i= 805
container[10].j= 257
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 805
container[11].j= 262
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 806
container[12].j= 258
container[12].angle= 315
container[12].value= 255


container[13].bin= 36
container[13].i= 806
container[13].j= 262
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 807
container[14].j= 259
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 807
container[15].j= 262
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 808
container[16].j= 259
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 808
container[17].j= 262
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 809
container[18].j= 260
container[18].angle= 315
container[18].value= 255


container[19].bin= 63
container[19].i= 810
container[19].j= 261
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 810
container[20].j= 263
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 811
container[21].j= 261
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 811
container[22].j= 263
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 812
container[23].j= 261
container[23].angle= 341
container[23].value= 255


container[24].bin= 54
container[24].i= 812
container[24].j= 262
container[24].angle= 270
container[24].value= 255


container[25].bin= 39
container[25].i= 812
container[25].j= 263
container[25].angle= 198
container[25].value= 255


