container[0].bin= 3
container[0].i= 245
container[0].j= 237
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 245
container[1].j= 238
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 245
container[2].j= 239
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 246
container[3].j= 237
container[3].angle= 26
container[3].value= 255


container[4].bin= 27
container[4].i= 246
container[4].j= 239
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 246
container[5].j= 240
container[5].angle= 135
container[5].value= 255


container[6].bin= 5
container[6].i= 247
container[6].j= 237
container[6].angle= 26
container[6].value= 255


container[7].bin= 27
container[7].i= 247
container[7].j= 240
container[7].angle= 135
container[7].value= 255


container[8].bin= 23
container[8].i= 247
container[8].j= 241
container[8].angle= 116
container[8].value= 255


container[9].bin= 5
container[9].i= 248
container[9].j= 236
container[9].angle= 26
container[9].value= 255


container[10].bin= 23
container[10].i= 248
container[10].j= 242
container[10].angle= 116
container[10].value= 255


container[11].bin= 23
container[11].i= 248
container[11].j= 243
container[11].angle= 116
container[11].value= 255


container[12].bin= 5
container[12].i= 249
container[12].j= 236
container[12].angle= 26
container[12].value= 255


container[13].bin= 27
container[13].i= 249
container[13].j= 244
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 250
container[14].j= 235
container[14].angle= 0
container[14].value= 255


container[15].bin= 30
container[15].i= 250
container[15].j= 245
container[15].angle= 153
container[15].value= 255


container[16].bin= 66
container[16].i= 251
container[16].j= 236
container[16].angle= 333
container[16].value= 255


container[17].bin= 27
container[17].i= 251
container[17].j= 245
container[17].angle= 135
container[17].value= 255


container[18].bin= 27
container[18].i= 251
container[18].j= 246
container[18].angle= 135
container[18].value= 255


container[19].bin= 66
container[19].i= 252
container[19].j= 236
container[19].angle= 333
container[19].value= 255


container[20].bin= 27
container[20].i= 252
container[20].j= 246
container[20].angle= 135
container[20].value= 255


container[21].bin= 27
container[21].i= 252
container[21].j= 247
container[21].angle= 135
container[21].value= 255


container[22].bin= 66
container[22].i= 253
container[22].j= 237
container[22].angle= 333
container[22].value= 255


container[23].bin= 30
container[23].i= 253
container[23].j= 247
container[23].angle= 153
container[23].value= 255


container[24].bin= 63
container[24].i= 254
container[24].j= 237
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 254
container[25].j= 238
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 254
container[26].j= 248
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 255
container[27].j= 238
container[27].angle= 315
container[27].value= 255


container[28].bin= 63
container[28].i= 255
container[28].j= 239
container[28].angle= 315
container[28].value= 255


container[29].bin= 30
container[29].i= 255
container[29].j= 248
container[29].angle= 153
container[29].value= 255


container[30].bin= 63
container[30].i= 256
container[30].j= 239
container[30].angle= 315
container[30].value= 255


container[31].bin= 63
container[31].i= 256
container[31].j= 240
container[31].angle= 315
container[31].value= 255


container[32].bin= 36
container[32].i= 256
container[32].j= 248
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 257
container[33].j= 240
container[33].angle= 315
container[33].value= 255


container[34].bin= 59
container[34].i= 257
container[34].j= 241
container[34].angle= 296
container[34].value= 255


container[35].bin= 36
container[35].i= 257
container[35].j= 248
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 258
container[36].j= 242
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 258
container[37].j= 248
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 259
container[38].j= 243
container[38].angle= 315
container[38].value= 255


container[39].bin= 36
container[39].i= 259
container[39].j= 248
container[39].angle= 180
container[39].value= 255


container[40].bin= 59
container[40].i= 260
container[40].j= 244
container[40].angle= 296
container[40].value= 255


container[41].bin= 59
container[41].i= 260
container[41].j= 245
container[41].angle= 296
container[41].value= 255


container[42].bin= 54
container[42].i= 260
container[42].j= 246
container[42].angle= 270
container[42].value= 255


container[43].bin= 54
container[43].i= 260
container[43].j= 247
container[43].angle= 270
container[43].value= 255


container[44].bin= 44
container[44].i= 260
container[44].j= 248
container[44].angle= 224
container[44].value= 255


