container[0].bin= 18
container[0].i= 465
container[0].j= 301
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 465
container[1].j= 302
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 466
container[2].j= 300
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 466
container[3].j= 303
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 467
container[4].j= 299
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 467
container[5].j= 303
container[5].angle= 180
container[5].value= 255


container[6].bin= 66
container[6].i= 468
container[6].j= 300
container[6].angle= 333
container[6].value= 255


container[7].bin= 36
container[7].i= 468
container[7].j= 303
container[7].angle= 180
container[7].value= 255


container[8].bin= 66
container[8].i= 469
container[8].j= 300
container[8].angle= 333
container[8].value= 255


container[9].bin= 36
container[9].i= 469
container[9].j= 303
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 470
container[10].j= 300
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 470
container[11].j= 303
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 471
container[12].j= 301
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 471
container[13].j= 302
container[13].angle= 270
container[13].value= 255


container[14].bin= 44
container[14].i= 471
container[14].j= 303
container[14].angle= 224
container[14].value= 255


