container[0].bin= 18
container[0].i= 447
container[0].j= 437
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 448
container[1].j= 436
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 448
container[2].j= 438
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 449
container[3].j= 436
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 449
container[4].j= 438
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 450
container[5].j= 436
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 450
container[6].j= 438
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 451
container[7].j= 436
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 451
container[8].j= 438
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 452
container[9].j= 436
container[9].angle= 0
container[9].value= 255


container[10].bin= 8
container[10].i= 453
container[10].j= 436
container[10].angle= 44
container[10].value= 255


container[11].bin= 8
container[11].i= 454
container[11].j= 435
container[11].angle= 44
container[11].value= 255


container[12].bin= 36
container[12].i= 454
container[12].j= 438
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 455
container[13].j= 434
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 455
container[14].j= 438
container[14].angle= 180
container[14].value= 255


container[15].bin= 3
container[15].i= 456
container[15].j= 431
container[15].angle= 18
container[15].value= 255


container[16].bin= 14
container[16].i= 456
container[16].j= 432
container[16].angle= 71
container[16].value= 255


container[17].bin= 23
container[17].i= 456
container[17].j= 433
container[17].angle= 116
container[17].value= 255


container[18].bin= 8
container[18].i= 456
container[18].j= 434
container[18].angle= 44
container[18].value= 255


container[19].bin= 36
container[19].i= 456
container[19].j= 438
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 457
container[20].j= 431
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 457
container[21].j= 438
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 458
container[22].j= 431
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 458
container[23].j= 438
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 459
container[24].j= 432
container[24].angle= 315
container[24].value= 255


container[25].bin= 54
container[25].i= 459
container[25].j= 437
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 459
container[26].j= 438
container[26].angle= 224
container[26].value= 255


container[27].bin= 63
container[27].i= 460
container[27].j= 433
container[27].angle= 315
container[27].value= 255


container[28].bin= 44
container[28].i= 460
container[28].j= 436
container[28].angle= 224
container[28].value= 255


container[29].bin= 0
container[29].i= 461
container[29].j= 433
container[29].angle= 0
container[29].value= 255


container[30].bin= 63
container[30].i= 462
container[30].j= 434
container[30].angle= 315
container[30].value= 255


container[31].bin= 44
container[31].i= 462
container[31].j= 435
container[31].angle= 224
container[31].value= 255


