container[0].bin= 18
container[0].i= 679
container[0].j= 242
container[0].angle= 90
container[0].value= 255


container[1].bin= 21
container[1].i= 679
container[1].j= 243
container[1].angle= 108
container[1].value= 255


container[2].bin= 8
container[2].i= 680
container[2].j= 241
container[2].angle= 44
container[2].value= 255


container[3].bin= 0
container[3].i= 681
container[3].j= 240
container[3].angle= 0
container[3].value= 255


container[4].bin= 32
container[4].i= 681
container[4].j= 243
container[4].angle= 161
container[4].value= 255


container[5].bin= 27
container[5].i= 681
container[5].j= 244
container[5].angle= 135
container[5].value= 255


container[6].bin= 63
container[6].i= 682
container[6].j= 241
container[6].angle= 315
container[6].value= 255


container[7].bin= 50
container[7].i= 682
container[7].j= 242
container[7].angle= 251
container[7].value= 255


container[8].bin= 54
container[8].i= 683
container[8].j= 243
container[8].angle= 270
container[8].value= 255


container[9].bin= 50
container[9].i= 683
container[9].j= 244
container[9].angle= 251
container[9].value= 255


