container[0].bin= 8
container[0].i= 768
container[0].j= 339
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 768
container[1].j= 340
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 769
container[2].j= 338
container[2].angle= 0
container[2].value= 255


container[3].bin= 5
container[3].i= 770
container[3].j= 338
container[3].angle= 26
container[3].value= 255


container[4].bin= 41
container[4].i= 770
container[4].j= 340
container[4].angle= 206
container[4].value= 255


container[5].bin= 5
container[5].i= 771
container[5].j= 338
container[5].angle= 26
container[5].value= 255


container[6].bin= 41
container[6].i= 771
container[6].j= 340
container[6].angle= 206
container[6].value= 255


container[7].bin= 0
container[7].i= 772
container[7].j= 337
container[7].angle= 0
container[7].value= 255


container[8].bin= 63
container[8].i= 773
container[8].j= 338
container[8].angle= 315
container[8].value= 255


container[9].bin= 44
container[9].i= 773
container[9].j= 339
container[9].angle= 224
container[9].value= 255


