container[0].bin= 18
container[0].i= 537
container[0].j= 466
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 538
container[1].j= 465
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 538
container[2].j= 467
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 539
container[3].j= 465
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 539
container[4].j= 467
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 540
container[5].j= 462
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 540
container[6].j= 463
container[6].angle= 90
container[6].value= 255


container[7].bin= 12
container[7].i= 540
container[7].j= 464
container[7].angle= 63
container[7].value= 255


container[8].bin= 8
container[8].i= 540
container[8].j= 465
container[8].angle= 44
container[8].value= 255


container[9].bin= 8
container[9].i= 541
container[9].j= 461
container[9].angle= 44
container[9].value= 255


container[10].bin= 36
container[10].i= 541
container[10].j= 466
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 542
container[11].j= 460
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 542
container[12].j= 466
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 543
container[13].j= 460
container[13].angle= 0
container[13].value= 255


container[14].bin= 54
container[14].i= 543
container[14].j= 464
container[14].angle= 270
container[14].value= 255


container[15].bin= 27
container[15].i= 543
container[15].j= 467
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 543
container[16].j= 468
container[16].angle= 90
container[16].value= 255


container[17].bin= 0
container[17].i= 544
container[17].j= 460
container[17].angle= 0
container[17].value= 255


container[18].bin= 44
container[18].i= 544
container[18].j= 463
container[18].angle= 224
container[18].value= 255


container[19].bin= 63
container[19].i= 544
container[19].j= 465
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 544
container[20].j= 469
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 545
container[21].j= 460
container[21].angle= 0
container[21].value= 255


container[22].bin= 0
container[22].i= 545
container[22].j= 465
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 545
container[23].j= 469
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 546
container[24].j= 461
container[24].angle= 315
container[24].value= 255


container[25].bin= 44
container[25].i= 546
container[25].j= 462
container[25].angle= 224
container[25].value= 255


container[26].bin= 0
container[26].i= 546
container[26].j= 465
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 546
container[27].j= 469
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 547
container[28].j= 465
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 547
container[29].j= 469
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 548
container[30].j= 465
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 548
container[31].j= 469
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 549
container[32].j= 466
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 549
container[33].j= 467
container[33].angle= 270
container[33].value= 255


container[34].bin= 63
container[34].i= 550
container[34].j= 468
container[34].angle= 315
container[34].value= 255


container[35].bin= 36
container[35].i= 550
container[35].j= 470
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 551
container[36].j= 468
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 551
container[37].j= 470
container[37].angle= 180
container[37].value= 255


container[38].bin= 68
container[38].i= 552
container[38].j= 468
container[38].angle= 341
container[38].value= 255


container[39].bin= 54
container[39].i= 552
container[39].j= 469
container[39].angle= 270
container[39].value= 255


container[40].bin= 39
container[40].i= 552
container[40].j= 470
container[40].angle= 198
container[40].value= 255


