container[0].bin= 18
container[0].i= 294
container[0].j= 310
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 295
container[1].j= 309
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 295
container[2].j= 311
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 296
container[3].j= 309
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 296
container[4].j= 311
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 297
container[5].j= 309
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 297
container[6].j= 311
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 298
container[7].j= 309
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 298
container[8].j= 311
container[8].angle= 180
container[8].value= 255


container[9].bin= 68
container[9].i= 299
container[9].j= 309
container[9].angle= 341
container[9].value= 255


container[10].bin= 12
container[10].i= 300
container[10].j= 308
container[10].angle= 63
container[10].value= 255


container[11].bin= 8
container[11].i= 301
container[11].j= 307
container[11].angle= 44
container[11].value= 255


container[12].bin= 27
container[12].i= 301
container[12].j= 311
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 302
container[13].j= 306
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 302
container[14].j= 311
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 303
container[15].j= 307
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 303
container[16].j= 308
container[16].angle= 270
container[16].value= 255


container[17].bin= 36
container[17].i= 303
container[17].j= 311
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 304
container[18].j= 309
container[18].angle= 315
container[18].value= 255


container[19].bin= 0
container[19].i= 305
container[19].j= 309
container[19].angle= 0
container[19].value= 255


container[20].bin= 63
container[20].i= 306
container[20].j= 310
container[20].angle= 315
container[20].value= 255


container[21].bin= 44
container[21].i= 306
container[21].j= 311
container[21].angle= 224
container[21].value= 255


