container[0].bin= 18
container[0].i= 20
container[0].j= 207
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 21
container[1].j= 206
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 21
container[2].j= 208
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 22
container[3].j= 206
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 22
container[4].j= 208
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 23
container[5].j= 206
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 23
container[6].j= 208
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 24
container[7].j= 206
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 24
container[8].j= 209
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 25
container[9].j= 206
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 25
container[10].j= 209
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 26
container[11].j= 206
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 26
container[12].j= 209
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 27
container[13].j= 207
container[13].angle= 315
container[13].value= 255


container[14].bin= 59
container[14].i= 28
container[14].j= 208
container[14].angle= 296
container[14].value= 255


container[15].bin= 32
container[15].i= 28
container[15].j= 210
container[15].angle= 161
container[15].value= 255


