container[0].bin= 18
container[0].i= 339
container[0].j= 160
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 339
container[1].j= 161
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 340
container[2].j= 159
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 340
container[3].j= 162
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 341
container[4].j= 158
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 341
container[5].j= 162
container[5].angle= 180
container[5].value= 255


container[6].bin= 14
container[6].i= 342
container[6].j= 154
container[6].angle= 71
container[6].value= 255


container[7].bin= 18
container[7].i= 342
container[7].j= 155
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 342
container[8].j= 156
container[8].angle= 90
container[8].value= 255


container[9].bin= 54
container[9].i= 342
container[9].j= 161
container[9].angle= 270
container[9].value= 255


container[10].bin= 44
container[10].i= 342
container[10].j= 162
container[10].angle= 224
container[10].value= 255


container[11].bin= 3
container[11].i= 343
container[11].j= 153
container[11].angle= 18
container[11].value= 255


container[12].bin= 8
container[12].i= 343
container[12].j= 154
container[12].angle= 44
container[12].value= 255


container[13].bin= 23
container[13].i= 343
container[13].j= 157
container[13].angle= 116
container[13].value= 255


container[14].bin= 44
container[14].i= 343
container[14].j= 160
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 344
container[15].j= 153
container[15].angle= 0
container[15].value= 255


container[16].bin= 0
container[16].i= 344
container[16].j= 156
container[16].angle= 0
container[16].value= 255


container[17].bin= 32
container[17].i= 344
container[17].j= 159
container[17].angle= 161
container[17].value= 255


container[18].bin= 5
container[18].i= 345
container[18].j= 153
container[18].angle= 26
container[18].value= 255


container[19].bin= 18
container[19].i= 345
container[19].j= 155
container[19].angle= 90
container[19].value= 255


container[20].bin= 44
container[20].i= 345
container[20].j= 159
container[20].angle= 224
container[20].value= 255


container[21].bin= 5
container[21].i= 346
container[21].j= 153
container[21].angle= 26
container[21].value= 255


container[22].bin= 44
container[22].i= 346
container[22].j= 158
container[22].angle= 224
container[22].value= 255


container[23].bin= 0
container[23].i= 347
container[23].j= 152
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 347
container[24].j= 157
container[24].angle= 180
container[24].value= 255


container[25].bin= 66
container[25].i= 348
container[25].j= 153
container[25].angle= 333
container[25].value= 255


container[26].bin= 54
container[26].i= 348
container[26].j= 154
container[26].angle= 270
container[26].value= 255


container[27].bin= 54
container[27].i= 348
container[27].j= 156
container[27].angle= 270
container[27].value= 255


container[28].bin= 44
container[28].i= 348
container[28].j= 157
container[28].angle= 224
container[28].value= 255


container[29].bin= 0
container[29].i= 349
container[29].j= 153
container[29].angle= 0
container[29].value= 255


container[30].bin= 44
container[30].i= 349
container[30].j= 155
container[30].angle= 224
container[30].value= 255


container[31].bin= 63
container[31].i= 351
container[31].j= 153
container[31].angle= 315
container[31].value= 255


