container[0].bin= 18
container[0].i= 249
container[0].j= 379
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 249
container[1].j= 380
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 249
container[2].j= 381
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 249
container[3].j= 382
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 249
container[4].j= 383
container[4].angle= 90
container[4].value= 255


container[5].bin= 8
container[5].i= 250
container[5].j= 378
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 250
container[6].j= 384
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 250
container[7].j= 387
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 251
container[8].j= 377
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 251
container[9].j= 384
container[9].angle= 180
container[9].value= 255


container[10].bin= 32
container[10].i= 251
container[10].j= 388
container[10].angle= 161
container[10].value= 255


container[11].bin= 0
container[11].i= 252
container[11].j= 377
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 252
container[12].j= 385
container[12].angle= 135
container[12].value= 255


container[13].bin= 8
container[13].i= 252
container[13].j= 386
container[13].angle= 44
container[13].value= 255


container[14].bin= 27
container[14].i= 252
container[14].j= 388
container[14].angle= 135
container[14].value= 255


container[15].bin= 18
container[15].i= 252
container[15].j= 389
container[15].angle= 90
container[15].value= 255


container[16].bin= 18
container[16].i= 252
container[16].j= 390
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 252
container[17].j= 391
container[17].angle= 90
container[17].value= 255


container[18].bin= 0
container[18].i= 253
container[18].j= 377
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 253
container[19].j= 392
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 254
container[20].j= 377
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 254
container[21].j= 392
container[21].angle= 180
container[21].value= 255


container[22].bin= 66
container[22].i= 255
container[22].j= 378
container[22].angle= 333
container[22].value= 255


container[23].bin= 36
container[23].i= 255
container[23].j= 392
container[23].angle= 180
container[23].value= 255


container[24].bin= 66
container[24].i= 256
container[24].j= 378
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 256
container[25].j= 392
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 257
container[26].j= 378
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 257
container[27].j= 392
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 258
container[28].j= 379
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 258
container[29].j= 392
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 259
container[30].j= 380
container[30].angle= 315
container[30].value= 255


container[31].bin= 36
container[31].i= 259
container[31].j= 392
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 260
container[32].j= 380
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 260
container[33].j= 392
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 261
container[34].j= 381
container[34].angle= 333
container[34].value= 255


container[35].bin= 54
container[35].i= 261
container[35].j= 382
container[35].angle= 270
container[35].value= 255


container[36].bin= 50
container[36].i= 261
container[36].j= 383
container[36].angle= 251
container[36].value= 255


container[37].bin= 54
container[37].i= 261
container[37].j= 384
container[37].angle= 270
container[37].value= 255


container[38].bin= 57
container[38].i= 261
container[38].j= 385
container[38].angle= 288
container[38].value= 255


container[39].bin= 36
container[39].i= 261
container[39].j= 392
container[39].angle= 180
container[39].value= 255


container[40].bin= 66
container[40].i= 262
container[40].j= 381
container[40].angle= 333
container[40].value= 255


container[41].bin= 39
container[41].i= 262
container[41].j= 383
container[41].angle= 198
container[41].value= 255


container[42].bin= 68
container[42].i= 262
container[42].j= 385
container[42].angle= 341
container[42].value= 255


container[43].bin= 36
container[43].i= 262
container[43].j= 392
container[43].angle= 180
container[43].value= 255


container[44].bin= 0
container[44].i= 263
container[44].j= 381
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 263
container[45].j= 383
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 263
container[46].j= 385
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 263
container[47].j= 392
container[47].angle= 180
container[47].value= 255


container[48].bin= 68
container[48].i= 264
container[48].j= 381
container[48].angle= 341
container[48].value= 255


container[49].bin= 57
container[49].i= 264
container[49].j= 382
container[49].angle= 288
container[49].value= 255


container[50].bin= 44
container[50].i= 264
container[50].j= 383
container[50].angle= 224
container[50].value= 255


container[51].bin= 54
container[51].i= 264
container[51].j= 384
container[51].angle= 270
container[51].value= 255


container[52].bin= 63
container[52].i= 264
container[52].j= 385
container[52].angle= 315
container[52].value= 255


container[53].bin= 63
container[53].i= 264
container[53].j= 386
container[53].angle= 315
container[53].value= 255


container[54].bin= 54
container[54].i= 264
container[54].j= 390
container[54].angle= 270
container[54].value= 255


container[55].bin= 54
container[55].i= 264
container[55].j= 391
container[55].angle= 270
container[55].value= 255


container[56].bin= 44
container[56].i= 264
container[56].j= 392
container[56].angle= 224
container[56].value= 255


container[57].bin= 66
container[57].i= 265
container[57].j= 386
container[57].angle= 333
container[57].value= 255


container[58].bin= 44
container[58].i= 265
container[58].j= 389
container[58].angle= 224
container[58].value= 255


container[59].bin= 0
container[59].i= 266
container[59].j= 386
container[59].angle= 0
container[59].value= 255


container[60].bin= 63
container[60].i= 267
container[60].j= 387
container[60].angle= 315
container[60].value= 255


container[61].bin= 23
container[61].i= 268
container[61].j= 390
container[61].angle= 116
container[61].value= 255


container[62].bin= 18
container[62].i= 268
container[62].j= 391
container[62].angle= 90
container[62].value= 255


container[63].bin= 21
container[63].i= 268
container[63].j= 392
container[63].angle= 108
container[63].value= 255


container[64].bin= 0
container[64].i= 269
container[64].j= 388
container[64].angle= 0
container[64].value= 255


container[65].bin= 39
container[65].i= 269
container[65].j= 392
container[65].angle= 198
container[65].value= 255


container[66].bin= 68
container[66].i= 270
container[66].j= 388
container[66].angle= 341
container[66].value= 255


container[67].bin= 54
container[67].i= 270
container[67].j= 390
container[67].angle= 270
container[67].value= 255


container[68].bin= 54
container[68].i= 270
container[68].j= 391
container[68].angle= 270
container[68].value= 255


container[69].bin= 44
container[69].i= 270
container[69].j= 392
container[69].angle= 224
container[69].value= 255


