container[0].bin= 18
container[0].i= 245
container[0].j= 220
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 246
container[1].j= 219
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 246
container[2].j= 221
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 247
container[3].j= 219
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 247
container[4].j= 221
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 248
container[5].j= 219
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 248
container[6].j= 221
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 249
container[7].j= 219
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 249
container[8].j= 222
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 250
container[9].j= 219
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 250
container[10].j= 222
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 251
container[11].j= 220
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 251
container[12].j= 223
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 252
container[13].j= 220
container[13].angle= 333
container[13].value= 255


container[14].bin= 27
container[14].i= 252
container[14].j= 223
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 252
container[15].j= 224
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 253
container[16].j= 220
container[16].angle= 0
container[16].value= 255


container[17].bin= 27
container[17].i= 253
container[17].j= 224
container[17].angle= 135
container[17].value= 255


container[18].bin= 27
container[18].i= 253
container[18].j= 225
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 254
container[19].j= 220
container[19].angle= 0
container[19].value= 255


container[20].bin= 27
container[20].i= 254
container[20].j= 225
container[20].angle= 135
container[20].value= 255


container[21].bin= 27
container[21].i= 254
container[21].j= 226
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 255
container[22].j= 220
container[22].angle= 0
container[22].value= 255


container[23].bin= 30
container[23].i= 255
container[23].j= 226
container[23].angle= 153
container[23].value= 255


container[24].bin= 0
container[24].i= 256
container[24].j= 220
container[24].angle= 0
container[24].value= 255


container[25].bin= 30
container[25].i= 256
container[25].j= 227
container[25].angle= 153
container[25].value= 255


container[26].bin= 0
container[26].i= 257
container[26].j= 220
container[26].angle= 0
container[26].value= 255


container[27].bin= 30
container[27].i= 257
container[27].j= 227
container[27].angle= 153
container[27].value= 255


container[28].bin= 5
container[28].i= 258
container[28].j= 220
container[28].angle= 26
container[28].value= 255


container[29].bin= 30
container[29].i= 258
container[29].j= 228
container[29].angle= 153
container[29].value= 255


container[30].bin= 5
container[30].i= 259
container[30].j= 220
container[30].angle= 26
container[30].value= 255


container[31].bin= 30
container[31].i= 259
container[31].j= 228
container[31].angle= 153
container[31].value= 255


container[32].bin= 0
container[32].i= 260
container[32].j= 219
container[32].angle= 0
container[32].value= 255


container[33].bin= 30
container[33].i= 260
container[33].j= 229
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 261
container[34].j= 219
container[34].angle= 0
container[34].value= 255


container[35].bin= 30
container[35].i= 261
container[35].j= 229
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 262
container[36].j= 220
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 262
container[37].j= 229
container[37].angle= 180
container[37].value= 255


container[38].bin= 59
container[38].i= 263
container[38].j= 221
container[38].angle= 296
container[38].value= 255


container[39].bin= 63
container[39].i= 263
container[39].j= 222
container[39].angle= 315
container[39].value= 255


container[40].bin= 30
container[40].i= 263
container[40].j= 230
container[40].angle= 153
container[40].value= 255


container[41].bin= 63
container[41].i= 264
container[41].j= 222
container[41].angle= 315
container[41].value= 255


container[42].bin= 63
container[42].i= 264
container[42].j= 223
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 264
container[43].j= 230
container[43].angle= 153
container[43].value= 255


container[44].bin= 63
container[44].i= 265
container[44].j= 223
container[44].angle= 315
container[44].value= 255


container[45].bin= 59
container[45].i= 265
container[45].j= 224
container[45].angle= 296
container[45].value= 255


container[46].bin= 30
container[46].i= 265
container[46].j= 231
container[46].angle= 153
container[46].value= 255


container[47].bin= 59
container[47].i= 266
container[47].j= 225
container[47].angle= 296
container[47].value= 255


container[48].bin= 59
container[48].i= 266
container[48].j= 226
container[48].angle= 296
container[48].value= 255


container[49].bin= 30
container[49].i= 266
container[49].j= 231
container[49].angle= 153
container[49].value= 255


container[50].bin= 59
container[50].i= 267
container[50].j= 227
container[50].angle= 296
container[50].value= 255


container[51].bin= 59
container[51].i= 267
container[51].j= 228
container[51].angle= 296
container[51].value= 255


container[52].bin= 36
container[52].i= 267
container[52].j= 231
container[52].angle= 180
container[52].value= 255


container[53].bin= 59
container[53].i= 268
container[53].j= 229
container[53].angle= 296
container[53].value= 255


container[54].bin= 59
container[54].i= 268
container[54].j= 230
container[54].angle= 296
container[54].value= 255


container[55].bin= 44
container[55].i= 268
container[55].j= 231
container[55].angle= 224
container[55].value= 255


