container[0].bin= 18
container[0].i= 531
container[0].j= 450
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 532
container[1].j= 449
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 532
container[2].j= 451
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 533
container[3].j= 449
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 533
container[4].j= 451
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 534
container[5].j= 449
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 534
container[6].j= 451
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 535
container[7].j= 448
container[7].angle= 44
container[7].value= 255


container[8].bin= 0
container[8].i= 536
container[8].j= 447
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 536
container[9].j= 450
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 537
container[10].j= 447
container[10].angle= 26
container[10].value= 255


container[11].bin= 36
container[11].i= 537
container[11].j= 450
container[11].angle= 180
container[11].value= 255


container[12].bin= 5
container[12].i= 538
container[12].j= 447
container[12].angle= 26
container[12].value= 255


container[13].bin= 36
container[13].i= 538
container[13].j= 450
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 539
container[14].j= 446
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 539
container[15].j= 450
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 540
container[16].j= 447
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 540
container[17].j= 448
container[17].angle= 270
container[17].value= 255


container[18].bin= 54
container[18].i= 540
container[18].j= 449
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 540
container[19].j= 450
container[19].angle= 224
container[19].value= 255


