container[0].bin= 18
container[0].i= 661
container[0].j= 265
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 661
container[1].j= 266
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 661
container[2].j= 267
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 662
container[3].j= 264
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 662
container[4].j= 268
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 663
container[5].j= 263
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 663
container[6].j= 268
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 664
container[7].j= 264
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 664
container[8].j= 268
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 665
container[9].j= 264
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 665
container[10].j= 268
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 666
container[11].j= 264
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 666
container[12].j= 268
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 667
container[13].j= 265
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 667
container[14].j= 266
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 667
container[15].j= 267
container[15].angle= 270
container[15].value= 255


container[16].bin= 44
container[16].i= 667
container[16].j= 268
container[16].angle= 224
container[16].value= 255


