container[0].bin= 18
container[0].i= 348
container[0].j= 473
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 348
container[1].j= 474
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 349
container[2].j= 472
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 349
container[3].j= 475
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 350
container[4].j= 471
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 350
container[5].j= 475
container[5].angle= 180
container[5].value= 255


container[6].bin= 14
container[6].i= 351
container[6].j= 469
container[6].angle= 71
container[6].value= 255


container[7].bin= 18
container[7].i= 351
container[7].j= 470
container[7].angle= 90
container[7].value= 255


container[8].bin= 8
container[8].i= 351
container[8].j= 471
container[8].angle= 44
container[8].value= 255


container[9].bin= 54
container[9].i= 351
container[9].j= 474
container[9].angle= 270
container[9].value= 255


container[10].bin= 44
container[10].i= 351
container[10].j= 475
container[10].angle= 224
container[10].value= 255


container[11].bin= 3
container[11].i= 352
container[11].j= 469
container[11].angle= 18
container[11].value= 255


container[12].bin= 44
container[12].i= 352
container[12].j= 473
container[12].angle= 224
container[12].value= 255


container[13].bin= 68
container[13].i= 353
container[13].j= 469
container[13].angle= 341
container[13].value= 255


container[14].bin= 36
container[14].i= 353
container[14].j= 472
container[14].angle= 180
container[14].value= 255


container[15].bin= 3
container[15].i= 354
container[15].j= 468
container[15].angle= 18
container[15].value= 255


container[16].bin= 63
container[16].i= 354
container[16].j= 471
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 354
container[17].j= 473
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 355
container[18].j= 468
container[18].angle= 0
container[18].value= 255


container[19].bin= 63
container[19].i= 355
container[19].j= 471
container[19].angle= 315
container[19].value= 255


container[20].bin= 0
container[20].i= 356
container[20].j= 468
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 356
container[21].j= 470
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 356
container[22].j= 472
container[22].angle= 315
container[22].value= 255


container[23].bin= 0
container[23].i= 357
container[23].j= 468
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 357
container[24].j= 470
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 357
container[25].j= 473
container[25].angle= 315
container[25].value= 255


container[26].bin= 0
container[26].i= 358
container[26].j= 468
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 358
container[27].j= 470
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 359
container[28].j= 468
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 359
container[29].j= 470
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 360
container[30].j= 468
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 360
container[31].j= 470
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 361
container[32].j= 468
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 361
container[33].j= 470
container[33].angle= 180
container[33].value= 255


container[34].bin= 0
container[34].i= 362
container[34].j= 468
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 362
container[35].j= 470
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 363
container[36].j= 468
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 363
container[37].j= 470
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 364
container[38].j= 468
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 364
container[39].j= 470
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 365
container[40].j= 468
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 365
container[41].j= 470
container[41].angle= 180
container[41].value= 255


container[42].bin= 68
container[42].i= 366
container[42].j= 468
container[42].angle= 341
container[42].value= 255


container[43].bin= 54
container[43].i= 366
container[43].j= 469
container[43].angle= 270
container[43].value= 255


container[44].bin= 39
container[44].i= 366
container[44].j= 470
container[44].angle= 198
container[44].value= 255


