container[0].bin= 18
container[0].i= 465
container[0].j= 122
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 466
container[1].j= 121
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 466
container[2].j= 123
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 466
container[3].j= 124
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 467
container[4].j= 120
container[4].angle= 0
container[4].value= 255


container[5].bin= 63
container[5].i= 468
container[5].j= 121
container[5].angle= 315
container[5].value= 255


container[6].bin= 48
container[6].i= 468
container[6].j= 122
container[6].angle= 243
container[6].value= 255


container[7].bin= 48
container[7].i= 468
container[7].j= 123
container[7].angle= 243
container[7].value= 255


