container[0].bin= 12
container[0].i= 266
container[0].j= 173
container[0].angle= 63
container[0].value= 255


container[1].bin= 12
container[1].i= 266
container[1].j= 174
container[1].angle= 63
container[1].value= 255


container[2].bin= 23
container[2].i= 266
container[2].j= 175
container[2].angle= 116
container[2].value= 255


container[3].bin= 23
container[3].i= 266
container[3].j= 176
container[3].angle= 116
container[3].value= 255


container[4].bin= 8
container[4].i= 267
container[4].j= 172
container[4].angle= 44
container[4].value= 255


container[5].bin= 23
container[5].i= 267
container[5].j= 177
container[5].angle= 116
container[5].value= 255


container[6].bin= 27
container[6].i= 267
container[6].j= 178
container[6].angle= 135
container[6].value= 255


container[7].bin= 5
container[7].i= 268
container[7].j= 171
container[7].angle= 26
container[7].value= 255


container[8].bin= 27
container[8].i= 268
container[8].j= 178
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 268
container[9].j= 179
container[9].angle= 135
container[9].value= 255


container[10].bin= 8
container[10].i= 269
container[10].j= 170
container[10].angle= 44
container[10].value= 255


container[11].bin= 8
container[11].i= 269
container[11].j= 171
container[11].angle= 44
container[11].value= 255


container[12].bin= 27
container[12].i= 269
container[12].j= 179
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 269
container[13].j= 180
container[13].angle= 135
container[13].value= 255


container[14].bin= 5
container[14].i= 270
container[14].j= 170
container[14].angle= 26
container[14].value= 255


container[15].bin= 30
container[15].i= 270
container[15].j= 180
container[15].angle= 153
container[15].value= 255


container[16].bin= 66
container[16].i= 271
container[16].j= 170
container[16].angle= 333
container[16].value= 255


container[17].bin= 30
container[17].i= 271
container[17].j= 181
container[17].angle= 153
container[17].value= 255


container[18].bin= 63
container[18].i= 272
container[18].j= 170
container[18].angle= 315
container[18].value= 255


container[19].bin= 63
container[19].i= 272
container[19].j= 171
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 272
container[20].j= 181
container[20].angle= 135
container[20].value= 255


container[21].bin= 27
container[21].i= 272
container[21].j= 182
container[21].angle= 135
container[21].value= 255


container[22].bin= 66
container[22].i= 273
container[22].j= 171
container[22].angle= 333
container[22].value= 255


container[23].bin= 30
container[23].i= 273
container[23].j= 182
container[23].angle= 153
container[23].value= 255


container[24].bin= 66
container[24].i= 274
container[24].j= 172
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 274
container[25].j= 182
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 275
container[26].j= 172
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 275
container[27].j= 173
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 275
container[28].j= 183
container[28].angle= 153
container[28].value= 255


container[29].bin= 66
container[29].i= 276
container[29].j= 173
container[29].angle= 333
container[29].value= 255


container[30].bin= 30
container[30].i= 276
container[30].j= 183
container[30].angle= 153
container[30].value= 255


container[31].bin= 0
container[31].i= 277
container[31].j= 173
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 277
container[32].j= 183
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 278
container[33].j= 174
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 278
container[34].j= 183
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 279
container[35].j= 174
container[35].angle= 315
container[35].value= 255


container[36].bin= 63
container[36].i= 279
container[36].j= 175
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 279
container[37].j= 183
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 280
container[38].j= 175
container[38].angle= 315
container[38].value= 255


container[39].bin= 63
container[39].i= 280
container[39].j= 176
container[39].angle= 315
container[39].value= 255


container[40].bin= 36
container[40].i= 280
container[40].j= 183
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 281
container[41].j= 176
container[41].angle= 315
container[41].value= 255


container[42].bin= 63
container[42].i= 281
container[42].j= 177
container[42].angle= 315
container[42].value= 255


container[43].bin= 36
container[43].i= 281
container[43].j= 183
container[43].angle= 180
container[43].value= 255


container[44].bin= 66
container[44].i= 282
container[44].j= 177
container[44].angle= 333
container[44].value= 255


container[45].bin= 36
container[45].i= 282
container[45].j= 183
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 283
container[46].j= 177
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 283
container[47].j= 183
container[47].angle= 180
container[47].value= 255


container[48].bin= 66
container[48].i= 284
container[48].j= 178
container[48].angle= 333
container[48].value= 255


container[49].bin= 41
container[49].i= 284
container[49].j= 183
container[49].angle= 206
container[49].value= 255


container[50].bin= 66
container[50].i= 285
container[50].j= 178
container[50].angle= 333
container[50].value= 255


container[51].bin= 36
container[51].i= 285
container[51].j= 183
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 286
container[52].j= 178
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 286
container[53].j= 183
container[53].angle= 180
container[53].value= 255


container[54].bin= 0
container[54].i= 287
container[54].j= 178
container[54].angle= 0
container[54].value= 255


container[55].bin= 41
container[55].i= 287
container[55].j= 183
container[55].angle= 206
container[55].value= 255


container[56].bin= 0
container[56].i= 288
container[56].j= 178
container[56].angle= 0
container[56].value= 255


container[57].bin= 41
container[57].i= 288
container[57].j= 182
container[57].angle= 206
container[57].value= 255


container[58].bin= 66
container[58].i= 289
container[58].j= 179
container[58].angle= 333
container[58].value= 255


container[59].bin= 41
container[59].i= 289
container[59].j= 182
container[59].angle= 206
container[59].value= 255


container[60].bin= 66
container[60].i= 290
container[60].j= 179
container[60].angle= 333
container[60].value= 255


container[61].bin= 0
container[61].i= 291
container[61].j= 179
container[61].angle= 0
container[61].value= 255


container[62].bin= 30
container[62].i= 291
container[62].j= 182
container[62].angle= 153
container[62].value= 255


container[63].bin= 0
container[63].i= 292
container[63].j= 179
container[63].angle= 0
container[63].value= 255


container[64].bin= 30
container[64].i= 292
container[64].j= 182
container[64].angle= 153
container[64].value= 255


container[65].bin= 0
container[65].i= 293
container[65].j= 179
container[65].angle= 0
container[65].value= 255


container[66].bin= 41
container[66].i= 293
container[66].j= 182
container[66].angle= 206
container[66].value= 255


container[67].bin= 0
container[67].i= 294
container[67].j= 179
container[67].angle= 0
container[67].value= 255


container[68].bin= 44
container[68].i= 294
container[68].j= 181
container[68].angle= 224
container[68].value= 255


container[69].bin= 44
container[69].i= 294
container[69].j= 182
container[69].angle= 224
container[69].value= 255


container[70].bin= 68
container[70].i= 295
container[70].j= 179
container[70].angle= 341
container[70].value= 255


container[71].bin= 44
container[71].i= 295
container[71].j= 181
container[71].angle= 224
container[71].value= 255


