container[0].bin= 18
container[0].i= 610
container[0].j= 186
container[0].angle= 90
container[0].value= 255


container[1].bin= 21
container[1].i= 610
container[1].j= 187
container[1].angle= 108
container[1].value= 255


container[2].bin= 8
container[2].i= 611
container[2].j= 185
container[2].angle= 44
container[2].value= 255


container[3].bin= 0
container[3].i= 612
container[3].j= 184
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 613
container[4].j= 184
container[4].angle= 0
container[4].value= 255


container[5].bin= 5
container[5].i= 614
container[5].j= 184
container[5].angle= 26
container[5].value= 255


container[6].bin= 5
container[6].i= 615
container[6].j= 184
container[6].angle= 26
container[6].value= 255


container[7].bin= 36
container[7].i= 615
container[7].j= 186
container[7].angle= 180
container[7].value= 255


container[8].bin= 66
container[8].i= 616
container[8].j= 184
container[8].angle= 333
container[8].value= 255


container[9].bin= 36
container[9].i= 616
container[9].j= 186
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 617
container[10].j= 184
container[10].angle= 333
container[10].value= 255


container[11].bin= 0
container[11].i= 618
container[11].j= 184
container[11].angle= 0
container[11].value= 255


container[12].bin= 63
container[12].i= 619
container[12].j= 185
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 619
container[13].j= 186
container[13].angle= 224
container[13].value= 255


