container[0].bin= 14
container[0].i= 435
container[0].j= 575
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 435
container[1].j= 576
container[1].angle= 108
container[1].value= 255


container[2].bin= 0
container[2].i= 436
container[2].j= 574
container[2].angle= 0
container[2].value= 255


container[3].bin= 8
container[3].i= 436
container[3].j= 579
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 436
container[4].j= 580
container[4].angle= 135
container[4].value= 255


container[5].bin= 57
container[5].i= 437
container[5].j= 575
container[5].angle= 288
container[5].value= 255


container[6].bin= 57
container[6].i= 437
container[6].j= 576
container[6].angle= 288
container[6].value= 255


container[7].bin= 63
container[7].i= 438
container[7].j= 576
container[7].angle= 315
container[7].value= 255


container[8].bin= 68
container[8].i= 438
container[8].j= 577
container[8].angle= 341
container[8].value= 255


container[9].bin= 30
container[9].i= 438
container[9].j= 581
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 439
container[10].j= 577
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 439
container[11].j= 581
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 440
container[12].j= 577
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 440
container[13].j= 581
container[13].angle= 180
container[13].value= 255


container[14].bin= 5
container[14].i= 441
container[14].j= 577
container[14].angle= 26
container[14].value= 255


container[15].bin= 36
container[15].i= 441
container[15].j= 581
container[15].angle= 180
container[15].value= 255


container[16].bin= 5
container[16].i= 442
container[16].j= 577
container[16].angle= 26
container[16].value= 255


container[17].bin= 36
container[17].i= 442
container[17].j= 581
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 443
container[18].j= 576
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 443
container[19].j= 581
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 444
container[20].j= 576
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 444
container[21].j= 582
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 445
container[22].j= 576
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 445
container[23].j= 583
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 446
container[24].j= 576
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 446
container[25].j= 583
container[25].angle= 180
container[25].value= 255


container[26].bin= 18
container[26].i= 447
container[26].j= 575
container[26].angle= 90
container[26].value= 255


container[27].bin= 8
container[27].i= 447
container[27].j= 576
container[27].angle= 44
container[27].value= 255


container[28].bin= 36
container[28].i= 447
container[28].j= 583
container[28].angle= 180
container[28].value= 255


container[29].bin= 8
container[29].i= 448
container[29].j= 574
container[29].angle= 44
container[29].value= 255


container[30].bin= 36
container[30].i= 448
container[30].j= 583
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 449
container[31].j= 573
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 449
container[32].j= 583
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 450
container[33].j= 573
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 450
container[34].j= 583
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 451
container[35].j= 573
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 451
container[36].j= 583
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 452
container[37].j= 573
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 452
container[38].j= 583
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 453
container[39].j= 573
container[39].angle= 0
container[39].value= 255


container[40].bin= 54
container[40].i= 453
container[40].j= 577
container[40].angle= 270
container[40].value= 255


container[41].bin= 27
container[41].i= 453
container[41].j= 584
container[41].angle= 135
container[41].value= 255


container[42].bin= 18
container[42].i= 453
container[42].j= 585
container[42].angle= 90
container[42].value= 255


container[43].bin= 18
container[43].i= 453
container[43].j= 586
container[43].angle= 90
container[43].value= 255


container[44].bin= 18
container[44].i= 453
container[44].j= 587
container[44].angle= 90
container[44].value= 255


container[45].bin= 0
container[45].i= 454
container[45].j= 573
container[45].angle= 0
container[45].value= 255


container[46].bin= 44
container[46].i= 454
container[46].j= 576
container[46].angle= 224
container[46].value= 255


container[47].bin= 63
container[47].i= 454
container[47].j= 578
container[47].angle= 315
container[47].value= 255


container[48].bin= 27
container[48].i= 454
container[48].j= 588
container[48].angle= 135
container[48].value= 255


container[49].bin= 0
container[49].i= 455
container[49].j= 573
container[49].angle= 0
container[49].value= 255


container[50].bin= 0
container[50].i= 455
container[50].j= 578
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 455
container[51].j= 588
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 456
container[52].j= 573
container[52].angle= 0
container[52].value= 255


container[53].bin= 66
container[53].i= 456
container[53].j= 579
container[53].angle= 333
container[53].value= 255


container[54].bin= 44
container[54].i= 456
container[54].j= 588
container[54].angle= 224
container[54].value= 255


container[55].bin= 0
container[55].i= 457
container[55].j= 573
container[55].angle= 0
container[55].value= 255


container[56].bin= 66
container[56].i= 457
container[56].j= 579
container[56].angle= 333
container[56].value= 255


container[57].bin= 44
container[57].i= 457
container[57].j= 587
container[57].angle= 224
container[57].value= 255


container[58].bin= 0
container[58].i= 458
container[58].j= 573
container[58].angle= 0
container[58].value= 255


container[59].bin= 0
container[59].i= 458
container[59].j= 579
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 458
container[60].j= 586
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 459
container[61].j= 574
container[61].angle= 315
container[61].value= 255


container[62].bin= 44
container[62].i= 459
container[62].j= 575
container[62].angle= 224
container[62].value= 255


container[63].bin= 0
container[63].i= 459
container[63].j= 579
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 459
container[64].j= 586
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 460
container[65].j= 579
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 460
container[66].j= 586
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 461
container[67].j= 579
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 461
container[68].j= 586
container[68].angle= 180
container[68].value= 255


container[69].bin= 63
container[69].i= 462
container[69].j= 580
container[69].angle= 315
container[69].value= 255


container[70].bin= 27
container[70].i= 462
container[70].j= 587
container[70].angle= 135
container[70].value= 255


container[71].bin= 63
container[71].i= 463
container[71].j= 581
container[71].angle= 315
container[71].value= 255


container[72].bin= 27
container[72].i= 463
container[72].j= 588
container[72].angle= 135
container[72].value= 255


container[73].bin= 0
container[73].i= 464
container[73].j= 581
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 464
container[74].j= 588
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 465
container[75].j= 581
container[75].angle= 0
container[75].value= 255


container[76].bin= 44
container[76].i= 465
container[76].j= 588
container[76].angle= 224
container[76].value= 255


container[77].bin= 0
container[77].i= 466
container[77].j= 581
container[77].angle= 0
container[77].value= 255


container[78].bin= 44
container[78].i= 466
container[78].j= 587
container[78].angle= 224
container[78].value= 255


container[79].bin= 0
container[79].i= 467
container[79].j= 581
container[79].angle= 0
container[79].value= 255


container[80].bin= 36
container[80].i= 467
container[80].j= 586
container[80].angle= 180
container[80].value= 255


container[81].bin= 63
container[81].i= 468
container[81].j= 582
container[81].angle= 315
container[81].value= 255


container[82].bin= 54
container[82].i= 468
container[82].j= 583
container[82].angle= 270
container[82].value= 255


container[83].bin= 54
container[83].i= 468
container[83].j= 584
container[83].angle= 270
container[83].value= 255


container[84].bin= 54
container[84].i= 468
container[84].j= 585
container[84].angle= 270
container[84].value= 255


container[85].bin= 44
container[85].i= 468
container[85].j= 586
container[85].angle= 224
container[85].value= 255


