container[0].bin= 18
container[0].i= 788
container[0].j= 220
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 788
container[1].j= 221
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 789
container[2].j= 219
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 789
container[3].j= 222
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 790
container[4].j= 218
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 790
container[5].j= 222
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 791
container[6].j= 218
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 791
container[7].j= 223
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 792
container[8].j= 218
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 792
container[9].j= 223
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 793
container[10].j= 218
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 793
container[11].j= 223
container[11].angle= 180
container[11].value= 255


container[12].bin= 66
container[12].i= 794
container[12].j= 219
container[12].angle= 333
container[12].value= 255


container[13].bin= 27
container[13].i= 794
container[13].j= 224
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 794
container[14].j= 225
container[14].angle= 90
container[14].value= 255


container[15].bin= 66
container[15].i= 795
container[15].j= 219
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 795
container[16].j= 226
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 796
container[17].j= 219
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 796
container[18].j= 226
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 797
container[19].j= 220
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 797
container[20].j= 227
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 797
container[21].j= 228
container[21].angle= 90
container[21].value= 255


container[22].bin= 18
container[22].i= 797
container[22].j= 229
container[22].angle= 90
container[22].value= 255


container[23].bin= 63
container[23].i= 798
container[23].j= 221
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 798
container[24].j= 230
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 799
container[25].j= 221
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 799
container[26].j= 230
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 800
container[27].j= 222
container[27].angle= 315
container[27].value= 255


container[28].bin= 54
container[28].i= 800
container[28].j= 229
container[28].angle= 270
container[28].value= 255


container[29].bin= 39
container[29].i= 800
container[29].j= 230
container[29].angle= 198
container[29].value= 255


container[30].bin= 63
container[30].i= 801
container[30].j= 223
container[30].angle= 315
container[30].value= 255


container[31].bin= 36
container[31].i= 801
container[31].j= 228
container[31].angle= 180
container[31].value= 255


container[32].bin= 44
container[32].i= 801
container[32].j= 230
container[32].angle= 224
container[32].value= 255


container[33].bin= 66
container[33].i= 802
container[33].j= 224
container[33].angle= 333
container[33].value= 255


container[34].bin= 63
container[34].i= 803
container[34].j= 224
container[34].angle= 315
container[34].value= 255


container[35].bin= 59
container[35].i= 803
container[35].j= 225
container[35].angle= 296
container[35].value= 255


container[36].bin= 63
container[36].i= 804
container[36].j= 226
container[36].angle= 315
container[36].value= 255


container[37].bin= 44
container[37].i= 804
container[37].j= 229
container[37].angle= 224
container[37].value= 255


container[38].bin= 66
container[38].i= 805
container[38].j= 227
container[38].angle= 333
container[38].value= 255


container[39].bin= 63
container[39].i= 806
container[39].j= 227
container[39].angle= 315
container[39].value= 255


