container[0].bin= 8
container[0].i= 59
container[0].j= 206
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 59
container[1].j= 207
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 59
container[2].j= 208
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 60
container[3].j= 206
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 60
container[4].j= 208
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 61
container[5].j= 205
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 61
container[6].j= 208
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 62
container[7].j= 205
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 62
container[8].j= 208
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 63
container[9].j= 205
container[9].angle= 26
container[9].value= 255


container[10].bin= 41
container[10].i= 63
container[10].j= 208
container[10].angle= 206
container[10].value= 255


container[11].bin= 5
container[11].i= 64
container[11].j= 204
container[11].angle= 26
container[11].value= 255


container[12].bin= 41
container[12].i= 64
container[12].j= 208
container[12].angle= 206
container[12].value= 255


container[13].bin= 5
container[13].i= 65
container[13].j= 204
container[13].angle= 26
container[13].value= 255


container[14].bin= 41
container[14].i= 65
container[14].j= 207
container[14].angle= 206
container[14].value= 255


container[15].bin= 63
container[15].i= 66
container[15].j= 204
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 66
container[16].j= 205
container[16].angle= 270
container[16].value= 255


container[17].bin= 48
container[17].i= 66
container[17].j= 206
container[17].angle= 243
container[17].value= 255


container[18].bin= 44
container[18].i= 66
container[18].j= 207
container[18].angle= 224
container[18].value= 255


