container[0].bin= 18
container[0].i= 839
container[0].j= 278
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 840
container[1].j= 277
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 840
container[2].j= 279
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 841
container[3].j= 276
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 841
container[4].j= 279
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 842
container[5].j= 276
container[5].angle= 0
container[5].value= 255


container[6].bin= 41
container[6].i= 842
container[6].j= 279
container[6].angle= 206
container[6].value= 255


container[7].bin= 0
container[7].i= 843
container[7].j= 276
container[7].angle= 0
container[7].value= 255


container[8].bin= 41
container[8].i= 843
container[8].j= 279
container[8].angle= 206
container[8].value= 255


container[9].bin= 66
container[9].i= 844
container[9].j= 277
container[9].angle= 333
container[9].value= 255


container[10].bin= 63
container[10].i= 845
container[10].j= 277
container[10].angle= 315
container[10].value= 255


