container[0].bin= 18
container[0].i= 896
container[0].j= 326
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 897
container[1].j= 325
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 897
container[2].j= 327
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 898
container[3].j= 325
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 898
container[4].j= 327
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 899
container[5].j= 325
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 899
container[6].j= 327
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 900
container[7].j= 325
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 900
container[8].j= 327
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 901
container[9].j= 325
container[9].angle= 0
container[9].value= 255


container[10].bin= 41
container[10].i= 901
container[10].j= 327
container[10].angle= 206
container[10].value= 255


container[11].bin= 68
container[11].i= 902
container[11].j= 325
container[11].angle= 341
container[11].value= 255


container[12].bin= 39
container[12].i= 902
container[12].j= 327
container[12].angle= 198
container[12].value= 255


