container[0].bin= 18
container[0].i= 230
container[0].j= 185
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 231
container[1].j= 184
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 231
container[2].j= 186
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 232
container[3].j= 184
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 232
container[4].j= 186
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 233
container[5].j= 184
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 233
container[6].j= 186
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 234
container[7].j= 183
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 234
container[8].j= 186
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 235
container[9].j= 183
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 235
container[10].j= 187
container[10].angle= 153
container[10].value= 255


container[11].bin= 5
container[11].i= 236
container[11].j= 183
container[11].angle= 26
container[11].value= 255


container[12].bin= 27
container[12].i= 236
container[12].j= 187
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 236
container[13].j= 188
container[13].angle= 135
container[13].value= 255


container[14].bin= 5
container[14].i= 237
container[14].j= 183
container[14].angle= 26
container[14].value= 255


container[15].bin= 30
container[15].i= 237
container[15].j= 188
container[15].angle= 153
container[15].value= 255


container[16].bin= 5
container[16].i= 238
container[16].j= 182
container[16].angle= 26
container[16].value= 255


container[17].bin= 36
container[17].i= 238
container[17].j= 188
container[17].angle= 180
container[17].value= 255


container[18].bin= 5
container[18].i= 239
container[18].j= 182
container[18].angle= 26
container[18].value= 255


container[19].bin= 30
container[19].i= 239
container[19].j= 189
container[19].angle= 153
container[19].value= 255


container[20].bin= 66
container[20].i= 240
container[20].j= 182
container[20].angle= 333
container[20].value= 255


container[21].bin= 30
container[21].i= 240
container[21].j= 189
container[21].angle= 153
container[21].value= 255


container[22].bin= 66
container[22].i= 241
container[22].j= 182
container[22].angle= 333
container[22].value= 255


container[23].bin= 41
container[23].i= 241
container[23].j= 189
container[23].angle= 206
container[23].value= 255


container[24].bin= 66
container[24].i= 242
container[24].j= 183
container[24].angle= 333
container[24].value= 255


container[25].bin= 48
container[25].i= 242
container[25].j= 188
container[25].angle= 243
container[25].value= 255


container[26].bin= 44
container[26].i= 242
container[26].j= 189
container[26].angle= 224
container[26].value= 255


container[27].bin= 66
container[27].i= 243
container[27].j= 183
container[27].angle= 333
container[27].value= 255


container[28].bin= 44
container[28].i= 243
container[28].j= 186
container[28].angle= 224
container[28].value= 255


container[29].bin= 48
container[29].i= 243
container[29].j= 187
container[29].angle= 243
container[29].value= 255


container[30].bin= 63
container[30].i= 244
container[30].j= 184
container[30].angle= 315
container[30].value= 255


container[31].bin= 48
container[31].i= 244
container[31].j= 185
container[31].angle= 243
container[31].value= 255


container[32].bin= 44
container[32].i= 244
container[32].j= 186
container[32].angle= 224
container[32].value= 255


