container[0].bin= 18
container[0].i= 363
container[0].j= 443
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 363
container[1].j= 444
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 363
container[2].j= 449
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 364
container[3].j= 442
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 364
container[4].j= 445
container[4].angle= 135
container[4].value= 255


container[5].bin= 8
container[5].i= 364
container[5].j= 448
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 364
container[6].j= 450
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 365
container[7].j= 441
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 365
container[8].j= 445
container[8].angle= 180
container[8].value= 255


container[9].bin= 36
container[9].i= 365
container[9].j= 450
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 366
container[10].j= 442
container[10].angle= 333
container[10].value= 255


container[11].bin= 54
container[11].i= 366
container[11].j= 443
container[11].angle= 270
container[11].value= 255


container[12].bin= 54
container[12].i= 366
container[12].j= 444
container[12].angle= 270
container[12].value= 255


container[13].bin= 27
container[13].i= 366
container[13].j= 446
container[13].angle= 135
container[13].value= 255


container[14].bin= 8
container[14].i= 366
container[14].j= 447
container[14].angle= 44
container[14].value= 255


container[15].bin= 44
container[15].i= 366
container[15].j= 450
container[15].angle= 224
container[15].value= 255


container[16].bin= 66
container[16].i= 367
container[16].j= 442
container[16].angle= 333
container[16].value= 255


container[17].bin= 44
container[17].i= 367
container[17].j= 449
container[17].angle= 224
container[17].value= 255


container[18].bin= 68
container[18].i= 368
container[18].j= 442
container[18].angle= 341
container[18].value= 255


container[19].bin= 63
container[19].i= 368
container[19].j= 443
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 368
container[20].j= 448
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 369
container[21].j= 444
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 369
container[22].j= 448
container[22].angle= 224
container[22].value= 255


container[23].bin= 0
container[23].i= 370
container[23].j= 444
container[23].angle= 0
container[23].value= 255


container[24].bin= 44
container[24].i= 370
container[24].j= 447
container[24].angle= 224
container[24].value= 255


container[25].bin= 0
container[25].i= 371
container[25].j= 444
container[25].angle= 0
container[25].value= 255


container[26].bin= 63
container[26].i= 372
container[26].j= 445
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 372
container[27].j= 446
container[27].angle= 224
container[27].value= 255


