container[0].bin= 18
container[0].i= 360
container[0].j= 218
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 361
container[1].j= 217
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 361
container[2].j= 219
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 361
container[3].j= 220
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 362
container[4].j= 216
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 362
container[5].j= 220
container[5].angle= 153
container[5].value= 255


container[6].bin= 63
container[6].i= 363
container[6].j= 217
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 363
container[7].j= 218
container[7].angle= 270
container[7].value= 255


container[8].bin= 54
container[8].i= 363
container[8].j= 219
container[8].angle= 270
container[8].value= 255


container[9].bin= 44
container[9].i= 363
container[9].j= 220
container[9].angle= 224
container[9].value= 255


