container[0].bin= 18
container[0].i= 483
container[0].j= 130
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 483
container[1].j= 135
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 484
container[2].j= 129
container[2].angle= 18
container[2].value= 255


container[3].bin= 32
container[3].i= 484
container[3].j= 131
container[3].angle= 161
container[3].value= 255


container[4].bin= 3
container[4].i= 484
container[4].j= 134
container[4].angle= 18
container[4].value= 255


container[5].bin= 32
container[5].i= 484
container[5].j= 136
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 485
container[6].j= 129
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 485
container[7].j= 131
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 485
container[8].j= 134
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 485
container[9].j= 136
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 486
container[10].j= 129
container[10].angle= 26
container[10].value= 255


container[11].bin= 36
container[11].i= 486
container[11].j= 131
container[11].angle= 180
container[11].value= 255


container[12].bin= 5
container[12].i= 486
container[12].j= 134
container[12].angle= 26
container[12].value= 255


container[13].bin= 18
container[13].i= 486
container[13].j= 135
container[13].angle= 90
container[13].value= 255


container[14].bin= 30
container[14].i= 486
container[14].j= 136
container[14].angle= 153
container[14].value= 255


container[15].bin= 5
container[15].i= 487
container[15].j= 129
container[15].angle= 26
container[15].value= 255


container[16].bin= 5
container[16].i= 487
container[16].j= 134
container[16].angle= 26
container[16].value= 255


container[17].bin= 30
container[17].i= 487
container[17].j= 136
container[17].angle= 153
container[17].value= 255


container[18].bin= 0
container[18].i= 488
container[18].j= 128
container[18].angle= 0
container[18].value= 255


container[19].bin= 0
container[19].i= 488
container[19].j= 133
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 488
container[20].j= 136
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 489
container[21].j= 128
container[21].angle= 0
container[21].value= 255


container[22].bin= 27
container[22].i= 489
container[22].j= 131
container[22].angle= 135
container[22].value= 255


container[23].bin= 18
container[23].i= 489
container[23].j= 132
container[23].angle= 90
container[23].value= 255


container[24].bin= 54
container[24].i= 489
container[24].j= 135
container[24].angle= 270
container[24].value= 255


container[25].bin= 44
container[25].i= 489
container[25].j= 136
container[25].angle= 224
container[25].value= 255


container[26].bin= 66
container[26].i= 490
container[26].j= 129
container[26].angle= 333
container[26].value= 255


container[27].bin= 66
container[27].i= 491
container[27].j= 129
container[27].angle= 333
container[27].value= 255


container[28].bin= 36
container[28].i= 491
container[28].j= 133
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 492
container[29].j= 130
container[29].angle= 315
container[29].value= 255


container[30].bin= 57
container[30].i= 492
container[30].j= 131
container[30].angle= 288
container[30].value= 255


container[31].bin= 54
container[31].i= 492
container[31].j= 132
container[31].angle= 270
container[31].value= 255


container[32].bin= 41
container[32].i= 492
container[32].j= 133
container[32].angle= 206
container[32].value= 255


container[33].bin= 41
container[33].i= 493
container[33].j= 133
container[33].angle= 206
container[33].value= 255


container[34].bin= 3
container[34].i= 494
container[34].j= 130
container[34].angle= 18
container[34].value= 255


container[35].bin= 68
container[35].i= 495
container[35].j= 130
container[35].angle= 341
container[35].value= 255


container[36].bin= 44
container[36].i= 495
container[36].j= 132
container[36].angle= 224
container[36].value= 255


