container[0].bin= 14
container[0].i= 686
container[0].j= 277
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 686
container[1].j= 278
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 687
container[2].j= 277
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 688
container[3].j= 277
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 688
container[4].j= 279
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 689
container[5].j= 277
container[5].angle= 26
container[5].value= 255


container[6].bin= 0
container[6].i= 690
container[6].j= 276
container[6].angle= 0
container[6].value= 255


container[7].bin= 66
container[7].i= 691
container[7].j= 277
container[7].angle= 333
container[7].value= 255


container[8].bin= 30
container[8].i= 691
container[8].j= 279
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 692
container[9].j= 277
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 692
container[10].j= 279
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 693
container[11].j= 277
container[11].angle= 0
container[11].value= 255


container[12].bin= 63
container[12].i= 694
container[12].j= 278
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 694
container[13].j= 279
container[13].angle= 224
container[13].value= 255


