container[0].bin= 18
container[0].i= 821
container[0].j= 204
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 821
container[1].j= 207
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 822
container[2].j= 203
container[2].angle= 18
container[2].value= 255


container[3].bin= 32
container[3].i= 822
container[3].j= 205
container[3].angle= 161
container[3].value= 255


container[4].bin= 32
container[4].i= 822
container[4].j= 208
container[4].angle= 161
container[4].value= 255


container[5].bin= 0
container[5].i= 823
container[5].j= 203
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 823
container[6].j= 205
container[6].angle= 180
container[6].value= 255


container[7].bin= 36
container[7].i= 823
container[7].j= 208
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 824
container[8].j= 203
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 824
container[9].j= 205
container[9].angle= 135
container[9].value= 255


container[10].bin= 8
container[10].i= 824
container[10].j= 206
container[10].angle= 44
container[10].value= 255


container[11].bin= 36
container[11].i= 824
container[11].j= 208
container[11].angle= 180
container[11].value= 255


container[12].bin= 5
container[12].i= 825
container[12].j= 203
container[12].angle= 26
container[12].value= 255


container[13].bin= 0
container[13].i= 826
container[13].j= 203
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 826
container[14].j= 207
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 827
container[15].j= 203
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 827
container[16].j= 208
container[16].angle= 135
container[16].value= 255


container[17].bin= 18
container[17].i= 827
container[17].j= 209
container[17].angle= 90
container[17].value= 255


container[18].bin= 0
container[18].i= 828
container[18].j= 203
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 828
container[19].j= 210
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 829
container[20].j= 203
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 829
container[21].j= 210
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 830
container[22].j= 203
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 830
container[23].j= 211
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 831
container[24].j= 203
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 831
container[25].j= 212
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 832
container[26].j= 203
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 832
container[27].j= 212
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 833
container[28].j= 204
container[28].angle= 315
container[28].value= 255


container[29].bin= 54
container[29].i= 833
container[29].j= 205
container[29].angle= 270
container[29].value= 255


container[30].bin= 27
container[30].i= 833
container[30].j= 213
container[30].angle= 135
container[30].value= 255


container[31].bin= 63
container[31].i= 834
container[31].j= 206
container[31].angle= 315
container[31].value= 255


container[32].bin= 23
container[32].i= 834
container[32].j= 214
container[32].angle= 116
container[32].value= 255


container[33].bin= 27
container[33].i= 834
container[33].j= 215
container[33].angle= 135
container[33].value= 255


container[34].bin= 0
container[34].i= 835
container[34].j= 206
container[34].angle= 0
container[34].value= 255


container[35].bin= 30
container[35].i= 835
container[35].j= 215
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 836
container[36].j= 207
container[36].angle= 315
container[36].value= 255


container[37].bin= 54
container[37].i= 836
container[37].j= 208
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 836
container[38].j= 209
container[38].angle= 270
container[38].value= 255


container[39].bin= 36
container[39].i= 836
container[39].j= 215
container[39].angle= 180
container[39].value= 255


container[40].bin= 63
container[40].i= 837
container[40].j= 210
container[40].angle= 315
container[40].value= 255


container[41].bin= 36
container[41].i= 837
container[41].j= 215
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 838
container[42].j= 210
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 838
container[43].j= 215
container[43].angle= 180
container[43].value= 255


container[44].bin= 66
container[44].i= 839
container[44].j= 211
container[44].angle= 333
container[44].value= 255


container[45].bin= 27
container[45].i= 839
container[45].j= 216
container[45].angle= 135
container[45].value= 255


container[46].bin= 66
container[46].i= 840
container[46].j= 211
container[46].angle= 333
container[46].value= 255


container[47].bin= 27
container[47].i= 840
container[47].j= 217
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 841
container[48].j= 211
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 841
container[49].j= 217
container[49].angle= 180
container[49].value= 255


container[50].bin= 63
container[50].i= 842
container[50].j= 212
container[50].angle= 315
container[50].value= 255


container[51].bin= 54
container[51].i= 842
container[51].j= 213
container[51].angle= 270
container[51].value= 255


container[52].bin= 54
container[52].i= 842
container[52].j= 214
container[52].angle= 270
container[52].value= 255


container[53].bin= 54
container[53].i= 842
container[53].j= 215
container[53].angle= 270
container[53].value= 255


container[54].bin= 54
container[54].i= 842
container[54].j= 216
container[54].angle= 270
container[54].value= 255


container[55].bin= 44
container[55].i= 842
container[55].j= 217
container[55].angle= 224
container[55].value= 255


