container[0].bin= 18
container[0].i= 63
container[0].j= 326
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 64
container[1].j= 325
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 64
container[2].j= 327
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 65
container[3].j= 324
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 65
container[4].j= 327
container[4].angle= 180
container[4].value= 255


container[5].bin= 66
container[5].i= 66
container[5].j= 325
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 66
container[6].j= 328
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 66
container[7].j= 329
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 66
container[8].j= 330
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 66
container[9].j= 331
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 66
container[10].j= 332
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 66
container[11].j= 333
container[11].angle= 90
container[11].value= 255


container[12].bin= 66
container[12].i= 67
container[12].j= 325
container[12].angle= 333
container[12].value= 255


container[13].bin= 27
container[13].i= 67
container[13].j= 334
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 68
container[14].j= 325
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 68
container[15].j= 334
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 69
container[16].j= 326
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 69
container[17].j= 327
container[17].angle= 270
container[17].value= 255


container[18].bin= 54
container[18].i= 69
container[18].j= 328
container[18].angle= 270
container[18].value= 255


container[19].bin= 54
container[19].i= 69
container[19].j= 329
container[19].angle= 270
container[19].value= 255


container[20].bin= 27
container[20].i= 69
container[20].j= 335
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 69
container[21].j= 336
container[21].angle= 90
container[21].value= 255


container[22].bin= 63
container[22].i= 70
container[22].j= 330
container[22].angle= 315
container[22].value= 255


container[23].bin= 27
container[23].i= 70
container[23].j= 337
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 71
container[24].j= 330
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 71
container[25].j= 337
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 72
container[26].j= 331
container[26].angle= 315
container[26].value= 255


container[27].bin= 27
container[27].i= 72
container[27].j= 338
container[27].angle= 135
container[27].value= 255


container[28].bin= 18
container[28].i= 72
container[28].j= 339
container[28].angle= 90
container[28].value= 255


container[29].bin= 21
container[29].i= 72
container[29].j= 340
container[29].angle= 108
container[29].value= 255


container[30].bin= 63
container[30].i= 73
container[30].j= 332
container[30].angle= 315
container[30].value= 255


container[31].bin= 0
container[31].i= 74
container[31].j= 332
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 74
container[32].j= 340
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 75
container[33].j= 333
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 75
container[34].j= 340
container[34].angle= 135
container[34].value= 255


container[35].bin= 23
container[35].i= 75
container[35].j= 341
container[35].angle= 116
container[35].value= 255


container[36].bin= 18
container[36].i= 75
container[36].j= 342
container[36].angle= 90
container[36].value= 255


container[37].bin= 18
container[37].i= 75
container[37].j= 343
container[37].angle= 90
container[37].value= 255


container[38].bin= 66
container[38].i= 76
container[38].j= 333
container[38].angle= 333
container[38].value= 255


container[39].bin= 23
container[39].i= 76
container[39].j= 344
container[39].angle= 116
container[39].value= 255


container[40].bin= 27
container[40].i= 76
container[40].j= 345
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 77
container[41].j= 333
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 77
container[42].j= 345
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 78
container[43].j= 334
container[43].angle= 315
container[43].value= 255


container[44].bin= 32
container[44].i= 78
container[44].j= 345
container[44].angle= 161
container[44].value= 255


container[45].bin= 63
container[45].i= 79
container[45].j= 335
container[45].angle= 315
container[45].value= 255


container[46].bin= 23
container[46].i= 79
container[46].j= 346
container[46].angle= 116
container[46].value= 255


container[47].bin= 27
container[47].i= 79
container[47].j= 347
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 80
container[48].j= 335
container[48].angle= 0
container[48].value= 255


container[49].bin= 30
container[49].i= 80
container[49].j= 347
container[49].angle= 153
container[49].value= 255


container[50].bin= 63
container[50].i= 81
container[50].j= 336
container[50].angle= 315
container[50].value= 255


container[51].bin= 30
container[51].i= 81
container[51].j= 348
container[51].angle= 153
container[51].value= 255


container[52].bin= 63
container[52].i= 82
container[52].j= 337
container[52].angle= 315
container[52].value= 255


container[53].bin= 30
container[53].i= 82
container[53].j= 348
container[53].angle= 153
container[53].value= 255


container[54].bin= 0
container[54].i= 83
container[54].j= 337
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 83
container[55].j= 348
container[55].angle= 180
container[55].value= 255


container[56].bin= 66
container[56].i= 84
container[56].j= 338
container[56].angle= 333
container[56].value= 255


container[57].bin= 27
container[57].i= 84
container[57].j= 349
container[57].angle= 135
container[57].value= 255


container[58].bin= 66
container[58].i= 85
container[58].j= 338
container[58].angle= 333
container[58].value= 255


container[59].bin= 27
container[59].i= 85
container[59].j= 350
container[59].angle= 135
container[59].value= 255


container[60].bin= 0
container[60].i= 86
container[60].j= 338
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 86
container[61].j= 350
container[61].angle= 180
container[61].value= 255


container[62].bin= 63
container[62].i= 87
container[62].j= 339
container[62].angle= 315
container[62].value= 255


container[63].bin= 27
container[63].i= 87
container[63].j= 351
container[63].angle= 135
container[63].value= 255


container[64].bin= 18
container[64].i= 87
container[64].j= 352
container[64].angle= 90
container[64].value= 255


container[65].bin= 63
container[65].i= 88
container[65].j= 340
container[65].angle= 315
container[65].value= 255


container[66].bin= 23
container[66].i= 88
container[66].j= 353
container[66].angle= 116
container[66].value= 255


container[67].bin= 18
container[67].i= 88
container[67].j= 354
container[67].angle= 90
container[67].value= 255


container[68].bin= 21
container[68].i= 88
container[68].j= 355
container[68].angle= 108
container[68].value= 255


container[69].bin= 0
container[69].i= 89
container[69].j= 340
container[69].angle= 0
container[69].value= 255


container[70].bin= 32
container[70].i= 89
container[70].j= 355
container[70].angle= 161
container[70].value= 255


container[71].bin= 63
container[71].i= 90
container[71].j= 341
container[71].angle= 315
container[71].value= 255


container[72].bin= 54
container[72].i= 90
container[72].j= 342
container[72].angle= 270
container[72].value= 255


container[73].bin= 54
container[73].i= 90
container[73].j= 343
container[73].angle= 270
container[73].value= 255


container[74].bin= 54
container[74].i= 90
container[74].j= 344
container[74].angle= 270
container[74].value= 255


container[75].bin= 30
container[75].i= 90
container[75].j= 356
container[75].angle= 153
container[75].value= 255


container[76].bin= 59
container[76].i= 91
container[76].j= 345
container[76].angle= 296
container[76].value= 255


container[77].bin= 63
container[77].i= 91
container[77].j= 346
container[77].angle= 315
container[77].value= 255


container[78].bin= 27
container[78].i= 91
container[78].j= 356
container[78].angle= 135
container[78].value= 255


container[79].bin= 27
container[79].i= 91
container[79].j= 357
container[79].angle= 135
container[79].value= 255


container[80].bin= 0
container[80].i= 92
container[80].j= 346
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 92
container[81].j= 357
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 93
container[82].j= 346
container[82].angle= 0
container[82].value= 255


container[83].bin= 32
container[83].i= 93
container[83].j= 357
container[83].angle= 161
container[83].value= 255


container[84].bin= 21
container[84].i= 93
container[84].j= 358
container[84].angle= 108
container[84].value= 255


container[85].bin= 18
container[85].i= 93
container[85].j= 359
container[85].angle= 90
container[85].value= 255


container[86].bin= 18
container[86].i= 93
container[86].j= 360
container[86].angle= 90
container[86].value= 255


container[87].bin= 66
container[87].i= 94
container[87].j= 346
container[87].angle= 333
container[87].value= 255


container[88].bin= 27
container[88].i= 94
container[88].j= 361
container[88].angle= 135
container[88].value= 255


container[89].bin= 0
container[89].i= 95
container[89].j= 346
container[89].angle= 0
container[89].value= 255


container[90].bin= 36
container[90].i= 95
container[90].j= 361
container[90].angle= 180
container[90].value= 255


container[91].bin= 63
container[91].i= 96
container[91].j= 347
container[91].angle= 315
container[91].value= 255


container[92].bin= 54
container[92].i= 96
container[92].j= 348
container[92].angle= 270
container[92].value= 255


container[93].bin= 36
container[93].i= 96
container[93].j= 361
container[93].angle= 180
container[93].value= 255


container[94].bin= 63
container[94].i= 97
container[94].j= 349
container[94].angle= 315
container[94].value= 255


container[95].bin= 36
container[95].i= 97
container[95].j= 361
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 98
container[96].j= 349
container[96].angle= 0
container[96].value= 255


container[97].bin= 36
container[97].i= 98
container[97].j= 361
container[97].angle= 180
container[97].value= 255


container[98].bin= 63
container[98].i= 99
container[98].j= 350
container[98].angle= 315
container[98].value= 255


container[99].bin= 54
container[99].i= 99
container[99].j= 351
container[99].angle= 270
container[99].value= 255


container[100].bin= 30
container[100].i= 99
container[100].j= 362
container[100].angle= 153
container[100].value= 255


container[101].bin= 63
container[101].i= 100
container[101].j= 352
container[101].angle= 315
container[101].value= 255


container[102].bin= 27
container[102].i= 100
container[102].j= 362
container[102].angle= 135
container[102].value= 255


container[103].bin= 27
container[103].i= 100
container[103].j= 363
container[103].angle= 135
container[103].value= 255


container[104].bin= 66
container[104].i= 101
container[104].j= 353
container[104].angle= 333
container[104].value= 255


container[105].bin= 36
container[105].i= 101
container[105].j= 363
container[105].angle= 180
container[105].value= 255


container[106].bin= 44
container[106].i= 102
container[106].j= 362
container[106].angle= 224
container[106].value= 255


container[107].bin= 44
container[107].i= 102
container[107].j= 363
container[107].angle= 224
container[107].value= 255


container[108].bin= 8
container[108].i= 103
container[108].j= 352
container[108].angle= 44
container[108].value= 255


container[109].bin= 41
container[109].i= 103
container[109].j= 362
container[109].angle= 206
container[109].value= 255


container[110].bin= 0
container[110].i= 104
container[110].j= 351
container[110].angle= 0
container[110].value= 255


container[111].bin= 36
container[111].i= 104
container[111].j= 361
container[111].angle= 180
container[111].value= 255


container[112].bin= 63
container[112].i= 105
container[112].j= 352
container[112].angle= 315
container[112].value= 255


container[113].bin= 36
container[113].i= 105
container[113].j= 361
container[113].angle= 180
container[113].value= 255


container[114].bin= 63
container[114].i= 106
container[114].j= 353
container[114].angle= 315
container[114].value= 255


container[115].bin= 36
container[115].i= 106
container[115].j= 361
container[115].angle= 180
container[115].value= 255


container[116].bin= 0
container[116].i= 107
container[116].j= 353
container[116].angle= 0
container[116].value= 255


container[117].bin= 36
container[117].i= 107
container[117].j= 361
container[117].angle= 180
container[117].value= 255


container[118].bin= 0
container[118].i= 108
container[118].j= 353
container[118].angle= 0
container[118].value= 255


container[119].bin= 36
container[119].i= 108
container[119].j= 361
container[119].angle= 180
container[119].value= 255


container[120].bin= 0
container[120].i= 109
container[120].j= 353
container[120].angle= 0
container[120].value= 255


container[121].bin= 36
container[121].i= 109
container[121].j= 361
container[121].angle= 180
container[121].value= 255


container[122].bin= 0
container[122].i= 110
container[122].j= 353
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 110
container[123].j= 361
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 111
container[124].j= 353
container[124].angle= 0
container[124].value= 255


container[125].bin= 27
container[125].i= 111
container[125].j= 362
container[125].angle= 135
container[125].value= 255


container[126].bin= 0
container[126].i= 112
container[126].j= 353
container[126].angle= 0
container[126].value= 255


container[127].bin= 27
container[127].i= 112
container[127].j= 363
container[127].angle= 135
container[127].value= 255


container[128].bin= 0
container[128].i= 113
container[128].j= 353
container[128].angle= 0
container[128].value= 255


container[129].bin= 36
container[129].i= 113
container[129].j= 363
container[129].angle= 180
container[129].value= 255


container[130].bin= 66
container[130].i= 114
container[130].j= 354
container[130].angle= 333
container[130].value= 255


container[131].bin= 36
container[131].i= 114
container[131].j= 363
container[131].angle= 180
container[131].value= 255


container[132].bin= 66
container[132].i= 115
container[132].j= 354
container[132].angle= 333
container[132].value= 255


container[133].bin= 36
container[133].i= 115
container[133].j= 363
container[133].angle= 180
container[133].value= 255


container[134].bin= 0
container[134].i= 116
container[134].j= 354
container[134].angle= 0
container[134].value= 255


container[135].bin= 36
container[135].i= 116
container[135].j= 363
container[135].angle= 180
container[135].value= 255


container[136].bin= 63
container[136].i= 117
container[136].j= 355
container[136].angle= 315
container[136].value= 255


container[137].bin= 36
container[137].i= 117
container[137].j= 363
container[137].angle= 180
container[137].value= 255


container[138].bin= 63
container[138].i= 118
container[138].j= 356
container[138].angle= 315
container[138].value= 255


container[139].bin= 36
container[139].i= 118
container[139].j= 363
container[139].angle= 180
container[139].value= 255


container[140].bin= 0
container[140].i= 119
container[140].j= 356
container[140].angle= 0
container[140].value= 255


container[141].bin= 36
container[141].i= 119
container[141].j= 363
container[141].angle= 180
container[141].value= 255


container[142].bin= 63
container[142].i= 120
container[142].j= 357
container[142].angle= 315
container[142].value= 255


container[143].bin= 54
container[143].i= 120
container[143].j= 358
container[143].angle= 270
container[143].value= 255


container[144].bin= 44
container[144].i= 120
container[144].j= 363
container[144].angle= 224
container[144].value= 255


container[145].bin= 63
container[145].i= 121
container[145].j= 359
container[145].angle= 315
container[145].value= 255


container[146].bin= 44
container[146].i= 121
container[146].j= 362
container[146].angle= 224
container[146].value= 255


container[147].bin= 0
container[147].i= 122
container[147].j= 359
container[147].angle= 0
container[147].value= 255


container[148].bin= 63
container[148].i= 123
container[148].j= 360
container[148].angle= 315
container[148].value= 255


container[149].bin= 44
container[149].i= 123
container[149].j= 361
container[149].angle= 224
container[149].value= 255


