container[0].bin= 14
container[0].i= 616
container[0].j= 511
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 616
container[1].j= 512
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 617
container[2].j= 510
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 618
container[3].j= 510
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 618
container[4].j= 512
container[4].angle= 206
container[4].value= 255


container[5].bin= 68
container[5].i= 619
container[5].j= 510
container[5].angle= 341
container[5].value= 255


container[6].bin= 39
container[6].i= 619
container[6].j= 512
container[6].angle= 198
container[6].value= 255


