container[0].bin= 8
container[0].i= 174
container[0].j= 224
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 174
container[1].j= 225
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 174
container[2].j= 226
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 175
container[3].j= 223
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 175
container[4].j= 226
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 175
container[5].j= 227
container[5].angle= 135
container[5].value= 255


container[6].bin= 66
container[6].i= 176
container[6].j= 224
container[6].angle= 333
container[6].value= 255


container[7].bin= 30
container[7].i= 176
container[7].j= 227
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 177
container[8].j= 224
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 177
container[9].j= 228
container[9].angle= 153
container[9].value= 255


container[10].bin= 66
container[10].i= 178
container[10].j= 225
container[10].angle= 333
container[10].value= 255


container[11].bin= 36
container[11].i= 178
container[11].j= 228
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 179
container[12].j= 225
container[12].angle= 315
container[12].value= 255


container[13].bin= 59
container[13].i= 179
container[13].j= 226
container[13].angle= 296
container[13].value= 255


container[14].bin= 48
container[14].i= 179
container[14].j= 227
container[14].angle= 243
container[14].value= 255


container[15].bin= 44
container[15].i= 179
container[15].j= 228
container[15].angle= 224
container[15].value= 255


