container[0].bin= 18
container[0].i= 4
container[0].j= 177
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 5
container[1].j= 176
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 5
container[2].j= 178
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 5
container[3].j= 179
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 6
container[4].j= 175
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 6
container[5].j= 179
container[5].angle= 135
container[5].value= 255


container[6].bin= 27
container[6].i= 6
container[6].j= 180
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 7
container[7].j= 175
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 7
container[8].j= 180
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 8
container[9].j= 176
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 8
container[10].j= 180
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 9
container[11].j= 176
container[11].angle= 315
container[11].value= 255


container[12].bin= 63
container[12].i= 9
container[12].j= 177
container[12].angle= 315
container[12].value= 255


container[13].bin= 30
container[13].i= 9
container[13].j= 181
container[13].angle= 153
container[13].value= 255


container[14].bin= 63
container[14].i= 10
container[14].j= 177
container[14].angle= 315
container[14].value= 255


container[15].bin= 63
container[15].i= 10
container[15].j= 178
container[15].angle= 315
container[15].value= 255


container[16].bin= 63
container[16].i= 11
container[16].j= 178
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 11
container[17].j= 179
container[17].angle= 270
container[17].value= 255


container[18].bin= 48
container[18].i= 11
container[18].j= 180
container[18].angle= 243
container[18].value= 255


