container[0].bin= 18
container[0].i= 51
container[0].j= 299
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 52
container[1].j= 298
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 52
container[2].j= 300
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 53
container[3].j= 298
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 53
container[4].j= 300
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 54
container[5].j= 298
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 54
container[6].j= 300
container[6].angle= 153
container[6].value= 255


container[7].bin= 68
container[7].i= 55
container[7].j= 298
container[7].angle= 341
container[7].value= 255


