container[0].bin= 18
container[0].i= 84
container[0].j= 101
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 84
container[1].j= 102
container[1].angle= 90
container[1].value= 255


container[2].bin= 12
container[2].i= 84
container[2].j= 103
container[2].angle= 63
container[2].value= 255


container[3].bin= 12
container[3].i= 84
container[3].j= 104
container[3].angle= 63
container[3].value= 255


container[4].bin= 27
container[4].i= 84
container[4].j= 105
container[4].angle= 135
container[4].value= 255


container[5].bin= 8
container[5].i= 85
container[5].j= 100
container[5].angle= 44
container[5].value= 255


container[6].bin= 30
container[6].i= 85
container[6].j= 106
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 86
container[7].j= 99
container[7].angle= 26
container[7].value= 255


container[8].bin= 27
container[8].i= 86
container[8].j= 106
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 86
container[9].j= 107
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 87
container[10].j= 99
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 87
container[11].j= 107
container[11].angle= 153
container[11].value= 255


container[12].bin= 66
container[12].i= 88
container[12].j= 99
container[12].angle= 333
container[12].value= 255


container[13].bin= 30
container[13].i= 88
container[13].j= 108
container[13].angle= 153
container[13].value= 255


container[14].bin= 66
container[14].i= 89
container[14].j= 100
container[14].angle= 333
container[14].value= 255


container[15].bin= 27
container[15].i= 89
container[15].j= 108
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 89
container[16].j= 109
container[16].angle= 135
container[16].value= 255


container[17].bin= 66
container[17].i= 90
container[17].j= 100
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 90
container[18].j= 109
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 91
container[19].j= 101
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 91
container[20].j= 110
container[20].angle= 153
container[20].value= 255


container[21].bin= 63
container[21].i= 92
container[21].j= 101
container[21].angle= 315
container[21].value= 255


container[22].bin= 63
container[22].i= 92
container[22].j= 102
container[22].angle= 315
container[22].value= 255


container[23].bin= 30
container[23].i= 92
container[23].j= 110
container[23].angle= 153
container[23].value= 255


container[24].bin= 66
container[24].i= 93
container[24].j= 102
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 93
container[25].j= 110
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 94
container[26].j= 103
container[26].angle= 315
container[26].value= 255


container[27].bin= 30
container[27].i= 94
container[27].j= 111
container[27].angle= 153
container[27].value= 255


container[28].bin= 59
container[28].i= 95
container[28].j= 104
container[28].angle= 296
container[28].value= 255


container[29].bin= 63
container[29].i= 95
container[29].j= 105
container[29].angle= 315
container[29].value= 255


container[30].bin= 30
container[30].i= 95
container[30].j= 111
container[30].angle= 153
container[30].value= 255


container[31].bin= 63
container[31].i= 96
container[31].j= 105
container[31].angle= 315
container[31].value= 255


container[32].bin= 63
container[32].i= 96
container[32].j= 106
container[32].angle= 315
container[32].value= 255


container[33].bin= 36
container[33].i= 96
container[33].j= 111
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 97
container[34].j= 106
container[34].angle= 315
container[34].value= 255


container[35].bin= 63
container[35].i= 97
container[35].j= 107
container[35].angle= 315
container[35].value= 255


container[36].bin= 36
container[36].i= 97
container[36].j= 111
container[36].angle= 180
container[36].value= 255


container[37].bin= 63
container[37].i= 98
container[37].j= 107
container[37].angle= 315
container[37].value= 255


container[38].bin= 63
container[38].i= 98
container[38].j= 108
container[38].angle= 315
container[38].value= 255


container[39].bin= 36
container[39].i= 98
container[39].j= 111
container[39].angle= 180
container[39].value= 255


container[40].bin= 66
container[40].i= 99
container[40].j= 108
container[40].angle= 333
container[40].value= 255


container[41].bin= 36
container[41].i= 99
container[41].j= 111
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 100
container[42].j= 108
container[42].angle= 0
container[42].value= 255


container[43].bin= 30
container[43].i= 100
container[43].j= 112
container[43].angle= 153
container[43].value= 255


container[44].bin= 0
container[44].i= 101
container[44].j= 108
container[44].angle= 0
container[44].value= 255


container[45].bin= 30
container[45].i= 101
container[45].j= 112
container[45].angle= 153
container[45].value= 255


container[46].bin= 0
container[46].i= 102
container[46].j= 108
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 102
container[47].j= 112
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 103
container[48].j= 108
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 103
container[49].j= 112
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 104
container[50].j= 108
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 104
container[51].j= 112
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 105
container[52].j= 108
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 105
container[53].j= 113
container[53].angle= 153
container[53].value= 255


container[54].bin= 0
container[54].i= 106
container[54].j= 108
container[54].angle= 0
container[54].value= 255


container[55].bin= 30
container[55].i= 106
container[55].j= 113
container[55].angle= 153
container[55].value= 255


container[56].bin= 66
container[56].i= 107
container[56].j= 109
container[56].angle= 333
container[56].value= 255


container[57].bin= 30
container[57].i= 107
container[57].j= 114
container[57].angle= 153
container[57].value= 255


container[58].bin= 66
container[58].i= 108
container[58].j= 109
container[58].angle= 333
container[58].value= 255


container[59].bin= 30
container[59].i= 108
container[59].j= 114
container[59].angle= 153
container[59].value= 255


container[60].bin= 0
container[60].i= 109
container[60].j= 109
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 109
container[61].j= 114
container[61].angle= 180
container[61].value= 255


container[62].bin= 0
container[62].i= 110
container[62].j= 109
container[62].angle= 0
container[62].value= 255


container[63].bin= 30
container[63].i= 110
container[63].j= 115
container[63].angle= 153
container[63].value= 255


container[64].bin= 66
container[64].i= 111
container[64].j= 110
container[64].angle= 333
container[64].value= 255


container[65].bin= 30
container[65].i= 111
container[65].j= 115
container[65].angle= 153
container[65].value= 255


container[66].bin= 66
container[66].i= 112
container[66].j= 110
container[66].angle= 333
container[66].value= 255


container[67].bin= 30
container[67].i= 112
container[67].j= 116
container[67].angle= 153
container[67].value= 255


container[68].bin= 66
container[68].i= 113
container[68].j= 111
container[68].angle= 333
container[68].value= 255


container[69].bin= 30
container[69].i= 113
container[69].j= 116
container[69].angle= 153
container[69].value= 255


container[70].bin= 63
container[70].i= 114
container[70].j= 111
container[70].angle= 315
container[70].value= 255


container[71].bin= 63
container[71].i= 114
container[71].j= 112
container[71].angle= 315
container[71].value= 255


container[72].bin= 36
container[72].i= 114
container[72].j= 116
container[72].angle= 180
container[72].value= 255


container[73].bin= 66
container[73].i= 115
container[73].j= 112
container[73].angle= 333
container[73].value= 255


container[74].bin= 30
container[74].i= 115
container[74].j= 117
container[74].angle= 153
container[74].value= 255


container[75].bin= 66
container[75].i= 116
container[75].j= 113
container[75].angle= 333
container[75].value= 255


container[76].bin= 27
container[76].i= 116
container[76].j= 117
container[76].angle= 135
container[76].value= 255


container[77].bin= 27
container[77].i= 116
container[77].j= 118
container[77].angle= 135
container[77].value= 255


container[78].bin= 63
container[78].i= 117
container[78].j= 113
container[78].angle= 315
container[78].value= 255


container[79].bin= 63
container[79].i= 117
container[79].j= 114
container[79].angle= 315
container[79].value= 255


container[80].bin= 30
container[80].i= 117
container[80].j= 118
container[80].angle= 153
container[80].value= 255


container[81].bin= 66
container[81].i= 118
container[81].j= 114
container[81].angle= 333
container[81].value= 255


container[82].bin= 30
container[82].i= 118
container[82].j= 119
container[82].angle= 153
container[82].value= 255


container[83].bin= 66
container[83].i= 119
container[83].j= 115
container[83].angle= 333
container[83].value= 255


container[84].bin= 30
container[84].i= 119
container[84].j= 119
container[84].angle= 153
container[84].value= 255


container[85].bin= 66
container[85].i= 120
container[85].j= 115
container[85].angle= 333
container[85].value= 255


container[86].bin= 36
container[86].i= 120
container[86].j= 119
container[86].angle= 180
container[86].value= 255


container[87].bin= 66
container[87].i= 121
container[87].j= 116
container[87].angle= 333
container[87].value= 255


container[88].bin= 36
container[88].i= 121
container[88].j= 119
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 122
container[89].j= 116
container[89].angle= 315
container[89].value= 255


container[90].bin= 63
container[90].i= 122
container[90].j= 117
container[90].angle= 315
container[90].value= 255


container[91].bin= 36
container[91].i= 122
container[91].j= 119
container[91].angle= 180
container[91].value= 255


container[92].bin= 63
container[92].i= 123
container[92].j= 117
container[92].angle= 315
container[92].value= 255


container[93].bin= 63
container[93].i= 123
container[93].j= 118
container[93].angle= 315
container[93].value= 255


container[94].bin= 63
container[94].i= 124
container[94].j= 118
container[94].angle= 315
container[94].value= 255


