container[0].bin= 8
container[0].i= 870
container[0].j= 333
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 870
container[1].j= 334
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 871
container[2].j= 332
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 872
container[3].j= 332
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 872
container[4].j= 335
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 873
container[5].j= 332
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 873
container[6].j= 336
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 874
container[7].j= 332
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 874
container[8].j= 336
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 875
container[9].j= 333
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 875
container[10].j= 337
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 876
container[11].j= 333
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 876
container[12].j= 337
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 877
container[13].j= 333
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 877
container[14].j= 337
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 878
container[15].j= 333
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 878
container[16].j= 338
container[16].angle= 135
container[16].value= 255


container[17].bin= 68
container[17].i= 879
container[17].j= 333
container[17].angle= 341
container[17].value= 255


container[18].bin= 57
container[18].i= 879
container[18].j= 335
container[18].angle= 288
container[18].value= 255


container[19].bin= 27
container[19].i= 879
container[19].j= 339
container[19].angle= 135
container[19].value= 255


container[20].bin= 68
container[20].i= 880
container[20].j= 335
container[20].angle= 341
container[20].value= 255


container[21].bin= 36
container[21].i= 880
container[21].j= 339
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 881
container[22].j= 336
container[22].angle= 315
container[22].value= 255


container[23].bin= 54
container[23].i= 881
container[23].j= 337
container[23].angle= 270
container[23].value= 255


container[24].bin= 54
container[24].i= 881
container[24].j= 338
container[24].angle= 270
container[24].value= 255


container[25].bin= 44
container[25].i= 881
container[25].j= 339
container[25].angle= 224
container[25].value= 255


