container[0].bin= 18
container[0].i= 426
container[0].j= 559
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 427
container[1].j= 558
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 427
container[2].j= 560
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 428
container[3].j= 558
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 428
container[4].j= 560
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 429
container[5].j= 558
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 429
container[6].j= 560
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 429
container[7].j= 561
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 429
container[8].j= 562
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 429
container[9].j= 563
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 429
container[10].j= 564
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 429
container[11].j= 565
container[11].angle= 90
container[11].value= 255


container[12].bin= 18
container[12].i= 429
container[12].j= 566
container[12].angle= 90
container[12].value= 255


container[13].bin= 21
container[13].i= 429
container[13].j= 567
container[13].angle= 108
container[13].value= 255


container[14].bin= 0
container[14].i= 430
container[14].j= 558
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 430
container[15].j= 568
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 431
container[16].j= 558
container[16].angle= 0
container[16].value= 255


container[17].bin= 63
container[17].i= 432
container[17].j= 559
container[17].angle= 315
container[17].value= 255


container[18].bin= 39
container[18].i= 432
container[18].j= 565
container[18].angle= 198
container[18].value= 255


container[19].bin= 44
container[19].i= 432
container[19].j= 566
container[19].angle= 224
container[19].value= 255


container[20].bin= 44
container[20].i= 432
container[20].j= 568
container[20].angle= 224
container[20].value= 255


container[21].bin= 63
container[21].i= 433
container[21].j= 560
container[21].angle= 315
container[21].value= 255


container[22].bin= 36
container[22].i= 433
container[22].j= 565
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 434
container[23].j= 560
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 434
container[24].j= 565
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 435
container[25].j= 560
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 435
container[26].j= 565
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 436
container[27].j= 560
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 436
container[28].j= 565
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 437
container[29].j= 560
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 437
container[30].j= 565
container[30].angle= 180
container[30].value= 255


container[31].bin= 66
container[31].i= 438
container[31].j= 561
container[31].angle= 333
container[31].value= 255


container[32].bin= 27
container[32].i= 438
container[32].j= 566
container[32].angle= 135
container[32].value= 255


container[33].bin= 66
container[33].i= 439
container[33].j= 561
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 439
container[34].j= 567
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 440
container[35].j= 561
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 440
container[36].j= 567
container[36].angle= 180
container[36].value= 255


container[37].bin= 63
container[37].i= 441
container[37].j= 562
container[37].angle= 315
container[37].value= 255


container[38].bin= 44
container[38].i= 441
container[38].j= 567
container[38].angle= 224
container[38].value= 255


container[39].bin= 63
container[39].i= 442
container[39].j= 563
container[39].angle= 315
container[39].value= 255


container[40].bin= 44
container[40].i= 442
container[40].j= 566
container[40].angle= 224
container[40].value= 255


container[41].bin= 0
container[41].i= 443
container[41].j= 563
container[41].angle= 0
container[41].value= 255


container[42].bin= 63
container[42].i= 444
container[42].j= 564
container[42].angle= 315
container[42].value= 255


container[43].bin= 44
container[43].i= 444
container[43].j= 565
container[43].angle= 224
container[43].value= 255


