container[0].bin= 18
container[0].i= 902
container[0].j= 440
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 903
container[1].j= 439
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 903
container[2].j= 441
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 904
container[3].j= 438
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 904
container[4].j= 441
container[4].angle= 180
container[4].value= 255


container[5].bin= 66
container[5].i= 905
container[5].j= 439
container[5].angle= 333
container[5].value= 255


container[6].bin= 36
container[6].i= 905
container[6].j= 441
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 906
container[7].j= 439
container[7].angle= 333
container[7].value= 255


container[8].bin= 0
container[8].i= 907
container[8].j= 439
container[8].angle= 0
container[8].value= 255


container[9].bin= 0
container[9].i= 908
container[9].j= 439
container[9].angle= 0
container[9].value= 255


container[10].bin= 41
container[10].i= 908
container[10].j= 441
container[10].angle= 206
container[10].value= 255


container[11].bin= 68
container[11].i= 909
container[11].j= 439
container[11].angle= 341
container[11].value= 255


container[12].bin= 44
container[12].i= 909
container[12].j= 441
container[12].angle= 224
container[12].value= 255


