container[0].bin= 8
container[0].i= 220
container[0].j= 338
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 220
container[1].j= 339
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 221
container[2].j= 337
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 222
container[3].j= 337
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 223
container[4].j= 337
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 224
container[5].j= 337
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 225
container[6].j= 338
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 225
container[7].j= 339
container[7].angle= 224
container[7].value= 255


