container[0].bin= 18
container[0].i= 195
container[0].j= 623
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 196
container[1].j= 622
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 196
container[2].j= 624
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 197
container[3].j= 621
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 197
container[4].j= 624
container[4].angle= 206
container[4].value= 255


container[5].bin= 0
container[5].i= 198
container[5].j= 621
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 198
container[6].j= 624
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 199
container[7].j= 621
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 199
container[8].j= 624
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 200
container[9].j= 621
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 200
container[10].j= 624
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 201
container[11].j= 621
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 201
container[12].j= 624
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 202
container[13].j= 621
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 202
container[14].j= 624
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 203
container[15].j= 621
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 203
container[16].j= 624
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 204
container[17].j= 622
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 204
container[18].j= 624
container[18].angle= 180
container[18].value= 255


container[19].bin= 66
container[19].i= 205
container[19].j= 622
container[19].angle= 333
container[19].value= 255


container[20].bin= 0
container[20].i= 206
container[20].j= 622
container[20].angle= 0
container[20].value= 255


container[21].bin= 63
container[21].i= 207
container[21].j= 623
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 207
container[22].j= 624
container[22].angle= 224
container[22].value= 255


