container[0].bin= 18
container[0].i= 661
container[0].j= 552
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 661
container[1].j= 553
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 661
container[2].j= 554
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 662
container[3].j= 551
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 662
container[4].j= 555
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 663
container[5].j= 550
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 663
container[6].j= 555
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 664
container[7].j= 551
container[7].angle= 315
container[7].value= 255


container[8].bin= 36
container[8].i= 664
container[8].j= 555
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 665
container[9].j= 552
container[9].angle= 315
container[9].value= 255


container[10].bin= 36
container[10].i= 665
container[10].j= 555
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 666
container[11].j= 552
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 666
container[12].j= 555
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 667
container[13].j= 553
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 667
container[14].j= 555
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 668
container[15].j= 553
container[15].angle= 333
container[15].value= 255


container[16].bin= 0
container[16].i= 669
container[16].j= 553
container[16].angle= 0
container[16].value= 255


container[17].bin= 0
container[17].i= 670
container[17].j= 553
container[17].angle= 0
container[17].value= 255


container[18].bin= 0
container[18].i= 671
container[18].j= 553
container[18].angle= 0
container[18].value= 255


container[19].bin= 0
container[19].i= 672
container[19].j= 553
container[19].angle= 0
container[19].value= 255


container[20].bin= 0
container[20].i= 673
container[20].j= 553
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 673
container[21].j= 556
container[21].angle= 135
container[21].value= 255


container[22].bin= 18
container[22].i= 673
container[22].j= 557
container[22].angle= 90
container[22].value= 255


container[23].bin= 18
container[23].i= 673
container[23].j= 558
container[23].angle= 90
container[23].value= 255


container[24].bin= 0
container[24].i= 674
container[24].j= 553
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 674
container[25].j= 559
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 675
container[26].j= 553
container[26].angle= 0
container[26].value= 255


container[27].bin= 39
container[27].i= 675
container[27].j= 559
container[27].angle= 198
container[27].value= 255


container[28].bin= 0
container[28].i= 676
container[28].j= 553
container[28].angle= 0
container[28].value= 255


container[29].bin= 48
container[29].i= 676
container[29].j= 557
container[29].angle= 243
container[29].value= 255


container[30].bin= 57
container[30].i= 676
container[30].j= 558
container[30].angle= 288
container[30].value= 255


container[31].bin= 36
container[31].i= 676
container[31].j= 560
container[31].angle= 180
container[31].value= 255


container[32].bin= 5
container[32].i= 677
container[32].j= 553
container[32].angle= 26
container[32].value= 255


container[33].bin= 44
container[33].i= 677
container[33].j= 556
container[33].angle= 224
container[33].value= 255


container[34].bin= 36
container[34].i= 677
container[34].j= 560
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 678
container[35].j= 553
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 678
container[36].j= 555
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 678
container[37].j= 558
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 678
container[38].j= 560
container[38].angle= 180
container[38].value= 255


container[39].bin= 18
container[39].i= 679
container[39].j= 551
container[39].angle= 90
container[39].value= 255


container[40].bin= 0
container[40].i= 679
container[40].j= 553
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 679
container[41].j= 555
container[41].angle= 180
container[41].value= 255


container[42].bin= 68
container[42].i= 679
container[42].j= 558
container[42].angle= 341
container[42].value= 255


container[43].bin= 54
container[43].i= 679
container[43].j= 559
container[43].angle= 270
container[43].value= 255


container[44].bin= 39
container[44].i= 679
container[44].j= 560
container[44].angle= 198
container[44].value= 255


container[45].bin= 3
container[45].i= 680
container[45].j= 550
container[45].angle= 18
container[45].value= 255


container[46].bin= 5
container[46].i= 680
container[46].j= 553
container[46].angle= 26
container[46].value= 255


container[47].bin= 36
container[47].i= 680
container[47].j= 555
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 681
container[48].j= 550
container[48].angle= 0
container[48].value= 255


container[49].bin= 3
container[49].i= 681
container[49].j= 553
container[49].angle= 18
container[49].value= 255


container[50].bin= 36
container[50].i= 681
container[50].j= 555
container[50].angle= 180
container[50].value= 255


container[51].bin= 8
container[51].i= 682
container[51].j= 550
container[51].angle= 44
container[51].value= 255


container[52].bin= 54
container[52].i= 682
container[52].j= 554
container[52].angle= 270
container[52].value= 255


container[53].bin= 44
container[53].i= 682
container[53].j= 555
container[53].angle= 224
container[53].value= 255


container[54].bin= 8
container[54].i= 683
container[54].j= 549
container[54].angle= 44
container[54].value= 255


container[55].bin= 44
container[55].i= 683
container[55].j= 553
container[55].angle= 224
container[55].value= 255


container[56].bin= 0
container[56].i= 684
container[56].j= 548
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 684
container[57].j= 552
container[57].angle= 180
container[57].value= 255


container[58].bin= 5
container[58].i= 685
container[58].j= 548
container[58].angle= 26
container[58].value= 255


container[59].bin= 41
container[59].i= 685
container[59].j= 552
container[59].angle= 206
container[59].value= 255


container[60].bin= 5
container[60].i= 686
container[60].j= 548
container[60].angle= 26
container[60].value= 255


container[61].bin= 41
container[61].i= 686
container[61].j= 552
container[61].angle= 206
container[61].value= 255


container[62].bin= 0
container[62].i= 687
container[62].j= 547
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 687
container[63].j= 551
container[63].angle= 180
container[63].value= 255


container[64].bin= 8
container[64].i= 688
container[64].j= 547
container[64].angle= 44
container[64].value= 255


container[65].bin= 36
container[65].i= 688
container[65].j= 551
container[65].angle= 180
container[65].value= 255


container[66].bin= 8
container[66].i= 689
container[66].j= 546
container[66].angle= 44
container[66].value= 255


container[67].bin= 30
container[67].i= 689
container[67].j= 552
container[67].angle= 153
container[67].value= 255


container[68].bin= 0
container[68].i= 690
container[68].j= 545
container[68].angle= 0
container[68].value= 255


container[69].bin= 36
container[69].i= 690
container[69].j= 552
container[69].angle= 180
container[69].value= 255


container[70].bin= 5
container[70].i= 691
container[70].j= 545
container[70].angle= 26
container[70].value= 255


container[71].bin= 41
container[71].i= 691
container[71].j= 552
container[71].angle= 206
container[71].value= 255


container[72].bin= 0
container[72].i= 692
container[72].j= 545
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 692
container[73].j= 551
container[73].angle= 180
container[73].value= 255


container[74].bin= 0
container[74].i= 693
container[74].j= 545
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 693
container[75].j= 551
container[75].angle= 180
container[75].value= 255


container[76].bin= 5
container[76].i= 694
container[76].j= 545
container[76].angle= 26
container[76].value= 255


container[77].bin= 44
container[77].i= 694
container[77].j= 551
container[77].angle= 224
container[77].value= 255


container[78].bin= 0
container[78].i= 695
container[78].j= 544
container[78].angle= 0
container[78].value= 255


container[79].bin= 44
container[79].i= 695
container[79].j= 550
container[79].angle= 224
container[79].value= 255


container[80].bin= 0
container[80].i= 696
container[80].j= 544
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 696
container[81].j= 549
container[81].angle= 180
container[81].value= 255


container[82].bin= 18
container[82].i= 697
container[82].j= 542
container[82].angle= 90
container[82].value= 255


container[83].bin= 18
container[83].i= 697
container[83].j= 543
container[83].angle= 90
container[83].value= 255


container[84].bin= 8
container[84].i= 697
container[84].j= 544
container[84].angle= 44
container[84].value= 255


container[85].bin= 36
container[85].i= 697
container[85].j= 549
container[85].angle= 180
container[85].value= 255


container[86].bin= 8
container[86].i= 698
container[86].j= 541
container[86].angle= 44
container[86].value= 255


container[87].bin= 36
container[87].i= 698
container[87].j= 549
container[87].angle= 180
container[87].value= 255


container[88].bin= 0
container[88].i= 699
container[88].j= 540
container[88].angle= 0
container[88].value= 255


container[89].bin= 36
container[89].i= 699
container[89].j= 549
container[89].angle= 180
container[89].value= 255


container[90].bin= 63
container[90].i= 700
container[90].j= 541
container[90].angle= 315
container[90].value= 255


container[91].bin= 27
container[91].i= 700
container[91].j= 550
container[91].angle= 135
container[91].value= 255


container[92].bin= 63
container[92].i= 701
container[92].j= 542
container[92].angle= 315
container[92].value= 255


container[93].bin= 27
container[93].i= 701
container[93].j= 551
container[93].angle= 135
container[93].value= 255


container[94].bin= 0
container[94].i= 702
container[94].j= 542
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 702
container[95].j= 551
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 703
container[96].j= 542
container[96].angle= 0
container[96].value= 255


container[97].bin= 30
container[97].i= 703
container[97].j= 552
container[97].angle= 153
container[97].value= 255


container[98].bin= 0
container[98].i= 704
container[98].j= 542
container[98].angle= 0
container[98].value= 255


container[99].bin= 30
container[99].i= 704
container[99].j= 552
container[99].angle= 153
container[99].value= 255


container[100].bin= 0
container[100].i= 705
container[100].j= 542
container[100].angle= 0
container[100].value= 255


container[101].bin= 36
container[101].i= 705
container[101].j= 552
container[101].angle= 180
container[101].value= 255


container[102].bin= 63
container[102].i= 706
container[102].j= 543
container[102].angle= 315
container[102].value= 255


container[103].bin= 41
container[103].i= 706
container[103].j= 552
container[103].angle= 206
container[103].value= 255


container[104].bin= 63
container[104].i= 707
container[104].j= 544
container[104].angle= 315
container[104].value= 255


container[105].bin= 41
container[105].i= 707
container[105].j= 552
container[105].angle= 206
container[105].value= 255


container[106].bin= 0
container[106].i= 708
container[106].j= 544
container[106].angle= 0
container[106].value= 255


container[107].bin= 36
container[107].i= 708
container[107].j= 551
container[107].angle= 180
container[107].value= 255


container[108].bin= 0
container[108].i= 709
container[108].j= 544
container[108].angle= 0
container[108].value= 255


container[109].bin= 36
container[109].i= 709
container[109].j= 551
container[109].angle= 180
container[109].value= 255


container[110].bin= 0
container[110].i= 710
container[110].j= 544
container[110].angle= 0
container[110].value= 255


container[111].bin= 36
container[111].i= 710
container[111].j= 551
container[111].angle= 180
container[111].value= 255


container[112].bin= 0
container[112].i= 711
container[112].j= 544
container[112].angle= 0
container[112].value= 255


container[113].bin= 36
container[113].i= 711
container[113].j= 551
container[113].angle= 180
container[113].value= 255


container[114].bin= 66
container[114].i= 712
container[114].j= 545
container[114].angle= 333
container[114].value= 255


container[115].bin= 44
container[115].i= 712
container[115].j= 551
container[115].angle= 224
container[115].value= 255


container[116].bin= 66
container[116].i= 713
container[116].j= 545
container[116].angle= 333
container[116].value= 255


container[117].bin= 44
container[117].i= 713
container[117].j= 550
container[117].angle= 224
container[117].value= 255


container[118].bin= 0
container[118].i= 714
container[118].j= 545
container[118].angle= 0
container[118].value= 255


container[119].bin= 36
container[119].i= 714
container[119].j= 549
container[119].angle= 180
container[119].value= 255


container[120].bin= 0
container[120].i= 715
container[120].j= 545
container[120].angle= 0
container[120].value= 255


container[121].bin= 54
container[121].i= 715
container[121].j= 548
container[121].angle= 270
container[121].value= 255


container[122].bin= 44
container[122].i= 715
container[122].j= 549
container[122].angle= 224
container[122].value= 255


container[123].bin= 0
container[123].i= 716
container[123].j= 545
container[123].angle= 0
container[123].value= 255


container[124].bin= 44
container[124].i= 716
container[124].j= 547
container[124].angle= 224
container[124].value= 255


container[125].bin= 0
container[125].i= 717
container[125].j= 545
container[125].angle= 0
container[125].value= 255


container[126].bin= 36
container[126].i= 717
container[126].j= 547
container[126].angle= 180
container[126].value= 255


container[127].bin= 0
container[127].i= 718
container[127].j= 545
container[127].angle= 0
container[127].value= 255


container[128].bin= 36
container[128].i= 718
container[128].j= 547
container[128].angle= 180
container[128].value= 255


container[129].bin= 0
container[129].i= 719
container[129].j= 545
container[129].angle= 0
container[129].value= 255


container[130].bin= 36
container[130].i= 719
container[130].j= 547
container[130].angle= 180
container[130].value= 255


container[131].bin= 0
container[131].i= 720
container[131].j= 545
container[131].angle= 0
container[131].value= 255


container[132].bin= 36
container[132].i= 720
container[132].j= 547
container[132].angle= 180
container[132].value= 255


container[133].bin= 0
container[133].i= 721
container[133].j= 545
container[133].angle= 0
container[133].value= 255


container[134].bin= 36
container[134].i= 721
container[134].j= 547
container[134].angle= 180
container[134].value= 255


container[135].bin= 0
container[135].i= 722
container[135].j= 545
container[135].angle= 0
container[135].value= 255


container[136].bin= 36
container[136].i= 722
container[136].j= 547
container[136].angle= 180
container[136].value= 255


container[137].bin= 0
container[137].i= 723
container[137].j= 545
container[137].angle= 0
container[137].value= 255


container[138].bin= 36
container[138].i= 723
container[138].j= 547
container[138].angle= 180
container[138].value= 255


container[139].bin= 68
container[139].i= 724
container[139].j= 545
container[139].angle= 341
container[139].value= 255


container[140].bin= 54
container[140].i= 724
container[140].j= 546
container[140].angle= 270
container[140].value= 255


container[141].bin= 39
container[141].i= 724
container[141].j= 547
container[141].angle= 198
container[141].value= 255


