container[0].bin= 8
container[0].i= 259
container[0].j= 188
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 259
container[1].j= 189
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 260
container[2].j= 187
container[2].angle= 0
container[2].value= 255


container[3].bin= 5
container[3].i= 261
container[3].j= 187
container[3].angle= 26
container[3].value= 255


container[4].bin= 27
container[4].i= 261
container[4].j= 190
container[4].angle= 135
container[4].value= 255


container[5].bin= 5
container[5].i= 262
container[5].j= 187
container[5].angle= 26
container[5].value= 255


container[6].bin= 23
container[6].i= 262
container[6].j= 191
container[6].angle= 116
container[6].value= 255


container[7].bin= 23
container[7].i= 262
container[7].j= 192
container[7].angle= 116
container[7].value= 255


container[8].bin= 21
container[8].i= 262
container[8].j= 193
container[8].angle= 108
container[8].value= 255


container[9].bin= 0
container[9].i= 263
container[9].j= 186
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 263
container[10].j= 191
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 264
container[11].j= 187
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 264
container[12].j= 191
container[12].angle= 180
container[12].value= 255


container[13].bin= 21
container[13].i= 264
container[13].j= 194
container[13].angle= 108
container[13].value= 255


container[14].bin= 66
container[14].i= 265
container[14].j= 187
container[14].angle= 333
container[14].value= 255


container[15].bin= 21
container[15].i= 265
container[15].j= 192
container[15].angle= 108
container[15].value= 255


container[16].bin= 18
container[16].i= 265
container[16].j= 193
container[16].angle= 90
container[16].value= 255


container[17].bin= 23
container[17].i= 265
container[17].j= 195
container[17].angle= 116
container[17].value= 255


container[18].bin= 27
container[18].i= 265
container[18].j= 196
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 266
container[19].j= 187
container[19].angle= 0
container[19].value= 255


container[20].bin= 32
container[20].i= 266
container[20].j= 196
container[20].angle= 161
container[20].value= 255


container[21].bin= 63
container[21].i= 267
container[21].j= 188
container[21].angle= 315
container[21].value= 255


container[22].bin= 50
container[22].i= 267
container[22].j= 192
container[22].angle= 251
container[22].value= 255


container[23].bin= 54
container[23].i= 267
container[23].j= 193
container[23].angle= 270
container[23].value= 255


container[24].bin= 48
container[24].i= 267
container[24].j= 194
container[24].angle= 243
container[24].value= 255


container[25].bin= 57
container[25].i= 267
container[25].j= 195
container[25].angle= 288
container[25].value= 255


container[26].bin= 36
container[26].i= 267
container[26].j= 197
container[26].angle= 180
container[26].value= 255


container[27].bin= 59
container[27].i= 268
container[27].j= 189
container[27].angle= 296
container[27].value= 255


container[28].bin= 63
container[28].i= 268
container[28].j= 190
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 268
container[29].j= 197
container[29].angle= 180
container[29].value= 255


container[30].bin= 66
container[30].i= 269
container[30].j= 190
container[30].angle= 333
container[30].value= 255


container[31].bin= 0
container[31].i= 269
container[31].j= 195
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 269
container[32].j= 197
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 270
container[33].j= 190
container[33].angle= 0
container[33].value= 255


container[34].bin= 44
container[34].i= 270
container[34].j= 192
container[34].angle= 224
container[34].value= 255


container[35].bin= 50
container[35].i= 270
container[35].j= 193
container[35].angle= 251
container[35].value= 255


container[36].bin= 68
container[36].i= 270
container[36].j= 195
container[36].angle= 341
container[36].value= 255


container[37].bin= 54
container[37].i= 270
container[37].j= 196
container[37].angle= 270
container[37].value= 255


container[38].bin= 39
container[38].i= 270
container[38].j= 197
container[38].angle= 198
container[38].value= 255


container[39].bin= 0
container[39].i= 271
container[39].j= 190
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 271
container[40].j= 192
container[40].angle= 180
container[40].value= 255


container[41].bin= 68
container[41].i= 272
container[41].j= 190
container[41].angle= 341
container[41].value= 255


container[42].bin= 54
container[42].i= 272
container[42].j= 191
container[42].angle= 270
container[42].value= 255


container[43].bin= 39
container[43].i= 272
container[43].j= 192
container[43].angle= 198
container[43].value= 255


