container[0].bin= 8
container[0].i= 140
container[0].j= 163
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 140
container[1].j= 164
container[1].angle= 116
container[1].value= 255


container[2].bin= 23
container[2].i= 140
container[2].j= 165
container[2].angle= 116
container[2].value= 255


container[3].bin= 0
container[3].i= 141
container[3].j= 162
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 141
container[4].j= 166
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 142
container[5].j= 162
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 142
container[6].j= 166
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 143
container[7].j= 162
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 143
container[8].j= 167
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 144
container[9].j= 162
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 144
container[10].j= 167
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 145
container[11].j= 163
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 145
container[12].j= 168
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 146
container[13].j= 163
container[13].angle= 333
container[13].value= 255


container[14].bin= 30
container[14].i= 146
container[14].j= 168
container[14].angle= 153
container[14].value= 255


container[15].bin= 66
container[15].i= 147
container[15].j= 164
container[15].angle= 333
container[15].value= 255


container[16].bin= 30
container[16].i= 147
container[16].j= 169
container[16].angle= 153
container[16].value= 255


container[17].bin= 63
container[17].i= 148
container[17].j= 164
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 148
container[18].j= 165
container[18].angle= 296
container[18].value= 255


container[19].bin= 54
container[19].i= 148
container[19].j= 166
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 148
container[20].j= 167
container[20].angle= 270
container[20].value= 255


