container[0].bin= 18
container[0].i= 845
container[0].j= 241
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 846
container[1].j= 240
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 846
container[2].j= 242
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 847
container[3].j= 240
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 847
container[4].j= 242
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 848
container[5].j= 240
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 848
container[6].j= 242
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 848
container[7].j= 243
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 848
container[8].j= 244
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 848
container[9].j= 245
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 848
container[10].j= 246
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 848
container[11].j= 247
container[11].angle= 90
container[11].value= 255


container[12].bin= 18
container[12].i= 848
container[12].j= 248
container[12].angle= 90
container[12].value= 255


container[13].bin= 0
container[13].i= 849
container[13].j= 240
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 849
container[14].j= 249
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 850
container[15].j= 240
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 850
container[16].j= 249
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 851
container[17].j= 241
container[17].angle= 315
container[17].value= 255


container[18].bin= 36
container[18].i= 851
container[18].j= 249
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 852
container[19].j= 242
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 852
container[20].j= 249
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 853
container[21].j= 242
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 853
container[22].j= 249
container[22].angle= 180
container[22].value= 255


container[23].bin= 66
container[23].i= 854
container[23].j= 243
container[23].angle= 333
container[23].value= 255


container[24].bin= 30
container[24].i= 854
container[24].j= 250
container[24].angle= 153
container[24].value= 255


container[25].bin= 66
container[25].i= 855
container[25].j= 243
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 855
container[26].j= 250
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 856
container[27].j= 243
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 856
container[28].j= 250
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 857
container[29].j= 243
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 857
container[30].j= 250
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 858
container[31].j= 243
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 858
container[32].j= 250
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 859
container[33].j= 243
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 859
container[34].j= 250
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 860
container[35].j= 244
container[35].angle= 315
container[35].value= 255


container[36].bin= 54
container[36].i= 860
container[36].j= 249
container[36].angle= 270
container[36].value= 255


container[37].bin= 44
container[37].i= 860
container[37].j= 250
container[37].angle= 224
container[37].value= 255


container[38].bin= 63
container[38].i= 861
container[38].j= 245
container[38].angle= 315
container[38].value= 255


container[39].bin= 44
container[39].i= 861
container[39].j= 248
container[39].angle= 224
container[39].value= 255


container[40].bin= 0
container[40].i= 862
container[40].j= 245
container[40].angle= 0
container[40].value= 255


container[41].bin= 63
container[41].i= 863
container[41].j= 246
container[41].angle= 315
container[41].value= 255


container[42].bin= 44
container[42].i= 863
container[42].j= 247
container[42].angle= 224
container[42].value= 255


