container[0].bin= 14
container[0].i= 758
container[0].j= 564
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 758
container[1].j= 565
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 759
container[2].j= 564
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 760
container[3].j= 564
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 760
container[4].j= 566
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 761
container[5].j= 564
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 761
container[6].j= 566
container[6].angle= 135
container[6].value= 255


container[7].bin= 66
container[7].i= 762
container[7].j= 564
container[7].angle= 333
container[7].value= 255


container[8].bin= 23
container[8].i= 762
container[8].j= 567
container[8].angle= 116
container[8].value= 255


container[9].bin= 27
container[9].i= 762
container[9].j= 568
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 763
container[10].j= 564
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 763
container[11].j= 568
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 764
container[12].j= 565
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 764
container[13].j= 566
container[13].angle= 270
container[13].value= 255


container[14].bin= 48
container[14].i= 764
container[14].j= 567
container[14].angle= 243
container[14].value= 255


container[15].bin= 44
container[15].i= 764
container[15].j= 568
container[15].angle= 224
container[15].value= 255


