container[0].bin= 18
container[0].i= 459
container[0].j= 599
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 460
container[1].j= 598
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 460
container[2].j= 600
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 461
container[3].j= 597
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 461
container[4].j= 600
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 462
container[5].j= 597
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 462
container[6].j= 600
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 463
container[7].j= 597
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 463
container[8].j= 600
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 464
container[9].j= 597
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 464
container[10].j= 600
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 465
container[11].j= 598
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 465
container[12].j= 600
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 466
container[13].j= 598
container[13].angle= 333
container[13].value= 255


container[14].bin= 0
container[14].i= 467
container[14].j= 598
container[14].angle= 0
container[14].value= 255


container[15].bin= 63
container[15].i= 468
container[15].j= 599
container[15].angle= 315
container[15].value= 255


container[16].bin= 18
container[16].i= 468
container[16].j= 602
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 468
container[17].j= 603
container[17].angle= 90
container[17].value= 255


container[18].bin= 27
container[18].i= 469
container[18].j= 604
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 470
container[19].j= 600
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 470
container[20].j= 604
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 471
container[21].j= 601
container[21].angle= 333
container[21].value= 255


container[22].bin= 36
container[22].i= 471
container[22].j= 604
container[22].angle= 180
container[22].value= 255


container[23].bin= 66
container[23].i= 472
container[23].j= 601
container[23].angle= 333
container[23].value= 255


container[24].bin= 36
container[24].i= 472
container[24].j= 604
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 473
container[25].j= 601
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 473
container[26].j= 604
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 474
container[27].j= 602
container[27].angle= 315
container[27].value= 255


container[28].bin= 54
container[28].i= 474
container[28].j= 603
container[28].angle= 270
container[28].value= 255


container[29].bin= 44
container[29].i= 474
container[29].j= 604
container[29].angle= 224
container[29].value= 255


