container[0].bin= 18
container[0].i= 57
container[0].j= 151
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 58
container[1].j= 150
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 58
container[2].j= 152
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 59
container[3].j= 150
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 59
container[4].j= 152
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 60
container[5].j= 150
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 61
container[6].j= 150
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 61
container[7].j= 152
container[7].angle= 224
container[7].value= 255


