container[0].bin= 8
container[0].i= 445
container[0].j= 413
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 445
container[1].j= 414
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 446
container[2].j= 412
container[2].angle= 0
container[2].value= 255


container[3].bin= 18
container[3].i= 447
container[3].j= 411
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 447
container[4].j= 412
container[4].angle= 44
container[4].value= 255


container[5].bin= 8
container[5].i= 448
container[5].j= 410
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 448
container[6].j= 414
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 449
container[7].j= 409
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 449
container[8].j= 414
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 450
container[9].j= 410
container[9].angle= 315
container[9].value= 255


container[10].bin= 54
container[10].i= 450
container[10].j= 411
container[10].angle= 270
container[10].value= 255


container[11].bin= 54
container[11].i= 450
container[11].j= 413
container[11].angle= 270
container[11].value= 255


container[12].bin= 41
container[12].i= 450
container[12].j= 414
container[12].angle= 206
container[12].value= 255


container[13].bin= 63
container[13].i= 451
container[13].j= 412
container[13].angle= 315
container[13].value= 255


container[14].bin= 41
container[14].i= 451
container[14].j= 414
container[14].angle= 206
container[14].value= 255


container[15].bin= 0
container[15].i= 452
container[15].j= 412
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 452
container[16].j= 414
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 453
container[17].j= 412
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 453
container[18].j= 414
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 454
container[19].j= 412
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 454
container[20].j= 414
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 455
container[21].j= 412
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 455
container[22].j= 414
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 456
container[23].j= 412
container[23].angle= 341
container[23].value= 255


container[24].bin= 54
container[24].i= 456
container[24].j= 413
container[24].angle= 270
container[24].value= 255


container[25].bin= 39
container[25].i= 456
container[25].j= 414
container[25].angle= 198
container[25].value= 255


