container[0].bin= 8
container[0].i= 12
container[0].j= 129
container[0].angle= 44
container[0].value= 255


container[1].bin= 66
container[1].i= 14
container[1].j= 129
container[1].angle= 333
container[1].value= 255


container[2].bin= 32
container[2].i= 14
container[2].j= 131
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 15
container[3].j= 129
container[3].angle= 0
container[3].value= 255


container[4].bin= 21
container[4].i= 15
container[4].j= 132
container[4].angle= 108
container[4].value= 255


container[5].bin= 0
container[5].i= 16
container[5].j= 129
container[5].angle= 0
container[5].value= 255


container[6].bin= 39
container[6].i= 16
container[6].j= 132
container[6].angle= 198
container[6].value= 255


container[7].bin= 0
container[7].i= 17
container[7].j= 129
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 17
container[8].j= 132
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 18
container[9].j= 129
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 18
container[10].j= 132
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 19
container[11].j= 129
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 19
container[12].j= 132
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 20
container[13].j= 130
container[13].angle= 315
container[13].value= 255


container[14].bin= 30
container[14].i= 20
container[14].j= 133
container[14].angle= 153
container[14].value= 255


container[15].bin= 63
container[15].i= 21
container[15].j= 131
container[15].angle= 315
container[15].value= 255


container[16].bin= 30
container[16].i= 21
container[16].j= 133
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 22
container[17].j= 131
container[17].angle= 0
container[17].value= 255


container[18].bin= 8
container[18].i= 23
container[18].j= 131
container[18].angle= 44
container[18].value= 255


container[19].bin= 8
container[19].i= 24
container[19].j= 130
container[19].angle= 44
container[19].value= 255


container[20].bin= 36
container[20].i= 24
container[20].j= 133
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 25
container[21].j= 129
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 25
container[22].j= 133
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 26
container[23].j= 129
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 26
container[24].j= 133
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 27
container[25].j= 129
container[25].angle= 0
container[25].value= 255


container[26].bin= 27
container[26].i= 27
container[26].j= 134
container[26].angle= 135
container[26].value= 255


container[27].bin= 0
container[27].i= 28
container[27].j= 129
container[27].angle= 0
container[27].value= 255


container[28].bin= 27
container[28].i= 28
container[28].j= 135
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 29
container[29].j= 129
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 29
container[30].j= 135
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 30
container[31].j= 129
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 30
container[32].j= 135
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 31
container[33].j= 129
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 31
container[34].j= 135
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 32
container[35].j= 129
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 32
container[36].j= 135
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 33
container[37].j= 129
container[37].angle= 0
container[37].value= 255


container[38].bin= 27
container[38].i= 33
container[38].j= 136
container[38].angle= 135
container[38].value= 255


container[39].bin= 18
container[39].i= 33
container[39].j= 137
container[39].angle= 90
container[39].value= 255


container[40].bin= 18
container[40].i= 33
container[40].j= 138
container[40].angle= 90
container[40].value= 255


container[41].bin= 21
container[41].i= 33
container[41].j= 139
container[41].angle= 108
container[41].value= 255


container[42].bin= 0
container[42].i= 34
container[42].j= 129
container[42].angle= 0
container[42].value= 255


container[43].bin= 27
container[43].i= 34
container[43].j= 139
container[43].angle= 135
container[43].value= 255


container[44].bin= 27
container[44].i= 34
container[44].j= 140
container[44].angle= 135
container[44].value= 255


container[45].bin= 0
container[45].i= 35
container[45].j= 129
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 35
container[46].j= 138
container[46].angle= 180
container[46].value= 255


container[47].bin= 27
container[47].i= 35
container[47].j= 140
container[47].angle= 135
container[47].value= 255


container[48].bin= 63
container[48].i= 36
container[48].j= 130
container[48].angle= 315
container[48].value= 255


container[49].bin= 54
container[49].i= 36
container[49].j= 131
container[49].angle= 270
container[49].value= 255


container[50].bin= 54
container[50].i= 36
container[50].j= 132
container[50].angle= 270
container[50].value= 255


container[51].bin= 39
container[51].i= 36
container[51].j= 140
container[51].angle= 198
container[51].value= 255


container[52].bin= 63
container[52].i= 37
container[52].j= 133
container[52].angle= 315
container[52].value= 255


container[53].bin= 41
container[53].i= 37
container[53].j= 140
container[53].angle= 206
container[53].value= 255


container[54].bin= 0
container[54].i= 38
container[54].j= 133
container[54].angle= 0
container[54].value= 255


container[55].bin= 39
container[55].i= 38
container[55].j= 139
container[55].angle= 198
container[55].value= 255


container[56].bin= 63
container[56].i= 39
container[56].j= 134
container[56].angle= 315
container[56].value= 255


container[57].bin= 54
container[57].i= 39
container[57].j= 135
container[57].angle= 270
container[57].value= 255


container[58].bin= 54
container[58].i= 39
container[58].j= 136
container[58].angle= 270
container[58].value= 255


container[59].bin= 27
container[59].i= 39
container[59].j= 140
container[59].angle= 135
container[59].value= 255


container[60].bin= 63
container[60].i= 40
container[60].j= 137
container[60].angle= 315
container[60].value= 255


container[61].bin= 32
container[61].i= 40
container[61].j= 140
container[61].angle= 161
container[61].value= 255


container[62].bin= 0
container[62].i= 41
container[62].j= 137
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 41
container[63].j= 140
container[63].angle= 180
container[63].value= 255


container[64].bin= 5
container[64].i= 42
container[64].j= 137
container[64].angle= 26
container[64].value= 255


container[65].bin= 30
container[65].i= 42
container[65].j= 141
container[65].angle= 153
container[65].value= 255


container[66].bin= 3
container[66].i= 43
container[66].j= 136
container[66].angle= 18
container[66].value= 255


container[67].bin= 30
container[67].i= 43
container[67].j= 141
container[67].angle= 153
container[67].value= 255


container[68].bin= 0
container[68].i= 44
container[68].j= 136
container[68].angle= 0
container[68].value= 255


container[69].bin= 0
container[69].i= 44
container[69].j= 139
container[69].angle= 0
container[69].value= 255


container[70].bin= 36
container[70].i= 44
container[70].j= 141
container[70].angle= 180
container[70].value= 255


container[71].bin= 68
container[71].i= 45
container[71].j= 136
container[71].angle= 341
container[71].value= 255


container[72].bin= 54
container[72].i= 45
container[72].j= 140
container[72].angle= 270
container[72].value= 255


container[73].bin= 63
container[73].i= 46
container[73].j= 137
container[73].angle= 315
container[73].value= 255


container[74].bin= 54
container[74].i= 46
container[74].j= 138
container[74].angle= 270
container[74].value= 255


container[75].bin= 48
container[75].i= 46
container[75].j= 139
container[75].angle= 243
container[75].value= 255


container[76].bin= 27
container[76].i= 46
container[76].j= 143
container[76].angle= 135
container[76].value= 255


container[77].bin= 0
container[77].i= 47
container[77].j= 141
container[77].angle= 0
container[77].value= 255


container[78].bin= 66
container[78].i= 48
container[78].j= 142
container[78].angle= 333
container[78].value= 255


container[79].bin= 0
container[79].i= 49
container[79].j= 142
container[79].angle= 0
container[79].value= 255


container[80].bin= 30
container[80].i= 49
container[80].j= 144
container[80].angle= 153
container[80].value= 255


container[81].bin= 68
container[81].i= 50
container[81].j= 142
container[81].angle= 341
container[81].value= 255


container[82].bin= 39
container[82].i= 50
container[82].j= 144
container[82].angle= 198
container[82].value= 255


container[83].bin= 54
container[83].i= 51
container[83].j= 143
container[83].angle= 270
container[83].value= 255


