container[0].bin= 8
container[0].i= 118
container[0].j= 171
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 118
container[1].j= 172
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 118
container[2].j= 173
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 119
container[3].j= 170
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 119
container[4].j= 173
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 120
container[5].j= 171
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 120
container[6].j= 174
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 120
container[7].j= 175
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 120
container[8].j= 176
container[8].angle= 90
container[8].value= 255


container[9].bin= 66
container[9].i= 121
container[9].j= 171
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 121
container[10].j= 177
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 122
container[11].j= 171
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 122
container[12].j= 177
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 123
container[13].j= 172
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 123
container[14].j= 173
container[14].angle= 270
container[14].value= 255


container[15].bin= 27
container[15].i= 123
container[15].j= 178
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 123
container[16].j= 179
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 123
container[17].j= 180
container[17].angle= 90
container[17].value= 255


container[18].bin= 63
container[18].i= 124
container[18].j= 174
container[18].angle= 315
container[18].value= 255


container[19].bin= 23
container[19].i= 124
container[19].j= 181
container[19].angle= 116
container[19].value= 255


container[20].bin= 18
container[20].i= 124
container[20].j= 182
container[20].angle= 90
container[20].value= 255


container[21].bin= 21
container[21].i= 124
container[21].j= 183
container[21].angle= 108
container[21].value= 255


container[22].bin= 0
container[22].i= 125
container[22].j= 174
container[22].angle= 0
container[22].value= 255


container[23].bin= 32
container[23].i= 125
container[23].j= 183
container[23].angle= 161
container[23].value= 255


container[24].bin= 63
container[24].i= 126
container[24].j= 175
container[24].angle= 315
container[24].value= 255


container[25].bin= 27
container[25].i= 126
container[25].j= 184
container[25].angle= 135
container[25].value= 255


container[26].bin= 63
container[26].i= 127
container[26].j= 176
container[26].angle= 315
container[26].value= 255


container[27].bin= 27
container[27].i= 127
container[27].j= 185
container[27].angle= 135
container[27].value= 255


container[28].bin= 0
container[28].i= 128
container[28].j= 176
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 128
container[29].j= 185
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 129
container[30].j= 176
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 129
container[31].j= 185
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 130
container[32].j= 176
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 130
container[33].j= 185
container[33].angle= 180
container[33].value= 255


container[34].bin= 0
container[34].i= 131
container[34].j= 176
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 131
container[35].j= 185
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 132
container[36].j= 177
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 132
container[37].j= 186
container[37].angle= 153
container[37].value= 255


container[38].bin= 63
container[38].i= 133
container[38].j= 178
container[38].angle= 315
container[38].value= 255


container[39].bin= 30
container[39].i= 133
container[39].j= 186
container[39].angle= 153
container[39].value= 255


container[40].bin= 0
container[40].i= 134
container[40].j= 178
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 134
container[41].j= 186
container[41].angle= 180
container[41].value= 255


container[42].bin= 66
container[42].i= 135
container[42].j= 179
container[42].angle= 333
container[42].value= 255


container[43].bin= 36
container[43].i= 135
container[43].j= 186
container[43].angle= 180
container[43].value= 255


container[44].bin= 66
container[44].i= 136
container[44].j= 179
container[44].angle= 333
container[44].value= 255


container[45].bin= 36
container[45].i= 136
container[45].j= 186
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 137
container[46].j= 179
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 137
container[47].j= 186
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 138
container[48].j= 179
container[48].angle= 0
container[48].value= 255


container[49].bin= 41
container[49].i= 138
container[49].j= 186
container[49].angle= 206
container[49].value= 255


container[50].bin= 0
container[50].i= 139
container[50].j= 179
container[50].angle= 0
container[50].value= 255


container[51].bin= 41
container[51].i= 139
container[51].j= 186
container[51].angle= 206
container[51].value= 255


container[52].bin= 0
container[52].i= 140
container[52].j= 179
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 140
container[53].j= 185
container[53].angle= 180
container[53].value= 255


container[54].bin= 63
container[54].i= 141
container[54].j= 180
container[54].angle= 315
container[54].value= 255


container[55].bin= 30
container[55].i= 141
container[55].j= 186
container[55].angle= 153
container[55].value= 255


container[56].bin= 63
container[56].i= 142
container[56].j= 181
container[56].angle= 315
container[56].value= 255


container[57].bin= 30
container[57].i= 142
container[57].j= 186
container[57].angle= 153
container[57].value= 255


container[58].bin= 0
container[58].i= 143
container[58].j= 181
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 143
container[59].j= 186
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 144
container[60].j= 181
container[60].angle= 0
container[60].value= 255


container[61].bin= 30
container[61].i= 144
container[61].j= 187
container[61].angle= 153
container[61].value= 255


container[62].bin= 0
container[62].i= 145
container[62].j= 181
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 145
container[63].j= 187
container[63].angle= 180
container[63].value= 255


container[64].bin= 0
container[64].i= 146
container[64].j= 181
container[64].angle= 0
container[64].value= 255


container[65].bin= 41
container[65].i= 146
container[65].j= 187
container[65].angle= 206
container[65].value= 255


container[66].bin= 63
container[66].i= 147
container[66].j= 182
container[66].angle= 315
container[66].value= 255


container[67].bin= 54
container[67].i= 147
container[67].j= 183
container[67].angle= 270
container[67].value= 255


container[68].bin= 54
container[68].i= 147
container[68].j= 184
container[68].angle= 270
container[68].value= 255


container[69].bin= 54
container[69].i= 147
container[69].j= 185
container[69].angle= 270
container[69].value= 255


container[70].bin= 27
container[70].i= 148
container[70].j= 188
container[70].angle= 135
container[70].value= 255


container[71].bin= 0
container[71].i= 149
container[71].j= 186
container[71].angle= 0
container[71].value= 255


container[72].bin= 0
container[72].i= 150
container[72].j= 186
container[72].angle= 0
container[72].value= 255


container[73].bin= 0
container[73].i= 151
container[73].j= 186
container[73].angle= 0
container[73].value= 255


container[74].bin= 30
container[74].i= 151
container[74].j= 189
container[74].angle= 153
container[74].value= 255


container[75].bin= 0
container[75].i= 152
container[75].j= 186
container[75].angle= 0
container[75].value= 255


container[76].bin= 36
container[76].i= 152
container[76].j= 189
container[76].angle= 180
container[76].value= 255


container[77].bin= 0
container[77].i= 153
container[77].j= 186
container[77].angle= 0
container[77].value= 255


container[78].bin= 44
container[78].i= 153
container[78].j= 188
container[78].angle= 224
container[78].value= 255


container[79].bin= 44
container[79].i= 153
container[79].j= 189
container[79].angle= 224
container[79].value= 255


container[80].bin= 68
container[80].i= 154
container[80].j= 186
container[80].angle= 341
container[80].value= 255


container[81].bin= 44
container[81].i= 154
container[81].j= 188
container[81].angle= 224
container[81].value= 255


