container[0].bin= 3
container[0].i= 387
container[0].j= 346
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 387
container[1].j= 347
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 387
container[2].j= 348
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 387
container[3].j= 349
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 387
container[4].j= 350
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 387
container[5].j= 351
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 388
container[6].j= 346
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 388
container[7].j= 352
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 389
container[8].j= 346
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 389
container[9].j= 352
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 390
container[10].j= 346
container[10].angle= 0
container[10].value= 255


container[11].bin= 54
container[11].i= 390
container[11].j= 351
container[11].angle= 270
container[11].value= 255


container[12].bin= 44
container[12].i= 390
container[12].j= 352
container[12].angle= 224
container[12].value= 255


container[13].bin= 0
container[13].i= 391
container[13].j= 346
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 391
container[14].j= 350
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 392
container[15].j= 346
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 392
container[16].j= 349
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 393
container[17].j= 347
container[17].angle= 315
container[17].value= 255


container[18].bin= 54
container[18].i= 393
container[18].j= 348
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 393
container[19].j= 349
container[19].angle= 224
container[19].value= 255


