container[0].bin= 18
container[0].i= 2
container[0].j= 124
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 3
container[1].j= 123
container[1].angle= 0
container[1].value= 255


container[2].bin= 21
container[2].i= 3
container[2].j= 125
container[2].angle= 108
container[2].value= 255


container[3].bin= 21
container[3].i= 3
container[3].j= 126
container[3].angle= 108
container[3].value= 255


container[4].bin= 57
container[4].i= 5
container[4].j= 125
container[4].angle= 288
container[4].value= 255


container[5].bin= 50
container[5].i= 5
container[5].j= 126
container[5].angle= 251
container[5].value= 255


