container[0].bin= 12
container[0].i= 601
container[0].j= 441
container[0].angle= 63
container[0].value= 255


container[1].bin= 12
container[1].i= 601
container[1].j= 442
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 601
container[2].j= 443
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 602
container[3].j= 440
container[3].angle= 44
container[3].value= 255


container[4].bin= 36
container[4].i= 602
container[4].j= 443
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 603
container[5].j= 439
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 603
container[6].j= 443
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 604
container[7].j= 440
container[7].angle= 315
container[7].value= 255


container[8].bin= 27
container[8].i= 604
container[8].j= 444
container[8].angle= 135
container[8].value= 255


container[9].bin= 63
container[9].i= 605
container[9].j= 441
container[9].angle= 315
container[9].value= 255


container[10].bin= 27
container[10].i= 605
container[10].j= 445
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 606
container[11].j= 441
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 606
container[12].j= 445
container[12].angle= 180
container[12].value= 255


container[13].bin= 3
container[13].i= 607
container[13].j= 441
container[13].angle= 18
container[13].value= 255


container[14].bin= 44
container[14].i= 607
container[14].j= 445
container[14].angle= 224
container[14].value= 255


container[15].bin= 3
container[15].i= 608
container[15].j= 439
container[15].angle= 18
container[15].value= 255


container[16].bin= 14
container[16].i= 608
container[16].j= 440
container[16].angle= 71
container[16].value= 255


container[17].bin= 44
container[17].i= 608
container[17].j= 444
container[17].angle= 224
container[17].value= 255


container[18].bin= 3
container[18].i= 609
container[18].j= 439
container[18].angle= 18
container[18].value= 255


container[19].bin= 36
container[19].i= 609
container[19].j= 443
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 610
container[20].j= 438
container[20].angle= 0
container[20].value= 255


container[21].bin= 57
container[21].i= 610
container[21].j= 441
container[21].angle= 288
container[21].value= 255


container[22].bin= 63
container[22].i= 610
container[22].j= 442
container[22].angle= 315
container[22].value= 255


container[23].bin= 68
container[23].i= 611
container[23].j= 439
container[23].angle= 341
container[23].value= 255


container[24].bin= 66
container[24].i= 611
container[24].j= 442
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 611
container[25].j= 444
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 612
container[26].j= 439
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 612
container[27].j= 441
container[27].angle= 180
container[27].value= 255


container[28].bin= 36
container[28].i= 612
container[28].j= 444
container[28].angle= 180
container[28].value= 255


container[29].bin= 68
container[29].i= 613
container[29].j= 439
container[29].angle= 341
container[29].value= 255


container[30].bin= 54
container[30].i= 613
container[30].j= 440
container[30].angle= 270
container[30].value= 255


container[31].bin= 39
container[31].i= 613
container[31].j= 441
container[31].angle= 198
container[31].value= 255


container[32].bin= 54
container[32].i= 613
container[32].j= 443
container[32].angle= 270
container[32].value= 255


container[33].bin= 39
container[33].i= 613
container[33].j= 444
container[33].angle= 198
container[33].value= 255


