container[0].bin= 14
container[0].i= 903
container[0].j= 265
container[0].angle= 71
container[0].value= 255


container[1].bin= 12
container[1].i= 903
container[1].j= 266
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 903
container[2].j= 267
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 903
container[3].j= 268
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 904
container[4].j= 264
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 904
container[5].j= 268
container[5].angle= 180
container[5].value= 255


container[6].bin= 5
container[6].i= 905
container[6].j= 264
container[6].angle= 26
container[6].value= 255


container[7].bin= 36
container[7].i= 905
container[7].j= 268
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 906
container[8].j= 263
container[8].angle= 0
container[8].value= 255


container[9].bin= 18
container[9].i= 906
container[9].j= 266
container[9].angle= 90
container[9].value= 255


container[10].bin= 36
container[10].i= 906
container[10].j= 268
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 907
container[11].j= 263
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 907
container[12].j= 268
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 908
container[13].j= 264
container[13].angle= 333
container[13].value= 255


container[14].bin= 27
container[14].i= 908
container[14].j= 269
container[14].angle= 135
container[14].value= 255


container[15].bin= 66
container[15].i= 909
container[15].j= 264
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 909
container[16].j= 270
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 910
container[17].j= 264
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 910
container[18].j= 270
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 911
container[19].j= 265
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 911
container[20].j= 271
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 911
container[21].j= 272
container[21].angle= 90
container[21].value= 255


container[22].bin= 63
container[22].i= 912
container[22].j= 266
container[22].angle= 315
container[22].value= 255


container[23].bin= 27
container[23].i= 912
container[23].j= 273
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 913
container[24].j= 266
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 913
container[25].j= 273
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 914
container[26].j= 266
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 914
container[27].j= 273
container[27].angle= 180
container[27].value= 255


