container[0].bin= 8
container[0].i= 27
container[0].j= 147
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 27
container[1].j= 148
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 27
container[2].j= 149
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 28
container[3].j= 146
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 28
container[4].j= 149
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 29
container[5].j= 146
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 29
container[6].j= 150
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 30
container[7].j= 146
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 30
container[8].j= 150
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 31
container[9].j= 147
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 31
container[10].j= 151
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 32
container[11].j= 147
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 32
container[12].j= 151
container[12].angle= 135
container[12].value= 255


container[13].bin= 23
container[13].i= 32
container[13].j= 152
container[13].angle= 116
container[13].value= 255


container[14].bin= 0
container[14].i= 33
container[14].j= 147
container[14].angle= 0
container[14].value= 255


container[15].bin= 23
container[15].i= 33
container[15].j= 153
container[15].angle= 116
container[15].value= 255


container[16].bin= 27
container[16].i= 33
container[16].j= 154
container[16].angle= 135
container[16].value= 255


container[17].bin= 66
container[17].i= 34
container[17].j= 148
container[17].angle= 333
container[17].value= 255


container[18].bin= 27
container[18].i= 34
container[18].j= 154
container[18].angle= 135
container[18].value= 255


container[19].bin= 23
container[19].i= 34
container[19].j= 155
container[19].angle= 116
container[19].value= 255


container[20].bin= 66
container[20].i= 35
container[20].j= 148
container[20].angle= 333
container[20].value= 255


container[21].bin= 27
container[21].i= 35
container[21].j= 156
container[21].angle= 135
container[21].value= 255


container[22].bin= 66
container[22].i= 36
container[22].j= 149
container[22].angle= 333
container[22].value= 255


container[23].bin= 30
container[23].i= 36
container[23].j= 157
container[23].angle= 153
container[23].value= 255


container[24].bin= 63
container[24].i= 37
container[24].j= 149
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 37
container[25].j= 150
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 37
container[26].j= 157
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 38
container[27].j= 150
container[27].angle= 315
container[27].value= 255


container[28].bin= 63
container[28].i= 38
container[28].j= 151
container[28].angle= 315
container[28].value= 255


container[29].bin= 30
container[29].i= 38
container[29].j= 158
container[29].angle= 153
container[29].value= 255


container[30].bin= 63
container[30].i= 39
container[30].j= 151
container[30].angle= 315
container[30].value= 255


container[31].bin= 63
container[31].i= 39
container[31].j= 152
container[31].angle= 315
container[31].value= 255


container[32].bin= 30
container[32].i= 39
container[32].j= 158
container[32].angle= 153
container[32].value= 255


container[33].bin= 63
container[33].i= 40
container[33].j= 152
container[33].angle= 315
container[33].value= 255


container[34].bin= 59
container[34].i= 40
container[34].j= 153
container[34].angle= 296
container[34].value= 255


container[35].bin= 30
container[35].i= 40
container[35].j= 159
container[35].angle= 153
container[35].value= 255


container[36].bin= 59
container[36].i= 41
container[36].j= 154
container[36].angle= 296
container[36].value= 255


container[37].bin= 63
container[37].i= 41
container[37].j= 155
container[37].angle= 315
container[37].value= 255


container[38].bin= 30
container[38].i= 41
container[38].j= 159
container[38].angle= 153
container[38].value= 255


container[39].bin= 63
container[39].i= 42
container[39].j= 155
container[39].angle= 315
container[39].value= 255


container[40].bin= 63
container[40].i= 42
container[40].j= 156
container[40].angle= 315
container[40].value= 255


container[41].bin= 36
container[41].i= 42
container[41].j= 159
container[41].angle= 180
container[41].value= 255


container[42].bin= 66
container[42].i= 43
container[42].j= 156
container[42].angle= 333
container[42].value= 255


container[43].bin= 36
container[43].i= 43
container[43].j= 159
container[43].angle= 180
container[43].value= 255


container[44].bin= 63
container[44].i= 44
container[44].j= 157
container[44].angle= 315
container[44].value= 255


container[45].bin= 54
container[45].i= 44
container[45].j= 158
container[45].angle= 270
container[45].value= 255


container[46].bin= 44
container[46].i= 44
container[46].j= 159
container[46].angle= 224
container[46].value= 255


