container[0].bin= 8
container[0].i= 124
container[0].j= 575
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 124
container[1].j= 576
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 124
container[2].j= 577
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 125
container[3].j= 574
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 125
container[4].j= 577
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 125
container[5].j= 578
container[5].angle= 135
container[5].value= 255


container[6].bin= 63
container[6].i= 126
container[6].j= 575
container[6].angle= 315
container[6].value= 255


container[7].bin= 27
container[7].i= 126
container[7].j= 578
container[7].angle= 135
container[7].value= 255


container[8].bin= 23
container[8].i= 126
container[8].j= 579
container[8].angle= 116
container[8].value= 255


container[9].bin= 63
container[9].i= 127
container[9].j= 576
container[9].angle= 315
container[9].value= 255


container[10].bin= 27
container[10].i= 127
container[10].j= 580
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 128
container[11].j= 576
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 128
container[12].j= 580
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 129
container[13].j= 577
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 129
container[14].j= 578
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 129
container[15].j= 579
container[15].angle= 270
container[15].value= 255


container[16].bin= 44
container[16].i= 129
container[16].j= 580
container[16].angle= 224
container[16].value= 255


