container[0].bin= 18
container[0].i= 141
container[0].j= 306
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 141
container[1].j= 307
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 141
container[2].j= 308
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 141
container[3].j= 309
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 142
container[4].j= 305
container[4].angle= 44
container[4].value= 255


container[5].bin= 23
container[5].i= 142
container[5].j= 310
container[5].angle= 116
container[5].value= 255


container[6].bin= 27
container[6].i= 142
container[6].j= 311
container[6].angle= 135
container[6].value= 255


container[7].bin= 66
container[7].i= 143
container[7].j= 305
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 143
container[8].j= 311
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 144
container[9].j= 305
container[9].angle= 315
container[9].value= 255


container[10].bin= 59
container[10].i= 144
container[10].j= 306
container[10].angle= 296
container[10].value= 255


container[11].bin= 54
container[11].i= 144
container[11].j= 307
container[11].angle= 270
container[11].value= 255


container[12].bin= 54
container[12].i= 144
container[12].j= 308
container[12].angle= 270
container[12].value= 255


container[13].bin= 54
container[13].i= 144
container[13].j= 309
container[13].angle= 270
container[13].value= 255


container[14].bin= 48
container[14].i= 144
container[14].j= 310
container[14].angle= 243
container[14].value= 255


container[15].bin= 44
container[15].i= 144
container[15].j= 311
container[15].angle= 224
container[15].value= 255


