container[0].bin= 18
container[0].i= 552
container[0].j= 140
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 553
container[1].j= 139
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 553
container[2].j= 141
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 554
container[3].j= 139
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 554
container[4].j= 141
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 555
container[5].j= 139
container[5].angle= 44
container[5].value= 255


container[6].bin= 18
container[6].i= 555
container[6].j= 140
container[6].angle= 90
container[6].value= 255


container[7].bin= 30
container[7].i= 555
container[7].j= 141
container[7].angle= 153
container[7].value= 255


container[8].bin= 8
container[8].i= 556
container[8].j= 138
container[8].angle= 44
container[8].value= 255


container[9].bin= 30
container[9].i= 556
container[9].j= 141
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 557
container[10].j= 137
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 557
container[11].j= 141
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 558
container[12].j= 138
container[12].angle= 315
container[12].value= 255


container[13].bin= 36
container[13].i= 558
container[13].j= 141
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 559
container[14].j= 139
container[14].angle= 315
container[14].value= 255


container[15].bin= 0
container[15].i= 560
container[15].j= 139
container[15].angle= 0
container[15].value= 255


container[16].bin= 63
container[16].i= 561
container[16].j= 140
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 561
container[17].j= 141
container[17].angle= 224
container[17].value= 255


