container[0].bin= 3
container[0].i= 840
container[0].j= 601
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 840
container[1].j= 602
container[1].angle= 71
container[1].value= 255


container[2].bin= 18
container[2].i= 840
container[2].j= 603
container[2].angle= 90
container[2].value= 255


container[3].bin= 21
container[3].i= 840
container[3].j= 604
container[3].angle= 108
container[3].value= 255


container[4].bin= 0
container[4].i= 841
container[4].j= 601
container[4].angle= 0
container[4].value= 255


container[5].bin= 32
container[5].i= 841
container[5].j= 604
container[5].angle= 161
container[5].value= 255


container[6].bin= 63
container[6].i= 842
container[6].j= 602
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 842
container[7].j= 603
container[7].angle= 270
container[7].value= 255


container[8].bin= 44
container[8].i= 842
container[8].j= 604
container[8].angle= 224
container[8].value= 255


