container[0].bin= 8
container[0].i= 370
container[0].j= 153
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 370
container[1].j= 154
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 371
container[2].j= 152
container[2].angle= 0
container[2].value= 255


container[3].bin= 44
container[3].i= 372
container[3].j= 154
container[3].angle= 224
container[3].value= 255


container[4].bin= 0
container[4].i= 374
container[4].j= 150
container[4].angle= 0
container[4].value= 255


container[5].bin= 68
container[5].i= 375
container[5].j= 150
container[5].angle= 341
container[5].value= 255


container[6].bin= 44
container[6].i= 375
container[6].j= 152
container[6].angle= 224
container[6].value= 255


