container[0].bin= 14
container[0].i= 785
container[0].j= 602
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 785
container[1].j= 603
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 786
container[2].j= 601
container[2].angle= 44
container[2].value= 255


container[3].bin= 8
container[3].i= 786
container[3].j= 602
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 786
container[4].j= 604
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 787
container[5].j= 600
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 787
container[6].j= 604
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 788
container[7].j= 601
container[7].angle= 315
container[7].value= 255


container[8].bin= 63
container[8].i= 788
container[8].j= 602
container[8].angle= 315
container[8].value= 255


container[9].bin= 63
container[9].i= 789
container[9].j= 603
container[9].angle= 315
container[9].value= 255


container[10].bin= 36
container[10].i= 789
container[10].j= 605
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 790
container[11].j= 603
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 790
container[12].j= 605
container[12].angle= 180
container[12].value= 255


container[13].bin= 68
container[13].i= 791
container[13].j= 603
container[13].angle= 341
container[13].value= 255


container[14].bin= 54
container[14].i= 791
container[14].j= 604
container[14].angle= 270
container[14].value= 255


container[15].bin= 39
container[15].i= 791
container[15].j= 605
container[15].angle= 198
container[15].value= 255


