container[0].bin= 18
container[0].i= 342
container[0].j= 411
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 343
container[1].j= 410
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 343
container[2].j= 412
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 344
container[3].j= 410
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 344
container[4].j= 412
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 345
container[5].j= 407
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 345
container[6].j= 410
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 345
container[7].j= 412
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 345
container[8].j= 413
container[8].angle= 90
container[8].value= 255


container[9].bin= 3
container[9].i= 346
container[9].j= 406
container[9].angle= 18
container[9].value= 255


container[10].bin= 32
container[10].i= 346
container[10].j= 408
container[10].angle= 161
container[10].value= 255


container[11].bin= 0
container[11].i= 346
container[11].j= 410
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 346
container[12].j= 414
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 347
container[13].j= 406
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 347
container[14].j= 408
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 347
container[15].j= 410
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 347
container[16].j= 414
container[16].angle= 180
container[16].value= 255


container[17].bin= 68
container[17].i= 348
container[17].j= 406
container[17].angle= 341
container[17].value= 255


container[18].bin= 23
container[18].i= 348
container[18].j= 409
container[18].angle= 116
container[18].value= 255


container[19].bin= 8
container[19].i= 348
container[19].j= 410
container[19].angle= 44
container[19].value= 255


container[20].bin= 27
container[20].i= 348
container[20].j= 415
container[20].angle= 135
container[20].value= 255


container[21].bin= 66
container[21].i= 349
container[21].j= 407
container[21].angle= 333
container[21].value= 255


container[22].bin= 27
container[22].i= 349
container[22].j= 416
container[22].angle= 135
container[22].value= 255


container[23].bin= 0
container[23].i= 350
container[23].j= 407
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 350
container[24].j= 416
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 351
container[25].j= 408
container[25].angle= 315
container[25].value= 255


container[26].bin= 54
container[26].i= 351
container[26].j= 409
container[26].angle= 270
container[26].value= 255


container[27].bin= 54
container[27].i= 351
container[27].j= 410
container[27].angle= 270
container[27].value= 255


container[28].bin= 54
container[28].i= 351
container[28].j= 411
container[28].angle= 270
container[28].value= 255


container[29].bin= 54
container[29].i= 351
container[29].j= 412
container[29].angle= 270
container[29].value= 255


container[30].bin= 54
container[30].i= 351
container[30].j= 413
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 351
container[31].j= 414
container[31].angle= 270
container[31].value= 255


container[32].bin= 27
container[32].i= 351
container[32].j= 417
container[32].angle= 135
container[32].value= 255


container[33].bin= 18
container[33].i= 351
container[33].j= 418
container[33].angle= 90
container[33].value= 255


container[34].bin= 63
container[34].i= 352
container[34].j= 415
container[34].angle= 315
container[34].value= 255


container[35].bin= 27
container[35].i= 352
container[35].j= 419
container[35].angle= 135
container[35].value= 255


container[36].bin= 0
container[36].i= 353
container[36].j= 415
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 353
container[37].j= 419
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 354
container[38].j= 416
container[38].angle= 315
container[38].value= 255


container[39].bin= 54
container[39].i= 354
container[39].j= 417
container[39].angle= 270
container[39].value= 255


container[40].bin= 54
container[40].i= 354
container[40].j= 418
container[40].angle= 270
container[40].value= 255


container[41].bin= 44
container[41].i= 354
container[41].j= 419
container[41].angle= 224
container[41].value= 255


