container[0].bin= 8
container[0].i= 325
container[0].j= 468
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 325
container[1].j= 469
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 325
container[2].j= 470
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 326
container[3].j= 467
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 326
container[4].j= 470
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 327
container[5].j= 468
container[5].angle= 333
container[5].value= 255


container[6].bin= 41
container[6].i= 327
container[6].j= 470
container[6].angle= 206
container[6].value= 255


container[7].bin= 66
container[7].i= 328
container[7].j= 468
container[7].angle= 333
container[7].value= 255


container[8].bin= 41
container[8].i= 328
container[8].j= 470
container[8].angle= 206
container[8].value= 255


container[9].bin= 0
container[9].i= 329
container[9].j= 468
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 329
container[10].j= 470
container[10].angle= 180
container[10].value= 255


container[11].bin= 68
container[11].i= 330
container[11].j= 468
container[11].angle= 341
container[11].value= 255


container[12].bin= 54
container[12].i= 330
container[12].j= 469
container[12].angle= 270
container[12].value= 255


container[13].bin= 39
container[13].i= 330
container[13].j= 470
container[13].angle= 198
container[13].value= 255


