container[0].bin= 8
container[0].i= 349
container[0].j= 163
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 349
container[1].j= 164
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 350
container[2].j= 162
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 351
container[3].j= 163
container[3].angle= 333
container[3].value= 255


container[4].bin= 66
container[4].i= 352
container[4].j= 163
container[4].angle= 333
container[4].value= 255


container[5].bin= 36
container[5].i= 352
container[5].j= 165
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 353
container[6].j= 163
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 353
container[7].j= 165
container[7].angle= 180
container[7].value= 255


container[8].bin= 68
container[8].i= 354
container[8].j= 163
container[8].angle= 341
container[8].value= 255


container[9].bin= 54
container[9].i= 354
container[9].j= 164
container[9].angle= 270
container[9].value= 255


container[10].bin= 39
container[10].i= 354
container[10].j= 165
container[10].angle= 198
container[10].value= 255


