container[0].bin= 14
container[0].i= 381
container[0].j= 563
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 381
container[1].j= 564
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 382
container[2].j= 563
container[2].angle= 18
container[2].value= 255


container[3].bin= 27
container[3].i= 382
container[3].j= 565
container[3].angle= 135
container[3].value= 255


container[4].bin= 66
container[4].i= 383
container[4].j= 563
container[4].angle= 333
container[4].value= 255


container[5].bin= 63
container[5].i= 384
container[5].j= 564
container[5].angle= 315
container[5].value= 255


container[6].bin= 44
container[6].i= 384
container[6].j= 565
container[6].angle= 224
container[6].value= 255


