container[0].bin= 3
container[0].i= 261
container[0].j= 569
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 261
container[1].j= 570
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 261
container[2].j= 571
container[2].angle= 116
container[2].value= 255


container[3].bin= 0
container[3].i= 262
container[3].j= 569
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 262
container[4].j= 572
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 263
container[5].j= 569
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 263
container[6].j= 572
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 264
container[7].j= 569
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 264
container[8].j= 573
container[8].angle= 135
container[8].value= 255


container[9].bin= 18
container[9].i= 264
container[9].j= 574
container[9].angle= 90
container[9].value= 255


container[10].bin= 0
container[10].i= 265
container[10].j= 569
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 265
container[11].j= 575
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 266
container[12].j= 569
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 266
container[13].j= 575
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 267
container[14].j= 570
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 267
container[15].j= 575
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 268
container[16].j= 571
container[16].angle= 315
container[16].value= 255


container[17].bin= 36
container[17].i= 268
container[17].j= 575
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 269
container[18].j= 571
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 269
container[19].j= 575
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 270
container[20].j= 571
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 270
container[21].j= 576
container[21].angle= 135
container[21].value= 255


container[22].bin= 18
container[22].i= 270
container[22].j= 577
container[22].angle= 90
container[22].value= 255


container[23].bin= 0
container[23].i= 271
container[23].j= 571
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 271
container[24].j= 578
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 272
container[25].j= 571
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 272
container[26].j= 578
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 273
container[27].j= 572
container[27].angle= 315
container[27].value= 255


container[28].bin= 27
container[28].i= 273
container[28].j= 579
container[28].angle= 135
container[28].value= 255


container[29].bin= 18
container[29].i= 273
container[29].j= 580
container[29].angle= 90
container[29].value= 255


container[30].bin= 63
container[30].i= 274
container[30].j= 573
container[30].angle= 315
container[30].value= 255


container[31].bin= 27
container[31].i= 274
container[31].j= 581
container[31].angle= 135
container[31].value= 255


container[32].bin= 0
container[32].i= 275
container[32].j= 573
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 275
container[33].j= 581
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 276
container[34].j= 574
container[34].angle= 333
container[34].value= 255


container[35].bin= 27
container[35].i= 276
container[35].j= 582
container[35].angle= 135
container[35].value= 255


container[36].bin= 66
container[36].i= 277
container[36].j= 574
container[36].angle= 333
container[36].value= 255


container[37].bin= 54
container[37].i= 277
container[37].j= 576
container[37].angle= 270
container[37].value= 255


container[38].bin= 27
container[38].i= 277
container[38].j= 583
container[38].angle= 135
container[38].value= 255


container[39].bin= 68
container[39].i= 278
container[39].j= 574
container[39].angle= 341
container[39].value= 255


container[40].bin= 63
container[40].i= 278
container[40].j= 575
container[40].angle= 315
container[40].value= 255


container[41].bin= 36
container[41].i= 278
container[41].j= 583
container[41].angle= 180
container[41].value= 255


container[42].bin= 63
container[42].i= 279
container[42].j= 575
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 279
container[43].j= 584
container[43].angle= 153
container[43].value= 255


container[44].bin= 66
container[44].i= 280
container[44].j= 576
container[44].angle= 333
container[44].value= 255


container[45].bin= 30
container[45].i= 280
container[45].j= 584
container[45].angle= 153
container[45].value= 255


container[46].bin= 0
container[46].i= 281
container[46].j= 576
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 281
container[47].j= 584
container[47].angle= 180
container[47].value= 255


container[48].bin= 63
container[48].i= 282
container[48].j= 577
container[48].angle= 315
container[48].value= 255


container[49].bin= 54
container[49].i= 282
container[49].j= 578
container[49].angle= 270
container[49].value= 255


container[50].bin= 54
container[50].i= 282
container[50].j= 579
container[50].angle= 270
container[50].value= 255


container[51].bin= 54
container[51].i= 282
container[51].j= 580
container[51].angle= 270
container[51].value= 255


container[52].bin= 54
container[52].i= 282
container[52].j= 581
container[52].angle= 270
container[52].value= 255


container[53].bin= 27
container[53].i= 282
container[53].j= 585
container[53].angle= 135
container[53].value= 255


container[54].bin= 18
container[54].i= 282
container[54].j= 586
container[54].angle= 90
container[54].value= 255


container[55].bin= 18
container[55].i= 282
container[55].j= 587
container[55].angle= 90
container[55].value= 255


container[56].bin= 63
container[56].i= 283
container[56].j= 582
container[56].angle= 315
container[56].value= 255


container[57].bin= 23
container[57].i= 283
container[57].j= 588
container[57].angle= 116
container[57].value= 255


container[58].bin= 27
container[58].i= 283
container[58].j= 589
container[58].angle= 135
container[58].value= 255


container[59].bin= 5
container[59].i= 284
container[59].j= 582
container[59].angle= 26
container[59].value= 255


container[60].bin= 30
container[60].i= 284
container[60].j= 589
container[60].angle= 153
container[60].value= 255


container[61].bin= 0
container[61].i= 285
container[61].j= 582
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 285
container[62].j= 589
container[62].angle= 180
container[62].value= 255


container[63].bin= 66
container[63].i= 286
container[63].j= 582
container[63].angle= 333
container[63].value= 255


container[64].bin= 36
container[64].i= 286
container[64].j= 589
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 287
container[65].j= 582
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 287
container[66].j= 589
container[66].angle= 180
container[66].value= 255


container[67].bin= 63
container[67].i= 288
container[67].j= 583
container[67].angle= 315
container[67].value= 255


container[68].bin= 36
container[68].i= 288
container[68].j= 589
container[68].angle= 180
container[68].value= 255


container[69].bin= 63
container[69].i= 289
container[69].j= 584
container[69].angle= 315
container[69].value= 255


container[70].bin= 36
container[70].i= 289
container[70].j= 589
container[70].angle= 180
container[70].value= 255


container[71].bin= 0
container[71].i= 290
container[71].j= 584
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 290
container[72].j= 589
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 291
container[73].j= 585
container[73].angle= 315
container[73].value= 255


container[74].bin= 54
container[74].i= 291
container[74].j= 586
container[74].angle= 270
container[74].value= 255


container[75].bin= 54
container[75].i= 291
container[75].j= 588
container[75].angle= 270
container[75].value= 255


container[76].bin= 41
container[76].i= 291
container[76].j= 589
container[76].angle= 206
container[76].value= 255


container[77].bin= 63
container[77].i= 292
container[77].j= 587
container[77].angle= 315
container[77].value= 255


container[78].bin= 41
container[78].i= 292
container[78].j= 589
container[78].angle= 206
container[78].value= 255


container[79].bin= 0
container[79].i= 293
container[79].j= 587
container[79].angle= 0
container[79].value= 255


container[80].bin= 36
container[80].i= 293
container[80].j= 589
container[80].angle= 180
container[80].value= 255


container[81].bin= 0
container[81].i= 294
container[81].j= 587
container[81].angle= 0
container[81].value= 255


container[82].bin= 36
container[82].i= 294
container[82].j= 589
container[82].angle= 180
container[82].value= 255


container[83].bin= 14
container[83].i= 295
container[83].j= 586
container[83].angle= 71
container[83].value= 255


container[84].bin= 8
container[84].i= 295
container[84].j= 587
container[84].angle= 44
container[84].value= 255


container[85].bin= 36
container[85].i= 295
container[85].j= 589
container[85].angle= 180
container[85].value= 255


container[86].bin= 3
container[86].i= 296
container[86].j= 585
container[86].angle= 18
container[86].value= 255


container[87].bin= 8
container[87].i= 296
container[87].j= 586
container[87].angle= 44
container[87].value= 255


container[88].bin= 36
container[88].i= 296
container[88].j= 589
container[88].angle= 180
container[88].value= 255


container[89].bin= 0
container[89].i= 297
container[89].j= 585
container[89].angle= 0
container[89].value= 255


container[90].bin= 30
container[90].i= 297
container[90].j= 589
container[90].angle= 153
container[90].value= 255


container[91].bin= 0
container[91].i= 298
container[91].j= 585
container[91].angle= 0
container[91].value= 255


container[92].bin= 18
container[92].i= 298
container[92].j= 587
container[92].angle= 90
container[92].value= 255


container[93].bin= 30
container[93].i= 298
container[93].j= 589
container[93].angle= 153
container[93].value= 255


container[94].bin= 0
container[94].i= 299
container[94].j= 585
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 299
container[95].j= 589
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 300
container[96].j= 585
container[96].angle= 0
container[96].value= 255


container[97].bin= 36
container[97].i= 300
container[97].j= 589
container[97].angle= 180
container[97].value= 255


container[98].bin= 0
container[98].i= 301
container[98].j= 585
container[98].angle= 0
container[98].value= 255


container[99].bin= 36
container[99].i= 301
container[99].j= 589
container[99].angle= 180
container[99].value= 255


container[100].bin= 0
container[100].i= 302
container[100].j= 585
container[100].angle= 0
container[100].value= 255


container[101].bin= 36
container[101].i= 302
container[101].j= 589
container[101].angle= 180
container[101].value= 255


container[102].bin= 63
container[102].i= 303
container[102].j= 586
container[102].angle= 315
container[102].value= 255


container[103].bin= 54
container[103].i= 303
container[103].j= 587
container[103].angle= 270
container[103].value= 255


container[104].bin= 54
container[104].i= 303
container[104].j= 588
container[104].angle= 270
container[104].value= 255


container[105].bin= 44
container[105].i= 303
container[105].j= 589
container[105].angle= 224
container[105].value= 255


