container[0].bin= 18
container[0].i= 339
container[0].j= 391
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 339
container[1].j= 392
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 339
container[2].j= 393
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 339
container[3].j= 394
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 340
container[4].j= 390
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 340
container[5].j= 395
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 341
container[6].j= 389
container[6].angle= 0
container[6].value= 255


container[7].bin= 39
container[7].i= 341
container[7].j= 392
container[7].angle= 198
container[7].value= 255


container[8].bin= 68
container[8].i= 341
container[8].j= 394
container[8].angle= 341
container[8].value= 255


container[9].bin= 0
container[9].i= 342
container[9].j= 389
container[9].angle= 0
container[9].value= 255


container[10].bin= 32
container[10].i= 342
container[10].j= 392
container[10].angle= 161
container[10].value= 255


container[11].bin= 3
container[11].i= 342
container[11].j= 394
container[11].angle= 18
container[11].value= 255


container[12].bin= 27
container[12].i= 342
container[12].j= 396
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 342
container[13].j= 397
container[13].angle= 90
container[13].value= 255


container[14].bin= 0
container[14].i= 343
container[14].j= 389
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 343
container[15].j= 398
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 344
container[16].j= 389
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 344
container[17].j= 398
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 345
container[18].j= 390
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 345
container[19].j= 391
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 345
container[20].j= 392
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 345
container[21].j= 393
container[21].angle= 270
container[21].value= 255


container[22].bin= 54
container[22].i= 345
container[22].j= 394
container[22].angle= 270
container[22].value= 255


container[23].bin= 54
container[23].i= 345
container[23].j= 395
container[23].angle= 270
container[23].value= 255


container[24].bin= 54
container[24].i= 345
container[24].j= 396
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 345
container[25].j= 397
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 345
container[26].j= 398
container[26].angle= 224
container[26].value= 255


