container[0].bin= 14
container[0].i= 381
container[0].j= 172
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 381
container[1].j= 173
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 382
container[2].j= 172
container[2].angle= 18
container[2].value= 255


container[3].bin= 66
container[3].i= 383
container[3].j= 172
container[3].angle= 333
container[3].value= 255


container[4].bin= 36
container[4].i= 383
container[4].j= 174
container[4].angle= 180
container[4].value= 255


container[5].bin= 3
container[5].i= 384
container[5].j= 172
container[5].angle= 18
container[5].value= 255


container[6].bin= 39
container[6].i= 384
container[6].j= 174
container[6].angle= 198
container[6].value= 255


container[7].bin= 0
container[7].i= 385
container[7].j= 171
container[7].angle= 0
container[7].value= 255


