container[0].bin= 8
container[0].i= 334
container[0].j= 182
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 334
container[1].j= 183
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 335
container[2].j= 181
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 336
container[3].j= 182
container[3].angle= 333
container[3].value= 255


container[4].bin= 27
container[4].i= 336
container[4].j= 184
container[4].angle= 135
container[4].value= 255


container[5].bin= 66
container[5].i= 337
container[5].j= 182
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 337
container[6].j= 185
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 338
container[7].j= 182
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 338
container[8].j= 185
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 339
container[9].j= 183
container[9].angle= 315
container[9].value= 255


container[10].bin= 54
container[10].i= 339
container[10].j= 184
container[10].angle= 270
container[10].value= 255


container[11].bin= 44
container[11].i= 339
container[11].j= 185
container[11].angle= 224
container[11].value= 255


