container[0].bin= 8
container[0].i= 68
container[0].j= 238
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 68
container[1].j= 239
container[1].angle= 63
container[1].value= 255


container[2].bin= 23
container[2].i= 68
container[2].j= 240
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 68
container[3].j= 241
container[3].angle= 135
container[3].value= 255


container[4].bin= 5
container[4].i= 69
container[4].j= 238
container[4].angle= 26
container[4].value= 255


container[5].bin= 27
container[5].i= 69
container[5].j= 241
container[5].angle= 135
container[5].value= 255


container[6].bin= 27
container[6].i= 69
container[6].j= 242
container[6].angle= 135
container[6].value= 255


container[7].bin= 5
container[7].i= 70
container[7].j= 237
container[7].angle= 26
container[7].value= 255


container[8].bin= 27
container[8].i= 70
container[8].j= 242
container[8].angle= 135
container[8].value= 255


container[9].bin= 27
container[9].i= 70
container[9].j= 243
container[9].angle= 135
container[9].value= 255


container[10].bin= 8
container[10].i= 71
container[10].j= 236
container[10].angle= 44
container[10].value= 255


container[11].bin= 8
container[11].i= 71
container[11].j= 237
container[11].angle= 44
container[11].value= 255


container[12].bin= 27
container[12].i= 71
container[12].j= 243
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 71
container[13].j= 244
container[13].angle= 135
container[13].value= 255


container[14].bin= 8
container[14].i= 72
container[14].j= 235
container[14].angle= 44
container[14].value= 255


container[15].bin= 8
container[15].i= 72
container[15].j= 236
container[15].angle= 44
container[15].value= 255


container[16].bin= 27
container[16].i= 72
container[16].j= 244
container[16].angle= 135
container[16].value= 255


container[17].bin= 27
container[17].i= 72
container[17].j= 245
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 73
container[18].j= 235
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 73
container[19].j= 245
container[19].angle= 135
container[19].value= 255


container[20].bin= 27
container[20].i= 73
container[20].j= 246
container[20].angle= 135
container[20].value= 255


container[21].bin= 63
container[21].i= 74
container[21].j= 235
container[21].angle= 315
container[21].value= 255


container[22].bin= 63
container[22].i= 74
container[22].j= 236
container[22].angle= 315
container[22].value= 255


container[23].bin= 27
container[23].i= 74
container[23].j= 246
container[23].angle= 135
container[23].value= 255


container[24].bin= 27
container[24].i= 74
container[24].j= 247
container[24].angle= 135
container[24].value= 255


container[25].bin= 66
container[25].i= 75
container[25].j= 236
container[25].angle= 333
container[25].value= 255


container[26].bin= 27
container[26].i= 75
container[26].j= 247
container[26].angle= 135
container[26].value= 255


container[27].bin= 27
container[27].i= 75
container[27].j= 248
container[27].angle= 135
container[27].value= 255


container[28].bin= 63
container[28].i= 76
container[28].j= 237
container[28].angle= 315
container[28].value= 255


container[29].bin= 30
container[29].i= 76
container[29].j= 248
container[29].angle= 153
container[29].value= 255


container[30].bin= 59
container[30].i= 77
container[30].j= 238
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 77
container[31].j= 239
container[31].angle= 315
container[31].value= 255


container[32].bin= 36
container[32].i= 77
container[32].j= 248
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 78
container[33].j= 239
container[33].angle= 315
container[33].value= 255


container[34].bin= 63
container[34].i= 78
container[34].j= 240
container[34].angle= 315
container[34].value= 255


container[35].bin= 30
container[35].i= 78
container[35].j= 249
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 79
container[36].j= 240
container[36].angle= 315
container[36].value= 255


container[37].bin= 63
container[37].i= 79
container[37].j= 241
container[37].angle= 315
container[37].value= 255


container[38].bin= 30
container[38].i= 79
container[38].j= 249
container[38].angle= 153
container[38].value= 255


container[39].bin= 63
container[39].i= 80
container[39].j= 241
container[39].angle= 315
container[39].value= 255


container[40].bin= 63
container[40].i= 80
container[40].j= 242
container[40].angle= 315
container[40].value= 255


container[41].bin= 36
container[41].i= 80
container[41].j= 249
container[41].angle= 180
container[41].value= 255


container[42].bin= 66
container[42].i= 81
container[42].j= 242
container[42].angle= 333
container[42].value= 255


container[43].bin= 41
container[43].i= 81
container[43].j= 249
container[43].angle= 206
container[43].value= 255


container[44].bin= 66
container[44].i= 82
container[44].j= 243
container[44].angle= 333
container[44].value= 255


container[45].bin= 54
container[45].i= 82
container[45].j= 247
container[45].angle= 270
container[45].value= 255


container[46].bin= 48
container[46].i= 82
container[46].j= 248
container[46].angle= 243
container[46].value= 255


container[47].bin= 44
container[47].i= 82
container[47].j= 249
container[47].angle= 224
container[47].value= 255


container[48].bin= 63
container[48].i= 83
container[48].j= 243
container[48].angle= 315
container[48].value= 255


container[49].bin= 59
container[49].i= 83
container[49].j= 244
container[49].angle= 296
container[49].value= 255


container[50].bin= 48
container[50].i= 83
container[50].j= 245
container[50].angle= 243
container[50].value= 255


container[51].bin= 48
container[51].i= 83
container[51].j= 246
container[51].angle= 243
container[51].value= 255


