container[0].bin= 8
container[0].i= 79
container[0].j= 117
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 79
container[1].j= 118
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 79
container[2].j= 119
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 80
container[3].j= 116
container[3].angle= 26
container[3].value= 255


container[4].bin= 27
container[4].i= 80
container[4].j= 119
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 80
container[5].j= 120
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 81
container[6].j= 116
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 81
container[7].j= 120
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 81
container[8].j= 121
container[8].angle= 135
container[8].value= 255


container[9].bin= 66
container[9].i= 82
container[9].j= 116
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 82
container[10].j= 121
container[10].angle= 153
container[10].value= 255


container[11].bin= 63
container[11].i= 83
container[11].j= 117
container[11].angle= 315
container[11].value= 255


container[12].bin= 30
container[12].i= 83
container[12].j= 122
container[12].angle= 153
container[12].value= 255


container[13].bin= 63
container[13].i= 84
container[13].j= 118
container[13].angle= 315
container[13].value= 255


container[14].bin= 27
container[14].i= 84
container[14].j= 122
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 84
container[15].j= 123
container[15].angle= 135
container[15].value= 255


container[16].bin= 63
container[16].i= 85
container[16].j= 119
container[16].angle= 315
container[16].value= 255


container[17].bin= 30
container[17].i= 85
container[17].j= 123
container[17].angle= 153
container[17].value= 255


container[18].bin= 59
container[18].i= 86
container[18].j= 120
container[18].angle= 296
container[18].value= 255


container[19].bin= 59
container[19].i= 86
container[19].j= 121
container[19].angle= 296
container[19].value= 255


container[20].bin= 59
container[20].i= 87
container[20].j= 122
container[20].angle= 296
container[20].value= 255


