container[0].bin= 18
container[0].i= 333
container[0].j= 274
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 333
container[1].j= 275
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 334
container[2].j= 273
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 334
container[3].j= 276
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 335
container[4].j= 272
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 335
container[5].j= 276
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 336
container[6].j= 273
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 336
container[7].j= 275
container[7].angle= 270
container[7].value= 255


container[8].bin= 41
container[8].i= 336
container[8].j= 276
container[8].angle= 206
container[8].value= 255


container[9].bin= 63
container[9].i= 337
container[9].j= 274
container[9].angle= 315
container[9].value= 255


container[10].bin= 41
container[10].i= 337
container[10].j= 276
container[10].angle= 206
container[10].value= 255


container[11].bin= 0
container[11].i= 338
container[11].j= 274
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 338
container[12].j= 276
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 339
container[13].j= 274
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 339
container[14].j= 276
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 340
container[15].j= 274
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 340
container[16].j= 276
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 341
container[17].j= 274
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 341
container[18].j= 276
container[18].angle= 180
container[18].value= 255


container[19].bin= 68
container[19].i= 342
container[19].j= 274
container[19].angle= 341
container[19].value= 255


container[20].bin= 54
container[20].i= 342
container[20].j= 275
container[20].angle= 270
container[20].value= 255


container[21].bin= 39
container[21].i= 342
container[21].j= 276
container[21].angle= 198
container[21].value= 255


