container[0].bin= 8
container[0].i= 596
container[0].j= 166
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 596
container[1].j= 167
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 597
container[2].j= 165
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 598
container[3].j= 166
container[3].angle= 333
container[3].value= 255


container[4].bin= 27
container[4].i= 598
container[4].j= 168
container[4].angle= 135
container[4].value= 255


container[5].bin= 18
container[5].i= 598
container[5].j= 169
container[5].angle= 90
container[5].value= 255


container[6].bin= 66
container[6].i= 599
container[6].j= 166
container[6].angle= 333
container[6].value= 255


container[7].bin= 27
container[7].i= 599
container[7].j= 170
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 600
container[8].j= 166
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 600
container[9].j= 170
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 601
container[10].j= 166
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 601
container[11].j= 171
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 602
container[12].j= 166
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 602
container[13].j= 172
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 603
container[14].j= 166
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 603
container[15].j= 172
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 604
container[16].j= 167
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 604
container[17].j= 168
container[17].angle= 270
container[17].value= 255


container[18].bin= 54
container[18].i= 604
container[18].j= 169
container[18].angle= 270
container[18].value= 255


container[19].bin= 54
container[19].i= 604
container[19].j= 170
container[19].angle= 270
container[19].value= 255


container[20].bin= 27
container[20].i= 604
container[20].j= 173
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 604
container[21].j= 174
container[21].angle= 90
container[21].value= 255


container[22].bin= 63
container[22].i= 605
container[22].j= 171
container[22].angle= 315
container[22].value= 255


container[23].bin= 27
container[23].i= 605
container[23].j= 175
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 606
container[24].j= 171
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 606
container[25].j= 175
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 607
container[26].j= 172
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 607
container[27].j= 175
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 608
container[28].j= 173
container[28].angle= 315
container[28].value= 255


container[29].bin= 21
container[29].i= 608
container[29].j= 177
container[29].angle= 108
container[29].value= 255


container[30].bin= 0
container[30].i= 609
container[30].j= 173
container[30].angle= 0
container[30].value= 255


container[31].bin= 39
container[31].i= 609
container[31].j= 177
container[31].angle= 198
container[31].value= 255


container[32].bin= 66
container[32].i= 610
container[32].j= 174
container[32].angle= 333
container[32].value= 255


container[33].bin= 36
container[33].i= 610
container[33].j= 177
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 611
container[34].j= 174
container[34].angle= 333
container[34].value= 255


container[35].bin= 30
container[35].i= 611
container[35].j= 177
container[35].angle= 153
container[35].value= 255


container[36].bin= 0
container[36].i= 612
container[36].j= 174
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 612
container[37].j= 177
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 613
container[38].j= 175
container[38].angle= 315
container[38].value= 255


container[39].bin= 54
container[39].i= 613
container[39].j= 176
container[39].angle= 270
container[39].value= 255


container[40].bin= 44
container[40].i= 613
container[40].j= 177
container[40].angle= 224
container[40].value= 255


