container[0].bin= 18
container[0].i= 429
container[0].j= 144
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 430
container[1].j= 143
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 430
container[2].j= 145
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 430
container[3].j= 146
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 431
container[4].j= 142
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 431
container[5].j= 146
container[5].angle= 153
container[5].value= 255


container[6].bin= 5
container[6].i= 432
container[6].j= 142
container[6].angle= 26
container[6].value= 255


container[7].bin= 44
container[7].i= 432
container[7].j= 146
container[7].angle= 224
container[7].value= 255


container[8].bin= 0
container[8].i= 433
container[8].j= 142
container[8].angle= 0
container[8].value= 255


container[9].bin= 44
container[9].i= 433
container[9].j= 145
container[9].angle= 224
container[9].value= 255


container[10].bin= 66
container[10].i= 434
container[10].j= 142
container[10].angle= 333
container[10].value= 255


container[11].bin= 0
container[11].i= 435
container[11].j= 142
container[11].angle= 0
container[11].value= 255


container[12].bin= 0
container[12].i= 436
container[12].j= 142
container[12].angle= 0
container[12].value= 255


container[13].bin= 0
container[13].i= 437
container[13].j= 142
container[13].angle= 0
container[13].value= 255


container[14].bin= 0
container[14].i= 438
container[14].j= 142
container[14].angle= 0
container[14].value= 255


container[15].bin= 41
container[15].i= 438
container[15].j= 144
container[15].angle= 206
container[15].value= 255


container[16].bin= 0
container[16].i= 439
container[16].j= 142
container[16].angle= 0
container[16].value= 255


container[17].bin= 41
container[17].i= 439
container[17].j= 144
container[17].angle= 206
container[17].value= 255


container[18].bin= 0
container[18].i= 440
container[18].j= 142
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 440
container[19].j= 144
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 441
container[20].j= 142
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 441
container[21].j= 144
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 442
container[22].j= 142
container[22].angle= 0
container[22].value= 255


container[23].bin= 30
container[23].i= 442
container[23].j= 144
container[23].angle= 153
container[23].value= 255


container[24].bin= 0
container[24].i= 443
container[24].j= 142
container[24].angle= 0
container[24].value= 255


container[25].bin= 63
container[25].i= 444
container[25].j= 143
container[25].angle= 315
container[25].value= 255


container[26].bin= 44
container[26].i= 444
container[26].j= 144
container[26].angle= 224
container[26].value= 255


