container[0].bin= 18
container[0].i= 848
container[0].j= 342
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 848
container[1].j= 343
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 849
container[2].j= 341
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 849
container[3].j= 344
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 850
container[4].j= 340
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 850
container[5].j= 344
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 851
container[6].j= 340
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 851
container[7].j= 345
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 852
container[8].j= 341
container[8].angle= 333
container[8].value= 255


container[9].bin= 27
container[9].i= 852
container[9].j= 345
container[9].angle= 135
container[9].value= 255


container[10].bin= 23
container[10].i= 852
container[10].j= 346
container[10].angle= 116
container[10].value= 255


container[11].bin= 21
container[11].i= 852
container[11].j= 347
container[11].angle= 108
container[11].value= 255


container[12].bin= 0
container[12].i= 853
container[12].j= 341
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 853
container[13].j= 345
container[13].angle= 180
container[13].value= 255


container[14].bin= 68
container[14].i= 854
container[14].j= 341
container[14].angle= 341
container[14].value= 255


container[15].bin= 57
container[15].i= 854
container[15].j= 342
container[15].angle= 288
container[15].value= 255


container[16].bin= 63
container[16].i= 855
container[16].j= 343
container[16].angle= 315
container[16].value= 255


container[17].bin= 21
container[17].i= 855
container[17].j= 346
container[17].angle= 108
container[17].value= 255


container[18].bin= 27
container[18].i= 855
container[18].j= 347
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 856
container[19].j= 343
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 856
container[20].j= 348
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 857
container[21].j= 343
container[21].angle= 0
container[21].value= 255


container[22].bin= 27
container[22].i= 857
container[22].j= 348
container[22].angle= 135
container[22].value= 255


container[23].bin= 23
container[23].i= 857
container[23].j= 349
container[23].angle= 116
container[23].value= 255


container[24].bin= 0
container[24].i= 858
container[24].j= 343
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 858
container[25].j= 350
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 859
container[26].j= 343
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 859
container[27].j= 350
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 860
container[28].j= 344
container[28].angle= 315
container[28].value= 255


container[29].bin= 27
container[29].i= 860
container[29].j= 351
container[29].angle= 135
container[29].value= 255


container[30].bin= 63
container[30].i= 861
container[30].j= 345
container[30].angle= 315
container[30].value= 255


container[31].bin= 27
container[31].i= 861
container[31].j= 352
container[31].angle= 135
container[31].value= 255


container[32].bin= 0
container[32].i= 862
container[32].j= 345
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 862
container[33].j= 352
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 863
container[34].j= 346
container[34].angle= 333
container[34].value= 255


container[35].bin= 27
container[35].i= 863
container[35].j= 353
container[35].angle= 135
container[35].value= 255


container[36].bin= 66
container[36].i= 864
container[36].j= 346
container[36].angle= 333
container[36].value= 255


container[37].bin= 27
container[37].i= 864
container[37].j= 354
container[37].angle= 135
container[37].value= 255


container[38].bin= 0
container[38].i= 865
container[38].j= 346
container[38].angle= 0
container[38].value= 255


container[39].bin= 30
container[39].i= 865
container[39].j= 355
container[39].angle= 153
container[39].value= 255


container[40].bin= 0
container[40].i= 866
container[40].j= 346
container[40].angle= 0
container[40].value= 255


container[41].bin= 30
container[41].i= 866
container[41].j= 355
container[41].angle= 153
container[41].value= 255


container[42].bin= 18
container[42].i= 866
container[42].j= 358
container[42].angle= 90
container[42].value= 255


container[43].bin= 0
container[43].i= 867
container[43].j= 346
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 867
container[44].j= 355
container[44].angle= 180
container[44].value= 255


container[45].bin= 32
container[45].i= 867
container[45].j= 359
container[45].angle= 161
container[45].value= 255


container[46].bin= 0
container[46].i= 868
container[46].j= 346
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 868
container[47].j= 355
container[47].angle= 180
container[47].value= 255


container[48].bin= 36
container[48].i= 868
container[48].j= 359
container[48].angle= 180
container[48].value= 255


container[49].bin= 63
container[49].i= 869
container[49].j= 347
container[49].angle= 315
container[49].value= 255


container[50].bin= 27
container[50].i= 869
container[50].j= 356
container[50].angle= 135
container[50].value= 255


container[51].bin= 8
container[51].i= 869
container[51].j= 357
container[51].angle= 44
container[51].value= 255


container[52].bin= 36
container[52].i= 869
container[52].j= 359
container[52].angle= 180
container[52].value= 255


container[53].bin= 63
container[53].i= 870
container[53].j= 348
container[53].angle= 315
container[53].value= 255


container[54].bin= 0
container[54].i= 871
container[54].j= 348
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 871
container[55].j= 358
container[55].angle= 180
container[55].value= 255


container[56].bin= 66
container[56].i= 872
container[56].j= 349
container[56].angle= 333
container[56].value= 255


container[57].bin= 36
container[57].i= 872
container[57].j= 358
container[57].angle= 180
container[57].value= 255


container[58].bin= 66
container[58].i= 873
container[58].j= 349
container[58].angle= 333
container[58].value= 255


container[59].bin= 36
container[59].i= 873
container[59].j= 358
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 874
container[60].j= 349
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 874
container[61].j= 358
container[61].angle= 180
container[61].value= 255


container[62].bin= 63
container[62].i= 875
container[62].j= 350
container[62].angle= 315
container[62].value= 255


container[63].bin= 36
container[63].i= 875
container[63].j= 358
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 876
container[64].j= 351
container[64].angle= 315
container[64].value= 255


container[65].bin= 36
container[65].i= 876
container[65].j= 358
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 877
container[66].j= 351
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 877
container[67].j= 358
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 878
container[68].j= 352
container[68].angle= 315
container[68].value= 255


container[69].bin= 54
container[69].i= 878
container[69].j= 353
container[69].angle= 270
container[69].value= 255


container[70].bin= 36
container[70].i= 878
container[70].j= 358
container[70].angle= 180
container[70].value= 255


container[71].bin= 63
container[71].i= 879
container[71].j= 354
container[71].angle= 315
container[71].value= 255


container[72].bin= 36
container[72].i= 879
container[72].j= 358
container[72].angle= 180
container[72].value= 255


container[73].bin= 5
container[73].i= 880
container[73].j= 354
container[73].angle= 26
container[73].value= 255


container[74].bin= 36
container[74].i= 880
container[74].j= 358
container[74].angle= 180
container[74].value= 255


container[75].bin= 68
container[75].i= 881
container[75].j= 354
container[75].angle= 341
container[75].value= 255


container[76].bin= 54
container[76].i= 881
container[76].j= 356
container[76].angle= 270
container[76].value= 255


container[77].bin= 54
container[77].i= 881
container[77].j= 357
container[77].angle= 270
container[77].value= 255


container[78].bin= 44
container[78].i= 881
container[78].j= 358
container[78].angle= 224
container[78].value= 255


