container[0].bin= 8
container[0].i= 54
container[0].j= 134
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 54
container[1].j= 135
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 54
container[2].j= 136
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 55
container[3].j= 134
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 55
container[4].j= 136
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 56
container[5].j= 133
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 56
container[6].j= 136
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 57
container[7].j= 133
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 57
container[8].j= 137
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 58
container[9].j= 133
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 58
container[10].j= 138
container[10].angle= 135
container[10].value= 255


container[11].bin= 66
container[11].i= 59
container[11].j= 134
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 59
container[12].j= 138
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 60
container[13].j= 134
container[13].angle= 315
container[13].value= 255


container[14].bin= 59
container[14].i= 60
container[14].j= 135
container[14].angle= 296
container[14].value= 255


container[15].bin= 54
container[15].i= 60
container[15].j= 136
container[15].angle= 270
container[15].value= 255


container[16].bin= 63
container[16].i= 61
container[16].j= 137
container[16].angle= 315
container[16].value= 255


container[17].bin= 21
container[17].i= 61
container[17].j= 140
container[17].angle= 108
container[17].value= 255


container[18].bin= 3
container[18].i= 62
container[18].j= 137
container[18].angle= 18
container[18].value= 255


container[19].bin= 32
container[19].i= 62
container[19].j= 140
container[19].angle= 161
container[19].value= 255


container[20].bin= 0
container[20].i= 63
container[20].j= 136
container[20].angle= 0
container[20].value= 255


container[21].bin= 57
container[21].i= 63
container[21].j= 138
container[21].angle= 288
container[21].value= 255


container[22].bin= 63
container[22].i= 63
container[22].j= 139
container[22].angle= 315
container[22].value= 255


container[23].bin= 30
container[23].i= 63
container[23].j= 141
container[23].angle= 153
container[23].value= 255


container[24].bin= 66
container[24].i= 64
container[24].j= 139
container[24].angle= 333
container[24].value= 255


container[25].bin= 30
container[25].i= 64
container[25].j= 141
container[25].angle= 153
container[25].value= 255


container[26].bin= 0
container[26].i= 65
container[26].j= 139
container[26].angle= 0
container[26].value= 255


container[27].bin= 63
container[27].i= 66
container[27].j= 140
container[27].angle= 315
container[27].value= 255


container[28].bin= 44
container[28].i= 66
container[28].j= 141
container[28].angle= 224
container[28].value= 255


