container[0].bin= 18
container[0].i= 76
container[0].j= 224
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 77
container[1].j= 223
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 77
container[2].j= 225
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 77
container[3].j= 226
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 78
container[4].j= 222
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 78
container[5].j= 226
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 79
container[6].j= 222
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 79
container[7].j= 227
container[7].angle= 153
container[7].value= 255


container[8].bin= 5
container[8].i= 80
container[8].j= 222
container[8].angle= 26
container[8].value= 255


container[9].bin= 30
container[9].i= 80
container[9].j= 227
container[9].angle= 153
container[9].value= 255


container[10].bin= 5
container[10].i= 81
container[10].j= 222
container[10].angle= 26
container[10].value= 255


container[11].bin= 36
container[11].i= 81
container[11].j= 227
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 82
container[12].j= 221
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 82
container[13].j= 228
container[13].angle= 153
container[13].value= 255


container[14].bin= 5
container[14].i= 83
container[14].j= 221
container[14].angle= 26
container[14].value= 255


container[15].bin= 30
container[15].i= 83
container[15].j= 228
container[15].angle= 153
container[15].value= 255


container[16].bin= 5
container[16].i= 84
container[16].j= 221
container[16].angle= 26
container[16].value= 255


container[17].bin= 36
container[17].i= 84
container[17].j= 228
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 85
container[18].j= 220
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 85
container[19].j= 229
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 86
container[20].j= 220
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 86
container[21].j= 229
container[21].angle= 153
container[21].value= 255


container[22].bin= 66
container[22].i= 87
container[22].j= 221
container[22].angle= 333
container[22].value= 255


container[23].bin= 36
container[23].i= 87
container[23].j= 229
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 88
container[24].j= 221
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 88
container[25].j= 222
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 88
container[26].j= 230
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 89
container[27].j= 222
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 89
container[28].j= 223
container[28].angle= 296
container[28].value= 255


container[29].bin= 30
container[29].i= 89
container[29].j= 230
container[29].angle= 153
container[29].value= 255


container[30].bin= 59
container[30].i= 90
container[30].j= 224
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 90
container[31].j= 225
container[31].angle= 315
container[31].value= 255


container[32].bin= 36
container[32].i= 90
container[32].j= 230
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 91
container[33].j= 225
container[33].angle= 315
container[33].value= 255


container[34].bin= 63
container[34].i= 91
container[34].j= 226
container[34].angle= 315
container[34].value= 255


container[35].bin= 30
container[35].i= 91
container[35].j= 231
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 92
container[36].j= 226
container[36].angle= 315
container[36].value= 255


container[37].bin= 59
container[37].i= 92
container[37].j= 227
container[37].angle= 296
container[37].value= 255


container[38].bin= 27
container[38].i= 92
container[38].j= 231
container[38].angle= 135
container[38].value= 255


container[39].bin= 27
container[39].i= 92
container[39].j= 232
container[39].angle= 135
container[39].value= 255


container[40].bin= 63
container[40].i= 93
container[40].j= 228
container[40].angle= 315
container[40].value= 255


container[41].bin= 30
container[41].i= 93
container[41].j= 232
container[41].angle= 153
container[41].value= 255


container[42].bin= 63
container[42].i= 94
container[42].j= 229
container[42].angle= 315
container[42].value= 255


container[43].bin= 36
container[43].i= 94
container[43].j= 232
container[43].angle= 180
container[43].value= 255


container[44].bin= 59
container[44].i= 95
container[44].j= 230
container[44].angle= 296
container[44].value= 255


container[45].bin= 63
container[45].i= 95
container[45].j= 231
container[45].angle= 315
container[45].value= 255


container[46].bin= 63
container[46].i= 96
container[46].j= 231
container[46].angle= 315
container[46].value= 255


