container[0].bin= 18
container[0].i= 135
container[0].j= 139
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 135
container[1].j= 140
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 136
container[2].j= 138
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 136
container[3].j= 141
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 137
container[4].j= 137
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 137
container[5].j= 141
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 138
container[6].j= 138
container[6].angle= 315
container[6].value= 255


container[7].bin= 27
container[7].i= 138
container[7].j= 142
container[7].angle= 135
container[7].value= 255


container[8].bin= 63
container[8].i= 139
container[8].j= 139
container[8].angle= 315
container[8].value= 255


container[9].bin= 27
container[9].i= 139
container[9].j= 143
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 140
container[10].j= 139
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 140
container[11].j= 143
container[11].angle= 180
container[11].value= 255


container[12].bin= 14
container[12].i= 141
container[12].j= 138
container[12].angle= 71
container[12].value= 255


container[13].bin= 8
container[13].i= 141
container[13].j= 139
container[13].angle= 44
container[13].value= 255


container[14].bin= 3
container[14].i= 142
container[14].j= 137
container[14].angle= 18
container[14].value= 255


container[15].bin= 8
container[15].i= 142
container[15].j= 138
container[15].angle= 44
container[15].value= 255


container[16].bin= 44
container[16].i= 142
container[16].j= 141
container[16].angle= 224
container[16].value= 255


container[17].bin= 63
container[17].i= 142
container[17].j= 142
container[17].angle= 315
container[17].value= 255


container[18].bin= 36
container[18].i= 142
container[18].j= 144
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 142
container[19].j= 150
container[19].angle= 44
container[19].value= 255


container[20].bin= 21
container[20].i= 142
container[20].j= 151
container[20].angle= 108
container[20].value= 255


container[21].bin= 0
container[21].i= 143
container[21].j= 137
container[21].angle= 0
container[21].value= 255


container[22].bin= 44
container[22].i= 143
container[22].j= 140
container[22].angle= 224
container[22].value= 255


container[23].bin= 36
container[23].i= 143
container[23].j= 144
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 144
container[24].j= 137
container[24].angle= 0
container[24].value= 255


container[25].bin= 39
container[25].i= 144
container[25].j= 139
container[25].angle= 198
container[25].value= 255


container[26].bin= 44
container[26].i= 144
container[26].j= 140
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 144
container[27].j= 142
container[27].angle= 0
container[27].value= 255


container[28].bin= 30
container[28].i= 144
container[28].j= 144
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 144
container[29].j= 149
container[29].angle= 0
container[29].value= 255


container[30].bin= 0
container[30].i= 145
container[30].j= 137
container[30].angle= 0
container[30].value= 255


container[31].bin= 41
container[31].i= 145
container[31].j= 139
container[31].angle= 206
container[31].value= 255


container[32].bin= 0
container[32].i= 145
container[32].j= 142
container[32].angle= 0
container[32].value= 255


container[33].bin= 30
container[33].i= 145
container[33].j= 144
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 145
container[34].j= 149
container[34].angle= 0
container[34].value= 255


container[35].bin= 41
container[35].i= 145
container[35].j= 151
container[35].angle= 206
container[35].value= 255


container[36].bin= 0
container[36].i= 146
container[36].j= 137
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 146
container[37].j= 139
container[37].angle= 180
container[37].value= 255


container[38].bin= 5
container[38].i= 146
container[38].j= 142
container[38].angle= 26
container[38].value= 255


container[39].bin= 68
container[39].i= 146
container[39].j= 149
container[39].angle= 341
container[39].value= 255


container[40].bin= 32
container[40].i= 146
container[40].j= 151
container[40].angle= 161
container[40].value= 255


container[41].bin= 68
container[41].i= 147
container[41].j= 137
container[41].angle= 341
container[41].value= 255


container[42].bin= 54
container[42].i= 147
container[42].j= 138
container[42].angle= 270
container[42].value= 255


container[43].bin= 39
container[43].i= 147
container[43].j= 139
container[43].angle= 198
container[43].value= 255


container[44].bin= 5
container[44].i= 147
container[44].j= 142
container[44].angle= 26
container[44].value= 255


container[45].bin= 36
container[45].i= 147
container[45].j= 144
container[45].angle= 180
container[45].value= 255


container[46].bin= 68
container[46].i= 147
container[46].j= 150
container[46].angle= 341
container[46].value= 255


container[47].bin= 27
container[47].i= 147
container[47].j= 152
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 148
container[48].j= 141
container[48].angle= 0
container[48].value= 255


container[49].bin= 27
container[49].i= 148
container[49].j= 145
container[49].angle= 135
container[49].value= 255


container[50].bin= 21
container[50].i= 148
container[50].j= 146
container[50].angle= 108
container[50].value= 255


container[51].bin= 0
container[51].i= 148
container[51].j= 150
container[51].angle= 0
container[51].value= 255


container[52].bin= 30
container[52].i= 148
container[52].j= 152
container[52].angle= 153
container[52].value= 255


container[53].bin= 5
container[53].i= 149
container[53].j= 141
container[53].angle= 26
container[53].value= 255


container[54].bin= 0
container[54].i= 149
container[54].j= 150
container[54].angle= 0
container[54].value= 255


container[55].bin= 8
container[55].i= 150
container[55].j= 140
container[55].angle= 44
container[55].value= 255


container[56].bin= 8
container[56].i= 150
container[56].j= 141
container[56].angle= 44
container[56].value= 255


container[57].bin= 39
container[57].i= 150
container[57].j= 145
container[57].angle= 198
container[57].value= 255


container[58].bin= 18
container[58].i= 150
container[58].j= 148
container[58].angle= 90
container[58].value= 255


container[59].bin= 41
container[59].i= 150
container[59].j= 152
container[59].angle= 206
container[59].value= 255


container[60].bin= 5
container[60].i= 151
container[60].j= 140
container[60].angle= 26
container[60].value= 255


container[61].bin= 39
container[61].i= 151
container[61].j= 145
container[61].angle= 198
container[61].value= 255


container[62].bin= 23
container[62].i= 151
container[62].j= 149
container[62].angle= 116
container[62].value= 255


container[63].bin= 44
container[63].i= 151
container[63].j= 152
container[63].angle= 224
container[63].value= 255


container[64].bin= 0
container[64].i= 152
container[64].j= 139
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 152
container[65].j= 144
container[65].angle= 180
container[65].value= 255


container[66].bin= 32
container[66].i= 152
container[66].j= 150
container[66].angle= 161
container[66].value= 255


container[67].bin= 63
container[67].i= 153
container[67].j= 140
container[67].angle= 315
container[67].value= 255


container[68].bin= 54
container[68].i= 153
container[68].j= 141
container[68].angle= 270
container[68].value= 255


container[69].bin= 30
container[69].i= 153
container[69].j= 151
container[69].angle= 153
container[69].value= 255


container[70].bin= 63
container[70].i= 154
container[70].j= 142
container[70].angle= 315
container[70].value= 255


container[71].bin= 44
container[71].i= 154
container[71].j= 145
container[71].angle= 224
container[71].value= 255


container[72].bin= 54
container[72].i= 154
container[72].j= 146
container[72].angle= 270
container[72].value= 255


container[73].bin= 63
container[73].i= 154
container[73].j= 147
container[73].angle= 315
container[73].value= 255


container[74].bin= 30
container[74].i= 154
container[74].j= 151
container[74].angle= 153
container[74].value= 255


container[75].bin= 0
container[75].i= 155
container[75].j= 142
container[75].angle= 0
container[75].value= 255


container[76].bin= 0
container[76].i= 155
container[76].j= 147
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 155
container[77].j= 151
container[77].angle= 180
container[77].value= 255


container[78].bin= 0
container[78].i= 156
container[78].j= 142
container[78].angle= 0
container[78].value= 255


container[79].bin= 41
container[79].i= 156
container[79].j= 144
container[79].angle= 206
container[79].value= 255


container[80].bin= 63
container[80].i= 156
container[80].j= 148
container[80].angle= 315
container[80].value= 255


container[81].bin= 36
container[81].i= 156
container[81].j= 151
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 157
container[82].j= 142
container[82].angle= 0
container[82].value= 255


container[83].bin= 41
container[83].i= 157
container[83].j= 144
container[83].angle= 206
container[83].value= 255


container[84].bin= 63
container[84].i= 157
container[84].j= 149
container[84].angle= 315
container[84].value= 255


container[85].bin= 0
container[85].i= 158
container[85].j= 142
container[85].angle= 0
container[85].value= 255


container[86].bin= 36
container[86].i= 158
container[86].j= 144
container[86].angle= 180
container[86].value= 255


container[87].bin= 0
container[87].i= 158
container[87].j= 149
container[87].angle= 0
container[87].value= 255


container[88].bin= 68
container[88].i= 159
container[88].j= 142
container[88].angle= 341
container[88].value= 255


container[89].bin= 54
container[89].i= 159
container[89].j= 143
container[89].angle= 270
container[89].value= 255


container[90].bin= 39
container[90].i= 159
container[90].j= 144
container[90].angle= 198
container[90].value= 255


container[91].bin= 63
container[91].i= 159
container[91].j= 150
container[91].angle= 315
container[91].value= 255


container[92].bin= 44
container[92].i= 159
container[92].j= 151
container[92].angle= 224
container[92].value= 255


