container[0].bin= 14
container[0].i= 535
container[0].j= 344
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 535
container[1].j= 345
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 536
container[2].j= 343
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 537
container[3].j= 343
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 537
container[4].j= 345
container[4].angle= 206
container[4].value= 255


container[5].bin= 0
container[5].i= 538
container[5].j= 343
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 538
container[6].j= 345
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 539
container[7].j= 343
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 539
container[8].j= 345
container[8].angle= 180
container[8].value= 255


container[9].bin= 68
container[9].i= 540
container[9].j= 343
container[9].angle= 341
container[9].value= 255


container[10].bin= 54
container[10].i= 540
container[10].j= 344
container[10].angle= 270
container[10].value= 255


container[11].bin= 39
container[11].i= 540
container[11].j= 345
container[11].angle= 198
container[11].value= 255


