container[0].bin= 18
container[0].i= 11
container[0].j= 249
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 12
container[1].j= 248
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 12
container[2].j= 250
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 13
container[3].j= 248
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 13
container[4].j= 250
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 14
container[5].j= 248
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 14
container[6].j= 250
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 15
container[7].j= 248
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 15
container[8].j= 250
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 16
container[9].j= 248
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 16
container[10].j= 250
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 17
container[11].j= 248
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 17
container[12].j= 250
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 18
container[13].j= 248
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 18
container[14].j= 250
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 19
container[15].j= 248
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 19
container[16].j= 250
container[16].angle= 180
container[16].value= 255


container[17].bin= 5
container[17].i= 20
container[17].j= 248
container[17].angle= 26
container[17].value= 255


container[18].bin= 18
container[18].i= 20
container[18].j= 249
container[18].angle= 90
container[18].value= 255


container[19].bin= 30
container[19].i= 20
container[19].j= 250
container[19].angle= 153
container[19].value= 255


container[20].bin= 5
container[20].i= 21
container[20].j= 248
container[20].angle= 26
container[20].value= 255


container[21].bin= 30
container[21].i= 21
container[21].j= 250
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 22
container[22].j= 247
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 22
container[23].j= 250
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 23
container[24].j= 247
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 23
container[25].j= 251
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 24
container[26].j= 247
container[26].angle= 0
container[26].value= 255


container[27].bin= 27
container[27].i= 24
container[27].j= 252
container[27].angle= 135
container[27].value= 255


container[28].bin= 66
container[28].i= 25
container[28].j= 248
container[28].angle= 333
container[28].value= 255


container[29].bin= 36
container[29].i= 25
container[29].j= 252
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 26
container[30].j= 248
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 26
container[31].j= 252
container[31].angle= 180
container[31].value= 255


container[32].bin= 5
container[32].i= 27
container[32].j= 248
container[32].angle= 26
container[32].value= 255


container[33].bin= 36
container[33].i= 27
container[33].j= 252
container[33].angle= 180
container[33].value= 255


container[34].bin= 0
container[34].i= 28
container[34].j= 247
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 28
container[35].j= 252
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 29
container[36].j= 247
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 29
container[37].j= 252
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 30
container[38].j= 248
container[38].angle= 315
container[38].value= 255


container[39].bin= 54
container[39].i= 30
container[39].j= 249
container[39].angle= 270
container[39].value= 255


container[40].bin= 27
container[40].i= 30
container[40].j= 253
container[40].angle= 135
container[40].value= 255


container[41].bin= 63
container[41].i= 31
container[41].j= 250
container[41].angle= 315
container[41].value= 255


container[42].bin= 27
container[42].i= 31
container[42].j= 254
container[42].angle= 135
container[42].value= 255


container[43].bin= 0
container[43].i= 32
container[43].j= 250
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 32
container[44].j= 254
container[44].angle= 180
container[44].value= 255


container[45].bin= 66
container[45].i= 33
container[45].j= 251
container[45].angle= 333
container[45].value= 255


container[46].bin= 27
container[46].i= 33
container[46].j= 255
container[46].angle= 135
container[46].value= 255


container[47].bin= 18
container[47].i= 33
container[47].j= 256
container[47].angle= 90
container[47].value= 255


container[48].bin= 66
container[48].i= 34
container[48].j= 251
container[48].angle= 333
container[48].value= 255


container[49].bin= 27
container[49].i= 34
container[49].j= 257
container[49].angle= 135
container[49].value= 255


container[50].bin= 0
container[50].i= 35
container[50].j= 251
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 35
container[51].j= 257
container[51].angle= 180
container[51].value= 255


container[52].bin= 5
container[52].i= 36
container[52].j= 251
container[52].angle= 26
container[52].value= 255


container[53].bin= 36
container[53].i= 36
container[53].j= 257
container[53].angle= 180
container[53].value= 255


container[54].bin= 5
container[54].i= 37
container[54].j= 251
container[54].angle= 26
container[54].value= 255


container[55].bin= 36
container[55].i= 37
container[55].j= 257
container[55].angle= 180
container[55].value= 255


container[56].bin= 0
container[56].i= 38
container[56].j= 250
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 38
container[57].j= 257
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 39
container[58].j= 250
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 39
container[59].j= 257
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 40
container[60].j= 250
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 40
container[61].j= 257
container[61].angle= 180
container[61].value= 255


container[62].bin= 0
container[62].i= 41
container[62].j= 250
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 41
container[63].j= 257
container[63].angle= 180
container[63].value= 255


container[64].bin= 0
container[64].i= 42
container[64].j= 250
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 42
container[65].j= 257
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 43
container[66].j= 250
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 43
container[67].j= 257
container[67].angle= 180
container[67].value= 255


container[68].bin= 0
container[68].i= 44
container[68].j= 250
container[68].angle= 0
container[68].value= 255


container[69].bin= 36
container[69].i= 44
container[69].j= 257
container[69].angle= 180
container[69].value= 255


container[70].bin= 66
container[70].i= 45
container[70].j= 251
container[70].angle= 333
container[70].value= 255


container[71].bin= 44
container[71].i= 45
container[71].j= 257
container[71].angle= 224
container[71].value= 255


container[72].bin= 66
container[72].i= 46
container[72].j= 251
container[72].angle= 333
container[72].value= 255


container[73].bin= 44
container[73].i= 46
container[73].j= 256
container[73].angle= 224
container[73].value= 255


container[74].bin= 0
container[74].i= 47
container[74].j= 251
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 47
container[75].j= 255
container[75].angle= 180
container[75].value= 255


container[76].bin= 0
container[76].i= 48
container[76].j= 251
container[76].angle= 0
container[76].value= 255


container[77].bin= 27
container[77].i= 48
container[77].j= 256
container[77].angle= 135
container[77].value= 255


container[78].bin= 0
container[78].i= 49
container[78].j= 251
container[78].angle= 0
container[78].value= 255


container[79].bin= 27
container[79].i= 49
container[79].j= 257
container[79].angle= 135
container[79].value= 255


container[80].bin= 0
container[80].i= 50
container[80].j= 251
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 50
container[81].j= 257
container[81].angle= 180
container[81].value= 255


container[82].bin= 5
container[82].i= 51
container[82].j= 251
container[82].angle= 26
container[82].value= 255


container[83].bin= 36
container[83].i= 51
container[83].j= 257
container[83].angle= 180
container[83].value= 255


container[84].bin= 5
container[84].i= 52
container[84].j= 251
container[84].angle= 26
container[84].value= 255


container[85].bin= 36
container[85].i= 52
container[85].j= 257
container[85].angle= 180
container[85].value= 255


container[86].bin= 0
container[86].i= 53
container[86].j= 250
container[86].angle= 0
container[86].value= 255


container[87].bin= 36
container[87].i= 53
container[87].j= 257
container[87].angle= 180
container[87].value= 255


container[88].bin= 66
container[88].i= 54
container[88].j= 251
container[88].angle= 333
container[88].value= 255


container[89].bin= 30
container[89].i= 54
container[89].j= 258
container[89].angle= 153
container[89].value= 255


container[90].bin= 66
container[90].i= 55
container[90].j= 251
container[90].angle= 333
container[90].value= 255


container[91].bin= 30
container[91].i= 55
container[91].j= 258
container[91].angle= 153
container[91].value= 255


container[92].bin= 0
container[92].i= 56
container[92].j= 251
container[92].angle= 0
container[92].value= 255


container[93].bin= 36
container[93].i= 56
container[93].j= 258
container[93].angle= 180
container[93].value= 255


container[94].bin= 0
container[94].i= 57
container[94].j= 251
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 57
container[95].j= 258
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 58
container[96].j= 251
container[96].angle= 0
container[96].value= 255


container[97].bin= 36
container[97].i= 58
container[97].j= 258
container[97].angle= 180
container[97].value= 255


container[98].bin= 0
container[98].i= 59
container[98].j= 251
container[98].angle= 0
container[98].value= 255


container[99].bin= 36
container[99].i= 59
container[99].j= 258
container[99].angle= 180
container[99].value= 255


container[100].bin= 63
container[100].i= 60
container[100].j= 252
container[100].angle= 315
container[100].value= 255


container[101].bin= 36
container[101].i= 60
container[101].j= 258
container[101].angle= 180
container[101].value= 255


container[102].bin= 63
container[102].i= 61
container[102].j= 253
container[102].angle= 315
container[102].value= 255


container[103].bin= 36
container[103].i= 61
container[103].j= 258
container[103].angle= 180
container[103].value= 255


container[104].bin= 0
container[104].i= 62
container[104].j= 253
container[104].angle= 0
container[104].value= 255


container[105].bin= 36
container[105].i= 62
container[105].j= 258
container[105].angle= 180
container[105].value= 255


container[106].bin= 63
container[106].i= 63
container[106].j= 254
container[106].angle= 315
container[106].value= 255


container[107].bin= 54
container[107].i= 63
container[107].j= 255
container[107].angle= 270
container[107].value= 255


container[108].bin= 54
container[108].i= 63
container[108].j= 256
container[108].angle= 270
container[108].value= 255


container[109].bin= 54
container[109].i= 63
container[109].j= 257
container[109].angle= 270
container[109].value= 255


container[110].bin= 44
container[110].i= 63
container[110].j= 258
container[110].angle= 224
container[110].value= 255


