container[0].bin= 18
container[0].i= 4
container[0].j= 127
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 5
container[1].j= 125
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 5
container[2].j= 126
container[2].angle= 63
container[2].value= 255


container[3].bin= 23
container[3].i= 5
container[3].j= 128
container[3].angle= 116
container[3].value= 255


container[4].bin= 27
container[4].i= 5
container[4].j= 129
container[4].angle= 135
container[4].value= 255


container[5].bin= 5
container[5].i= 6
container[5].j= 125
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 6
container[6].j= 129
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 7
container[7].j= 124
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 7
container[8].j= 130
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 8
container[9].j= 124
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 8
container[10].j= 130
container[10].angle= 153
container[10].value= 255


container[11].bin= 5
container[11].i= 9
container[11].j= 124
container[11].angle= 26
container[11].value= 255


container[12].bin= 30
container[12].i= 9
container[12].j= 131
container[12].angle= 153
container[12].value= 255


container[13].bin= 5
container[13].i= 10
container[13].j= 124
container[13].angle= 26
container[13].value= 255


container[14].bin= 30
container[14].i= 10
container[14].j= 131
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 11
container[15].j= 123
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 11
container[16].j= 131
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 12
container[17].j= 124
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 12
container[18].j= 131
container[18].angle= 180
container[18].value= 255


container[19].bin= 66
container[19].i= 13
container[19].j= 124
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 13
container[20].j= 132
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 14
container[21].j= 125
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 14
container[22].j= 132
container[22].angle= 153
container[22].value= 255


container[23].bin= 66
container[23].i= 15
container[23].j= 125
container[23].angle= 333
container[23].value= 255


container[24].bin= 36
container[24].i= 15
container[24].j= 132
container[24].angle= 180
container[24].value= 255


container[25].bin= 66
container[25].i= 16
container[25].j= 126
container[25].angle= 333
container[25].value= 255


container[26].bin= 36
container[26].i= 16
container[26].j= 132
container[26].angle= 180
container[26].value= 255


container[27].bin= 66
container[27].i= 17
container[27].j= 126
container[27].angle= 333
container[27].value= 255


container[28].bin= 41
container[28].i= 17
container[28].j= 132
container[28].angle= 206
container[28].value= 255


container[29].bin= 0
container[29].i= 18
container[29].j= 126
container[29].angle= 0
container[29].value= 255


container[30].bin= 41
container[30].i= 18
container[30].j= 132
container[30].angle= 206
container[30].value= 255


container[31].bin= 66
container[31].i= 19
container[31].j= 127
container[31].angle= 333
container[31].value= 255


container[32].bin= 41
container[32].i= 19
container[32].j= 131
container[32].angle= 206
container[32].value= 255


container[33].bin= 66
container[33].i= 20
container[33].j= 127
container[33].angle= 333
container[33].value= 255


container[34].bin= 41
container[34].i= 20
container[34].j= 131
container[34].angle= 206
container[34].value= 255


container[35].bin= 63
container[35].i= 21
container[35].j= 128
container[35].angle= 315
container[35].value= 255


container[36].bin= 54
container[36].i= 21
container[36].j= 129
container[36].angle= 270
container[36].value= 255


container[37].bin= 44
container[37].i= 21
container[37].j= 130
container[37].angle= 224
container[37].value= 255


