container[0].bin= 8
container[0].i= 139
container[0].j= 105
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 139
container[1].j= 106
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 140
container[2].j= 105
container[2].angle= 26
container[2].value= 255


container[3].bin= 30
container[3].i= 140
container[3].j= 107
container[3].angle= 153
container[3].value= 255


container[4].bin= 0
container[4].i= 141
container[4].j= 104
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 141
container[5].j= 107
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 142
container[6].j= 104
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 142
container[7].j= 108
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 143
container[8].j= 104
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 143
container[9].j= 108
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 144
container[10].j= 104
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 144
container[11].j= 108
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 145
container[12].j= 104
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 145
container[13].j= 108
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 146
container[14].j= 105
container[14].angle= 333
container[14].value= 255


container[15].bin= 30
container[15].i= 146
container[15].j= 109
container[15].angle= 153
container[15].value= 255


container[16].bin= 66
container[16].i= 147
container[16].j= 105
container[16].angle= 333
container[16].value= 255


container[17].bin= 30
container[17].i= 147
container[17].j= 109
container[17].angle= 153
container[17].value= 255


container[18].bin= 66
container[18].i= 148
container[18].j= 106
container[18].angle= 333
container[18].value= 255


container[19].bin= 30
container[19].i= 148
container[19].j= 110
container[19].angle= 153
container[19].value= 255


container[20].bin= 63
container[20].i= 149
container[20].j= 106
container[20].angle= 315
container[20].value= 255


container[21].bin= 63
container[21].i= 149
container[21].j= 107
container[21].angle= 315
container[21].value= 255


container[22].bin= 27
container[22].i= 149
container[22].j= 110
container[22].angle= 135
container[22].value= 255


container[23].bin= 27
container[23].i= 149
container[23].j= 111
container[23].angle= 135
container[23].value= 255


container[24].bin= 63
container[24].i= 150
container[24].j= 107
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 150
container[25].j= 108
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 150
container[26].j= 111
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 151
container[27].j= 108
container[27].angle= 333
container[27].value= 255


container[28].bin= 30
container[28].i= 151
container[28].j= 112
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 152
container[29].j= 108
container[29].angle= 0
container[29].value= 255


container[30].bin= 27
container[30].i= 152
container[30].j= 112
container[30].angle= 135
container[30].value= 255


container[31].bin= 27
container[31].i= 152
container[31].j= 113
container[31].angle= 135
container[31].value= 255


container[32].bin= 0
container[32].i= 153
container[32].j= 108
container[32].angle= 0
container[32].value= 255


container[33].bin= 30
container[33].i= 153
container[33].j= 113
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 154
container[34].j= 108
container[34].angle= 0
container[34].value= 255


container[35].bin= 30
container[35].i= 154
container[35].j= 114
container[35].angle= 153
container[35].value= 255


container[36].bin= 0
container[36].i= 155
container[36].j= 108
container[36].angle= 0
container[36].value= 255


container[37].bin= 27
container[37].i= 155
container[37].j= 114
container[37].angle= 135
container[37].value= 255


container[38].bin= 27
container[38].i= 155
container[38].j= 115
container[38].angle= 135
container[38].value= 255


container[39].bin= 0
container[39].i= 156
container[39].j= 108
container[39].angle= 0
container[39].value= 255


container[40].bin= 27
container[40].i= 156
container[40].j= 115
container[40].angle= 135
container[40].value= 255


container[41].bin= 27
container[41].i= 156
container[41].j= 116
container[41].angle= 135
container[41].value= 255


container[42].bin= 66
container[42].i= 157
container[42].j= 109
container[42].angle= 333
container[42].value= 255


container[43].bin= 27
container[43].i= 157
container[43].j= 116
container[43].angle= 135
container[43].value= 255


container[44].bin= 27
container[44].i= 157
container[44].j= 117
container[44].angle= 135
container[44].value= 255


container[45].bin= 63
container[45].i= 158
container[45].j= 109
container[45].angle= 315
container[45].value= 255


container[46].bin= 63
container[46].i= 158
container[46].j= 110
container[46].angle= 315
container[46].value= 255


container[47].bin= 27
container[47].i= 158
container[47].j= 117
container[47].angle= 135
container[47].value= 255


container[48].bin= 27
container[48].i= 158
container[48].j= 118
container[48].angle= 135
container[48].value= 255


container[49].bin= 63
container[49].i= 159
container[49].j= 110
container[49].angle= 315
container[49].value= 255


container[50].bin= 63
container[50].i= 159
container[50].j= 111
container[50].angle= 315
container[50].value= 255


container[51].bin= 30
container[51].i= 159
container[51].j= 118
container[51].angle= 153
container[51].value= 255


container[52].bin= 63
container[52].i= 160
container[52].j= 111
container[52].angle= 315
container[52].value= 255


container[53].bin= 63
container[53].i= 160
container[53].j= 112
container[53].angle= 315
container[53].value= 255


container[54].bin= 36
container[54].i= 160
container[54].j= 118
container[54].angle= 180
container[54].value= 255


container[55].bin= 63
container[55].i= 161
container[55].j= 112
container[55].angle= 315
container[55].value= 255


container[56].bin= 59
container[56].i= 161
container[56].j= 113
container[56].angle= 296
container[56].value= 255


container[57].bin= 30
container[57].i= 161
container[57].j= 119
container[57].angle= 153
container[57].value= 255


container[58].bin= 59
container[58].i= 162
container[58].j= 114
container[58].angle= 296
container[58].value= 255


container[59].bin= 63
container[59].i= 162
container[59].j= 115
container[59].angle= 315
container[59].value= 255


container[60].bin= 27
container[60].i= 162
container[60].j= 119
container[60].angle= 135
container[60].value= 255


container[61].bin= 27
container[61].i= 162
container[61].j= 120
container[61].angle= 135
container[61].value= 255


container[62].bin= 63
container[62].i= 163
container[62].j= 115
container[62].angle= 315
container[62].value= 255


container[63].bin= 63
container[63].i= 163
container[63].j= 116
container[63].angle= 315
container[63].value= 255


container[64].bin= 30
container[64].i= 163
container[64].j= 120
container[64].angle= 153
container[64].value= 255


container[65].bin= 63
container[65].i= 164
container[65].j= 116
container[65].angle= 315
container[65].value= 255


container[66].bin= 59
container[66].i= 164
container[66].j= 117
container[66].angle= 296
container[66].value= 255


container[67].bin= 30
container[67].i= 164
container[67].j= 121
container[67].angle= 153
container[67].value= 255


container[68].bin= 63
container[68].i= 165
container[68].j= 118
container[68].angle= 315
container[68].value= 255


container[69].bin= 27
container[69].i= 165
container[69].j= 121
container[69].angle= 135
container[69].value= 255


container[70].bin= 27
container[70].i= 165
container[70].j= 122
container[70].angle= 135
container[70].value= 255


container[71].bin= 66
container[71].i= 166
container[71].j= 119
container[71].angle= 333
container[71].value= 255


container[72].bin= 30
container[72].i= 166
container[72].j= 122
container[72].angle= 153
container[72].value= 255


container[73].bin= 63
container[73].i= 167
container[73].j= 119
container[73].angle= 315
container[73].value= 255


container[74].bin= 63
container[74].i= 167
container[74].j= 120
container[74].angle= 315
container[74].value= 255


container[75].bin= 30
container[75].i= 167
container[75].j= 123
container[75].angle= 153
container[75].value= 255


container[76].bin= 66
container[76].i= 168
container[76].j= 120
container[76].angle= 333
container[76].value= 255


container[77].bin= 27
container[77].i= 168
container[77].j= 123
container[77].angle= 135
container[77].value= 255


container[78].bin= 27
container[78].i= 168
container[78].j= 124
container[78].angle= 135
container[78].value= 255


container[79].bin= 0
container[79].i= 169
container[79].j= 120
container[79].angle= 0
container[79].value= 255


container[80].bin= 27
container[80].i= 169
container[80].j= 124
container[80].angle= 135
container[80].value= 255


container[81].bin= 27
container[81].i= 169
container[81].j= 125
container[81].angle= 135
container[81].value= 255


container[82].bin= 66
container[82].i= 170
container[82].j= 121
container[82].angle= 333
container[82].value= 255


container[83].bin= 30
container[83].i= 170
container[83].j= 125
container[83].angle= 153
container[83].value= 255


container[84].bin= 66
container[84].i= 171
container[84].j= 121
container[84].angle= 333
container[84].value= 255


container[85].bin= 30
container[85].i= 171
container[85].j= 126
container[85].angle= 153
container[85].value= 255


container[86].bin= 0
container[86].i= 172
container[86].j= 121
container[86].angle= 0
container[86].value= 255


container[87].bin= 30
container[87].i= 172
container[87].j= 126
container[87].angle= 153
container[87].value= 255


container[88].bin= 0
container[88].i= 173
container[88].j= 121
container[88].angle= 0
container[88].value= 255


container[89].bin= 30
container[89].i= 173
container[89].j= 127
container[89].angle= 153
container[89].value= 255


container[90].bin= 0
container[90].i= 174
container[90].j= 121
container[90].angle= 0
container[90].value= 255


container[91].bin= 27
container[91].i= 174
container[91].j= 127
container[91].angle= 135
container[91].value= 255


container[92].bin= 27
container[92].i= 174
container[92].j= 128
container[92].angle= 135
container[92].value= 255


container[93].bin= 66
container[93].i= 175
container[93].j= 122
container[93].angle= 333
container[93].value= 255


container[94].bin= 30
container[94].i= 175
container[94].j= 128
container[94].angle= 153
container[94].value= 255


container[95].bin= 63
container[95].i= 176
container[95].j= 122
container[95].angle= 315
container[95].value= 255


container[96].bin= 59
container[96].i= 176
container[96].j= 123
container[96].angle= 296
container[96].value= 255


container[97].bin= 30
container[97].i= 176
container[97].j= 129
container[97].angle= 153
container[97].value= 255


container[98].bin= 63
container[98].i= 177
container[98].j= 124
container[98].angle= 315
container[98].value= 255


container[99].bin= 30
container[99].i= 177
container[99].j= 129
container[99].angle= 153
container[99].value= 255


container[100].bin= 66
container[100].i= 178
container[100].j= 125
container[100].angle= 333
container[100].value= 255


container[101].bin= 30
container[101].i= 178
container[101].j= 130
container[101].angle= 153
container[101].value= 255


container[102].bin= 63
container[102].i= 179
container[102].j= 125
container[102].angle= 315
container[102].value= 255


container[103].bin= 63
container[103].i= 179
container[103].j= 126
container[103].angle= 315
container[103].value= 255


container[104].bin= 30
container[104].i= 179
container[104].j= 130
container[104].angle= 153
container[104].value= 255


container[105].bin= 63
container[105].i= 180
container[105].j= 126
container[105].angle= 315
container[105].value= 255


container[106].bin= 63
container[106].i= 180
container[106].j= 127
container[106].angle= 315
container[106].value= 255


container[107].bin= 36
container[107].i= 180
container[107].j= 130
container[107].angle= 180
container[107].value= 255


container[108].bin= 66
container[108].i= 181
container[108].j= 127
container[108].angle= 333
container[108].value= 255


container[109].bin= 30
container[109].i= 181
container[109].j= 131
container[109].angle= 153
container[109].value= 255


container[110].bin= 66
container[110].i= 182
container[110].j= 128
container[110].angle= 333
container[110].value= 255


container[111].bin= 30
container[111].i= 182
container[111].j= 131
container[111].angle= 153
container[111].value= 255


container[112].bin= 66
container[112].i= 183
container[112].j= 128
container[112].angle= 333
container[112].value= 255


container[113].bin= 36
container[113].i= 183
container[113].j= 131
container[113].angle= 180
container[113].value= 255


container[114].bin= 66
container[114].i= 184
container[114].j= 129
container[114].angle= 333
container[114].value= 255


container[115].bin= 30
container[115].i= 184
container[115].j= 132
container[115].angle= 153
container[115].value= 255


container[116].bin= 63
container[116].i= 185
container[116].j= 129
container[116].angle= 315
container[116].value= 255


container[117].bin= 63
container[117].i= 185
container[117].j= 130
container[117].angle= 315
container[117].value= 255


container[118].bin= 30
container[118].i= 185
container[118].j= 132
container[118].angle= 153
container[118].value= 255


container[119].bin= 66
container[119].i= 186
container[119].j= 130
container[119].angle= 333
container[119].value= 255


container[120].bin= 30
container[120].i= 186
container[120].j= 133
container[120].angle= 153
container[120].value= 255


container[121].bin= 66
container[121].i= 187
container[121].j= 131
container[121].angle= 333
container[121].value= 255


container[122].bin= 30
container[122].i= 187
container[122].j= 133
container[122].angle= 153
container[122].value= 255


container[123].bin= 66
container[123].i= 188
container[123].j= 131
container[123].angle= 333
container[123].value= 255


container[124].bin= 0
container[124].i= 189
container[124].j= 131
container[124].angle= 0
container[124].value= 255


container[125].bin= 30
container[125].i= 189
container[125].j= 134
container[125].angle= 153
container[125].value= 255


container[126].bin= 66
container[126].i= 190
container[126].j= 132
container[126].angle= 333
container[126].value= 255


container[127].bin= 36
container[127].i= 190
container[127].j= 134
container[127].angle= 180
container[127].value= 255


container[128].bin= 63
container[128].i= 191
container[128].j= 132
container[128].angle= 315
container[128].value= 255


container[129].bin= 54
container[129].i= 191
container[129].j= 133
container[129].angle= 270
container[129].value= 255


container[130].bin= 44
container[130].i= 191
container[130].j= 134
container[130].angle= 224
container[130].value= 255


