container[0].bin= 18
container[0].i= 129
container[0].j= 205
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 129
container[1].j= 206
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 129
container[2].j= 207
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 129
container[3].j= 208
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 130
container[4].j= 204
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 130
container[5].j= 209
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 131
container[6].j= 203
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 131
container[7].j= 209
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 132
container[8].j= 203
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 132
container[9].j= 209
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 133
container[10].j= 203
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 133
container[11].j= 209
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 134
container[12].j= 203
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 134
container[13].j= 209
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 135
container[14].j= 204
container[14].angle= 315
container[14].value= 255


container[15].bin= 44
container[15].i= 135
container[15].j= 209
container[15].angle= 224
container[15].value= 255


container[16].bin= 63
container[16].i= 136
container[16].j= 205
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 136
container[17].j= 208
container[17].angle= 224
container[17].value= 255


container[18].bin= 0
container[18].i= 137
container[18].j= 205
container[18].angle= 0
container[18].value= 255


container[19].bin= 63
container[19].i= 138
container[19].j= 206
container[19].angle= 315
container[19].value= 255


container[20].bin= 44
container[20].i= 138
container[20].j= 207
container[20].angle= 224
container[20].value= 255


