container[0].bin= 14
container[0].i= 351
container[0].j= 347
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 351
container[1].j= 348
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 352
container[2].j= 346
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 353
container[3].j= 346
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 353
container[4].j= 348
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 354
container[5].j= 346
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 354
container[6].j= 348
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 355
container[7].j= 346
container[7].angle= 0
container[7].value= 255


container[8].bin= 41
container[8].i= 355
container[8].j= 348
container[8].angle= 206
container[8].value= 255


container[9].bin= 68
container[9].i= 356
container[9].j= 346
container[9].angle= 341
container[9].value= 255


container[10].bin= 32
container[10].i= 356
container[10].j= 348
container[10].angle= 161
container[10].value= 255


container[11].bin= 27
container[11].i= 356
container[11].j= 349
container[11].angle= 135
container[11].value= 255


container[12].bin= 63
container[12].i= 358
container[12].j= 347
container[12].angle= 315
container[12].value= 255


