container[0].bin= 18
container[0].i= 237
container[0].j= 54
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 238
container[1].j= 53
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 238
container[2].j= 55
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 239
container[3].j= 53
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 239
container[4].j= 55
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 240
container[5].j= 53
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 240
container[6].j= 55
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 241
container[7].j= 53
container[7].angle= 333
container[7].value= 255


container[8].bin= 41
container[8].i= 241
container[8].j= 55
container[8].angle= 206
container[8].value= 255


container[9].bin= 63
container[9].i= 242
container[9].j= 53
container[9].angle= 315
container[9].value= 255


container[10].bin= 54
container[10].i= 242
container[10].j= 54
container[10].angle= 270
container[10].value= 255


container[11].bin= 44
container[11].i= 242
container[11].j= 55
container[11].angle= 224
container[11].value= 255


