container[0].bin= 3
container[0].i= 63
container[0].j= 153
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 63
container[1].j= 154
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 63
container[2].j= 155
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 64
container[3].j= 153
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 64
container[4].j= 155
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 65
container[5].j= 153
container[5].angle= 341
container[5].value= 255


container[6].bin= 57
container[6].i= 65
container[6].j= 154
container[6].angle= 288
container[6].value= 255


container[7].bin= 44
container[7].i= 65
container[7].j= 155
container[7].angle= 224
container[7].value= 255


