container[0].bin= 14
container[0].i= 501
container[0].j= 111
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 501
container[1].j= 112
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 501
container[2].j= 113
container[2].angle= 90
container[2].value= 255


container[3].bin= 3
container[3].i= 502
container[3].j= 110
container[3].angle= 18
container[3].value= 255


container[4].bin= 8
container[4].i= 502
container[4].j= 111
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 502
container[5].j= 114
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 503
container[6].j= 110
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 503
container[7].j= 114
container[7].angle= 180
container[7].value= 255


container[8].bin= 68
container[8].i= 504
container[8].j= 110
container[8].angle= 341
container[8].value= 255


container[9].bin= 63
container[9].i= 504
container[9].j= 111
container[9].angle= 315
container[9].value= 255


container[10].bin= 57
container[10].i= 504
container[10].j= 113
container[10].angle= 288
container[10].value= 255


container[11].bin= 44
container[11].i= 504
container[11].j= 114
container[11].angle= 224
container[11].value= 255


container[12].bin= 54
container[12].i= 505
container[12].j= 112
container[12].angle= 270
container[12].value= 255


