container[0].bin= 0
container[0].i= 0
container[0].j= 22
container[0].angle= 0
container[0].value= 255


container[1].bin= 36
container[1].i= 0
container[1].j= 25
container[1].angle= 180
container[1].value= 255


container[2].bin= 0
container[2].i= 0
container[2].j= 33
container[2].angle= 0
container[2].value= 255


container[3].bin= 36
container[3].i= 0
container[3].j= 37
container[3].angle= 180
container[3].value= 255


container[4].bin= 66
container[4].i= 1
container[4].j= 23
container[4].angle= 333
container[4].value= 255


container[5].bin= 30
container[5].i= 1
container[5].j= 26
container[5].angle= 153
container[5].value= 255


container[6].bin= 66
container[6].i= 1
container[6].j= 34
container[6].angle= 333
container[6].value= 255


container[7].bin= 41
container[7].i= 1
container[7].j= 37
container[7].angle= 206
container[7].value= 255


container[8].bin= 0
container[8].i= 2
container[8].j= 23
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 2
container[9].j= 26
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 2
container[10].j= 27
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 2
container[11].j= 34
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 2
container[12].j= 37
container[12].angle= 153
container[12].value= 255


container[13].bin= 5
container[13].i= 3
container[13].j= 23
container[13].angle= 26
container[13].value= 255


container[14].bin= 27
container[14].i= 3
container[14].j= 27
container[14].angle= 135
container[14].value= 255


container[15].bin= 23
container[15].i= 3
container[15].j= 28
container[15].angle= 116
container[15].value= 255


container[16].bin= 0
container[16].i= 3
container[16].j= 34
container[16].angle= 0
container[16].value= 255


container[17].bin= 30
container[17].i= 3
container[17].j= 37
container[17].angle= 153
container[17].value= 255


container[18].bin= 66
container[18].i= 4
container[18].j= 23
container[18].angle= 333
container[18].value= 255


container[19].bin= 23
container[19].i= 4
container[19].j= 29
container[19].angle= 116
container[19].value= 255


container[20].bin= 27
container[20].i= 4
container[20].j= 30
container[20].angle= 135
container[20].value= 255


container[21].bin= 66
container[21].i= 4
container[21].j= 34
container[21].angle= 333
container[21].value= 255


container[22].bin= 36
container[22].i= 4
container[22].j= 37
container[22].angle= 180
container[22].value= 255


container[23].bin= 18
container[23].i= 4
container[23].j= 44
container[23].angle= 90
container[23].value= 255


container[24].bin= 66
container[24].i= 5
container[24].j= 23
container[24].angle= 333
container[24].value= 255


container[25].bin= 30
container[25].i= 5
container[25].j= 30
container[25].angle= 153
container[25].value= 255


container[26].bin= 66
container[26].i= 5
container[26].j= 35
container[26].angle= 333
container[26].value= 255


container[27].bin= 27
container[27].i= 5
container[27].j= 38
container[27].angle= 135
container[27].value= 255


container[28].bin= 12
container[28].i= 5
container[28].j= 42
container[28].angle= 63
container[28].value= 255


container[29].bin= 12
container[29].i= 5
container[29].j= 43
container[29].angle= 63
container[29].value= 255


container[30].bin= 23
container[30].i= 5
container[30].j= 45
container[30].angle= 116
container[30].value= 255


container[31].bin= 27
container[31].i= 5
container[31].j= 46
container[31].angle= 135
container[31].value= 255


container[32].bin= 66
container[32].i= 6
container[32].j= 24
container[32].angle= 333
container[32].value= 255


container[33].bin= 30
container[33].i= 6
container[33].j= 31
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 6
container[34].j= 35
container[34].angle= 0
container[34].value= 255


container[35].bin= 23
container[35].i= 6
container[35].j= 39
container[35].angle= 116
container[35].value= 255


container[36].bin= 18
container[36].i= 6
container[36].j= 40
container[36].angle= 90
container[36].value= 255


container[37].bin= 12
container[37].i= 6
container[37].j= 41
container[37].angle= 63
container[37].value= 255


container[38].bin= 30
container[38].i= 6
container[38].j= 46
container[38].angle= 153
container[38].value= 255


container[39].bin= 66
container[39].i= 7
container[39].j= 24
container[39].angle= 333
container[39].value= 255


container[40].bin= 27
container[40].i= 7
container[40].j= 31
container[40].angle= 135
container[40].value= 255


container[41].bin= 23
container[41].i= 7
container[41].j= 32
container[41].angle= 116
container[41].value= 255


container[42].bin= 18
container[42].i= 7
container[42].j= 33
container[42].angle= 90
container[42].value= 255


container[43].bin= 12
container[43].i= 7
container[43].j= 34
container[43].angle= 63
container[43].value= 255


container[44].bin= 8
container[44].i= 7
container[44].j= 35
container[44].angle= 44
container[44].value= 255


container[45].bin= 36
container[45].i= 7
container[45].j= 46
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 8
container[46].j= 24
container[46].angle= 0
container[46].value= 255


container[47].bin= 30
container[47].i= 8
container[47].j= 47
container[47].angle= 153
container[47].value= 255


container[48].bin= 66
container[48].i= 9
container[48].j= 25
container[48].angle= 333
container[48].value= 255


container[49].bin= 27
container[49].i= 9
container[49].j= 47
container[49].angle= 135
container[49].value= 255


container[50].bin= 27
container[50].i= 9
container[50].j= 48
container[50].angle= 135
container[50].value= 255


container[51].bin= 63
container[51].i= 10
container[51].j= 25
container[51].angle= 315
container[51].value= 255


container[52].bin= 63
container[52].i= 10
container[52].j= 26
container[52].angle= 315
container[52].value= 255


container[53].bin= 30
container[53].i= 10
container[53].j= 48
container[53].angle= 153
container[53].value= 255


container[54].bin= 66
container[54].i= 11
container[54].j= 26
container[54].angle= 333
container[54].value= 255


container[55].bin= 30
container[55].i= 11
container[55].j= 49
container[55].angle= 153
container[55].value= 255


container[56].bin= 66
container[56].i= 12
container[56].j= 27
container[56].angle= 333
container[56].value= 255


container[57].bin= 30
container[57].i= 12
container[57].j= 49
container[57].angle= 153
container[57].value= 255


container[58].bin= 63
container[58].i= 13
container[58].j= 27
container[58].angle= 315
container[58].value= 255


container[59].bin= 63
container[59].i= 13
container[59].j= 28
container[59].angle= 315
container[59].value= 255


container[60].bin= 30
container[60].i= 13
container[60].j= 50
container[60].angle= 153
container[60].value= 255


container[61].bin= 66
container[61].i= 14
container[61].j= 28
container[61].angle= 333
container[61].value= 255


container[62].bin= 54
container[62].i= 14
container[62].j= 38
container[62].angle= 270
container[62].value= 255


container[63].bin= 27
container[63].i= 14
container[63].j= 50
container[63].angle= 135
container[63].value= 255


container[64].bin= 27
container[64].i= 14
container[64].j= 51
container[64].angle= 135
container[64].value= 255


container[65].bin= 66
container[65].i= 15
container[65].j= 29
container[65].angle= 333
container[65].value= 255


container[66].bin= 44
container[66].i= 15
container[66].j= 37
container[66].angle= 224
container[66].value= 255


container[67].bin= 59
container[67].i= 15
container[67].j= 39
container[67].angle= 296
container[67].value= 255


container[68].bin= 63
container[68].i= 15
container[68].j= 40
container[68].angle= 315
container[68].value= 255


container[69].bin= 30
container[69].i= 15
container[69].j= 51
container[69].angle= 153
container[69].value= 255


container[70].bin= 63
container[70].i= 16
container[70].j= 29
container[70].angle= 315
container[70].value= 255


container[71].bin= 63
container[71].i= 16
container[71].j= 30
container[71].angle= 315
container[71].value= 255


container[72].bin= 41
container[72].i= 16
container[72].j= 36
container[72].angle= 206
container[72].value= 255


container[73].bin= 63
container[73].i= 16
container[73].j= 40
container[73].angle= 315
container[73].value= 255


container[74].bin= 59
container[74].i= 16
container[74].j= 41
container[74].angle= 296
container[74].value= 255


container[75].bin= 30
container[75].i= 16
container[75].j= 52
container[75].angle= 153
container[75].value= 255


container[76].bin= 66
container[76].i= 17
container[76].j= 30
container[76].angle= 333
container[76].value= 255


container[77].bin= 41
container[77].i= 17
container[77].j= 36
container[77].angle= 206
container[77].value= 255


container[78].bin= 59
container[78].i= 17
container[78].j= 42
container[78].angle= 296
container[78].value= 255


container[79].bin= 59
container[79].i= 17
container[79].j= 43
container[79].angle= 296
container[79].value= 255


container[80].bin= 27
container[80].i= 17
container[80].j= 52
container[80].angle= 135
container[80].value= 255


container[81].bin= 27
container[81].i= 17
container[81].j= 53
container[81].angle= 135
container[81].value= 255


container[82].bin= 66
container[82].i= 18
container[82].j= 31
container[82].angle= 333
container[82].value= 255


container[83].bin= 30
container[83].i= 18
container[83].j= 36
container[83].angle= 153
container[83].value= 255


container[84].bin= 59
container[84].i= 18
container[84].j= 44
container[84].angle= 296
container[84].value= 255


container[85].bin= 63
container[85].i= 18
container[85].j= 45
container[85].angle= 315
container[85].value= 255


container[86].bin= 30
container[86].i= 18
container[86].j= 53
container[86].angle= 153
container[86].value= 255


container[87].bin= 63
container[87].i= 19
container[87].j= 31
container[87].angle= 315
container[87].value= 255


container[88].bin= 63
container[88].i= 19
container[88].j= 32
container[88].angle= 315
container[88].value= 255


container[89].bin= 30
container[89].i= 19
container[89].j= 36
container[89].angle= 153
container[89].value= 255


container[90].bin= 63
container[90].i= 19
container[90].j= 45
container[90].angle= 315
container[90].value= 255


container[91].bin= 63
container[91].i= 19
container[91].j= 46
container[91].angle= 315
container[91].value= 255


container[92].bin= 30
container[92].i= 19
container[92].j= 54
container[92].angle= 153
container[92].value= 255


container[93].bin= 66
container[93].i= 20
container[93].j= 32
container[93].angle= 333
container[93].value= 255


container[94].bin= 36
container[94].i= 20
container[94].j= 36
container[94].angle= 180
container[94].value= 255


container[95].bin= 63
container[95].i= 20
container[95].j= 46
container[95].angle= 315
container[95].value= 255


container[96].bin= 59
container[96].i= 20
container[96].j= 47
container[96].angle= 296
container[96].value= 255


container[97].bin= 54
container[97].i= 20
container[97].j= 48
container[97].angle= 270
container[97].value= 255


container[98].bin= 54
container[98].i= 20
container[98].j= 49
container[98].angle= 270
container[98].value= 255


container[99].bin= 54
container[99].i= 20
container[99].j= 50
container[99].angle= 270
container[99].value= 255


container[100].bin= 27
container[100].i= 20
container[100].j= 54
container[100].angle= 135
container[100].value= 255


container[101].bin= 27
container[101].i= 20
container[101].j= 55
container[101].angle= 135
container[101].value= 255


container[102].bin= 66
container[102].i= 21
container[102].j= 33
container[102].angle= 333
container[102].value= 255


container[103].bin= 36
container[103].i= 21
container[103].j= 36
container[103].angle= 180
container[103].value= 255


container[104].bin= 59
container[104].i= 21
container[104].j= 51
container[104].angle= 296
container[104].value= 255


container[105].bin= 63
container[105].i= 21
container[105].j= 52
container[105].angle= 315
container[105].value= 255


container[106].bin= 30
container[106].i= 21
container[106].j= 55
container[106].angle= 153
container[106].value= 255


container[107].bin= 66
container[107].i= 22
container[107].j= 33
container[107].angle= 333
container[107].value= 255


container[108].bin= 30
container[108].i= 22
container[108].j= 37
container[108].angle= 153
container[108].value= 255


container[109].bin= 63
container[109].i= 22
container[109].j= 52
container[109].angle= 315
container[109].value= 255


container[110].bin= 63
container[110].i= 22
container[110].j= 53
container[110].angle= 315
container[110].value= 255


container[111].bin= 36
container[111].i= 22
container[111].j= 55
container[111].angle= 180
container[111].value= 255


container[112].bin= 66
container[112].i= 23
container[112].j= 34
container[112].angle= 333
container[112].value= 255


container[113].bin= 27
container[113].i= 23
container[113].j= 37
container[113].angle= 135
container[113].value= 255


container[114].bin= 27
container[114].i= 23
container[114].j= 38
container[114].angle= 135
container[114].value= 255


container[115].bin= 63
container[115].i= 23
container[115].j= 53
container[115].angle= 315
container[115].value= 255


container[116].bin= 63
container[116].i= 23
container[116].j= 54
container[116].angle= 315
container[116].value= 255


container[117].bin= 66
container[117].i= 24
container[117].j= 34
container[117].angle= 333
container[117].value= 255


container[118].bin= 30
container[118].i= 24
container[118].j= 38
container[118].angle= 153
container[118].value= 255


container[119].bin= 63
container[119].i= 24
container[119].j= 54
container[119].angle= 315
container[119].value= 255


container[120].bin= 66
container[120].i= 25
container[120].j= 35
container[120].angle= 333
container[120].value= 255


container[121].bin= 30
container[121].i= 25
container[121].j= 39
container[121].angle= 153
container[121].value= 255


container[122].bin= 66
container[122].i= 26
container[122].j= 35
container[122].angle= 333
container[122].value= 255


container[123].bin= 27
container[123].i= 26
container[123].j= 39
container[123].angle= 135
container[123].value= 255


container[124].bin= 27
container[124].i= 26
container[124].j= 40
container[124].angle= 135
container[124].value= 255


container[125].bin= 66
container[125].i= 27
container[125].j= 36
container[125].angle= 333
container[125].value= 255


container[126].bin= 30
container[126].i= 27
container[126].j= 40
container[126].angle= 153
container[126].value= 255


container[127].bin= 66
container[127].i= 28
container[127].j= 36
container[127].angle= 333
container[127].value= 255


container[128].bin= 30
container[128].i= 28
container[128].j= 41
container[128].angle= 153
container[128].value= 255


container[129].bin= 66
container[129].i= 29
container[129].j= 37
container[129].angle= 333
container[129].value= 255


container[130].bin= 30
container[130].i= 29
container[130].j= 41
container[130].angle= 153
container[130].value= 255


container[131].bin= 66
container[131].i= 30
container[131].j= 37
container[131].angle= 333
container[131].value= 255


container[132].bin= 36
container[132].i= 30
container[132].j= 41
container[132].angle= 180
container[132].value= 255


container[133].bin= 66
container[133].i= 31
container[133].j= 38
container[133].angle= 333
container[133].value= 255


container[134].bin= 30
container[134].i= 31
container[134].j= 42
container[134].angle= 153
container[134].value= 255


container[135].bin= 66
container[135].i= 32
container[135].j= 38
container[135].angle= 333
container[135].value= 255


container[136].bin= 30
container[136].i= 32
container[136].j= 42
container[136].angle= 153
container[136].value= 255


container[137].bin= 0
container[137].i= 33
container[137].j= 38
container[137].angle= 0
container[137].value= 255


container[138].bin= 30
container[138].i= 33
container[138].j= 43
container[138].angle= 153
container[138].value= 255


container[139].bin= 66
container[139].i= 34
container[139].j= 39
container[139].angle= 333
container[139].value= 255


container[140].bin= 30
container[140].i= 34
container[140].j= 43
container[140].angle= 153
container[140].value= 255


container[141].bin= 66
container[141].i= 35
container[141].j= 39
container[141].angle= 333
container[141].value= 255


container[142].bin= 30
container[142].i= 35
container[142].j= 44
container[142].angle= 153
container[142].value= 255


container[143].bin= 0
container[143].i= 36
container[143].j= 39
container[143].angle= 0
container[143].value= 255


container[144].bin= 30
container[144].i= 36
container[144].j= 44
container[144].angle= 153
container[144].value= 255


container[145].bin= 0
container[145].i= 37
container[145].j= 39
container[145].angle= 0
container[145].value= 255


container[146].bin= 41
container[146].i= 37
container[146].j= 44
container[146].angle= 206
container[146].value= 255


container[147].bin= 0
container[147].i= 38
container[147].j= 39
container[147].angle= 0
container[147].value= 255


container[148].bin= 41
container[148].i= 38
container[148].j= 44
container[148].angle= 206
container[148].value= 255


container[149].bin= 5
container[149].i= 39
container[149].j= 39
container[149].angle= 26
container[149].value= 255


container[150].bin= 36
container[150].i= 39
container[150].j= 43
container[150].angle= 180
container[150].value= 255


container[151].bin= 0
container[151].i= 40
container[151].j= 39
container[151].angle= 0
container[151].value= 255


container[152].bin= 36
container[152].i= 40
container[152].j= 43
container[152].angle= 180
container[152].value= 255


container[153].bin= 63
container[153].i= 41
container[153].j= 39
container[153].angle= 315
container[153].value= 255


container[154].bin= 63
container[154].i= 41
container[154].j= 40
container[154].angle= 315
container[154].value= 255


container[155].bin= 30
container[155].i= 41
container[155].j= 44
container[155].angle= 153
container[155].value= 255


container[156].bin= 63
container[156].i= 42
container[156].j= 40
container[156].angle= 315
container[156].value= 255


container[157].bin= 63
container[157].i= 42
container[157].j= 41
container[157].angle= 315
container[157].value= 255


container[158].bin= 27
container[158].i= 42
container[158].j= 44
container[158].angle= 135
container[158].value= 255


container[159].bin= 27
container[159].i= 42
container[159].j= 45
container[159].angle= 135
container[159].value= 255


container[160].bin= 63
container[160].i= 43
container[160].j= 41
container[160].angle= 315
container[160].value= 255


container[161].bin= 59
container[161].i= 43
container[161].j= 42
container[161].angle= 296
container[161].value= 255


container[162].bin= 54
container[162].i= 43
container[162].j= 43
container[162].angle= 270
container[162].value= 255


container[163].bin= 32
container[163].i= 43
container[163].j= 45
container[163].angle= 161
container[163].value= 255


container[164].bin= 63
container[164].i= 44
container[164].j= 44
container[164].angle= 315
container[164].value= 255


container[165].bin= 30
container[165].i= 44
container[165].j= 46
container[165].angle= 153
container[165].value= 255


container[166].bin= 68
container[166].i= 45
container[166].j= 44
container[166].angle= 341
container[166].value= 255


container[167].bin= 63
container[167].i= 46
container[167].j= 45
container[167].angle= 315
container[167].value= 255


