container[0].bin= 14
container[0].i= 330
container[0].j= 532
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 330
container[1].j= 533
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 330
container[2].j= 534
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 330
container[3].j= 535
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 330
container[4].j= 536
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 330
container[5].j= 537
container[5].angle= 90
container[5].value= 255


container[6].bin= 3
container[6].i= 331
container[6].j= 532
container[6].angle= 18
container[6].value= 255


container[7].bin= 27
container[7].i= 331
container[7].j= 538
container[7].angle= 135
container[7].value= 255


container[8].bin= 66
container[8].i= 332
container[8].j= 532
container[8].angle= 333
container[8].value= 255


container[9].bin= 36
container[9].i= 332
container[9].j= 538
container[9].angle= 180
container[9].value= 255


container[10].bin= 63
container[10].i= 333
container[10].j= 533
container[10].angle= 315
container[10].value= 255


container[11].bin= 54
container[11].i= 333
container[11].j= 534
container[11].angle= 270
container[11].value= 255


container[12].bin= 54
container[12].i= 333
container[12].j= 535
container[12].angle= 270
container[12].value= 255


container[13].bin= 54
container[13].i= 333
container[13].j= 536
container[13].angle= 270
container[13].value= 255


container[14].bin= 59
container[14].i= 334
container[14].j= 537
container[14].angle= 296
container[14].value= 255


