container[0].bin= 3
container[0].i= 256
container[0].j= 77
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 256
container[1].j= 78
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 256
container[2].j= 79
container[2].angle= 116
container[2].value= 255


container[3].bin= 5
container[3].i= 257
container[3].j= 77
container[3].angle= 26
container[3].value= 255


container[4].bin= 23
container[4].i= 257
container[4].j= 80
container[4].angle= 116
container[4].value= 255


container[5].bin= 23
container[5].i= 257
container[5].j= 81
container[5].angle= 116
container[5].value= 255


container[6].bin= 5
container[6].i= 258
container[6].j= 77
container[6].angle= 26
container[6].value= 255


container[7].bin= 23
container[7].i= 258
container[7].j= 82
container[7].angle= 116
container[7].value= 255


container[8].bin= 23
container[8].i= 258
container[8].j= 83
container[8].angle= 116
container[8].value= 255


container[9].bin= 18
container[9].i= 258
container[9].j= 84
container[9].angle= 90
container[9].value= 255


container[10].bin= 0
container[10].i= 259
container[10].j= 76
container[10].angle= 0
container[10].value= 255


container[11].bin= 23
container[11].i= 259
container[11].j= 85
container[11].angle= 116
container[11].value= 255


container[12].bin= 27
container[12].i= 259
container[12].j= 86
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 260
container[13].j= 76
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 260
container[14].j= 86
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 260
container[15].j= 87
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 261
container[16].j= 76
container[16].angle= 0
container[16].value= 255


container[17].bin= 27
container[17].i= 261
container[17].j= 87
container[17].angle= 135
container[17].value= 255


container[18].bin= 27
container[18].i= 261
container[18].j= 88
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 262
container[19].j= 76
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 262
container[20].j= 88
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 263
container[21].j= 76
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 263
container[22].j= 88
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 264
container[23].j= 76
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 264
container[24].j= 89
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 265
container[25].j= 76
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 265
container[26].j= 89
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 266
container[27].j= 76
container[27].angle= 0
container[27].value= 255


container[28].bin= 30
container[28].i= 266
container[28].j= 90
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 267
container[29].j= 76
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 267
container[30].j= 90
container[30].angle= 153
container[30].value= 255


container[31].bin= 66
container[31].i= 268
container[31].j= 77
container[31].angle= 333
container[31].value= 255


container[32].bin= 30
container[32].i= 268
container[32].j= 91
container[32].angle= 153
container[32].value= 255


container[33].bin= 63
container[33].i= 269
container[33].j= 77
container[33].angle= 315
container[33].value= 255


container[34].bin= 59
container[34].i= 269
container[34].j= 78
container[34].angle= 296
container[34].value= 255


container[35].bin= 54
container[35].i= 269
container[35].j= 79
container[35].angle= 270
container[35].value= 255


container[36].bin= 27
container[36].i= 269
container[36].j= 91
container[36].angle= 135
container[36].value= 255


container[37].bin= 27
container[37].i= 269
container[37].j= 92
container[37].angle= 135
container[37].value= 255


container[38].bin= 59
container[38].i= 270
container[38].j= 80
container[38].angle= 296
container[38].value= 255


container[39].bin= 63
container[39].i= 270
container[39].j= 81
container[39].angle= 315
container[39].value= 255


container[40].bin= 30
container[40].i= 270
container[40].j= 92
container[40].angle= 153
container[40].value= 255


container[41].bin= 63
container[41].i= 271
container[41].j= 81
container[41].angle= 315
container[41].value= 255


container[42].bin= 59
container[42].i= 271
container[42].j= 82
container[42].angle= 296
container[42].value= 255


container[43].bin= 30
container[43].i= 271
container[43].j= 93
container[43].angle= 153
container[43].value= 255


container[44].bin= 59
container[44].i= 272
container[44].j= 83
container[44].angle= 296
container[44].value= 255


container[45].bin= 63
container[45].i= 272
container[45].j= 84
container[45].angle= 315
container[45].value= 255


container[46].bin= 30
container[46].i= 272
container[46].j= 93
container[46].angle= 153
container[46].value= 255


container[47].bin= 63
container[47].i= 273
container[47].j= 84
container[47].angle= 315
container[47].value= 255


container[48].bin= 63
container[48].i= 273
container[48].j= 85
container[48].angle= 315
container[48].value= 255


container[49].bin= 30
container[49].i= 273
container[49].j= 94
container[49].angle= 153
container[49].value= 255


container[50].bin= 63
container[50].i= 274
container[50].j= 85
container[50].angle= 315
container[50].value= 255


container[51].bin= 63
container[51].i= 274
container[51].j= 86
container[51].angle= 315
container[51].value= 255


container[52].bin= 27
container[52].i= 274
container[52].j= 94
container[52].angle= 135
container[52].value= 255


container[53].bin= 27
container[53].i= 274
container[53].j= 95
container[53].angle= 135
container[53].value= 255


container[54].bin= 63
container[54].i= 275
container[54].j= 86
container[54].angle= 315
container[54].value= 255


container[55].bin= 63
container[55].i= 275
container[55].j= 87
container[55].angle= 315
container[55].value= 255


container[56].bin= 30
container[56].i= 275
container[56].j= 95
container[56].angle= 153
container[56].value= 255


container[57].bin= 66
container[57].i= 276
container[57].j= 87
container[57].angle= 333
container[57].value= 255


container[58].bin= 30
container[58].i= 276
container[58].j= 96
container[58].angle= 153
container[58].value= 255


container[59].bin= 63
container[59].i= 277
container[59].j= 88
container[59].angle= 315
container[59].value= 255


container[60].bin= 30
container[60].i= 277
container[60].j= 96
container[60].angle= 153
container[60].value= 255


container[61].bin= 63
container[61].i= 278
container[61].j= 89
container[61].angle= 315
container[61].value= 255


container[62].bin= 30
container[62].i= 278
container[62].j= 97
container[62].angle= 153
container[62].value= 255


container[63].bin= 66
container[63].i= 279
container[63].j= 90
container[63].angle= 333
container[63].value= 255


container[64].bin= 30
container[64].i= 279
container[64].j= 97
container[64].angle= 153
container[64].value= 255


container[65].bin= 63
container[65].i= 280
container[65].j= 90
container[65].angle= 315
container[65].value= 255


container[66].bin= 63
container[66].i= 280
container[66].j= 91
container[66].angle= 315
container[66].value= 255


container[67].bin= 36
container[67].i= 280
container[67].j= 97
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 281
container[68].j= 91
container[68].angle= 315
container[68].value= 255


container[69].bin= 63
container[69].i= 281
container[69].j= 92
container[69].angle= 315
container[69].value= 255


container[70].bin= 30
container[70].i= 281
container[70].j= 98
container[70].angle= 153
container[70].value= 255


container[71].bin= 63
container[71].i= 282
container[71].j= 92
container[71].angle= 315
container[71].value= 255


container[72].bin= 63
container[72].i= 282
container[72].j= 93
container[72].angle= 315
container[72].value= 255


container[73].bin= 27
container[73].i= 282
container[73].j= 98
container[73].angle= 135
container[73].value= 255


container[74].bin= 27
container[74].i= 282
container[74].j= 99
container[74].angle= 135
container[74].value= 255


container[75].bin= 63
container[75].i= 283
container[75].j= 93
container[75].angle= 315
container[75].value= 255


container[76].bin= 63
container[76].i= 283
container[76].j= 94
container[76].angle= 315
container[76].value= 255


container[77].bin= 30
container[77].i= 283
container[77].j= 99
container[77].angle= 153
container[77].value= 255


container[78].bin= 66
container[78].i= 284
container[78].j= 94
container[78].angle= 333
container[78].value= 255


container[79].bin= 30
container[79].i= 284
container[79].j= 100
container[79].angle= 153
container[79].value= 255


container[80].bin= 66
container[80].i= 285
container[80].j= 95
container[80].angle= 333
container[80].value= 255


container[81].bin= 27
container[81].i= 285
container[81].j= 100
container[81].angle= 135
container[81].value= 255


container[82].bin= 27
container[82].i= 285
container[82].j= 101
container[82].angle= 135
container[82].value= 255


container[83].bin= 63
container[83].i= 286
container[83].j= 95
container[83].angle= 315
container[83].value= 255


container[84].bin= 63
container[84].i= 286
container[84].j= 96
container[84].angle= 315
container[84].value= 255


container[85].bin= 27
container[85].i= 286
container[85].j= 101
container[85].angle= 135
container[85].value= 255


container[86].bin= 27
container[86].i= 286
container[86].j= 102
container[86].angle= 135
container[86].value= 255


container[87].bin= 63
container[87].i= 287
container[87].j= 96
container[87].angle= 315
container[87].value= 255


container[88].bin= 63
container[88].i= 287
container[88].j= 97
container[88].angle= 315
container[88].value= 255


container[89].bin= 27
container[89].i= 287
container[89].j= 102
container[89].angle= 135
container[89].value= 255


container[90].bin= 27
container[90].i= 287
container[90].j= 103
container[90].angle= 135
container[90].value= 255


container[91].bin= 66
container[91].i= 288
container[91].j= 97
container[91].angle= 333
container[91].value= 255


container[92].bin= 27
container[92].i= 288
container[92].j= 103
container[92].angle= 135
container[92].value= 255


container[93].bin= 27
container[93].i= 288
container[93].j= 104
container[93].angle= 135
container[93].value= 255


container[94].bin= 66
container[94].i= 289
container[94].j= 98
container[94].angle= 333
container[94].value= 255


container[95].bin= 27
container[95].i= 289
container[95].j= 104
container[95].angle= 135
container[95].value= 255


container[96].bin= 27
container[96].i= 289
container[96].j= 105
container[96].angle= 135
container[96].value= 255


container[97].bin= 63
container[97].i= 290
container[97].j= 98
container[97].angle= 315
container[97].value= 255


container[98].bin= 63
container[98].i= 290
container[98].j= 99
container[98].angle= 315
container[98].value= 255


container[99].bin= 30
container[99].i= 290
container[99].j= 105
container[99].angle= 153
container[99].value= 255


container[100].bin= 63
container[100].i= 291
container[100].j= 99
container[100].angle= 315
container[100].value= 255


container[101].bin= 63
container[101].i= 291
container[101].j= 100
container[101].angle= 315
container[101].value= 255


container[102].bin= 36
container[102].i= 291
container[102].j= 105
container[102].angle= 180
container[102].value= 255


container[103].bin= 66
container[103].i= 292
container[103].j= 100
container[103].angle= 333
container[103].value= 255


container[104].bin= 30
container[104].i= 292
container[104].j= 106
container[104].angle= 153
container[104].value= 255


container[105].bin= 66
container[105].i= 293
container[105].j= 101
container[105].angle= 333
container[105].value= 255


container[106].bin= 27
container[106].i= 293
container[106].j= 106
container[106].angle= 135
container[106].value= 255


container[107].bin= 27
container[107].i= 293
container[107].j= 107
container[107].angle= 135
container[107].value= 255


container[108].bin= 66
container[108].i= 294
container[108].j= 101
container[108].angle= 333
container[108].value= 255


container[109].bin= 27
container[109].i= 294
container[109].j= 107
container[109].angle= 135
container[109].value= 255


container[110].bin= 27
container[110].i= 294
container[110].j= 108
container[110].angle= 135
container[110].value= 255


container[111].bin= 0
container[111].i= 295
container[111].j= 101
container[111].angle= 0
container[111].value= 255


container[112].bin= 27
container[112].i= 295
container[112].j= 108
container[112].angle= 135
container[112].value= 255


container[113].bin= 27
container[113].i= 295
container[113].j= 109
container[113].angle= 135
container[113].value= 255


container[114].bin= 66
container[114].i= 296
container[114].j= 102
container[114].angle= 333
container[114].value= 255


container[115].bin= 27
container[115].i= 296
container[115].j= 109
container[115].angle= 135
container[115].value= 255


container[116].bin= 27
container[116].i= 296
container[116].j= 110
container[116].angle= 135
container[116].value= 255


container[117].bin= 66
container[117].i= 297
container[117].j= 102
container[117].angle= 333
container[117].value= 255


container[118].bin= 27
container[118].i= 297
container[118].j= 110
container[118].angle= 135
container[118].value= 255


container[119].bin= 27
container[119].i= 297
container[119].j= 111
container[119].angle= 135
container[119].value= 255


container[120].bin= 0
container[120].i= 298
container[120].j= 102
container[120].angle= 0
container[120].value= 255


container[121].bin= 30
container[121].i= 298
container[121].j= 111
container[121].angle= 153
container[121].value= 255


container[122].bin= 66
container[122].i= 299
container[122].j= 103
container[122].angle= 333
container[122].value= 255


container[123].bin= 30
container[123].i= 299
container[123].j= 112
container[123].angle= 153
container[123].value= 255


container[124].bin= 66
container[124].i= 300
container[124].j= 103
container[124].angle= 333
container[124].value= 255


container[125].bin= 30
container[125].i= 300
container[125].j= 112
container[125].angle= 153
container[125].value= 255


container[126].bin= 0
container[126].i= 301
container[126].j= 103
container[126].angle= 0
container[126].value= 255


container[127].bin= 30
container[127].i= 301
container[127].j= 113
container[127].angle= 153
container[127].value= 255


container[128].bin= 5
container[128].i= 302
container[128].j= 103
container[128].angle= 26
container[128].value= 255


container[129].bin= 27
container[129].i= 302
container[129].j= 113
container[129].angle= 135
container[129].value= 255


container[130].bin= 27
container[130].i= 302
container[130].j= 114
container[130].angle= 135
container[130].value= 255


container[131].bin= 5
container[131].i= 303
container[131].j= 103
container[131].angle= 26
container[131].value= 255


container[132].bin= 30
container[132].i= 303
container[132].j= 114
container[132].angle= 153
container[132].value= 255


container[133].bin= 0
container[133].i= 304
container[133].j= 102
container[133].angle= 0
container[133].value= 255


container[134].bin= 30
container[134].i= 304
container[134].j= 115
container[134].angle= 153
container[134].value= 255


container[135].bin= 5
container[135].i= 305
container[135].j= 102
container[135].angle= 26
container[135].value= 255


container[136].bin= 27
container[136].i= 305
container[136].j= 115
container[136].angle= 135
container[136].value= 255


container[137].bin= 27
container[137].i= 305
container[137].j= 116
container[137].angle= 135
container[137].value= 255


container[138].bin= 0
container[138].i= 306
container[138].j= 102
container[138].angle= 0
container[138].value= 255


container[139].bin= 30
container[139].i= 306
container[139].j= 116
container[139].angle= 153
container[139].value= 255


container[140].bin= 63
container[140].i= 307
container[140].j= 102
container[140].angle= 315
container[140].value= 255


container[141].bin= 63
container[141].i= 307
container[141].j= 103
container[141].angle= 315
container[141].value= 255


container[142].bin= 30
container[142].i= 307
container[142].j= 117
container[142].angle= 153
container[142].value= 255


container[143].bin= 63
container[143].i= 308
container[143].j= 103
container[143].angle= 315
container[143].value= 255


container[144].bin= 63
container[144].i= 308
container[144].j= 104
container[144].angle= 315
container[144].value= 255


container[145].bin= 27
container[145].i= 308
container[145].j= 117
container[145].angle= 135
container[145].value= 255


container[146].bin= 27
container[146].i= 308
container[146].j= 118
container[146].angle= 135
container[146].value= 255


container[147].bin= 63
container[147].i= 309
container[147].j= 104
container[147].angle= 315
container[147].value= 255


container[148].bin= 63
container[148].i= 309
container[148].j= 105
container[148].angle= 315
container[148].value= 255


container[149].bin= 30
container[149].i= 309
container[149].j= 118
container[149].angle= 153
container[149].value= 255


container[150].bin= 63
container[150].i= 310
container[150].j= 105
container[150].angle= 315
container[150].value= 255


container[151].bin= 63
container[151].i= 310
container[151].j= 106
container[151].angle= 315
container[151].value= 255


container[152].bin= 30
container[152].i= 310
container[152].j= 119
container[152].angle= 153
container[152].value= 255


container[153].bin= 63
container[153].i= 311
container[153].j= 106
container[153].angle= 315
container[153].value= 255


container[154].bin= 63
container[154].i= 311
container[154].j= 107
container[154].angle= 315
container[154].value= 255


container[155].bin= 30
container[155].i= 311
container[155].j= 119
container[155].angle= 153
container[155].value= 255


container[156].bin= 63
container[156].i= 312
container[156].j= 107
container[156].angle= 315
container[156].value= 255


container[157].bin= 63
container[157].i= 312
container[157].j= 108
container[157].angle= 315
container[157].value= 255


container[158].bin= 36
container[158].i= 312
container[158].j= 119
container[158].angle= 180
container[158].value= 255


container[159].bin= 63
container[159].i= 313
container[159].j= 108
container[159].angle= 315
container[159].value= 255


container[160].bin= 63
container[160].i= 313
container[160].j= 109
container[160].angle= 315
container[160].value= 255


container[161].bin= 30
container[161].i= 313
container[161].j= 120
container[161].angle= 153
container[161].value= 255


container[162].bin= 63
container[162].i= 314
container[162].j= 109
container[162].angle= 315
container[162].value= 255


container[163].bin= 63
container[163].i= 314
container[163].j= 110
container[163].angle= 315
container[163].value= 255


container[164].bin= 30
container[164].i= 314
container[164].j= 120
container[164].angle= 153
container[164].value= 255


container[165].bin= 66
container[165].i= 315
container[165].j= 110
container[165].angle= 333
container[165].value= 255


container[166].bin= 30
container[166].i= 315
container[166].j= 121
container[166].angle= 153
container[166].value= 255


container[167].bin= 66
container[167].i= 316
container[167].j= 111
container[167].angle= 333
container[167].value= 255


container[168].bin= 30
container[168].i= 316
container[168].j= 121
container[168].angle= 153
container[168].value= 255


container[169].bin= 63
container[169].i= 317
container[169].j= 111
container[169].angle= 315
container[169].value= 255


container[170].bin= 63
container[170].i= 317
container[170].j= 112
container[170].angle= 315
container[170].value= 255


container[171].bin= 30
container[171].i= 317
container[171].j= 122
container[171].angle= 153
container[171].value= 255


container[172].bin= 66
container[172].i= 318
container[172].j= 112
container[172].angle= 333
container[172].value= 255


container[173].bin= 30
container[173].i= 318
container[173].j= 122
container[173].angle= 153
container[173].value= 255


container[174].bin= 63
container[174].i= 319
container[174].j= 113
container[174].angle= 315
container[174].value= 255


container[175].bin= 30
container[175].i= 319
container[175].j= 123
container[175].angle= 153
container[175].value= 255


container[176].bin= 59
container[176].i= 320
container[176].j= 114
container[176].angle= 296
container[176].value= 255


container[177].bin= 63
container[177].i= 320
container[177].j= 115
container[177].angle= 315
container[177].value= 255


container[178].bin= 27
container[178].i= 320
container[178].j= 123
container[178].angle= 135
container[178].value= 255


container[179].bin= 27
container[179].i= 320
container[179].j= 124
container[179].angle= 135
container[179].value= 255


container[180].bin= 63
container[180].i= 321
container[180].j= 115
container[180].angle= 315
container[180].value= 255


container[181].bin= 59
container[181].i= 321
container[181].j= 116
container[181].angle= 296
container[181].value= 255


container[182].bin= 30
container[182].i= 321
container[182].j= 124
container[182].angle= 153
container[182].value= 255


container[183].bin= 59
container[183].i= 322
container[183].j= 117
container[183].angle= 296
container[183].value= 255


container[184].bin= 59
container[184].i= 322
container[184].j= 118
container[184].angle= 296
container[184].value= 255


container[185].bin= 27
container[185].i= 322
container[185].j= 125
container[185].angle= 135
container[185].value= 255


container[186].bin= 59
container[186].i= 323
container[186].j= 119
container[186].angle= 296
container[186].value= 255


container[187].bin= 59
container[187].i= 323
container[187].j= 120
container[187].angle= 296
container[187].value= 255


container[188].bin= 27
container[188].i= 323
container[188].j= 126
container[188].angle= 135
container[188].value= 255


container[189].bin= 59
container[189].i= 324
container[189].j= 121
container[189].angle= 296
container[189].value= 255


container[190].bin= 59
container[190].i= 324
container[190].j= 122
container[190].angle= 296
container[190].value= 255


container[191].bin= 30
container[191].i= 324
container[191].j= 127
container[191].angle= 153
container[191].value= 255


container[192].bin= 59
container[192].i= 325
container[192].j= 123
container[192].angle= 296
container[192].value= 255


container[193].bin= 63
container[193].i= 325
container[193].j= 124
container[193].angle= 315
container[193].value= 255


container[194].bin= 30
container[194].i= 325
container[194].j= 127
container[194].angle= 153
container[194].value= 255


container[195].bin= 63
container[195].i= 326
container[195].j= 124
container[195].angle= 315
container[195].value= 255


container[196].bin= 63
container[196].i= 326
container[196].j= 125
container[196].angle= 315
container[196].value= 255


container[197].bin= 30
container[197].i= 326
container[197].j= 128
container[197].angle= 153
container[197].value= 255


container[198].bin= 63
container[198].i= 327
container[198].j= 125
container[198].angle= 315
container[198].value= 255


container[199].bin= 59
container[199].i= 327
container[199].j= 126
container[199].angle= 296
container[199].value= 255


container[200].bin= 32
container[200].i= 327
container[200].j= 128
container[200].angle= 161
container[200].value= 255


container[201].bin= 59
container[201].i= 328
container[201].j= 127
container[201].angle= 296
container[201].value= 255


