container[0].bin= 18
container[0].i= 643
container[0].j= 360
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 644
container[1].j= 359
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 644
container[2].j= 361
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 645
container[3].j= 359
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 645
container[4].j= 361
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 646
container[5].j= 359
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 646
container[6].j= 361
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 647
container[7].j= 358
container[7].angle= 44
container[7].value= 255


container[8].bin= 0
container[8].i= 648
container[8].j= 357
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 648
container[9].j= 360
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 649
container[10].j= 357
container[10].angle= 26
container[10].value= 255


container[11].bin= 44
container[11].i= 649
container[11].j= 360
container[11].angle= 224
container[11].value= 255


container[12].bin= 5
container[12].i= 650
container[12].j= 357
container[12].angle= 26
container[12].value= 255


container[13].bin= 44
container[13].i= 650
container[13].j= 359
container[13].angle= 224
container[13].value= 255


container[14].bin= 0
container[14].i= 651
container[14].j= 356
container[14].angle= 0
container[14].value= 255


container[15].bin= 63
container[15].i= 652
container[15].j= 357
container[15].angle= 315
container[15].value= 255


container[16].bin= 44
container[16].i= 652
container[16].j= 358
container[16].angle= 224
container[16].value= 255


