container[0].bin= 8
container[0].i= 481
container[0].j= 384
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 481
container[1].j= 385
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 482
container[2].j= 383
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 483
container[3].j= 383
container[3].angle= 0
container[3].value= 255


container[4].bin= 21
container[4].i= 483
container[4].j= 387
container[4].angle= 108
container[4].value= 255


container[5].bin= 0
container[5].i= 484
container[5].j= 383
container[5].angle= 0
container[5].value= 255


container[6].bin= 68
container[6].i= 485
container[6].j= 383
container[6].angle= 341
container[6].value= 255


container[7].bin= 68
container[7].i= 485
container[7].j= 386
container[7].angle= 341
container[7].value= 255


container[8].bin= 36
container[8].i= 485
container[8].j= 388
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 486
container[9].j= 384
container[9].angle= 315
container[9].value= 255


container[10].bin= 39
container[10].i= 486
container[10].j= 388
container[10].angle= 198
container[10].value= 255


