container[0].bin= 18
container[0].i= 622
container[0].j= 184
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 623
container[1].j= 183
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 623
container[2].j= 185
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 624
container[3].j= 182
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 624
container[4].j= 185
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 625
container[5].j= 183
container[5].angle= 315
container[5].value= 255


container[6].bin= 59
container[6].i= 626
container[6].j= 184
container[6].angle= 296
container[6].value= 255


