container[0].bin= 18
container[0].i= 507
container[0].j= 120
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 507
container[1].j= 121
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 508
container[2].j= 118
container[2].angle= 44
container[2].value= 255


container[3].bin= 12
container[3].i= 508
container[3].j= 119
container[3].angle= 63
container[3].value= 255


container[4].bin= 27
container[4].i= 508
container[4].j= 122
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 509
container[5].j= 118
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 509
container[6].j= 122
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 510
container[7].j= 118
container[7].angle= 315
container[7].value= 255


container[8].bin= 59
container[8].i= 510
container[8].j= 119
container[8].angle= 296
container[8].value= 255


container[9].bin= 54
container[9].i= 510
container[9].j= 120
container[9].angle= 270
container[9].value= 255


container[10].bin= 54
container[10].i= 510
container[10].j= 121
container[10].angle= 270
container[10].value= 255


container[11].bin= 44
container[11].i= 510
container[11].j= 122
container[11].angle= 224
container[11].value= 255


