container[0].bin= 14
container[0].i= 848
container[0].j= 428
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 848
container[1].j= 429
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 849
container[2].j= 428
container[2].angle= 18
container[2].value= 255


container[3].bin= 27
container[3].i= 849
container[3].j= 430
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 850
container[4].j= 428
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 850
container[5].j= 430
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 851
container[6].j= 428
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 851
container[7].j= 431
container[7].angle= 135
container[7].value= 255


container[8].bin= 21
container[8].i= 851
container[8].j= 432
container[8].angle= 108
container[8].value= 255


container[9].bin= 66
container[9].i= 852
container[9].j= 428
container[9].angle= 333
container[9].value= 255


container[10].bin= 0
container[10].i= 853
container[10].j= 428
container[10].angle= 0
container[10].value= 255


container[11].bin= 39
container[11].i= 853
container[11].j= 431
container[11].angle= 198
container[11].value= 255


container[12].bin= 44
container[12].i= 853
container[12].j= 432
container[12].angle= 224
container[12].value= 255


container[13].bin= 0
container[13].i= 854
container[13].j= 428
container[13].angle= 0
container[13].value= 255


container[14].bin= 0
container[14].i= 855
container[14].j= 428
container[14].angle= 0
container[14].value= 255


container[15].bin= 44
container[15].i= 855
container[15].j= 430
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 856
container[16].j= 428
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 856
container[17].j= 430
container[17].angle= 180
container[17].value= 255


container[18].bin= 68
container[18].i= 857
container[18].j= 428
container[18].angle= 341
container[18].value= 255


container[19].bin= 54
container[19].i= 857
container[19].j= 429
container[19].angle= 270
container[19].value= 255


container[20].bin= 39
container[20].i= 857
container[20].j= 430
container[20].angle= 198
container[20].value= 255


