container[0].bin= 8
container[0].i= 268
container[0].j= 59
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 268
container[1].j= 60
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 268
container[2].j= 61
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 269
container[3].j= 58
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 269
container[4].j= 59
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 269
container[5].j= 61
container[5].angle= 135
container[5].value= 255


container[6].bin= 27
container[6].i= 269
container[6].j= 62
container[6].angle= 135
container[6].value= 255


container[7].bin= 8
container[7].i= 270
container[7].j= 57
container[7].angle= 44
container[7].value= 255


container[8].bin= 8
container[8].i= 270
container[8].j= 58
container[8].angle= 44
container[8].value= 255


container[9].bin= 27
container[9].i= 270
container[9].j= 62
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 270
container[10].j= 63
container[10].angle= 135
container[10].value= 255


container[11].bin= 5
container[11].i= 271
container[11].j= 57
container[11].angle= 26
container[11].value= 255


container[12].bin= 27
container[12].i= 271
container[12].j= 63
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 271
container[13].j= 64
container[13].angle= 135
container[13].value= 255


container[14].bin= 5
container[14].i= 272
container[14].j= 56
container[14].angle= 26
container[14].value= 255


container[15].bin= 27
container[15].i= 272
container[15].j= 64
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 272
container[16].j= 65
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 273
container[17].j= 56
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 273
container[18].j= 65
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 274
container[19].j= 56
container[19].angle= 333
container[19].value= 255


container[20].bin= 36
container[20].i= 274
container[20].j= 65
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 275
container[21].j= 56
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 275
container[22].j= 65
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 276
container[23].j= 56
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 276
container[24].j= 66
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 277
container[25].j= 56
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 277
container[26].j= 66
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 278
container[27].j= 57
container[27].angle= 333
container[27].value= 255


container[28].bin= 36
container[28].i= 278
container[28].j= 66
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 279
container[29].j= 57
container[29].angle= 315
container[29].value= 255


container[30].bin= 63
container[30].i= 279
container[30].j= 58
container[30].angle= 315
container[30].value= 255


container[31].bin= 30
container[31].i= 279
container[31].j= 67
container[31].angle= 153
container[31].value= 255


container[32].bin= 63
container[32].i= 280
container[32].j= 58
container[32].angle= 315
container[32].value= 255


container[33].bin= 59
container[33].i= 280
container[33].j= 59
container[33].angle= 296
container[33].value= 255


container[34].bin= 30
container[34].i= 280
container[34].j= 67
container[34].angle= 153
container[34].value= 255


container[35].bin= 59
container[35].i= 281
container[35].j= 60
container[35].angle= 296
container[35].value= 255


container[36].bin= 59
container[36].i= 281
container[36].j= 61
container[36].angle= 296
container[36].value= 255


container[37].bin= 54
container[37].i= 281
container[37].j= 62
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 281
container[38].j= 63
container[38].angle= 270
container[38].value= 255


container[39].bin= 30
container[39].i= 281
container[39].j= 68
container[39].angle= 153
container[39].value= 255


container[40].bin= 59
container[40].i= 282
container[40].j= 64
container[40].angle= 296
container[40].value= 255


container[41].bin= 59
container[41].i= 282
container[41].j= 65
container[41].angle= 296
container[41].value= 255


container[42].bin= 59
container[42].i= 283
container[42].j= 66
container[42].angle= 296
container[42].value= 255


container[43].bin= 44
container[43].i= 283
container[43].j= 68
container[43].angle= 224
container[43].value= 255


