container[0].bin= 18
container[0].i= 277
container[0].j= 402
container[0].angle= 90
container[0].value= 255


container[1].bin= 14
container[1].i= 278
container[1].j= 400
container[1].angle= 71
container[1].value= 255


container[2].bin= 14
container[2].i= 278
container[2].j= 401
container[2].angle= 71
container[2].value= 255


container[3].bin= 3
container[3].i= 279
container[3].j= 399
container[3].angle= 18
container[3].value= 255


container[4].bin= 68
container[4].i= 280
container[4].j= 399
container[4].angle= 341
container[4].value= 255


container[5].bin= 44
container[5].i= 280
container[5].j= 401
container[5].angle= 224
container[5].value= 255


