container[0].bin= 8
container[0].i= 518
container[0].j= 500
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 518
container[1].j= 501
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 519
container[2].j= 500
container[2].angle= 26
container[2].value= 255


container[3].bin= 0
container[3].i= 520
container[3].j= 499
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 520
container[4].j= 502
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 521
container[5].j= 499
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 521
container[6].j= 502
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 522
container[7].j= 500
container[7].angle= 333
container[7].value= 255


container[8].bin= 41
container[8].i= 522
container[8].j= 502
container[8].angle= 206
container[8].value= 255


container[9].bin= 66
container[9].i= 523
container[9].j= 500
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 523
container[10].j= 502
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 524
container[11].j= 500
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 524
container[12].j= 502
container[12].angle= 180
container[12].value= 255


container[13].bin= 68
container[13].i= 525
container[13].j= 500
container[13].angle= 341
container[13].value= 255


container[14].bin= 54
container[14].i= 525
container[14].j= 501
container[14].angle= 270
container[14].value= 255


container[15].bin= 39
container[15].i= 525
container[15].j= 502
container[15].angle= 198
container[15].value= 255


