container[0].bin= 18
container[0].i= 234
container[0].j= 310
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 235
container[1].j= 309
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 235
container[2].j= 311
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 236
container[3].j= 309
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 236
container[4].j= 311
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 237
container[5].j= 309
container[5].angle= 341
container[5].value= 255


container[6].bin= 27
container[6].i= 237
container[6].j= 311
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 237
container[7].j= 312
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 237
container[8].j= 313
container[8].angle= 90
container[8].value= 255


container[9].bin= 0
container[9].i= 238
container[9].j= 309
container[9].angle= 0
container[9].value= 255


container[10].bin= 23
container[10].i= 238
container[10].j= 314
container[10].angle= 116
container[10].value= 255


container[11].bin= 27
container[11].i= 238
container[11].j= 315
container[11].angle= 135
container[11].value= 255


container[12].bin= 3
container[12].i= 239
container[12].j= 309
container[12].angle= 18
container[12].value= 255


container[13].bin= 8
container[13].i= 239
container[13].j= 310
container[13].angle= 44
container[13].value= 255


container[14].bin= 30
container[14].i= 239
container[14].j= 315
container[14].angle= 153
container[14].value= 255


container[15].bin= 68
container[15].i= 240
container[15].j= 309
container[15].angle= 341
container[15].value= 255


container[16].bin= 63
container[16].i= 240
container[16].j= 310
container[16].angle= 315
container[16].value= 255


container[17].bin= 30
container[17].i= 240
container[17].j= 316
container[17].angle= 153
container[17].value= 255


container[18].bin= 63
container[18].i= 241
container[18].j= 311
container[18].angle= 315
container[18].value= 255


container[19].bin= 30
container[19].i= 241
container[19].j= 316
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 242
container[20].j= 311
container[20].angle= 0
container[20].value= 255


container[21].bin= 41
container[21].i= 242
container[21].j= 316
container[21].angle= 206
container[21].value= 255


container[22].bin= 66
container[22].i= 243
container[22].j= 312
container[22].angle= 333
container[22].value= 255


container[23].bin= 41
container[23].i= 243
container[23].j= 316
container[23].angle= 206
container[23].value= 255


container[24].bin= 66
container[24].i= 244
container[24].j= 312
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 244
container[25].j= 315
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 245
container[26].j= 312
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 245
container[27].j= 315
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 246
container[28].j= 313
container[28].angle= 315
container[28].value= 255


container[29].bin= 54
container[29].i= 246
container[29].j= 314
container[29].angle= 270
container[29].value= 255


container[30].bin= 44
container[30].i= 246
container[30].j= 315
container[30].angle= 224
container[30].value= 255


