container[0].bin= 0
container[0].i= 0
container[0].j= 81
container[0].angle= 0
container[0].value= 255


container[1].bin= 36
container[1].i= 0
container[1].j= 84
container[1].angle= 180
container[1].value= 255


container[2].bin= 66
container[2].i= 1
container[2].j= 82
container[2].angle= 333
container[2].value= 255


container[3].bin= 36
container[3].i= 1
container[3].j= 84
container[3].angle= 180
container[3].value= 255


container[4].bin= 0
container[4].i= 2
container[4].j= 82
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 2
container[5].j= 85
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 3
container[6].j= 82
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 3
container[7].j= 85
container[7].angle= 153
container[7].value= 255


container[8].bin= 63
container[8].i= 4
container[8].j= 82
container[8].angle= 315
container[8].value= 255


container[9].bin= 63
container[9].i= 4
container[9].j= 83
container[9].angle= 315
container[9].value= 255


container[10].bin= 36
container[10].i= 4
container[10].j= 85
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 5
container[11].j= 83
container[11].angle= 333
container[11].value= 255


container[12].bin= 63
container[12].i= 6
container[12].j= 84
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 6
container[13].j= 85
container[13].angle= 224
container[13].value= 255


