container[0].bin= 18
container[0].i= 393
container[0].j= 193
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 394
container[1].j= 192
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 394
container[2].j= 194
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 395
container[3].j= 192
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 395
container[4].j= 194
container[4].angle= 153
container[4].value= 255


container[5].bin= 68
container[5].i= 396
container[5].j= 192
container[5].angle= 341
container[5].value= 255


