container[0].bin= 3
container[0].i= 258
container[0].j= 2
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 258
container[1].j= 3
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 258
container[2].j= 4
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 259
container[3].j= 2
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 259
container[4].j= 4
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 259
container[5].j= 5
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 260
container[6].j= 2
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 260
container[7].j= 5
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 260
container[8].j= 6
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 261
container[9].j= 2
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 261
container[10].j= 6
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 262
container[11].j= 3
container[11].angle= 333
container[11].value= 255


container[12].bin= 41
container[12].i= 262
container[12].j= 6
container[12].angle= 206
container[12].value= 255


container[13].bin= 63
container[13].i= 263
container[13].j= 3
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 263
container[14].j= 4
container[14].angle= 315
container[14].value= 255


container[15].bin= 41
container[15].i= 263
container[15].j= 6
container[15].angle= 206
container[15].value= 255


container[16].bin= 63
container[16].i= 264
container[16].j= 4
container[16].angle= 315
container[16].value= 255


