container[0].bin= 18
container[0].i= 468
container[0].j= 128
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 468
container[1].j= 129
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 469
container[2].j= 127
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 469
container[3].j= 130
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 470
container[4].j= 126
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 470
container[5].j= 130
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 471
container[6].j= 126
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 471
container[7].j= 130
container[7].angle= 180
container[7].value= 255


container[8].bin= 5
container[8].i= 472
container[8].j= 126
container[8].angle= 26
container[8].value= 255


container[9].bin= 36
container[9].i= 472
container[9].j= 130
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 473
container[10].j= 126
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 473
container[11].j= 130
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 474
container[12].j= 126
container[12].angle= 315
container[12].value= 255


container[13].bin= 59
container[13].i= 474
container[13].j= 127
container[13].angle= 296
container[13].value= 255


container[14].bin= 27
container[14].i= 474
container[14].j= 131
container[14].angle= 135
container[14].value= 255


container[15].bin= 18
container[15].i= 474
container[15].j= 132
container[15].angle= 90
container[15].value= 255


container[16].bin= 63
container[16].i= 475
container[16].j= 128
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 475
container[17].j= 133
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 476
container[18].j= 128
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 476
container[19].j= 133
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 477
container[20].j= 129
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 477
container[21].j= 130
container[21].angle= 270
container[21].value= 255


container[22].bin= 27
container[22].i= 477
container[22].j= 134
container[22].angle= 135
container[22].value= 255


container[23].bin= 63
container[23].i= 478
container[23].j= 131
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 478
container[24].j= 135
container[24].angle= 135
container[24].value= 255


container[25].bin= 66
container[25].i= 479
container[25].j= 132
container[25].angle= 333
container[25].value= 255


container[26].bin= 36
container[26].i= 479
container[26].j= 135
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 480
container[27].j= 132
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 480
container[28].j= 133
container[28].angle= 296
container[28].value= 255


container[29].bin= 54
container[29].i= 480
container[29].j= 134
container[29].angle= 270
container[29].value= 255


container[30].bin= 44
container[30].i= 480
container[30].j= 135
container[30].angle= 224
container[30].value= 255


