container[0].bin= 8
container[0].i= 223
container[0].j= 373
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 223
container[1].j= 374
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 224
container[2].j= 372
container[2].angle= 0
container[2].value= 255


container[3].bin= 18
container[3].i= 225
container[3].j= 369
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 225
container[4].j= 370
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 225
container[5].j= 371
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 225
container[6].j= 372
container[6].angle= 44
container[6].value= 255


container[7].bin= 8
container[7].i= 226
container[7].j= 368
container[7].angle= 44
container[7].value= 255


container[8].bin= 36
container[8].i= 226
container[8].j= 374
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 227
container[9].j= 367
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 227
container[10].j= 374
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 228
container[11].j= 368
container[11].angle= 315
container[11].value= 255


container[12].bin= 36
container[12].i= 228
container[12].j= 374
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 229
container[13].j= 369
container[13].angle= 315
container[13].value= 255


container[14].bin= 36
container[14].i= 229
container[14].j= 374
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 230
container[15].j= 369
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 230
container[16].j= 374
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 231
container[17].j= 369
container[17].angle= 0
container[17].value= 255


container[18].bin= 44
container[18].i= 231
container[18].j= 374
container[18].angle= 224
container[18].value= 255


container[19].bin= 0
container[19].i= 232
container[19].j= 369
container[19].angle= 0
container[19].value= 255


container[20].bin= 44
container[20].i= 232
container[20].j= 373
container[20].angle= 224
container[20].value= 255


container[21].bin= 0
container[21].i= 233
container[21].j= 369
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 233
container[22].j= 372
container[22].angle= 180
container[22].value= 255


container[23].bin= 66
container[23].i= 234
container[23].j= 370
container[23].angle= 333
container[23].value= 255


container[24].bin= 36
container[24].i= 234
container[24].j= 372
container[24].angle= 180
container[24].value= 255


container[25].bin= 66
container[25].i= 235
container[25].j= 370
container[25].angle= 333
container[25].value= 255


container[26].bin= 0
container[26].i= 236
container[26].j= 370
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 237
container[27].j= 370
container[27].angle= 0
container[27].value= 255


container[28].bin= 0
container[28].i= 238
container[28].j= 370
container[28].angle= 0
container[28].value= 255


container[29].bin= 0
container[29].i= 239
container[29].j= 370
container[29].angle= 0
container[29].value= 255


container[30].bin= 63
container[30].i= 240
container[30].j= 371
container[30].angle= 315
container[30].value= 255


container[31].bin= 44
container[31].i= 240
container[31].j= 372
container[31].angle= 224
container[31].value= 255


