container[0].bin= 14
container[0].i= 804
container[0].j= 612
container[0].angle= 71
container[0].value= 255


container[1].bin= 12
container[1].i= 804
container[1].j= 613
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 804
container[2].j= 614
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 804
container[3].j= 615
container[3].angle= 135
container[3].value= 255


container[4].bin= 3
container[4].i= 805
container[4].j= 611
container[4].angle= 18
container[4].value= 255


container[5].bin= 36
container[5].i= 805
container[5].j= 615
container[5].angle= 180
container[5].value= 255


container[6].bin= 68
container[6].i= 806
container[6].j= 611
container[6].angle= 341
container[6].value= 255


container[7].bin= 57
container[7].i= 806
container[7].j= 613
container[7].angle= 288
container[7].value= 255


container[8].bin= 68
container[8].i= 807
container[8].j= 613
container[8].angle= 341
container[8].value= 255


container[9].bin= 0
container[9].i= 808
container[9].j= 613
container[9].angle= 0
container[9].value= 255


container[10].bin= 66
container[10].i= 809
container[10].j= 614
container[10].angle= 333
container[10].value= 255


container[11].bin= 66
container[11].i= 810
container[11].j= 614
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 810
container[12].j= 616
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 811
container[13].j= 614
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 811
container[14].j= 616
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 812
container[15].j= 614
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 812
container[16].j= 616
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 813
container[17].j= 614
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 813
container[18].j= 616
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 814
container[19].j= 614
container[19].angle= 0
container[19].value= 255


container[20].bin= 41
container[20].i= 814
container[20].j= 616
container[20].angle= 206
container[20].value= 255


container[21].bin= 68
container[21].i= 815
container[21].j= 614
container[21].angle= 341
container[21].value= 255


container[22].bin= 44
container[22].i= 815
container[22].j= 616
container[22].angle= 224
container[22].value= 255


