container[0].bin= 18
container[0].i= 465
container[0].j= 453
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 466
container[1].j= 452
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 466
container[2].j= 454
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 467
container[3].j= 452
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 467
container[4].j= 454
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 468
container[5].j= 446
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 468
container[6].j= 447
container[6].angle= 90
container[6].value= 255


container[7].bin= 18
container[7].i= 468
container[7].j= 448
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 468
container[8].j= 449
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 468
container[9].j= 450
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 468
container[10].j= 451
container[10].angle= 90
container[10].value= 255


container[11].bin= 8
container[11].i= 468
container[11].j= 452
container[11].angle= 44
container[11].value= 255


container[12].bin= 36
container[12].i= 468
container[12].j= 454
container[12].angle= 180
container[12].value= 255


container[13].bin= 8
container[13].i= 469
container[13].j= 445
container[13].angle= 44
container[13].value= 255


container[14].bin= 0
container[14].i= 470
container[14].j= 444
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 470
container[15].j= 453
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 471
container[16].j= 445
container[16].angle= 315
container[16].value= 255


container[17].bin= 54
container[17].i= 471
container[17].j= 446
container[17].angle= 270
container[17].value= 255


container[18].bin= 36
container[18].i= 471
container[18].j= 453
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 472
container[19].j= 447
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 472
container[20].j= 453
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 473
container[21].j= 447
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 473
container[22].j= 453
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 474
container[23].j= 448
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 474
container[24].j= 454
container[24].angle= 135
container[24].value= 255


container[25].bin= 18
container[25].i= 474
container[25].j= 455
container[25].angle= 90
container[25].value= 255


container[26].bin= 18
container[26].i= 474
container[26].j= 456
container[26].angle= 90
container[26].value= 255


container[27].bin= 18
container[27].i= 474
container[27].j= 457
container[27].angle= 90
container[27].value= 255


container[28].bin= 18
container[28].i= 474
container[28].j= 458
container[28].angle= 90
container[28].value= 255


container[29].bin= 63
container[29].i= 475
container[29].j= 449
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 475
container[30].j= 459
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 476
container[31].j= 449
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 476
container[32].j= 459
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 477
container[33].j= 450
container[33].angle= 315
container[33].value= 255


container[34].bin= 54
container[34].i= 477
container[34].j= 456
container[34].angle= 270
container[34].value= 255


container[35].bin= 54
container[35].i= 477
container[35].j= 457
container[35].angle= 270
container[35].value= 255


container[36].bin= 54
container[36].i= 477
container[36].j= 458
container[36].angle= 270
container[36].value= 255


container[37].bin= 44
container[37].i= 477
container[37].j= 459
container[37].angle= 224
container[37].value= 255


container[38].bin= 63
container[38].i= 478
container[38].j= 451
container[38].angle= 315
container[38].value= 255


container[39].bin= 44
container[39].i= 478
container[39].j= 455
container[39].angle= 224
container[39].value= 255


container[40].bin= 0
container[40].i= 479
container[40].j= 451
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 479
container[41].j= 454
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 480
container[42].j= 451
container[42].angle= 0
container[42].value= 255


container[43].bin= 41
container[43].i= 480
container[43].j= 454
container[43].angle= 206
container[43].value= 255


container[44].bin= 5
container[44].i= 481
container[44].j= 451
container[44].angle= 26
container[44].value= 255


container[45].bin= 41
container[45].i= 481
container[45].j= 454
container[45].angle= 206
container[45].value= 255


container[46].bin= 8
container[46].i= 482
container[46].j= 450
container[46].angle= 44
container[46].value= 255


container[47].bin= 36
container[47].i= 482
container[47].j= 453
container[47].angle= 180
container[47].value= 255


container[48].bin= 18
container[48].i= 483
container[48].j= 448
container[48].angle= 90
container[48].value= 255


container[49].bin= 12
container[49].i= 483
container[49].j= 449
container[49].angle= 63
container[49].value= 255


container[50].bin= 8
container[50].i= 484
container[50].j= 447
container[50].angle= 44
container[50].value= 255


container[51].bin= 27
container[51].i= 484
container[51].j= 450
container[51].angle= 135
container[51].value= 255


container[52].bin= 39
container[52].i= 484
container[52].j= 451
container[52].angle= 198
container[52].value= 255


container[53].bin= 36
container[53].i= 484
container[53].j= 454
container[53].angle= 180
container[53].value= 255


container[54].bin= 0
container[54].i= 485
container[54].j= 446
container[54].angle= 0
container[54].value= 255


container[55].bin= 41
container[55].i= 485
container[55].j= 451
container[55].angle= 206
container[55].value= 255


container[56].bin= 36
container[56].i= 485
container[56].j= 454
container[56].angle= 180
container[56].value= 255


container[57].bin= 63
container[57].i= 486
container[57].j= 447
container[57].angle= 315
container[57].value= 255


container[58].bin= 54
container[58].i= 486
container[58].j= 448
container[58].angle= 270
container[58].value= 255


container[59].bin= 36
container[59].i= 486
container[59].j= 454
container[59].angle= 180
container[59].value= 255


container[60].bin= 63
container[60].i= 487
container[60].j= 449
container[60].angle= 315
container[60].value= 255


container[61].bin= 36
container[61].i= 487
container[61].j= 451
container[61].angle= 180
container[61].value= 255


container[62].bin= 36
container[62].i= 487
container[62].j= 454
container[62].angle= 180
container[62].value= 255


container[63].bin= 0
container[63].i= 488
container[63].j= 449
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 488
container[64].j= 451
container[64].angle= 180
container[64].value= 255


container[65].bin= 36
container[65].i= 488
container[65].j= 454
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 489
container[66].j= 449
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 489
container[67].j= 451
container[67].angle= 180
container[67].value= 255


container[68].bin= 54
container[68].i= 489
container[68].j= 453
container[68].angle= 270
container[68].value= 255


container[69].bin= 39
container[69].i= 489
container[69].j= 454
container[69].angle= 198
container[69].value= 255


container[70].bin= 0
container[70].i= 490
container[70].j= 449
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 490
container[71].j= 451
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 491
container[72].j= 449
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 491
container[73].j= 451
container[73].angle= 180
container[73].value= 255


container[74].bin= 68
container[74].i= 492
container[74].j= 449
container[74].angle= 341
container[74].value= 255


container[75].bin= 54
container[75].i= 492
container[75].j= 450
container[75].angle= 270
container[75].value= 255


container[76].bin= 39
container[76].i= 492
container[76].j= 451
container[76].angle= 198
container[76].value= 255


