container[0].bin= 18
container[0].i= 537
container[0].j= 549
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 538
container[1].j= 548
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 538
container[2].j= 550
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 539
container[3].j= 548
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 539
container[4].j= 550
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 540
container[5].j= 548
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 540
container[6].j= 549
container[6].angle= 90
container[6].value= 255


container[7].bin= 27
container[7].i= 540
container[7].j= 550
container[7].angle= 135
container[7].value= 255


container[8].bin= 5
container[8].i= 541
container[8].j= 548
container[8].angle= 26
container[8].value= 255


container[9].bin= 27
container[9].i= 541
container[9].j= 551
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 542
container[10].j= 547
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 542
container[11].j= 551
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 543
container[12].j= 548
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 543
container[13].j= 549
container[13].angle= 270
container[13].value= 255


container[14].bin= 54
container[14].i= 543
container[14].j= 550
container[14].angle= 270
container[14].value= 255


container[15].bin= 44
container[15].i= 543
container[15].j= 551
container[15].angle= 224
container[15].value= 255


