container[0].bin= 8
container[0].i= 202
container[0].j= 252
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 202
container[1].j= 253
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 202
container[2].j= 254
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 203
container[3].j= 251
container[3].angle= 0
container[3].value= 255


container[4].bin= 32
container[4].i= 203
container[4].j= 254
container[4].angle= 161
container[4].value= 255


container[5].bin= 68
container[5].i= 204
container[5].j= 251
container[5].angle= 341
container[5].value= 255


container[6].bin= 57
container[6].i= 204
container[6].j= 253
container[6].angle= 288
container[6].value= 255


container[7].bin= 27
container[7].i= 204
container[7].j= 255
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 204
container[8].j= 262
container[8].angle= 90
container[8].value= 255


container[9].bin= 68
container[9].i= 205
container[9].j= 253
container[9].angle= 341
container[9].value= 255


container[10].bin= 23
container[10].i= 205
container[10].j= 256
container[10].angle= 116
container[10].value= 255


container[11].bin= 18
container[11].i= 205
container[11].j= 257
container[11].angle= 90
container[11].value= 255


container[12].bin= 21
container[12].i= 205
container[12].j= 258
container[12].angle= 108
container[12].value= 255


container[13].bin= 3
container[13].i= 205
container[13].j= 261
container[13].angle= 18
container[13].value= 255


container[14].bin= 32
container[14].i= 205
container[14].j= 263
container[14].angle= 161
container[14].value= 255


container[15].bin= 0
container[15].i= 206
container[15].j= 253
container[15].angle= 0
container[15].value= 255


container[16].bin= 32
container[16].i= 206
container[16].j= 258
container[16].angle= 161
container[16].value= 255


container[17].bin= 0
container[17].i= 206
container[17].j= 261
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 206
container[18].j= 263
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 207
container[19].j= 254
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 207
container[20].j= 259
container[20].angle= 135
container[20].value= 255


container[21].bin= 18
container[21].i= 207
container[21].j= 260
container[21].angle= 90
container[21].value= 255


container[22].bin= 8
container[22].i= 207
container[22].j= 261
container[22].angle= 44
container[22].value= 255


container[23].bin= 18
container[23].i= 207
container[23].j= 262
container[23].angle= 90
container[23].value= 255


container[24].bin= 30
container[24].i= 207
container[24].j= 263
container[24].angle= 153
container[24].value= 255


container[25].bin= 63
container[25].i= 208
container[25].j= 255
container[25].angle= 315
container[25].value= 255


container[26].bin= 30
container[26].i= 208
container[26].j= 263
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 209
container[27].j= 255
container[27].angle= 0
container[27].value= 255


container[28].bin= 41
container[28].i= 209
container[28].j= 263
container[28].angle= 206
container[28].value= 255


container[29].bin= 66
container[29].i= 210
container[29].j= 256
container[29].angle= 333
container[29].value= 255


container[30].bin= 41
container[30].i= 210
container[30].j= 263
container[30].angle= 206
container[30].value= 255


container[31].bin= 66
container[31].i= 211
container[31].j= 256
container[31].angle= 333
container[31].value= 255


container[32].bin= 36
container[32].i= 211
container[32].j= 262
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 212
container[33].j= 256
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 212
container[34].j= 262
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 213
container[35].j= 256
container[35].angle= 0
container[35].value= 255


container[36].bin= 44
container[36].i= 213
container[36].j= 262
container[36].angle= 224
container[36].value= 255


container[37].bin= 0
container[37].i= 214
container[37].j= 256
container[37].angle= 0
container[37].value= 255


container[38].bin= 44
container[38].i= 214
container[38].j= 261
container[38].angle= 224
container[38].value= 255


container[39].bin= 0
container[39].i= 215
container[39].j= 256
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 215
container[40].j= 260
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 216
container[41].j= 257
container[41].angle= 315
container[41].value= 255


container[42].bin= 54
container[42].i= 216
container[42].j= 258
container[42].angle= 270
container[42].value= 255


container[43].bin= 54
container[43].i= 216
container[43].j= 259
container[43].angle= 270
container[43].value= 255


container[44].bin= 44
container[44].i= 216
container[44].j= 260
container[44].angle= 224
container[44].value= 255


