container[0].bin= 27
container[0].i= 544
container[0].j= 133
container[0].angle= 135
container[0].value= 255


container[1].bin= 0
container[1].i= 545
container[1].j= 131
container[1].angle= 0
container[1].value= 255


container[2].bin= 68
container[2].i= 546
container[2].j= 131
container[2].angle= 341
container[2].value= 255


container[3].bin= 44
container[3].i= 546
container[3].j= 133
container[3].angle= 224
container[3].value= 255


