container[0].bin= 8
container[0].i= 136
container[0].j= 133
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 136
container[1].j= 134
container[1].angle= 116
container[1].value= 255


container[2].bin= 23
container[2].i= 136
container[2].j= 135
container[2].angle= 116
container[2].value= 255


container[3].bin= 18
container[3].i= 136
container[3].j= 136
container[3].angle= 90
container[3].value= 255


container[4].bin= 0
container[4].i= 137
container[4].j= 132
container[4].angle= 0
container[4].value= 255


container[5].bin= 23
container[5].i= 137
container[5].j= 137
container[5].angle= 116
container[5].value= 255


container[6].bin= 27
container[6].i= 137
container[6].j= 138
container[6].angle= 135
container[6].value= 255


container[7].bin= 66
container[7].i= 138
container[7].j= 133
container[7].angle= 333
container[7].value= 255


container[8].bin= 30
container[8].i= 138
container[8].j= 138
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 139
container[9].j= 133
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 139
container[10].j= 139
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 140
container[11].j= 134
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 140
container[12].j= 139
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 140
container[13].j= 140
container[13].angle= 135
container[13].value= 255


container[14].bin= 63
container[14].i= 141
container[14].j= 134
container[14].angle= 315
container[14].value= 255


container[15].bin= 63
container[15].i= 141
container[15].j= 135
container[15].angle= 315
container[15].value= 255


container[16].bin= 30
container[16].i= 141
container[16].j= 140
container[16].angle= 153
container[16].value= 255


container[17].bin= 63
container[17].i= 142
container[17].j= 135
container[17].angle= 315
container[17].value= 255


container[18].bin= 63
container[18].i= 142
container[18].j= 136
container[18].angle= 315
container[18].value= 255


container[19].bin= 30
container[19].i= 142
container[19].j= 141
container[19].angle= 153
container[19].value= 255


container[20].bin= 63
container[20].i= 143
container[20].j= 136
container[20].angle= 315
container[20].value= 255


container[21].bin= 59
container[21].i= 143
container[21].j= 137
container[21].angle= 296
container[21].value= 255


container[22].bin= 30
container[22].i= 143
container[22].j= 141
container[22].angle= 153
container[22].value= 255


container[23].bin= 59
container[23].i= 144
container[23].j= 138
container[23].angle= 296
container[23].value= 255


container[24].bin= 63
container[24].i= 144
container[24].j= 139
container[24].angle= 315
container[24].value= 255


container[25].bin= 36
container[25].i= 144
container[25].j= 141
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 145
container[26].j= 139
container[26].angle= 315
container[26].value= 255


container[27].bin= 59
container[27].i= 145
container[27].j= 140
container[27].angle= 296
container[27].value= 255


container[28].bin= 44
container[28].i= 145
container[28].j= 141
container[28].angle= 224
container[28].value= 255


