container[0].bin= 18
container[0].i= 506
container[0].j= 610
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 507
container[1].j= 609
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 507
container[2].j= 611
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 508
container[3].j= 609
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 508
container[4].j= 611
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 509
container[5].j= 609
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 509
container[6].j= 611
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 510
container[7].j= 609
container[7].angle= 44
container[7].value= 255


container[8].bin= 36
container[8].i= 510
container[8].j= 611
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 511
container[9].j= 607
container[9].angle= 44
container[9].value= 255


container[10].bin= 12
container[10].i= 511
container[10].j= 608
container[10].angle= 63
container[10].value= 255


container[11].bin= 5
container[11].i= 512
container[11].j= 607
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 512
container[12].j= 610
container[12].angle= 180
container[12].value= 255


container[13].bin= 18
container[13].i= 513
container[13].j= 604
container[13].angle= 90
container[13].value= 255


container[14].bin= 0
container[14].i= 513
container[14].j= 606
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 513
container[15].j= 611
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 513
container[16].j= 612
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 513
container[17].j= 613
container[17].angle= 90
container[17].value= 255


container[18].bin= 18
container[18].i= 513
container[18].j= 614
container[18].angle= 90
container[18].value= 255


container[19].bin= 3
container[19].i= 514
container[19].j= 603
container[19].angle= 18
container[19].value= 255


container[20].bin= 32
container[20].i= 514
container[20].j= 605
container[20].angle= 161
container[20].value= 255


container[21].bin= 27
container[21].i= 514
container[21].j= 615
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 515
container[22].j= 603
container[22].angle= 0
container[22].value= 255


container[23].bin= 5
container[23].i= 515
container[23].j= 606
container[23].angle= 26
container[23].value= 255


container[24].bin= 36
container[24].i= 515
container[24].j= 615
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 516
container[25].j= 603
container[25].angle= 0
container[25].value= 255


container[26].bin= 8
container[26].i= 516
container[26].j= 606
container[26].angle= 44
container[26].value= 255


container[27].bin= 44
container[27].i= 516
container[27].j= 615
container[27].angle= 224
container[27].value= 255


container[28].bin= 0
container[28].i= 517
container[28].j= 603
container[28].angle= 0
container[28].value= 255


container[29].bin= 44
container[29].i= 517
container[29].j= 614
container[29].angle= 224
container[29].value= 255


container[30].bin= 0
container[30].i= 518
container[30].j= 603
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 518
container[31].j= 613
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 519
container[32].j= 604
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 519
container[33].j= 605
container[33].angle= 270
container[33].value= 255


container[34].bin= 36
container[34].i= 519
container[34].j= 613
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 520
container[35].j= 606
container[35].angle= 315
container[35].value= 255


container[36].bin= 36
container[36].i= 520
container[36].j= 613
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 521
container[37].j= 606
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 521
container[38].j= 613
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 522
container[39].j= 606
container[39].angle= 0
container[39].value= 255


container[40].bin= 27
container[40].i= 522
container[40].j= 614
container[40].angle= 135
container[40].value= 255


container[41].bin= 18
container[41].i= 522
container[41].j= 615
container[41].angle= 90
container[41].value= 255


container[42].bin= 0
container[42].i= 523
container[42].j= 606
container[42].angle= 0
container[42].value= 255


container[43].bin= 27
container[43].i= 523
container[43].j= 616
container[43].angle= 135
container[43].value= 255


container[44].bin= 8
container[44].i= 523
container[44].j= 623
container[44].angle= 44
container[44].value= 255


container[45].bin= 27
container[45].i= 523
container[45].j= 624
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 524
container[46].j= 606
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 524
container[47].j= 616
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 524
container[48].j= 622
container[48].angle= 0
container[48].value= 255


container[49].bin= 0
container[49].i= 525
container[49].j= 606
container[49].angle= 0
container[49].value= 255


container[50].bin= 27
container[50].i= 525
container[50].j= 617
container[50].angle= 135
container[50].value= 255


container[51].bin= 18
container[51].i= 525
container[51].j= 618
container[51].angle= 90
container[51].value= 255


container[52].bin= 18
container[52].i= 525
container[52].j= 619
container[52].angle= 90
container[52].value= 255


container[53].bin= 18
container[53].i= 525
container[53].j= 620
container[53].angle= 90
container[53].value= 255


container[54].bin= 18
container[54].i= 525
container[54].j= 621
container[54].angle= 90
container[54].value= 255


container[55].bin= 8
container[55].i= 525
container[55].j= 622
container[55].angle= 44
container[55].value= 255


container[56].bin= 0
container[56].i= 526
container[56].j= 606
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 526
container[57].j= 624
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 527
container[58].j= 606
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 527
container[59].j= 624
container[59].angle= 180
container[59].value= 255


container[60].bin= 5
container[60].i= 528
container[60].j= 606
container[60].angle= 26
container[60].value= 255


container[61].bin= 54
container[61].i= 528
container[61].j= 609
container[61].angle= 270
container[61].value= 255


container[62].bin= 54
container[62].i= 528
container[62].j= 610
container[62].angle= 270
container[62].value= 255


container[63].bin= 54
container[63].i= 528
container[63].j= 611
container[63].angle= 270
container[63].value= 255


container[64].bin= 54
container[64].i= 528
container[64].j= 612
container[64].angle= 270
container[64].value= 255


container[65].bin= 36
container[65].i= 528
container[65].j= 624
container[65].angle= 180
container[65].value= 255


container[66].bin= 5
container[66].i= 529
container[66].j= 606
container[66].angle= 26
container[66].value= 255


container[67].bin= 44
container[67].i= 529
container[67].j= 608
container[67].angle= 224
container[67].value= 255


container[68].bin= 63
container[68].i= 529
container[68].j= 613
container[68].angle= 315
container[68].value= 255


container[69].bin= 36
container[69].i= 529
container[69].j= 624
container[69].angle= 180
container[69].value= 255


container[70].bin= 0
container[70].i= 530
container[70].j= 605
container[70].angle= 0
container[70].value= 255


container[71].bin= 0
container[71].i= 530
container[71].j= 613
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 530
container[72].j= 624
container[72].angle= 180
container[72].value= 255


container[73].bin= 66
container[73].i= 531
container[73].j= 606
container[73].angle= 333
container[73].value= 255


container[74].bin= 0
container[74].i= 531
container[74].j= 613
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 531
container[75].j= 624
container[75].angle= 180
container[75].value= 255


container[76].bin= 66
container[76].i= 532
container[76].j= 606
container[76].angle= 333
container[76].value= 255


container[77].bin= 36
container[77].i= 532
container[77].j= 608
container[77].angle= 180
container[77].value= 255


container[78].bin= 0
container[78].i= 532
container[78].j= 613
container[78].angle= 0
container[78].value= 255


container[79].bin= 36
container[79].i= 532
container[79].j= 624
container[79].angle= 180
container[79].value= 255


container[80].bin= 0
container[80].i= 533
container[80].j= 606
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 533
container[81].j= 608
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 533
container[82].j= 613
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 533
container[83].j= 624
container[83].angle= 180
container[83].value= 255


container[84].bin= 5
container[84].i= 534
container[84].j= 606
container[84].angle= 26
container[84].value= 255


container[85].bin= 36
container[85].i= 534
container[85].j= 608
container[85].angle= 180
container[85].value= 255


container[86].bin= 14
container[86].i= 534
container[86].j= 612
container[86].angle= 71
container[86].value= 255


container[87].bin= 8
container[87].i= 534
container[87].j= 613
container[87].angle= 44
container[87].value= 255


container[88].bin= 36
container[88].i= 534
container[88].j= 624
container[88].angle= 180
container[88].value= 255


container[89].bin= 5
container[89].i= 535
container[89].j= 606
container[89].angle= 26
container[89].value= 255


container[90].bin= 3
container[90].i= 535
container[90].j= 612
container[90].angle= 18
container[90].value= 255


container[91].bin= 36
container[91].i= 535
container[91].j= 624
container[91].angle= 180
container[91].value= 255


container[92].bin= 0
container[92].i= 536
container[92].j= 605
container[92].angle= 0
container[92].value= 255


container[93].bin= 0
container[93].i= 536
container[93].j= 612
container[93].angle= 0
container[93].value= 255


container[94].bin= 36
container[94].i= 536
container[94].j= 624
container[94].angle= 180
container[94].value= 255


container[95].bin= 63
container[95].i= 537
container[95].j= 606
container[95].angle= 315
container[95].value= 255


container[96].bin= 44
container[96].i= 537
container[96].j= 607
container[96].angle= 224
container[96].value= 255


container[97].bin= 68
container[97].i= 537
container[97].j= 612
container[97].angle= 341
container[97].value= 255


container[98].bin= 41
container[98].i= 537
container[98].j= 624
container[98].angle= 206
container[98].value= 255


container[99].bin= 63
container[99].i= 538
container[99].j= 613
container[99].angle= 315
container[99].value= 255


container[100].bin= 41
container[100].i= 538
container[100].j= 624
container[100].angle= 206
container[100].value= 255


container[101].bin= 0
container[101].i= 539
container[101].j= 613
container[101].angle= 0
container[101].value= 255


container[102].bin= 36
container[102].i= 539
container[102].j= 623
container[102].angle= 180
container[102].value= 255


container[103].bin= 63
container[103].i= 540
container[103].j= 614
container[103].angle= 315
container[103].value= 255


container[104].bin= 54
container[104].i= 540
container[104].j= 615
container[104].angle= 270
container[104].value= 255


container[105].bin= 36
container[105].i= 540
container[105].j= 623
container[105].angle= 180
container[105].value= 255


container[106].bin= 63
container[106].i= 541
container[106].j= 616
container[106].angle= 315
container[106].value= 255


container[107].bin= 36
container[107].i= 541
container[107].j= 623
container[107].angle= 180
container[107].value= 255


container[108].bin= 0
container[108].i= 542
container[108].j= 616
container[108].angle= 0
container[108].value= 255


container[109].bin= 36
container[109].i= 542
container[109].j= 623
container[109].angle= 180
container[109].value= 255


container[110].bin= 66
container[110].i= 543
container[110].j= 617
container[110].angle= 333
container[110].value= 255


container[111].bin= 44
container[111].i= 543
container[111].j= 623
container[111].angle= 224
container[111].value= 255


container[112].bin= 66
container[112].i= 544
container[112].j= 617
container[112].angle= 333
container[112].value= 255


container[113].bin= 44
container[113].i= 544
container[113].j= 622
container[113].angle= 224
container[113].value= 255


container[114].bin= 0
container[114].i= 545
container[114].j= 617
container[114].angle= 0
container[114].value= 255


container[115].bin= 36
container[115].i= 545
container[115].j= 621
container[115].angle= 180
container[115].value= 255


container[116].bin= 18
container[116].i= 546
container[116].j= 615
container[116].angle= 90
container[116].value= 255


container[117].bin= 18
container[117].i= 546
container[117].j= 616
container[117].angle= 90
container[117].value= 255


container[118].bin= 8
container[118].i= 546
container[118].j= 617
container[118].angle= 44
container[118].value= 255


container[119].bin= 36
container[119].i= 546
container[119].j= 621
container[119].angle= 180
container[119].value= 255


container[120].bin= 8
container[120].i= 547
container[120].j= 614
container[120].angle= 44
container[120].value= 255


container[121].bin= 36
container[121].i= 547
container[121].j= 621
container[121].angle= 180
container[121].value= 255


container[122].bin= 0
container[122].i= 548
container[122].j= 613
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 548
container[123].j= 621
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 549
container[124].j= 613
container[124].angle= 0
container[124].value= 255


container[125].bin= 27
container[125].i= 549
container[125].j= 622
container[125].angle= 135
container[125].value= 255


container[126].bin= 0
container[126].i= 550
container[126].j= 613
container[126].angle= 0
container[126].value= 255


container[127].bin= 27
container[127].i= 550
container[127].j= 623
container[127].angle= 135
container[127].value= 255


container[128].bin= 0
container[128].i= 551
container[128].j= 613
container[128].angle= 0
container[128].value= 255


container[129].bin= 36
container[129].i= 551
container[129].j= 623
container[129].angle= 180
container[129].value= 255


container[130].bin= 66
container[130].i= 552
container[130].j= 614
container[130].angle= 333
container[130].value= 255


container[131].bin= 54
container[131].i= 552
container[131].j= 620
container[131].angle= 270
container[131].value= 255


container[132].bin= 54
container[132].i= 552
container[132].j= 621
container[132].angle= 270
container[132].value= 255


container[133].bin= 54
container[133].i= 552
container[133].j= 622
container[133].angle= 270
container[133].value= 255


container[134].bin= 44
container[134].i= 552
container[134].j= 623
container[134].angle= 224
container[134].value= 255


container[135].bin= 66
container[135].i= 553
container[135].j= 614
container[135].angle= 333
container[135].value= 255


container[136].bin= 44
container[136].i= 553
container[136].j= 619
container[136].angle= 224
container[136].value= 255


container[137].bin= 0
container[137].i= 554
container[137].j= 614
container[137].angle= 0
container[137].value= 255


container[138].bin= 36
container[138].i= 554
container[138].j= 618
container[138].angle= 180
container[138].value= 255


container[139].bin= 63
container[139].i= 555
container[139].j= 615
container[139].angle= 315
container[139].value= 255


container[140].bin= 54
container[140].i= 555
container[140].j= 616
container[140].angle= 270
container[140].value= 255


container[141].bin= 54
container[141].i= 555
container[141].j= 617
container[141].angle= 270
container[141].value= 255


container[142].bin= 44
container[142].i= 555
container[142].j= 618
container[142].angle= 224
container[142].value= 255


