container[0].bin= 18
container[0].i= 33
container[0].j= 305
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 33
container[1].j= 306
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 33
container[2].j= 307
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 34
container[3].j= 304
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 34
container[4].j= 308
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 35
container[5].j= 303
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 35
container[6].j= 308
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 36
container[7].j= 304
container[7].angle= 333
container[7].value= 255


container[8].bin= 54
container[8].i= 36
container[8].j= 305
container[8].angle= 270
container[8].value= 255


container[9].bin= 54
container[9].i= 36
container[9].j= 306
container[9].angle= 270
container[9].value= 255


container[10].bin= 27
container[10].i= 36
container[10].j= 309
container[10].angle= 135
container[10].value= 255


container[11].bin= 18
container[11].i= 36
container[11].j= 310
container[11].angle= 90
container[11].value= 255


container[12].bin= 66
container[12].i= 37
container[12].j= 304
container[12].angle= 333
container[12].value= 255


container[13].bin= 68
container[13].i= 37
container[13].j= 307
container[13].angle= 341
container[13].value= 255


container[14].bin= 27
container[14].i= 37
container[14].j= 311
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 38
container[15].j= 304
container[15].angle= 0
container[15].value= 255


container[16].bin= 3
container[16].i= 38
container[16].j= 307
container[16].angle= 18
container[16].value= 255


container[17].bin= 36
container[17].i= 38
container[17].j= 311
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 39
container[18].j= 304
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 39
container[19].j= 312
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 40
container[20].j= 304
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 40
container[21].j= 313
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 41
container[22].j= 304
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 41
container[23].j= 313
container[23].angle= 180
container[23].value= 255


container[24].bin= 5
container[24].i= 42
container[24].j= 304
container[24].angle= 26
container[24].value= 255


container[25].bin= 27
container[25].i= 42
container[25].j= 314
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 43
container[26].j= 304
container[26].angle= 0
container[26].value= 255


container[27].bin= 27
container[27].i= 43
container[27].j= 315
container[27].angle= 135
container[27].value= 255


container[28].bin= 66
container[28].i= 44
container[28].j= 304
container[28].angle= 333
container[28].value= 255


container[29].bin= 36
container[29].i= 44
container[29].j= 315
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 45
container[30].j= 304
container[30].angle= 0
container[30].value= 255


container[31].bin= 30
container[31].i= 45
container[31].j= 316
container[31].angle= 153
container[31].value= 255


container[32].bin= 0
container[32].i= 46
container[32].j= 304
container[32].angle= 0
container[32].value= 255


container[33].bin= 30
container[33].i= 46
container[33].j= 316
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 47
container[34].j= 304
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 47
container[35].j= 316
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 48
container[36].j= 305
container[36].angle= 315
container[36].value= 255


container[37].bin= 54
container[37].i= 48
container[37].j= 306
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 48
container[38].j= 307
container[38].angle= 270
container[38].value= 255


container[39].bin= 27
container[39].i= 48
container[39].j= 317
container[39].angle= 135
container[39].value= 255


container[40].bin= 63
container[40].i= 49
container[40].j= 308
container[40].angle= 315
container[40].value= 255


container[41].bin= 23
container[41].i= 49
container[41].j= 318
container[41].angle= 116
container[41].value= 255


container[42].bin= 27
container[42].i= 49
container[42].j= 319
container[42].angle= 135
container[42].value= 255


container[43].bin= 0
container[43].i= 50
container[43].j= 308
container[43].angle= 0
container[43].value= 255


container[44].bin= 30
container[44].i= 50
container[44].j= 319
container[44].angle= 153
container[44].value= 255


container[45].bin= 0
container[45].i= 51
container[45].j= 308
container[45].angle= 0
container[45].value= 255


container[46].bin= 27
container[46].i= 51
container[46].j= 320
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 52
container[47].j= 308
container[47].angle= 0
container[47].value= 255


container[48].bin= 27
container[48].i= 52
container[48].j= 321
container[48].angle= 135
container[48].value= 255


container[49].bin= 0
container[49].i= 53
container[49].j= 308
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 53
container[50].j= 321
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 54
container[51].j= 308
container[51].angle= 0
container[51].value= 255


container[52].bin= 27
container[52].i= 54
container[52].j= 322
container[52].angle= 135
container[52].value= 255


container[53].bin= 0
container[53].i= 55
container[53].j= 308
container[53].angle= 0
container[53].value= 255


container[54].bin= 27
container[54].i= 55
container[54].j= 323
container[54].angle= 135
container[54].value= 255


container[55].bin= 0
container[55].i= 56
container[55].j= 308
container[55].angle= 0
container[55].value= 255


container[56].bin= 36
container[56].i= 56
container[56].j= 323
container[56].angle= 180
container[56].value= 255


container[57].bin= 66
container[57].i= 57
container[57].j= 309
container[57].angle= 333
container[57].value= 255


container[58].bin= 30
container[58].i= 57
container[58].j= 324
container[58].angle= 153
container[58].value= 255


container[59].bin= 66
container[59].i= 58
container[59].j= 309
container[59].angle= 333
container[59].value= 255


container[60].bin= 30
container[60].i= 58
container[60].j= 324
container[60].angle= 153
container[60].value= 255


container[61].bin= 0
container[61].i= 59
container[61].j= 309
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 59
container[62].j= 324
container[62].angle= 180
container[62].value= 255


container[63].bin= 63
container[63].i= 60
container[63].j= 310
container[63].angle= 315
container[63].value= 255


container[64].bin= 48
container[64].i= 60
container[64].j= 315
container[64].angle= 243
container[64].value= 255


container[65].bin= 48
container[65].i= 60
container[65].j= 316
container[65].angle= 243
container[65].value= 255


container[66].bin= 59
container[66].i= 60
container[66].j= 317
container[66].angle= 296
container[66].value= 255


container[67].bin= 59
container[67].i= 60
container[67].j= 318
container[67].angle= 296
container[67].value= 255


container[68].bin= 54
container[68].i= 60
container[68].j= 322
container[68].angle= 270
container[68].value= 255


container[69].bin= 54
container[69].i= 60
container[69].j= 323
container[69].angle= 270
container[69].value= 255


container[70].bin= 41
container[70].i= 60
container[70].j= 324
container[70].angle= 206
container[70].value= 255


container[71].bin= 63
container[71].i= 61
container[71].j= 311
container[71].angle= 315
container[71].value= 255


container[72].bin= 44
container[72].i= 61
container[72].j= 314
container[72].angle= 224
container[72].value= 255


container[73].bin= 63
container[73].i= 61
container[73].j= 319
container[73].angle= 315
container[73].value= 255


container[74].bin= 41
container[74].i= 61
container[74].j= 324
container[74].angle= 206
container[74].value= 255


container[75].bin= 0
container[75].i= 62
container[75].j= 311
container[75].angle= 0
container[75].value= 255


container[76].bin= 0
container[76].i= 62
container[76].j= 319
container[76].angle= 0
container[76].value= 255


container[77].bin= 39
container[77].i= 62
container[77].j= 324
container[77].angle= 198
container[77].value= 255


container[78].bin= 66
container[78].i= 63
container[78].j= 312
container[78].angle= 333
container[78].value= 255


container[79].bin= 63
container[79].i= 63
container[79].j= 320
container[79].angle= 315
container[79].value= 255


container[80].bin= 44
container[80].i= 63
container[80].j= 323
container[80].angle= 224
container[80].value= 255


container[81].bin= 66
container[81].i= 64
container[81].j= 312
container[81].angle= 333
container[81].value= 255


container[82].bin= 36
container[82].i= 64
container[82].j= 314
container[82].angle= 180
container[82].value= 255


container[83].bin= 0
container[83].i= 65
container[83].j= 312
container[83].angle= 0
container[83].value= 255


container[84].bin= 36
container[84].i= 65
container[84].j= 314
container[84].angle= 180
container[84].value= 255


container[85].bin= 68
container[85].i= 66
container[85].j= 312
container[85].angle= 341
container[85].value= 255


container[86].bin= 54
container[86].i= 66
container[86].j= 313
container[86].angle= 270
container[86].value= 255


container[87].bin= 39
container[87].i= 66
container[87].j= 314
container[87].angle= 198
container[87].value= 255


