container[0].bin= 8
container[0].i= 157
container[0].j= 293
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 157
container[1].j= 294
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 158
container[2].j= 292
container[2].angle= 0
container[2].value= 255


container[3].bin= 30
container[3].i= 158
container[3].j= 295
container[3].angle= 153
container[3].value= 255


container[4].bin= 0
container[4].i= 159
container[4].j= 292
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 159
container[5].j= 295
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 160
container[6].j= 292
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 160
container[7].j= 296
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 161
container[8].j= 292
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 161
container[9].j= 296
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 162
container[10].j= 292
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 162
container[11].j= 297
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 163
container[12].j= 292
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 163
container[13].j= 297
container[13].angle= 135
container[13].value= 255


container[14].bin= 27
container[14].i= 163
container[14].j= 298
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 164
container[15].j= 292
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 164
container[16].j= 298
container[16].angle= 135
container[16].value= 255


container[17].bin= 27
container[17].i= 164
container[17].j= 299
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 165
container[18].j= 292
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 165
container[19].j= 299
container[19].angle= 135
container[19].value= 255


container[20].bin= 27
container[20].i= 165
container[20].j= 300
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 166
container[21].j= 292
container[21].angle= 0
container[21].value= 255


container[22].bin= 27
container[22].i= 166
container[22].j= 300
container[22].angle= 135
container[22].value= 255


container[23].bin= 27
container[23].i= 166
container[23].j= 301
container[23].angle= 135
container[23].value= 255


container[24].bin= 5
container[24].i= 167
container[24].j= 292
container[24].angle= 26
container[24].value= 255


container[25].bin= 27
container[25].i= 167
container[25].j= 301
container[25].angle= 135
container[25].value= 255


container[26].bin= 27
container[26].i= 167
container[26].j= 302
container[26].angle= 135
container[26].value= 255


container[27].bin= 5
container[27].i= 168
container[27].j= 292
container[27].angle= 26
container[27].value= 255


container[28].bin= 27
container[28].i= 168
container[28].j= 302
container[28].angle= 135
container[28].value= 255


container[29].bin= 27
container[29].i= 168
container[29].j= 303
container[29].angle= 135
container[29].value= 255


container[30].bin= 5
container[30].i= 169
container[30].j= 291
container[30].angle= 26
container[30].value= 255


container[31].bin= 30
container[31].i= 169
container[31].j= 303
container[31].angle= 153
container[31].value= 255


container[32].bin= 5
container[32].i= 170
container[32].j= 291
container[32].angle= 26
container[32].value= 255


container[33].bin= 30
container[33].i= 170
container[33].j= 304
container[33].angle= 153
container[33].value= 255


container[34].bin= 0
container[34].i= 171
container[34].j= 290
container[34].angle= 0
container[34].value= 255


container[35].bin= 30
container[35].i= 171
container[35].j= 304
container[35].angle= 153
container[35].value= 255


container[36].bin= 0
container[36].i= 172
container[36].j= 290
container[36].angle= 0
container[36].value= 255


container[37].bin= 30
container[37].i= 172
container[37].j= 305
container[37].angle= 153
container[37].value= 255


container[38].bin= 0
container[38].i= 173
container[38].j= 290
container[38].angle= 0
container[38].value= 255


container[39].bin= 27
container[39].i= 173
container[39].j= 305
container[39].angle= 135
container[39].value= 255


container[40].bin= 27
container[40].i= 173
container[40].j= 306
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 174
container[41].j= 290
container[41].angle= 0
container[41].value= 255


container[42].bin= 30
container[42].i= 174
container[42].j= 306
container[42].angle= 153
container[42].value= 255


container[43].bin= 0
container[43].i= 175
container[43].j= 290
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 175
container[44].j= 306
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 176
container[45].j= 290
container[45].angle= 0
container[45].value= 255


container[46].bin= 30
container[46].i= 176
container[46].j= 307
container[46].angle= 153
container[46].value= 255


container[47].bin= 0
container[47].i= 177
container[47].j= 290
container[47].angle= 0
container[47].value= 255


container[48].bin= 30
container[48].i= 177
container[48].j= 307
container[48].angle= 153
container[48].value= 255


container[49].bin= 0
container[49].i= 178
container[49].j= 290
container[49].angle= 0
container[49].value= 255


container[50].bin= 30
container[50].i= 178
container[50].j= 308
container[50].angle= 153
container[50].value= 255


container[51].bin= 0
container[51].i= 179
container[51].j= 290
container[51].angle= 0
container[51].value= 255


container[52].bin= 30
container[52].i= 179
container[52].j= 308
container[52].angle= 153
container[52].value= 255


container[53].bin= 0
container[53].i= 180
container[53].j= 290
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 180
container[54].j= 308
container[54].angle= 180
container[54].value= 255


container[55].bin= 5
container[55].i= 181
container[55].j= 290
container[55].angle= 26
container[55].value= 255


container[56].bin= 30
container[56].i= 181
container[56].j= 309
container[56].angle= 153
container[56].value= 255


container[57].bin= 5
container[57].i= 182
container[57].j= 290
container[57].angle= 26
container[57].value= 255


container[58].bin= 27
container[58].i= 182
container[58].j= 309
container[58].angle= 135
container[58].value= 255


container[59].bin= 23
container[59].i= 182
container[59].j= 310
container[59].angle= 116
container[59].value= 255


container[60].bin= 0
container[60].i= 183
container[60].j= 289
container[60].angle= 0
container[60].value= 255


container[61].bin= 23
container[61].i= 183
container[61].j= 311
container[61].angle= 116
container[61].value= 255


container[62].bin= 27
container[62].i= 183
container[62].j= 312
container[62].angle= 135
container[62].value= 255


container[63].bin= 0
container[63].i= 184
container[63].j= 289
container[63].angle= 0
container[63].value= 255


container[64].bin= 30
container[64].i= 184
container[64].j= 312
container[64].angle= 153
container[64].value= 255


container[65].bin= 0
container[65].i= 185
container[65].j= 289
container[65].angle= 0
container[65].value= 255


container[66].bin= 30
container[66].i= 185
container[66].j= 313
container[66].angle= 153
container[66].value= 255


container[67].bin= 0
container[67].i= 186
container[67].j= 289
container[67].angle= 0
container[67].value= 255


container[68].bin= 30
container[68].i= 186
container[68].j= 313
container[68].angle= 153
container[68].value= 255


container[69].bin= 0
container[69].i= 187
container[69].j= 289
container[69].angle= 0
container[69].value= 255


container[70].bin= 41
container[70].i= 187
container[70].j= 313
container[70].angle= 206
container[70].value= 255


container[71].bin= 0
container[71].i= 188
container[71].j= 289
container[71].angle= 0
container[71].value= 255


container[72].bin= 44
container[72].i= 188
container[72].j= 312
container[72].angle= 224
container[72].value= 255


container[73].bin= 44
container[73].i= 188
container[73].j= 313
container[73].angle= 224
container[73].value= 255


container[74].bin= 0
container[74].i= 189
container[74].j= 289
container[74].angle= 0
container[74].value= 255


container[75].bin= 41
container[75].i= 189
container[75].j= 312
container[75].angle= 206
container[75].value= 255


container[76].bin= 0
container[76].i= 190
container[76].j= 289
container[76].angle= 0
container[76].value= 255


container[77].bin= 41
container[77].i= 190
container[77].j= 311
container[77].angle= 206
container[77].value= 255


container[78].bin= 66
container[78].i= 191
container[78].j= 290
container[78].angle= 333
container[78].value= 255


container[79].bin= 41
container[79].i= 191
container[79].j= 311
container[79].angle= 206
container[79].value= 255


container[80].bin= 63
container[80].i= 192
container[80].j= 290
container[80].angle= 315
container[80].value= 255


container[81].bin= 63
container[81].i= 192
container[81].j= 291
container[81].angle= 315
container[81].value= 255


container[82].bin= 36
container[82].i= 192
container[82].j= 310
container[82].angle= 180
container[82].value= 255


container[83].bin= 63
container[83].i= 193
container[83].j= 291
container[83].angle= 315
container[83].value= 255


container[84].bin= 59
container[84].i= 193
container[84].j= 292
container[84].angle= 296
container[84].value= 255


container[85].bin= 54
container[85].i= 193
container[85].j= 293
container[85].angle= 270
container[85].value= 255


container[86].bin= 54
container[86].i= 193
container[86].j= 294
container[86].angle= 270
container[86].value= 255


container[87].bin= 54
container[87].i= 193
container[87].j= 295
container[87].angle= 270
container[87].value= 255


container[88].bin= 54
container[88].i= 193
container[88].j= 296
container[88].angle= 270
container[88].value= 255


container[89].bin= 54
container[89].i= 193
container[89].j= 297
container[89].angle= 270
container[89].value= 255


container[90].bin= 54
container[90].i= 193
container[90].j= 298
container[90].angle= 270
container[90].value= 255


container[91].bin= 48
container[91].i= 193
container[91].j= 299
container[91].angle= 243
container[91].value= 255


container[92].bin= 54
container[92].i= 193
container[92].j= 300
container[92].angle= 270
container[92].value= 255


container[93].bin= 59
container[93].i= 193
container[93].j= 301
container[93].angle= 296
container[93].value= 255


container[94].bin= 54
container[94].i= 193
container[94].j= 302
container[94].angle= 270
container[94].value= 255


container[95].bin= 54
container[95].i= 193
container[95].j= 303
container[95].angle= 270
container[95].value= 255


container[96].bin= 41
container[96].i= 193
container[96].j= 310
container[96].angle= 206
container[96].value= 255


container[97].bin= 59
container[97].i= 194
container[97].j= 304
container[97].angle= 296
container[97].value= 255


container[98].bin= 59
container[98].i= 194
container[98].j= 305
container[98].angle= 296
container[98].value= 255


container[99].bin= 54
container[99].i= 194
container[99].j= 306
container[99].angle= 270
container[99].value= 255


container[100].bin= 54
container[100].i= 194
container[100].j= 307
container[100].angle= 270
container[100].value= 255


container[101].bin= 54
container[101].i= 194
container[101].j= 308
container[101].angle= 270
container[101].value= 255


container[102].bin= 48
container[102].i= 194
container[102].j= 309
container[102].angle= 243
container[102].value= 255


container[103].bin= 44
container[103].i= 194
container[103].j= 310
container[103].angle= 224
container[103].value= 255


