container[0].bin= 18
container[0].i= 664
container[0].j= 225
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 665
container[1].j= 224
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 665
container[2].j= 226
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 666
container[3].j= 224
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 666
container[4].j= 226
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 667
container[5].j= 224
container[5].angle= 341
container[5].value= 255


container[6].bin= 32
container[6].i= 667
container[6].j= 226
container[6].angle= 161
container[6].value= 255


container[7].bin= 0
container[7].i= 668
container[7].j= 224
container[7].angle= 0
container[7].value= 255


container[8].bin= 3
container[8].i= 669
container[8].j= 224
container[8].angle= 18
container[8].value= 255


container[9].bin= 68
container[9].i= 670
container[9].j= 224
container[9].angle= 341
container[9].value= 255


