container[0].bin= 18
container[0].i= 135
container[0].j= 0
container[0].angle= 90
container[0].value= 255


container[1].bin= 54
container[1].i= 136
container[1].j= 0
container[1].angle= 270
container[1].value= 255


