container[0].bin= 8
container[0].i= 397
container[0].j= 280
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 397
container[1].j= 281
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 398
container[2].j= 279
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 399
container[3].j= 279
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 400
container[4].j= 279
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 401
container[5].j= 279
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 402
container[6].j= 280
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 402
container[7].j= 281
container[7].angle= 224
container[7].value= 255


