container[0].bin= 18
container[0].i= 285
container[0].j= 321
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 285
container[1].j= 326
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 286
container[2].j= 320
container[2].angle= 18
container[2].value= 255


container[3].bin= 32
container[3].i= 286
container[3].j= 322
container[3].angle= 161
container[3].value= 255


container[4].bin= 3
container[4].i= 286
container[4].j= 325
container[4].angle= 18
container[4].value= 255


container[5].bin= 32
container[5].i= 286
container[5].j= 327
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 287
container[6].j= 320
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 287
container[7].j= 322
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 287
container[8].j= 325
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 287
container[9].j= 327
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 288
container[10].j= 320
container[10].angle= 26
container[10].value= 255


container[11].bin= 18
container[11].i= 288
container[11].j= 321
container[11].angle= 90
container[11].value= 255


container[12].bin= 27
container[12].i= 288
container[12].j= 322
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 288
container[13].j= 323
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 288
container[14].j= 324
container[14].angle= 90
container[14].value= 255


container[15].bin= 8
container[15].i= 288
container[15].j= 325
container[15].angle= 44
container[15].value= 255


container[16].bin= 18
container[16].i= 288
container[16].j= 326
container[16].angle= 90
container[16].value= 255


container[17].bin= 30
container[17].i= 288
container[17].j= 327
container[17].angle= 153
container[17].value= 255


container[18].bin= 5
container[18].i= 289
container[18].j= 320
container[18].angle= 26
container[18].value= 255


container[19].bin= 36
container[19].i= 289
container[19].j= 327
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 290
container[20].j= 319
container[20].angle= 0
container[20].value= 255


container[21].bin= 41
container[21].i= 290
container[21].j= 327
container[21].angle= 206
container[21].value= 255


container[22].bin= 66
container[22].i= 291
container[22].j= 320
container[22].angle= 333
container[22].value= 255


container[23].bin= 36
container[23].i= 291
container[23].j= 326
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 292
container[24].j= 320
container[24].angle= 0
container[24].value= 255


container[25].bin= 41
container[25].i= 292
container[25].j= 326
container[25].angle= 206
container[25].value= 255


container[26].bin= 0
container[26].i= 293
container[26].j= 320
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 294
container[27].j= 320
container[27].angle= 0
container[27].value= 255


container[28].bin= 54
container[28].i= 294
container[28].j= 322
container[28].angle= 270
container[28].value= 255


container[29].bin= 27
container[29].i= 294
container[29].j= 326
container[29].angle= 135
container[29].value= 255


container[30].bin= 5
container[30].i= 295
container[30].j= 320
container[30].angle= 26
container[30].value= 255


container[31].bin= 32
container[31].i= 295
container[31].j= 326
container[31].angle= 161
container[31].value= 255


container[32].bin= 0
container[32].i= 296
container[32].j= 319
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 296
container[33].j= 326
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 297
container[34].j= 320
container[34].angle= 333
container[34].value= 255


container[35].bin= 32
container[35].i= 297
container[35].j= 323
container[35].angle= 161
container[35].value= 255


container[36].bin= 59
container[36].i= 297
container[36].j= 325
container[36].angle= 296
container[36].value= 255


container[37].bin= 44
container[37].i= 297
container[37].j= 326
container[37].angle= 224
container[37].value= 255


container[38].bin= 66
container[38].i= 298
container[38].j= 320
container[38].angle= 333
container[38].value= 255


container[39].bin= 36
container[39].i= 298
container[39].j= 323
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 299
container[40].j= 320
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 299
container[41].j= 323
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 300
container[42].j= 320
container[42].angle= 0
container[42].value= 255


container[43].bin= 44
container[43].i= 300
container[43].j= 323
container[43].angle= 224
container[43].value= 255


container[44].bin= 0
container[44].i= 301
container[44].j= 320
container[44].angle= 0
container[44].value= 255


container[45].bin= 44
container[45].i= 301
container[45].j= 322
container[45].angle= 224
container[45].value= 255


container[46].bin= 0
container[46].i= 302
container[46].j= 320
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 302
container[47].j= 322
container[47].angle= 180
container[47].value= 255


container[48].bin= 3
container[48].i= 303
container[48].j= 317
container[48].angle= 18
container[48].value= 255


container[49].bin= 14
container[49].i= 303
container[49].j= 318
container[49].angle= 71
container[49].value= 255


container[50].bin= 23
container[50].i= 303
container[50].j= 319
container[50].angle= 116
container[50].value= 255


container[51].bin= 8
container[51].i= 303
container[51].j= 320
container[51].angle= 44
container[51].value= 255


container[52].bin= 18
container[52].i= 303
container[52].j= 321
container[52].angle= 90
container[52].value= 255


container[53].bin= 27
container[53].i= 303
container[53].j= 322
container[53].angle= 135
container[53].value= 255


container[54].bin= 0
container[54].i= 304
container[54].j= 317
container[54].angle= 0
container[54].value= 255


container[55].bin= 27
container[55].i= 304
container[55].j= 323
container[55].angle= 135
container[55].value= 255


container[56].bin= 66
container[56].i= 305
container[56].j= 318
container[56].angle= 333
container[56].value= 255


container[57].bin= 30
container[57].i= 305
container[57].j= 324
container[57].angle= 153
container[57].value= 255


container[58].bin= 63
container[58].i= 306
container[58].j= 318
container[58].angle= 315
container[58].value= 255


container[59].bin= 59
container[59].i= 306
container[59].j= 319
container[59].angle= 296
container[59].value= 255


container[60].bin= 27
container[60].i= 306
container[60].j= 324
container[60].angle= 135
container[60].value= 255


container[61].bin= 23
container[61].i= 306
container[61].j= 325
container[61].angle= 116
container[61].value= 255


container[62].bin= 63
container[62].i= 307
container[62].j= 320
container[62].angle= 315
container[62].value= 255


container[63].bin= 27
container[63].i= 307
container[63].j= 326
container[63].angle= 135
container[63].value= 255


container[64].bin= 0
container[64].i= 308
container[64].j= 320
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 308
container[65].j= 326
container[65].angle= 180
container[65].value= 255


container[66].bin= 63
container[66].i= 309
container[66].j= 321
container[66].angle= 315
container[66].value= 255


container[67].bin= 54
container[67].i= 309
container[67].j= 323
container[67].angle= 270
container[67].value= 255


container[68].bin= 50
container[68].i= 309
container[68].j= 324
container[68].angle= 251
container[68].value= 255


container[69].bin= 54
container[69].i= 309
container[69].j= 325
container[69].angle= 270
container[69].value= 255


container[70].bin= 44
container[70].i= 309
container[70].j= 326
container[70].angle= 224
container[70].value= 255


container[71].bin= 63
container[71].i= 310
container[71].j= 322
container[71].angle= 315
container[71].value= 255


container[72].bin= 39
container[72].i= 310
container[72].j= 324
container[72].angle= 198
container[72].value= 255


container[73].bin= 0
container[73].i= 311
container[73].j= 322
container[73].angle= 0
container[73].value= 255


container[74].bin= 36
container[74].i= 311
container[74].j= 324
container[74].angle= 180
container[74].value= 255


container[75].bin= 68
container[75].i= 312
container[75].j= 322
container[75].angle= 341
container[75].value= 255


container[76].bin= 57
container[76].i= 312
container[76].j= 323
container[76].angle= 288
container[76].value= 255


container[77].bin= 44
container[77].i= 312
container[77].j= 324
container[77].angle= 224
container[77].value= 255


