container[0].bin= 18
container[0].i= 16
container[0].j= 213
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 17
container[1].j= 211
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 17
container[2].j= 212
container[2].angle= 63
container[2].value= 255


container[3].bin= 23
container[3].i= 17
container[3].j= 214
container[3].angle= 116
container[3].value= 255


container[4].bin= 27
container[4].i= 17
container[4].j= 215
container[4].angle= 135
container[4].value= 255


container[5].bin= 5
container[5].i= 18
container[5].j= 211
container[5].angle= 26
container[5].value= 255


container[6].bin= 27
container[6].i= 18
container[6].j= 215
container[6].angle= 135
container[6].value= 255


container[7].bin= 27
container[7].i= 18
container[7].j= 216
container[7].angle= 135
container[7].value= 255


container[8].bin= 66
container[8].i= 19
container[8].j= 211
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 19
container[9].j= 216
container[9].angle= 153
container[9].value= 255


container[10].bin= 63
container[10].i= 20
container[10].j= 211
container[10].angle= 315
container[10].value= 255


container[11].bin= 63
container[11].i= 20
container[11].j= 212
container[11].angle= 315
container[11].value= 255


container[12].bin= 36
container[12].i= 20
container[12].j= 216
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 21
container[13].j= 212
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 21
container[14].j= 213
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 21
container[15].j= 216
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 22
container[16].j= 213
container[16].angle= 315
container[16].value= 255


container[17].bin= 59
container[17].i= 22
container[17].j= 214
container[17].angle= 296
container[17].value= 255


container[18].bin= 54
container[18].i= 22
container[18].j= 215
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 22
container[19].j= 216
container[19].angle= 224
container[19].value= 255


