container[0].bin= 18
container[0].i= 676
container[0].j= 526
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 677
container[1].j= 525
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 677
container[2].j= 527
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 678
container[3].j= 524
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 678
container[4].j= 527
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 679
container[5].j= 524
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 679
container[6].j= 528
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 680
container[7].j= 524
container[7].angle= 26
container[7].value= 255


container[8].bin= 30
container[8].i= 680
container[8].j= 528
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 681
container[9].j= 523
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 681
container[10].j= 528
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 682
container[11].j= 523
container[11].angle= 0
container[11].value= 255


container[12].bin= 41
container[12].i= 682
container[12].j= 528
container[12].angle= 206
container[12].value= 255


container[13].bin= 0
container[13].i= 683
container[13].j= 523
container[13].angle= 0
container[13].value= 255


container[14].bin= 41
container[14].i= 683
container[14].j= 528
container[14].angle= 206
container[14].value= 255


container[15].bin= 0
container[15].i= 684
container[15].j= 523
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 684
container[16].j= 527
container[16].angle= 180
container[16].value= 255


container[17].bin= 14
container[17].i= 685
container[17].j= 521
container[17].angle= 71
container[17].value= 255


container[18].bin= 18
container[18].i= 685
container[18].j= 522
container[18].angle= 90
container[18].value= 255


container[19].bin= 8
container[19].i= 685
container[19].j= 523
container[19].angle= 44
container[19].value= 255


container[20].bin= 30
container[20].i= 685
container[20].j= 528
container[20].angle= 153
container[20].value= 255


container[21].bin= 3
container[21].i= 686
container[21].j= 518
container[21].angle= 18
container[21].value= 255


container[22].bin= 14
container[22].i= 686
container[22].j= 519
container[22].angle= 71
container[22].value= 255


container[23].bin= 21
container[23].i= 686
container[23].j= 520
container[23].angle= 108
container[23].value= 255


container[24].bin= 8
container[24].i= 686
container[24].j= 521
container[24].angle= 44
container[24].value= 255


container[25].bin= 30
container[25].i= 686
container[25].j= 528
container[25].angle= 153
container[25].value= 255


container[26].bin= 0
container[26].i= 687
container[26].j= 518
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 687
container[27].j= 528
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 688
container[28].j= 518
container[28].angle= 0
container[28].value= 255


container[29].bin= 57
container[29].i= 688
container[29].j= 522
container[29].angle= 288
container[29].value= 255


container[30].bin= 27
container[30].i= 688
container[30].j= 529
container[30].angle= 135
container[30].value= 255


container[31].bin= 18
container[31].i= 688
container[31].j= 530
container[31].angle= 90
container[31].value= 255


container[32].bin= 0
container[32].i= 689
container[32].j= 518
container[32].angle= 0
container[32].value= 255


container[33].bin= 39
container[33].i= 689
container[33].j= 520
container[33].angle= 198
container[33].value= 255


container[34].bin= 63
container[34].i= 689
container[34].j= 523
container[34].angle= 315
container[34].value= 255


container[35].bin= 27
container[35].i= 689
container[35].j= 531
container[35].angle= 135
container[35].value= 255


container[36].bin= 0
container[36].i= 690
container[36].j= 518
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 690
container[37].j= 520
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 690
container[38].j= 523
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 690
container[39].j= 531
container[39].angle= 180
container[39].value= 255


container[40].bin= 68
container[40].i= 691
container[40].j= 518
container[40].angle= 341
container[40].value= 255


container[41].bin= 54
container[41].i= 691
container[41].j= 519
container[41].angle= 270
container[41].value= 255


container[42].bin= 39
container[42].i= 691
container[42].j= 520
container[42].angle= 198
container[42].value= 255


container[43].bin= 0
container[43].i= 691
container[43].j= 523
container[43].angle= 0
container[43].value= 255


container[44].bin= 27
container[44].i= 691
container[44].j= 532
container[44].angle= 135
container[44].value= 255


container[45].bin= 0
container[45].i= 692
container[45].j= 523
container[45].angle= 0
container[45].value= 255


container[46].bin= 27
container[46].i= 692
container[46].j= 533
container[46].angle= 135
container[46].value= 255


container[47].bin= 0
container[47].i= 693
container[47].j= 523
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 693
container[48].j= 533
container[48].angle= 180
container[48].value= 255


container[49].bin= 63
container[49].i= 694
container[49].j= 524
container[49].angle= 315
container[49].value= 255


container[50].bin= 54
container[50].i= 694
container[50].j= 525
container[50].angle= 270
container[50].value= 255


container[51].bin= 54
container[51].i= 694
container[51].j= 526
container[51].angle= 270
container[51].value= 255


container[52].bin= 54
container[52].i= 694
container[52].j= 527
container[52].angle= 270
container[52].value= 255


container[53].bin= 27
container[53].i= 694
container[53].j= 534
container[53].angle= 135
container[53].value= 255


container[54].bin= 63
container[54].i= 695
container[54].j= 528
container[54].angle= 315
container[54].value= 255


container[55].bin= 27
container[55].i= 695
container[55].j= 535
container[55].angle= 135
container[55].value= 255


container[56].bin= 0
container[56].i= 696
container[56].j= 528
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 696
container[57].j= 535
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 697
container[58].j= 528
container[58].angle= 0
container[58].value= 255


container[59].bin= 54
container[59].i= 697
container[59].j= 531
container[59].angle= 270
container[59].value= 255


container[60].bin= 63
container[60].i= 697
container[60].j= 532
container[60].angle= 315
container[60].value= 255


container[61].bin= 41
container[61].i= 697
container[61].j= 535
container[61].angle= 206
container[61].value= 255


container[62].bin= 5
container[62].i= 698
container[62].j= 528
container[62].angle= 26
container[62].value= 255


container[63].bin= 0
container[63].i= 698
container[63].j= 532
container[63].angle= 0
container[63].value= 255


container[64].bin= 44
container[64].i= 698
container[64].j= 534
container[64].angle= 224
container[64].value= 255


container[65].bin= 44
container[65].i= 698
container[65].j= 535
container[65].angle= 224
container[65].value= 255


container[66].bin= 0
container[66].i= 699
container[66].j= 528
container[66].angle= 0
container[66].value= 255


container[67].bin= 41
container[67].i= 699
container[67].j= 534
container[67].angle= 206
container[67].value= 255


container[68].bin= 66
container[68].i= 700
container[68].j= 528
container[68].angle= 333
container[68].value= 255


container[69].bin= 36
container[69].i= 700
container[69].j= 533
container[69].angle= 180
container[69].value= 255


container[70].bin= 0
container[70].i= 701
container[70].j= 528
container[70].angle= 0
container[70].value= 255


container[71].bin= 21
container[71].i= 701
container[71].j= 530
container[71].angle= 108
container[71].value= 255


container[72].bin= 14
container[72].i= 701
container[72].j= 531
container[72].angle= 71
container[72].value= 255


container[73].bin= 36
container[73].i= 701
container[73].j= 533
container[73].angle= 180
container[73].value= 255


container[74].bin= 0
container[74].i= 702
container[74].j= 528
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 702
container[75].j= 533
container[75].angle= 180
container[75].value= 255


container[76].bin= 54
container[76].i= 703
container[76].j= 530
container[76].angle= 270
container[76].value= 255


container[77].bin= 36
container[77].i= 703
container[77].j= 533
container[77].angle= 180
container[77].value= 255


container[78].bin= 8
container[78].i= 704
container[78].j= 527
container[78].angle= 44
container[78].value= 255


container[79].bin= 63
container[79].i= 704
container[79].j= 531
container[79].angle= 315
container[79].value= 255


container[80].bin= 0
container[80].i= 705
container[80].j= 526
container[80].angle= 0
container[80].value= 255


container[81].bin= 0
container[81].i= 705
container[81].j= 531
container[81].angle= 0
container[81].value= 255


container[82].bin= 0
container[82].i= 706
container[82].j= 526
container[82].angle= 0
container[82].value= 255


container[83].bin= 63
container[83].i= 706
container[83].j= 532
container[83].angle= 315
container[83].value= 255


container[84].bin= 44
container[84].i= 706
container[84].j= 533
container[84].angle= 224
container[84].value= 255


container[85].bin= 8
container[85].i= 707
container[85].j= 521
container[85].angle= 44
container[85].value= 255


container[86].bin= 27
container[86].i= 707
container[86].j= 522
container[86].angle= 135
container[86].value= 255


container[87].bin= 0
container[87].i= 707
container[87].j= 526
container[87].angle= 0
container[87].value= 255


container[88].bin= 0
container[88].i= 708
container[88].j= 520
container[88].angle= 0
container[88].value= 255


container[89].bin= 0
container[89].i= 708
container[89].j= 526
container[89].angle= 0
container[89].value= 255


container[90].bin= 0
container[90].i= 709
container[90].j= 520
container[90].angle= 0
container[90].value= 255


container[91].bin= 27
container[91].i= 709
container[91].j= 523
container[91].angle= 135
container[91].value= 255


container[92].bin= 18
container[92].i= 709
container[92].j= 524
container[92].angle= 90
container[92].value= 255


container[93].bin= 18
container[93].i= 709
container[93].j= 525
container[93].angle= 90
container[93].value= 255


container[94].bin= 8
container[94].i= 709
container[94].j= 526
container[94].angle= 44
container[94].value= 255


container[95].bin= 27
container[95].i= 709
container[95].j= 529
container[95].angle= 135
container[95].value= 255


container[96].bin= 18
container[96].i= 709
container[96].j= 530
container[96].angle= 90
container[96].value= 255


container[97].bin= 0
container[97].i= 710
container[97].j= 520
container[97].angle= 0
container[97].value= 255


container[98].bin= 27
container[98].i= 710
container[98].j= 531
container[98].angle= 135
container[98].value= 255


container[99].bin= 0
container[99].i= 711
container[99].j= 520
container[99].angle= 0
container[99].value= 255


container[100].bin= 36
container[100].i= 711
container[100].j= 531
container[100].angle= 180
container[100].value= 255


container[101].bin= 66
container[101].i= 712
container[101].j= 521
container[101].angle= 333
container[101].value= 255


container[102].bin= 36
container[102].i= 712
container[102].j= 531
container[102].angle= 180
container[102].value= 255


container[103].bin= 66
container[103].i= 713
container[103].j= 521
container[103].angle= 333
container[103].value= 255


container[104].bin= 36
container[104].i= 713
container[104].j= 531
container[104].angle= 180
container[104].value= 255


container[105].bin= 5
container[105].i= 714
container[105].j= 521
container[105].angle= 26
container[105].value= 255


container[106].bin= 36
container[106].i= 714
container[106].j= 531
container[106].angle= 180
container[106].value= 255


container[107].bin= 0
container[107].i= 715
container[107].j= 521
container[107].angle= 0
container[107].value= 255


container[108].bin= 36
container[108].i= 715
container[108].j= 531
container[108].angle= 180
container[108].value= 255


container[109].bin= 14
container[109].i= 715
container[109].j= 534
container[109].angle= 71
container[109].value= 255


container[110].bin= 21
container[110].i= 715
container[110].j= 535
container[110].angle= 108
container[110].value= 255


container[111].bin= 18
container[111].i= 715
container[111].j= 536
container[111].angle= 90
container[111].value= 255


container[112].bin= 14
container[112].i= 715
container[112].j= 537
container[112].angle= 71
container[112].value= 255


container[113].bin= 21
container[113].i= 715
container[113].j= 538
container[113].angle= 108
container[113].value= 255


container[114].bin= 66
container[114].i= 716
container[114].j= 521
container[114].angle= 333
container[114].value= 255


container[115].bin= 27
container[115].i= 716
container[115].j= 532
container[115].angle= 135
container[115].value= 255


container[116].bin= 14
container[116].i= 716
container[116].j= 533
container[116].angle= 71
container[116].value= 255


container[117].bin= 8
container[117].i= 716
container[117].j= 537
container[117].angle= 44
container[117].value= 255


container[118].bin= 27
container[118].i= 716
container[118].j= 538
container[118].angle= 135
container[118].value= 255


container[119].bin= 0
container[119].i= 717
container[119].j= 521
container[119].angle= 0
container[119].value= 255


container[120].bin= 36
container[120].i= 717
container[120].j= 539
container[120].angle= 180
container[120].value= 255


container[121].bin= 63
container[121].i= 718
container[121].j= 522
container[121].angle= 315
container[121].value= 255


container[122].bin= 36
container[122].i= 718
container[122].j= 532
container[122].angle= 180
container[122].value= 255


container[123].bin= 14
container[123].i= 718
container[123].j= 534
container[123].angle= 71
container[123].value= 255


container[124].bin= 14
container[124].i= 718
container[124].j= 535
container[124].angle= 71
container[124].value= 255


container[125].bin= 32
container[125].i= 718
container[125].j= 538
container[125].angle= 161
container[125].value= 255


container[126].bin= 63
container[126].i= 719
container[126].j= 523
container[126].angle= 315
container[126].value= 255


container[127].bin= 30
container[127].i= 719
container[127].j= 539
container[127].angle= 153
container[127].value= 255


container[128].bin= 0
container[128].i= 720
container[128].j= 523
container[128].angle= 0
container[128].value= 255


container[129].bin= 30
container[129].i= 720
container[129].j= 539
container[129].angle= 153
container[129].value= 255


container[130].bin= 0
container[130].i= 721
container[130].j= 523
container[130].angle= 0
container[130].value= 255


container[131].bin= 44
container[131].i= 721
container[131].j= 527
container[131].angle= 224
container[131].value= 255


container[132].bin= 54
container[132].i= 721
container[132].j= 528
container[132].angle= 270
container[132].value= 255


container[133].bin= 63
container[133].i= 721
container[133].j= 529
container[133].angle= 315
container[133].value= 255


container[134].bin= 36
container[134].i= 721
container[134].j= 539
container[134].angle= 180
container[134].value= 255


container[135].bin= 0
container[135].i= 722
container[135].j= 523
container[135].angle= 0
container[135].value= 255


container[136].bin= 54
container[136].i= 722
container[136].j= 526
container[136].angle= 270
container[136].value= 255


container[137].bin= 44
container[137].i= 722
container[137].j= 527
container[137].angle= 224
container[137].value= 255


container[138].bin= 0
container[138].i= 722
container[138].j= 529
container[138].angle= 0
container[138].value= 255


container[139].bin= 36
container[139].i= 722
container[139].j= 539
container[139].angle= 180
container[139].value= 255


container[140].bin= 0
container[140].i= 723
container[140].j= 523
container[140].angle= 0
container[140].value= 255


container[141].bin= 0
container[141].i= 723
container[141].j= 529
container[141].angle= 0
container[141].value= 255


container[142].bin= 36
container[142].i= 723
container[142].j= 539
container[142].angle= 180
container[142].value= 255


container[143].bin= 66
container[143].i= 724
container[143].j= 524
container[143].angle= 333
container[143].value= 255


container[144].bin= 57
container[144].i= 724
container[144].j= 527
container[144].angle= 288
container[144].value= 255


container[145].bin= 54
container[145].i= 724
container[145].j= 528
container[145].angle= 270
container[145].value= 255


container[146].bin= 59
container[146].i= 724
container[146].j= 529
container[146].angle= 296
container[146].value= 255


container[147].bin= 54
container[147].i= 724
container[147].j= 530
container[147].angle= 270
container[147].value= 255


container[148].bin= 36
container[148].i= 724
container[148].j= 539
container[148].angle= 180
container[148].value= 255


container[149].bin= 66
container[149].i= 725
container[149].j= 524
container[149].angle= 333
container[149].value= 255


container[150].bin= 39
container[150].i= 725
container[150].j= 526
container[150].angle= 198
container[150].value= 255


container[151].bin= 63
container[151].i= 725
container[151].j= 531
container[151].angle= 315
container[151].value= 255


container[152].bin= 36
container[152].i= 725
container[152].j= 539
container[152].angle= 180
container[152].value= 255


container[153].bin= 0
container[153].i= 726
container[153].j= 524
container[153].angle= 0
container[153].value= 255


container[154].bin= 36
container[154].i= 726
container[154].j= 526
container[154].angle= 180
container[154].value= 255


container[155].bin= 0
container[155].i= 726
container[155].j= 531
container[155].angle= 0
container[155].value= 255


container[156].bin= 36
container[156].i= 726
container[156].j= 539
container[156].angle= 180
container[156].value= 255


container[157].bin= 68
container[157].i= 727
container[157].j= 524
container[157].angle= 341
container[157].value= 255


container[158].bin= 54
container[158].i= 727
container[158].j= 525
container[158].angle= 270
container[158].value= 255


container[159].bin= 39
container[159].i= 727
container[159].j= 526
container[159].angle= 198
container[159].value= 255


container[160].bin= 66
container[160].i= 727
container[160].j= 532
container[160].angle= 333
container[160].value= 255


container[161].bin= 41
container[161].i= 727
container[161].j= 539
container[161].angle= 206
container[161].value= 255


container[162].bin= 66
container[162].i= 728
container[162].j= 532
container[162].angle= 333
container[162].value= 255


container[163].bin= 41
container[163].i= 728
container[163].j= 539
container[163].angle= 206
container[163].value= 255


container[164].bin= 0
container[164].i= 729
container[164].j= 532
container[164].angle= 0
container[164].value= 255


container[165].bin= 36
container[165].i= 729
container[165].j= 538
container[165].angle= 180
container[165].value= 255


container[166].bin= 5
container[166].i= 730
container[166].j= 532
container[166].angle= 26
container[166].value= 255


container[167].bin= 54
container[167].i= 730
container[167].j= 537
container[167].angle= 270
container[167].value= 255


container[168].bin= 44
container[168].i= 730
container[168].j= 538
container[168].angle= 224
container[168].value= 255


container[169].bin= 5
container[169].i= 731
container[169].j= 532
container[169].angle= 26
container[169].value= 255


container[170].bin= 44
container[170].i= 731
container[170].j= 536
container[170].angle= 224
container[170].value= 255


container[171].bin= 0
container[171].i= 732
container[171].j= 531
container[171].angle= 0
container[171].value= 255


container[172].bin= 36
container[172].i= 732
container[172].j= 535
container[172].angle= 180
container[172].value= 255


container[173].bin= 18
container[173].i= 733
container[173].j= 530
container[173].angle= 90
container[173].value= 255


container[174].bin= 8
container[174].i= 733
container[174].j= 531
container[174].angle= 44
container[174].value= 255


container[175].bin= 36
container[175].i= 733
container[175].j= 535
container[175].angle= 180
container[175].value= 255


container[176].bin= 8
container[176].i= 734
container[176].j= 529
container[176].angle= 44
container[176].value= 255


container[177].bin= 36
container[177].i= 734
container[177].j= 535
container[177].angle= 180
container[177].value= 255


container[178].bin= 0
container[178].i= 735
container[178].j= 528
container[178].angle= 0
container[178].value= 255


container[179].bin= 36
container[179].i= 735
container[179].j= 535
container[179].angle= 180
container[179].value= 255


container[180].bin= 0
container[180].i= 736
container[180].j= 528
container[180].angle= 0
container[180].value= 255


container[181].bin= 27
container[181].i= 736
container[181].j= 536
container[181].angle= 135
container[181].value= 255


container[182].bin= 18
container[182].i= 736
container[182].j= 537
container[182].angle= 90
container[182].value= 255


container[183].bin= 21
container[183].i= 736
container[183].j= 538
container[183].angle= 108
container[183].value= 255


container[184].bin= 0
container[184].i= 737
container[184].j= 528
container[184].angle= 0
container[184].value= 255


container[185].bin= 27
container[185].i= 737
container[185].j= 538
container[185].angle= 135
container[185].value= 255


container[186].bin= 0
container[186].i= 738
container[186].j= 528
container[186].angle= 0
container[186].value= 255


container[187].bin= 36
container[187].i= 738
container[187].j= 536
container[187].angle= 180
container[187].value= 255


container[188].bin= 36
container[188].i= 738
container[188].j= 539
container[188].angle= 180
container[188].value= 255


container[189].bin= 0
container[189].i= 739
container[189].j= 528
container[189].angle= 0
container[189].value= 255


container[190].bin= 27
container[190].i= 739
container[190].j= 536
container[190].angle= 135
container[190].value= 255


container[191].bin= 18
container[191].i= 739
container[191].j= 537
container[191].angle= 90
container[191].value= 255


container[192].bin= 32
container[192].i= 739
container[192].j= 538
container[192].angle= 161
container[192].value= 255


container[193].bin= 0
container[193].i= 740
container[193].j= 528
container[193].angle= 0
container[193].value= 255


container[194].bin= 36
container[194].i= 740
container[194].j= 538
container[194].angle= 180
container[194].value= 255


container[195].bin= 0
container[195].i= 741
container[195].j= 528
container[195].angle= 0
container[195].value= 255


container[196].bin= 36
container[196].i= 741
container[196].j= 538
container[196].angle= 180
container[196].value= 255


container[197].bin= 18
container[197].i= 742
container[197].j= 527
container[197].angle= 90
container[197].value= 255


container[198].bin= 66
container[198].i= 742
container[198].j= 529
container[198].angle= 333
container[198].value= 255


container[199].bin= 36
container[199].i= 742
container[199].j= 538
container[199].angle= 180
container[199].value= 255


container[200].bin= 3
container[200].i= 743
container[200].j= 526
container[200].angle= 18
container[200].value= 255


container[201].bin= 66
container[201].i= 743
container[201].j= 529
container[201].angle= 333
container[201].value= 255


container[202].bin= 36
container[202].i= 743
container[202].j= 538
container[202].angle= 180
container[202].value= 255


container[203].bin= 8
container[203].i= 743
container[203].j= 542
container[203].angle= 44
container[203].value= 255


container[204].bin= 12
container[204].i= 743
container[204].j= 543
container[204].angle= 63
container[204].value= 255


container[205].bin= 27
container[205].i= 743
container[205].j= 544
container[205].angle= 135
container[205].value= 255


container[206].bin= 0
container[206].i= 744
container[206].j= 526
container[206].angle= 0
container[206].value= 255


container[207].bin= 36
container[207].i= 744
container[207].j= 528
container[207].angle= 180
container[207].value= 255


container[208].bin= 36
container[208].i= 744
container[208].j= 538
container[208].angle= 180
container[208].value= 255


container[209].bin= 3
container[209].i= 744
container[209].j= 541
container[209].angle= 18
container[209].value= 255


container[210].bin= 39
container[210].i= 744
container[210].j= 544
container[210].angle= 198
container[210].value= 255


container[211].bin= 0
container[211].i= 745
container[211].j= 526
container[211].angle= 0
container[211].value= 255


container[212].bin= 5
container[212].i= 745
container[212].j= 529
container[212].angle= 26
container[212].value= 255


container[213].bin= 36
container[213].i= 745
container[213].j= 538
container[213].angle= 180
container[213].value= 255


container[214].bin= 3
container[214].i= 745
container[214].j= 541
container[214].angle= 18
container[214].value= 255


container[215].bin= 36
container[215].i= 745
container[215].j= 545
container[215].angle= 180
container[215].value= 255


container[216].bin= 8
container[216].i= 746
container[216].j= 526
container[216].angle= 44
container[216].value= 255


container[217].bin= 18
container[217].i= 746
container[217].j= 527
container[217].angle= 90
container[217].value= 255


container[218].bin= 8
container[218].i= 746
container[218].j= 529
container[218].angle= 44
container[218].value= 255


container[219].bin= 41
container[219].i= 746
container[219].j= 538
container[219].angle= 206
container[219].value= 255


container[220].bin= 8
container[220].i= 746
container[220].j= 540
container[220].angle= 44
container[220].value= 255


container[221].bin= 8
container[221].i= 747
container[221].j= 525
container[221].angle= 44
container[221].value= 255


container[222].bin= 44
container[222].i= 747
container[222].j= 537
container[222].angle= 224
container[222].value= 255


container[223].bin= 44
container[223].i= 747
container[223].j= 538
container[223].angle= 224
container[223].value= 255


container[224].bin= 5
container[224].i= 747
container[224].j= 540
container[224].angle= 26
container[224].value= 255


container[225].bin= 36
container[225].i= 747
container[225].j= 544
container[225].angle= 180
container[225].value= 255


container[226].bin= 0
container[226].i= 748
container[226].j= 524
container[226].angle= 0
container[226].value= 255


container[227].bin= 41
container[227].i= 748
container[227].j= 537
container[227].angle= 206
container[227].value= 255


container[228].bin= 0
container[228].i= 748
container[228].j= 539
container[228].angle= 0
container[228].value= 255


container[229].bin= 36
container[229].i= 748
container[229].j= 544
container[229].angle= 180
container[229].value= 255


container[230].bin= 63
container[230].i= 749
container[230].j= 525
container[230].angle= 315
container[230].value= 255


container[231].bin= 36
container[231].i= 749
container[231].j= 536
container[231].angle= 180
container[231].value= 255


container[232].bin= 0
container[232].i= 749
container[232].j= 539
container[232].angle= 0
container[232].value= 255


container[233].bin= 54
container[233].i= 749
container[233].j= 543
container[233].angle= 270
container[233].value= 255


container[234].bin= 44
container[234].i= 749
container[234].j= 544
container[234].angle= 224
container[234].value= 255


container[235].bin= 63
container[235].i= 750
container[235].j= 526
container[235].angle= 315
container[235].value= 255


container[236].bin= 36
container[236].i= 750
container[236].j= 536
container[236].angle= 180
container[236].value= 255


container[237].bin= 0
container[237].i= 750
container[237].j= 539
container[237].angle= 0
container[237].value= 255


container[238].bin= 44
container[238].i= 750
container[238].j= 542
container[238].angle= 224
container[238].value= 255


container[239].bin= 0
container[239].i= 751
container[239].j= 526
container[239].angle= 0
container[239].value= 255


container[240].bin= 36
container[240].i= 751
container[240].j= 536
container[240].angle= 180
container[240].value= 255


container[241].bin= 0
container[241].i= 751
container[241].j= 539
container[241].angle= 0
container[241].value= 255


container[242].bin= 0
container[242].i= 752
container[242].j= 526
container[242].angle= 0
container[242].value= 255


container[243].bin= 27
container[243].i= 752
container[243].j= 537
container[243].angle= 135
container[243].value= 255


container[244].bin= 18
container[244].i= 752
container[244].j= 538
container[244].angle= 90
container[244].value= 255


container[245].bin= 8
container[245].i= 752
container[245].j= 539
container[245].angle= 44
container[245].value= 255


container[246].bin= 0
container[246].i= 753
container[246].j= 526
container[246].angle= 0
container[246].value= 255


container[247].bin= 36
container[247].i= 753
container[247].j= 541
container[247].angle= 180
container[247].value= 255


container[248].bin= 0
container[248].i= 754
container[248].j= 526
container[248].angle= 0
container[248].value= 255


container[249].bin= 36
container[249].i= 754
container[249].j= 541
container[249].angle= 180
container[249].value= 255


container[250].bin= 0
container[250].i= 755
container[250].j= 526
container[250].angle= 0
container[250].value= 255


container[251].bin= 0
container[251].i= 756
container[251].j= 526
container[251].angle= 0
container[251].value= 255


container[252].bin= 44
container[252].i= 756
container[252].j= 539
container[252].angle= 224
container[252].value= 255


container[253].bin= 63
container[253].i= 756
container[253].j= 540
container[253].angle= 315
container[253].value= 255


container[254].bin= 36
container[254].i= 756
container[254].j= 542
container[254].angle= 180
container[254].value= 255


container[255].bin= 0
container[255].i= 757
container[255].j= 526
container[255].angle= 0
container[255].value= 255


container[256].bin= 36
container[256].i= 757
container[256].j= 538
container[256].angle= 180
container[256].value= 255


container[257].bin= 36
container[257].i= 757
container[257].j= 542
container[257].angle= 180
container[257].value= 255


container[258].bin= 0
container[258].i= 758
container[258].j= 526
container[258].angle= 0
container[258].value= 255


container[259].bin= 36
container[259].i= 758
container[259].j= 538
container[259].angle= 180
container[259].value= 255


container[260].bin= 36
container[260].i= 758
container[260].j= 542
container[260].angle= 180
container[260].value= 255


container[261].bin= 66
container[261].i= 759
container[261].j= 527
container[261].angle= 333
container[261].value= 255


container[262].bin= 36
container[262].i= 759
container[262].j= 538
container[262].angle= 180
container[262].value= 255


container[263].bin= 36
container[263].i= 759
container[263].j= 542
container[263].angle= 180
container[263].value= 255


container[264].bin= 68
container[264].i= 760
container[264].j= 527
container[264].angle= 341
container[264].value= 255


container[265].bin= 63
container[265].i= 760
container[265].j= 528
container[265].angle= 315
container[265].value= 255


container[266].bin= 36
container[266].i= 760
container[266].j= 538
container[266].angle= 180
container[266].value= 255


container[267].bin= 36
container[267].i= 760
container[267].j= 542
container[267].angle= 180
container[267].value= 255


container[268].bin= 0
container[268].i= 761
container[268].j= 526
container[268].angle= 0
container[268].value= 255


container[269].bin= 63
container[269].i= 761
container[269].j= 528
container[269].angle= 315
container[269].value= 255


container[270].bin= 27
container[270].i= 761
container[270].j= 539
container[270].angle= 135
container[270].value= 255


container[271].bin= 8
container[271].i= 761
container[271].j= 540
container[271].angle= 44
container[271].value= 255


container[272].bin= 36
container[272].i= 761
container[272].j= 542
container[272].angle= 180
container[272].value= 255


container[273].bin= 68
container[273].i= 762
container[273].j= 528
container[273].angle= 341
container[273].value= 255


container[274].bin= 0
container[274].i= 763
container[274].j= 528
container[274].angle= 0
container[274].value= 255


container[275].bin= 36
container[275].i= 763
container[275].j= 541
container[275].angle= 180
container[275].value= 255


container[276].bin= 0
container[276].i= 764
container[276].j= 528
container[276].angle= 0
container[276].value= 255


container[277].bin= 54
container[277].i= 764
container[277].j= 537
container[277].angle= 270
container[277].value= 255


container[278].bin= 54
container[278].i= 764
container[278].j= 538
container[278].angle= 270
container[278].value= 255


container[279].bin= 54
container[279].i= 764
container[279].j= 539
container[279].angle= 270
container[279].value= 255


container[280].bin= 54
container[280].i= 764
container[280].j= 540
container[280].angle= 270
container[280].value= 255


container[281].bin= 44
container[281].i= 764
container[281].j= 541
container[281].angle= 224
container[281].value= 255


container[282].bin= 0
container[282].i= 765
container[282].j= 528
container[282].angle= 0
container[282].value= 255


container[283].bin= 44
container[283].i= 765
container[283].j= 536
container[283].angle= 224
container[283].value= 255


container[284].bin= 0
container[284].i= 766
container[284].j= 528
container[284].angle= 0
container[284].value= 255


container[285].bin= 36
container[285].i= 766
container[285].j= 535
container[285].angle= 180
container[285].value= 255


container[286].bin= 8
container[286].i= 767
container[286].j= 528
container[286].angle= 44
container[286].value= 255


container[287].bin= 54
container[287].i= 767
container[287].j= 532
container[287].angle= 270
container[287].value= 255


container[288].bin= 36
container[288].i= 767
container[288].j= 535
container[288].angle= 180
container[288].value= 255


container[289].bin= 8
container[289].i= 768
container[289].j= 527
container[289].angle= 44
container[289].value= 255


container[290].bin= 44
container[290].i= 768
container[290].j= 531
container[290].angle= 224
container[290].value= 255


container[291].bin= 36
container[291].i= 768
container[291].j= 535
container[291].angle= 180
container[291].value= 255


container[292].bin= 0
container[292].i= 769
container[292].j= 526
container[292].angle= 0
container[292].value= 255


container[293].bin= 36
container[293].i= 769
container[293].j= 530
container[293].angle= 180
container[293].value= 255


container[294].bin= 36
container[294].i= 769
container[294].j= 535
container[294].angle= 180
container[294].value= 255


container[295].bin= 63
container[295].i= 770
container[295].j= 527
container[295].angle= 315
container[295].value= 255


container[296].bin= 39
container[296].i= 770
container[296].j= 531
container[296].angle= 198
container[296].value= 255


container[297].bin= 57
container[297].i= 770
container[297].j= 532
container[297].angle= 288
container[297].value= 255


container[298].bin= 59
container[298].i= 770
container[298].j= 533
container[298].angle= 296
container[298].value= 255


container[299].bin= 54
container[299].i= 770
container[299].j= 534
container[299].angle= 270
container[299].value= 255


container[300].bin= 44
container[300].i= 770
container[300].j= 535
container[300].angle= 224
container[300].value= 255


container[301].bin= 63
container[301].i= 771
container[301].j= 528
container[301].angle= 315
container[301].value= 255


container[302].bin= 41
container[302].i= 771
container[302].j= 531
container[302].angle= 206
container[302].value= 255


container[303].bin= 0
container[303].i= 772
container[303].j= 528
container[303].angle= 0
container[303].value= 255


container[304].bin= 63
container[304].i= 773
container[304].j= 529
container[304].angle= 315
container[304].value= 255


container[305].bin= 44
container[305].i= 773
container[305].j= 530
container[305].angle= 224
container[305].value= 255


