container[0].bin= 18
container[0].i= 294
container[0].j= 191
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 295
container[1].j= 190
container[1].angle= 18
container[1].value= 255


container[2].bin= 27
container[2].i= 295
container[2].j= 192
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 296
container[3].j= 190
container[3].angle= 0
container[3].value= 255


container[4].bin= 21
container[4].i= 296
container[4].j= 193
container[4].angle= 108
container[4].value= 255


container[5].bin= 68
container[5].i= 297
container[5].j= 190
container[5].angle= 341
container[5].value= 255


container[6].bin= 27
container[6].i= 297
container[6].j= 194
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 297
container[7].j= 195
container[7].angle= 90
container[7].value= 255


container[8].bin= 63
container[8].i= 298
container[8].j= 192
container[8].angle= 315
container[8].value= 255


container[9].bin= 27
container[9].i= 298
container[9].j= 196
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 299
container[10].j= 192
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 299
container[11].j= 196
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 300
container[12].j= 193
container[12].angle= 315
container[12].value= 255


container[13].bin= 30
container[13].i= 300
container[13].j= 197
container[13].angle= 153
container[13].value= 255


container[14].bin= 63
container[14].i= 301
container[14].j= 194
container[14].angle= 315
container[14].value= 255


container[15].bin= 30
container[15].i= 301
container[15].j= 197
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 302
container[16].j= 194
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 302
container[17].j= 197
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 303
container[18].j= 195
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 303
container[19].j= 196
container[19].angle= 270
container[19].value= 255


container[20].bin= 44
container[20].i= 303
container[20].j= 197
container[20].angle= 224
container[20].value= 255


