container[0].bin= 8
container[0].i= 620
container[0].j= 548
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 620
container[1].j= 549
container[1].angle= 108
container[1].value= 255


container[2].bin= 63
container[2].i= 622
container[2].j= 548
container[2].angle= 315
container[2].value= 255


