container[0].bin= 18
container[0].i= 231
container[0].j= 205
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 232
container[1].j= 202
container[1].angle= 18
container[1].value= 255


container[2].bin= 14
container[2].i= 232
container[2].j= 203
container[2].angle= 71
container[2].value= 255


container[3].bin= 21
container[3].i= 232
container[3].j= 204
container[3].angle= 108
container[3].value= 255


container[4].bin= 14
container[4].i= 232
container[4].j= 206
container[4].angle= 71
container[4].value= 255


container[5].bin= 21
container[5].i= 232
container[5].j= 207
container[5].angle= 108
container[5].value= 255


container[6].bin= 68
container[6].i= 233
container[6].j= 202
container[6].angle= 341
container[6].value= 255


container[7].bin= 3
container[7].i= 233
container[7].j= 206
container[7].angle= 18
container[7].value= 255


container[8].bin= 63
container[8].i= 234
container[8].j= 203
container[8].angle= 315
container[8].value= 255


container[9].bin= 50
container[9].i= 234
container[9].j= 204
container[9].angle= 251
container[9].value= 255


container[10].bin= 54
container[10].i= 234
container[10].j= 205
container[10].angle= 270
container[10].value= 255


container[11].bin= 63
container[11].i= 234
container[11].j= 206
container[11].angle= 315
container[11].value= 255


container[12].bin= 44
container[12].i= 234
container[12].j= 207
container[12].angle= 224
container[12].value= 255


