container[0].bin= 3
container[0].i= 32
container[0].j= 183
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 32
container[1].j= 184
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 32
container[2].j= 185
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 33
container[3].j= 183
container[3].angle= 26
container[3].value= 255


container[4].bin= 27
container[4].i= 33
container[4].j= 185
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 33
container[5].j= 186
container[5].angle= 135
container[5].value= 255


container[6].bin= 5
container[6].i= 34
container[6].j= 183
container[6].angle= 26
container[6].value= 255


container[7].bin= 30
container[7].i= 34
container[7].j= 186
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 35
container[8].j= 182
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 35
container[9].j= 187
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 36
container[10].j= 182
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 36
container[11].j= 187
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 37
container[12].j= 182
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 37
container[13].j= 187
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 38
container[14].j= 182
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 38
container[15].j= 187
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 39
container[16].j= 182
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 39
container[17].j= 187
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 40
container[18].j= 182
container[18].angle= 0
container[18].value= 255


container[19].bin= 41
container[19].i= 40
container[19].j= 187
container[19].angle= 206
container[19].value= 255


container[20].bin= 0
container[20].i= 41
container[20].j= 182
container[20].angle= 0
container[20].value= 255


container[21].bin= 41
container[21].i= 41
container[21].j= 187
container[21].angle= 206
container[21].value= 255


container[22].bin= 0
container[22].i= 42
container[22].j= 182
container[22].angle= 0
container[22].value= 255


container[23].bin= 41
container[23].i= 42
container[23].j= 186
container[23].angle= 206
container[23].value= 255


container[24].bin= 0
container[24].i= 43
container[24].j= 182
container[24].angle= 0
container[24].value= 255


container[25].bin= 41
container[25].i= 43
container[25].j= 186
container[25].angle= 206
container[25].value= 255


container[26].bin= 5
container[26].i= 44
container[26].j= 182
container[26].angle= 26
container[26].value= 255


container[27].bin= 36
container[27].i= 44
container[27].j= 185
container[27].angle= 180
container[27].value= 255


container[28].bin= 8
container[28].i= 45
container[28].j= 181
container[28].angle= 44
container[28].value= 255


container[29].bin= 8
container[29].i= 45
container[29].j= 182
container[29].angle= 44
container[29].value= 255


container[30].bin= 36
container[30].i= 45
container[30].j= 185
container[30].angle= 180
container[30].value= 255


container[31].bin= 8
container[31].i= 46
container[31].j= 180
container[31].angle= 44
container[31].value= 255


container[32].bin= 8
container[32].i= 46
container[32].j= 181
container[32].angle= 44
container[32].value= 255


container[33].bin= 36
container[33].i= 46
container[33].j= 185
container[33].angle= 180
container[33].value= 255


container[34].bin= 5
container[34].i= 47
container[34].j= 180
container[34].angle= 26
container[34].value= 255


container[35].bin= 36
container[35].i= 47
container[35].j= 185
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 48
container[36].j= 179
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 48
container[37].j= 185
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 49
container[38].j= 179
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 49
container[39].j= 185
container[39].angle= 180
container[39].value= 255


container[40].bin= 66
container[40].i= 50
container[40].j= 180
container[40].angle= 333
container[40].value= 255


container[41].bin= 41
container[41].i= 50
container[41].j= 185
container[41].angle= 206
container[41].value= 255


container[42].bin= 66
container[42].i= 51
container[42].j= 180
container[42].angle= 333
container[42].value= 255


container[43].bin= 41
container[43].i= 51
container[43].j= 185
container[43].angle= 206
container[43].value= 255


container[44].bin= 63
container[44].i= 52
container[44].j= 181
container[44].angle= 315
container[44].value= 255


container[45].bin= 36
container[45].i= 52
container[45].j= 184
container[45].angle= 180
container[45].value= 255


container[46].bin= 59
container[46].i= 53
container[46].j= 182
container[46].angle= 296
container[46].value= 255


container[47].bin= 59
container[47].i= 53
container[47].j= 183
container[47].angle= 296
container[47].value= 255


container[48].bin= 44
container[48].i= 53
container[48].j= 184
container[48].angle= 224
container[48].value= 255


