container[0].bin= 8
container[0].i= 432
container[0].j= 113
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 432
container[1].j= 114
container[1].angle= 108
container[1].value= 255


container[2].bin= 0
container[2].i= 433
container[2].j= 113
container[2].angle= 0
container[2].value= 255


container[3].bin= 36
container[3].i= 433
container[3].j= 115
container[3].angle= 180
container[3].value= 255


container[4].bin= 0
container[4].i= 434
container[4].j= 113
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 434
container[5].j= 115
container[5].angle= 180
container[5].value= 255


container[6].bin= 68
container[6].i= 435
container[6].j= 113
container[6].angle= 341
container[6].value= 255


