container[0].bin= 8
container[0].i= 196
container[0].j= 233
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 196
container[1].j= 234
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 197
container[2].j= 232
container[2].angle= 0
container[2].value= 255


container[3].bin= 63
container[3].i= 198
container[3].j= 233
container[3].angle= 315
container[3].value= 255


container[4].bin= 18
container[4].i= 198
container[4].j= 236
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 198
container[5].j= 237
container[5].angle= 90
container[5].value= 255


container[6].bin= 27
container[6].i= 199
container[6].j= 238
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 200
container[7].j= 234
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 200
container[8].j= 238
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 201
container[9].j= 234
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 201
container[10].j= 238
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 202
container[11].j= 234
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 202
container[12].j= 238
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 203
container[13].j= 234
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 203
container[14].j= 238
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 204
container[15].j= 234
container[15].angle= 0
container[15].value= 255


container[16].bin= 50
container[16].i= 204
container[16].j= 237
container[16].angle= 251
container[16].value= 255


container[17].bin= 44
container[17].i= 204
container[17].j= 238
container[17].angle= 224
container[17].value= 255


container[18].bin= 0
container[18].i= 205
container[18].j= 234
container[18].angle= 0
container[18].value= 255


container[19].bin= 44
container[19].i= 205
container[19].j= 237
container[19].angle= 224
container[19].value= 255


container[20].bin= 8
container[20].i= 205
container[20].j= 241
container[20].angle= 44
container[20].value= 255


container[21].bin= 27
container[21].i= 205
container[21].j= 242
container[21].angle= 135
container[21].value= 255


container[22].bin= 0
container[22].i= 206
container[22].j= 234
container[22].angle= 0
container[22].value= 255


container[23].bin= 32
container[23].i= 206
container[23].j= 239
container[23].angle= 161
container[23].value= 255


container[24].bin= 8
container[24].i= 207
container[24].j= 234
container[24].angle= 44
container[24].value= 255


container[25].bin= 27
container[25].i= 207
container[25].j= 239
container[25].angle= 135
container[25].value= 255


container[26].bin= 8
container[26].i= 207
container[26].j= 240
container[26].angle= 44
container[26].value= 255


container[27].bin= 27
container[27].i= 207
container[27].j= 243
container[27].angle= 135
container[27].value= 255


container[28].bin= 8
container[28].i= 208
container[28].j= 233
container[28].angle= 44
container[28].value= 255


container[29].bin= 27
container[29].i= 208
container[29].j= 244
container[29].angle= 135
container[29].value= 255


container[30].bin= 0
container[30].i= 209
container[30].j= 232
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 209
container[31].j= 244
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 210
container[32].j= 233
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 210
container[33].j= 234
container[33].angle= 270
container[33].value= 255


container[34].bin= 27
container[34].i= 210
container[34].j= 245
container[34].angle= 135
container[34].value= 255


container[35].bin= 63
container[35].i= 211
container[35].j= 235
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 211
container[36].j= 246
container[36].angle= 135
container[36].value= 255


container[37].bin= 0
container[37].i= 212
container[37].j= 235
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 212
container[38].j= 246
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 213
container[39].j= 235
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 213
container[40].j= 246
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 214
container[41].j= 235
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 214
container[42].j= 246
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 215
container[43].j= 235
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 215
container[44].j= 246
container[44].angle= 180
container[44].value= 255


container[45].bin= 63
container[45].i= 216
container[45].j= 236
container[45].angle= 315
container[45].value= 255


container[46].bin= 48
container[46].i= 216
container[46].j= 237
container[46].angle= 243
container[46].value= 255


container[47].bin= 54
container[47].i= 216
container[47].j= 238
container[47].angle= 270
container[47].value= 255


container[48].bin= 59
container[48].i= 216
container[48].j= 239
container[48].angle= 296
container[48].value= 255


container[49].bin= 57
container[49].i= 216
container[49].j= 240
container[49].angle= 288
container[49].value= 255


container[50].bin= 54
container[50].i= 216
container[50].j= 244
container[50].angle= 270
container[50].value= 255


container[51].bin= 54
container[51].i= 216
container[51].j= 245
container[51].angle= 270
container[51].value= 255


container[52].bin= 44
container[52].i= 216
container[52].j= 246
container[52].angle= 224
container[52].value= 255


container[53].bin= 44
container[53].i= 217
container[53].j= 242
container[53].angle= 224
container[53].value= 255


container[54].bin= 48
container[54].i= 217
container[54].j= 243
container[54].angle= 243
container[54].value= 255


container[55].bin= 41
container[55].i= 218
container[55].j= 242
container[55].angle= 206
container[55].value= 255


container[56].bin= 63
container[56].i= 219
container[56].j= 240
container[56].angle= 315
container[56].value= 255


