container[0].bin= 8
container[0].i= 46
container[0].j= 60
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 46
container[1].j= 61
container[1].angle= 90
container[1].value= 255


container[2].bin= 23
container[2].i= 46
container[2].j= 62
container[2].angle= 116
container[2].value= 255


container[3].bin= 8
container[3].i= 47
container[3].j= 59
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 47
container[4].j= 60
container[4].angle= 44
container[4].value= 255


container[5].bin= 23
container[5].i= 47
container[5].j= 63
container[5].angle= 116
container[5].value= 255


container[6].bin= 27
container[6].i= 47
container[6].j= 64
container[6].angle= 135
container[6].value= 255


container[7].bin= 5
container[7].i= 48
container[7].j= 59
container[7].angle= 26
container[7].value= 255


container[8].bin= 30
container[8].i= 48
container[8].j= 64
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 49
container[9].j= 58
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 49
container[10].j= 65
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 50
container[11].j= 58
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 50
container[12].j= 65
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 50
container[13].j= 66
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 51
container[14].j= 58
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 51
container[15].j= 66
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 51
container[16].j= 67
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 52
container[17].j= 58
container[17].angle= 0
container[17].value= 255


container[18].bin= 27
container[18].i= 52
container[18].j= 67
container[18].angle= 135
container[18].value= 255


container[19].bin= 27
container[19].i= 52
container[19].j= 68
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 53
container[20].j= 58
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 53
container[21].j= 68
container[21].angle= 135
container[21].value= 255


container[22].bin= 27
container[22].i= 53
container[22].j= 69
container[22].angle= 135
container[22].value= 255


container[23].bin= 0
container[23].i= 54
container[23].j= 58
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 54
container[24].j= 69
container[24].angle= 153
container[24].value= 255


container[25].bin= 66
container[25].i= 55
container[25].j= 59
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 55
container[26].j= 70
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 56
container[27].j= 59
container[27].angle= 333
container[27].value= 255


container[28].bin= 30
container[28].i= 56
container[28].j= 70
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 57
container[29].j= 59
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 57
container[30].j= 71
container[30].angle= 153
container[30].value= 255


container[31].bin= 63
container[31].i= 58
container[31].j= 60
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 58
container[32].j= 61
container[32].angle= 270
container[32].value= 255


container[33].bin= 54
container[33].i= 58
container[33].j= 62
container[33].angle= 270
container[33].value= 255


container[34].bin= 27
container[34].i= 58
container[34].j= 71
container[34].angle= 135
container[34].value= 255


container[35].bin= 27
container[35].i= 58
container[35].j= 72
container[35].angle= 135
container[35].value= 255


container[36].bin= 59
container[36].i= 59
container[36].j= 63
container[36].angle= 296
container[36].value= 255


container[37].bin= 59
container[37].i= 59
container[37].j= 64
container[37].angle= 296
container[37].value= 255


container[38].bin= 54
container[38].i= 59
container[38].j= 65
container[38].angle= 270
container[38].value= 255


container[39].bin= 27
container[39].i= 59
container[39].j= 72
container[39].angle= 135
container[39].value= 255


container[40].bin= 27
container[40].i= 59
container[40].j= 73
container[40].angle= 135
container[40].value= 255


container[41].bin= 59
container[41].i= 60
container[41].j= 66
container[41].angle= 296
container[41].value= 255


container[42].bin= 59
container[42].i= 60
container[42].j= 67
container[42].angle= 296
container[42].value= 255


container[43].bin= 30
container[43].i= 60
container[43].j= 73
container[43].angle= 153
container[43].value= 255


container[44].bin= 59
container[44].i= 61
container[44].j= 68
container[44].angle= 296
container[44].value= 255


container[45].bin= 59
container[45].i= 61
container[45].j= 69
container[45].angle= 296
container[45].value= 255


container[46].bin= 36
container[46].i= 61
container[46].j= 73
container[46].angle= 180
container[46].value= 255


container[47].bin= 59
container[47].i= 62
container[47].j= 70
container[47].angle= 296
container[47].value= 255


container[48].bin= 59
container[48].i= 62
container[48].j= 71
container[48].angle= 296
container[48].value= 255


container[49].bin= 59
container[49].i= 63
container[49].j= 72
container[49].angle= 296
container[49].value= 255


