container[0].bin= 3
container[0].i= 403
container[0].j= 375
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 403
container[1].j= 376
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 403
container[2].j= 377
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 404
container[3].j= 375
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 404
container[4].j= 377
container[4].angle= 153
container[4].value= 255


container[5].bin= 3
container[5].i= 405
container[5].j= 375
container[5].angle= 18
container[5].value= 255


container[6].bin= 3
container[6].i= 406
container[6].j= 373
container[6].angle= 18
container[6].value= 255


container[7].bin= 14
container[7].i= 406
container[7].j= 374
container[7].angle= 71
container[7].value= 255


container[8].bin= 0
container[8].i= 407
container[8].j= 373
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 407
container[9].j= 377
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 408
container[10].j= 373
container[10].angle= 26
container[10].value= 255


container[11].bin= 36
container[11].i= 408
container[11].j= 377
container[11].angle= 180
container[11].value= 255


container[12].bin= 5
container[12].i= 409
container[12].j= 373
container[12].angle= 26
container[12].value= 255


container[13].bin= 36
container[13].i= 409
container[13].j= 377
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 410
container[14].j= 372
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 410
container[15].j= 377
container[15].angle= 180
container[15].value= 255


container[16].bin= 66
container[16].i= 411
container[16].j= 373
container[16].angle= 333
container[16].value= 255


container[17].bin= 27
container[17].i= 411
container[17].j= 378
container[17].angle= 135
container[17].value= 255


container[18].bin= 66
container[18].i= 412
container[18].j= 373
container[18].angle= 333
container[18].value= 255


container[19].bin= 27
container[19].i= 412
container[19].j= 379
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 413
container[20].j= 373
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 413
container[21].j= 379
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 414
container[22].j= 373
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 414
container[23].j= 379
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 415
container[24].j= 373
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 415
container[25].j= 379
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 416
container[26].j= 373
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 416
container[27].j= 379
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 417
container[28].j= 373
container[28].angle= 0
container[28].value= 255


container[29].bin= 27
container[29].i= 417
container[29].j= 380
container[29].angle= 135
container[29].value= 255


container[30].bin= 18
container[30].i= 417
container[30].j= 381
container[30].angle= 90
container[30].value= 255


container[31].bin= 0
container[31].i= 418
container[31].j= 373
container[31].angle= 0
container[31].value= 255


container[32].bin= 27
container[32].i= 418
container[32].j= 382
container[32].angle= 135
container[32].value= 255


container[33].bin= 0
container[33].i= 419
container[33].j= 373
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 419
container[34].j= 382
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 420
container[35].j= 374
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 420
container[36].j= 383
container[36].angle= 135
container[36].value= 255


container[37].bin= 18
container[37].i= 420
container[37].j= 384
container[37].angle= 90
container[37].value= 255


container[38].bin= 63
container[38].i= 421
container[38].j= 375
container[38].angle= 315
container[38].value= 255


container[39].bin= 27
container[39].i= 421
container[39].j= 385
container[39].angle= 135
container[39].value= 255


container[40].bin= 0
container[40].i= 422
container[40].j= 375
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 422
container[41].j= 385
container[41].angle= 180
container[41].value= 255


container[42].bin= 63
container[42].i= 423
container[42].j= 376
container[42].angle= 315
container[42].value= 255


container[43].bin= 54
container[43].i= 423
container[43].j= 377
container[43].angle= 270
container[43].value= 255


container[44].bin= 54
container[44].i= 423
container[44].j= 378
container[44].angle= 270
container[44].value= 255


container[45].bin= 54
container[45].i= 423
container[45].j= 379
container[45].angle= 270
container[45].value= 255


container[46].bin= 27
container[46].i= 423
container[46].j= 386
container[46].angle= 135
container[46].value= 255


container[47].bin= 63
container[47].i= 424
container[47].j= 380
container[47].angle= 315
container[47].value= 255


container[48].bin= 27
container[48].i= 424
container[48].j= 387
container[48].angle= 135
container[48].value= 255


container[49].bin= 0
container[49].i= 425
container[49].j= 380
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 425
container[50].j= 387
container[50].angle= 180
container[50].value= 255


container[51].bin= 63
container[51].i= 426
container[51].j= 381
container[51].angle= 315
container[51].value= 255


container[52].bin= 54
container[52].i= 426
container[52].j= 382
container[52].angle= 270
container[52].value= 255


container[53].bin= 54
container[53].i= 426
container[53].j= 383
container[53].angle= 270
container[53].value= 255


container[54].bin= 54
container[54].i= 426
container[54].j= 384
container[54].angle= 270
container[54].value= 255


container[55].bin= 36
container[55].i= 426
container[55].j= 387
container[55].angle= 180
container[55].value= 255


container[56].bin= 59
container[56].i= 427
container[56].j= 385
container[56].angle= 296
container[56].value= 255


container[57].bin= 59
container[57].i= 427
container[57].j= 386
container[57].angle= 296
container[57].value= 255


container[58].bin= 44
container[58].i= 427
container[58].j= 387
container[58].angle= 224
container[58].value= 255


