container[0].bin= 8
container[0].i= 94
container[0].j= 119
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 94
container[1].j= 120
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 95
container[2].j= 119
container[2].angle= 26
container[2].value= 255


container[3].bin= 30
container[3].i= 95
container[3].j= 121
container[3].angle= 153
container[3].value= 255


container[4].bin= 0
container[4].i= 96
container[4].j= 118
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 96
container[5].j= 121
container[5].angle= 135
container[5].value= 255


container[6].bin= 27
container[6].i= 96
container[6].j= 122
container[6].angle= 135
container[6].value= 255


container[7].bin= 8
container[7].i= 96
container[7].j= 133
container[7].angle= 44
container[7].value= 255


container[8].bin= 23
container[8].i= 96
container[8].j= 134
container[8].angle= 116
container[8].value= 255


container[9].bin= 27
container[9].i= 96
container[9].j= 135
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 97
container[10].j= 118
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 97
container[11].j= 122
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 97
container[12].j= 132
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 97
container[13].j= 135
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 98
container[14].j= 118
container[14].angle= 0
container[14].value= 255


container[15].bin= 30
container[15].i= 98
container[15].j= 123
container[15].angle= 153
container[15].value= 255


container[16].bin= 5
container[16].i= 98
container[16].j= 132
container[16].angle= 26
container[16].value= 255


container[17].bin= 30
container[17].i= 98
container[17].j= 136
container[17].angle= 153
container[17].value= 255


container[18].bin= 0
container[18].i= 99
container[18].j= 118
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 99
container[19].j= 123
container[19].angle= 153
container[19].value= 255


container[20].bin= 5
container[20].i= 99
container[20].j= 132
container[20].angle= 26
container[20].value= 255


container[21].bin= 30
container[21].i= 99
container[21].j= 136
container[21].angle= 153
container[21].value= 255


container[22].bin= 66
container[22].i= 100
container[22].j= 119
container[22].angle= 333
container[22].value= 255


container[23].bin= 30
container[23].i= 100
container[23].j= 124
container[23].angle= 153
container[23].value= 255


container[24].bin= 0
container[24].i= 100
container[24].j= 131
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 100
container[25].j= 136
container[25].angle= 180
container[25].value= 255


container[26].bin= 66
container[26].i= 101
container[26].j= 119
container[26].angle= 333
container[26].value= 255


container[27].bin= 30
container[27].i= 101
container[27].j= 124
container[27].angle= 153
container[27].value= 255


container[28].bin= 0
container[28].i= 101
container[28].j= 131
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 101
container[29].j= 136
container[29].angle= 180
container[29].value= 255


container[30].bin= 66
container[30].i= 102
container[30].j= 120
container[30].angle= 333
container[30].value= 255


container[31].bin= 30
container[31].i= 102
container[31].j= 125
container[31].angle= 153
container[31].value= 255


container[32].bin= 0
container[32].i= 102
container[32].j= 131
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 102
container[33].j= 136
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 103
container[34].j= 120
container[34].angle= 315
container[34].value= 255


container[35].bin= 63
container[35].i= 103
container[35].j= 121
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 103
container[36].j= 125
container[36].angle= 135
container[36].value= 255


container[37].bin= 27
container[37].i= 103
container[37].j= 126
container[37].angle= 135
container[37].value= 255


container[38].bin= 0
container[38].i= 103
container[38].j= 131
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 103
container[39].j= 136
container[39].angle= 180
container[39].value= 255


container[40].bin= 63
container[40].i= 104
container[40].j= 121
container[40].angle= 315
container[40].value= 255


container[41].bin= 63
container[41].i= 104
container[41].j= 122
container[41].angle= 315
container[41].value= 255


container[42].bin= 27
container[42].i= 104
container[42].j= 126
container[42].angle= 135
container[42].value= 255


container[43].bin= 27
container[43].i= 104
container[43].j= 127
container[43].angle= 135
container[43].value= 255


container[44].bin= 0
container[44].i= 104
container[44].j= 131
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 104
container[45].j= 136
container[45].angle= 180
container[45].value= 255


container[46].bin= 66
container[46].i= 105
container[46].j= 122
container[46].angle= 333
container[46].value= 255


container[47].bin= 30
container[47].i= 105
container[47].j= 127
container[47].angle= 153
container[47].value= 255


container[48].bin= 5
container[48].i= 105
container[48].j= 131
container[48].angle= 26
container[48].value= 255


container[49].bin= 36
container[49].i= 105
container[49].j= 136
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 106
container[50].j= 122
container[50].angle= 0
container[50].value= 255


container[51].bin= 27
container[51].i= 106
container[51].j= 128
container[51].angle= 135
container[51].value= 255


container[52].bin= 18
container[52].i= 106
container[52].j= 129
container[52].angle= 90
container[52].value= 255


container[53].bin= 12
container[53].i= 106
container[53].j= 130
container[53].angle= 63
container[53].value= 255


container[54].bin= 8
container[54].i= 106
container[54].j= 131
container[54].angle= 44
container[54].value= 255


container[55].bin= 30
container[55].i= 106
container[55].j= 137
container[55].angle= 153
container[55].value= 255


container[56].bin= 66
container[56].i= 107
container[56].j= 123
container[56].angle= 333
container[56].value= 255


container[57].bin= 30
container[57].i= 107
container[57].j= 137
container[57].angle= 153
container[57].value= 255


container[58].bin= 66
container[58].i= 108
container[58].j= 123
container[58].angle= 333
container[58].value= 255


container[59].bin= 30
container[59].i= 108
container[59].j= 138
container[59].angle= 153
container[59].value= 255


container[60].bin= 0
container[60].i= 109
container[60].j= 123
container[60].angle= 0
container[60].value= 255


container[61].bin= 30
container[61].i= 109
container[61].j= 138
container[61].angle= 153
container[61].value= 255


container[62].bin= 66
container[62].i= 110
container[62].j= 124
container[62].angle= 333
container[62].value= 255


container[63].bin= 30
container[63].i= 110
container[63].j= 139
container[63].angle= 153
container[63].value= 255


container[64].bin= 66
container[64].i= 111
container[64].j= 124
container[64].angle= 333
container[64].value= 255


container[65].bin= 27
container[65].i= 111
container[65].j= 139
container[65].angle= 135
container[65].value= 255


container[66].bin= 27
container[66].i= 111
container[66].j= 140
container[66].angle= 135
container[66].value= 255


container[67].bin= 66
container[67].i= 112
container[67].j= 125
container[67].angle= 333
container[67].value= 255


container[68].bin= 30
container[68].i= 112
container[68].j= 140
container[68].angle= 153
container[68].value= 255


container[69].bin= 66
container[69].i= 113
container[69].j= 125
container[69].angle= 333
container[69].value= 255


container[70].bin= 30
container[70].i= 113
container[70].j= 141
container[70].angle= 153
container[70].value= 255


container[71].bin= 0
container[71].i= 114
container[71].j= 125
container[71].angle= 0
container[71].value= 255


container[72].bin= 30
container[72].i= 114
container[72].j= 141
container[72].angle= 153
container[72].value= 255


container[73].bin= 0
container[73].i= 115
container[73].j= 125
container[73].angle= 0
container[73].value= 255


container[74].bin= 54
container[74].i= 115
container[74].j= 131
container[74].angle= 270
container[74].value= 255


container[75].bin= 54
container[75].i= 115
container[75].j= 132
container[75].angle= 270
container[75].value= 255


container[76].bin= 36
container[76].i= 115
container[76].j= 141
container[76].angle= 180
container[76].value= 255


container[77].bin= 66
container[77].i= 116
container[77].j= 126
container[77].angle= 333
container[77].value= 255


container[78].bin= 44
container[78].i= 116
container[78].j= 129
container[78].angle= 224
container[78].value= 255


container[79].bin= 48
container[79].i= 116
container[79].j= 130
container[79].angle= 243
container[79].value= 255


container[80].bin= 59
container[80].i= 116
container[80].j= 133
container[80].angle= 296
container[80].value= 255


container[81].bin= 59
container[81].i= 116
container[81].j= 134
container[81].angle= 296
container[81].value= 255


container[82].bin= 30
container[82].i= 116
container[82].j= 142
container[82].angle= 153
container[82].value= 255


container[83].bin= 66
container[83].i= 117
container[83].j= 126
container[83].angle= 333
container[83].value= 255


container[84].bin= 41
container[84].i= 117
container[84].j= 129
container[84].angle= 206
container[84].value= 255


container[85].bin= 59
container[85].i= 117
container[85].j= 135
container[85].angle= 296
container[85].value= 255


container[86].bin= 63
container[86].i= 117
container[86].j= 136
container[86].angle= 315
container[86].value= 255


container[87].bin= 30
container[87].i= 117
container[87].j= 142
container[87].angle= 153
container[87].value= 255


container[88].bin= 0
container[88].i= 118
container[88].j= 126
container[88].angle= 0
container[88].value= 255


container[89].bin= 30
container[89].i= 118
container[89].j= 129
container[89].angle= 153
container[89].value= 255


container[90].bin= 63
container[90].i= 118
container[90].j= 136
container[90].angle= 315
container[90].value= 255


container[91].bin= 59
container[91].i= 118
container[91].j= 137
container[91].angle= 296
container[91].value= 255


container[92].bin= 41
container[92].i= 118
container[92].j= 142
container[92].angle= 206
container[92].value= 255


container[93].bin= 0
container[93].i= 119
container[93].j= 126
container[93].angle= 0
container[93].value= 255


container[94].bin= 30
container[94].i= 119
container[94].j= 129
container[94].angle= 153
container[94].value= 255


container[95].bin= 59
container[95].i= 119
container[95].j= 138
container[95].angle= 296
container[95].value= 255


container[96].bin= 59
container[96].i= 119
container[96].j= 139
container[96].angle= 296
container[96].value= 255


container[97].bin= 54
container[97].i= 119
container[97].j= 140
container[97].angle= 270
container[97].value= 255


container[98].bin= 48
container[98].i= 119
container[98].j= 141
container[98].angle= 243
container[98].value= 255


container[99].bin= 44
container[99].i= 119
container[99].j= 142
container[99].angle= 224
container[99].value= 255


container[100].bin= 0
container[100].i= 120
container[100].j= 126
container[100].angle= 0
container[100].value= 255


container[101].bin= 36
container[101].i= 120
container[101].j= 129
container[101].angle= 180
container[101].value= 255


container[102].bin= 66
container[102].i= 121
container[102].j= 127
container[102].angle= 333
container[102].value= 255


container[103].bin= 36
container[103].i= 121
container[103].j= 129
container[103].angle= 180
container[103].value= 255


container[104].bin= 63
container[104].i= 122
container[104].j= 127
container[104].angle= 315
container[104].value= 255


container[105].bin= 59
container[105].i= 122
container[105].j= 128
container[105].angle= 296
container[105].value= 255


container[106].bin= 44
container[106].i= 122
container[106].j= 129
container[106].angle= 224
container[106].value= 255


