container[0].bin= 8
container[0].i= 231
container[0].j= 371
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 231
container[1].j= 372
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 231
container[2].j= 373
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 232
container[3].j= 371
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 232
container[4].j= 373
container[4].angle= 135
container[4].value= 255


container[5].bin= 23
container[5].i= 232
container[5].j= 374
container[5].angle= 116
container[5].value= 255


container[6].bin= 66
container[6].i= 233
container[6].j= 371
container[6].angle= 333
container[6].value= 255


container[7].bin= 23
container[7].i= 233
container[7].j= 375
container[7].angle= 116
container[7].value= 255


container[8].bin= 27
container[8].i= 233
container[8].j= 376
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 234
container[9].j= 371
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 234
container[10].j= 376
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 235
container[11].j= 372
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 235
container[12].j= 377
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 236
container[13].j= 372
container[13].angle= 333
container[13].value= 255


container[14].bin= 30
container[14].i= 236
container[14].j= 377
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 237
container[15].j= 372
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 237
container[16].j= 377
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 238
container[17].j= 373
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 238
container[18].j= 377
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 239
container[19].j= 373
container[19].angle= 315
container[19].value= 255


container[20].bin= 59
container[20].i= 239
container[20].j= 374
container[20].angle= 296
container[20].value= 255


container[21].bin= 54
container[21].i= 239
container[21].j= 375
container[21].angle= 270
container[21].value= 255


container[22].bin= 59
container[22].i= 240
container[22].j= 376
container[22].angle= 296
container[22].value= 255


