container[0].bin= 18
container[0].i= 51
container[0].j= 127
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 52
container[1].j= 126
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 52
container[2].j= 128
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 53
container[3].j= 126
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 53
container[4].j= 128
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 54
container[5].j= 126
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 54
container[6].j= 128
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 55
container[7].j= 126
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 55
container[8].j= 128
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 56
container[9].j= 126
container[9].angle= 26
container[9].value= 255


container[10].bin= 36
container[10].i= 56
container[10].j= 128
container[10].angle= 180
container[10].value= 255


container[11].bin= 18
container[11].i= 57
container[11].j= 115
container[11].angle= 90
container[11].value= 255


container[12].bin= 18
container[12].i= 57
container[12].j= 116
container[12].angle= 90
container[12].value= 255


container[13].bin= 18
container[13].i= 57
container[13].j= 117
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 57
container[14].j= 118
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 57
container[15].j= 119
container[15].angle= 90
container[15].value= 255


container[16].bin= 21
container[16].i= 57
container[16].j= 120
container[16].angle= 108
container[16].value= 255


container[17].bin= 5
container[17].i= 57
container[17].j= 126
container[17].angle= 26
container[17].value= 255


container[18].bin= 8
container[18].i= 58
container[18].j= 114
container[18].angle= 44
container[18].value= 255


container[19].bin= 14
container[19].i= 58
container[19].j= 124
container[19].angle= 71
container[19].value= 255


container[20].bin= 8
container[20].i= 58
container[20].j= 125
container[20].angle= 44
container[20].value= 255


container[21].bin= 66
container[21].i= 59
container[21].j= 114
container[21].angle= 333
container[21].value= 255


container[22].bin= 44
container[22].i= 59
container[22].j= 118
container[22].angle= 224
container[22].value= 255


container[23].bin= 57
container[23].i= 59
container[23].j= 119
container[23].angle= 288
container[23].value= 255


container[24].bin= 36
container[24].i= 59
container[24].j= 121
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 59
container[25].j= 123
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 59
container[26].j= 127
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 60
container[27].j= 114
container[27].angle= 315
container[27].value= 255


container[28].bin= 63
container[28].i= 60
container[28].j= 115
container[28].angle= 315
container[28].value= 255


container[29].bin= 41
container[29].i= 60
container[29].j= 118
container[29].angle= 206
container[29].value= 255


container[30].bin= 14
container[30].i= 60
container[30].j= 123
container[30].angle= 71
container[30].value= 255


container[31].bin= 41
container[31].i= 60
container[31].j= 127
container[31].angle= 206
container[31].value= 255


container[32].bin= 66
container[32].i= 61
container[32].j= 115
container[32].angle= 333
container[32].value= 255


container[33].bin= 8
container[33].i= 61
container[33].j= 122
container[33].angle= 44
container[33].value= 255


container[34].bin= 18
container[34].i= 61
container[34].j= 124
container[34].angle= 90
container[34].value= 255


container[35].bin= 14
container[35].i= 61
container[35].j= 125
container[35].angle= 71
container[35].value= 255


container[36].bin= 36
container[36].i= 61
container[36].j= 127
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 62
container[37].j= 115
container[37].angle= 0
container[37].value= 255


container[38].bin= 0
container[38].i= 62
container[38].j= 121
container[38].angle= 0
container[38].value= 255


container[39].bin= 32
container[39].i= 62
container[39].j= 127
container[39].angle= 161
container[39].value= 255


container[40].bin= 0
container[40].i= 63
container[40].j= 115
container[40].angle= 0
container[40].value= 255


container[41].bin= 27
container[41].i= 63
container[41].j= 118
container[41].angle= 135
container[41].value= 255


container[42].bin= 18
container[42].i= 63
container[42].j= 119
container[42].angle= 90
container[42].value= 255


container[43].bin= 63
container[43].i= 63
container[43].j= 122
container[43].angle= 315
container[43].value= 255


container[44].bin= 39
container[44].i= 63
container[44].j= 125
container[44].angle= 198
container[44].value= 255


container[45].bin= 50
container[45].i= 63
container[45].j= 126
container[45].angle= 251
container[45].value= 255


container[46].bin= 0
container[46].i= 64
container[46].j= 115
container[46].angle= 0
container[46].value= 255


container[47].bin= 27
container[47].i= 64
container[47].j= 120
container[47].angle= 135
container[47].value= 255


container[48].bin= 63
container[48].i= 64
container[48].j= 123
container[48].angle= 315
container[48].value= 255


container[49].bin= 0
container[49].i= 65
container[49].j= 115
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 65
container[50].j= 120
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 65
container[51].j= 123
container[51].angle= 0
container[51].value= 255


container[52].bin= 0
container[52].i= 66
container[52].j= 115
container[52].angle= 0
container[52].value= 255


container[53].bin= 27
container[53].i= 66
container[53].j= 121
container[53].angle= 135
container[53].value= 255


container[54].bin= 18
container[54].i= 66
container[54].j= 122
container[54].angle= 90
container[54].value= 255


container[55].bin= 8
container[55].i= 66
container[55].j= 123
container[55].angle= 44
container[55].value= 255


container[56].bin= 41
container[56].i= 66
container[56].j= 125
container[56].angle= 206
container[56].value= 255


container[57].bin= 5
container[57].i= 67
container[57].j= 115
container[57].angle= 26
container[57].value= 255


container[58].bin= 44
container[58].i= 67
container[58].j= 117
container[58].angle= 224
container[58].value= 255


container[59].bin= 63
container[59].i= 67
container[59].j= 118
container[59].angle= 315
container[59].value= 255


container[60].bin= 44
container[60].i= 67
container[60].j= 125
container[60].angle= 224
container[60].value= 255


container[61].bin= 0
container[61].i= 68
container[61].j= 115
container[61].angle= 0
container[61].value= 255


container[62].bin= 36
container[62].i= 68
container[62].j= 117
container[62].angle= 180
container[62].value= 255


container[63].bin= 36
container[63].i= 68
container[63].j= 124
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 69
container[64].j= 115
container[64].angle= 315
container[64].value= 255


container[65].bin= 50
container[65].i= 69
container[65].j= 116
container[65].angle= 251
container[65].value= 255


container[66].bin= 30
container[66].i= 69
container[66].j= 124
container[66].angle= 153
container[66].value= 255


container[67].bin= 0
container[67].i= 70
container[67].j= 118
container[67].angle= 0
container[67].value= 255


container[68].bin= 30
container[68].i= 70
container[68].j= 125
container[68].angle= 153
container[68].value= 255


container[69].bin= 0
container[69].i= 71
container[69].j= 118
container[69].angle= 0
container[69].value= 255


container[70].bin= 30
container[70].i= 71
container[70].j= 125
container[70].angle= 153
container[70].value= 255


container[71].bin= 63
container[71].i= 72
container[71].j= 119
container[71].angle= 315
container[71].value= 255


container[72].bin= 36
container[72].i= 72
container[72].j= 125
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 73
container[73].j= 120
container[73].angle= 315
container[73].value= 255


container[74].bin= 36
container[74].i= 73
container[74].j= 125
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 74
container[75].j= 120
container[75].angle= 0
container[75].value= 255


container[76].bin= 36
container[76].i= 74
container[76].j= 125
container[76].angle= 180
container[76].value= 255


container[77].bin= 63
container[77].i= 75
container[77].j= 121
container[77].angle= 315
container[77].value= 255


container[78].bin= 54
container[78].i= 75
container[78].j= 122
container[78].angle= 270
container[78].value= 255


container[79].bin= 36
container[79].i= 75
container[79].j= 125
container[79].angle= 180
container[79].value= 255


container[80].bin= 63
container[80].i= 76
container[80].j= 123
container[80].angle= 315
container[80].value= 255


container[81].bin= 0
container[81].i= 77
container[81].j= 123
container[81].angle= 0
container[81].value= 255


container[82].bin= 0
container[82].i= 78
container[82].j= 123
container[82].angle= 0
container[82].value= 255


container[83].bin= 0
container[83].i= 79
container[83].j= 123
container[83].angle= 0
container[83].value= 255


container[84].bin= 0
container[84].i= 80
container[84].j= 123
container[84].angle= 0
container[84].value= 255


container[85].bin= 63
container[85].i= 81
container[85].j= 124
container[85].angle= 315
container[85].value= 255


container[86].bin= 27
container[86].i= 82
container[86].j= 127
container[86].angle= 135
container[86].value= 255


container[87].bin= 0
container[87].i= 83
container[87].j= 125
container[87].angle= 0
container[87].value= 255


container[88].bin= 66
container[88].i= 84
container[88].j= 126
container[88].angle= 333
container[88].value= 255


container[89].bin= 66
container[89].i= 85
container[89].j= 126
container[89].angle= 333
container[89].value= 255


container[90].bin= 36
container[90].i= 85
container[90].j= 128
container[90].angle= 180
container[90].value= 255


container[91].bin= 0
container[91].i= 86
container[91].j= 126
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 86
container[92].j= 128
container[92].angle= 180
container[92].value= 255


container[93].bin= 68
container[93].i= 87
container[93].j= 126
container[93].angle= 341
container[93].value= 255


container[94].bin= 54
container[94].i= 87
container[94].j= 127
container[94].angle= 270
container[94].value= 255


container[95].bin= 39
container[95].i= 87
container[95].j= 128
container[95].angle= 198
container[95].value= 255


