container[0].bin= 18
container[0].i= 364
container[0].j= 543
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 365
container[1].j= 542
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 365
container[2].j= 544
container[2].angle= 161
container[2].value= 255


container[3].bin= 8
container[3].i= 366
container[3].j= 542
container[3].angle= 44
container[3].value= 255


container[4].bin= 36
container[4].i= 366
container[4].j= 544
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 367
container[5].j= 541
container[5].angle= 44
container[5].value= 255


container[6].bin= 0
container[6].i= 368
container[6].j= 540
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 368
container[7].j= 543
container[7].angle= 180
container[7].value= 255


container[8].bin= 63
container[8].i= 369
container[8].j= 541
container[8].angle= 315
container[8].value= 255


container[9].bin= 63
container[9].i= 370
container[9].j= 542
container[9].angle= 315
container[9].value= 255


container[10].bin= 36
container[10].i= 370
container[10].j= 544
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 371
container[11].j= 542
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 371
container[12].j= 544
container[12].angle= 180
container[12].value= 255


container[13].bin= 68
container[13].i= 372
container[13].j= 542
container[13].angle= 341
container[13].value= 255


container[14].bin= 54
container[14].i= 372
container[14].j= 543
container[14].angle= 270
container[14].value= 255


container[15].bin= 39
container[15].i= 372
container[15].j= 544
container[15].angle= 198
container[15].value= 255


