container[0].bin= 8
container[0].i= 264
container[0].j= 349
container[0].angle= 44
container[0].value= 255


container[1].bin= 66
container[1].i= 266
container[1].j= 349
container[1].angle= 333
container[1].value= 255


container[2].bin= 36
container[2].i= 266
container[2].j= 351
container[2].angle= 180
container[2].value= 255


container[3].bin= 0
container[3].i= 267
container[3].j= 349
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 267
container[4].j= 351
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 268
container[5].j= 349
container[5].angle= 341
container[5].value= 255


container[6].bin= 54
container[6].i= 268
container[6].j= 350
container[6].angle= 270
container[6].value= 255


container[7].bin= 39
container[7].i= 268
container[7].j= 351
container[7].angle= 198
container[7].value= 255


