container[0].bin= 8
container[0].i= 61
container[0].j= 203
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 61
container[1].j= 204
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 62
container[2].j= 202
container[2].angle= 0
container[2].value= 255


container[3].bin= 8
container[3].i= 63
container[3].j= 202
container[3].angle= 44
container[3].value= 255


container[4].bin= 30
container[4].i= 63
container[4].j= 205
container[4].angle= 153
container[4].value= 255


container[5].bin= 8
container[5].i= 64
container[5].j= 201
container[5].angle= 44
container[5].value= 255


container[6].bin= 30
container[6].i= 64
container[6].j= 205
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 65
container[7].j= 200
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 65
container[8].j= 205
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 66
container[9].j= 200
container[9].angle= 44
container[9].value= 255


container[10].bin= 36
container[10].i= 66
container[10].j= 205
container[10].angle= 180
container[10].value= 255


container[11].bin= 8
container[11].i= 67
container[11].j= 199
container[11].angle= 44
container[11].value= 255


container[12].bin= 36
container[12].i= 67
container[12].j= 205
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 68
container[13].j= 198
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 68
container[14].j= 205
container[14].angle= 180
container[14].value= 255


container[15].bin= 5
container[15].i= 69
container[15].j= 198
container[15].angle= 26
container[15].value= 255


container[16].bin= 54
container[16].i= 69
container[16].j= 201
container[16].angle= 270
container[16].value= 255


container[17].bin= 41
container[17].i= 69
container[17].j= 205
container[17].angle= 206
container[17].value= 255


container[18].bin= 5
container[18].i= 70
container[18].j= 198
container[18].angle= 26
container[18].value= 255


container[19].bin= 44
container[19].i= 70
container[19].j= 200
container[19].angle= 224
container[19].value= 255


container[20].bin= 63
container[20].i= 70
container[20].j= 202
container[20].angle= 315
container[20].value= 255


container[21].bin= 41
container[21].i= 70
container[21].j= 205
container[21].angle= 206
container[21].value= 255


container[22].bin= 0
container[22].i= 71
container[22].j= 197
container[22].angle= 0
container[22].value= 255


container[23].bin= 0
container[23].i= 71
container[23].j= 202
container[23].angle= 0
container[23].value= 255


container[24].bin= 0
container[24].i= 72
container[24].j= 197
container[24].angle= 0
container[24].value= 255


container[25].bin= 63
container[25].i= 72
container[25].j= 203
container[25].angle= 315
container[25].value= 255


container[26].bin= 44
container[26].i= 72
container[26].j= 204
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 73
container[27].j= 197
container[27].angle= 0
container[27].value= 255


container[28].bin= 0
container[28].i= 74
container[28].j= 197
container[28].angle= 0
container[28].value= 255


container[29].bin= 63
container[29].i= 75
container[29].j= 198
container[29].angle= 315
container[29].value= 255


container[30].bin= 44
container[30].i= 75
container[30].j= 199
container[30].angle= 224
container[30].value= 255


