container[0].bin= 18
container[0].i= 715
container[0].j= 215
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 715
container[1].j= 216
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 715
container[2].j= 217
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 716
container[3].j= 214
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 716
container[4].j= 218
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 717
container[5].j= 213
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 717
container[6].j= 218
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 718
container[7].j= 213
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 718
container[8].j= 219
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 719
container[9].j= 213
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 719
container[10].j= 220
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 720
container[11].j= 213
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 720
container[12].j= 220
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 721
container[13].j= 214
container[13].angle= 333
container[13].value= 255


container[14].bin= 27
container[14].i= 721
container[14].j= 221
container[14].angle= 135
container[14].value= 255


container[15].bin= 18
container[15].i= 721
container[15].j= 222
container[15].angle= 90
container[15].value= 255


container[16].bin= 66
container[16].i= 722
container[16].j= 214
container[16].angle= 333
container[16].value= 255


container[17].bin= 27
container[17].i= 722
container[17].j= 223
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 723
container[18].j= 214
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 723
container[19].j= 223
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 724
container[20].j= 215
container[20].angle= 315
container[20].value= 255


container[21].bin= 27
container[21].i= 724
container[21].j= 224
container[21].angle= 135
container[21].value= 255


container[22].bin= 18
container[22].i= 724
container[22].j= 225
container[22].angle= 90
container[22].value= 255


container[23].bin= 63
container[23].i= 725
container[23].j= 216
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 725
container[24].j= 226
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 726
container[25].j= 216
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 726
container[26].j= 226
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 727
container[27].j= 217
container[27].angle= 315
container[27].value= 255


container[28].bin= 27
container[28].i= 727
container[28].j= 227
container[28].angle= 135
container[28].value= 255


container[29].bin= 63
container[29].i= 728
container[29].j= 218
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 728
container[30].j= 228
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 729
container[31].j= 218
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 729
container[32].j= 228
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 730
container[33].j= 219
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 730
container[34].j= 229
container[34].angle= 135
container[34].value= 255


container[35].bin= 66
container[35].i= 731
container[35].j= 219
container[35].angle= 333
container[35].value= 255


container[36].bin= 27
container[36].i= 731
container[36].j= 230
container[36].angle= 135
container[36].value= 255


container[37].bin= 0
container[37].i= 732
container[37].j= 219
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 732
container[38].j= 230
container[38].angle= 180
container[38].value= 255


container[39].bin= 63
container[39].i= 733
container[39].j= 220
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 733
container[40].j= 231
container[40].angle= 135
container[40].value= 255


container[41].bin= 18
container[41].i= 733
container[41].j= 232
container[41].angle= 90
container[41].value= 255


container[42].bin= 63
container[42].i= 734
container[42].j= 221
container[42].angle= 315
container[42].value= 255


container[43].bin= 27
container[43].i= 734
container[43].j= 233
container[43].angle= 135
container[43].value= 255


container[44].bin= 66
container[44].i= 735
container[44].j= 222
container[44].angle= 333
container[44].value= 255


container[45].bin= 36
container[45].i= 735
container[45].j= 233
container[45].angle= 180
container[45].value= 255


container[46].bin= 63
container[46].i= 736
container[46].j= 222
container[46].angle= 315
container[46].value= 255


container[47].bin= 59
container[47].i= 736
container[47].j= 223
container[47].angle= 296
container[47].value= 255


container[48].bin= 36
container[48].i= 736
container[48].j= 233
container[48].angle= 180
container[48].value= 255


container[49].bin= 63
container[49].i= 737
container[49].j= 224
container[49].angle= 315
container[49].value= 255


container[50].bin= 36
container[50].i= 737
container[50].j= 233
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 738
container[51].j= 224
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 738
container[52].j= 233
container[52].angle= 180
container[52].value= 255


container[53].bin= 63
container[53].i= 739
container[53].j= 225
container[53].angle= 315
container[53].value= 255


container[54].bin= 30
container[54].i= 739
container[54].j= 234
container[54].angle= 153
container[54].value= 255


container[55].bin= 63
container[55].i= 740
container[55].j= 226
container[55].angle= 315
container[55].value= 255


container[56].bin= 30
container[56].i= 740
container[56].j= 234
container[56].angle= 153
container[56].value= 255


container[57].bin= 0
container[57].i= 741
container[57].j= 226
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 741
container[58].j= 234
container[58].angle= 180
container[58].value= 255


container[59].bin= 63
container[59].i= 742
container[59].j= 227
container[59].angle= 315
container[59].value= 255


container[60].bin= 54
container[60].i= 742
container[60].j= 228
container[60].angle= 270
container[60].value= 255


container[61].bin= 36
container[61].i= 742
container[61].j= 234
container[61].angle= 180
container[61].value= 255


container[62].bin= 63
container[62].i= 743
container[62].j= 229
container[62].angle= 315
container[62].value= 255


container[63].bin= 36
container[63].i= 743
container[63].j= 234
container[63].angle= 180
container[63].value= 255


container[64].bin= 0
container[64].i= 744
container[64].j= 229
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 744
container[65].j= 234
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 745
container[66].j= 229
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 745
container[67].j= 234
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 746
container[68].j= 230
container[68].angle= 315
container[68].value= 255


container[69].bin= 36
container[69].i= 746
container[69].j= 234
container[69].angle= 180
container[69].value= 255


container[70].bin= 63
container[70].i= 747
container[70].j= 231
container[70].angle= 315
container[70].value= 255


container[71].bin= 36
container[71].i= 747
container[71].j= 234
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 748
container[72].j= 231
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 748
container[73].j= 234
container[73].angle= 180
container[73].value= 255


container[74].bin= 63
container[74].i= 749
container[74].j= 232
container[74].angle= 315
container[74].value= 255


container[75].bin= 54
container[75].i= 749
container[75].j= 233
container[75].angle= 270
container[75].value= 255


container[76].bin= 44
container[76].i= 749
container[76].j= 234
container[76].angle= 224
container[76].value= 255


