container[0].bin= 18
container[0].i= 417
container[0].j= 208
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 417
container[1].j= 209
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 417
container[2].j= 210
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 417
container[3].j= 211
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 417
container[4].j= 212
container[4].angle= 90
container[4].value= 255


container[5].bin= 8
container[5].i= 418
container[5].j= 207
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 418
container[6].j= 213
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 419
container[7].j= 206
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 419
container[8].j= 213
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 420
container[9].j= 206
container[9].angle= 0
container[9].value= 255


container[10].bin= 54
container[10].i= 420
container[10].j= 211
container[10].angle= 270
container[10].value= 255


container[11].bin= 54
container[11].i= 420
container[11].j= 212
container[11].angle= 270
container[11].value= 255


container[12].bin= 44
container[12].i= 420
container[12].j= 213
container[12].angle= 224
container[12].value= 255


container[13].bin= 0
container[13].i= 421
container[13].j= 206
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 421
container[14].j= 210
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 422
container[15].j= 206
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 422
container[16].j= 209
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 423
container[17].j= 207
container[17].angle= 315
container[17].value= 255


container[18].bin= 54
container[18].i= 423
container[18].j= 208
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 423
container[19].j= 209
container[19].angle= 224
container[19].value= 255


