container[0].bin= 8
container[0].i= 641
container[0].j= 126
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 641
container[1].j= 127
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 642
container[2].j= 125
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 643
container[3].j= 126
container[3].angle= 333
container[3].value= 255


container[4].bin= 66
container[4].i= 644
container[4].j= 126
container[4].angle= 333
container[4].value= 255


container[5].bin= 27
container[5].i= 644
container[5].j= 128
container[5].angle= 135
container[5].value= 255


container[6].bin= 12
container[6].i= 644
container[6].j= 129
container[6].angle= 63
container[6].value= 255


container[7].bin= 21
container[7].i= 644
container[7].j= 130
container[7].angle= 108
container[7].value= 255


container[8].bin= 68
container[8].i= 645
container[8].j= 126
container[8].angle= 341
container[8].value= 255


container[9].bin= 59
container[9].i= 646
container[9].j= 128
container[9].angle= 296
container[9].value= 255


container[10].bin= 59
container[10].i= 646
container[10].j= 129
container[10].angle= 296
container[10].value= 255


container[11].bin= 44
container[11].i= 646
container[11].j= 130
container[11].angle= 224
container[11].value= 255


