container[0].bin= 14
container[0].i= 414
container[0].j= 358
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 414
container[1].j= 359
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 415
container[2].j= 357
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 416
container[3].j= 357
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 416
container[4].j= 359
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 417
container[5].j= 357
container[5].angle= 341
container[5].value= 255


