container[0].bin= 8
container[0].i= 349
container[0].j= 214
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 349
container[1].j= 215
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 349
container[2].j= 216
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 350
container[3].j= 213
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 350
container[4].j= 216
container[4].angle= 153
container[4].value= 255


container[5].bin= 8
container[5].i= 351
container[5].j= 213
container[5].angle= 44
container[5].value= 255


container[6].bin= 41
container[6].i= 351
container[6].j= 216
container[6].angle= 206
container[6].value= 255


container[7].bin= 8
container[7].i= 352
container[7].j= 212
container[7].angle= 44
container[7].value= 255


container[8].bin= 41
container[8].i= 352
container[8].j= 216
container[8].angle= 206
container[8].value= 255


container[9].bin= 0
container[9].i= 353
container[9].j= 211
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 353
container[10].j= 215
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 354
container[11].j= 211
container[11].angle= 0
container[11].value= 255


container[12].bin= 44
container[12].i= 354
container[12].j= 215
container[12].angle= 224
container[12].value= 255


container[13].bin= 0
container[13].i= 355
container[13].j= 211
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 355
container[14].j= 214
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 356
container[15].j= 211
container[15].angle= 0
container[15].value= 255


container[16].bin= 63
container[16].i= 357
container[16].j= 212
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 357
container[17].j= 213
container[17].angle= 224
container[17].value= 255


