container[0].bin= 18
container[0].i= 465
container[0].j= 139
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 465
container[1].j= 140
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 466
container[2].j= 138
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 466
container[3].j= 141
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 467
container[4].j= 137
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 467
container[5].j= 141
container[5].angle= 180
container[5].value= 255


container[6].bin= 68
container[6].i= 468
container[6].j= 137
container[6].angle= 341
container[6].value= 255


container[7].bin= 57
container[7].i= 468
container[7].j= 139
container[7].angle= 288
container[7].value= 255


container[8].bin= 27
container[8].i= 468
container[8].j= 142
container[8].angle= 135
container[8].value= 255


container[9].bin= 68
container[9].i= 469
container[9].j= 139
container[9].angle= 341
container[9].value= 255


container[10].bin= 27
container[10].i= 469
container[10].j= 143
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 470
container[11].j= 139
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 470
container[12].j= 143
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 471
container[13].j= 140
container[13].angle= 315
container[13].value= 255


container[14].bin= 36
container[14].i= 471
container[14].j= 143
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 472
container[15].j= 141
container[15].angle= 315
container[15].value= 255


container[16].bin= 0
container[16].i= 473
container[16].j= 141
container[16].angle= 0
container[16].value= 255


container[17].bin= 63
container[17].i= 474
container[17].j= 142
container[17].angle= 315
container[17].value= 255


container[18].bin= 44
container[18].i= 474
container[18].j= 143
container[18].angle= 224
container[18].value= 255


