container[0].bin= 18
container[0].i= 447
container[0].j= 187
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 448
container[1].j= 186
container[1].angle= 0
container[1].value= 255


container[2].bin= 68
container[2].i= 449
container[2].j= 187
container[2].angle= 341
container[2].value= 255


container[3].bin= 32
container[3].i= 449
container[3].j= 189
container[3].angle= 161
container[3].value= 255


container[4].bin= 68
container[4].i= 450
container[4].j= 187
container[4].angle= 341
container[4].value= 255


container[5].bin= 32
container[5].i= 450
container[5].j= 189
container[5].angle= 161
container[5].value= 255


container[6].bin= 0
container[6].i= 451
container[6].j= 187
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 452
container[7].j= 187
container[7].angle= 0
container[7].value= 255


container[8].bin= 44
container[8].i= 452
container[8].j= 189
container[8].angle= 224
container[8].value= 255


