container[0].bin= 18
container[0].i= 342
container[0].j= 334
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 342
container[1].j= 335
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 343
container[2].j= 333
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 343
container[3].j= 336
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 344
container[4].j= 332
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 344
container[5].j= 336
container[5].angle= 180
container[5].value= 255


container[6].bin= 8
container[6].i= 345
container[6].j= 332
container[6].angle= 44
container[6].value= 255


container[7].bin= 36
container[7].i= 345
container[7].j= 336
container[7].angle= 180
container[7].value= 255


container[8].bin= 8
container[8].i= 346
container[8].j= 331
container[8].angle= 44
container[8].value= 255


container[9].bin= 36
container[9].i= 346
container[9].j= 336
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 347
container[10].j= 330
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 347
container[11].j= 336
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 348
container[12].j= 330
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 348
container[13].j= 336
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 349
container[14].j= 330
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 349
container[15].j= 336
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 350
container[16].j= 330
container[16].angle= 0
container[16].value= 255


container[17].bin= 30
container[17].i= 350
container[17].j= 337
container[17].angle= 153
container[17].value= 255


container[18].bin= 63
container[18].i= 351
container[18].j= 331
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 351
container[19].j= 332
container[19].angle= 270
container[19].value= 255


container[20].bin= 54
container[20].i= 351
container[20].j= 333
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 351
container[21].j= 334
container[21].angle= 270
container[21].value= 255


container[22].bin= 54
container[22].i= 351
container[22].j= 335
container[22].angle= 270
container[22].value= 255


