container[0].bin= 18
container[0].i= 839
container[0].j= 359
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 840
container[1].j= 358
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 840
container[2].j= 360
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 841
container[3].j= 357
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 841
container[4].j= 360
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 842
container[5].j= 357
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 842
container[6].j= 360
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 843
container[7].j= 357
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 843
container[8].j= 360
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 844
container[9].j= 357
container[9].angle= 26
container[9].value= 255


container[10].bin= 36
container[10].i= 844
container[10].j= 360
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 845
container[11].j= 357
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 845
container[12].j= 361
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 846
container[13].j= 357
container[13].angle= 333
container[13].value= 255


container[14].bin= 30
container[14].i= 846
container[14].j= 361
container[14].angle= 153
container[14].value= 255


container[15].bin= 66
container[15].i= 847
container[15].j= 358
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 847
container[16].j= 361
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 848
container[17].j= 358
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 848
container[18].j= 359
container[18].angle= 296
container[18].value= 255


container[19].bin= 54
container[19].i= 848
container[19].j= 360
container[19].angle= 270
container[19].value= 255


container[20].bin= 44
container[20].i= 848
container[20].j= 361
container[20].angle= 224
container[20].value= 255


