container[0].bin= 18
container[0].i= 279
container[0].j= 443
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 280
container[1].j= 442
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 280
container[2].j= 444
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 281
container[3].j= 442
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 281
container[4].j= 444
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 282
container[5].j= 442
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 282
container[6].j= 443
container[6].angle= 90
container[6].value= 255


container[7].bin= 27
container[7].i= 282
container[7].j= 444
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 282
container[8].j= 445
container[8].angle= 90
container[8].value= 255


container[9].bin= 5
container[9].i= 283
container[9].j= 442
container[9].angle= 26
container[9].value= 255


container[10].bin= 27
container[10].i= 283
container[10].j= 446
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 284
container[11].j= 441
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 284
container[12].j= 446
container[12].angle= 180
container[12].value= 255


container[13].bin= 8
container[13].i= 285
container[13].j= 441
container[13].angle= 44
container[13].value= 255


container[14].bin= 50
container[14].i= 285
container[14].j= 445
container[14].angle= 251
container[14].value= 255


container[15].bin= 44
container[15].i= 285
container[15].j= 446
container[15].angle= 224
container[15].value= 255


container[16].bin= 8
container[16].i= 286
container[16].j= 440
container[16].angle= 44
container[16].value= 255


container[17].bin= 39
container[17].i= 286
container[17].j= 445
container[17].angle= 198
container[17].value= 255


container[18].bin= 0
container[18].i= 287
container[18].j= 439
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 287
container[19].j= 445
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 288
container[20].j= 439
container[20].angle= 0
container[20].value= 255


container[21].bin= 54
container[21].i= 288
container[21].j= 443
container[21].angle= 270
container[21].value= 255


container[22].bin= 54
container[22].i= 288
container[22].j= 444
container[22].angle= 270
container[22].value= 255


container[23].bin= 44
container[23].i= 288
container[23].j= 445
container[23].angle= 224
container[23].value= 255


container[24].bin= 0
container[24].i= 289
container[24].j= 439
container[24].angle= 0
container[24].value= 255


container[25].bin= 44
container[25].i= 289
container[25].j= 442
container[25].angle= 224
container[25].value= 255


container[26].bin= 0
container[26].i= 290
container[26].j= 439
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 291
container[27].j= 439
container[27].angle= 0
container[27].value= 255


container[28].bin= 0
container[28].i= 292
container[28].j= 439
container[28].angle= 0
container[28].value= 255


container[29].bin= 0
container[29].i= 293
container[29].j= 439
container[29].angle= 0
container[29].value= 255


container[30].bin= 63
container[30].i= 294
container[30].j= 440
container[30].angle= 315
container[30].value= 255


container[31].bin= 44
container[31].i= 294
container[31].j= 441
container[31].angle= 224
container[31].value= 255


