container[0].bin= 18
container[0].i= 429
container[0].j= 319
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 429
container[1].j= 320
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 430
container[2].j= 318
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 430
container[3].j= 321
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 431
container[4].j= 317
container[4].angle= 0
container[4].value= 255


container[5].bin= 41
container[5].i= 431
container[5].j= 321
container[5].angle= 206
container[5].value= 255


container[6].bin= 63
container[6].i= 432
container[6].j= 318
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 432
container[7].j= 319
container[7].angle= 270
container[7].value= 255


container[8].bin= 48
container[8].i= 432
container[8].j= 320
container[8].angle= 243
container[8].value= 255


container[9].bin= 44
container[9].i= 432
container[9].j= 321
container[9].angle= 224
container[9].value= 255


