container[0].bin= 18
container[0].i= 492
container[0].j= 557
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 492
container[1].j= 558
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 492
container[2].j= 559
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 492
container[3].j= 560
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 492
container[4].j= 561
container[4].angle= 90
container[4].value= 255


container[5].bin= 8
container[5].i= 493
container[5].j= 556
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 493
container[6].j= 562
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 494
container[7].j= 555
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 494
container[8].j= 562
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 495
container[9].j= 556
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 495
container[10].j= 563
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 496
container[11].j= 556
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 496
container[12].j= 563
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 497
container[13].j= 556
container[13].angle= 0
container[13].value= 255


container[14].bin= 41
container[14].i= 497
container[14].j= 563
container[14].angle= 206
container[14].value= 255


container[15].bin= 63
container[15].i= 498
container[15].j= 557
container[15].angle= 315
container[15].value= 255


container[16].bin= 41
container[16].i= 498
container[16].j= 563
container[16].angle= 206
container[16].value= 255


container[17].bin= 63
container[17].i= 499
container[17].j= 558
container[17].angle= 315
container[17].value= 255


container[18].bin= 36
container[18].i= 499
container[18].j= 562
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 500
container[19].j= 558
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 500
container[20].j= 562
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 501
container[21].j= 558
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 501
container[22].j= 562
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 502
container[23].j= 558
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 502
container[24].j= 562
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 503
container[25].j= 558
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 503
container[26].j= 562
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 504
container[27].j= 559
container[27].angle= 315
container[27].value= 255


container[28].bin= 54
container[28].i= 504
container[28].j= 560
container[28].angle= 270
container[28].value= 255


container[29].bin= 54
container[29].i= 504
container[29].j= 561
container[29].angle= 270
container[29].value= 255


container[30].bin= 44
container[30].i= 504
container[30].j= 562
container[30].angle= 224
container[30].value= 255


