container[0].bin= 3
container[0].i= 195
container[0].j= 205
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 195
container[1].j= 206
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 195
container[2].j= 207
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 196
container[3].j= 205
container[3].angle= 0
container[3].value= 255


container[4].bin= 66
container[4].i= 198
container[4].j= 206
container[4].angle= 333
container[4].value= 255


container[5].bin= 36
container[5].i= 198
container[5].j= 208
container[5].angle= 180
container[5].value= 255


container[6].bin= 68
container[6].i= 199
container[6].j= 206
container[6].angle= 341
container[6].value= 255


container[7].bin= 39
container[7].i= 199
container[7].j= 208
container[7].angle= 198
container[7].value= 255


