container[0].bin= 14
container[0].i= 110
container[0].j= 392
container[0].angle= 71
container[0].value= 255


container[1].bin= 12
container[1].i= 110
container[1].j= 393
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 110
container[2].j= 394
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 110
container[3].j= 395
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 111
container[4].j= 391
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 111
container[5].j= 396
container[5].angle= 135
container[5].value= 255


container[6].bin= 57
container[6].i= 112
container[6].j= 392
container[6].angle= 288
container[6].value= 255


container[7].bin= 63
container[7].i= 112
container[7].j= 393
container[7].angle= 315
container[7].value= 255


container[8].bin= 27
container[8].i= 112
container[8].j= 397
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 113
container[9].j= 393
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 113
container[10].j= 397
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 114
container[11].j= 393
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 114
container[12].j= 397
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 115
container[13].j= 393
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 115
container[14].j= 397
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 116
container[15].j= 393
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 116
container[16].j= 397
container[16].angle= 180
container[16].value= 255


container[17].bin= 66
container[17].i= 117
container[17].j= 394
container[17].angle= 333
container[17].value= 255


container[18].bin= 54
container[18].i= 117
container[18].j= 395
container[18].angle= 270
container[18].value= 255


container[19].bin= 44
container[19].i= 117
container[19].j= 397
container[19].angle= 224
container[19].value= 255


container[20].bin= 66
container[20].i= 118
container[20].j= 394
container[20].angle= 333
container[20].value= 255


container[21].bin= 44
container[21].i= 118
container[21].j= 396
container[21].angle= 224
container[21].value= 255


container[22].bin= 0
container[22].i= 119
container[22].j= 394
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 119
container[23].j= 396
container[23].angle= 180
container[23].value= 255


container[24].bin= 68
container[24].i= 120
container[24].j= 394
container[24].angle= 341
container[24].value= 255


container[25].bin= 54
container[25].i= 120
container[25].j= 395
container[25].angle= 270
container[25].value= 255


container[26].bin= 39
container[26].i= 120
container[26].j= 396
container[26].angle= 198
container[26].value= 255


