container[0].bin= 18
container[0].i= 113
container[0].j= 173
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 114
container[1].j= 172
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 114
container[2].j= 174
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 115
container[3].j= 171
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 115
container[4].j= 175
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 116
container[5].j= 171
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 116
container[6].j= 175
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 117
container[7].j= 171
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 117
container[8].j= 175
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 118
container[9].j= 171
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 118
container[10].j= 176
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 119
container[11].j= 171
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 119
container[12].j= 176
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 120
container[13].j= 171
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 120
container[14].j= 177
container[14].angle= 153
container[14].value= 255


container[15].bin= 66
container[15].i= 121
container[15].j= 172
container[15].angle= 333
container[15].value= 255


container[16].bin= 30
container[16].i= 121
container[16].j= 177
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 122
container[17].j= 172
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 122
container[18].j= 178
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 123
container[19].j= 172
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 123
container[20].j= 178
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 124
container[21].j= 173
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 124
container[22].j= 179
container[22].angle= 153
container[22].value= 255


container[23].bin= 66
container[23].i= 125
container[23].j= 173
container[23].angle= 333
container[23].value= 255


container[24].bin= 27
container[24].i= 125
container[24].j= 179
container[24].angle= 135
container[24].value= 255


container[25].bin= 27
container[25].i= 125
container[25].j= 180
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 126
container[26].j= 173
container[26].angle= 0
container[26].value= 255


container[27].bin= 30
container[27].i= 126
container[27].j= 180
container[27].angle= 153
container[27].value= 255


container[28].bin= 66
container[28].i= 127
container[28].j= 174
container[28].angle= 333
container[28].value= 255


container[29].bin= 36
container[29].i= 127
container[29].j= 180
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 128
container[30].j= 174
container[30].angle= 315
container[30].value= 255


container[31].bin= 63
container[31].i= 128
container[31].j= 175
container[31].angle= 315
container[31].value= 255


container[32].bin= 30
container[32].i= 128
container[32].j= 181
container[32].angle= 153
container[32].value= 255


container[33].bin= 66
container[33].i= 129
container[33].j= 175
container[33].angle= 333
container[33].value= 255


container[34].bin= 30
container[34].i= 129
container[34].j= 181
container[34].angle= 153
container[34].value= 255


container[35].bin= 66
container[35].i= 130
container[35].j= 176
container[35].angle= 333
container[35].value= 255


container[36].bin= 30
container[36].i= 130
container[36].j= 182
container[36].angle= 153
container[36].value= 255


container[37].bin= 63
container[37].i= 131
container[37].j= 176
container[37].angle= 315
container[37].value= 255


container[38].bin= 59
container[38].i= 131
container[38].j= 177
container[38].angle= 296
container[38].value= 255


container[39].bin= 27
container[39].i= 131
container[39].j= 182
container[39].angle= 135
container[39].value= 255


container[40].bin= 27
container[40].i= 131
container[40].j= 183
container[40].angle= 135
container[40].value= 255


container[41].bin= 63
container[41].i= 132
container[41].j= 178
container[41].angle= 315
container[41].value= 255


container[42].bin= 30
container[42].i= 132
container[42].j= 183
container[42].angle= 153
container[42].value= 255


container[43].bin= 63
container[43].i= 133
container[43].j= 179
container[43].angle= 315
container[43].value= 255


container[44].bin= 30
container[44].i= 133
container[44].j= 184
container[44].angle= 153
container[44].value= 255


container[45].bin= 59
container[45].i= 134
container[45].j= 180
container[45].angle= 296
container[45].value= 255


container[46].bin= 63
container[46].i= 134
container[46].j= 181
container[46].angle= 315
container[46].value= 255


container[47].bin= 27
container[47].i= 134
container[47].j= 184
container[47].angle= 135
container[47].value= 255


container[48].bin= 27
container[48].i= 134
container[48].j= 185
container[48].angle= 135
container[48].value= 255


container[49].bin= 63
container[49].i= 135
container[49].j= 181
container[49].angle= 315
container[49].value= 255


container[50].bin= 63
container[50].i= 135
container[50].j= 182
container[50].angle= 315
container[50].value= 255


container[51].bin= 27
container[51].i= 135
container[51].j= 185
container[51].angle= 135
container[51].value= 255


container[52].bin= 27
container[52].i= 135
container[52].j= 186
container[52].angle= 135
container[52].value= 255


container[53].bin= 63
container[53].i= 136
container[53].j= 182
container[53].angle= 315
container[53].value= 255


container[54].bin= 59
container[54].i= 136
container[54].j= 183
container[54].angle= 296
container[54].value= 255


container[55].bin= 54
container[55].i= 136
container[55].j= 184
container[55].angle= 270
container[55].value= 255


container[56].bin= 32
container[56].i= 136
container[56].j= 186
container[56].angle= 161
container[56].value= 255


container[57].bin= 59
container[57].i= 137
container[57].j= 185
container[57].angle= 296
container[57].value= 255


