container[0].bin= 18
container[0].i= 234
container[0].j= 209
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 235
container[1].j= 208
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 235
container[2].j= 210
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 236
container[3].j= 208
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 236
container[4].j= 210
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 237
container[5].j= 207
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 237
container[6].j= 208
container[6].angle= 44
container[6].value= 255


container[7].bin= 18
container[7].i= 237
container[7].j= 209
container[7].angle= 90
container[7].value= 255


container[8].bin= 30
container[8].i= 237
container[8].j= 210
container[8].angle= 153
container[8].value= 255


container[9].bin= 8
container[9].i= 238
container[9].j= 206
container[9].angle= 44
container[9].value= 255


container[10].bin= 30
container[10].i= 238
container[10].j= 210
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 239
container[11].j= 205
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 239
container[12].j= 210
container[12].angle= 180
container[12].value= 255


container[13].bin= 66
container[13].i= 240
container[13].j= 206
container[13].angle= 333
container[13].value= 255


container[14].bin= 27
container[14].i= 240
container[14].j= 211
container[14].angle= 135
container[14].value= 255


container[15].bin= 66
container[15].i= 241
container[15].j= 206
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 241
container[16].j= 212
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 242
container[17].j= 206
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 242
container[18].j= 212
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 243
container[19].j= 207
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 243
container[20].j= 208
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 243
container[21].j= 209
container[21].angle= 270
container[21].value= 255


container[22].bin= 30
container[22].i= 243
container[22].j= 213
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 244
container[23].j= 210
container[23].angle= 315
container[23].value= 255


container[24].bin= 30
container[24].i= 244
container[24].j= 213
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 245
container[25].j= 210
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 245
container[26].j= 213
container[26].angle= 180
container[26].value= 255


container[27].bin= 66
container[27].i= 246
container[27].j= 211
container[27].angle= 333
container[27].value= 255


container[28].bin= 54
container[28].i= 246
container[28].j= 212
container[28].angle= 270
container[28].value= 255


container[29].bin= 41
container[29].i= 246
container[29].j= 213
container[29].angle= 206
container[29].value= 255


container[30].bin= 66
container[30].i= 247
container[30].j= 211
container[30].angle= 333
container[30].value= 255


container[31].bin= 41
container[31].i= 247
container[31].j= 213
container[31].angle= 206
container[31].value= 255


container[32].bin= 0
container[32].i= 248
container[32].j= 211
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 248
container[33].j= 213
container[33].angle= 180
container[33].value= 255


container[34].bin= 18
container[34].i= 249
container[34].j= 207
container[34].angle= 90
container[34].value= 255


container[35].bin= 5
container[35].i= 249
container[35].j= 211
container[35].angle= 26
container[35].value= 255


container[36].bin= 36
container[36].i= 249
container[36].j= 213
container[36].angle= 180
container[36].value= 255


container[37].bin= 3
container[37].i= 250
container[37].j= 206
container[37].angle= 18
container[37].value= 255


container[38].bin= 32
container[38].i= 250
container[38].j= 208
container[38].angle= 161
container[38].value= 255


container[39].bin= 5
container[39].i= 250
container[39].j= 211
container[39].angle= 26
container[39].value= 255


container[40].bin= 0
container[40].i= 251
container[40].j= 206
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 251
container[41].j= 208
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 251
container[42].j= 210
container[42].angle= 0
container[42].value= 255


container[43].bin= 0
container[43].i= 252
container[43].j= 206
container[43].angle= 0
container[43].value= 255


container[44].bin= 27
container[44].i= 252
container[44].j= 208
container[44].angle= 135
container[44].value= 255


container[45].bin= 18
container[45].i= 252
container[45].j= 209
container[45].angle= 90
container[45].value= 255


container[46].bin= 8
container[46].i= 252
container[46].j= 210
container[46].angle= 44
container[46].value= 255


container[47].bin= 27
container[47].i= 252
container[47].j= 213
container[47].angle= 135
container[47].value= 255


container[48].bin= 18
container[48].i= 252
container[48].j= 214
container[48].angle= 90
container[48].value= 255


container[49].bin= 0
container[49].i= 253
container[49].j= 206
container[49].angle= 0
container[49].value= 255


container[50].bin= 27
container[50].i= 253
container[50].j= 215
container[50].angle= 135
container[50].value= 255


container[51].bin= 0
container[51].i= 254
container[51].j= 206
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 254
container[52].j= 215
container[52].angle= 180
container[52].value= 255


container[53].bin= 63
container[53].i= 255
container[53].j= 207
container[53].angle= 315
container[53].value= 255


container[54].bin= 54
container[54].i= 255
container[54].j= 208
container[54].angle= 270
container[54].value= 255


container[55].bin= 54
container[55].i= 255
container[55].j= 209
container[55].angle= 270
container[55].value= 255


container[56].bin= 27
container[56].i= 255
container[56].j= 216
container[56].angle= 135
container[56].value= 255


container[57].bin= 63
container[57].i= 256
container[57].j= 210
container[57].angle= 315
container[57].value= 255


container[58].bin= 27
container[58].i= 256
container[58].j= 217
container[58].angle= 135
container[58].value= 255


container[59].bin= 0
container[59].i= 257
container[59].j= 210
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 257
container[60].j= 217
container[60].angle= 180
container[60].value= 255


container[61].bin= 66
container[61].i= 258
container[61].j= 211
container[61].angle= 333
container[61].value= 255


container[62].bin= 27
container[62].i= 258
container[62].j= 218
container[62].angle= 135
container[62].value= 255


container[63].bin= 18
container[63].i= 258
container[63].j= 219
container[63].angle= 90
container[63].value= 255


container[64].bin= 66
container[64].i= 259
container[64].j= 211
container[64].angle= 333
container[64].value= 255


container[65].bin= 27
container[65].i= 259
container[65].j= 220
container[65].angle= 135
container[65].value= 255


container[66].bin= 0
container[66].i= 260
container[66].j= 211
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 260
container[67].j= 220
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 261
container[68].j= 212
container[68].angle= 315
container[68].value= 255


container[69].bin= 44
container[69].i= 261
container[69].j= 220
container[69].angle= 224
container[69].value= 255


container[70].bin= 63
container[70].i= 262
container[70].j= 213
container[70].angle= 315
container[70].value= 255


container[71].bin= 44
container[71].i= 262
container[71].j= 219
container[71].angle= 224
container[71].value= 255


container[72].bin= 0
container[72].i= 263
container[72].j= 213
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 263
container[73].j= 218
container[73].angle= 180
container[73].value= 255


container[74].bin= 66
container[74].i= 264
container[74].j= 214
container[74].angle= 333
container[74].value= 255


container[75].bin= 41
container[75].i= 264
container[75].j= 218
container[75].angle= 206
container[75].value= 255


container[76].bin= 63
container[76].i= 265
container[76].j= 214
container[76].angle= 315
container[76].value= 255


container[77].bin= 59
container[77].i= 265
container[77].j= 215
container[77].angle= 296
container[77].value= 255


container[78].bin= 57
container[78].i= 265
container[78].j= 216
container[78].angle= 288
container[78].value= 255


container[79].bin= 36
container[79].i= 265
container[79].j= 218
container[79].angle= 180
container[79].value= 255


container[80].bin= 0
container[80].i= 266
container[80].j= 214
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 266
container[81].j= 218
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 267
container[82].j= 214
container[82].angle= 0
container[82].value= 255


container[83].bin= 41
container[83].i= 267
container[83].j= 218
container[83].angle= 206
container[83].value= 255


container[84].bin= 57
container[84].i= 268
container[84].j= 215
container[84].angle= 288
container[84].value= 255


container[85].bin= 63
container[85].i= 268
container[85].j= 216
container[85].angle= 315
container[85].value= 255


container[86].bin= 36
container[86].i= 268
container[86].j= 218
container[86].angle= 180
container[86].value= 255


container[87].bin= 0
container[87].i= 269
container[87].j= 216
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 269
container[88].j= 218
container[88].angle= 180
container[88].value= 255


container[89].bin= 0
container[89].i= 270
container[89].j= 216
container[89].angle= 0
container[89].value= 255


container[90].bin= 36
container[90].i= 270
container[90].j= 218
container[90].angle= 180
container[90].value= 255


container[91].bin= 0
container[91].i= 271
container[91].j= 216
container[91].angle= 0
container[91].value= 255


container[92].bin= 36
container[92].i= 271
container[92].j= 218
container[92].angle= 180
container[92].value= 255


container[93].bin= 0
container[93].i= 272
container[93].j= 216
container[93].angle= 0
container[93].value= 255


container[94].bin= 36
container[94].i= 272
container[94].j= 218
container[94].angle= 180
container[94].value= 255


container[95].bin= 68
container[95].i= 273
container[95].j= 216
container[95].angle= 341
container[95].value= 255


container[96].bin= 54
container[96].i= 273
container[96].j= 217
container[96].angle= 270
container[96].value= 255


container[97].bin= 39
container[97].i= 273
container[97].j= 218
container[97].angle= 198
container[97].value= 255


