container[0].bin= 18
container[0].i= 818
container[0].j= 267
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 819
container[1].j= 266
container[1].angle= 18
container[1].value= 255


container[2].bin= 27
container[2].i= 819
container[2].j= 268
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 819
container[3].j= 269
container[3].angle= 44
container[3].value= 255


container[4].bin= 21
container[4].i= 819
container[4].j= 270
container[4].angle= 108
container[4].value= 255


container[5].bin= 0
container[5].i= 820
container[5].j= 266
container[5].angle= 0
container[5].value= 255


container[6].bin= 8
container[6].i= 820
container[6].j= 269
container[6].angle= 44
container[6].value= 255


container[7].bin= 0
container[7].i= 821
container[7].j= 266
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 821
container[8].j= 270
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 822
container[9].j= 266
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 822
container[10].j= 270
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 823
container[11].j= 266
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 823
container[12].j= 270
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 824
container[13].j= 266
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 824
container[14].j= 270
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 825
container[15].j= 266
container[15].angle= 0
container[15].value= 255


container[16].bin= 44
container[16].i= 825
container[16].j= 269
container[16].angle= 224
container[16].value= 255


container[17].bin= 0
container[17].i= 826
container[17].j= 266
container[17].angle= 0
container[17].value= 255


container[18].bin= 8
container[18].i= 827
container[18].j= 266
container[18].angle= 44
container[18].value= 255


container[19].bin= 8
container[19].i= 828
container[19].j= 265
container[19].angle= 44
container[19].value= 255


container[20].bin= 36
container[20].i= 828
container[20].j= 268
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 829
container[21].j= 264
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 829
container[22].j= 268
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 830
container[23].j= 265
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 830
container[24].j= 266
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 830
container[25].j= 267
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 830
container[26].j= 268
container[26].angle= 224
container[26].value= 255


