container[0].bin= 18
container[0].i= 213
container[0].j= 302
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 214
container[1].j= 301
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 214
container[2].j= 303
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 215
container[3].j= 301
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 215
container[4].j= 303
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 216
container[5].j= 301
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 216
container[6].j= 303
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 216
container[7].j= 304
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 217
container[8].j= 301
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 217
container[9].j= 305
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 218
container[10].j= 301
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 218
container[11].j= 305
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 219
container[12].j= 301
container[12].angle= 0
container[12].value= 255


container[13].bin= 41
container[13].i= 219
container[13].j= 305
container[13].angle= 206
container[13].value= 255


container[14].bin= 0
container[14].i= 220
container[14].j= 301
container[14].angle= 0
container[14].value= 255


container[15].bin= 41
container[15].i= 220
container[15].j= 305
container[15].angle= 206
container[15].value= 255


container[16].bin= 68
container[16].i= 221
container[16].j= 301
container[16].angle= 341
container[16].value= 255


container[17].bin= 57
container[17].i= 221
container[17].j= 303
container[17].angle= 288
container[17].value= 255


container[18].bin= 36
container[18].i= 221
container[18].j= 305
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 222
container[19].j= 303
container[19].angle= 315
container[19].value= 255


container[20].bin= 39
container[20].i= 222
container[20].j= 305
container[20].angle= 198
container[20].value= 255


