container[0].bin= 18
container[0].i= 114
container[0].j= 155
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 115
container[1].j= 154
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 115
container[2].j= 156
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 116
container[3].j= 153
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 116
container[4].j= 156
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 117
container[5].j= 153
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 117
container[6].j= 157
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 118
container[7].j= 153
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 118
container[8].j= 157
container[8].angle= 153
container[8].value= 255


container[9].bin= 8
container[9].i= 118
container[9].j= 163
container[9].angle= 44
container[9].value= 255


container[10].bin= 27
container[10].i= 118
container[10].j= 164
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 119
container[11].j= 153
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 119
container[12].j= 157
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 119
container[13].j= 162
container[13].angle= 0
container[13].value= 255


container[14].bin= 63
container[14].i= 120
container[14].j= 154
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 120
container[15].j= 158
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 120
container[16].j= 159
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 120
container[17].j= 160
container[17].angle= 90
container[17].value= 255


container[18].bin= 18
container[18].i= 120
container[18].j= 161
container[18].angle= 90
container[18].value= 255


container[19].bin= 8
container[19].i= 120
container[19].j= 162
container[19].angle= 44
container[19].value= 255


container[20].bin= 41
container[20].i= 120
container[20].j= 164
container[20].angle= 206
container[20].value= 255


container[21].bin= 63
container[21].i= 121
container[21].j= 155
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 121
container[22].j= 164
container[22].angle= 224
container[22].value= 255


container[23].bin= 0
container[23].i= 122
container[23].j= 155
container[23].angle= 0
container[23].value= 255


container[24].bin= 41
container[24].i= 122
container[24].j= 163
container[24].angle= 206
container[24].value= 255


container[25].bin= 63
container[25].i= 123
container[25].j= 156
container[25].angle= 315
container[25].value= 255


container[26].bin= 27
container[26].i= 123
container[26].j= 163
container[26].angle= 135
container[26].value= 255


container[27].bin= 63
container[27].i= 124
container[27].j= 157
container[27].angle= 315
container[27].value= 255


container[28].bin= 27
container[28].i= 124
container[28].j= 164
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 125
container[29].j= 157
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 125
container[30].j= 164
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 126
container[31].j= 157
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 126
container[32].j= 164
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 127
container[33].j= 157
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 127
container[34].j= 164
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 128
container[35].j= 157
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 128
container[36].j= 164
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 129
container[37].j= 157
container[37].angle= 0
container[37].value= 255


container[38].bin= 39
container[38].i= 129
container[38].j= 161
container[38].angle= 198
container[38].value= 255


container[39].bin= 50
container[39].i= 129
container[39].j= 162
container[39].angle= 251
container[39].value= 255


container[40].bin= 59
container[40].i= 129
container[40].j= 163
container[40].angle= 296
container[40].value= 255


container[41].bin= 44
container[41].i= 129
container[41].j= 164
container[41].angle= 224
container[41].value= 255


container[42].bin= 0
container[42].i= 130
container[42].j= 157
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 130
container[43].j= 161
container[43].angle= 180
container[43].value= 255


container[44].bin= 8
container[44].i= 130
container[44].j= 166
container[44].angle= 44
container[44].value= 255


container[45].bin= 27
container[45].i= 130
container[45].j= 167
container[45].angle= 135
container[45].value= 255


container[46].bin= 66
container[46].i= 131
container[46].j= 158
container[46].angle= 333
container[46].value= 255


container[47].bin= 36
container[47].i= 131
container[47].j= 161
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 131
container[48].j= 165
container[48].angle= 0
container[48].value= 255


container[49].bin= 66
container[49].i= 132
container[49].j= 158
container[49].angle= 333
container[49].value= 255


container[50].bin= 27
container[50].i= 132
container[50].j= 162
container[50].angle= 135
container[50].value= 255


container[51].bin= 18
container[51].i= 132
container[51].j= 164
container[51].angle= 90
container[51].value= 255


container[52].bin= 5
container[52].i= 132
container[52].j= 165
container[52].angle= 26
container[52].value= 255


container[53].bin= 18
container[53].i= 132
container[53].j= 169
container[53].angle= 90
container[53].value= 255


container[54].bin= 0
container[54].i= 133
container[54].j= 158
container[54].angle= 0
container[54].value= 255


container[55].bin= 27
container[55].i= 133
container[55].j= 163
container[55].angle= 135
container[55].value= 255


container[56].bin= 0
container[56].i= 133
container[56].j= 165
container[56].angle= 0
container[56].value= 255


container[57].bin= 32
container[57].i= 133
container[57].j= 167
container[57].angle= 161
container[57].value= 255


container[58].bin= 27
container[58].i= 133
container[58].j= 168
container[58].angle= 135
container[58].value= 255


container[59].bin= 0
container[59].i= 134
container[59].j= 158
container[59].angle= 0
container[59].value= 255


container[60].bin= 32
container[60].i= 134
container[60].j= 163
container[60].angle= 161
container[60].value= 255


container[61].bin= 63
container[61].i= 135
container[61].j= 159
container[61].angle= 315
container[61].value= 255


container[62].bin= 21
container[62].i= 135
container[62].j= 169
container[62].angle= 108
container[62].value= 255


container[63].bin= 27
container[63].i= 135
container[63].j= 170
container[63].angle= 135
container[63].value= 255


container[64].bin= 63
container[64].i= 136
container[64].j= 160
container[64].angle= 315
container[64].value= 255


container[65].bin= 30
container[65].i= 136
container[65].j= 170
container[65].angle= 153
container[65].value= 255


container[66].bin= 0
container[66].i= 137
container[66].j= 160
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 137
container[67].j= 170
container[67].angle= 180
container[67].value= 255


container[68].bin= 63
container[68].i= 138
container[68].j= 161
container[68].angle= 315
container[68].value= 255


container[69].bin= 36
container[69].i= 138
container[69].j= 170
container[69].angle= 180
container[69].value= 255


container[70].bin= 59
container[70].i= 139
container[70].j= 162
container[70].angle= 296
container[70].value= 255


container[71].bin= 63
container[71].i= 139
container[71].j= 163
container[71].angle= 315
container[71].value= 255


container[72].bin= 36
container[72].i= 139
container[72].j= 170
container[72].angle= 180
container[72].value= 255


container[73].bin= 66
container[73].i= 140
container[73].j= 163
container[73].angle= 333
container[73].value= 255


container[74].bin= 36
container[74].i= 140
container[74].j= 170
container[74].angle= 180
container[74].value= 255


container[75].bin= 63
container[75].i= 141
container[75].j= 164
container[75].angle= 315
container[75].value= 255


container[76].bin= 54
container[76].i= 141
container[76].j= 169
container[76].angle= 270
container[76].value= 255


container[77].bin= 44
container[77].i= 141
container[77].j= 170
container[77].angle= 224
container[77].value= 255


container[78].bin= 63
container[78].i= 142
container[78].j= 165
container[78].angle= 315
container[78].value= 255


container[79].bin= 44
container[79].i= 142
container[79].j= 168
container[79].angle= 224
container[79].value= 255


container[80].bin= 0
container[80].i= 143
container[80].j= 165
container[80].angle= 0
container[80].value= 255


container[81].bin= 63
container[81].i= 144
container[81].j= 166
container[81].angle= 315
container[81].value= 255


container[82].bin= 44
container[82].i= 144
container[82].j= 167
container[82].angle= 224
container[82].value= 255


