container[0].bin= 18
container[0].i= 875
container[0].j= 454
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 875
container[1].j= 455
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 876
container[2].j= 453
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 876
container[3].j= 456
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 877
container[4].j= 452
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 877
container[5].j= 456
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 878
container[6].j= 453
container[6].angle= 315
container[6].value= 255


container[7].bin= 30
container[7].i= 878
container[7].j= 457
container[7].angle= 153
container[7].value= 255


container[8].bin= 63
container[8].i= 879
container[8].j= 454
container[8].angle= 315
container[8].value= 255


container[9].bin= 30
container[9].i= 879
container[9].j= 457
container[9].angle= 153
container[9].value= 255


container[10].bin= 5
container[10].i= 880
container[10].j= 454
container[10].angle= 26
container[10].value= 255


container[11].bin= 41
container[11].i= 880
container[11].j= 457
container[11].angle= 206
container[11].value= 255


container[12].bin= 68
container[12].i= 881
container[12].j= 454
container[12].angle= 341
container[12].value= 255


container[13].bin= 48
container[13].i= 881
container[13].j= 456
container[13].angle= 243
container[13].value= 255


container[14].bin= 44
container[14].i= 881
container[14].j= 457
container[14].angle= 224
container[14].value= 255


