container[0].bin= 18
container[0].i= 432
container[0].j= 534
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 433
container[1].j= 533
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 433
container[2].j= 535
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 434
container[3].j= 532
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 434
container[4].j= 535
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 435
container[5].j= 533
container[5].angle= 315
container[5].value= 255


container[6].bin= 54
container[6].i= 435
container[6].j= 534
container[6].angle= 270
container[6].value= 255


container[7].bin= 44
container[7].i= 435
container[7].j= 535
container[7].angle= 224
container[7].value= 255


