container[0].bin= 8
container[0].i= 587
container[0].j= 423
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 587
container[1].j= 424
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 588
container[2].j= 423
container[2].angle= 26
container[2].value= 255


container[3].bin= 0
container[3].i= 589
container[3].j= 422
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 590
container[4].j= 422
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 591
container[5].j= 422
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 592
container[6].j= 423
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 592
container[7].j= 424
container[7].angle= 224
container[7].value= 255


