container[0].bin= 8
container[0].i= 406
container[0].j= 609
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 406
container[1].j= 610
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 407
container[2].j= 608
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 408
container[3].j= 609
container[3].angle= 333
container[3].value= 255


container[4].bin= 0
container[4].i= 409
container[4].j= 609
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 409
container[5].j= 611
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 410
container[6].j= 609
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 410
container[7].j= 611
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 411
container[8].j= 609
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 411
container[9].j= 611
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 412
container[10].j= 609
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 412
container[11].j= 611
container[11].angle= 135
container[11].value= 255


container[12].bin= 27
container[12].i= 412
container[12].j= 612
container[12].angle= 135
container[12].value= 255


container[13].bin= 66
container[13].i= 413
container[13].j= 609
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 413
container[14].j= 612
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 414
container[15].j= 610
container[15].angle= 315
container[15].value= 255


container[16].bin= 48
container[16].i= 414
container[16].j= 611
container[16].angle= 243
container[16].value= 255


container[17].bin= 44
container[17].i= 414
container[17].j= 612
container[17].angle= 224
container[17].value= 255


