container[0].bin= 18
container[0].i= 462
container[0].j= 315
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 463
container[1].j= 314
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 463
container[2].j= 316
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 464
container[3].j= 314
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 464
container[4].j= 316
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 465
container[5].j= 314
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 465
container[6].j= 316
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 466
container[7].j= 314
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 466
container[8].j= 316
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 467
container[9].j= 314
container[9].angle= 0
container[9].value= 255


container[10].bin= 8
container[10].i= 468
container[10].j= 314
container[10].angle= 44
container[10].value= 255


container[11].bin= 30
container[11].i= 468
container[11].j= 317
container[11].angle= 153
container[11].value= 255


container[12].bin= 8
container[12].i= 469
container[12].j= 313
container[12].angle= 44
container[12].value= 255


container[13].bin= 27
container[13].i= 469
container[13].j= 317
container[13].angle= 135
container[13].value= 255


container[14].bin= 23
container[14].i= 469
container[14].j= 318
container[14].angle= 116
container[14].value= 255


container[15].bin= 0
container[15].i= 470
container[15].j= 312
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 470
container[16].j= 319
container[16].angle= 135
container[16].value= 255


container[17].bin= 5
container[17].i= 471
container[17].j= 312
container[17].angle= 26
container[17].value= 255


container[18].bin= 36
container[18].i= 471
container[18].j= 319
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 472
container[19].j= 312
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 472
container[20].j= 319
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 473
container[21].j= 312
container[21].angle= 333
container[21].value= 255


container[22].bin= 36
container[22].i= 473
container[22].j= 319
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 474
container[23].j= 313
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 474
container[24].j= 318
container[24].angle= 270
container[24].value= 255


container[25].bin= 44
container[25].i= 474
container[25].j= 319
container[25].angle= 224
container[25].value= 255


container[26].bin= 63
container[26].i= 475
container[26].j= 314
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 475
container[27].j= 317
container[27].angle= 224
container[27].value= 255


container[28].bin= 0
container[28].i= 476
container[28].j= 314
container[28].angle= 0
container[28].value= 255


container[29].bin= 63
container[29].i= 477
container[29].j= 315
container[29].angle= 315
container[29].value= 255


container[30].bin= 44
container[30].i= 477
container[30].j= 316
container[30].angle= 224
container[30].value= 255


