container[0].bin= 8
container[0].i= 562
container[0].j= 505
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 562
container[1].j= 506
container[1].angle= 108
container[1].value= 255


container[2].bin= 0
container[2].i= 563
container[2].j= 505
container[2].angle= 0
container[2].value= 255


container[3].bin= 36
container[3].i= 563
container[3].j= 507
container[3].angle= 180
container[3].value= 255


container[4].bin= 63
container[4].i= 564
container[4].j= 505
container[4].angle= 315
container[4].value= 255


container[5].bin= 50
container[5].i= 564
container[5].j= 506
container[5].angle= 251
container[5].value= 255


