container[0].bin= 8
container[0].i= 210
container[0].j= 188
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 210
container[1].j= 189
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 211
container[2].j= 188
container[2].angle= 26
container[2].value= 255


container[3].bin= 5
container[3].i= 212
container[3].j= 187
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 212
container[4].j= 190
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 213
container[5].j= 187
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 213
container[6].j= 190
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 214
container[7].j= 186
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 214
container[8].j= 190
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 215
container[9].j= 186
container[9].angle= 26
container[9].value= 255


container[10].bin= 36
container[10].i= 215
container[10].j= 190
container[10].angle= 180
container[10].value= 255


container[11].bin= 5
container[11].i= 216
container[11].j= 186
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 216
container[12].j= 190
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 217
container[13].j= 185
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 217
container[14].j= 190
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 218
container[15].j= 185
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 218
container[16].j= 191
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 219
container[17].j= 185
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 219
container[18].j= 191
container[18].angle= 153
container[18].value= 255


container[19].bin= 5
container[19].i= 220
container[19].j= 185
container[19].angle= 26
container[19].value= 255


container[20].bin= 36
container[20].i= 220
container[20].j= 191
container[20].angle= 180
container[20].value= 255


container[21].bin= 5
container[21].i= 221
container[21].j= 185
container[21].angle= 26
container[21].value= 255


container[22].bin= 36
container[22].i= 221
container[22].j= 191
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 222
container[23].j= 184
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 222
container[24].j= 191
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 223
container[25].j= 184
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 223
container[26].j= 192
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 224
container[27].j= 185
container[27].angle= 333
container[27].value= 255


container[28].bin= 44
container[28].i= 224
container[28].j= 187
container[28].angle= 224
container[28].value= 255


container[29].bin= 54
container[29].i= 224
container[29].j= 188
container[29].angle= 270
container[29].value= 255


container[30].bin= 63
container[30].i= 224
container[30].j= 189
container[30].angle= 315
container[30].value= 255


container[31].bin= 30
container[31].i= 224
container[31].j= 192
container[31].angle= 153
container[31].value= 255


container[32].bin= 63
container[32].i= 225
container[32].j= 185
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 225
container[33].j= 186
container[33].angle= 270
container[33].value= 255


container[34].bin= 44
container[34].i= 225
container[34].j= 187
container[34].angle= 224
container[34].value= 255


container[35].bin= 63
container[35].i= 225
container[35].j= 189
container[35].angle= 315
container[35].value= 255


container[36].bin= 63
container[36].i= 225
container[36].j= 190
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 225
container[37].j= 192
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 226
container[38].j= 190
container[38].angle= 315
container[38].value= 255


container[39].bin= 63
container[39].i= 226
container[39].j= 191
container[39].angle= 315
container[39].value= 255


container[40].bin= 63
container[40].i= 227
container[40].j= 191
container[40].angle= 315
container[40].value= 255


container[41].bin= 32
container[41].i= 227
container[41].j= 193
container[41].angle= 161
container[41].value= 255


