container[0].bin= 8
container[0].i= 101
container[0].j= 204
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 101
container[1].j= 205
container[1].angle= 63
container[1].value= 255


container[2].bin= 23
container[2].i= 101
container[2].j= 206
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 101
container[3].j= 207
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 102
container[4].j= 203
container[4].angle= 44
container[4].value= 255


container[5].bin= 8
container[5].i= 102
container[5].j= 204
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 102
container[6].j= 207
container[6].angle= 135
container[6].value= 255


container[7].bin= 27
container[7].i= 102
container[7].j= 208
container[7].angle= 135
container[7].value= 255


container[8].bin= 5
container[8].i= 103
container[8].j= 203
container[8].angle= 26
container[8].value= 255


container[9].bin= 27
container[9].i= 103
container[9].j= 208
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 103
container[10].j= 209
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 104
container[11].j= 202
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 104
container[12].j= 209
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 104
container[13].j= 210
container[13].angle= 135
container[13].value= 255


container[14].bin= 66
container[14].i= 105
container[14].j= 203
container[14].angle= 333
container[14].value= 255


container[15].bin= 30
container[15].i= 105
container[15].j= 210
container[15].angle= 153
container[15].value= 255


container[16].bin= 63
container[16].i= 106
container[16].j= 203
container[16].angle= 315
container[16].value= 255


container[17].bin= 63
container[17].i= 106
container[17].j= 204
container[17].angle= 315
container[17].value= 255


container[18].bin= 30
container[18].i= 106
container[18].j= 211
container[18].angle= 153
container[18].value= 255


container[19].bin= 63
container[19].i= 107
container[19].j= 204
container[19].angle= 315
container[19].value= 255


container[20].bin= 63
container[20].i= 107
container[20].j= 205
container[20].angle= 315
container[20].value= 255


container[21].bin= 30
container[21].i= 107
container[21].j= 211
container[21].angle= 153
container[21].value= 255


container[22].bin= 63
container[22].i= 108
container[22].j= 205
container[22].angle= 315
container[22].value= 255


container[23].bin= 59
container[23].i= 108
container[23].j= 206
container[23].angle= 296
container[23].value= 255


container[24].bin= 36
container[24].i= 108
container[24].j= 211
container[24].angle= 180
container[24].value= 255


container[25].bin= 59
container[25].i= 109
container[25].j= 207
container[25].angle= 296
container[25].value= 255


container[26].bin= 63
container[26].i= 109
container[26].j= 208
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 109
container[27].j= 211
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 110
container[28].j= 208
container[28].angle= 315
container[28].value= 255


container[29].bin= 59
container[29].i= 110
container[29].j= 209
container[29].angle= 296
container[29].value= 255


container[30].bin= 59
container[30].i= 111
container[30].j= 210
container[30].angle= 296
container[30].value= 255


