container[0].bin= 8
container[0].i= 265
container[0].j= 277
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 265
container[1].j= 278
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 266
container[2].j= 276
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 267
container[3].j= 277
container[3].angle= 333
container[3].value= 255


container[4].bin= 66
container[4].i= 268
container[4].j= 277
container[4].angle= 333
container[4].value= 255


container[5].bin= 36
container[5].i= 268
container[5].j= 279
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 269
container[6].j= 277
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 269
container[7].j= 279
container[7].angle= 180
container[7].value= 255


container[8].bin= 5
container[8].i= 270
container[8].j= 277
container[8].angle= 26
container[8].value= 255


container[9].bin= 36
container[9].i= 270
container[9].j= 279
container[9].angle= 180
container[9].value= 255


container[10].bin= 5
container[10].i= 271
container[10].j= 277
container[10].angle= 26
container[10].value= 255


container[11].bin= 0
container[11].i= 272
container[11].j= 276
container[11].angle= 0
container[11].value= 255


container[12].bin= 63
container[12].i= 273
container[12].j= 277
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 273
container[13].j= 278
container[13].angle= 224
container[13].value= 255


