container[0].bin= 18
container[0].i= 483
container[0].j= 480
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 483
container[1].j= 481
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 483
container[2].j= 482
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 483
container[3].j= 483
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 483
container[4].j= 484
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 483
container[5].j= 485
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 483
container[6].j= 486
container[6].angle= 90
container[6].value= 255


container[7].bin= 12
container[7].i= 483
container[7].j= 487
container[7].angle= 63
container[7].value= 255


container[8].bin= 21
container[8].i= 483
container[8].j= 488
container[8].angle= 108
container[8].value= 255


container[9].bin= 8
container[9].i= 484
container[9].j= 479
container[9].angle= 44
container[9].value= 255


container[10].bin= 27
container[10].i= 484
container[10].j= 489
container[10].angle= 135
container[10].value= 255


container[11].bin= 21
container[11].i= 484
container[11].j= 490
container[11].angle= 108
container[11].value= 255


container[12].bin= 0
container[12].i= 485
container[12].j= 478
container[12].angle= 0
container[12].value= 255


container[13].bin= 63
container[13].i= 486
container[13].j= 479
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 486
container[14].j= 480
container[14].angle= 270
container[14].value= 255


container[15].bin= 44
container[15].i= 486
container[15].j= 489
container[15].angle= 224
container[15].value= 255


container[16].bin= 44
container[16].i= 486
container[16].j= 490
container[16].angle= 224
container[16].value= 255


container[17].bin= 63
container[17].i= 487
container[17].j= 481
container[17].angle= 315
container[17].value= 255


container[18].bin= 41
container[18].i= 487
container[18].j= 489
container[18].angle= 206
container[18].value= 255


container[19].bin= 0
container[19].i= 488
container[19].j= 481
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 488
container[20].j= 488
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 489
container[21].j= 481
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 489
container[22].j= 488
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 490
container[23].j= 481
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 490
container[24].j= 488
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 491
container[25].j= 481
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 491
container[26].j= 488
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 492
container[27].j= 482
container[27].angle= 315
container[27].value= 255


container[28].bin= 54
container[28].i= 492
container[28].j= 483
container[28].angle= 270
container[28].value= 255


container[29].bin= 36
container[29].i= 492
container[29].j= 488
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 493
container[30].j= 484
container[30].angle= 315
container[30].value= 255


container[31].bin= 36
container[31].i= 493
container[31].j= 488
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 494
container[32].j= 484
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 494
container[33].j= 488
container[33].angle= 180
container[33].value= 255


container[34].bin= 5
container[34].i= 495
container[34].j= 484
container[34].angle= 26
container[34].value= 255


container[35].bin= 36
container[35].i= 495
container[35].j= 488
container[35].angle= 180
container[35].value= 255


container[36].bin= 5
container[36].i= 496
container[36].j= 484
container[36].angle= 26
container[36].value= 255


container[37].bin= 36
container[37].i= 496
container[37].j= 488
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 497
container[38].j= 483
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 497
container[39].j= 488
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 498
container[40].j= 483
container[40].angle= 0
container[40].value= 255


container[41].bin= 54
container[41].i= 498
container[41].j= 487
container[41].angle= 270
container[41].value= 255


container[42].bin= 44
container[42].i= 498
container[42].j= 488
container[42].angle= 224
container[42].value= 255


container[43].bin= 0
container[43].i= 499
container[43].j= 483
container[43].angle= 0
container[43].value= 255


container[44].bin= 44
container[44].i= 499
container[44].j= 486
container[44].angle= 224
container[44].value= 255


container[45].bin= 66
container[45].i= 500
container[45].j= 484
container[45].angle= 333
container[45].value= 255


container[46].bin= 63
container[46].i= 501
container[46].j= 484
container[46].angle= 315
container[46].value= 255


