container[0].bin= 18
container[0].i= 776
container[0].j= 441
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 777
container[1].j= 440
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 777
container[2].j= 442
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 777
container[3].j= 443
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 778
container[4].j= 439
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 778
container[5].j= 443
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 779
container[6].j= 439
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 779
container[7].j= 443
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 780
container[8].j= 439
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 780
container[9].j= 443
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 781
container[10].j= 439
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 781
container[11].j= 443
container[11].angle= 180
container[11].value= 255


container[12].bin= 5
container[12].i= 782
container[12].j= 439
container[12].angle= 26
container[12].value= 255


container[13].bin= 44
container[13].i= 782
container[13].j= 443
container[13].angle= 224
container[13].value= 255


container[14].bin= 5
container[14].i= 783
container[14].j= 439
container[14].angle= 26
container[14].value= 255


container[15].bin= 44
container[15].i= 783
container[15].j= 442
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 784
container[16].j= 438
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 784
container[17].j= 441
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 785
container[18].j= 439
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 785
container[19].j= 440
container[19].angle= 270
container[19].value= 255


container[20].bin= 44
container[20].i= 785
container[20].j= 441
container[20].angle= 224
container[20].value= 255


