container[0].bin= 18
container[0].i= 272
container[0].j= 157
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 273
container[1].j= 155
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 273
container[2].j= 156
container[2].angle= 63
container[2].value= 255


container[3].bin= 23
container[3].i= 273
container[3].j= 158
container[3].angle= 116
container[3].value= 255


container[4].bin= 27
container[4].i= 273
container[4].j= 159
container[4].angle= 135
container[4].value= 255


container[5].bin= 5
container[5].i= 274
container[5].j= 155
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 274
container[6].j= 159
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 275
container[7].j= 154
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 275
container[8].j= 160
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 276
container[9].j= 154
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 276
container[10].j= 160
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 277
container[11].j= 154
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 277
container[12].j= 161
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 278
container[13].j= 154
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 278
container[14].j= 161
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 279
container[15].j= 154
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 279
container[16].j= 161
container[16].angle= 180
container[16].value= 255


container[17].bin= 5
container[17].i= 280
container[17].j= 154
container[17].angle= 26
container[17].value= 255


container[18].bin= 30
container[18].i= 280
container[18].j= 162
container[18].angle= 153
container[18].value= 255


container[19].bin= 8
container[19].i= 281
container[19].j= 153
container[19].angle= 44
container[19].value= 255


container[20].bin= 8
container[20].i= 281
container[20].j= 154
container[20].angle= 44
container[20].value= 255


container[21].bin= 27
container[21].i= 281
container[21].j= 162
container[21].angle= 135
container[21].value= 255


container[22].bin= 27
container[22].i= 281
container[22].j= 163
container[22].angle= 135
container[22].value= 255


container[23].bin= 5
container[23].i= 282
container[23].j= 153
container[23].angle= 26
container[23].value= 255


container[24].bin= 30
container[24].i= 282
container[24].j= 163
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 283
container[25].j= 152
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 283
container[26].j= 163
container[26].angle= 180
container[26].value= 255


container[27].bin= 5
container[27].i= 284
container[27].j= 152
container[27].angle= 26
container[27].value= 255


container[28].bin= 30
container[28].i= 284
container[28].j= 164
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 285
container[29].j= 152
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 285
container[30].j= 164
container[30].angle= 153
container[30].value= 255


container[31].bin= 63
container[31].i= 286
container[31].j= 152
container[31].angle= 315
container[31].value= 255


container[32].bin= 59
container[32].i= 286
container[32].j= 153
container[32].angle= 296
container[32].value= 255


container[33].bin= 30
container[33].i= 286
container[33].j= 165
container[33].angle= 153
container[33].value= 255


container[34].bin= 59
container[34].i= 287
container[34].j= 154
container[34].angle= 296
container[34].value= 255


container[35].bin= 59
container[35].i= 287
container[35].j= 155
container[35].angle= 296
container[35].value= 255


container[36].bin= 27
container[36].i= 287
container[36].j= 165
container[36].angle= 135
container[36].value= 255


container[37].bin= 27
container[37].i= 287
container[37].j= 166
container[37].angle= 135
container[37].value= 255


container[38].bin= 59
container[38].i= 288
container[38].j= 156
container[38].angle= 296
container[38].value= 255


container[39].bin= 59
container[39].i= 288
container[39].j= 157
container[39].angle= 296
container[39].value= 255


container[40].bin= 30
container[40].i= 288
container[40].j= 166
container[40].angle= 153
container[40].value= 255


container[41].bin= 59
container[41].i= 289
container[41].j= 158
container[41].angle= 296
container[41].value= 255


container[42].bin= 59
container[42].i= 289
container[42].j= 159
container[42].angle= 296
container[42].value= 255


container[43].bin= 30
container[43].i= 289
container[43].j= 167
container[43].angle= 153
container[43].value= 255


container[44].bin= 59
container[44].i= 290
container[44].j= 160
container[44].angle= 296
container[44].value= 255


container[45].bin= 63
container[45].i= 290
container[45].j= 161
container[45].angle= 315
container[45].value= 255


container[46].bin= 27
container[46].i= 290
container[46].j= 167
container[46].angle= 135
container[46].value= 255


container[47].bin= 27
container[47].i= 290
container[47].j= 168
container[47].angle= 135
container[47].value= 255


container[48].bin= 63
container[48].i= 291
container[48].j= 161
container[48].angle= 315
container[48].value= 255


container[49].bin= 63
container[49].i= 291
container[49].j= 162
container[49].angle= 315
container[49].value= 255


container[50].bin= 30
container[50].i= 291
container[50].j= 168
container[50].angle= 153
container[50].value= 255


container[51].bin= 63
container[51].i= 292
container[51].j= 162
container[51].angle= 315
container[51].value= 255


container[52].bin= 59
container[52].i= 292
container[52].j= 163
container[52].angle= 296
container[52].value= 255


container[53].bin= 36
container[53].i= 292
container[53].j= 168
container[53].angle= 180
container[53].value= 255


container[54].bin= 59
container[54].i= 293
container[54].j= 164
container[54].angle= 296
container[54].value= 255


container[55].bin= 63
container[55].i= 293
container[55].j= 165
container[55].angle= 315
container[55].value= 255


container[56].bin= 36
container[56].i= 293
container[56].j= 168
container[56].angle= 180
container[56].value= 255


container[57].bin= 63
container[57].i= 294
container[57].j= 165
container[57].angle= 315
container[57].value= 255


container[58].bin= 59
container[58].i= 294
container[58].j= 166
container[58].angle= 296
container[58].value= 255


container[59].bin= 54
container[59].i= 294
container[59].j= 167
container[59].angle= 270
container[59].value= 255


container[60].bin= 44
container[60].i= 294
container[60].j= 168
container[60].angle= 224
container[60].value= 255


