container[0].bin= 14
container[0].i= 679
container[0].j= 598
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 679
container[1].j= 599
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 680
container[2].j= 595
container[2].angle= 18
container[2].value= 255


container[3].bin= 14
container[3].i= 680
container[3].j= 596
container[3].angle= 71
container[3].value= 255


container[4].bin= 21
container[4].i= 680
container[4].j= 597
container[4].angle= 108
container[4].value= 255


container[5].bin= 8
container[5].i= 680
container[5].j= 598
container[5].angle= 44
container[5].value= 255


container[6].bin= 0
container[6].i= 681
container[6].j= 595
container[6].angle= 0
container[6].value= 255


container[7].bin= 39
container[7].i= 681
container[7].j= 597
container[7].angle= 198
container[7].value= 255


container[8].bin= 36
container[8].i= 681
container[8].j= 600
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 682
container[9].j= 595
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 682
container[10].j= 597
container[10].angle= 180
container[10].value= 255


container[11].bin= 39
container[11].i= 682
container[11].j= 600
container[11].angle= 198
container[11].value= 255


container[12].bin= 0
container[12].i= 683
container[12].j= 595
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 683
container[13].j= 597
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 684
container[14].j= 595
container[14].angle= 0
container[14].value= 255


container[15].bin= 0
container[15].i= 685
container[15].j= 595
container[15].angle= 0
container[15].value= 255


container[16].bin= 63
container[16].i= 686
container[16].j= 596
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 686
container[17].j= 597
container[17].angle= 224
container[17].value= 255


