container[0].bin= 8
container[0].i= 454
container[0].j= 150
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 454
container[1].j= 151
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 455
container[2].j= 149
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 456
container[3].j= 150
container[3].angle= 333
container[3].value= 255


container[4].bin= 0
container[4].i= 457
container[4].j= 150
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 457
container[5].j= 152
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 458
container[6].j= 150
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 458
container[7].j= 152
container[7].angle= 180
container[7].value= 255


container[8].bin= 63
container[8].i= 459
container[8].j= 150
container[8].angle= 315
container[8].value= 255


container[9].bin= 50
container[9].i= 459
container[9].j= 151
container[9].angle= 251
container[9].value= 255


