container[0].bin= 3
container[0].i= 499
container[0].j= 221
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 499
container[1].j= 222
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 499
container[2].j= 223
container[2].angle= 116
container[2].value= 255


container[3].bin= 21
container[3].i= 499
container[3].j= 224
container[3].angle= 108
container[3].value= 255


container[4].bin= 0
container[4].i= 500
container[4].j= 221
container[4].angle= 0
container[4].value= 255


container[5].bin= 68
container[5].i= 501
container[5].j= 221
container[5].angle= 341
container[5].value= 255


container[6].bin= 57
container[6].i= 501
container[6].j= 222
container[6].angle= 288
container[6].value= 255


container[7].bin= 48
container[7].i= 501
container[7].j= 223
container[7].angle= 243
container[7].value= 255


container[8].bin= 50
container[8].i= 501
container[8].j= 224
container[8].angle= 251
container[8].value= 255


