container[0].bin= 18
container[0].i= 213
container[0].j= 41
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 214
container[1].j= 40
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 214
container[2].j= 42
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 215
container[3].j= 40
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 215
container[4].j= 42
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 216
container[5].j= 40
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 216
container[6].j= 42
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 217
container[7].j= 40
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 217
container[8].j= 42
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 218
container[9].j= 40
container[9].angle= 315
container[9].value= 255


container[10].bin= 59
container[10].i= 218
container[10].j= 41
container[10].angle= 296
container[10].value= 255


container[11].bin= 23
container[11].i= 219
container[11].j= 45
container[11].angle= 116
container[11].value= 255


container[12].bin= 23
container[12].i= 220
container[12].j= 46
container[12].angle= 116
container[12].value= 255


container[13].bin= 27
container[13].i= 220
container[13].j= 47
container[13].angle= 135
container[13].value= 255


container[14].bin= 66
container[14].i= 221
container[14].j= 43
container[14].angle= 333
container[14].value= 255


container[15].bin= 27
container[15].i= 221
container[15].j= 47
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 221
container[16].j= 48
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 222
container[17].j= 43
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 222
container[18].j= 48
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 223
container[19].j= 44
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 223
container[20].j= 49
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 224
container[21].j= 44
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 224
container[22].j= 49
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 225
container[23].j= 44
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 225
container[24].j= 49
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 226
container[25].j= 44
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 226
container[26].j= 50
container[26].angle= 153
container[26].value= 255


container[27].bin= 0
container[27].i= 227
container[27].j= 44
container[27].angle= 0
container[27].value= 255


container[28].bin= 30
container[28].i= 227
container[28].j= 50
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 228
container[29].j= 44
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 228
container[30].j= 50
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 229
container[31].j= 44
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 229
container[32].j= 50
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 230
container[33].j= 44
container[33].angle= 0
container[33].value= 255


container[34].bin= 41
container[34].i= 230
container[34].j= 50
container[34].angle= 206
container[34].value= 255


container[35].bin= 0
container[35].i= 231
container[35].j= 44
container[35].angle= 0
container[35].value= 255


container[36].bin= 44
container[36].i= 231
container[36].j= 49
container[36].angle= 224
container[36].value= 255


container[37].bin= 44
container[37].i= 231
container[37].j= 50
container[37].angle= 224
container[37].value= 255


container[38].bin= 0
container[38].i= 232
container[38].j= 44
container[38].angle= 0
container[38].value= 255


container[39].bin= 41
container[39].i= 232
container[39].j= 49
container[39].angle= 206
container[39].value= 255


container[40].bin= 0
container[40].i= 233
container[40].j= 44
container[40].angle= 0
container[40].value= 255


container[41].bin= 41
container[41].i= 233
container[41].j= 48
container[41].angle= 206
container[41].value= 255


container[42].bin= 0
container[42].i= 234
container[42].j= 44
container[42].angle= 0
container[42].value= 255


container[43].bin= 41
container[43].i= 234
container[43].j= 48
container[43].angle= 206
container[43].value= 255


container[44].bin= 0
container[44].i= 235
container[44].j= 44
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 235
container[45].j= 47
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 236
container[46].j= 44
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 236
container[47].j= 47
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 237
container[48].j= 44
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 237
container[49].j= 47
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 238
container[50].j= 44
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 238
container[51].j= 47
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 239
container[52].j= 44
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 239
container[53].j= 48
container[53].angle= 153
container[53].value= 255


container[54].bin= 0
container[54].i= 240
container[54].j= 44
container[54].angle= 0
container[54].value= 255


container[55].bin= 30
container[55].i= 240
container[55].j= 48
container[55].angle= 153
container[55].value= 255


container[56].bin= 0
container[56].i= 241
container[56].j= 44
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 241
container[57].j= 48
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 242
container[58].j= 44
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 242
container[59].j= 48
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 243
container[60].j= 44
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 243
container[61].j= 48
container[61].angle= 180
container[61].value= 255


container[62].bin= 5
container[62].i= 244
container[62].j= 44
container[62].angle= 26
container[62].value= 255


container[63].bin= 36
container[63].i= 244
container[63].j= 48
container[63].angle= 180
container[63].value= 255


container[64].bin= 5
container[64].i= 245
container[64].j= 44
container[64].angle= 26
container[64].value= 255


container[65].bin= 36
container[65].i= 245
container[65].j= 48
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 246
container[66].j= 43
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 246
container[67].j= 48
container[67].angle= 180
container[67].value= 255


container[68].bin= 0
container[68].i= 247
container[68].j= 43
container[68].angle= 0
container[68].value= 255


container[69].bin= 36
container[69].i= 247
container[69].j= 48
container[69].angle= 180
container[69].value= 255


container[70].bin= 0
container[70].i= 248
container[70].j= 43
container[70].angle= 0
container[70].value= 255


container[71].bin= 30
container[71].i= 248
container[71].j= 49
container[71].angle= 153
container[71].value= 255


container[72].bin= 0
container[72].i= 249
container[72].j= 43
container[72].angle= 0
container[72].value= 255


container[73].bin= 30
container[73].i= 249
container[73].j= 49
container[73].angle= 153
container[73].value= 255


container[74].bin= 0
container[74].i= 250
container[74].j= 43
container[74].angle= 0
container[74].value= 255


container[75].bin= 30
container[75].i= 250
container[75].j= 50
container[75].angle= 153
container[75].value= 255


container[76].bin= 0
container[76].i= 251
container[76].j= 43
container[76].angle= 0
container[76].value= 255


container[77].bin= 30
container[77].i= 251
container[77].j= 50
container[77].angle= 153
container[77].value= 255


container[78].bin= 0
container[78].i= 252
container[78].j= 43
container[78].angle= 0
container[78].value= 255


container[79].bin= 30
container[79].i= 252
container[79].j= 51
container[79].angle= 153
container[79].value= 255


container[80].bin= 66
container[80].i= 253
container[80].j= 44
container[80].angle= 333
container[80].value= 255


container[81].bin= 30
container[81].i= 253
container[81].j= 51
container[81].angle= 153
container[81].value= 255


container[82].bin= 66
container[82].i= 254
container[82].j= 44
container[82].angle= 333
container[82].value= 255


container[83].bin= 36
container[83].i= 254
container[83].j= 51
container[83].angle= 180
container[83].value= 255


container[84].bin= 66
container[84].i= 255
container[84].j= 45
container[84].angle= 333
container[84].value= 255


container[85].bin= 30
container[85].i= 255
container[85].j= 52
container[85].angle= 153
container[85].value= 255


container[86].bin= 66
container[86].i= 256
container[86].j= 45
container[86].angle= 333
container[86].value= 255


container[87].bin= 36
container[87].i= 256
container[87].j= 52
container[87].angle= 180
container[87].value= 255


container[88].bin= 66
container[88].i= 257
container[88].j= 46
container[88].angle= 333
container[88].value= 255


container[89].bin= 41
container[89].i= 257
container[89].j= 52
container[89].angle= 206
container[89].value= 255


container[90].bin= 63
container[90].i= 258
container[90].j= 46
container[90].angle= 315
container[90].value= 255


container[91].bin= 63
container[91].i= 258
container[91].j= 47
container[91].angle= 315
container[91].value= 255


container[92].bin= 36
container[92].i= 258
container[92].j= 51
container[92].angle= 180
container[92].value= 255


container[93].bin= 63
container[93].i= 259
container[93].j= 47
container[93].angle= 315
container[93].value= 255


container[94].bin= 59
container[94].i= 259
container[94].j= 48
container[94].angle= 296
container[94].value= 255


container[95].bin= 54
container[95].i= 259
container[95].j= 49
container[95].angle= 270
container[95].value= 255


container[96].bin= 54
container[96].i= 259
container[96].j= 50
container[96].angle= 270
container[96].value= 255


container[97].bin= 44
container[97].i= 259
container[97].j= 51
container[97].angle= 224
container[97].value= 255


