container[0].bin= 18
container[0].i= 355
container[0].j= 504
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 356
container[1].j= 503
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 356
container[2].j= 505
container[2].angle= 161
container[2].value= 255


container[3].bin= 18
container[3].i= 357
container[3].j= 502
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 357
container[4].j= 503
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 357
container[5].j= 505
container[5].angle= 180
container[5].value= 255


container[6].bin= 8
container[6].i= 358
container[6].j= 501
container[6].angle= 44
container[6].value= 255


container[7].bin= 0
container[7].i= 359
container[7].j= 500
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 359
container[8].j= 504
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 360
container[9].j= 501
container[9].angle= 315
container[9].value= 255


container[10].bin= 54
container[10].i= 360
container[10].j= 502
container[10].angle= 270
container[10].value= 255


container[11].bin= 63
container[11].i= 361
container[11].j= 503
container[11].angle= 315
container[11].value= 255


container[12].bin= 36
container[12].i= 361
container[12].j= 505
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 362
container[13].j= 503
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 362
container[14].j= 505
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 363
container[15].j= 503
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 363
container[16].j= 505
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 364
container[17].j= 503
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 364
container[18].j= 505
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 365
container[19].j= 503
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 365
container[20].j= 505
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 366
container[21].j= 503
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 366
container[22].j= 505
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 367
container[23].j= 503
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 367
container[24].j= 505
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 368
container[25].j= 503
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 368
container[26].j= 505
container[26].angle= 180
container[26].value= 255


container[27].bin= 68
container[27].i= 369
container[27].j= 503
container[27].angle= 341
container[27].value= 255


container[28].bin= 54
container[28].i= 369
container[28].j= 504
container[28].angle= 270
container[28].value= 255


container[29].bin= 39
container[29].i= 369
container[29].j= 505
container[29].angle= 198
container[29].value= 255


