container[0].bin= 18
container[0].i= 132
container[0].j= 154
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 133
container[1].j= 153
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 133
container[2].j= 155
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 134
container[3].j= 153
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 134
container[4].j= 155
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 135
container[5].j= 153
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 135
container[6].j= 155
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 136
container[7].j= 153
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 136
container[8].j= 155
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 137
container[9].j= 153
container[9].angle= 26
container[9].value= 255


container[10].bin= 32
container[10].i= 137
container[10].j= 155
container[10].angle= 161
container[10].value= 255


container[11].bin= 66
container[11].i= 138
container[11].j= 153
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 138
container[12].j= 156
container[12].angle= 135
container[12].value= 255


container[13].bin= 66
container[13].i= 139
container[13].j= 153
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 139
container[14].j= 156
container[14].angle= 180
container[14].value= 255


container[15].bin= 5
container[15].i= 140
container[15].j= 153
container[15].angle= 26
container[15].value= 255


container[16].bin= 36
container[16].i= 140
container[16].j= 156
container[16].angle= 180
container[16].value= 255


container[17].bin= 68
container[17].i= 141
container[17].j= 153
container[17].angle= 341
container[17].value= 255


container[18].bin= 63
container[18].i= 142
container[18].j= 155
container[18].angle= 315
container[18].value= 255


container[19].bin= 36
container[19].i= 142
container[19].j= 157
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 143
container[20].j= 155
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 143
container[21].j= 157
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 144
container[22].j= 155
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 144
container[23].j= 157
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 145
container[24].j= 155
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 145
container[25].j= 157
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 146
container[26].j= 155
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 146
container[27].j= 157
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 147
container[28].j= 155
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 147
container[29].j= 157
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 148
container[30].j= 155
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 148
container[31].j= 157
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 149
container[32].j= 155
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 149
container[33].j= 157
container[33].angle= 180
container[33].value= 255


container[34].bin= 68
container[34].i= 150
container[34].j= 155
container[34].angle= 341
container[34].value= 255


container[35].bin= 54
container[35].i= 150
container[35].j= 156
container[35].angle= 270
container[35].value= 255


container[36].bin= 39
container[36].i= 150
container[36].j= 157
container[36].angle= 198
container[36].value= 255


