container[0].bin= 18
container[0].i= 140
container[0].j= 340
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 141
container[1].j= 338
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 141
container[2].j= 339
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 141
container[3].j= 341
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 142
container[4].j= 337
container[4].angle= 44
container[4].value= 255


container[5].bin= 8
container[5].i= 142
container[5].j= 338
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 142
container[6].j= 341
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 143
container[7].j= 337
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 143
container[8].j= 341
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 144
container[9].j= 336
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 144
container[10].j= 341
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 145
container[11].j= 336
container[11].angle= 0
container[11].value= 255


container[12].bin= 41
container[12].i= 145
container[12].j= 341
container[12].angle= 206
container[12].value= 255


container[13].bin= 0
container[13].i= 146
container[13].j= 336
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 146
container[14].j= 340
container[14].angle= 224
container[14].value= 255


container[15].bin= 44
container[15].i= 146
container[15].j= 341
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 147
container[16].j= 336
container[16].angle= 0
container[16].value= 255


container[17].bin= 41
container[17].i= 147
container[17].j= 340
container[17].angle= 206
container[17].value= 255


container[18].bin= 5
container[18].i= 148
container[18].j= 336
container[18].angle= 26
container[18].value= 255


container[19].bin= 36
container[19].i= 148
container[19].j= 339
container[19].angle= 180
container[19].value= 255


container[20].bin= 5
container[20].i= 149
container[20].j= 336
container[20].angle= 26
container[20].value= 255


container[21].bin= 36
container[21].i= 149
container[21].j= 339
container[21].angle= 180
container[21].value= 255


container[22].bin= 5
container[22].i= 150
container[22].j= 335
container[22].angle= 26
container[22].value= 255


container[23].bin= 36
container[23].i= 150
container[23].j= 339
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 151
container[24].j= 335
container[24].angle= 0
container[24].value= 255


container[25].bin= 41
container[25].i= 151
container[25].j= 339
container[25].angle= 206
container[25].value= 255


container[26].bin= 63
container[26].i= 152
container[26].j= 335
container[26].angle= 315
container[26].value= 255


container[27].bin= 59
container[27].i= 152
container[27].j= 336
container[27].angle= 296
container[27].value= 255


container[28].bin= 54
container[28].i= 152
container[28].j= 337
container[28].angle= 270
container[28].value= 255


container[29].bin= 48
container[29].i= 152
container[29].j= 338
container[29].angle= 243
container[29].value= 255


container[30].bin= 44
container[30].i= 152
container[30].j= 339
container[30].angle= 224
container[30].value= 255


