container[0].bin= 18
container[0].i= 522
container[0].j= 562
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 522
container[1].j= 563
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 522
container[2].j= 564
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 523
container[3].j= 561
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 523
container[4].j= 565
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 524
container[5].j= 560
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 524
container[6].j= 565
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 525
container[7].j= 561
container[7].angle= 315
container[7].value= 255


container[8].bin= 54
container[8].i= 525
container[8].j= 562
container[8].angle= 270
container[8].value= 255


container[9].bin= 27
container[9].i= 525
container[9].j= 566
container[9].angle= 135
container[9].value= 255


container[10].bin= 63
container[10].i= 526
container[10].j= 563
container[10].angle= 315
container[10].value= 255


container[11].bin= 27
container[11].i= 526
container[11].j= 567
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 527
container[12].j= 563
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 527
container[13].j= 567
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 528
container[14].j= 563
container[14].angle= 0
container[14].value= 255


container[15].bin= 44
container[15].i= 528
container[15].j= 567
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 529
container[16].j= 563
container[16].angle= 0
container[16].value= 255


container[17].bin= 44
container[17].i= 529
container[17].j= 566
container[17].angle= 224
container[17].value= 255


container[18].bin= 0
container[18].i= 530
container[18].j= 563
container[18].angle= 0
container[18].value= 255


container[19].bin= 63
container[19].i= 531
container[19].j= 564
container[19].angle= 315
container[19].value= 255


container[20].bin= 44
container[20].i= 531
container[20].j= 565
container[20].angle= 224
container[20].value= 255


