container[0].bin= 8
container[0].i= 50
container[0].j= 129
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 50
container[1].j= 130
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 50
container[2].j= 131
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 51
container[3].j= 129
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 51
container[4].j= 131
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 51
container[5].j= 132
container[5].angle= 135
container[5].value= 255


container[6].bin= 66
container[6].i= 52
container[6].j= 129
container[6].angle= 333
container[6].value= 255


container[7].bin= 27
container[7].i= 52
container[7].j= 132
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 52
container[8].j= 133
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 53
container[9].j= 129
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 53
container[10].j= 133
container[10].angle= 135
container[10].value= 255


container[11].bin= 23
container[11].i= 53
container[11].j= 134
container[11].angle= 116
container[11].value= 255


container[12].bin= 18
container[12].i= 53
container[12].j= 135
container[12].angle= 90
container[12].value= 255


container[13].bin= 66
container[13].i= 54
container[13].j= 130
container[13].angle= 333
container[13].value= 255


container[14].bin= 23
container[14].i= 54
container[14].j= 136
container[14].angle= 116
container[14].value= 255


container[15].bin= 27
container[15].i= 54
container[15].j= 137
container[15].angle= 135
container[15].value= 255


container[16].bin= 63
container[16].i= 55
container[16].j= 130
container[16].angle= 315
container[16].value= 255


container[17].bin= 63
container[17].i= 55
container[17].j= 131
container[17].angle= 315
container[17].value= 255


container[18].bin= 27
container[18].i= 55
container[18].j= 137
container[18].angle= 135
container[18].value= 255


container[19].bin= 27
container[19].i= 55
container[19].j= 138
container[19].angle= 135
container[19].value= 255


container[20].bin= 66
container[20].i= 56
container[20].j= 131
container[20].angle= 333
container[20].value= 255


container[21].bin= 27
container[21].i= 56
container[21].j= 138
container[21].angle= 135
container[21].value= 255


container[22].bin= 27
container[22].i= 56
container[22].j= 139
container[22].angle= 135
container[22].value= 255


container[23].bin= 66
container[23].i= 57
container[23].j= 132
container[23].angle= 333
container[23].value= 255


container[24].bin= 30
container[24].i= 57
container[24].j= 139
container[24].angle= 153
container[24].value= 255


container[25].bin= 63
container[25].i= 58
container[25].j= 132
container[25].angle= 315
container[25].value= 255


container[26].bin= 63
container[26].i= 58
container[26].j= 133
container[26].angle= 315
container[26].value= 255


container[27].bin= 30
container[27].i= 58
container[27].j= 140
container[27].angle= 153
container[27].value= 255


container[28].bin= 63
container[28].i= 59
container[28].j= 133
container[28].angle= 315
container[28].value= 255


container[29].bin= 63
container[29].i= 59
container[29].j= 134
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 59
container[30].j= 140
container[30].angle= 135
container[30].value= 255


container[31].bin= 27
container[31].i= 59
container[31].j= 141
container[31].angle= 135
container[31].value= 255


container[32].bin= 66
container[32].i= 60
container[32].j= 134
container[32].angle= 333
container[32].value= 255


container[33].bin= 30
container[33].i= 60
container[33].j= 141
container[33].angle= 153
container[33].value= 255


container[34].bin= 66
container[34].i= 61
container[34].j= 135
container[34].angle= 333
container[34].value= 255


container[35].bin= 30
container[35].i= 61
container[35].j= 142
container[35].angle= 153
container[35].value= 255


container[36].bin= 63
container[36].i= 62
container[36].j= 135
container[36].angle= 315
container[36].value= 255


container[37].bin= 63
container[37].i= 62
container[37].j= 136
container[37].angle= 315
container[37].value= 255


container[38].bin= 30
container[38].i= 62
container[38].j= 142
container[38].angle= 153
container[38].value= 255


container[39].bin= 66
container[39].i= 63
container[39].j= 136
container[39].angle= 333
container[39].value= 255


container[40].bin= 30
container[40].i= 63
container[40].j= 143
container[40].angle= 153
container[40].value= 255


container[41].bin= 0
container[41].i= 64
container[41].j= 136
container[41].angle= 0
container[41].value= 255


container[42].bin= 30
container[42].i= 64
container[42].j= 143
container[42].angle= 153
container[42].value= 255


container[43].bin= 66
container[43].i= 65
container[43].j= 137
container[43].angle= 333
container[43].value= 255


container[44].bin= 30
container[44].i= 65
container[44].j= 144
container[44].angle= 153
container[44].value= 255


container[45].bin= 66
container[45].i= 66
container[45].j= 137
container[45].angle= 333
container[45].value= 255


container[46].bin= 30
container[46].i= 66
container[46].j= 144
container[46].angle= 153
container[46].value= 255


container[47].bin= 0
container[47].i= 67
container[47].j= 137
container[47].angle= 0
container[47].value= 255


container[48].bin= 30
container[48].i= 67
container[48].j= 145
container[48].angle= 153
container[48].value= 255


container[49].bin= 0
container[49].i= 68
container[49].j= 137
container[49].angle= 0
container[49].value= 255


container[50].bin= 30
container[50].i= 68
container[50].j= 145
container[50].angle= 153
container[50].value= 255


container[51].bin= 66
container[51].i= 69
container[51].j= 138
container[51].angle= 333
container[51].value= 255


container[52].bin= 30
container[52].i= 69
container[52].j= 146
container[52].angle= 153
container[52].value= 255


container[53].bin= 66
container[53].i= 70
container[53].j= 138
container[53].angle= 333
container[53].value= 255


container[54].bin= 30
container[54].i= 70
container[54].j= 146
container[54].angle= 153
container[54].value= 255


container[55].bin= 66
container[55].i= 71
container[55].j= 139
container[55].angle= 333
container[55].value= 255


container[56].bin= 30
container[56].i= 71
container[56].j= 147
container[56].angle= 153
container[56].value= 255


container[57].bin= 66
container[57].i= 72
container[57].j= 139
container[57].angle= 333
container[57].value= 255


container[58].bin= 30
container[58].i= 72
container[58].j= 147
container[58].angle= 153
container[58].value= 255


container[59].bin= 66
container[59].i= 73
container[59].j= 140
container[59].angle= 333
container[59].value= 255


container[60].bin= 36
container[60].i= 73
container[60].j= 147
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 74
container[61].j= 140
container[61].angle= 315
container[61].value= 255


container[62].bin= 63
container[62].i= 74
container[62].j= 141
container[62].angle= 315
container[62].value= 255


container[63].bin= 27
container[63].i= 74
container[63].j= 148
container[63].angle= 135
container[63].value= 255


container[64].bin= 63
container[64].i= 75
container[64].j= 141
container[64].angle= 315
container[64].value= 255


container[65].bin= 59
container[65].i= 75
container[65].j= 142
container[65].angle= 296
container[65].value= 255


container[66].bin= 48
container[66].i= 75
container[66].j= 143
container[66].angle= 243
container[66].value= 255


container[67].bin= 54
container[67].i= 75
container[67].j= 144
container[67].angle= 270
container[67].value= 255


container[68].bin= 63
container[68].i= 75
container[68].j= 145
container[68].angle= 315
container[68].value= 255


container[69].bin= 27
container[69].i= 75
container[69].j= 149
container[69].angle= 135
container[69].value= 255


container[70].bin= 63
container[70].i= 76
container[70].j= 145
container[70].angle= 315
container[70].value= 255


container[71].bin= 63
container[71].i= 76
container[71].j= 146
container[71].angle= 315
container[71].value= 255


container[72].bin= 30
container[72].i= 76
container[72].j= 150
container[72].angle= 153
container[72].value= 255


container[73].bin= 63
container[73].i= 77
container[73].j= 146
container[73].angle= 315
container[73].value= 255


container[74].bin= 63
container[74].i= 77
container[74].j= 147
container[74].angle= 315
container[74].value= 255


container[75].bin= 27
container[75].i= 77
container[75].j= 150
container[75].angle= 135
container[75].value= 255


container[76].bin= 23
container[76].i= 77
container[76].j= 151
container[76].angle= 116
container[76].value= 255


container[77].bin= 66
container[77].i= 78
container[77].j= 147
container[77].angle= 333
container[77].value= 255


container[78].bin= 23
container[78].i= 78
container[78].j= 152
container[78].angle= 116
container[78].value= 255


container[79].bin= 27
container[79].i= 78
container[79].j= 153
container[79].angle= 135
container[79].value= 255


container[80].bin= 0
container[80].i= 79
container[80].j= 147
container[80].angle= 0
container[80].value= 255


container[81].bin= 27
container[81].i= 79
container[81].j= 153
container[81].angle= 135
container[81].value= 255


container[82].bin= 27
container[82].i= 79
container[82].j= 154
container[82].angle= 135
container[82].value= 255


container[83].bin= 66
container[83].i= 80
container[83].j= 148
container[83].angle= 333
container[83].value= 255


container[84].bin= 27
container[84].i= 80
container[84].j= 154
container[84].angle= 135
container[84].value= 255


container[85].bin= 23
container[85].i= 80
container[85].j= 155
container[85].angle= 116
container[85].value= 255


container[86].bin= 63
container[86].i= 81
container[86].j= 148
container[86].angle= 315
container[86].value= 255


container[87].bin= 59
container[87].i= 81
container[87].j= 149
container[87].angle= 296
container[87].value= 255


container[88].bin= 23
container[88].i= 81
container[88].j= 156
container[88].angle= 116
container[88].value= 255


container[89].bin= 27
container[89].i= 81
container[89].j= 157
container[89].angle= 135
container[89].value= 255


container[90].bin= 59
container[90].i= 82
container[90].j= 150
container[90].angle= 296
container[90].value= 255


container[91].bin= 63
container[91].i= 82
container[91].j= 151
container[91].angle= 315
container[91].value= 255


container[92].bin= 27
container[92].i= 82
container[92].j= 157
container[92].angle= 135
container[92].value= 255


container[93].bin= 27
container[93].i= 82
container[93].j= 158
container[93].angle= 135
container[93].value= 255


container[94].bin= 63
container[94].i= 83
container[94].j= 151
container[94].angle= 315
container[94].value= 255


container[95].bin= 63
container[95].i= 83
container[95].j= 152
container[95].angle= 315
container[95].value= 255


container[96].bin= 27
container[96].i= 83
container[96].j= 158
container[96].angle= 135
container[96].value= 255


container[97].bin= 27
container[97].i= 83
container[97].j= 159
container[97].angle= 135
container[97].value= 255


container[98].bin= 63
container[98].i= 84
container[98].j= 152
container[98].angle= 315
container[98].value= 255


container[99].bin= 63
container[99].i= 84
container[99].j= 153
container[99].angle= 315
container[99].value= 255


container[100].bin= 30
container[100].i= 84
container[100].j= 159
container[100].angle= 153
container[100].value= 255


container[101].bin= 63
container[101].i= 85
container[101].j= 153
container[101].angle= 315
container[101].value= 255


container[102].bin= 63
container[102].i= 85
container[102].j= 154
container[102].angle= 315
container[102].value= 255


container[103].bin= 30
container[103].i= 85
container[103].j= 160
container[103].angle= 153
container[103].value= 255


container[104].bin= 63
container[104].i= 86
container[104].j= 154
container[104].angle= 315
container[104].value= 255


container[105].bin= 59
container[105].i= 86
container[105].j= 155
container[105].angle= 296
container[105].value= 255


container[106].bin= 54
container[106].i= 86
container[106].j= 156
container[106].angle= 270
container[106].value= 255


container[107].bin= 27
container[107].i= 86
container[107].j= 160
container[107].angle= 135
container[107].value= 255


container[108].bin= 27
container[108].i= 86
container[108].j= 161
container[108].angle= 135
container[108].value= 255


container[109].bin= 63
container[109].i= 87
container[109].j= 157
container[109].angle= 315
container[109].value= 255


container[110].bin= 30
container[110].i= 87
container[110].j= 161
container[110].angle= 153
container[110].value= 255


container[111].bin= 66
container[111].i= 88
container[111].j= 158
container[111].angle= 333
container[111].value= 255


container[112].bin= 36
container[112].i= 88
container[112].j= 161
container[112].angle= 180
container[112].value= 255


container[113].bin= 63
container[113].i= 89
container[113].j= 158
container[113].angle= 315
container[113].value= 255


container[114].bin= 63
container[114].i= 89
container[114].j= 159
container[114].angle= 315
container[114].value= 255


container[115].bin= 30
container[115].i= 89
container[115].j= 162
container[115].angle= 153
container[115].value= 255


container[116].bin= 66
container[116].i= 90
container[116].j= 159
container[116].angle= 333
container[116].value= 255


container[117].bin= 30
container[117].i= 90
container[117].j= 162
container[117].angle= 153
container[117].value= 255


container[118].bin= 66
container[118].i= 91
container[118].j= 160
container[118].angle= 333
container[118].value= 255


container[119].bin= 36
container[119].i= 91
container[119].j= 162
container[119].angle= 180
container[119].value= 255


container[120].bin= 63
container[120].i= 92
container[120].j= 160
container[120].angle= 315
container[120].value= 255


container[121].bin= 59
container[121].i= 92
container[121].j= 161
container[121].angle= 296
container[121].value= 255


container[122].bin= 44
container[122].i= 92
container[122].j= 162
container[122].angle= 224
container[122].value= 255


