container[0].bin= 8
container[0].i= 93
container[0].j= 335
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 93
container[1].j= 336
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 93
container[2].j= 337
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 94
container[3].j= 334
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 94
container[4].j= 337
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 95
container[5].j= 334
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 95
container[6].j= 338
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 96
container[7].j= 334
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 96
container[8].j= 338
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 97
container[9].j= 335
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 97
container[10].j= 339
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 98
container[11].j= 335
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 98
container[12].j= 339
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 99
container[13].j= 335
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 99
container[14].j= 339
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 100
container[15].j= 335
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 100
container[16].j= 340
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 101
container[17].j= 335
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 101
container[18].j= 340
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 102
container[19].j= 335
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 102
container[20].j= 340
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 103
container[21].j= 336
container[21].angle= 333
container[21].value= 255


container[22].bin= 36
container[22].i= 103
container[22].j= 340
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 104
container[23].j= 336
container[23].angle= 315
container[23].value= 255


container[24].bin= 63
container[24].i= 104
container[24].j= 337
container[24].angle= 315
container[24].value= 255


container[25].bin= 36
container[25].i= 104
container[25].j= 340
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 105
container[26].j= 337
container[26].angle= 315
container[26].value= 255


container[27].bin= 59
container[27].i= 105
container[27].j= 338
container[27].angle= 296
container[27].value= 255


container[28].bin= 54
container[28].i= 105
container[28].j= 339
container[28].angle= 270
container[28].value= 255


container[29].bin= 44
container[29].i= 105
container[29].j= 340
container[29].angle= 224
container[29].value= 255


