container[0].bin= 8
container[0].i= 647
container[0].j= 524
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 647
container[1].j= 525
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 648
container[2].j= 523
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 649
container[3].j= 524
container[3].angle= 333
container[3].value= 255


container[4].bin= 68
container[4].i= 650
container[4].j= 524
container[4].angle= 341
container[4].value= 255


container[5].bin= 0
container[5].i= 651
container[5].j= 523
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 652
container[6].j= 524
container[6].angle= 315
container[6].value= 255


