container[0].bin= 8
container[0].i= 423
container[0].j= 145
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 423
container[1].j= 146
container[1].angle= 108
container[1].value= 255


container[2].bin= 5
container[2].i= 424
container[2].j= 145
container[2].angle= 26
container[2].value= 255


container[3].bin= 0
container[3].i= 425
container[3].j= 144
container[3].angle= 0
container[3].value= 255


container[4].bin= 63
container[4].i= 426
container[4].j= 145
container[4].angle= 315
container[4].value= 255


container[5].bin= 44
container[5].i= 426
container[5].j= 146
container[5].angle= 224
container[5].value= 255


