container[0].bin= 18
container[0].i= 27
container[0].j= 536
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 27
container[1].j= 537
container[1].angle= 90
container[1].value= 255


container[2].bin= 21
container[2].i= 27
container[2].j= 538
container[2].angle= 108
container[2].value= 255


container[3].bin= 8
container[3].i= 28
container[3].j= 535
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 28
container[4].j= 539
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 29
container[5].j= 534
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 29
container[6].j= 539
container[6].angle= 153
container[6].value= 255


container[7].bin= 63
container[7].i= 30
container[7].j= 535
container[7].angle= 315
container[7].value= 255


container[8].bin= 36
container[8].i= 30
container[8].j= 539
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 31
container[9].j= 536
container[9].angle= 315
container[9].value= 255


container[10].bin= 32
container[10].i= 31
container[10].j= 539
container[10].angle= 161
container[10].value= 255


container[11].bin= 21
container[11].i= 31
container[11].j= 541
container[11].angle= 108
container[11].value= 255


container[12].bin= 0
container[12].i= 32
container[12].j= 536
container[12].angle= 0
container[12].value= 255


container[13].bin= 32
container[13].i= 32
container[13].j= 541
container[13].angle= 161
container[13].value= 255


container[14].bin= 63
container[14].i= 33
container[14].j= 537
container[14].angle= 315
container[14].value= 255


container[15].bin= 48
container[15].i= 33
container[15].j= 538
container[15].angle= 243
container[15].value= 255


container[16].bin= 57
container[16].i= 33
container[16].j= 539
container[16].angle= 288
container[16].value= 255


container[17].bin= 27
container[17].i= 33
container[17].j= 542
container[17].angle= 135
container[17].value= 255


container[18].bin= 18
container[18].i= 33
container[18].j= 543
container[18].angle= 90
container[18].value= 255


container[19].bin= 27
container[19].i= 34
container[19].j= 544
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 35
container[20].j= 539
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 35
container[21].j= 544
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 36
container[22].j= 540
container[22].angle= 315
container[22].value= 255


container[23].bin= 54
container[23].i= 36
container[23].j= 541
container[23].angle= 270
container[23].value= 255


container[24].bin= 36
container[24].i= 36
container[24].j= 544
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 37
container[25].j= 542
container[25].angle= 315
container[25].value= 255


container[26].bin= 0
container[26].i= 38
container[26].j= 542
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 39
container[27].j= 542
container[27].angle= 0
container[27].value= 255


container[28].bin= 41
container[28].i= 39
container[28].j= 544
container[28].angle= 206
container[28].value= 255


container[29].bin= 0
container[29].i= 40
container[29].j= 542
container[29].angle= 0
container[29].value= 255


container[30].bin= 41
container[30].i= 40
container[30].j= 544
container[30].angle= 206
container[30].value= 255


container[31].bin= 0
container[31].i= 41
container[31].j= 542
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 41
container[32].j= 544
container[32].angle= 180
container[32].value= 255


container[33].bin= 68
container[33].i= 42
container[33].j= 542
container[33].angle= 341
container[33].value= 255


container[34].bin= 54
container[34].i= 42
container[34].j= 543
container[34].angle= 270
container[34].value= 255


container[35].bin= 39
container[35].i= 42
container[35].j= 544
container[35].angle= 198
container[35].value= 255


