container[0].bin= 18
container[0].i= 586
container[0].j= 514
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 586
container[1].j= 515
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 586
container[2].j= 516
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 586
container[3].j= 517
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 586
container[4].j= 518
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 586
container[5].j= 519
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 587
container[6].j= 513
container[6].angle= 44
container[6].value= 255


container[7].bin= 27
container[7].i= 587
container[7].j= 520
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 588
container[8].j= 512
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 588
container[9].j= 520
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 589
container[10].j= 513
container[10].angle= 333
container[10].value= 255


container[11].bin= 54
container[11].i= 589
container[11].j= 519
container[11].angle= 270
container[11].value= 255


container[12].bin= 18
container[12].i= 589
container[12].j= 522
container[12].angle= 90
container[12].value= 255


container[13].bin= 66
container[13].i= 590
container[13].j= 513
container[13].angle= 333
container[13].value= 255


container[14].bin= 44
container[14].i= 590
container[14].j= 518
container[14].angle= 224
container[14].value= 255


container[15].bin= 27
container[15].i= 590
container[15].j= 523
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 591
container[16].j= 513
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 591
container[17].j= 517
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 591
container[18].j= 520
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 591
container[19].j= 523
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 592
container[20].j= 513
container[20].angle= 0
container[20].value= 255


container[21].bin= 44
container[21].i= 592
container[21].j= 517
container[21].angle= 224
container[21].value= 255


container[22].bin= 63
container[22].i= 592
container[22].j= 521
container[22].angle= 315
container[22].value= 255


container[23].bin= 57
container[23].i= 592
container[23].j= 522
container[23].angle= 288
container[23].value= 255


container[24].bin= 27
container[24].i= 592
container[24].j= 524
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 593
container[25].j= 513
container[25].angle= 0
container[25].value= 255


container[26].bin= 44
container[26].i= 593
container[26].j= 516
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 593
container[27].j= 520
container[27].angle= 0
container[27].value= 255


container[28].bin= 27
container[28].i= 593
container[28].j= 525
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 594
container[29].j= 513
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 594
container[30].j= 516
container[30].angle= 153
container[30].value= 255


container[31].bin= 0
container[31].i= 594
container[31].j= 520
container[31].angle= 0
container[31].value= 255


container[32].bin= 3
container[32].i= 594
container[32].j= 523
container[32].angle= 18
container[32].value= 255


container[33].bin= 36
container[33].i= 594
container[33].j= 525
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 595
container[34].j= 514
container[34].angle= 315
container[34].value= 255


container[35].bin= 63
container[35].i= 595
container[35].j= 521
container[35].angle= 315
container[35].value= 255


container[36].bin= 57
container[36].i= 595
container[36].j= 524
container[36].angle= 288
container[36].value= 255


container[37].bin= 44
container[37].i= 595
container[37].j= 525
container[37].angle= 224
container[37].value= 255


container[38].bin= 57
container[38].i= 596
container[38].j= 522
container[38].angle= 288
container[38].value= 255


container[39].bin= 54
container[39].i= 596
container[39].j= 523
container[39].angle= 270
container[39].value= 255


