container[0].bin= 18
container[0].i= 138
container[0].j= 8
container[0].angle= 90
container[0].value= 255


container[1].bin= 12
container[1].i= 139
container[1].j= 6
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 139
container[2].j= 7
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 139
container[3].j= 9
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 140
container[4].j= 5
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 140
container[5].j= 9
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 141
container[6].j= 4
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 141
container[7].j= 9
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 142
container[8].j= 4
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 142
container[9].j= 9
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 143
container[10].j= 4
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 143
container[11].j= 10
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 144
container[12].j= 4
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 144
container[13].j= 10
container[13].angle= 153
container[13].value= 255


container[14].bin= 66
container[14].i= 145
container[14].j= 5
container[14].angle= 333
container[14].value= 255


container[15].bin= 36
container[15].i= 145
container[15].j= 10
container[15].angle= 180
container[15].value= 255


container[16].bin= 66
container[16].i= 146
container[16].j= 5
container[16].angle= 333
container[16].value= 255


container[17].bin= 36
container[17].i= 146
container[17].j= 10
container[17].angle= 180
container[17].value= 255


container[18].bin= 66
container[18].i= 147
container[18].j= 6
container[18].angle= 333
container[18].value= 255


container[19].bin= 36
container[19].i= 147
container[19].j= 10
container[19].angle= 180
container[19].value= 255


container[20].bin= 66
container[20].i= 148
container[20].j= 6
container[20].angle= 333
container[20].value= 255


container[21].bin= 30
container[21].i= 148
container[21].j= 11
container[21].angle= 153
container[21].value= 255


container[22].bin= 66
container[22].i= 149
container[22].j= 7
container[22].angle= 333
container[22].value= 255


container[23].bin= 27
container[23].i= 149
container[23].j= 11
container[23].angle= 135
container[23].value= 255


container[24].bin= 27
container[24].i= 149
container[24].j= 12
container[24].angle= 135
container[24].value= 255


container[25].bin= 66
container[25].i= 150
container[25].j= 7
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 150
container[26].j= 12
container[26].angle= 153
container[26].value= 255


container[27].bin= 63
container[27].i= 151
container[27].j= 8
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 151
container[28].j= 13
container[28].angle= 153
container[28].value= 255


container[29].bin= 59
container[29].i= 152
container[29].j= 9
container[29].angle= 296
container[29].value= 255


container[30].bin= 59
container[30].i= 152
container[30].j= 10
container[30].angle= 296
container[30].value= 255


container[31].bin= 27
container[31].i= 152
container[31].j= 14
container[31].angle= 135
container[31].value= 255


container[32].bin= 59
container[32].i= 153
container[32].j= 11
container[32].angle= 296
container[32].value= 255


container[33].bin= 27
container[33].i= 153
container[33].j= 15
container[33].angle= 135
container[33].value= 255


container[34].bin= 63
container[34].i= 154
container[34].j= 12
container[34].angle= 315
container[34].value= 255


container[35].bin= 32
container[35].i= 154
container[35].j= 15
container[35].angle= 161
container[35].value= 255


container[36].bin= 63
container[36].i= 155
container[36].j= 14
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 155
container[37].j= 16
container[37].angle= 153
container[37].value= 255


container[38].bin= 68
container[38].i= 156
container[38].j= 14
container[38].angle= 341
container[38].value= 255


container[39].bin= 27
container[39].i= 156
container[39].j= 17
container[39].angle= 135
container[39].value= 255


container[40].bin= 63
container[40].i= 157
container[40].j= 15
container[40].angle= 315
container[40].value= 255


container[41].bin= 21
container[41].i= 157
container[41].j= 18
container[41].angle= 108
container[41].value= 255


container[42].bin= 63
container[42].i= 160
container[42].j= 18
container[42].angle= 315
container[42].value= 255


