container[0].bin= 18
container[0].i= 201
container[0].j= 167
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 202
container[1].j= 166
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 202
container[2].j= 168
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 203
container[3].j= 166
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 203
container[4].j= 168
container[4].angle= 135
container[4].value= 255


container[5].bin= 21
container[5].i= 203
container[5].j= 169
container[5].angle= 108
container[5].value= 255


container[6].bin= 68
container[6].i= 204
container[6].j= 166
container[6].angle= 341
container[6].value= 255


container[7].bin= 54
container[7].i= 205
container[7].j= 168
container[7].angle= 270
container[7].value= 255


container[8].bin= 50
container[8].i= 205
container[8].j= 169
container[8].angle= 251
container[8].value= 255


