container[0].bin= 18
container[0].i= 586
container[0].j= 170
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 587
container[1].j= 169
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 587
container[2].j= 171
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 587
container[3].j= 172
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 588
container[4].j= 168
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 588
container[5].j= 172
container[5].angle= 153
container[5].value= 255


container[6].bin= 63
container[6].i= 589
container[6].j= 169
container[6].angle= 315
container[6].value= 255


container[7].bin= 27
container[7].i= 589
container[7].j= 173
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 589
container[8].j= 174
container[8].angle= 90
container[8].value= 255


container[9].bin= 63
container[9].i= 590
container[9].j= 170
container[9].angle= 315
container[9].value= 255


container[10].bin= 27
container[10].i= 590
container[10].j= 175
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 591
container[11].j= 170
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 591
container[12].j= 175
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 592
container[13].j= 171
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 592
container[14].j= 172
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 592
container[15].j= 173
container[15].angle= 270
container[15].value= 255


container[16].bin= 27
container[16].i= 592
container[16].j= 176
container[16].angle= 135
container[16].value= 255


container[17].bin= 63
container[17].i= 593
container[17].j= 174
container[17].angle= 315
container[17].value= 255


container[18].bin= 27
container[18].i= 593
container[18].j= 177
container[18].angle= 135
container[18].value= 255


container[19].bin= 5
container[19].i= 594
container[19].j= 174
container[19].angle= 26
container[19].value= 255


container[20].bin= 36
container[20].i= 594
container[20].j= 177
container[20].angle= 180
container[20].value= 255


container[21].bin= 68
container[21].i= 595
container[21].j= 174
container[21].angle= 341
container[21].value= 255


container[22].bin= 54
container[22].i= 595
container[22].j= 176
container[22].angle= 270
container[22].value= 255


container[23].bin= 44
container[23].i= 595
container[23].j= 177
container[23].angle= 224
container[23].value= 255


