container[0].bin= 18
container[0].i= 366
container[0].j= 159
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 367
container[1].j= 158
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 367
container[2].j= 160
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 368
container[3].j= 158
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 368
container[4].j= 160
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 369
container[5].j= 158
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 369
container[6].j= 160
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 369
container[7].j= 161
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 369
container[8].j= 162
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 369
container[9].j= 163
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 369
container[10].j= 164
container[10].angle= 90
container[10].value= 255


container[11].bin= 0
container[11].i= 370
container[11].j= 158
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 370
container[12].j= 165
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 371
container[13].j= 158
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 371
container[14].j= 165
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 372
container[15].j= 158
container[15].angle= 0
container[15].value= 255


container[16].bin= 54
container[16].i= 372
container[16].j= 163
container[16].angle= 270
container[16].value= 255


container[17].bin= 0
container[17].i= 373
container[17].j= 158
container[17].angle= 0
container[17].value= 255


container[18].bin= 44
container[18].i= 373
container[18].j= 162
container[18].angle= 224
container[18].value= 255


container[19].bin= 59
container[19].i= 373
container[19].j= 164
container[19].angle= 296
container[19].value= 255


container[20].bin= 0
container[20].i= 374
container[20].j= 158
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 374
container[21].j= 161
container[21].angle= 180
container[21].value= 255


container[22].bin= 5
container[22].i= 375
container[22].j= 158
container[22].angle= 26
container[22].value= 255


container[23].bin= 44
container[23].i= 375
container[23].j= 161
container[23].angle= 224
container[23].value= 255


container[24].bin= 5
container[24].i= 376
container[24].j= 158
container[24].angle= 26
container[24].value= 255


container[25].bin= 44
container[25].i= 376
container[25].j= 160
container[25].angle= 224
container[25].value= 255


container[26].bin= 0
container[26].i= 377
container[26].j= 157
container[26].angle= 0
container[26].value= 255


container[27].bin= 44
container[27].i= 378
container[27].j= 159
container[27].angle= 224
container[27].value= 255


container[28].bin= 8
container[28].i= 379
container[28].j= 156
container[28].angle= 44
container[28].value= 255


container[29].bin= 0
container[29].i= 380
container[29].j= 155
container[29].angle= 0
container[29].value= 255


container[30].bin= 18
container[30].i= 381
container[30].j= 154
container[30].angle= 90
container[30].value= 255


container[31].bin= 8
container[31].i= 381
container[31].j= 155
container[31].angle= 44
container[31].value= 255


container[32].bin= 41
container[32].i= 381
container[32].j= 157
container[32].angle= 206
container[32].value= 255


container[33].bin= 8
container[33].i= 382
container[33].j= 153
container[33].angle= 44
container[33].value= 255


container[34].bin= 41
container[34].i= 382
container[34].j= 157
container[34].angle= 206
container[34].value= 255


container[35].bin= 0
container[35].i= 383
container[35].j= 152
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 383
container[36].j= 156
container[36].angle= 180
container[36].value= 255


container[37].bin= 18
container[37].i= 384
container[37].j= 143
container[37].angle= 90
container[37].value= 255


container[38].bin= 3
container[38].i= 384
container[38].j= 152
container[38].angle= 18
container[38].value= 255


container[39].bin= 63
container[39].i= 384
container[39].j= 153
container[39].angle= 315
container[39].value= 255


container[40].bin= 54
container[40].i= 384
container[40].j= 154
container[40].angle= 270
container[40].value= 255


container[41].bin= 54
container[41].i= 384
container[41].j= 155
container[41].angle= 270
container[41].value= 255


container[42].bin= 44
container[42].i= 384
container[42].j= 156
container[42].angle= 224
container[42].value= 255


container[43].bin= 8
container[43].i= 385
container[43].j= 142
container[43].angle= 44
container[43].value= 255


container[44].bin= 27
container[44].i= 385
container[44].j= 144
container[44].angle= 135
container[44].value= 255


container[45].bin= 8
container[45].i= 385
container[45].j= 151
container[45].angle= 44
container[45].value= 255


container[46].bin= 0
container[46].i= 386
container[46].j= 141
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 386
container[47].j= 144
container[47].angle= 180
container[47].value= 255


container[48].bin= 63
container[48].i= 387
container[48].j= 142
container[48].angle= 315
container[48].value= 255


container[49].bin= 54
container[49].i= 387
container[49].j= 143
container[49].angle= 270
container[49].value= 255


container[50].bin= 18
container[50].i= 387
container[50].j= 146
container[50].angle= 90
container[50].value= 255


container[51].bin= 18
container[51].i= 387
container[51].j= 147
container[51].angle= 90
container[51].value= 255


container[52].bin= 0
container[52].i= 387
container[52].j= 150
container[52].angle= 0
container[52].value= 255


container[53].bin= 27
container[53].i= 388
container[53].j= 148
container[53].angle= 135
container[53].value= 255


container[54].bin= 5
container[54].i= 388
container[54].j= 150
container[54].angle= 26
container[54].value= 255


container[55].bin= 41
container[55].i= 388
container[55].j= 152
container[55].angle= 206
container[55].value= 255


container[56].bin= 0
container[56].i= 389
container[56].j= 144
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 389
container[57].j= 148
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 389
container[58].j= 150
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 389
container[59].j= 152
container[59].angle= 180
container[59].value= 255


container[60].bin= 18
container[60].i= 390
container[60].j= 143
container[60].angle= 90
container[60].value= 255


container[61].bin= 54
container[61].i= 390
container[61].j= 146
container[61].angle= 270
container[61].value= 255


container[62].bin= 30
container[62].i= 390
container[62].j= 152
container[62].angle= 153
container[62].value= 255


container[63].bin= 8
container[63].i= 391
container[63].j= 142
container[63].angle= 44
container[63].value= 255


container[64].bin= 63
container[64].i= 391
container[64].j= 147
container[64].angle= 315
container[64].value= 255


container[65].bin= 30
container[65].i= 391
container[65].j= 152
container[65].angle= 153
container[65].value= 255


container[66].bin= 0
container[66].i= 392
container[66].j= 141
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 392
container[67].j= 144
container[67].angle= 180
container[67].value= 255


container[68].bin= 68
container[68].i= 392
container[68].j= 147
container[68].angle= 341
container[68].value= 255


container[69].bin= 57
container[69].i= 392
container[69].j= 148
container[69].angle= 288
container[69].value= 255


container[70].bin= 57
container[70].i= 392
container[70].j= 149
container[70].angle= 288
container[70].value= 255


container[71].bin= 36
container[71].i= 392
container[71].j= 152
container[71].angle= 180
container[71].value= 255


container[72].bin= 63
container[72].i= 393
container[72].j= 142
container[72].angle= 315
container[72].value= 255


container[73].bin= 54
container[73].i= 393
container[73].j= 143
container[73].angle= 270
container[73].value= 255


container[74].bin= 44
container[74].i= 393
container[74].j= 144
container[74].angle= 224
container[74].value= 255


container[75].bin= 68
container[75].i= 393
container[75].j= 149
container[75].angle= 341
container[75].value= 255


container[76].bin= 36
container[76].i= 393
container[76].j= 152
container[76].angle= 180
container[76].value= 255


container[77].bin= 14
container[77].i= 394
container[77].j= 148
container[77].angle= 71
container[77].value= 255


container[78].bin= 8
container[78].i= 394
container[78].j= 149
container[78].angle= 44
container[78].value= 255


container[79].bin= 36
container[79].i= 394
container[79].j= 152
container[79].angle= 180
container[79].value= 255


container[80].bin= 0
container[80].i= 395
container[80].j= 147
container[80].angle= 0
container[80].value= 255


container[81].bin= 36
container[81].i= 395
container[81].j= 152
container[81].angle= 180
container[81].value= 255


container[82].bin= 57
container[82].i= 396
container[82].j= 148
container[82].angle= 288
container[82].value= 255


container[83].bin= 63
container[83].i= 396
container[83].j= 149
container[83].angle= 315
container[83].value= 255


container[84].bin= 27
container[84].i= 396
container[84].j= 153
container[84].angle= 135
container[84].value= 255


container[85].bin= 18
container[85].i= 396
container[85].j= 154
container[85].angle= 90
container[85].value= 255


container[86].bin= 12
container[86].i= 396
container[86].j= 155
container[86].angle= 63
container[86].value= 255


container[87].bin= 21
container[87].i= 396
container[87].j= 156
container[87].angle= 108
container[87].value= 255


container[88].bin= 0
container[88].i= 397
container[88].j= 149
container[88].angle= 0
container[88].value= 255


container[89].bin= 0
container[89].i= 398
container[89].j= 149
container[89].angle= 0
container[89].value= 255


container[90].bin= 36
container[90].i= 398
container[90].j= 156
container[90].angle= 180
container[90].value= 255


container[91].bin= 63
container[91].i= 399
container[91].j= 150
container[91].angle= 315
container[91].value= 255


container[92].bin= 54
container[92].i= 399
container[92].j= 151
container[92].angle= 270
container[92].value= 255


container[93].bin= 27
container[93].i= 399
container[93].j= 157
container[93].angle= 135
container[93].value= 255


container[94].bin= 18
container[94].i= 399
container[94].j= 158
container[94].angle= 90
container[94].value= 255


container[95].bin= 63
container[95].i= 400
container[95].j= 152
container[95].angle= 315
container[95].value= 255


container[96].bin= 27
container[96].i= 400
container[96].j= 159
container[96].angle= 135
container[96].value= 255


container[97].bin= 0
container[97].i= 401
container[97].j= 152
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 401
container[98].j= 159
container[98].angle= 180
container[98].value= 255


container[99].bin= 18
container[99].i= 402
container[99].j= 151
container[99].angle= 90
container[99].value= 255


container[100].bin= 8
container[100].i= 402
container[100].j= 152
container[100].angle= 44
container[100].value= 255


container[101].bin= 54
container[101].i= 402
container[101].j= 158
container[101].angle= 270
container[101].value= 255


container[102].bin= 44
container[102].i= 402
container[102].j= 159
container[102].angle= 224
container[102].value= 255


container[103].bin= 8
container[103].i= 403
container[103].j= 150
container[103].angle= 44
container[103].value= 255


container[104].bin= 44
container[104].i= 403
container[104].j= 157
container[104].angle= 224
container[104].value= 255


container[105].bin= 66
container[105].i= 404
container[105].j= 150
container[105].angle= 333
container[105].value= 255


container[106].bin= 36
container[106].i= 404
container[106].j= 156
container[106].angle= 180
container[106].value= 255


container[107].bin= 63
container[107].i= 405
container[107].j= 150
container[107].angle= 315
container[107].value= 255


container[108].bin= 59
container[108].i= 405
container[108].j= 151
container[108].angle= 296
container[108].value= 255


container[109].bin= 54
container[109].i= 405
container[109].j= 152
container[109].angle= 270
container[109].value= 255


container[110].bin= 36
container[110].i= 405
container[110].j= 156
container[110].angle= 180
container[110].value= 255


container[111].bin= 63
container[111].i= 406
container[111].j= 153
container[111].angle= 315
container[111].value= 255


container[112].bin= 36
container[112].i= 406
container[112].j= 156
container[112].angle= 180
container[112].value= 255


container[113].bin= 0
container[113].i= 407
container[113].j= 153
container[113].angle= 0
container[113].value= 255


container[114].bin= 36
container[114].i= 407
container[114].j= 156
container[114].angle= 180
container[114].value= 255


container[115].bin= 63
container[115].i= 408
container[115].j= 154
container[115].angle= 315
container[115].value= 255


container[116].bin= 30
container[116].i= 408
container[116].j= 157
container[116].angle= 153
container[116].value= 255


container[117].bin= 63
container[117].i= 409
container[117].j= 155
container[117].angle= 315
container[117].value= 255


container[118].bin= 30
container[118].i= 409
container[118].j= 157
container[118].angle= 153
container[118].value= 255


container[119].bin= 0
container[119].i= 410
container[119].j= 155
container[119].angle= 0
container[119].value= 255


container[120].bin= 63
container[120].i= 411
container[120].j= 156
container[120].angle= 315
container[120].value= 255


container[121].bin= 44
container[121].i= 411
container[121].j= 157
container[121].angle= 224
container[121].value= 255


