container[0].bin= 18
container[0].i= 399
container[0].j= 493
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 400
container[1].j= 492
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 400
container[2].j= 494
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 401
container[3].j= 492
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 401
container[4].j= 494
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 402
container[5].j= 492
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 402
container[6].j= 493
container[6].angle= 90
container[6].value= 255


container[7].bin= 30
container[7].i= 402
container[7].j= 494
container[7].angle= 153
container[7].value= 255


container[8].bin= 5
container[8].i= 403
container[8].j= 492
container[8].angle= 26
container[8].value= 255


container[9].bin= 30
container[9].i= 403
container[9].j= 494
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 404
container[10].j= 491
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 404
container[11].j= 494
container[11].angle= 180
container[11].value= 255


container[12].bin= 66
container[12].i= 405
container[12].j= 492
container[12].angle= 333
container[12].value= 255


container[13].bin= 30
container[13].i= 405
container[13].j= 495
container[13].angle= 153
container[13].value= 255


container[14].bin= 66
container[14].i= 406
container[14].j= 492
container[14].angle= 333
container[14].value= 255


container[15].bin= 30
container[15].i= 406
container[15].j= 495
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 407
container[16].j= 492
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 407
container[17].j= 495
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 408
container[18].j= 493
container[18].angle= 315
container[18].value= 255


container[19].bin= 54
container[19].i= 408
container[19].j= 494
container[19].angle= 270
container[19].value= 255


container[20].bin= 44
container[20].i= 408
container[20].j= 495
container[20].angle= 224
container[20].value= 255


