container[0].bin= 3
container[0].i= 382
container[0].j= 367
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 382
container[1].j= 368
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 382
container[2].j= 369
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 383
container[3].j= 367
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 383
container[4].j= 369
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 384
container[5].j= 367
container[5].angle= 0
container[5].value= 255


container[6].bin= 41
container[6].i= 384
container[6].j= 369
container[6].angle= 206
container[6].value= 255


container[7].bin= 0
container[7].i= 385
container[7].j= 367
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 385
container[8].j= 369
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 386
container[9].j= 367
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 386
container[10].j= 369
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 387
container[11].j= 367
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 387
container[12].j= 369
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 388
container[13].j= 367
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 388
container[14].j= 369
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 389
container[15].j= 367
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 389
container[16].j= 369
container[16].angle= 180
container[16].value= 255


container[17].bin= 18
container[17].i= 390
container[17].j= 366
container[17].angle= 90
container[17].value= 255


container[18].bin= 8
container[18].i= 390
container[18].j= 367
container[18].angle= 44
container[18].value= 255


container[19].bin= 36
container[19].i= 390
container[19].j= 369
container[19].angle= 180
container[19].value= 255


container[20].bin= 8
container[20].i= 391
container[20].j= 365
container[20].angle= 44
container[20].value= 255


container[21].bin= 0
container[21].i= 392
container[21].j= 364
container[21].angle= 0
container[21].value= 255


container[22].bin= 27
container[22].i= 392
container[22].j= 369
container[22].angle= 135
container[22].value= 255


container[23].bin= 12
container[23].i= 392
container[23].j= 370
container[23].angle= 63
container[23].value= 255


container[24].bin= 21
container[24].i= 392
container[24].j= 371
container[24].angle= 108
container[24].value= 255


container[25].bin= 66
container[25].i= 393
container[25].j= 365
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 393
container[26].j= 372
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 394
container[27].j= 365
container[27].angle= 333
container[27].value= 255


container[28].bin= 30
container[28].i= 394
container[28].j= 372
container[28].angle= 153
container[28].value= 255


container[29].bin= 0
container[29].i= 395
container[29].j= 365
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 395
container[30].j= 372
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 396
container[31].j= 366
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 396
container[32].j= 367
container[32].angle= 270
container[32].value= 255


container[33].bin= 54
container[33].i= 396
container[33].j= 368
container[33].angle= 270
container[33].value= 255


container[34].bin= 54
container[34].i= 396
container[34].j= 369
container[34].angle= 270
container[34].value= 255


container[35].bin= 36
container[35].i= 396
container[35].j= 372
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 397
container[36].j= 370
container[36].angle= 315
container[36].value= 255


container[37].bin= 0
container[37].i= 398
container[37].j= 370
container[37].angle= 0
container[37].value= 255


container[38].bin= 63
container[38].i= 399
container[38].j= 371
container[38].angle= 315
container[38].value= 255


container[39].bin= 44
container[39].i= 399
container[39].j= 372
container[39].angle= 224
container[39].value= 255


