container[0].bin= 18
container[0].i= 148
container[0].j= 175
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 149
container[1].j= 174
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 149
container[2].j= 176
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 150
container[3].j= 174
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 150
container[4].j= 176
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 151
container[5].j= 174
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 151
container[6].j= 176
container[6].angle= 135
container[6].value= 255


container[7].bin= 27
container[7].i= 151
container[7].j= 177
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 152
container[8].j= 174
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 152
container[9].j= 177
container[9].angle= 153
container[9].value= 255


container[10].bin= 63
container[10].i= 153
container[10].j= 175
container[10].angle= 315
container[10].value= 255


container[11].bin= 27
container[11].i= 153
container[11].j= 178
container[11].angle= 135
container[11].value= 255


container[12].bin= 18
container[12].i= 153
container[12].j= 179
container[12].angle= 90
container[12].value= 255


container[13].bin= 63
container[13].i= 154
container[13].j= 176
container[13].angle= 315
container[13].value= 255


container[14].bin= 27
container[14].i= 154
container[14].j= 180
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 155
container[15].j= 176
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 155
container[16].j= 180
container[16].angle= 180
container[16].value= 255


container[17].bin= 18
container[17].i= 155
container[17].j= 191
container[17].angle= 90
container[17].value= 255


container[18].bin= 0
container[18].i= 156
container[18].j= 176
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 156
container[19].j= 181
container[19].angle= 135
container[19].value= 255


container[20].bin= 18
container[20].i= 156
container[20].j= 182
container[20].angle= 90
container[20].value= 255


container[21].bin= 18
container[21].i= 156
container[21].j= 183
container[21].angle= 90
container[21].value= 255


container[22].bin= 18
container[22].i= 156
container[22].j= 184
container[22].angle= 90
container[22].value= 255


container[23].bin= 18
container[23].i= 156
container[23].j= 185
container[23].angle= 90
container[23].value= 255


container[24].bin= 3
container[24].i= 156
container[24].j= 190
container[24].angle= 18
container[24].value= 255


container[25].bin= 32
container[25].i= 156
container[25].j= 192
container[25].angle= 161
container[25].value= 255


container[26].bin= 0
container[26].i= 157
container[26].j= 176
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 157
container[27].j= 180
container[27].angle= 180
container[27].value= 255


container[28].bin= 27
container[28].i= 157
container[28].j= 186
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 157
container[29].j= 190
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 157
container[30].j= 192
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 158
container[31].j= 176
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 158
container[32].j= 180
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 158
container[33].j= 182
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 158
container[34].j= 186
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 158
container[35].j= 190
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 158
container[36].j= 192
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 159
container[37].j= 176
container[37].angle= 0
container[37].value= 255


container[38].bin= 27
container[38].i= 159
container[38].j= 180
container[38].angle= 135
container[38].value= 255


container[39].bin= 18
container[39].i= 159
container[39].j= 181
container[39].angle= 90
container[39].value= 255


container[40].bin= 8
container[40].i= 159
container[40].j= 182
container[40].angle= 44
container[40].value= 255


container[41].bin= 27
container[41].i= 159
container[41].j= 187
container[41].angle= 135
container[41].value= 255


container[42].bin= 18
container[42].i= 159
container[42].j= 188
container[42].angle= 90
container[42].value= 255


container[43].bin= 18
container[43].i= 159
container[43].j= 189
container[43].angle= 90
container[43].value= 255


container[44].bin= 8
container[44].i= 159
container[44].j= 190
container[44].angle= 44
container[44].value= 255


container[45].bin= 36
container[45].i= 159
container[45].j= 192
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 160
container[46].j= 176
container[46].angle= 0
container[46].value= 255


container[47].bin= 0
container[47].i= 161
container[47].j= 176
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 161
container[48].j= 191
container[48].angle= 180
container[48].value= 255


container[49].bin= 63
container[49].i= 162
container[49].j= 177
container[49].angle= 315
container[49].value= 255


container[50].bin= 36
container[50].i= 162
container[50].j= 191
container[50].angle= 180
container[50].value= 255


container[51].bin= 63
container[51].i= 163
container[51].j= 178
container[51].angle= 315
container[51].value= 255


container[52].bin= 32
container[52].i= 163
container[52].j= 191
container[52].angle= 161
container[52].value= 255


container[53].bin= 12
container[53].i= 163
container[53].j= 193
container[53].angle= 63
container[53].value= 255


container[54].bin= 27
container[54].i= 163
container[54].j= 194
container[54].angle= 135
container[54].value= 255


container[55].bin= 0
container[55].i= 164
container[55].j= 178
container[55].angle= 0
container[55].value= 255


container[56].bin= 36
container[56].i= 164
container[56].j= 194
container[56].angle= 180
container[56].value= 255


container[57].bin= 66
container[57].i= 165
container[57].j= 179
container[57].angle= 333
container[57].value= 255


container[58].bin= 44
container[58].i= 165
container[58].j= 190
container[58].angle= 224
container[58].value= 255


container[59].bin= 59
container[59].i= 165
container[59].j= 191
container[59].angle= 296
container[59].value= 255


container[60].bin= 59
container[60].i= 165
container[60].j= 192
container[60].angle= 296
container[60].value= 255


container[61].bin= 54
container[61].i= 165
container[61].j= 193
container[61].angle= 270
container[61].value= 255


container[62].bin= 18
container[62].i= 165
container[62].j= 196
container[62].angle= 90
container[62].value= 255


container[63].bin= 66
container[63].i= 166
container[63].j= 179
container[63].angle= 333
container[63].value= 255


container[64].bin= 36
container[64].i= 166
container[64].j= 189
container[64].angle= 180
container[64].value= 255


container[65].bin= 27
container[65].i= 166
container[65].j= 197
container[65].angle= 135
container[65].value= 255


container[66].bin= 0
container[66].i= 167
container[66].j= 179
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 167
container[67].j= 189
container[67].angle= 180
container[67].value= 255


container[68].bin= 0
container[68].i= 167
container[68].j= 194
container[68].angle= 0
container[68].value= 255


container[69].bin= 36
container[69].i= 167
container[69].j= 197
container[69].angle= 180
container[69].value= 255


container[70].bin= 63
container[70].i= 168
container[70].j= 180
container[70].angle= 315
container[70].value= 255


container[71].bin= 41
container[71].i= 168
container[71].j= 189
container[71].angle= 206
container[71].value= 255


container[72].bin= 63
container[72].i= 168
container[72].j= 195
container[72].angle= 315
container[72].value= 255


container[73].bin= 54
container[73].i= 168
container[73].j= 196
container[73].angle= 270
container[73].value= 255


container[74].bin= 18
container[74].i= 168
container[74].j= 199
container[74].angle= 90
container[74].value= 255


container[75].bin= 18
container[75].i= 168
container[75].j= 200
container[75].angle= 90
container[75].value= 255


container[76].bin= 18
container[76].i= 168
container[76].j= 201
container[76].angle= 90
container[76].value= 255


container[77].bin= 18
container[77].i= 168
container[77].j= 202
container[77].angle= 90
container[77].value= 255


container[78].bin= 18
container[78].i= 168
container[78].j= 203
container[78].angle= 90
container[78].value= 255


container[79].bin= 18
container[79].i= 168
container[79].j= 204
container[79].angle= 90
container[79].value= 255


container[80].bin= 18
container[80].i= 168
container[80].j= 205
container[80].angle= 90
container[80].value= 255


container[81].bin= 63
container[81].i= 169
container[81].j= 181
container[81].angle= 315
container[81].value= 255


container[82].bin= 41
container[82].i= 169
container[82].j= 189
container[82].angle= 206
container[82].value= 255


container[83].bin= 23
container[83].i= 169
container[83].j= 206
container[83].angle= 116
container[83].value= 255


container[84].bin= 27
container[84].i= 169
container[84].j= 207
container[84].angle= 135
container[84].value= 255


container[85].bin= 0
container[85].i= 170
container[85].j= 181
container[85].angle= 0
container[85].value= 255


container[86].bin= 36
container[86].i= 170
container[86].j= 188
container[86].angle= 180
container[86].value= 255


container[87].bin= 0
container[87].i= 170
container[87].j= 197
container[87].angle= 0
container[87].value= 255


container[88].bin= 63
container[88].i= 171
container[88].j= 182
container[88].angle= 315
container[88].value= 255


container[89].bin= 54
container[89].i= 171
container[89].j= 183
container[89].angle= 270
container[89].value= 255


container[90].bin= 36
container[90].i= 171
container[90].j= 188
container[90].angle= 180
container[90].value= 255


container[91].bin= 66
container[91].i= 171
container[91].j= 198
container[91].angle= 333
container[91].value= 255


container[92].bin= 36
container[92].i= 171
container[92].j= 205
container[92].angle= 180
container[92].value= 255


container[93].bin= 21
container[93].i= 171
container[93].j= 208
container[93].angle= 108
container[93].value= 255


container[94].bin= 18
container[94].i= 171
container[94].j= 209
container[94].angle= 90
container[94].value= 255


container[95].bin= 63
container[95].i= 172
container[95].j= 184
container[95].angle= 315
container[95].value= 255


container[96].bin= 36
container[96].i= 172
container[96].j= 188
container[96].angle= 180
container[96].value= 255


container[97].bin= 66
container[97].i= 172
container[97].j= 198
container[97].angle= 333
container[97].value= 255


container[98].bin= 21
container[98].i= 172
container[98].j= 206
container[98].angle= 108
container[98].value= 255


container[99].bin= 18
container[99].i= 172
container[99].j= 207
container[99].angle= 90
container[99].value= 255


container[100].bin= 27
container[100].i= 172
container[100].j= 210
container[100].angle= 135
container[100].value= 255


container[101].bin= 0
container[101].i= 173
container[101].j= 184
container[101].angle= 0
container[101].value= 255


container[102].bin= 36
container[102].i= 173
container[102].j= 188
container[102].angle= 180
container[102].value= 255


container[103].bin= 0
container[103].i= 173
container[103].j= 198
container[103].angle= 0
container[103].value= 255


container[104].bin= 36
container[104].i= 173
container[104].j= 210
container[104].angle= 180
container[104].value= 255


container[105].bin= 63
container[105].i= 174
container[105].j= 185
container[105].angle= 315
container[105].value= 255


container[106].bin= 54
container[106].i= 174
container[106].j= 186
container[106].angle= 270
container[106].value= 255


container[107].bin= 54
container[107].i= 174
container[107].j= 187
container[107].angle= 270
container[107].value= 255


container[108].bin= 44
container[108].i= 174
container[108].j= 188
container[108].angle= 224
container[108].value= 255


container[109].bin= 63
container[109].i= 174
container[109].j= 199
container[109].angle= 315
container[109].value= 255


container[110].bin= 27
container[110].i= 174
container[110].j= 211
container[110].angle= 135
container[110].value= 255


container[111].bin= 18
container[111].i= 174
container[111].j= 212
container[111].angle= 90
container[111].value= 255


container[112].bin= 63
container[112].i= 175
container[112].j= 200
container[112].angle= 315
container[112].value= 255


container[113].bin= 23
container[113].i= 175
container[113].j= 213
container[113].angle= 116
container[113].value= 255


container[114].bin= 23
container[114].i= 175
container[114].j= 214
container[114].angle= 116
container[114].value= 255


container[115].bin= 21
container[115].i= 175
container[115].j= 215
container[115].angle= 108
container[115].value= 255


container[116].bin= 0
container[116].i= 176
container[116].j= 200
container[116].angle= 0
container[116].value= 255


container[117].bin= 36
container[117].i= 176
container[117].j= 213
container[117].angle= 180
container[117].value= 255


container[118].bin= 63
container[118].i= 177
container[118].j= 201
container[118].angle= 315
container[118].value= 255


container[119].bin= 54
container[119].i= 177
container[119].j= 207
container[119].angle= 270
container[119].value= 255


container[120].bin= 54
container[120].i= 177
container[120].j= 208
container[120].angle= 270
container[120].value= 255


container[121].bin= 54
container[121].i= 177
container[121].j= 209
container[121].angle= 270
container[121].value= 255


container[122].bin= 54
container[122].i= 177
container[122].j= 210
container[122].angle= 270
container[122].value= 255


container[123].bin= 63
container[123].i= 178
container[123].j= 202
container[123].angle= 315
container[123].value= 255


container[124].bin= 44
container[124].i= 178
container[124].j= 206
container[124].angle= 224
container[124].value= 255


container[125].bin= 63
container[125].i= 178
container[125].j= 211
container[125].angle= 315
container[125].value= 255


container[126].bin= 21
container[126].i= 178
container[126].j= 214
container[126].angle= 108
container[126].value= 255


container[127].bin= 27
container[127].i= 178
container[127].j= 215
container[127].angle= 135
container[127].value= 255


container[128].bin= 0
container[128].i= 179
container[128].j= 202
container[128].angle= 0
container[128].value= 255


container[129].bin= 36
container[129].i= 179
container[129].j= 205
container[129].angle= 180
container[129].value= 255


container[130].bin= 0
container[130].i= 179
container[130].j= 211
container[130].angle= 0
container[130].value= 255


container[131].bin= 36
container[131].i= 179
container[131].j= 215
container[131].angle= 180
container[131].value= 255


container[132].bin= 0
container[132].i= 180
container[132].j= 202
container[132].angle= 0
container[132].value= 255


container[133].bin= 36
container[133].i= 180
container[133].j= 205
container[133].angle= 180
container[133].value= 255


container[134].bin= 63
container[134].i= 180
container[134].j= 212
container[134].angle= 315
container[134].value= 255


container[135].bin= 54
container[135].i= 180
container[135].j= 213
container[135].angle= 270
container[135].value= 255


container[136].bin= 57
container[136].i= 180
container[136].j= 214
container[136].angle= 288
container[136].value= 255


container[137].bin= 27
container[137].i= 180
container[137].j= 216
container[137].angle= 135
container[137].value= 255


container[138].bin= 0
container[138].i= 181
container[138].j= 202
container[138].angle= 0
container[138].value= 255


container[139].bin= 36
container[139].i= 181
container[139].j= 205
container[139].angle= 180
container[139].value= 255


container[140].bin= 27
container[140].i= 181
container[140].j= 217
container[140].angle= 135
container[140].value= 255


container[141].bin= 0
container[141].i= 182
container[141].j= 202
container[141].angle= 0
container[141].value= 255


container[142].bin= 36
container[142].i= 182
container[142].j= 205
container[142].angle= 180
container[142].value= 255


container[143].bin= 0
container[143].i= 182
container[143].j= 214
container[143].angle= 0
container[143].value= 255


container[144].bin= 36
container[144].i= 182
container[144].j= 217
container[144].angle= 180
container[144].value= 255


container[145].bin= 0
container[145].i= 183
container[145].j= 202
container[145].angle= 0
container[145].value= 255


container[146].bin= 41
container[146].i= 183
container[146].j= 205
container[146].angle= 206
container[146].value= 255


container[147].bin= 63
container[147].i= 183
container[147].j= 214
container[147].angle= 315
container[147].value= 255


container[148].bin= 59
container[148].i= 183
container[148].j= 215
container[148].angle= 296
container[148].value= 255


container[149].bin= 0
container[149].i= 184
container[149].j= 202
container[149].angle= 0
container[149].value= 255


container[150].bin= 41
container[150].i= 184
container[150].j= 205
container[150].angle= 206
container[150].value= 255


container[151].bin= 63
container[151].i= 184
container[151].j= 216
container[151].angle= 315
container[151].value= 255


container[152].bin= 36
container[152].i= 184
container[152].j= 218
container[152].angle= 180
container[152].value= 255


container[153].bin= 0
container[153].i= 185
container[153].j= 202
container[153].angle= 0
container[153].value= 255


container[154].bin= 0
container[154].i= 185
container[154].j= 216
container[154].angle= 0
container[154].value= 255


container[155].bin= 36
container[155].i= 185
container[155].j= 218
container[155].angle= 180
container[155].value= 255


container[156].bin= 63
container[156].i= 186
container[156].j= 203
container[156].angle= 315
container[156].value= 255


container[157].bin= 44
container[157].i= 186
container[157].j= 204
container[157].angle= 224
container[157].value= 255


container[158].bin= 0
container[158].i= 186
container[158].j= 216
container[158].angle= 0
container[158].value= 255


container[159].bin= 36
container[159].i= 186
container[159].j= 218
container[159].angle= 180
container[159].value= 255


container[160].bin= 0
container[160].i= 187
container[160].j= 216
container[160].angle= 0
container[160].value= 255


container[161].bin= 36
container[161].i= 187
container[161].j= 218
container[161].angle= 180
container[161].value= 255


container[162].bin= 0
container[162].i= 188
container[162].j= 216
container[162].angle= 0
container[162].value= 255


container[163].bin= 36
container[163].i= 188
container[163].j= 218
container[163].angle= 180
container[163].value= 255


container[164].bin= 0
container[164].i= 189
container[164].j= 216
container[164].angle= 0
container[164].value= 255


container[165].bin= 36
container[165].i= 189
container[165].j= 218
container[165].angle= 180
container[165].value= 255


container[166].bin= 0
container[166].i= 190
container[166].j= 216
container[166].angle= 0
container[166].value= 255


container[167].bin= 36
container[167].i= 190
container[167].j= 218
container[167].angle= 180
container[167].value= 255


container[168].bin= 0
container[168].i= 191
container[168].j= 216
container[168].angle= 0
container[168].value= 255


container[169].bin= 36
container[169].i= 191
container[169].j= 218
container[169].angle= 180
container[169].value= 255


container[170].bin= 68
container[170].i= 192
container[170].j= 216
container[170].angle= 341
container[170].value= 255


container[171].bin= 54
container[171].i= 192
container[171].j= 217
container[171].angle= 270
container[171].value= 255


container[172].bin= 39
container[172].i= 192
container[172].j= 218
container[172].angle= 198
container[172].value= 255


