container[0].bin= 18
container[0].i= 261
container[0].j= 314
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 262
container[1].j= 313
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 262
container[2].j= 315
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 263
container[3].j= 312
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 263
container[4].j= 315
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 264
container[5].j= 312
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 264
container[6].j= 316
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 265
container[7].j= 312
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 265
container[8].j= 316
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 266
container[9].j= 312
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 266
container[10].j= 316
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 267
container[11].j= 312
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 267
container[12].j= 316
container[12].angle= 135
container[12].value= 255


container[13].bin= 23
container[13].i= 267
container[13].j= 317
container[13].angle= 116
container[13].value= 255


container[14].bin= 0
container[14].i= 268
container[14].j= 312
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 268
container[15].j= 318
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 269
container[16].j= 312
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 269
container[17].j= 318
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 270
container[18].j= 312
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 270
container[19].j= 319
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 271
container[20].j= 312
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 271
container[21].j= 319
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 272
container[22].j= 312
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 272
container[23].j= 319
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 273
container[24].j= 312
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 273
container[25].j= 319
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 274
container[26].j= 312
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 274
container[27].j= 319
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 275
container[28].j= 312
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 275
container[29].j= 319
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 276
container[30].j= 312
container[30].angle= 0
container[30].value= 255


container[31].bin= 27
container[31].i= 276
container[31].j= 320
container[31].angle= 135
container[31].value= 255


container[32].bin= 0
container[32].i= 277
container[32].j= 312
container[32].angle= 0
container[32].value= 255


container[33].bin= 27
container[33].i= 277
container[33].j= 321
container[33].angle= 135
container[33].value= 255


container[34].bin= 0
container[34].i= 278
container[34].j= 312
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 278
container[35].j= 321
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 279
container[36].j= 313
container[36].angle= 315
container[36].value= 255


container[37].bin= 27
container[37].i= 279
container[37].j= 322
container[37].angle= 135
container[37].value= 255


container[38].bin= 18
container[38].i= 279
container[38].j= 323
container[38].angle= 90
container[38].value= 255


container[39].bin= 63
container[39].i= 280
container[39].j= 314
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 280
container[40].j= 324
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 281
container[41].j= 314
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 281
container[42].j= 324
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 282
container[43].j= 315
container[43].angle= 315
container[43].value= 255


container[44].bin= 54
container[44].i= 282
container[44].j= 320
container[44].angle= 270
container[44].value= 255


container[45].bin= 54
container[45].i= 282
container[45].j= 321
container[45].angle= 270
container[45].value= 255


container[46].bin= 54
container[46].i= 282
container[46].j= 322
container[46].angle= 270
container[46].value= 255


container[47].bin= 54
container[47].i= 282
container[47].j= 323
container[47].angle= 270
container[47].value= 255


container[48].bin= 44
container[48].i= 282
container[48].j= 324
container[48].angle= 224
container[48].value= 255


container[49].bin= 63
container[49].i= 283
container[49].j= 316
container[49].angle= 315
container[49].value= 255


container[50].bin= 44
container[50].i= 283
container[50].j= 319
container[50].angle= 224
container[50].value= 255


container[51].bin= 0
container[51].i= 284
container[51].j= 316
container[51].angle= 0
container[51].value= 255


container[52].bin= 66
container[52].i= 285
container[52].j= 317
container[52].angle= 333
container[52].value= 255


container[53].bin= 66
container[53].i= 286
container[53].j= 317
container[53].angle= 333
container[53].value= 255


container[54].bin= 36
container[54].i= 286
container[54].j= 319
container[54].angle= 180
container[54].value= 255


container[55].bin= 0
container[55].i= 287
container[55].j= 317
container[55].angle= 0
container[55].value= 255


container[56].bin= 36
container[56].i= 287
container[56].j= 319
container[56].angle= 180
container[56].value= 255


container[57].bin= 68
container[57].i= 288
container[57].j= 317
container[57].angle= 341
container[57].value= 255


container[58].bin= 54
container[58].i= 288
container[58].j= 318
container[58].angle= 270
container[58].value= 255


container[59].bin= 39
container[59].i= 288
container[59].j= 319
container[59].angle= 198
container[59].value= 255


