container[0].bin= 18
container[0].i= 279
container[0].j= 202
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 279
container[1].j= 203
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 279
container[2].j= 204
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 280
container[3].j= 201
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 280
container[4].j= 205
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 281
container[5].j= 200
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 281
container[6].j= 205
container[6].angle= 180
container[6].value= 255


container[7].bin= 63
container[7].i= 282
container[7].j= 201
container[7].angle= 315
container[7].value= 255


container[8].bin= 36
container[8].i= 282
container[8].j= 205
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 283
container[9].j= 202
container[9].angle= 315
container[9].value= 255


container[10].bin= 36
container[10].i= 283
container[10].j= 205
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 284
container[11].j= 202
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 284
container[12].j= 205
container[12].angle= 180
container[12].value= 255


container[13].bin= 18
container[13].i= 285
container[13].j= 200
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 285
container[14].j= 201
container[14].angle= 90
container[14].value= 255


container[15].bin= 8
container[15].i= 285
container[15].j= 202
container[15].angle= 44
container[15].value= 255


container[16].bin= 41
container[16].i= 285
container[16].j= 205
container[16].angle= 206
container[16].value= 255


container[17].bin= 8
container[17].i= 286
container[17].j= 199
container[17].angle= 44
container[17].value= 255


container[18].bin= 41
container[18].i= 286
container[18].j= 205
container[18].angle= 206
container[18].value= 255


container[19].bin= 0
container[19].i= 287
container[19].j= 198
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 287
container[20].j= 204
container[20].angle= 180
container[20].value= 255


container[21].bin= 63
container[21].i= 288
container[21].j= 199
container[21].angle= 315
container[21].value= 255


container[22].bin= 27
container[22].i= 288
container[22].j= 205
container[22].angle= 135
container[22].value= 255


container[23].bin= 18
container[23].i= 288
container[23].j= 206
container[23].angle= 90
container[23].value= 255


container[24].bin= 18
container[24].i= 288
container[24].j= 207
container[24].angle= 90
container[24].value= 255


container[25].bin= 21
container[25].i= 288
container[25].j= 208
container[25].angle= 108
container[25].value= 255


container[26].bin= 63
container[26].i= 289
container[26].j= 200
container[26].angle= 315
container[26].value= 255


container[27].bin= 0
container[27].i= 290
container[27].j= 200
container[27].angle= 0
container[27].value= 255


container[28].bin= 41
container[28].i= 290
container[28].j= 208
container[28].angle= 206
container[28].value= 255


container[29].bin= 63
container[29].i= 291
container[29].j= 201
container[29].angle= 315
container[29].value= 255


container[30].bin= 54
container[30].i= 291
container[30].j= 202
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 291
container[31].j= 204
container[31].angle= 270
container[31].value= 255


container[32].bin= 54
container[32].i= 291
container[32].j= 206
container[32].angle= 270
container[32].value= 255


container[33].bin= 44
container[33].i= 291
container[33].j= 207
container[33].angle= 224
container[33].value= 255


container[34].bin= 63
container[34].i= 292
container[34].j= 203
container[34].angle= 315
container[34].value= 255


container[35].bin= 44
container[35].i= 292
container[35].j= 205
container[35].angle= 224
container[35].value= 255


container[36].bin= 0
container[36].i= 293
container[36].j= 203
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 293
container[37].j= 205
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 294
container[38].j= 203
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 294
container[39].j= 205
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 295
container[40].j= 203
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 295
container[41].j= 205
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 296
container[42].j= 203
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 296
container[43].j= 205
container[43].angle= 180
container[43].value= 255


container[44].bin= 68
container[44].i= 297
container[44].j= 203
container[44].angle= 341
container[44].value= 255


container[45].bin= 54
container[45].i= 297
container[45].j= 204
container[45].angle= 270
container[45].value= 255


container[46].bin= 39
container[46].i= 297
container[46].j= 205
container[46].angle= 198
container[46].value= 255


