container[0].bin= 8
container[0].i= 547
container[0].j= 151
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 547
container[1].j= 152
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 548
container[2].j= 150
container[2].angle= 0
container[2].value= 255


container[3].bin= 18
container[3].i= 549
container[3].j= 149
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 549
container[4].j= 150
container[4].angle= 44
container[4].value= 255


container[5].bin= 41
container[5].i= 549
container[5].j= 152
container[5].angle= 206
container[5].value= 255


container[6].bin= 8
container[6].i= 550
container[6].j= 148
container[6].angle= 44
container[6].value= 255


container[7].bin= 41
container[7].i= 550
container[7].j= 152
container[7].angle= 206
container[7].value= 255


container[8].bin= 0
container[8].i= 551
container[8].j= 147
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 551
container[9].j= 151
container[9].angle= 180
container[9].value= 255


container[10].bin= 8
container[10].i= 552
container[10].j= 147
container[10].angle= 44
container[10].value= 255


container[11].bin= 41
container[11].i= 552
container[11].j= 151
container[11].angle= 206
container[11].value= 255


container[12].bin= 8
container[12].i= 553
container[12].j= 146
container[12].angle= 44
container[12].value= 255


container[13].bin= 44
container[13].i= 553
container[13].j= 150
container[13].angle= 224
container[13].value= 255


container[14].bin= 44
container[14].i= 553
container[14].j= 151
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 554
container[15].j= 145
container[15].angle= 0
container[15].value= 255


container[16].bin= 41
container[16].i= 554
container[16].j= 150
container[16].angle= 206
container[16].value= 255


container[17].bin= 63
container[17].i= 555
container[17].j= 146
container[17].angle= 315
container[17].value= 255


container[18].bin= 54
container[18].i= 555
container[18].j= 147
container[18].angle= 270
container[18].value= 255


container[19].bin= 59
container[19].i= 556
container[19].j= 148
container[19].angle= 296
container[19].value= 255


