container[0].bin= 18
container[0].i= 408
container[0].j= 469
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 409
container[1].j= 468
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 409
container[2].j= 470
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 410
container[3].j= 468
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 410
container[4].j= 470
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 411
container[5].j= 465
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 411
container[6].j= 466
container[6].angle= 90
container[6].value= 255


container[7].bin= 12
container[7].i= 411
container[7].j= 467
container[7].angle= 63
container[7].value= 255


container[8].bin= 8
container[8].i= 411
container[8].j= 468
container[8].angle= 44
container[8].value= 255


container[9].bin= 8
container[9].i= 412
container[9].j= 464
container[9].angle= 44
container[9].value= 255


container[10].bin= 36
container[10].i= 412
container[10].j= 469
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 413
container[11].j= 463
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 413
container[12].j= 469
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 414
container[13].j= 463
container[13].angle= 0
container[13].value= 255


container[14].bin= 44
container[14].i= 414
container[14].j= 469
container[14].angle= 224
container[14].value= 255


container[15].bin= 0
container[15].i= 415
container[15].j= 463
container[15].angle= 0
container[15].value= 255


container[16].bin= 44
container[16].i= 415
container[16].j= 468
container[16].angle= 224
container[16].value= 255


container[17].bin= 0
container[17].i= 416
container[17].j= 463
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 416
container[18].j= 467
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 417
container[19].j= 464
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 417
container[20].j= 466
container[20].angle= 270
container[20].value= 255


container[21].bin= 41
container[21].i= 417
container[21].j= 467
container[21].angle= 206
container[21].value= 255


container[22].bin= 63
container[22].i= 418
container[22].j= 465
container[22].angle= 315
container[22].value= 255


container[23].bin= 41
container[23].i= 418
container[23].j= 467
container[23].angle= 206
container[23].value= 255


container[24].bin= 0
container[24].i= 419
container[24].j= 465
container[24].angle= 0
container[24].value= 255


container[25].bin= 30
container[25].i= 419
container[25].j= 467
container[25].angle= 153
container[25].value= 255


container[26].bin= 8
container[26].i= 420
container[26].j= 465
container[26].angle= 44
container[26].value= 255


container[27].bin= 30
container[27].i= 420
container[27].j= 467
container[27].angle= 153
container[27].value= 255


container[28].bin= 8
container[28].i= 421
container[28].j= 464
container[28].angle= 44
container[28].value= 255


container[29].bin= 36
container[29].i= 421
container[29].j= 467
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 422
container[30].j= 463
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 422
container[31].j= 467
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 423
container[32].j= 463
container[32].angle= 0
container[32].value= 255


container[33].bin= 27
container[33].i= 423
container[33].j= 468
container[33].angle= 135
container[33].value= 255


container[34].bin= 18
container[34].i= 423
container[34].j= 469
container[34].angle= 90
container[34].value= 255


container[35].bin= 0
container[35].i= 424
container[35].j= 463
container[35].angle= 0
container[35].value= 255


container[36].bin= 18
container[36].i= 424
container[36].j= 465
container[36].angle= 90
container[36].value= 255


container[37].bin= 8
container[37].i= 424
container[37].j= 466
container[37].angle= 44
container[37].value= 255


container[38].bin= 27
container[38].i= 424
container[38].j= 470
container[38].angle= 135
container[38].value= 255


container[39].bin= 0
container[39].i= 425
container[39].j= 463
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 425
container[40].j= 470
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 426
container[41].j= 463
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 426
container[42].j= 470
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 427
container[43].j= 463
container[43].angle= 0
container[43].value= 255


container[44].bin= 30
container[44].i= 427
container[44].j= 471
container[44].angle= 153
container[44].value= 255


container[45].bin= 0
container[45].i= 428
container[45].j= 463
container[45].angle= 0
container[45].value= 255


container[46].bin= 27
container[46].i= 428
container[46].j= 471
container[46].angle= 135
container[46].value= 255


container[47].bin= 27
container[47].i= 428
container[47].j= 472
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 429
container[48].j= 463
container[48].angle= 0
container[48].value= 255


container[49].bin= 54
container[49].i= 429
container[49].j= 469
container[49].angle= 270
container[49].value= 255


container[50].bin= 0
container[50].i= 430
container[50].j= 463
container[50].angle= 0
container[50].value= 255


container[51].bin= 44
container[51].i= 430
container[51].j= 467
container[51].angle= 224
container[51].value= 255


container[52].bin= 63
container[52].i= 430
container[52].j= 468
container[52].angle= 315
container[52].value= 255


container[53].bin= 44
container[53].i= 430
container[53].j= 470
container[53].angle= 224
container[53].value= 255


container[54].bin= 0
container[54].i= 431
container[54].j= 463
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 431
container[55].j= 466
container[55].angle= 180
container[55].value= 255


container[56].bin= 36
container[56].i= 431
container[56].j= 470
container[56].angle= 180
container[56].value= 255


container[57].bin= 0
container[57].i= 432
container[57].j= 463
container[57].angle= 0
container[57].value= 255


container[58].bin= 27
container[58].i= 432
container[58].j= 467
container[58].angle= 135
container[58].value= 255


container[59].bin= 8
container[59].i= 432
container[59].j= 468
container[59].angle= 44
container[59].value= 255


container[60].bin= 36
container[60].i= 432
container[60].j= 470
container[60].angle= 180
container[60].value= 255


container[61].bin= 0
container[61].i= 433
container[61].j= 463
container[61].angle= 0
container[61].value= 255


container[62].bin= 0
container[62].i= 434
container[62].j= 463
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 434
container[63].j= 469
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 435
container[64].j= 464
container[64].angle= 315
container[64].value= 255


container[65].bin= 44
container[65].i= 435
container[65].j= 469
container[65].angle= 224
container[65].value= 255


container[66].bin= 63
container[66].i= 436
container[66].j= 465
container[66].angle= 315
container[66].value= 255


container[67].bin= 44
container[67].i= 436
container[67].j= 468
container[67].angle= 224
container[67].value= 255


container[68].bin= 0
container[68].i= 437
container[68].j= 465
container[68].angle= 0
container[68].value= 255


container[69].bin= 63
container[69].i= 438
container[69].j= 466
container[69].angle= 315
container[69].value= 255


container[70].bin= 44
container[70].i= 438
container[70].j= 467
container[70].angle= 224
container[70].value= 255


