container[0].bin= 12
container[0].i= 251
container[0].j= 109
container[0].angle= 63
container[0].value= 255


container[1].bin= 18
container[1].i= 251
container[1].j= 110
container[1].angle= 90
container[1].value= 255


container[2].bin= 27
container[2].i= 251
container[2].j= 111
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 252
container[3].j= 108
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 252
container[4].j= 111
container[4].angle= 135
container[4].value= 255


container[5].bin= 27
container[5].i= 252
container[5].j= 112
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 253
container[6].j= 107
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 253
container[7].j= 112
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 253
container[8].j= 113
container[8].angle= 135
container[8].value= 255


container[9].bin= 66
container[9].i= 254
container[9].j= 108
container[9].angle= 333
container[9].value= 255


container[10].bin= 27
container[10].i= 254
container[10].j= 113
container[10].angle= 135
container[10].value= 255


container[11].bin= 27
container[11].i= 254
container[11].j= 114
container[11].angle= 135
container[11].value= 255


container[12].bin= 66
container[12].i= 255
container[12].j= 108
container[12].angle= 333
container[12].value= 255


container[13].bin= 27
container[13].i= 255
container[13].j= 114
container[13].angle= 135
container[13].value= 255


container[14].bin= 27
container[14].i= 255
container[14].j= 115
container[14].angle= 135
container[14].value= 255


container[15].bin= 66
container[15].i= 256
container[15].j= 109
container[15].angle= 333
container[15].value= 255


container[16].bin= 30
container[16].i= 256
container[16].j= 115
container[16].angle= 153
container[16].value= 255


container[17].bin= 63
container[17].i= 257
container[17].j= 109
container[17].angle= 315
container[17].value= 255


container[18].bin= 63
container[18].i= 257
container[18].j= 110
container[18].angle= 315
container[18].value= 255


container[19].bin= 30
container[19].i= 257
container[19].j= 116
container[19].angle= 153
container[19].value= 255


container[20].bin= 66
container[20].i= 258
container[20].j= 110
container[20].angle= 333
container[20].value= 255


container[21].bin= 27
container[21].i= 258
container[21].j= 116
container[21].angle= 135
container[21].value= 255


container[22].bin= 27
container[22].i= 258
container[22].j= 117
container[22].angle= 135
container[22].value= 255


container[23].bin= 63
container[23].i= 259
container[23].j= 111
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 259
container[24].j= 117
container[24].angle= 135
container[24].value= 255


container[25].bin= 27
container[25].i= 259
container[25].j= 118
container[25].angle= 135
container[25].value= 255


container[26].bin= 59
container[26].i= 260
container[26].j= 112
container[26].angle= 296
container[26].value= 255


container[27].bin= 63
container[27].i= 260
container[27].j= 113
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 260
container[28].j= 118
container[28].angle= 153
container[28].value= 255


container[29].bin= 63
container[29].i= 261
container[29].j= 113
container[29].angle= 315
container[29].value= 255


container[30].bin= 63
container[30].i= 261
container[30].j= 114
container[30].angle= 315
container[30].value= 255


container[31].bin= 30
container[31].i= 261
container[31].j= 119
container[31].angle= 153
container[31].value= 255


container[32].bin= 63
container[32].i= 262
container[32].j= 114
container[32].angle= 315
container[32].value= 255


container[33].bin= 59
container[33].i= 262
container[33].j= 115
container[33].angle= 296
container[33].value= 255


container[34].bin= 30
container[34].i= 262
container[34].j= 119
container[34].angle= 153
container[34].value= 255


container[35].bin= 59
container[35].i= 263
container[35].j= 116
container[35].angle= 296
container[35].value= 255


container[36].bin= 63
container[36].i= 263
container[36].j= 117
container[36].angle= 315
container[36].value= 255


container[37].bin= 30
container[37].i= 263
container[37].j= 120
container[37].angle= 153
container[37].value= 255


container[38].bin= 63
container[38].i= 264
container[38].j= 117
container[38].angle= 315
container[38].value= 255


container[39].bin= 63
container[39].i= 264
container[39].j= 118
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 264
container[40].j= 121
container[40].angle= 135
container[40].value= 255


container[41].bin= 63
container[41].i= 265
container[41].j= 118
container[41].angle= 315
container[41].value= 255


