container[0].bin= 8
container[0].i= 201
container[0].j= 46
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 201
container[1].j= 47
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 201
container[2].j= 48
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 202
container[3].j= 45
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 202
container[4].j= 46
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 202
container[5].j= 49
container[5].angle= 135
container[5].value= 255


container[6].bin= 5
container[6].i= 203
container[6].j= 45
container[6].angle= 26
container[6].value= 255


container[7].bin= 23
container[7].i= 203
container[7].j= 50
container[7].angle= 116
container[7].value= 255


container[8].bin= 23
container[8].i= 203
container[8].j= 51
container[8].angle= 116
container[8].value= 255


container[9].bin= 8
container[9].i= 204
container[9].j= 44
container[9].angle= 44
container[9].value= 255


container[10].bin= 23
container[10].i= 204
container[10].j= 52
container[10].angle= 116
container[10].value= 255


container[11].bin= 27
container[11].i= 204
container[11].j= 53
container[11].angle= 135
container[11].value= 255


container[12].bin= 8
container[12].i= 205
container[12].j= 43
container[12].angle= 44
container[12].value= 255


container[13].bin= 27
container[13].i= 205
container[13].j= 53
container[13].angle= 135
container[13].value= 255


container[14].bin= 27
container[14].i= 205
container[14].j= 54
container[14].angle= 135
container[14].value= 255


container[15].bin= 5
container[15].i= 206
container[15].j= 42
container[15].angle= 26
container[15].value= 255


container[16].bin= 27
container[16].i= 206
container[16].j= 54
container[16].angle= 135
container[16].value= 255


container[17].bin= 27
container[17].i= 206
container[17].j= 55
container[17].angle= 135
container[17].value= 255


container[18].bin= 5
container[18].i= 207
container[18].j= 42
container[18].angle= 26
container[18].value= 255


container[19].bin= 27
container[19].i= 207
container[19].j= 55
container[19].angle= 135
container[19].value= 255


container[20].bin= 27
container[20].i= 207
container[20].j= 56
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 208
container[21].j= 41
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 208
container[22].j= 56
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 209
container[23].j= 41
container[23].angle= 0
container[23].value= 255


container[24].bin= 44
container[24].i= 209
container[24].j= 43
container[24].angle= 224
container[24].value= 255


container[25].bin= 54
container[25].i= 209
container[25].j= 44
container[25].angle= 270
container[25].value= 255


container[26].bin= 59
container[26].i= 209
container[26].j= 45
container[26].angle= 296
container[26].value= 255


container[27].bin= 30
container[27].i= 209
container[27].j= 57
container[27].angle= 153
container[27].value= 255


container[28].bin= 68
container[28].i= 210
container[28].j= 41
container[28].angle= 341
container[28].value= 255


container[29].bin= 44
container[29].i= 210
container[29].j= 43
container[29].angle= 224
container[29].value= 255


container[30].bin= 59
container[30].i= 210
container[30].j= 46
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 210
container[31].j= 47
container[31].angle= 315
container[31].value= 255


container[32].bin= 30
container[32].i= 210
container[32].j= 57
container[32].angle= 153
container[32].value= 255


container[33].bin= 63
container[33].i= 211
container[33].j= 47
container[33].angle= 315
container[33].value= 255


container[34].bin= 59
container[34].i= 211
container[34].j= 48
container[34].angle= 296
container[34].value= 255


container[35].bin= 36
container[35].i= 211
container[35].j= 57
container[35].angle= 180
container[35].value= 255


container[36].bin= 59
container[36].i= 212
container[36].j= 49
container[36].angle= 296
container[36].value= 255


container[37].bin= 59
container[37].i= 212
container[37].j= 50
container[37].angle= 296
container[37].value= 255


container[38].bin= 30
container[38].i= 212
container[38].j= 58
container[38].angle= 153
container[38].value= 255


container[39].bin= 63
container[39].i= 213
container[39].j= 51
container[39].angle= 315
container[39].value= 255


container[40].bin= 30
container[40].i= 213
container[40].j= 58
container[40].angle= 153
container[40].value= 255


container[41].bin= 66
container[41].i= 214
container[41].j= 52
container[41].angle= 333
container[41].value= 255


container[42].bin= 36
container[42].i= 214
container[42].j= 58
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 215
container[43].j= 52
container[43].angle= 315
container[43].value= 255


container[44].bin= 63
container[44].i= 215
container[44].j= 53
container[44].angle= 315
container[44].value= 255


container[45].bin= 36
container[45].i= 215
container[45].j= 58
container[45].angle= 180
container[45].value= 255


container[46].bin= 66
container[46].i= 216
container[46].j= 53
container[46].angle= 333
container[46].value= 255


container[47].bin= 36
container[47].i= 216
container[47].j= 58
container[47].angle= 180
container[47].value= 255


container[48].bin= 66
container[48].i= 217
container[48].j= 54
container[48].angle= 333
container[48].value= 255


container[49].bin= 36
container[49].i= 217
container[49].j= 58
container[49].angle= 180
container[49].value= 255


container[50].bin= 66
container[50].i= 218
container[50].j= 54
container[50].angle= 333
container[50].value= 255


container[51].bin= 30
container[51].i= 218
container[51].j= 59
container[51].angle= 153
container[51].value= 255


container[52].bin= 66
container[52].i= 219
container[52].j= 55
container[52].angle= 333
container[52].value= 255


container[53].bin= 30
container[53].i= 219
container[53].j= 59
container[53].angle= 153
container[53].value= 255


container[54].bin= 66
container[54].i= 220
container[54].j= 55
container[54].angle= 333
container[54].value= 255


container[55].bin= 36
container[55].i= 220
container[55].j= 59
container[55].angle= 180
container[55].value= 255


container[56].bin= 66
container[56].i= 221
container[56].j= 56
container[56].angle= 333
container[56].value= 255


container[57].bin= 41
container[57].i= 221
container[57].j= 59
container[57].angle= 206
container[57].value= 255


container[58].bin= 66
container[58].i= 222
container[58].j= 56
container[58].angle= 333
container[58].value= 255


container[59].bin= 41
container[59].i= 222
container[59].j= 59
container[59].angle= 206
container[59].value= 255


container[60].bin= 63
container[60].i= 223
container[60].j= 57
container[60].angle= 315
container[60].value= 255


container[61].bin= 44
container[61].i= 223
container[61].j= 58
container[61].angle= 224
container[61].value= 255


