container[0].bin= 18
container[0].i= 510
container[0].j= 127
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 511
container[1].j= 126
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 511
container[2].j= 128
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 512
container[3].j= 126
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 512
container[4].j= 128
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 513
container[5].j= 126
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 513
container[6].j= 128
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 514
container[7].j= 125
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 514
container[8].j= 128
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 515
container[9].j= 125
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 515
container[10].j= 128
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 516
container[11].j= 125
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 516
container[12].j= 128
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 517
container[13].j= 125
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 517
container[14].j= 128
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 518
container[15].j= 126
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 518
container[16].j= 128
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 519
container[17].j= 126
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 519
container[18].j= 127
container[18].angle= 296
container[18].value= 255


container[19].bin= 27
container[19].i= 520
container[19].j= 130
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 521
container[20].j= 128
container[20].angle= 0
container[20].value= 255


container[21].bin= 0
container[21].i= 522
container[21].j= 128
container[21].angle= 0
container[21].value= 255


container[22].bin= 0
container[22].i= 523
container[22].j= 128
container[22].angle= 0
container[22].value= 255


container[23].bin= 0
container[23].i= 524
container[23].j= 128
container[23].angle= 0
container[23].value= 255


container[24].bin= 0
container[24].i= 525
container[24].j= 128
container[24].angle= 0
container[24].value= 255


container[25].bin= 0
container[25].i= 526
container[25].j= 128
container[25].angle= 0
container[25].value= 255


container[26].bin= 0
container[26].i= 527
container[26].j= 128
container[26].angle= 0
container[26].value= 255


container[27].bin= 63
container[27].i= 528
container[27].j= 129
container[27].angle= 315
container[27].value= 255


container[28].bin= 44
container[28].i= 528
container[28].j= 130
container[28].angle= 224
container[28].value= 255


