container[0].bin= 8
container[0].i= 220
container[0].j= 463
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 220
container[1].j= 464
container[1].angle= 135
container[1].value= 255


container[2].bin= 8
container[2].i= 220
container[2].j= 471
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 220
container[3].j= 472
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 221
container[4].j= 462
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 221
container[5].j= 470
container[5].angle= 0
container[5].value= 255


container[6].bin= 66
container[6].i= 222
container[6].j= 463
container[6].angle= 333
container[6].value= 255


container[7].bin= 27
container[7].i= 222
container[7].j= 465
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 222
container[8].j= 466
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 222
container[9].j= 467
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 222
container[10].j= 468
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 222
container[11].j= 469
container[11].angle= 90
container[11].value= 255


container[12].bin= 8
container[12].i= 222
container[12].j= 470
container[12].angle= 44
container[12].value= 255


container[13].bin= 27
container[13].i= 222
container[13].j= 473
container[13].angle= 135
container[13].value= 255


container[14].bin= 66
container[14].i= 223
container[14].j= 463
container[14].angle= 333
container[14].value= 255


container[15].bin= 27
container[15].i= 223
container[15].j= 474
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 224
container[16].j= 463
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 224
container[17].j= 474
container[17].angle= 180
container[17].value= 255


container[18].bin= 63
container[18].i= 225
container[18].j= 464
container[18].angle= 315
container[18].value= 255


container[19].bin= 27
container[19].i= 225
container[19].j= 475
container[19].angle= 135
container[19].value= 255


container[20].bin= 18
container[20].i= 225
container[20].j= 476
container[20].angle= 90
container[20].value= 255


container[21].bin= 63
container[21].i= 226
container[21].j= 465
container[21].angle= 315
container[21].value= 255


container[22].bin= 27
container[22].i= 226
container[22].j= 477
container[22].angle= 135
container[22].value= 255


container[23].bin= 0
container[23].i= 227
container[23].j= 465
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 227
container[24].j= 477
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 228
container[25].j= 466
container[25].angle= 315
container[25].value= 255


container[26].bin= 54
container[26].i= 228
container[26].j= 467
container[26].angle= 270
container[26].value= 255


container[27].bin= 54
container[27].i= 228
container[27].j= 468
container[27].angle= 270
container[27].value= 255


container[28].bin= 27
container[28].i= 228
container[28].j= 478
container[28].angle= 135
container[28].value= 255


container[29].bin= 18
container[29].i= 228
container[29].j= 479
container[29].angle= 90
container[29].value= 255


container[30].bin= 59
container[30].i= 229
container[30].j= 469
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 229
container[31].j= 470
container[31].angle= 315
container[31].value= 255


container[32].bin= 27
container[32].i= 229
container[32].j= 480
container[32].angle= 135
container[32].value= 255


container[33].bin= 66
container[33].i= 230
container[33].j= 470
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 230
container[34].j= 480
container[34].angle= 180
container[34].value= 255


container[35].bin= 8
container[35].i= 231
container[35].j= 470
container[35].angle= 44
container[35].value= 255


container[36].bin= 27
container[36].i= 231
container[36].j= 481
container[36].angle= 135
container[36].value= 255


container[37].bin= 18
container[37].i= 231
container[37].j= 482
container[37].angle= 90
container[37].value= 255


container[38].bin= 18
container[38].i= 231
container[38].j= 483
container[38].angle= 90
container[38].value= 255


container[39].bin= 18
container[39].i= 231
container[39].j= 484
container[39].angle= 90
container[39].value= 255


container[40].bin= 18
container[40].i= 231
container[40].j= 485
container[40].angle= 90
container[40].value= 255


container[41].bin= 21
container[41].i= 231
container[41].j= 486
container[41].angle= 108
container[41].value= 255


container[42].bin= 18
container[42].i= 231
container[42].j= 487
container[42].angle= 90
container[42].value= 255


container[43].bin= 18
container[43].i= 231
container[43].j= 488
container[43].angle= 90
container[43].value= 255


container[44].bin= 8
container[44].i= 232
container[44].j= 469
container[44].angle= 44
container[44].value= 255


container[45].bin= 63
container[45].i= 233
container[45].j= 469
container[45].angle= 315
container[45].value= 255


container[46].bin= 39
container[46].i= 233
container[46].j= 485
container[46].angle= 198
container[46].value= 255


container[47].bin= 32
container[47].i= 233
container[47].j= 488
container[47].angle= 161
container[47].value= 255


container[48].bin= 59
container[48].i= 234
container[48].j= 470
container[48].angle= 296
container[48].value= 255


container[49].bin= 63
container[49].i= 234
container[49].j= 471
container[49].angle= 315
container[49].value= 255


container[50].bin= 32
container[50].i= 234
container[50].j= 485
container[50].angle= 161
container[50].value= 255


container[51].bin= 8
container[51].i= 234
container[51].j= 487
container[51].angle= 44
container[51].value= 255


container[52].bin= 27
container[52].i= 234
container[52].j= 488
container[52].angle= 135
container[52].value= 255


container[53].bin= 23
container[53].i= 234
container[53].j= 489
container[53].angle= 116
container[53].value= 255


container[54].bin= 66
container[54].i= 235
container[54].j= 471
container[54].angle= 333
container[54].value= 255


container[55].bin= 27
container[55].i= 235
container[55].j= 490
container[55].angle= 135
container[55].value= 255


container[56].bin= 0
container[56].i= 236
container[56].j= 471
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 236
container[57].j= 490
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 237
container[58].j= 471
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 237
container[59].j= 490
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 238
container[60].j= 471
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 238
container[61].j= 490
container[61].angle= 180
container[61].value= 255


container[62].bin= 0
container[62].i= 239
container[62].j= 471
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 239
container[63].j= 490
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 240
container[64].j= 472
container[64].angle= 315
container[64].value= 255


container[65].bin= 54
container[65].i= 240
container[65].j= 473
container[65].angle= 270
container[65].value= 255


container[66].bin= 54
container[66].i= 240
container[66].j= 474
container[66].angle= 270
container[66].value= 255


container[67].bin= 44
container[67].i= 240
container[67].j= 490
container[67].angle= 224
container[67].value= 255


container[68].bin= 63
container[68].i= 241
container[68].j= 475
container[68].angle= 315
container[68].value= 255


container[69].bin= 44
container[69].i= 241
container[69].j= 489
container[69].angle= 224
container[69].value= 255


container[70].bin= 0
container[70].i= 242
container[70].j= 475
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 242
container[71].j= 488
container[71].angle= 180
container[71].value= 255


container[72].bin= 66
container[72].i= 243
container[72].j= 476
container[72].angle= 333
container[72].value= 255


container[73].bin= 36
container[73].i= 243
container[73].j= 488
container[73].angle= 180
container[73].value= 255


container[74].bin= 63
container[74].i= 244
container[74].j= 476
container[74].angle= 315
container[74].value= 255


container[75].bin= 63
container[75].i= 244
container[75].j= 477
container[75].angle= 315
container[75].value= 255


container[76].bin= 36
container[76].i= 244
container[76].j= 488
container[76].angle= 180
container[76].value= 255


container[77].bin= 63
container[77].i= 245
container[77].j= 477
container[77].angle= 315
container[77].value= 255


container[78].bin= 63
container[78].i= 245
container[78].j= 478
container[78].angle= 315
container[78].value= 255


container[79].bin= 36
container[79].i= 245
container[79].j= 488
container[79].angle= 180
container[79].value= 255


container[80].bin= 66
container[80].i= 246
container[80].j= 478
container[80].angle= 333
container[80].value= 255


container[81].bin= 36
container[81].i= 246
container[81].j= 488
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 247
container[82].j= 478
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 247
container[83].j= 488
container[83].angle= 180
container[83].value= 255


container[84].bin= 0
container[84].i= 248
container[84].j= 478
container[84].angle= 0
container[84].value= 255


container[85].bin= 36
container[85].i= 248
container[85].j= 488
container[85].angle= 180
container[85].value= 255


container[86].bin= 66
container[86].i= 249
container[86].j= 479
container[86].angle= 333
container[86].value= 255


container[87].bin= 36
container[87].i= 249
container[87].j= 488
container[87].angle= 180
container[87].value= 255


container[88].bin= 66
container[88].i= 250
container[88].j= 479
container[88].angle= 333
container[88].value= 255


container[89].bin= 36
container[89].i= 250
container[89].j= 488
container[89].angle= 180
container[89].value= 255


container[90].bin= 0
container[90].i= 251
container[90].j= 479
container[90].angle= 0
container[90].value= 255


container[91].bin= 36
container[91].i= 251
container[91].j= 488
container[91].angle= 180
container[91].value= 255


container[92].bin= 63
container[92].i= 252
container[92].j= 480
container[92].angle= 315
container[92].value= 255


container[93].bin= 54
container[93].i= 252
container[93].j= 487
container[93].angle= 270
container[93].value= 255


container[94].bin= 44
container[94].i= 252
container[94].j= 488
container[94].angle= 224
container[94].value= 255


container[95].bin= 63
container[95].i= 253
container[95].j= 481
container[95].angle= 315
container[95].value= 255


container[96].bin= 44
container[96].i= 253
container[96].j= 486
container[96].angle= 224
container[96].value= 255


container[97].bin= 0
container[97].i= 254
container[97].j= 481
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 254
container[98].j= 485
container[98].angle= 180
container[98].value= 255


container[99].bin= 63
container[99].i= 255
container[99].j= 482
container[99].angle= 315
container[99].value= 255


container[100].bin= 54
container[100].i= 255
container[100].j= 483
container[100].angle= 270
container[100].value= 255


container[101].bin= 54
container[101].i= 255
container[101].j= 484
container[101].angle= 270
container[101].value= 255


container[102].bin= 44
container[102].i= 255
container[102].j= 485
container[102].angle= 224
container[102].value= 255


