container[0].bin= 18
container[0].i= 69
container[0].j= 82
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 70
container[1].j= 81
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 70
container[2].j= 83
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 70
container[3].j= 84
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 71
container[4].j= 80
container[4].angle= 0
container[4].value= 255


container[5].bin= 27
container[5].i= 71
container[5].j= 84
container[5].angle= 135
container[5].value= 255


container[6].bin= 23
container[6].i= 71
container[6].j= 85
container[6].angle= 116
container[6].value= 255


container[7].bin= 66
container[7].i= 72
container[7].j= 81
container[7].angle= 333
container[7].value= 255


container[8].bin= 27
container[8].i= 72
container[8].j= 86
container[8].angle= 135
container[8].value= 255


container[9].bin= 63
container[9].i= 73
container[9].j= 81
container[9].angle= 315
container[9].value= 255


container[10].bin= 63
container[10].i= 73
container[10].j= 82
container[10].angle= 315
container[10].value= 255


container[11].bin= 27
container[11].i= 73
container[11].j= 87
container[11].angle= 135
container[11].value= 255


container[12].bin= 66
container[12].i= 74
container[12].j= 82
container[12].angle= 333
container[12].value= 255


container[13].bin= 27
container[13].i= 74
container[13].j= 88
container[13].angle= 135
container[13].value= 255


container[14].bin= 66
container[14].i= 75
container[14].j= 83
container[14].angle= 333
container[14].value= 255


container[15].bin= 30
container[15].i= 75
container[15].j= 89
container[15].angle= 153
container[15].value= 255


container[16].bin= 63
container[16].i= 76
container[16].j= 83
container[16].angle= 315
container[16].value= 255


container[17].bin= 63
container[17].i= 76
container[17].j= 84
container[17].angle= 315
container[17].value= 255


container[18].bin= 30
container[18].i= 76
container[18].j= 89
container[18].angle= 153
container[18].value= 255


container[19].bin= 63
container[19].i= 77
container[19].j= 84
container[19].angle= 315
container[19].value= 255


container[20].bin= 59
container[20].i= 77
container[20].j= 85
container[20].angle= 296
container[20].value= 255


container[21].bin= 41
container[21].i= 77
container[21].j= 89
container[21].angle= 206
container[21].value= 255


container[22].bin= 59
container[22].i= 78
container[22].j= 86
container[22].angle= 296
container[22].value= 255


container[23].bin= 59
container[23].i= 78
container[23].j= 87
container[23].angle= 296
container[23].value= 255


container[24].bin= 48
container[24].i= 78
container[24].j= 88
container[24].angle= 243
container[24].value= 255


container[25].bin= 44
container[25].i= 78
container[25].j= 89
container[25].angle= 224
container[25].value= 255


