container[0].bin= 18
container[0].i= 102
container[0].j= 177
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 103
container[1].j= 176
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 103
container[2].j= 178
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 104
container[3].j= 176
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 104
container[4].j= 178
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 105
container[5].j= 176
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 105
container[6].j= 178
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 106
container[7].j= 176
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 106
container[8].j= 178
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 107
container[9].j= 176
container[9].angle= 0
container[9].value= 255


container[10].bin= 63
container[10].i= 108
container[10].j= 177
container[10].angle= 315
container[10].value= 255


container[11].bin= 44
container[11].i= 108
container[11].j= 178
container[11].angle= 224
container[11].value= 255


