container[0].bin= 8
container[0].i= 263
container[0].j= 361
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 263
container[1].j= 362
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 263
container[2].j= 363
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 264
container[3].j= 360
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 264
container[4].j= 363
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 265
container[5].j= 360
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 265
container[6].j= 364
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 266
container[7].j= 360
container[7].angle= 333
container[7].value= 255


container[8].bin= 30
container[8].i= 266
container[8].j= 364
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 267
container[9].j= 360
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 267
container[10].j= 364
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 268
container[11].j= 361
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 268
container[12].j= 364
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 269
container[13].j= 361
container[13].angle= 315
container[13].value= 255


container[14].bin= 63
container[14].i= 269
container[14].j= 362
container[14].angle= 315
container[14].value= 255


container[15].bin= 30
container[15].i= 269
container[15].j= 365
container[15].angle= 153
container[15].value= 255


container[16].bin= 66
container[16].i= 270
container[16].j= 362
container[16].angle= 333
container[16].value= 255


container[17].bin= 30
container[17].i= 270
container[17].j= 365
container[17].angle= 153
container[17].value= 255


container[18].bin= 66
container[18].i= 271
container[18].j= 363
container[18].angle= 333
container[18].value= 255


container[19].bin= 41
container[19].i= 271
container[19].j= 365
container[19].angle= 206
container[19].value= 255


container[20].bin= 63
container[20].i= 272
container[20].j= 363
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 272
container[21].j= 364
container[21].angle= 270
container[21].value= 255


container[22].bin= 44
container[22].i= 272
container[22].j= 365
container[22].angle= 224
container[22].value= 255


