container[0].bin= 14
container[0].i= 285
container[0].j= 192
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 285
container[1].j= 193
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 286
container[2].j= 192
container[2].angle= 18
container[2].value= 255


container[3].bin= 66
container[3].i= 287
container[3].j= 192
container[3].angle= 333
container[3].value= 255


container[4].bin= 36
container[4].i= 287
container[4].j= 194
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 288
container[5].j= 192
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 288
container[6].j= 194
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 289
container[7].j= 191
container[7].angle= 44
container[7].value= 255


container[8].bin= 0
container[8].i= 290
container[8].j= 190
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 290
container[9].j= 193
container[9].angle= 180
container[9].value= 255


container[10].bin= 63
container[10].i= 291
container[10].j= 191
container[10].angle= 315
container[10].value= 255


container[11].bin= 63
container[11].i= 292
container[11].j= 192
container[11].angle= 315
container[11].value= 255


container[12].bin= 36
container[12].i= 292
container[12].j= 194
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 293
container[13].j= 192
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 293
container[14].j= 194
container[14].angle= 180
container[14].value= 255


container[15].bin= 68
container[15].i= 294
container[15].j= 192
container[15].angle= 341
container[15].value= 255


container[16].bin= 54
container[16].i= 294
container[16].j= 193
container[16].angle= 270
container[16].value= 255


container[17].bin= 39
container[17].i= 294
container[17].j= 194
container[17].angle= 198
container[17].value= 255


