container[0].bin= 18
container[0].i= 88
container[0].j= 145
container[0].angle= 90
container[0].value= 255


container[1].bin= 12
container[1].i= 89
container[1].j= 143
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 89
container[2].j= 144
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 89
container[3].j= 146
container[3].angle= 135
container[3].value= 255


container[4].bin= 8
container[4].i= 90
container[4].j= 142
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 90
container[5].j= 146
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 91
container[6].j= 141
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 91
container[7].j= 146
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 92
container[8].j= 141
container[8].angle= 0
container[8].value= 255


container[9].bin= 30
container[9].i= 92
container[9].j= 147
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 93
container[10].j= 141
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 93
container[11].j= 147
container[11].angle= 153
container[11].value= 255


container[12].bin= 66
container[12].i= 94
container[12].j= 142
container[12].angle= 333
container[12].value= 255


container[13].bin= 30
container[13].i= 94
container[13].j= 148
container[13].angle= 153
container[13].value= 255


container[14].bin= 66
container[14].i= 95
container[14].j= 142
container[14].angle= 333
container[14].value= 255


container[15].bin= 27
container[15].i= 95
container[15].j= 148
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 95
container[16].j= 149
container[16].angle= 135
container[16].value= 255


container[17].bin= 66
container[17].i= 96
container[17].j= 143
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 96
container[18].j= 149
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 97
container[19].j= 143
container[19].angle= 333
container[19].value= 255


container[20].bin= 36
container[20].i= 97
container[20].j= 149
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 98
container[21].j= 144
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 98
container[22].j= 150
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 99
container[23].j= 144
container[23].angle= 315
container[23].value= 255


container[24].bin= 63
container[24].i= 99
container[24].j= 145
container[24].angle= 315
container[24].value= 255


container[25].bin= 30
container[25].i= 99
container[25].j= 150
container[25].angle= 153
container[25].value= 255


container[26].bin= 66
container[26].i= 100
container[26].j= 145
container[26].angle= 333
container[26].value= 255


container[27].bin= 30
container[27].i= 100
container[27].j= 151
container[27].angle= 153
container[27].value= 255


container[28].bin= 66
container[28].i= 101
container[28].j= 146
container[28].angle= 333
container[28].value= 255


container[29].bin= 27
container[29].i= 101
container[29].j= 151
container[29].angle= 135
container[29].value= 255


container[30].bin= 27
container[30].i= 101
container[30].j= 152
container[30].angle= 135
container[30].value= 255


container[31].bin= 66
container[31].i= 102
container[31].j= 146
container[31].angle= 333
container[31].value= 255


container[32].bin= 30
container[32].i= 102
container[32].j= 152
container[32].angle= 153
container[32].value= 255


container[33].bin= 0
container[33].i= 103
container[33].j= 146
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 103
container[34].j= 152
container[34].angle= 180
container[34].value= 255


container[35].bin= 66
container[35].i= 104
container[35].j= 147
container[35].angle= 333
container[35].value= 255


container[36].bin= 30
container[36].i= 104
container[36].j= 153
container[36].angle= 153
container[36].value= 255


container[37].bin= 66
container[37].i= 105
container[37].j= 147
container[37].angle= 333
container[37].value= 255


container[38].bin= 30
container[38].i= 105
container[38].j= 153
container[38].angle= 153
container[38].value= 255


container[39].bin= 0
container[39].i= 106
container[39].j= 147
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 106
container[40].j= 153
container[40].angle= 180
container[40].value= 255


container[41].bin= 66
container[41].i= 107
container[41].j= 148
container[41].angle= 333
container[41].value= 255


container[42].bin= 36
container[42].i= 107
container[42].j= 153
container[42].angle= 180
container[42].value= 255


container[43].bin= 66
container[43].i= 108
container[43].j= 148
container[43].angle= 333
container[43].value= 255


container[44].bin= 36
container[44].i= 108
container[44].j= 153
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 109
container[45].j= 148
container[45].angle= 0
container[45].value= 255


container[46].bin= 30
container[46].i= 109
container[46].j= 154
container[46].angle= 153
container[46].value= 255


container[47].bin= 0
container[47].i= 110
container[47].j= 148
container[47].angle= 0
container[47].value= 255


container[48].bin= 30
container[48].i= 110
container[48].j= 154
container[48].angle= 153
container[48].value= 255


container[49].bin= 66
container[49].i= 111
container[49].j= 149
container[49].angle= 333
container[49].value= 255


container[50].bin= 36
container[50].i= 111
container[50].j= 154
container[50].angle= 180
container[50].value= 255


container[51].bin= 66
container[51].i= 112
container[51].j= 149
container[51].angle= 333
container[51].value= 255


container[52].bin= 30
container[52].i= 112
container[52].j= 155
container[52].angle= 153
container[52].value= 255


container[53].bin= 66
container[53].i= 113
container[53].j= 150
container[53].angle= 333
container[53].value= 255


container[54].bin= 30
container[54].i= 113
container[54].j= 155
container[54].angle= 153
container[54].value= 255


container[55].bin= 63
container[55].i= 114
container[55].j= 150
container[55].angle= 315
container[55].value= 255


container[56].bin= 63
container[56].i= 114
container[56].j= 151
container[56].angle= 315
container[56].value= 255


container[57].bin= 36
container[57].i= 114
container[57].j= 155
container[57].angle= 180
container[57].value= 255


container[58].bin= 63
container[58].i= 115
container[58].j= 151
container[58].angle= 315
container[58].value= 255


container[59].bin= 63
container[59].i= 115
container[59].j= 152
container[59].angle= 315
container[59].value= 255


container[60].bin= 44
container[60].i= 115
container[60].j= 155
container[60].angle= 224
container[60].value= 255


container[61].bin= 63
container[61].i= 116
container[61].j= 152
container[61].angle= 315
container[61].value= 255


container[62].bin= 54
container[62].i= 116
container[62].j= 153
container[62].angle= 270
container[62].value= 255


container[63].bin= 48
container[63].i= 116
container[63].j= 154
container[63].angle= 243
container[63].value= 255


