container[0].bin= 18
container[0].i= 756
container[0].j= 236
container[0].angle= 90
container[0].value= 255


container[1].bin= 14
container[1].i= 757
container[1].j= 234
container[1].angle= 71
container[1].value= 255


container[2].bin= 14
container[2].i= 757
container[2].j= 235
container[2].angle= 71
container[2].value= 255


container[3].bin= 3
container[3].i= 758
container[3].j= 234
container[3].angle= 18
container[3].value= 255


container[4].bin= 27
container[4].i= 758
container[4].j= 236
container[4].angle= 135
container[4].value= 255


container[5].bin= 66
container[5].i= 759
container[5].j= 234
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 759
container[6].j= 237
container[6].angle= 135
container[6].value= 255


container[7].bin= 27
container[7].i= 759
container[7].j= 238
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 760
container[8].j= 234
container[8].angle= 0
container[8].value= 255


container[9].bin= 0
container[9].i= 761
container[9].j= 234
container[9].angle= 0
container[9].value= 255


container[10].bin= 39
container[10].i= 761
container[10].j= 237
container[10].angle= 198
container[10].value= 255


container[11].bin= 44
container[11].i= 761
container[11].j= 238
container[11].angle= 224
container[11].value= 255


container[12].bin= 0
container[12].i= 762
container[12].j= 234
container[12].angle= 0
container[12].value= 255


container[13].bin= 41
container[13].i= 762
container[13].j= 237
container[13].angle= 206
container[13].value= 255


container[14].bin= 0
container[14].i= 763
container[14].j= 234
container[14].angle= 0
container[14].value= 255


container[15].bin= 0
container[15].i= 764
container[15].j= 234
container[15].angle= 0
container[15].value= 255


container[16].bin= 27
container[16].i= 764
container[16].j= 237
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 765
container[17].j= 234
container[17].angle= 0
container[17].value= 255


container[18].bin= 27
container[18].i= 765
container[18].j= 238
container[18].angle= 135
container[18].value= 255


container[19].bin= 0
container[19].i= 766
container[19].j= 234
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 766
container[20].j= 238
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 767
container[21].j= 234
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 767
container[22].j= 238
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 768
container[23].j= 234
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 768
container[24].j= 238
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 769
container[25].j= 234
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 769
container[26].j= 238
container[26].angle= 180
container[26].value= 255


container[27].bin= 8
container[27].i= 770
container[27].j= 234
container[27].angle= 44
container[27].value= 255


container[28].bin= 44
container[28].i= 770
container[28].j= 238
container[28].angle= 224
container[28].value= 255


container[29].bin= 8
container[29].i= 771
container[29].j= 233
container[29].angle= 44
container[29].value= 255


container[30].bin= 44
container[30].i= 771
container[30].j= 237
container[30].angle= 224
container[30].value= 255


container[31].bin= 0
container[31].i= 772
container[31].j= 232
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 772
container[32].j= 236
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 773
container[33].j= 233
container[33].angle= 315
container[33].value= 255


container[34].bin= 36
container[34].i= 773
container[34].j= 236
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 774
container[35].j= 234
container[35].angle= 315
container[35].value= 255


container[36].bin= 0
container[36].i= 775
container[36].j= 234
container[36].angle= 0
container[36].value= 255


container[37].bin= 66
container[37].i= 776
container[37].j= 235
container[37].angle= 333
container[37].value= 255


container[38].bin= 66
container[38].i= 777
container[38].j= 235
container[38].angle= 333
container[38].value= 255


container[39].bin= 36
container[39].i= 777
container[39].j= 237
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 778
container[40].j= 235
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 778
container[41].j= 237
container[41].angle= 180
container[41].value= 255


container[42].bin= 68
container[42].i= 779
container[42].j= 235
container[42].angle= 341
container[42].value= 255


container[43].bin= 54
container[43].i= 779
container[43].j= 236
container[43].angle= 270
container[43].value= 255


container[44].bin= 39
container[44].i= 779
container[44].j= 237
container[44].angle= 198
container[44].value= 255


