container[0].bin= 8
container[0].i= 316
container[0].j= 365
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 316
container[1].j= 366
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 317
container[2].j= 364
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 318
container[3].j= 365
container[3].angle= 333
container[3].value= 255


container[4].bin= 18
container[4].i= 318
container[4].j= 370
container[4].angle= 90
container[4].value= 255


container[5].bin= 66
container[5].i= 319
container[5].j= 365
container[5].angle= 333
container[5].value= 255


container[6].bin= 36
container[6].i= 319
container[6].j= 367
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 319
container[7].j= 369
container[7].angle= 44
container[7].value= 255


container[8].bin= 27
container[8].i= 319
container[8].j= 371
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 320
container[9].j= 365
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 320
container[10].j= 367
container[10].angle= 135
container[10].value= 255


container[11].bin= 14
container[11].i= 320
container[11].j= 368
container[11].angle= 71
container[11].value= 255


container[12].bin= 32
container[12].i= 320
container[12].j= 372
container[12].angle= 161
container[12].value= 255


container[13].bin= 68
container[13].i= 321
container[13].j= 365
container[13].angle= 341
container[13].value= 255


container[14].bin= 3
container[14].i= 321
container[14].j= 370
container[14].angle= 18
container[14].value= 255


container[15].bin= 36
container[15].i= 321
container[15].j= 372
container[15].angle= 180
container[15].value= 255


container[16].bin= 54
container[16].i= 322
container[16].j= 367
container[16].angle= 270
container[16].value= 255


container[17].bin= 50
container[17].i= 322
container[17].j= 368
container[17].angle= 251
container[17].value= 255


container[18].bin= 5
container[18].i= 322
container[18].j= 370
container[18].angle= 26
container[18].value= 255


container[19].bin= 0
container[19].i= 323
container[19].j= 369
container[19].angle= 0
container[19].value= 255


container[20].bin= 66
container[20].i= 324
container[20].j= 370
container[20].angle= 333
container[20].value= 255


container[21].bin= 66
container[21].i= 325
container[21].j= 370
container[21].angle= 333
container[21].value= 255


container[22].bin= 36
container[22].i= 325
container[22].j= 372
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 326
container[23].j= 370
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 326
container[24].j= 372
container[24].angle= 180
container[24].value= 255


container[25].bin= 68
container[25].i= 327
container[25].j= 370
container[25].angle= 341
container[25].value= 255


container[26].bin= 54
container[26].i= 327
container[26].j= 371
container[26].angle= 270
container[26].value= 255


container[27].bin= 39
container[27].i= 327
container[27].j= 372
container[27].angle= 198
container[27].value= 255


