container[0].bin= 8
container[0].i= 858
container[0].j= 378
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 858
container[1].j= 379
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 859
container[2].j= 377
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 860
container[3].j= 377
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 860
container[4].j= 380
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 861
container[5].j= 377
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 861
container[6].j= 380
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 862
container[7].j= 377
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 862
container[8].j= 380
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 863
container[9].j= 377
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 863
container[10].j= 380
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 864
container[11].j= 377
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 864
container[12].j= 380
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 865
container[13].j= 377
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 865
container[14].j= 380
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 866
container[15].j= 377
container[15].angle= 0
container[15].value= 255


container[16].bin= 41
container[16].i= 866
container[16].j= 380
container[16].angle= 206
container[16].value= 255


container[17].bin= 0
container[17].i= 867
container[17].j= 377
container[17].angle= 0
container[17].value= 255


container[18].bin= 41
container[18].i= 867
container[18].j= 380
container[18].angle= 206
container[18].value= 255


container[19].bin= 0
container[19].i= 868
container[19].j= 377
container[19].angle= 0
container[19].value= 255


container[20].bin= 63
container[20].i= 869
container[20].j= 378
container[20].angle= 315
container[20].value= 255


container[21].bin= 44
container[21].i= 869
container[21].j= 379
container[21].angle= 224
container[21].value= 255


