container[0].bin= 18
container[0].i= 51
container[0].j= 0
container[0].angle= 90
container[0].value= 255


container[1].bin= 27
container[1].i= 51
container[1].j= 1
container[1].angle= 135
container[1].value= 255


container[2].bin= 30
container[2].i= 52
container[2].j= 1
container[2].angle= 153
container[2].value= 255


container[3].bin= 32
container[3].i= 53
container[3].j= 1
container[3].angle= 161
container[3].value= 255


container[4].bin= 18
container[4].i= 53
container[4].j= 3
container[4].angle= 90
container[4].value= 255


container[5].bin= 27
container[5].i= 53
container[5].j= 4
container[5].angle= 135
container[5].value= 255


container[6].bin= 30
container[6].i= 54
container[6].j= 4
container[6].angle= 153
container[6].value= 255


container[7].bin= 36
container[7].i= 55
container[7].j= 4
container[7].angle= 180
container[7].value= 255


container[8].bin= 30
container[8].i= 56
container[8].j= 5
container[8].angle= 153
container[8].value= 255


container[9].bin= 27
container[9].i= 57
container[9].j= 5
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 57
container[10].j= 6
container[10].angle= 135
container[10].value= 255


container[11].bin= 27
container[11].i= 58
container[11].j= 6
container[11].angle= 135
container[11].value= 255


container[12].bin= 27
container[12].i= 58
container[12].j= 7
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 59
container[13].j= 7
container[13].angle= 135
container[13].value= 255


container[14].bin= 27
container[14].i= 59
container[14].j= 8
container[14].angle= 135
container[14].value= 255


container[15].bin= 30
container[15].i= 60
container[15].j= 8
container[15].angle= 153
container[15].value= 255


container[16].bin= 30
container[16].i= 61
container[16].j= 9
container[16].angle= 153
container[16].value= 255


container[17].bin= 54
container[17].i= 62
container[17].j= 0
container[17].angle= 270
container[17].value= 255


container[18].bin= 27
container[18].i= 62
container[18].j= 9
container[18].angle= 135
container[18].value= 255


container[19].bin= 27
container[19].i= 62
container[19].j= 10
container[19].angle= 135
container[19].value= 255


container[20].bin= 59
container[20].i= 63
container[20].j= 1
container[20].angle= 296
container[20].value= 255


container[21].bin= 63
container[21].i= 63
container[21].j= 2
container[21].angle= 315
container[21].value= 255


container[22].bin= 27
container[22].i= 63
container[22].j= 10
container[22].angle= 135
container[22].value= 255


container[23].bin= 27
container[23].i= 63
container[23].j= 11
container[23].angle= 135
container[23].value= 255


container[24].bin= 63
container[24].i= 64
container[24].j= 2
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 64
container[25].j= 3
container[25].angle= 315
container[25].value= 255


container[26].bin= 27
container[26].i= 64
container[26].j= 11
container[26].angle= 135
container[26].value= 255


container[27].bin= 27
container[27].i= 64
container[27].j= 12
container[27].angle= 135
container[27].value= 255


container[28].bin= 63
container[28].i= 65
container[28].j= 3
container[28].angle= 315
container[28].value= 255


container[29].bin= 59
container[29].i= 65
container[29].j= 4
container[29].angle= 296
container[29].value= 255


container[30].bin= 27
container[30].i= 65
container[30].j= 12
container[30].angle= 135
container[30].value= 255


container[31].bin= 27
container[31].i= 65
container[31].j= 13
container[31].angle= 135
container[31].value= 255


container[32].bin= 59
container[32].i= 66
container[32].j= 5
container[32].angle= 296
container[32].value= 255


container[33].bin= 63
container[33].i= 66
container[33].j= 6
container[33].angle= 315
container[33].value= 255


container[34].bin= 30
container[34].i= 66
container[34].j= 13
container[34].angle= 153
container[34].value= 255


container[35].bin= 63
container[35].i= 67
container[35].j= 6
container[35].angle= 315
container[35].value= 255


container[36].bin= 59
container[36].i= 67
container[36].j= 7
container[36].angle= 296
container[36].value= 255


container[37].bin= 30
container[37].i= 67
container[37].j= 14
container[37].angle= 153
container[37].value= 255


container[38].bin= 59
container[38].i= 68
container[38].j= 8
container[38].angle= 296
container[38].value= 255


container[39].bin= 59
container[39].i= 68
container[39].j= 9
container[39].angle= 296
container[39].value= 255


container[40].bin= 27
container[40].i= 68
container[40].j= 14
container[40].angle= 135
container[40].value= 255


container[41].bin= 27
container[41].i= 68
container[41].j= 15
container[41].angle= 135
container[41].value= 255


container[42].bin= 63
container[42].i= 69
container[42].j= 10
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 69
container[43].j= 15
container[43].angle= 153
container[43].value= 255


container[44].bin= 63
container[44].i= 70
container[44].j= 11
container[44].angle= 315
container[44].value= 255


container[45].bin= 30
container[45].i= 70
container[45].j= 16
container[45].angle= 153
container[45].value= 255


container[46].bin= 63
container[46].i= 71
container[46].j= 12
container[46].angle= 315
container[46].value= 255


container[47].bin= 30
container[47].i= 71
container[47].j= 16
container[47].angle= 153
container[47].value= 255


container[48].bin= 66
container[48].i= 72
container[48].j= 13
container[48].angle= 333
container[48].value= 255


container[49].bin= 30
container[49].i= 72
container[49].j= 17
container[49].angle= 153
container[49].value= 255


container[50].bin= 63
container[50].i= 73
container[50].j= 13
container[50].angle= 315
container[50].value= 255


container[51].bin= 63
container[51].i= 73
container[51].j= 14
container[51].angle= 315
container[51].value= 255


container[52].bin= 30
container[52].i= 73
container[52].j= 17
container[52].angle= 153
container[52].value= 255


container[53].bin= 63
container[53].i= 74
container[53].j= 14
container[53].angle= 315
container[53].value= 255


container[54].bin= 63
container[54].i= 74
container[54].j= 15
container[54].angle= 315
container[54].value= 255


container[55].bin= 36
container[55].i= 74
container[55].j= 17
container[55].angle= 180
container[55].value= 255


container[56].bin= 63
container[56].i= 75
container[56].j= 15
container[56].angle= 315
container[56].value= 255


container[57].bin= 63
container[57].i= 75
container[57].j= 16
container[57].angle= 315
container[57].value= 255


container[58].bin= 63
container[58].i= 76
container[58].j= 16
container[58].angle= 315
container[58].value= 255


