container[0].bin= 14
container[0].i= 583
container[0].j= 192
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 583
container[1].j= 193
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 583
container[2].j= 194
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 583
container[3].j= 195
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 583
container[4].j= 196
container[4].angle= 90
container[4].value= 255


container[5].bin= 3
container[5].i= 584
container[5].j= 192
container[5].angle= 18
container[5].value= 255


container[6].bin= 27
container[6].i= 584
container[6].j= 197
container[6].angle= 135
container[6].value= 255


container[7].bin= 36
container[7].i= 585
container[7].j= 197
container[7].angle= 180
container[7].value= 255


container[8].bin= 8
container[8].i= 586
container[8].j= 191
container[8].angle= 44
container[8].value= 255


container[9].bin= 36
container[9].i= 586
container[9].j= 197
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 587
container[10].j= 190
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 587
container[11].j= 197
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 588
container[12].j= 190
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 588
container[13].j= 197
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 589
container[14].j= 191
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 589
container[15].j= 198
container[15].angle= 135
container[15].value= 255


container[16].bin= 63
container[16].i= 590
container[16].j= 192
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 590
container[17].j= 199
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 591
container[18].j= 192
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 591
container[19].j= 199
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 592
container[20].j= 193
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 592
container[21].j= 198
container[21].angle= 270
container[21].value= 255


container[22].bin= 44
container[22].i= 592
container[22].j= 199
container[22].angle= 224
container[22].value= 255


container[23].bin= 63
container[23].i= 593
container[23].j= 194
container[23].angle= 315
container[23].value= 255


container[24].bin= 44
container[24].i= 593
container[24].j= 197
container[24].angle= 224
container[24].value= 255


container[25].bin= 0
container[25].i= 594
container[25].j= 194
container[25].angle= 0
container[25].value= 255


container[26].bin= 66
container[26].i= 595
container[26].j= 195
container[26].angle= 333
container[26].value= 255


container[27].bin= 66
container[27].i= 596
container[27].j= 195
container[27].angle= 333
container[27].value= 255


container[28].bin= 36
container[28].i= 596
container[28].j= 197
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 597
container[29].j= 195
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 597
container[30].j= 197
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 598
container[31].j= 195
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 598
container[32].j= 197
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 599
container[33].j= 195
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 599
container[34].j= 197
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 600
container[35].j= 195
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 600
container[36].j= 197
container[36].angle= 180
container[36].value= 255


container[37].bin= 68
container[37].i= 601
container[37].j= 195
container[37].angle= 341
container[37].value= 255


container[38].bin= 54
container[38].i= 601
container[38].j= 196
container[38].angle= 270
container[38].value= 255


container[39].bin= 39
container[39].i= 601
container[39].j= 197
container[39].angle= 198
container[39].value= 255


