container[0].bin= 8
container[0].i= 849
container[0].j= 214
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 849
container[1].j= 215
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 850
container[2].j= 213
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 851
container[3].j= 213
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 851
container[4].j= 216
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 852
container[5].j= 213
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 852
container[6].j= 217
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 853
container[7].j= 213
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 853
container[8].j= 217
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 854
container[9].j= 213
container[9].angle= 44
container[9].value= 255


container[10].bin= 44
container[10].i= 854
container[10].j= 217
container[10].angle= 224
container[10].value= 255


container[11].bin= 8
container[11].i= 855
container[11].j= 212
container[11].angle= 44
container[11].value= 255


container[12].bin= 44
container[12].i= 855
container[12].j= 216
container[12].angle= 224
container[12].value= 255


container[13].bin= 0
container[13].i= 856
container[13].j= 211
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 856
container[14].j= 215
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 857
container[15].j= 211
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 857
container[16].j= 215
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 858
container[17].j= 211
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 858
container[18].j= 215
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 859
container[19].j= 211
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 859
container[20].j= 215
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 860
container[21].j= 211
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 860
container[22].j= 215
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 861
container[23].j= 211
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 861
container[24].j= 215
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 862
container[25].j= 211
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 862
container[26].j= 215
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 863
container[27].j= 211
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 863
container[28].j= 215
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 864
container[29].j= 211
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 864
container[30].j= 215
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 865
container[31].j= 211
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 865
container[32].j= 215
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 866
container[33].j= 212
container[33].angle= 315
container[33].value= 255


container[34].bin= 36
container[34].i= 866
container[34].j= 215
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 867
container[35].j= 213
container[35].angle= 315
container[35].value= 255


container[36].bin= 0
container[36].i= 868
container[36].j= 213
container[36].angle= 0
container[36].value= 255


container[37].bin= 0
container[37].i= 869
container[37].j= 213
container[37].angle= 0
container[37].value= 255


container[38].bin= 0
container[38].i= 870
container[38].j= 213
container[38].angle= 0
container[38].value= 255


container[39].bin= 41
container[39].i= 870
container[39].j= 215
container[39].angle= 206
container[39].value= 255


container[40].bin= 0
container[40].i= 871
container[40].j= 213
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 871
container[41].j= 215
container[41].angle= 180
container[41].value= 255


container[42].bin= 68
container[42].i= 872
container[42].j= 213
container[42].angle= 341
container[42].value= 255


