container[0].bin= 18
container[0].i= 450
container[0].j= 131
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 450
container[1].j= 132
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 451
container[2].j= 130
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 451
container[3].j= 133
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 452
container[4].j= 129
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 452
container[5].j= 133
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 453
container[6].j= 130
container[6].angle= 315
container[6].value= 255


container[7].bin= 54
container[7].i= 453
container[7].j= 132
container[7].angle= 270
container[7].value= 255


container[8].bin= 41
container[8].i= 453
container[8].j= 133
container[8].angle= 206
container[8].value= 255


container[9].bin= 63
container[9].i= 454
container[9].j= 131
container[9].angle= 315
container[9].value= 255


container[10].bin= 41
container[10].i= 454
container[10].j= 133
container[10].angle= 206
container[10].value= 255


container[11].bin= 0
container[11].i= 455
container[11].j= 131
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 455
container[12].j= 133
container[12].angle= 180
container[12].value= 255


container[13].bin= 18
container[13].i= 456
container[13].j= 125
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 456
container[14].j= 126
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 456
container[15].j= 127
container[15].angle= 90
container[15].value= 255


container[16].bin= 18
container[16].i= 456
container[16].j= 128
container[16].angle= 90
container[16].value= 255


container[17].bin= 0
container[17].i= 456
container[17].j= 131
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 456
container[18].j= 133
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 457
container[19].j= 124
container[19].angle= 44
container[19].value= 255


container[20].bin= 23
container[20].i= 457
container[20].j= 129
container[20].angle= 116
container[20].value= 255


container[21].bin= 23
container[21].i= 457
container[21].j= 130
container[21].angle= 116
container[21].value= 255


container[22].bin= 39
container[22].i= 457
container[22].j= 133
container[22].angle= 198
container[22].value= 255


container[23].bin= 0
container[23].i= 458
container[23].j= 123
container[23].angle= 0
container[23].value= 255


container[24].bin= 63
container[24].i= 459
container[24].j= 124
container[24].angle= 315
container[24].value= 255


container[25].bin= 54
container[25].i= 459
container[25].j= 125
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 459
container[26].j= 131
container[26].angle= 224
container[26].value= 255


container[27].bin= 63
container[27].i= 460
container[27].j= 126
container[27].angle= 315
container[27].value= 255


container[28].bin= 44
container[28].i= 460
container[28].j= 129
container[28].angle= 224
container[28].value= 255


container[29].bin= 0
container[29].i= 461
container[29].j= 126
container[29].angle= 0
container[29].value= 255


container[30].bin= 63
container[30].i= 462
container[30].j= 127
container[30].angle= 315
container[30].value= 255


container[31].bin= 44
container[31].i= 462
container[31].j= 128
container[31].angle= 224
container[31].value= 255


