container[0].bin= 8
container[0].i= 57
container[0].j= 291
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 57
container[1].j= 292
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 57
container[2].j= 293
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 58
container[3].j= 290
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 58
container[4].j= 293
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 59
container[5].j= 290
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 59
container[6].j= 293
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 60
container[7].j= 289
container[7].angle= 0
container[7].value= 255


container[8].bin= 41
container[8].i= 60
container[8].j= 293
container[8].angle= 206
container[8].value= 255


container[9].bin= 0
container[9].i= 61
container[9].j= 289
container[9].angle= 0
container[9].value= 255


container[10].bin= 41
container[10].i= 61
container[10].j= 293
container[10].angle= 206
container[10].value= 255


container[11].bin= 0
container[11].i= 62
container[11].j= 289
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 62
container[12].j= 292
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 63
container[13].j= 289
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 63
container[14].j= 292
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 64
container[15].j= 290
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 64
container[16].j= 292
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 65
container[17].j= 290
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 65
container[18].j= 291
container[18].angle= 296
container[18].value= 255


container[19].bin= 44
container[19].i= 65
container[19].j= 292
container[19].angle= 224
container[19].value= 255


