container[0].bin= 14
container[0].i= 899
container[0].j= 611
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 899
container[1].j= 612
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 899
container[2].j= 613
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 899
container[3].j= 614
container[3].angle= 90
container[3].value= 255


container[4].bin= 27
container[4].i= 900
container[4].j= 615
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 901
container[5].j= 609
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 901
container[6].j= 615
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 902
container[7].j= 609
container[7].angle= 0
container[7].value= 255


container[8].bin= 8
container[8].i= 902
container[8].j= 611
container[8].angle= 44
container[8].value= 255


container[9].bin= 36
container[9].i= 902
container[9].j= 615
container[9].angle= 180
container[9].value= 255


container[10].bin= 8
container[10].i= 903
container[10].j= 610
container[10].angle= 44
container[10].value= 255


container[11].bin= 36
container[11].i= 903
container[11].j= 615
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 904
container[12].j= 609
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 904
container[13].j= 615
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 905
container[14].j= 609
container[14].angle= 0
container[14].value= 255


container[15].bin= 54
container[15].i= 905
container[15].j= 612
container[15].angle= 270
container[15].value= 255


container[16].bin= 36
container[16].i= 905
container[16].j= 615
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 906
container[17].j= 609
container[17].angle= 0
container[17].value= 255


container[18].bin= 44
container[18].i= 906
container[18].j= 611
container[18].angle= 224
container[18].value= 255


container[19].bin= 63
container[19].i= 906
container[19].j= 613
container[19].angle= 315
container[19].value= 255


container[20].bin= 0
container[20].i= 907
container[20].j= 609
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 907
container[21].j= 611
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 907
container[22].j= 613
container[22].angle= 0
container[22].value= 255


container[23].bin= 18
container[23].i= 908
container[23].j= 608
container[23].angle= 90
container[23].value= 255


container[24].bin= 8
container[24].i= 908
container[24].j= 609
container[24].angle= 44
container[24].value= 255


container[25].bin= 36
container[25].i= 908
container[25].j= 611
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 908
container[26].j= 614
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 908
container[27].j= 615
container[27].angle= 224
container[27].value= 255


container[28].bin= 8
container[28].i= 909
container[28].j= 607
container[28].angle= 44
container[28].value= 255


container[29].bin= 0
container[29].i= 910
container[29].j= 606
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 910
container[30].j= 610
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 911
container[31].j= 607
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 911
container[32].j= 608
container[32].angle= 270
container[32].value= 255


container[33].bin= 54
container[33].i= 911
container[33].j= 609
container[33].angle= 270
container[33].value= 255


container[34].bin= 44
container[34].i= 911
container[34].j= 610
container[34].angle= 224
container[34].value= 255


