container[0].bin= 18
container[0].i= 42
container[0].j= 132
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 43
container[1].j= 130
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 43
container[2].j= 131
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 43
container[3].j= 133
container[3].angle= 135
container[3].value= 255


container[4].bin= 3
container[4].i= 44
container[4].j= 129
container[4].angle= 18
container[4].value= 255


container[5].bin= 36
container[5].i= 44
container[5].j= 133
container[5].angle= 180
container[5].value= 255


container[6].bin= 68
container[6].i= 45
container[6].j= 129
container[6].angle= 341
container[6].value= 255


container[7].bin= 57
container[7].i= 45
container[7].j= 131
container[7].angle= 288
container[7].value= 255


container[8].bin= 68
container[8].i= 46
container[8].j= 131
container[8].angle= 341
container[8].value= 255


container[9].bin= 0
container[9].i= 47
container[9].j= 131
container[9].angle= 0
container[9].value= 255


container[10].bin= 63
container[10].i= 48
container[10].j= 132
container[10].angle= 315
container[10].value= 255


container[11].bin= 44
container[11].i= 48
container[11].j= 133
container[11].angle= 224
container[11].value= 255


