container[0].bin= 18
container[0].i= 761
container[0].j= 306
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 762
container[1].j= 305
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 762
container[2].j= 307
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 763
container[3].j= 304
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 763
container[4].j= 307
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 764
container[5].j= 305
container[5].angle= 315
container[5].value= 255


container[6].bin= 30
container[6].i= 764
container[6].j= 308
container[6].angle= 153
container[6].value= 255


container[7].bin= 63
container[7].i= 765
container[7].j= 306
container[7].angle= 315
container[7].value= 255


container[8].bin= 30
container[8].i= 765
container[8].j= 308
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 766
container[9].j= 306
container[9].angle= 0
container[9].value= 255


container[10].bin= 63
container[10].i= 767
container[10].j= 307
container[10].angle= 315
container[10].value= 255


container[11].bin= 44
container[11].i= 767
container[11].j= 308
container[11].angle= 224
container[11].value= 255


