container[0].bin= 18
container[0].i= 189
container[0].j= 167
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 189
container[1].j= 168
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 190
container[2].j= 166
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 190
container[3].j= 169
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 191
container[4].j= 165
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 191
container[5].j= 169
container[5].angle= 180
container[5].value= 255


container[6].bin= 66
container[6].i= 192
container[6].j= 166
container[6].angle= 333
container[6].value= 255


container[7].bin= 30
container[7].i= 192
container[7].j= 170
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 193
container[8].j= 166
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 193
container[9].j= 170
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 194
container[10].j= 166
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 194
container[11].j= 170
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 195
container[12].j= 167
container[12].angle= 315
container[12].value= 255


container[13].bin= 27
container[13].i= 195
container[13].j= 171
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 195
container[14].j= 172
container[14].angle= 90
container[14].value= 255


container[15].bin= 63
container[15].i= 196
container[15].j= 168
container[15].angle= 315
container[15].value= 255


container[16].bin= 27
container[16].i= 196
container[16].j= 173
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 197
container[17].j= 168
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 197
container[18].j= 173
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 198
container[19].j= 168
container[19].angle= 0
container[19].value= 255


container[20].bin= 54
container[20].i= 198
container[20].j= 171
container[20].angle= 270
container[20].value= 255


container[21].bin= 57
container[21].i= 198
container[21].j= 172
container[21].angle= 288
container[21].value= 255


container[22].bin= 0
container[22].i= 199
container[22].j= 168
container[22].angle= 0
container[22].value= 255


container[23].bin= 44
container[23].i= 199
container[23].j= 170
container[23].angle= 224
container[23].value= 255


container[24].bin= 36
container[24].i= 199
container[24].j= 174
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 200
container[25].j= 168
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 200
container[26].j= 170
container[26].angle= 180
container[26].value= 255


container[27].bin= 0
container[27].i= 201
container[27].j= 168
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 201
container[28].j= 170
container[28].angle= 180
container[28].value= 255


container[29].bin= 63
container[29].i= 201
container[29].j= 172
container[29].angle= 315
container[29].value= 255


container[30].bin= 68
container[30].i= 202
container[30].j= 168
container[30].angle= 341
container[30].value= 255


container[31].bin= 54
container[31].i= 202
container[31].j= 169
container[31].angle= 270
container[31].value= 255


container[32].bin= 39
container[32].i= 202
container[32].j= 170
container[32].angle= 198
container[32].value= 255


