container[0].bin= 8
container[0].i= 783
container[0].j= 326
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 783
container[1].j= 327
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 784
container[2].j= 325
container[2].angle= 0
container[2].value= 255


container[3].bin= 63
container[3].i= 785
container[3].j= 326
container[3].angle= 315
container[3].value= 255


container[4].bin= 27
container[4].i= 786
container[4].j= 329
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 787
container[5].j= 327
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 788
container[6].j= 328
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 788
container[7].j= 329
container[7].angle= 224
container[7].value= 255


