container[0].bin= 8
container[0].i= 424
container[0].j= 543
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 424
container[1].j= 544
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 425
container[2].j= 542
container[2].angle= 0
container[2].value= 255


container[3].bin= 14
container[3].i= 426
container[3].j= 541
container[3].angle= 71
container[3].value= 255


container[4].bin= 8
container[4].i= 426
container[4].j= 542
container[4].angle= 44
container[4].value= 255


container[5].bin= 0
container[5].i= 427
container[5].j= 540
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 427
container[6].j= 544
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 428
container[7].j= 540
container[7].angle= 0
container[7].value= 255


container[8].bin= 63
container[8].i= 428
container[8].j= 542
container[8].angle= 315
container[8].value= 255


container[9].bin= 0
container[9].i= 429
container[9].j= 540
container[9].angle= 0
container[9].value= 255


container[10].bin= 8
container[10].i= 429
container[10].j= 542
container[10].angle= 44
container[10].value= 255


container[11].bin= 3
container[11].i= 430
container[11].j= 541
container[11].angle= 18
container[11].value= 255


container[12].bin= 8
container[12].i= 430
container[12].j= 542
container[12].angle= 44
container[12].value= 255


container[13].bin= 36
container[13].i= 430
container[13].j= 544
container[13].angle= 180
container[13].value= 255


container[14].bin= 5
container[14].i= 431
container[14].j= 541
container[14].angle= 26
container[14].value= 255


container[15].bin= 36
container[15].i= 431
container[15].j= 544
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 432
container[16].j= 540
container[16].angle= 0
container[16].value= 255


container[17].bin= 27
container[17].i= 432
container[17].j= 545
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 433
container[18].j= 540
container[18].angle= 0
container[18].value= 255


container[19].bin= 27
container[19].i= 433
container[19].j= 546
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 434
container[20].j= 540
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 434
container[21].j= 546
container[21].angle= 180
container[21].value= 255


container[22].bin= 18
container[22].i= 435
container[22].j= 538
container[22].angle= 90
container[22].value= 255


container[23].bin= 18
container[23].i= 435
container[23].j= 539
container[23].angle= 90
container[23].value= 255


container[24].bin= 8
container[24].i= 435
container[24].j= 540
container[24].angle= 44
container[24].value= 255


container[25].bin= 36
container[25].i= 435
container[25].j= 546
container[25].angle= 180
container[25].value= 255


container[26].bin= 8
container[26].i= 436
container[26].j= 537
container[26].angle= 44
container[26].value= 255


container[27].bin= 36
container[27].i= 436
container[27].j= 546
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 437
container[28].j= 536
container[28].angle= 0
container[28].value= 255


container[29].bin= 54
container[29].i= 437
container[29].j= 541
container[29].angle= 270
container[29].value= 255


container[30].bin= 36
container[30].i= 437
container[30].j= 546
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 438
container[31].j= 537
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 438
container[32].j= 538
container[32].angle= 270
container[32].value= 255


container[33].bin= 48
container[33].i= 438
container[33].j= 539
container[33].angle= 243
container[33].value= 255


container[34].bin= 48
container[34].i= 438
container[34].j= 540
container[34].angle= 243
container[34].value= 255


container[35].bin= 63
container[35].i= 438
container[35].j= 542
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 438
container[36].j= 547
container[36].angle= 135
container[36].value= 255


container[37].bin= 18
container[37].i= 438
container[37].j= 548
container[37].angle= 90
container[37].value= 255


container[38].bin= 18
container[38].i= 438
container[38].j= 549
container[38].angle= 90
container[38].value= 255


container[39].bin= 18
container[39].i= 438
container[39].j= 550
container[39].angle= 90
container[39].value= 255


container[40].bin= 0
container[40].i= 439
container[40].j= 542
container[40].angle= 0
container[40].value= 255


container[41].bin= 27
container[41].i= 439
container[41].j= 551
container[41].angle= 135
container[41].value= 255


container[42].bin= 0
container[42].i= 440
container[42].j= 542
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 440
container[43].j= 551
container[43].angle= 180
container[43].value= 255


container[44].bin= 63
container[44].i= 441
container[44].j= 543
container[44].angle= 315
container[44].value= 255


container[45].bin= 27
container[45].i= 441
container[45].j= 552
container[45].angle= 135
container[45].value= 255


container[46].bin= 18
container[46].i= 441
container[46].j= 553
container[46].angle= 90
container[46].value= 255


container[47].bin= 63
container[47].i= 442
container[47].j= 544
container[47].angle= 315
container[47].value= 255


container[48].bin= 27
container[48].i= 442
container[48].j= 554
container[48].angle= 135
container[48].value= 255


container[49].bin= 0
container[49].i= 443
container[49].j= 544
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 443
container[50].j= 554
container[50].angle= 180
container[50].value= 255


container[51].bin= 63
container[51].i= 444
container[51].j= 545
container[51].angle= 315
container[51].value= 255


container[52].bin= 54
container[52].i= 444
container[52].j= 546
container[52].angle= 270
container[52].value= 255


container[53].bin= 54
container[53].i= 444
container[53].j= 547
container[53].angle= 270
container[53].value= 255


container[54].bin= 30
container[54].i= 444
container[54].j= 555
container[54].angle= 153
container[54].value= 255


container[55].bin= 63
container[55].i= 445
container[55].j= 548
container[55].angle= 315
container[55].value= 255


container[56].bin= 30
container[56].i= 445
container[56].j= 555
container[56].angle= 153
container[56].value= 255


container[57].bin= 0
container[57].i= 446
container[57].j= 548
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 446
container[58].j= 555
container[58].angle= 180
container[58].value= 255


container[59].bin= 63
container[59].i= 447
container[59].j= 549
container[59].angle= 315
container[59].value= 255


container[60].bin= 27
container[60].i= 447
container[60].j= 556
container[60].angle= 135
container[60].value= 255


container[61].bin= 63
container[61].i= 448
container[61].j= 550
container[61].angle= 315
container[61].value= 255


container[62].bin= 27
container[62].i= 448
container[62].j= 557
container[62].angle= 135
container[62].value= 255


container[63].bin= 0
container[63].i= 449
container[63].j= 550
container[63].angle= 0
container[63].value= 255


container[64].bin= 36
container[64].i= 449
container[64].j= 557
container[64].angle= 180
container[64].value= 255


container[65].bin= 63
container[65].i= 450
container[65].j= 551
container[65].angle= 315
container[65].value= 255


container[66].bin= 36
container[66].i= 450
container[66].j= 557
container[66].angle= 180
container[66].value= 255


container[67].bin= 63
container[67].i= 451
container[67].j= 552
container[67].angle= 315
container[67].value= 255


container[68].bin= 36
container[68].i= 451
container[68].j= 557
container[68].angle= 180
container[68].value= 255


container[69].bin= 66
container[69].i= 452
container[69].j= 553
container[69].angle= 333
container[69].value= 255


container[70].bin= 36
container[70].i= 452
container[70].j= 557
container[70].angle= 180
container[70].value= 255


container[71].bin= 63
container[71].i= 453
container[71].j= 553
container[71].angle= 315
container[71].value= 255


container[72].bin= 59
container[72].i= 453
container[72].j= 554
container[72].angle= 296
container[72].value= 255


container[73].bin= 54
container[73].i= 453
container[73].j= 555
container[73].angle= 270
container[73].value= 255


container[74].bin= 54
container[74].i= 453
container[74].j= 556
container[74].angle= 270
container[74].value= 255


container[75].bin= 44
container[75].i= 453
container[75].j= 557
container[75].angle= 224
container[75].value= 255


