container[0].bin= 18
container[0].i= 213
container[0].j= 143
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 213
container[1].j= 149
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 214
container[2].j= 142
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 214
container[3].j= 144
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 215
container[4].j= 141
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 215
container[5].j= 144
container[5].angle= 180
container[5].value= 255


container[6].bin= 3
container[6].i= 215
container[6].j= 147
container[6].angle= 18
container[6].value= 255


container[7].bin= 0
container[7].i= 216
container[7].j= 141
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 216
container[8].j= 145
container[8].angle= 135
container[8].value= 255


container[9].bin= 18
container[9].i= 216
container[9].j= 146
container[9].angle= 90
container[9].value= 255


container[10].bin= 8
container[10].i= 216
container[10].j= 147
container[10].angle= 44
container[10].value= 255


container[11].bin= 27
container[11].i= 216
container[11].j= 149
container[11].angle= 135
container[11].value= 255


container[12].bin= 27
container[12].i= 216
container[12].j= 150
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 217
container[13].j= 141
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 217
container[14].j= 150
container[14].angle= 153
container[14].value= 255


container[15].bin= 8
container[15].i= 217
container[15].j= 153
container[15].angle= 44
container[15].value= 255


container[16].bin= 27
container[16].i= 217
container[16].j= 154
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 218
container[17].j= 141
container[17].angle= 0
container[17].value= 255


container[18].bin= 27
container[18].i= 218
container[18].j= 151
container[18].angle= 135
container[18].value= 255


container[19].bin= 8
container[19].i= 218
container[19].j= 152
container[19].angle= 44
container[19].value= 255


container[20].bin= 66
container[20].i= 219
container[20].j= 142
container[20].angle= 333
container[20].value= 255


container[21].bin= 44
container[21].i= 219
container[21].j= 154
container[21].angle= 224
container[21].value= 255


container[22].bin= 66
container[22].i= 220
container[22].j= 142
container[22].angle= 333
container[22].value= 255


container[23].bin= 44
container[23].i= 220
container[23].j= 153
container[23].angle= 224
container[23].value= 255


container[24].bin= 0
container[24].i= 221
container[24].j= 142
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 221
container[25].j= 152
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 222
container[26].j= 143
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 222
container[27].j= 152
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 223
container[28].j= 144
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 223
container[29].j= 152
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 224
container[30].j= 144
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 224
container[31].j= 152
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 225
container[32].j= 144
container[32].angle= 0
container[32].value= 255


container[33].bin= 41
container[33].i= 225
container[33].j= 152
container[33].angle= 206
container[33].value= 255


container[34].bin= 0
container[34].i= 226
container[34].j= 144
container[34].angle= 0
container[34].value= 255


container[35].bin= 41
container[35].i= 226
container[35].j= 152
container[35].angle= 206
container[35].value= 255


container[36].bin= 0
container[36].i= 227
container[36].j= 144
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 227
container[37].j= 151
container[37].angle= 180
container[37].value= 255


container[38].bin= 66
container[38].i= 228
container[38].j= 145
container[38].angle= 333
container[38].value= 255


container[39].bin= 30
container[39].i= 228
container[39].j= 152
container[39].angle= 153
container[39].value= 255


container[40].bin= 66
container[40].i= 229
container[40].j= 145
container[40].angle= 333
container[40].value= 255


container[41].bin= 44
container[41].i= 229
container[41].j= 149
container[41].angle= 224
container[41].value= 255


container[42].bin= 63
container[42].i= 229
container[42].j= 150
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 229
container[43].j= 152
container[43].angle= 153
container[43].value= 255


container[44].bin= 0
container[44].i= 230
container[44].j= 145
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 230
container[45].j= 148
container[45].angle= 180
container[45].value= 255


container[46].bin= 63
container[46].i= 231
container[46].j= 146
container[46].angle= 315
container[46].value= 255


container[47].bin= 63
container[47].i= 231
container[47].j= 151
container[47].angle= 315
container[47].value= 255


container[48].bin= 44
container[48].i= 231
container[48].j= 152
container[48].angle= 224
container[48].value= 255


container[49].bin= 63
container[49].i= 232
container[49].j= 147
container[49].angle= 315
container[49].value= 255


container[50].bin= 30
container[50].i= 232
container[50].j= 149
container[50].angle= 153
container[50].value= 255


container[51].bin= 0
container[51].i= 233
container[51].j= 147
container[51].angle= 0
container[51].value= 255


container[52].bin= 30
container[52].i= 233
container[52].j= 149
container[52].angle= 153
container[52].value= 255


container[53].bin= 0
container[53].i= 234
container[53].j= 147
container[53].angle= 0
container[53].value= 255


container[54].bin= 41
container[54].i= 234
container[54].j= 149
container[54].angle= 206
container[54].value= 255


container[55].bin= 0
container[55].i= 235
container[55].j= 147
container[55].angle= 0
container[55].value= 255


container[56].bin= 41
container[56].i= 235
container[56].j= 149
container[56].angle= 206
container[56].value= 255


container[57].bin= 0
container[57].i= 236
container[57].j= 147
container[57].angle= 0
container[57].value= 255


container[58].bin= 36
container[58].i= 236
container[58].j= 149
container[58].angle= 180
container[58].value= 255


container[59].bin= 68
container[59].i= 237
container[59].j= 147
container[59].angle= 341
container[59].value= 255


container[60].bin= 54
container[60].i= 237
container[60].j= 148
container[60].angle= 270
container[60].value= 255


container[61].bin= 39
container[61].i= 237
container[61].j= 149
container[61].angle= 198
container[61].value= 255


