container[0].bin= 8
container[0].i= 196
container[0].j= 293
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 196
container[1].j= 294
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 197
container[2].j= 292
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 198
container[3].j= 292
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 199
container[4].j= 292
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 200
container[5].j= 292
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 201
container[6].j= 292
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 202
container[7].j= 292
container[7].angle= 0
container[7].value= 255


container[8].bin= 0
container[8].i= 203
container[8].j= 292
container[8].angle= 0
container[8].value= 255


container[9].bin= 63
container[9].i= 204
container[9].j= 293
container[9].angle= 315
container[9].value= 255


container[10].bin= 44
container[10].i= 204
container[10].j= 294
container[10].angle= 224
container[10].value= 255


