container[0].bin= 14
container[0].i= 111
container[0].j= 185
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 111
container[1].j= 186
container[1].angle= 108
container[1].value= 255


container[2].bin= 18
container[2].i= 111
container[2].j= 187
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 111
container[3].j= 188
container[3].angle= 90
container[3].value= 255


container[4].bin= 3
container[4].i= 112
container[4].j= 184
container[4].angle= 18
container[4].value= 255


container[5].bin= 8
container[5].i= 112
container[5].j= 185
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 112
container[6].j= 186
container[6].angle= 135
container[6].value= 255


container[7].bin= 0
container[7].i= 113
container[7].j= 184
container[7].angle= 0
container[7].value= 255


container[8].bin= 32
container[8].i= 113
container[8].j= 188
container[8].angle= 161
container[8].value= 255


container[9].bin= 68
container[9].i= 114
container[9].j= 184
container[9].angle= 341
container[9].value= 255


container[10].bin= 8
container[10].i= 114
container[10].j= 187
container[10].angle= 44
container[10].value= 255


container[11].bin= 27
container[11].i= 114
container[11].j= 188
container[11].angle= 135
container[11].value= 255


container[12].bin= 23
container[12].i= 114
container[12].j= 189
container[12].angle= 116
container[12].value= 255


container[13].bin= 18
container[13].i= 114
container[13].j= 190
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 114
container[14].j= 191
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 114
container[15].j= 192
container[15].angle= 90
container[15].value= 255


container[16].bin= 68
container[16].i= 115
container[16].j= 185
container[16].angle= 341
container[16].value= 255


container[17].bin= 27
container[17].i= 115
container[17].j= 193
container[17].angle= 135
container[17].value= 255


container[18].bin= 66
container[18].i= 116
container[18].j= 186
container[18].angle= 333
container[18].value= 255


container[19].bin= 36
container[19].i= 116
container[19].j= 193
container[19].angle= 180
container[19].value= 255


container[20].bin= 66
container[20].i= 117
container[20].j= 186
container[20].angle= 333
container[20].value= 255


container[21].bin= 44
container[21].i= 117
container[21].j= 193
container[21].angle= 224
container[21].value= 255


container[22].bin= 0
container[22].i= 118
container[22].j= 186
container[22].angle= 0
container[22].value= 255


container[23].bin= 44
container[23].i= 118
container[23].j= 192
container[23].angle= 224
container[23].value= 255


container[24].bin= 66
container[24].i= 119
container[24].j= 187
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 119
container[25].j= 191
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 120
container[26].j= 187
container[26].angle= 315
container[26].value= 255


container[27].bin= 59
container[27].i= 120
container[27].j= 188
container[27].angle= 296
container[27].value= 255


container[28].bin= 54
container[28].i= 120
container[28].j= 189
container[28].angle= 270
container[28].value= 255


container[29].bin= 54
container[29].i= 120
container[29].j= 190
container[29].angle= 270
container[29].value= 255


container[30].bin= 44
container[30].i= 120
container[30].j= 191
container[30].angle= 224
container[30].value= 255


