container[0].bin= 18
container[0].i= 630
container[0].j= 358
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 631
container[1].j= 357
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 631
container[2].j= 359
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 632
container[3].j= 357
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 632
container[4].j= 359
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 633
container[5].j= 357
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 633
container[6].j= 359
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 634
container[7].j= 357
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 634
container[8].j= 359
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 635
container[9].j= 357
container[9].angle= 26
container[9].value= 255


container[10].bin= 0
container[10].i= 636
container[10].j= 356
container[10].angle= 0
container[10].value= 255


container[11].bin= 63
container[11].i= 637
container[11].j= 357
container[11].angle= 315
container[11].value= 255


container[12].bin= 44
container[12].i= 637
container[12].j= 358
container[12].angle= 224
container[12].value= 255


