container[0].bin= 18
container[0].i= 749
container[0].j= 270
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 750
container[1].j= 269
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 750
container[2].j= 271
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 751
container[3].j= 269
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 751
container[4].j= 271
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 752
container[5].j= 269
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 752
container[6].j= 271
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 753
container[7].j= 264
container[7].angle= 44
container[7].value= 255


container[8].bin= 27
container[8].i= 753
container[8].j= 265
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 753
container[9].j= 269
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 753
container[10].j= 271
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 754
container[11].j= 263
container[11].angle= 0
container[11].value= 255


container[12].bin= 0
container[12].i= 754
container[12].j= 269
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 754
container[13].j= 271
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 755
container[14].j= 263
container[14].angle= 0
container[14].value= 255


container[15].bin= 27
container[15].i= 755
container[15].j= 266
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 755
container[16].j= 267
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 755
container[17].j= 268
container[17].angle= 90
container[17].value= 255


container[18].bin= 8
container[18].i= 755
container[18].j= 269
container[18].angle= 44
container[18].value= 255


container[19].bin= 18
container[19].i= 755
container[19].j= 270
container[19].angle= 90
container[19].value= 255


container[20].bin= 30
container[20].i= 755
container[20].j= 271
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 756
container[21].j= 263
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 756
container[22].j= 271
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 757
container[23].j= 263
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 757
container[24].j= 266
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 757
container[25].j= 268
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 757
container[26].j= 271
container[26].angle= 180
container[26].value= 255


container[27].bin= 66
container[27].i= 758
container[27].j= 264
container[27].angle= 333
container[27].value= 255


container[28].bin= 18
container[28].i= 758
container[28].j= 267
container[28].angle= 90
container[28].value= 255


container[29].bin= 8
container[29].i= 758
container[29].j= 268
container[29].angle= 44
container[29].value= 255


container[30].bin= 36
container[30].i= 758
container[30].j= 271
container[30].angle= 180
container[30].value= 255


container[31].bin= 66
container[31].i= 759
container[31].j= 264
container[31].angle= 333
container[31].value= 255


container[32].bin= 36
container[32].i= 759
container[32].j= 271
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 760
container[33].j= 264
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 760
container[34].j= 271
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 761
container[35].j= 264
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 761
container[36].j= 271
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 762
container[37].j= 264
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 762
container[38].j= 271
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 763
container[39].j= 264
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 763
container[40].j= 271
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 764
container[41].j= 265
container[41].angle= 315
container[41].value= 255


container[42].bin= 30
container[42].i= 764
container[42].j= 272
container[42].angle= 153
container[42].value= 255


container[43].bin= 63
container[43].i= 765
container[43].j= 266
container[43].angle= 315
container[43].value= 255


container[44].bin= 27
container[44].i= 765
container[44].j= 272
container[44].angle= 135
container[44].value= 255


container[45].bin= 27
container[45].i= 765
container[45].j= 273
container[45].angle= 135
container[45].value= 255


container[46].bin= 0
container[46].i= 766
container[46].j= 266
container[46].angle= 0
container[46].value= 255


container[47].bin= 30
container[47].i= 766
container[47].j= 273
container[47].angle= 153
container[47].value= 255


container[48].bin= 66
container[48].i= 767
container[48].j= 267
container[48].angle= 333
container[48].value= 255


container[49].bin= 44
container[49].i= 767
container[49].j= 273
container[49].angle= 224
container[49].value= 255


container[50].bin= 66
container[50].i= 768
container[50].j= 267
container[50].angle= 333
container[50].value= 255


container[51].bin= 44
container[51].i= 768
container[51].j= 272
container[51].angle= 224
container[51].value= 255


container[52].bin= 0
container[52].i= 769
container[52].j= 267
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 769
container[53].j= 271
container[53].angle= 180
container[53].value= 255


container[54].bin= 63
container[54].i= 770
container[54].j= 268
container[54].angle= 315
container[54].value= 255


container[55].bin= 36
container[55].i= 770
container[55].j= 271
container[55].angle= 180
container[55].value= 255


container[56].bin= 63
container[56].i= 771
container[56].j= 269
container[56].angle= 315
container[56].value= 255


container[57].bin= 0
container[57].i= 772
container[57].j= 269
container[57].angle= 0
container[57].value= 255


container[58].bin= 0
container[58].i= 773
container[58].j= 269
container[58].angle= 0
container[58].value= 255


container[59].bin= 14
container[59].i= 774
container[59].j= 268
container[59].angle= 71
container[59].value= 255


container[60].bin= 8
container[60].i= 774
container[60].j= 269
container[60].angle= 44
container[60].value= 255


container[61].bin= 3
container[61].i= 775
container[61].j= 267
container[61].angle= 18
container[61].value= 255


container[62].bin= 36
container[62].i= 775
container[62].j= 271
container[62].angle= 180
container[62].value= 255


container[63].bin= 68
container[63].i= 776
container[63].j= 267
container[63].angle= 341
container[63].value= 255


container[64].bin= 54
container[64].i= 776
container[64].j= 269
container[64].angle= 270
container[64].value= 255


container[65].bin= 59
container[65].i= 776
container[65].j= 270
container[65].angle= 296
container[65].value= 255


container[66].bin= 44
container[66].i= 776
container[66].j= 271
container[66].angle= 224
container[66].value= 255


