container[0].bin= 8
container[0].i= 343
container[0].j= 423
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 343
container[1].j= 424
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 344
container[2].j= 422
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 345
container[3].j= 422
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 346
container[4].j= 422
container[4].angle= 0
container[4].value= 255


container[5].bin= 66
container[5].i= 347
container[5].j= 423
container[5].angle= 333
container[5].value= 255


container[6].bin= 63
container[6].i= 348
container[6].j= 423
container[6].angle= 315
container[6].value= 255


