container[0].bin= 8
container[0].i= 251
container[0].j= 16
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 251
container[1].j= 17
container[1].angle= 116
container[1].value= 255


container[2].bin= 23
container[2].i= 251
container[2].j= 18
container[2].angle= 116
container[2].value= 255


container[3].bin= 5
container[3].i= 252
container[3].j= 15
container[3].angle= 26
container[3].value= 255


container[4].bin= 23
container[4].i= 252
container[4].j= 19
container[4].angle= 116
container[4].value= 255


container[5].bin= 27
container[5].i= 252
container[5].j= 20
container[5].angle= 135
container[5].value= 255


container[6].bin= 5
container[6].i= 253
container[6].j= 15
container[6].angle= 26
container[6].value= 255


container[7].bin= 27
container[7].i= 253
container[7].j= 20
container[7].angle= 135
container[7].value= 255


container[8].bin= 27
container[8].i= 253
container[8].j= 21
container[8].angle= 135
container[8].value= 255


container[9].bin= 5
container[9].i= 254
container[9].j= 14
container[9].angle= 26
container[9].value= 255


container[10].bin= 30
container[10].i= 254
container[10].j= 21
container[10].angle= 153
container[10].value= 255


container[11].bin= 5
container[11].i= 255
container[11].j= 14
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 255
container[12].j= 21
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 256
container[13].j= 13
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 256
container[14].j= 21
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 257
container[15].j= 13
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 257
container[16].j= 21
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 258
container[17].j= 13
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 258
container[18].j= 21
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 259
container[19].j= 13
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 259
container[20].j= 21
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 260
container[21].j= 14
container[21].angle= 333
container[21].value= 255


container[22].bin= 41
container[22].i= 260
container[22].j= 21
container[22].angle= 206
container[22].value= 255


container[23].bin= 63
container[23].i= 261
container[23].j= 14
container[23].angle= 315
container[23].value= 255


container[24].bin= 63
container[24].i= 261
container[24].j= 15
container[24].angle= 315
container[24].value= 255


container[25].bin= 41
container[25].i= 261
container[25].j= 21
container[25].angle= 206
container[25].value= 255


container[26].bin= 66
container[26].i= 262
container[26].j= 15
container[26].angle= 333
container[26].value= 255


container[27].bin= 36
container[27].i= 262
container[27].j= 20
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 263
container[28].j= 15
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 263
container[29].j= 20
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 264
container[30].j= 15
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 264
container[31].j= 20
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 265
container[32].j= 15
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 265
container[33].j= 20
container[33].angle= 180
container[33].value= 255


container[34].bin= 0
container[34].i= 266
container[34].j= 15
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 266
container[35].j= 20
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 267
container[36].j= 15
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 267
container[37].j= 20
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 268
container[38].j= 15
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 268
container[39].j= 20
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 269
container[40].j= 15
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 269
container[41].j= 20
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 270
container[42].j= 15
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 270
container[43].j= 20
container[43].angle= 180
container[43].value= 255


container[44].bin= 66
container[44].i= 271
container[44].j= 16
container[44].angle= 333
container[44].value= 255


container[45].bin= 36
container[45].i= 271
container[45].j= 20
container[45].angle= 180
container[45].value= 255


container[46].bin= 66
container[46].i= 272
container[46].j= 16
container[46].angle= 333
container[46].value= 255


container[47].bin= 30
container[47].i= 272
container[47].j= 21
container[47].angle= 153
container[47].value= 255


container[48].bin= 66
container[48].i= 273
container[48].j= 17
container[48].angle= 333
container[48].value= 255


container[49].bin= 30
container[49].i= 273
container[49].j= 21
container[49].angle= 153
container[49].value= 255


container[50].bin= 63
container[50].i= 274
container[50].j= 17
container[50].angle= 315
container[50].value= 255


container[51].bin= 59
container[51].i= 274
container[51].j= 18
container[51].angle= 296
container[51].value= 255


container[52].bin= 36
container[52].i= 274
container[52].j= 21
container[52].angle= 180
container[52].value= 255


container[53].bin= 59
container[53].i= 275
container[53].j= 19
container[53].angle= 296
container[53].value= 255


container[54].bin= 59
container[54].i= 275
container[54].j= 20
container[54].angle= 296
container[54].value= 255


container[55].bin= 44
container[55].i= 275
container[55].j= 21
container[55].angle= 224
container[55].value= 255


