container[0].bin= 18
container[0].i= 893
container[0].j= 408
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 893
container[1].j= 411
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 894
container[2].j= 407
container[2].angle= 44
container[2].value= 255


container[3].bin= 23
container[3].i= 894
container[3].j= 409
container[3].angle= 116
container[3].value= 255


container[4].bin= 21
container[4].i= 894
container[4].j= 410
container[4].angle= 108
container[4].value= 255


container[5].bin= 0
container[5].i= 895
container[5].j= 406
container[5].angle= 0
container[5].value= 255


container[6].bin= 32
container[6].i= 895
container[6].j= 410
container[6].angle= 161
container[6].value= 255


container[7].bin= 66
container[7].i= 896
container[7].j= 407
container[7].angle= 333
container[7].value= 255


container[8].bin= 27
container[8].i= 896
container[8].j= 411
container[8].angle= 135
container[8].value= 255


container[9].bin= 18
container[9].i= 896
container[9].j= 412
container[9].angle= 90
container[9].value= 255


container[10].bin= 66
container[10].i= 897
container[10].j= 407
container[10].angle= 333
container[10].value= 255


container[11].bin= 27
container[11].i= 897
container[11].j= 413
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 898
container[12].j= 407
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 898
container[13].j= 413
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 899
container[14].j= 408
container[14].angle= 315
container[14].value= 255


container[15].bin= 54
container[15].i= 899
container[15].j= 409
container[15].angle= 270
container[15].value= 255


container[16].bin= 54
container[16].i= 899
container[16].j= 411
container[16].angle= 270
container[16].value= 255


container[17].bin= 44
container[17].i= 899
container[17].j= 413
container[17].angle= 224
container[17].value= 255


container[18].bin= 63
container[18].i= 900
container[18].j= 410
container[18].angle= 315
container[18].value= 255


container[19].bin= 44
container[19].i= 900
container[19].j= 412
container[19].angle= 224
container[19].value= 255


container[20].bin= 0
container[20].i= 901
container[20].j= 410
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 901
container[21].j= 412
container[21].angle= 180
container[21].value= 255


container[22].bin= 68
container[22].i= 902
container[22].j= 410
container[22].angle= 341
container[22].value= 255


container[23].bin= 54
container[23].i= 902
container[23].j= 411
container[23].angle= 270
container[23].value= 255


container[24].bin= 39
container[24].i= 902
container[24].j= 412
container[24].angle= 198
container[24].value= 255


