container[0].bin= 18
container[0].i= 120
container[0].j= 514
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 121
container[1].j= 513
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 121
container[2].j= 515
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 122
container[3].j= 512
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 122
container[4].j= 515
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 123
container[5].j= 512
container[5].angle= 44
container[5].value= 255


container[6].bin= 27
container[6].i= 123
container[6].j= 516
container[6].angle= 135
container[6].value= 255


container[7].bin= 8
container[7].i= 124
container[7].j= 511
container[7].angle= 44
container[7].value= 255


container[8].bin= 27
container[8].i= 124
container[8].j= 517
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 125
container[9].j= 510
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 125
container[10].j= 517
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 126
container[11].j= 510
container[11].angle= 0
container[11].value= 255


container[12].bin= 27
container[12].i= 126
container[12].j= 518
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 127
container[13].j= 510
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 127
container[14].j= 519
container[14].angle= 135
container[14].value= 255


container[15].bin= 0
container[15].i= 128
container[15].j= 510
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 128
container[16].j= 519
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 129
container[17].j= 510
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 129
container[18].j= 520
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 130
container[19].j= 510
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 130
container[20].j= 520
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 131
container[21].j= 510
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 131
container[22].j= 520
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 132
container[23].j= 510
container[23].angle= 341
container[23].value= 255


container[24].bin= 54
container[24].i= 132
container[24].j= 512
container[24].angle= 270
container[24].value= 255


container[25].bin= 63
container[25].i= 132
container[25].j= 513
container[25].angle= 315
container[25].value= 255


container[26].bin= 27
container[26].i= 132
container[26].j= 521
container[26].angle= 135
container[26].value= 255


container[27].bin= 18
container[27].i= 132
container[27].j= 522
container[27].angle= 90
container[27].value= 255


container[28].bin= 66
container[28].i= 133
container[28].j= 513
container[28].angle= 333
container[28].value= 255


container[29].bin= 27
container[29].i= 133
container[29].j= 523
container[29].angle= 135
container[29].value= 255


container[30].bin= 0
container[30].i= 134
container[30].j= 513
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 134
container[31].j= 523
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 135
container[32].j= 514
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 135
container[33].j= 515
container[33].angle= 270
container[33].value= 255


container[34].bin= 27
container[34].i= 135
container[34].j= 524
container[34].angle= 135
container[34].value= 255


container[35].bin= 63
container[35].i= 136
container[35].j= 516
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 136
container[36].j= 525
container[36].angle= 135
container[36].value= 255


container[37].bin= 0
container[37].i= 137
container[37].j= 516
container[37].angle= 0
container[37].value= 255


container[38].bin= 44
container[38].i= 137
container[38].j= 525
container[38].angle= 224
container[38].value= 255


container[39].bin= 63
container[39].i= 138
container[39].j= 517
container[39].angle= 315
container[39].value= 255


container[40].bin= 44
container[40].i= 138
container[40].j= 524
container[40].angle= 224
container[40].value= 255


container[41].bin= 63
container[41].i= 139
container[41].j= 518
container[41].angle= 315
container[41].value= 255


container[42].bin= 36
container[42].i= 139
container[42].j= 523
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 140
container[43].j= 518
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 140
container[44].j= 523
container[44].angle= 180
container[44].value= 255


container[45].bin= 63
container[45].i= 141
container[45].j= 519
container[45].angle= 315
container[45].value= 255


container[46].bin= 54
container[46].i= 141
container[46].j= 520
container[46].angle= 270
container[46].value= 255


container[47].bin= 57
container[47].i= 141
container[47].j= 521
container[47].angle= 288
container[47].value= 255


container[48].bin= 41
container[48].i= 141
container[48].j= 523
container[48].angle= 206
container[48].value= 255


container[49].bin= 50
container[49].i= 142
container[49].j= 522
container[49].angle= 251
container[49].value= 255


container[50].bin= 44
container[50].i= 142
container[50].j= 523
container[50].angle= 224
container[50].value= 255


container[51].bin= 3
container[51].i= 143
container[51].j= 520
container[51].angle= 18
container[51].value= 255


container[52].bin= 39
container[52].i= 143
container[52].j= 522
container[52].angle= 198
container[52].value= 255


container[53].bin= 68
container[53].i= 144
container[53].j= 520
container[53].angle= 341
container[53].value= 255


container[54].bin= 39
container[54].i= 144
container[54].j= 522
container[54].angle= 198
container[54].value= 255


