container[0].bin= 18
container[0].i= 192
container[0].j= 140
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 193
container[1].j= 139
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 193
container[2].j= 141
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 194
container[3].j= 139
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 194
container[4].j= 141
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 195
container[5].j= 139
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 195
container[6].j= 141
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 195
container[7].j= 142
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 196
container[8].j= 139
container[8].angle= 0
container[8].value= 255


container[9].bin= 23
container[9].i= 196
container[9].j= 143
container[9].angle= 116
container[9].value= 255


container[10].bin= 27
container[10].i= 196
container[10].j= 144
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 197
container[11].j= 139
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 197
container[12].j= 144
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 198
container[13].j= 140
container[13].angle= 315
container[13].value= 255


container[14].bin= 32
container[14].i= 198
container[14].j= 144
container[14].angle= 161
container[14].value= 255


container[15].bin= 14
container[15].i= 198
container[15].j= 145
container[15].angle= 71
container[15].value= 255


container[16].bin= 21
container[16].i= 198
container[16].j= 146
container[16].angle= 108
container[16].value= 255


container[17].bin= 63
container[17].i= 199
container[17].j= 141
container[17].angle= 315
container[17].value= 255


container[18].bin= 0
container[18].i= 200
container[18].j= 141
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 200
container[19].j= 146
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 201
container[20].j= 142
container[20].angle= 315
container[20].value= 255


container[21].bin= 54
container[21].i= 201
container[21].j= 143
container[21].angle= 270
container[21].value= 255


container[22].bin= 36
container[22].i= 201
container[22].j= 146
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 202
container[23].j= 144
container[23].angle= 315
container[23].value= 255


container[24].bin= 0
container[24].i= 203
container[24].j= 144
container[24].angle= 0
container[24].value= 255


container[25].bin= 66
container[25].i= 204
container[25].j= 145
container[25].angle= 333
container[25].value= 255


container[26].bin= 27
container[26].i= 204
container[26].j= 147
container[26].angle= 135
container[26].value= 255


container[27].bin= 66
container[27].i= 205
container[27].j= 145
container[27].angle= 333
container[27].value= 255


container[28].bin= 27
container[28].i= 205
container[28].j= 148
container[28].angle= 135
container[28].value= 255


container[29].bin= 0
container[29].i= 206
container[29].j= 145
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 206
container[30].j= 148
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 207
container[31].j= 146
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 207
container[32].j= 147
container[32].angle= 270
container[32].value= 255


container[33].bin= 44
container[33].i= 207
container[33].j= 148
container[33].angle= 224
container[33].value= 255


