container[0].bin= 14
container[0].i= 631
container[0].j= 207
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 631
container[1].j= 208
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 632
container[2].j= 206
container[2].angle= 18
container[2].value= 255


container[3].bin= 27
container[3].i= 632
container[3].j= 208
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 633
container[4].j= 206
container[4].angle= 0
container[4].value= 255


container[5].bin= 68
container[5].i= 634
container[5].j= 206
container[5].angle= 341
container[5].value= 255


container[6].bin= 44
container[6].i= 634
container[6].j= 208
container[6].angle= 224
container[6].value= 255


