container[0].bin= 18
container[0].i= 570
container[0].j= 172
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 571
container[1].j= 171
container[1].angle= 0
container[1].value= 255


container[2].bin= 21
container[2].i= 571
container[2].j= 173
container[2].angle= 108
container[2].value= 255


container[3].bin= 12
container[3].i= 571
container[3].j= 174
container[3].angle= 63
container[3].value= 255


container[4].bin= 18
container[4].i= 571
container[4].j= 175
container[4].angle= 90
container[4].value= 255


container[5].bin= 23
container[5].i= 571
container[5].j= 176
container[5].angle= 116
container[5].value= 255


container[6].bin= 21
container[6].i= 571
container[6].j= 177
container[6].angle= 108
container[6].value= 255


container[7].bin= 3
container[7].i= 572
container[7].j= 172
container[7].angle= 18
container[7].value= 255


container[8].bin= 68
container[8].i= 573
container[8].j= 172
container[8].angle= 341
container[8].value= 255


container[9].bin= 48
container[9].i= 573
container[9].j= 175
container[9].angle= 243
container[9].value= 255


container[10].bin= 48
container[10].i= 573
container[10].j= 176
container[10].angle= 243
container[10].value= 255


container[11].bin= 50
container[11].i= 573
container[11].j= 177
container[11].angle= 251
container[11].value= 255


