container[0].bin= 18
container[0].i= 414
container[0].j= 615
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 414
container[1].j= 616
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 414
container[2].j= 617
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 414
container[3].j= 618
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 414
container[4].j= 619
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 414
container[5].j= 620
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 415
container[6].j= 614
container[6].angle= 44
container[6].value= 255


container[7].bin= 27
container[7].i= 415
container[7].j= 621
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 416
container[8].j= 613
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 416
container[9].j= 621
container[9].angle= 180
container[9].value= 255


container[10].bin= 63
container[10].i= 417
container[10].j= 614
container[10].angle= 315
container[10].value= 255


container[11].bin= 54
container[11].i= 417
container[11].j= 615
container[11].angle= 270
container[11].value= 255


container[12].bin= 27
container[12].i= 417
container[12].j= 622
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 417
container[13].j= 623
container[13].angle= 90
container[13].value= 255


container[14].bin= 63
container[14].i= 418
container[14].j= 616
container[14].angle= 315
container[14].value= 255


container[15].bin= 27
container[15].i= 418
container[15].j= 624
container[15].angle= 135
container[15].value= 255


container[16].bin= 0
container[16].i= 419
container[16].j= 616
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 419
container[17].j= 624
container[17].angle= 180
container[17].value= 255


container[18].bin= 66
container[18].i= 420
container[18].j= 617
container[18].angle= 333
container[18].value= 255


container[19].bin= 36
container[19].i= 420
container[19].j= 624
container[19].angle= 180
container[19].value= 255


container[20].bin= 66
container[20].i= 421
container[20].j= 617
container[20].angle= 333
container[20].value= 255


container[21].bin= 36
container[21].i= 421
container[21].j= 624
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 422
container[22].j= 617
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 422
container[23].j= 624
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 423
container[24].j= 617
container[24].angle= 0
container[24].value= 255


container[25].bin= 54
container[25].i= 423
container[25].j= 623
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 423
container[26].j= 624
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 424
container[27].j= 617
container[27].angle= 0
container[27].value= 255


container[28].bin= 44
container[28].i= 424
container[28].j= 622
container[28].angle= 224
container[28].value= 255


container[29].bin= 0
container[29].i= 425
container[29].j= 617
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 425
container[30].j= 621
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 426
container[31].j= 618
container[31].angle= 315
container[31].value= 255


container[32].bin= 36
container[32].i= 426
container[32].j= 621
container[32].angle= 180
container[32].value= 255


container[33].bin= 63
container[33].i= 427
container[33].j= 619
container[33].angle= 315
container[33].value= 255


container[34].bin= 0
container[34].i= 428
container[34].j= 619
container[34].angle= 0
container[34].value= 255


container[35].bin= 0
container[35].i= 429
container[35].j= 619
container[35].angle= 0
container[35].value= 255


container[36].bin= 41
container[36].i= 429
container[36].j= 621
container[36].angle= 206
container[36].value= 255


container[37].bin= 0
container[37].i= 430
container[37].j= 619
container[37].angle= 0
container[37].value= 255


container[38].bin= 41
container[38].i= 430
container[38].j= 621
container[38].angle= 206
container[38].value= 255


container[39].bin= 0
container[39].i= 431
container[39].j= 619
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 431
container[40].j= 621
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 432
container[41].j= 619
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 432
container[42].j= 621
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 433
container[43].j= 619
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 433
container[44].j= 621
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 434
container[45].j= 619
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 434
container[46].j= 621
container[46].angle= 180
container[46].value= 255


container[47].bin= 0
container[47].i= 435
container[47].j= 619
container[47].angle= 0
container[47].value= 255


container[48].bin= 30
container[48].i= 435
container[48].j= 621
container[48].angle= 153
container[48].value= 255


container[49].bin= 0
container[49].i= 436
container[49].j= 619
container[49].angle= 0
container[49].value= 255


container[50].bin= 30
container[50].i= 436
container[50].j= 621
container[50].angle= 153
container[50].value= 255


container[51].bin= 0
container[51].i= 437
container[51].j= 619
container[51].angle= 0
container[51].value= 255


container[52].bin= 63
container[52].i= 438
container[52].j= 620
container[52].angle= 315
container[52].value= 255


container[53].bin= 44
container[53].i= 438
container[53].j= 621
container[53].angle= 224
container[53].value= 255


