container[0].bin= 8
container[0].i= 765
container[0].j= 317
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 765
container[1].j= 318
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 765
container[2].j= 319
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 766
container[3].j= 316
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 766
container[4].j= 319
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 767
container[5].j= 317
container[5].angle= 333
container[5].value= 255


container[6].bin= 36
container[6].i= 767
container[6].j= 319
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 768
container[7].j= 317
container[7].angle= 333
container[7].value= 255


container[8].bin= 0
container[8].i= 769
container[8].j= 317
container[8].angle= 0
container[8].value= 255


container[9].bin= 63
container[9].i= 770
container[9].j= 318
container[9].angle= 315
container[9].value= 255


container[10].bin= 27
container[10].i= 771
container[10].j= 321
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 772
container[11].j= 319
container[11].angle= 0
container[11].value= 255


container[12].bin= 66
container[12].i= 773
container[12].j= 320
container[12].angle= 333
container[12].value= 255


container[13].bin= 66
container[13].i= 774
container[13].j= 320
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 774
container[14].j= 322
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 775
container[15].j= 320
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 775
container[16].j= 322
container[16].angle= 180
container[16].value= 255


container[17].bin= 68
container[17].i= 776
container[17].j= 320
container[17].angle= 341
container[17].value= 255


container[18].bin= 54
container[18].i= 776
container[18].j= 321
container[18].angle= 270
container[18].value= 255


container[19].bin= 39
container[19].i= 776
container[19].j= 322
container[19].angle= 198
container[19].value= 255


