container[0].bin= 18
container[0].i= 363
container[0].j= 380
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 363
container[1].j= 381
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 364
container[2].j= 379
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 364
container[3].j= 382
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 365
container[4].j= 378
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 365
container[5].j= 382
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 366
container[6].j= 378
container[6].angle= 0
container[6].value= 255


container[7].bin= 44
container[7].i= 366
container[7].j= 382
container[7].angle= 224
container[7].value= 255


container[8].bin= 0
container[8].i= 367
container[8].j= 378
container[8].angle= 0
container[8].value= 255


container[9].bin= 44
container[9].i= 367
container[9].j= 381
container[9].angle= 224
container[9].value= 255


container[10].bin= 0
container[10].i= 368
container[10].j= 378
container[10].angle= 0
container[10].value= 255


container[11].bin= 63
container[11].i= 369
container[11].j= 379
container[11].angle= 315
container[11].value= 255


container[12].bin= 44
container[12].i= 369
container[12].j= 380
container[12].angle= 224
container[12].value= 255


