container[0].bin= 18
container[0].i= 441
container[0].j= 383
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 442
container[1].j= 382
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 442
container[2].j= 384
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 442
container[3].j= 385
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 443
container[4].j= 381
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 443
container[5].j= 385
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 444
container[6].j= 381
container[6].angle= 0
container[6].value= 255


container[7].bin= 54
container[7].i= 444
container[7].j= 384
container[7].angle= 270
container[7].value= 255


container[8].bin= 44
container[8].i= 444
container[8].j= 385
container[8].angle= 224
container[8].value= 255


container[9].bin= 0
container[9].i= 445
container[9].j= 381
container[9].angle= 0
container[9].value= 255


container[10].bin= 44
container[10].i= 445
container[10].j= 383
container[10].angle= 224
container[10].value= 255


container[11].bin= 0
container[11].i= 446
container[11].j= 381
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 446
container[12].j= 383
container[12].angle= 180
container[12].value= 255


container[13].bin= 68
container[13].i= 447
container[13].j= 381
container[13].angle= 341
container[13].value= 255


container[14].bin= 54
container[14].i= 447
container[14].j= 382
container[14].angle= 270
container[14].value= 255


container[15].bin= 39
container[15].i= 447
container[15].j= 383
container[15].angle= 198
container[15].value= 255


