container[0].bin= 8
container[0].i= 207
container[0].j= 415
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 207
container[1].j= 416
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 208
container[2].j= 414
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 209
container[3].j= 414
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 209
container[4].j= 417
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 210
container[5].j= 415
container[5].angle= 333
container[5].value= 255


container[6].bin= 27
container[6].i= 210
container[6].j= 418
container[6].angle= 135
container[6].value= 255


container[7].bin= 63
container[7].i= 211
container[7].j= 415
container[7].angle= 315
container[7].value= 255


container[8].bin= 30
container[8].i= 211
container[8].j= 418
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 212
container[9].j= 416
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 212
container[10].j= 419
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 213
container[11].j= 417
container[11].angle= 333
container[11].value= 255


container[12].bin= 63
container[12].i= 214
container[12].j= 417
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 214
container[13].j= 419
container[13].angle= 224
container[13].value= 255


