container[0].bin= 8
container[0].i= 267
container[0].j= 270
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 267
container[1].j= 271
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 268
container[2].j= 269
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 269
container[3].j= 269
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 269
container[4].j= 272
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 270
container[5].j= 269
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 270
container[6].j= 272
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 271
container[7].j= 269
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 271
container[8].j= 273
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 272
container[9].j= 270
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 272
container[10].j= 273
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 273
container[11].j= 270
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 273
container[12].j= 273
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 274
container[13].j= 270
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 274
container[14].j= 274
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 275
container[15].j= 270
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 275
container[16].j= 274
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 276
container[17].j= 271
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 276
container[18].j= 274
container[18].angle= 180
container[18].value= 255


container[19].bin= 66
container[19].i= 277
container[19].j= 271
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 277
container[20].j= 275
container[20].angle= 153
container[20].value= 255


container[21].bin= 66
container[21].i= 278
container[21].j= 272
container[21].angle= 333
container[21].value= 255


container[22].bin= 30
container[22].i= 278
container[22].j= 275
container[22].angle= 153
container[22].value= 255


container[23].bin= 66
container[23].i= 279
container[23].j= 272
container[23].angle= 333
container[23].value= 255


container[24].bin= 30
container[24].i= 279
container[24].j= 276
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 280
container[25].j= 272
container[25].angle= 0
container[25].value= 255


container[26].bin= 30
container[26].i= 280
container[26].j= 276
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 281
container[27].j= 273
container[27].angle= 333
container[27].value= 255


container[28].bin= 27
container[28].i= 281
container[28].j= 277
container[28].angle= 135
container[28].value= 255


container[29].bin= 66
container[29].i= 282
container[29].j= 273
container[29].angle= 333
container[29].value= 255


container[30].bin= 27
container[30].i= 282
container[30].j= 278
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 283
container[31].j= 273
container[31].angle= 0
container[31].value= 255


container[32].bin= 30
container[32].i= 283
container[32].j= 279
container[32].angle= 153
container[32].value= 255


container[33].bin= 66
container[33].i= 284
container[33].j= 274
container[33].angle= 333
container[33].value= 255


container[34].bin= 27
container[34].i= 284
container[34].j= 279
container[34].angle= 135
container[34].value= 255


container[35].bin= 27
container[35].i= 284
container[35].j= 280
container[35].angle= 135
container[35].value= 255


container[36].bin= 66
container[36].i= 285
container[36].j= 274
container[36].angle= 333
container[36].value= 255


container[37].bin= 27
container[37].i= 285
container[37].j= 280
container[37].angle= 135
container[37].value= 255


container[38].bin= 27
container[38].i= 285
container[38].j= 281
container[38].angle= 135
container[38].value= 255


container[39].bin= 66
container[39].i= 286
container[39].j= 275
container[39].angle= 333
container[39].value= 255


container[40].bin= 30
container[40].i= 286
container[40].j= 281
container[40].angle= 153
container[40].value= 255


container[41].bin= 63
container[41].i= 287
container[41].j= 275
container[41].angle= 315
container[41].value= 255


container[42].bin= 63
container[42].i= 287
container[42].j= 276
container[42].angle= 315
container[42].value= 255


container[43].bin= 30
container[43].i= 287
container[43].j= 282
container[43].angle= 153
container[43].value= 255


container[44].bin= 66
container[44].i= 288
container[44].j= 276
container[44].angle= 333
container[44].value= 255


container[45].bin= 27
container[45].i= 288
container[45].j= 282
container[45].angle= 135
container[45].value= 255


container[46].bin= 27
container[46].i= 288
container[46].j= 283
container[46].angle= 135
container[46].value= 255


container[47].bin= 66
container[47].i= 289
container[47].j= 277
container[47].angle= 333
container[47].value= 255


container[48].bin= 27
container[48].i= 289
container[48].j= 283
container[48].angle= 135
container[48].value= 255


container[49].bin= 27
container[49].i= 289
container[49].j= 284
container[49].angle= 135
container[49].value= 255


container[50].bin= 66
container[50].i= 290
container[50].j= 277
container[50].angle= 333
container[50].value= 255


container[51].bin= 30
container[51].i= 290
container[51].j= 284
container[51].angle= 153
container[51].value= 255


container[52].bin= 0
container[52].i= 291
container[52].j= 277
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 291
container[53].j= 285
container[53].angle= 153
container[53].value= 255


container[54].bin= 66
container[54].i= 292
container[54].j= 278
container[54].angle= 333
container[54].value= 255


container[55].bin= 30
container[55].i= 292
container[55].j= 285
container[55].angle= 153
container[55].value= 255


container[56].bin= 66
container[56].i= 293
container[56].j= 278
container[56].angle= 333
container[56].value= 255


container[57].bin= 36
container[57].i= 293
container[57].j= 285
container[57].angle= 180
container[57].value= 255


container[58].bin= 0
container[58].i= 294
container[58].j= 278
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 294
container[59].j= 285
container[59].angle= 180
container[59].value= 255


container[60].bin= 0
container[60].i= 295
container[60].j= 278
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 295
container[61].j= 285
container[61].angle= 180
container[61].value= 255


container[62].bin= 66
container[62].i= 296
container[62].j= 279
container[62].angle= 333
container[62].value= 255


container[63].bin= 36
container[63].i= 296
container[63].j= 285
container[63].angle= 180
container[63].value= 255


container[64].bin= 66
container[64].i= 297
container[64].j= 279
container[64].angle= 333
container[64].value= 255


container[65].bin= 36
container[65].i= 297
container[65].j= 285
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 298
container[66].j= 279
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 298
container[67].j= 285
container[67].angle= 180
container[67].value= 255


container[68].bin= 66
container[68].i= 299
container[68].j= 280
container[68].angle= 333
container[68].value= 255


container[69].bin= 36
container[69].i= 299
container[69].j= 285
container[69].angle= 180
container[69].value= 255


container[70].bin= 66
container[70].i= 300
container[70].j= 280
container[70].angle= 333
container[70].value= 255


container[71].bin= 36
container[71].i= 300
container[71].j= 285
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 301
container[72].j= 280
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 301
container[73].j= 285
container[73].angle= 180
container[73].value= 255


container[74].bin= 66
container[74].i= 302
container[74].j= 281
container[74].angle= 333
container[74].value= 255


container[75].bin= 36
container[75].i= 302
container[75].j= 285
container[75].angle= 180
container[75].value= 255


container[76].bin= 63
container[76].i= 303
container[76].j= 281
container[76].angle= 315
container[76].value= 255


container[77].bin= 63
container[77].i= 303
container[77].j= 282
container[77].angle= 315
container[77].value= 255


container[78].bin= 36
container[78].i= 303
container[78].j= 285
container[78].angle= 180
container[78].value= 255


container[79].bin= 63
container[79].i= 304
container[79].j= 282
container[79].angle= 315
container[79].value= 255


container[80].bin= 63
container[80].i= 304
container[80].j= 283
container[80].angle= 315
container[80].value= 255


container[81].bin= 41
container[81].i= 304
container[81].j= 285
container[81].angle= 206
container[81].value= 255


container[82].bin= 63
container[82].i= 305
container[82].j= 283
container[82].angle= 315
container[82].value= 255


container[83].bin= 54
container[83].i= 305
container[83].j= 284
container[83].angle= 270
container[83].value= 255


container[84].bin= 44
container[84].i= 305
container[84].j= 285
container[84].angle= 224
container[84].value= 255


