container[0].bin= 18
container[0].i= 640
container[0].j= 244
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 641
container[1].j= 243
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 641
container[2].j= 245
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 642
container[3].j= 243
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 642
container[4].j= 245
container[4].angle= 180
container[4].value= 255


container[5].bin= 18
container[5].i= 643
container[5].j= 241
container[5].angle= 90
container[5].value= 255


container[6].bin= 18
container[6].i= 643
container[6].j= 242
container[6].angle= 90
container[6].value= 255


container[7].bin= 8
container[7].i= 643
container[7].j= 243
container[7].angle= 44
container[7].value= 255


container[8].bin= 36
container[8].i= 643
container[8].j= 245
container[8].angle= 180
container[8].value= 255


container[9].bin= 8
container[9].i= 644
container[9].j= 240
container[9].angle= 44
container[9].value= 255


container[10].bin= 0
container[10].i= 645
container[10].j= 239
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 645
container[11].j= 244
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 646
container[12].j= 239
container[12].angle= 0
container[12].value= 255


container[13].bin= 44
container[13].i= 646
container[13].j= 244
container[13].angle= 224
container[13].value= 255


container[14].bin= 0
container[14].i= 647
container[14].j= 239
container[14].angle= 0
container[14].value= 255


container[15].bin= 44
container[15].i= 647
container[15].j= 243
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 648
container[16].j= 239
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 648
container[17].j= 242
container[17].angle= 180
container[17].value= 255


container[18].bin= 66
container[18].i= 649
container[18].j= 240
container[18].angle= 333
container[18].value= 255


container[19].bin= 36
container[19].i= 649
container[19].j= 242
container[19].angle= 180
container[19].value= 255


container[20].bin= 66
container[20].i= 650
container[20].j= 240
container[20].angle= 333
container[20].value= 255


container[21].bin= 0
container[21].i= 651
container[21].j= 240
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 651
container[22].j= 243
container[22].angle= 153
container[22].value= 255


container[23].bin= 0
container[23].i= 652
container[23].j= 240
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 652
container[24].j= 243
container[24].angle= 180
container[24].value= 255


container[25].bin= 0
container[25].i= 653
container[25].j= 240
container[25].angle= 0
container[25].value= 255


container[26].bin= 44
container[26].i= 653
container[26].j= 242
container[26].angle= 224
container[26].value= 255


container[27].bin= 44
container[27].i= 653
container[27].j= 243
container[27].angle= 224
container[27].value= 255


container[28].bin= 0
container[28].i= 654
container[28].j= 240
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 654
container[29].j= 242
container[29].angle= 180
container[29].value= 255


container[30].bin= 68
container[30].i= 655
container[30].j= 240
container[30].angle= 341
container[30].value= 255


