container[0].bin= 3
container[0].i= 674
container[0].j= 435
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 674
container[1].j= 436
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 674
container[2].j= 437
container[2].angle= 135
container[2].value= 255


container[3].bin= 68
container[3].i= 675
container[3].j= 435
container[3].angle= 341
container[3].value= 255


container[4].bin= 66
container[4].i= 676
container[4].j= 436
container[4].angle= 333
container[4].value= 255


container[5].bin= 36
container[5].i= 676
container[5].j= 438
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 677
container[6].j= 436
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 677
container[7].j= 438
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 678
container[8].j= 436
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 678
container[9].j= 438
container[9].angle= 180
container[9].value= 255


container[10].bin= 68
container[10].i= 679
container[10].j= 436
container[10].angle= 341
container[10].value= 255


container[11].bin= 54
container[11].i= 679
container[11].j= 437
container[11].angle= 270
container[11].value= 255


container[12].bin= 39
container[12].i= 679
container[12].j= 438
container[12].angle= 198
container[12].value= 255


