container[0].bin= 18
container[0].i= 893
container[0].j= 554
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 894
container[1].j= 553
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 894
container[2].j= 555
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 895
container[3].j= 553
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 895
container[4].j= 555
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 896
container[5].j= 553
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 896
container[6].j= 555
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 897
container[7].j= 553
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 897
container[8].j= 555
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 898
container[9].j= 553
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 898
container[10].j= 555
container[10].angle= 180
container[10].value= 255


container[11].bin= 68
container[11].i= 899
container[11].j= 553
container[11].angle= 341
container[11].value= 255


container[12].bin= 54
container[12].i= 899
container[12].j= 554
container[12].angle= 270
container[12].value= 255


container[13].bin= 39
container[13].i= 899
container[13].j= 555
container[13].angle= 198
container[13].value= 255


