container[0].bin= 8
container[0].i= 64
container[0].j= 296
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 64
container[1].j= 297
container[1].angle= 108
container[1].value= 255


container[2].bin= 0
container[2].i= 65
container[2].j= 296
container[2].angle= 0
container[2].value= 255


container[3].bin= 36
container[3].i= 65
container[3].j= 298
container[3].angle= 180
container[3].value= 255


container[4].bin= 66
container[4].i= 66
container[4].j= 296
container[4].angle= 333
container[4].value= 255


container[5].bin= 27
container[5].i= 66
container[5].j= 298
container[5].angle= 135
container[5].value= 255


container[6].bin= 18
container[6].i= 66
container[6].j= 299
container[6].angle= 90
container[6].value= 255


container[7].bin= 0
container[7].i= 67
container[7].j= 296
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 67
container[8].j= 300
container[8].angle= 135
container[8].value= 255


container[9].bin= 0
container[9].i= 68
container[9].j= 296
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 68
container[10].j= 300
container[10].angle= 180
container[10].value= 255


container[11].bin= 63
container[11].i= 69
container[11].j= 297
container[11].angle= 315
container[11].value= 255


container[12].bin= 27
container[12].i= 69
container[12].j= 301
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 69
container[13].j= 302
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 69
container[14].j= 303
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 69
container[15].j= 304
container[15].angle= 90
container[15].value= 255


container[16].bin= 18
container[16].i= 69
container[16].j= 305
container[16].angle= 90
container[16].value= 255


container[17].bin= 18
container[17].i= 69
container[17].j= 306
container[17].angle= 90
container[17].value= 255


container[18].bin= 18
container[18].i= 69
container[18].j= 307
container[18].angle= 90
container[18].value= 255


container[19].bin= 63
container[19].i= 70
container[19].j= 298
container[19].angle= 315
container[19].value= 255


container[20].bin= 27
container[20].i= 70
container[20].j= 308
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 71
container[21].j= 298
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 71
container[22].j= 308
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 72
container[23].j= 298
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 72
container[24].j= 309
container[24].angle= 153
container[24].value= 255


container[25].bin= 0
container[25].i= 73
container[25].j= 298
container[25].angle= 0
container[25].value= 255


container[26].bin= 32
container[26].i= 73
container[26].j= 309
container[26].angle= 161
container[26].value= 255


container[27].bin= 27
container[27].i= 73
container[27].j= 310
container[27].angle= 135
container[27].value= 255


container[28].bin= 0
container[28].i= 74
container[28].j= 298
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 74
container[29].j= 308
container[29].angle= 180
container[29].value= 255


container[30].bin= 27
container[30].i= 74
container[30].j= 310
container[30].angle= 135
container[30].value= 255


container[31].bin= 63
container[31].i= 75
container[31].j= 299
container[31].angle= 315
container[31].value= 255


container[32].bin= 32
container[32].i= 75
container[32].j= 310
container[32].angle= 161
container[32].value= 255


container[33].bin= 63
container[33].i= 76
container[33].j= 300
container[33].angle= 315
container[33].value= 255


container[34].bin= 36
container[34].i= 76
container[34].j= 310
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 77
container[35].j= 300
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 77
container[36].j= 310
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 78
container[37].j= 300
container[37].angle= 0
container[37].value= 255


container[38].bin= 44
container[38].i= 78
container[38].j= 310
container[38].angle= 224
container[38].value= 255


container[39].bin= 0
container[39].i= 79
container[39].j= 300
container[39].angle= 0
container[39].value= 255


container[40].bin= 44
container[40].i= 79
container[40].j= 309
container[40].angle= 224
container[40].value= 255


container[41].bin= 0
container[41].i= 80
container[41].j= 300
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 80
container[42].j= 308
container[42].angle= 180
container[42].value= 255


container[43].bin= 66
container[43].i= 81
container[43].j= 301
container[43].angle= 333
container[43].value= 255


container[44].bin= 36
container[44].i= 81
container[44].j= 308
container[44].angle= 180
container[44].value= 255


container[45].bin= 66
container[45].i= 82
container[45].j= 301
container[45].angle= 333
container[45].value= 255


container[46].bin= 36
container[46].i= 82
container[46].j= 308
container[46].angle= 180
container[46].value= 255


container[47].bin= 0
container[47].i= 83
container[47].j= 301
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 83
container[48].j= 308
container[48].angle= 180
container[48].value= 255


container[49].bin= 66
container[49].i= 84
container[49].j= 302
container[49].angle= 333
container[49].value= 255


container[50].bin= 27
container[50].i= 84
container[50].j= 309
container[50].angle= 135
container[50].value= 255


container[51].bin= 63
container[51].i= 85
container[51].j= 302
container[51].angle= 315
container[51].value= 255


container[52].bin= 63
container[52].i= 85
container[52].j= 303
container[52].angle= 315
container[52].value= 255


container[53].bin= 27
container[53].i= 85
container[53].j= 310
container[53].angle= 135
container[53].value= 255


container[54].bin= 66
container[54].i= 86
container[54].j= 303
container[54].angle= 333
container[54].value= 255


container[55].bin= 36
container[55].i= 86
container[55].j= 310
container[55].angle= 180
container[55].value= 255


container[56].bin= 66
container[56].i= 87
container[56].j= 304
container[56].angle= 333
container[56].value= 255


container[57].bin= 30
container[57].i= 87
container[57].j= 311
container[57].angle= 153
container[57].value= 255


container[58].bin= 66
container[58].i= 88
container[58].j= 304
container[58].angle= 333
container[58].value= 255


container[59].bin= 30
container[59].i= 88
container[59].j= 311
container[59].angle= 153
container[59].value= 255


container[60].bin= 0
container[60].i= 89
container[60].j= 304
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 89
container[61].j= 311
container[61].angle= 180
container[61].value= 255


container[62].bin= 63
container[62].i= 90
container[62].j= 305
container[62].angle= 315
container[62].value= 255


container[63].bin= 54
container[63].i= 90
container[63].j= 310
container[63].angle= 270
container[63].value= 255


container[64].bin= 44
container[64].i= 90
container[64].j= 311
container[64].angle= 224
container[64].value= 255


container[65].bin= 63
container[65].i= 91
container[65].j= 306
container[65].angle= 315
container[65].value= 255


container[66].bin= 44
container[66].i= 91
container[66].j= 309
container[66].angle= 224
container[66].value= 255


container[67].bin= 0
container[67].i= 92
container[67].j= 306
container[67].angle= 0
container[67].value= 255


container[68].bin= 63
container[68].i= 93
container[68].j= 307
container[68].angle= 315
container[68].value= 255


container[69].bin= 44
container[69].i= 93
container[69].j= 308
container[69].angle= 224
container[69].value= 255


