container[0].bin= 18
container[0].i= 192
container[0].j= 246
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 193
container[1].j= 245
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 193
container[2].j= 247
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 194
container[3].j= 245
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 194
container[4].j= 247
container[4].angle= 180
container[4].value= 255


container[5].bin= 8
container[5].i= 195
container[5].j= 245
container[5].angle= 44
container[5].value= 255


container[6].bin= 36
container[6].i= 195
container[6].j= 247
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 196
container[7].j= 244
container[7].angle= 44
container[7].value= 255


container[8].bin= 0
container[8].i= 197
container[8].j= 243
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 197
container[9].j= 246
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 198
container[10].j= 243
container[10].angle= 0
container[10].value= 255


container[11].bin= 44
container[11].i= 198
container[11].j= 246
container[11].angle= 224
container[11].value= 255


container[12].bin= 0
container[12].i= 199
container[12].j= 243
container[12].angle= 0
container[12].value= 255


container[13].bin= 44
container[13].i= 199
container[13].j= 245
container[13].angle= 224
container[13].value= 255


container[14].bin= 0
container[14].i= 200
container[14].j= 243
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 200
container[15].j= 245
container[15].angle= 180
container[15].value= 255


container[16].bin= 68
container[16].i= 201
container[16].j= 243
container[16].angle= 341
container[16].value= 255


container[17].bin= 54
container[17].i= 201
container[17].j= 244
container[17].angle= 270
container[17].value= 255


container[18].bin= 39
container[18].i= 201
container[18].j= 245
container[18].angle= 198
container[18].value= 255


