container[0].bin= 18
container[0].i= 274
container[0].j= 0
container[0].angle= 90
container[0].value= 255


container[1].bin= 0
container[1].i= 275
container[1].j= 0
container[1].angle= 0
container[1].value= 255


container[2].bin= 0
container[2].i= 276
container[2].j= 0
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 277
container[3].j= 0
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 278
container[4].j= 0
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 279
container[5].j= 1
container[5].angle= 153
container[5].value= 255


container[6].bin= 27
container[6].i= 280
container[6].j= 1
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 280
container[7].j= 2
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 280
container[8].j= 3
container[8].angle= 90
container[8].value= 255


container[9].bin= 23
container[9].i= 280
container[9].j= 4
container[9].angle= 116
container[9].value= 255


container[10].bin= 18
container[10].i= 280
container[10].j= 5
container[10].angle= 90
container[10].value= 255


container[11].bin= 23
container[11].i= 281
container[11].j= 6
container[11].angle= 116
container[11].value= 255


container[12].bin= 27
container[12].i= 281
container[12].j= 7
container[12].angle= 135
container[12].value= 255


container[13].bin= 27
container[13].i= 282
container[13].j= 7
container[13].angle= 135
container[13].value= 255


container[14].bin= 27
container[14].i= 282
container[14].j= 8
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 283
container[15].j= 8
container[15].angle= 135
container[15].value= 255


container[16].bin= 27
container[16].i= 283
container[16].j= 9
container[16].angle= 135
container[16].value= 255


container[17].bin= 27
container[17].i= 284
container[17].j= 9
container[17].angle= 135
container[17].value= 255


container[18].bin= 27
container[18].i= 284
container[18].j= 10
container[18].angle= 135
container[18].value= 255


container[19].bin= 30
container[19].i= 285
container[19].j= 10
container[19].angle= 153
container[19].value= 255


container[20].bin= 54
container[20].i= 286
container[20].j= 0
container[20].angle= 270
container[20].value= 255


container[21].bin= 54
container[21].i= 286
container[21].j= 1
container[21].angle= 270
container[21].value= 255


container[22].bin= 54
container[22].i= 286
container[22].j= 2
container[22].angle= 270
container[22].value= 255


container[23].bin= 54
container[23].i= 286
container[23].j= 3
container[23].angle= 270
container[23].value= 255


container[24].bin= 54
container[24].i= 286
container[24].j= 4
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 286
container[25].j= 5
container[25].angle= 270
container[25].value= 255


container[26].bin= 54
container[26].i= 286
container[26].j= 6
container[26].angle= 270
container[26].value= 255


container[27].bin= 30
container[27].i= 286
container[27].j= 11
container[27].angle= 153
container[27].value= 255


container[28].bin= 59
container[28].i= 287
container[28].j= 7
container[28].angle= 296
container[28].value= 255


container[29].bin= 63
container[29].i= 287
container[29].j= 8
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 287
container[30].j= 11
container[30].angle= 135
container[30].value= 255


container[31].bin= 27
container[31].i= 287
container[31].j= 12
container[31].angle= 135
container[31].value= 255


container[32].bin= 63
container[32].i= 288
container[32].j= 8
container[32].angle= 315
container[32].value= 255


container[33].bin= 63
container[33].i= 288
container[33].j= 9
container[33].angle= 315
container[33].value= 255


container[34].bin= 27
container[34].i= 288
container[34].j= 12
container[34].angle= 135
container[34].value= 255


container[35].bin= 27
container[35].i= 288
container[35].j= 13
container[35].angle= 135
container[35].value= 255


container[36].bin= 66
container[36].i= 289
container[36].j= 9
container[36].angle= 333
container[36].value= 255


container[37].bin= 30
container[37].i= 289
container[37].j= 13
container[37].angle= 153
container[37].value= 255


container[38].bin= 66
container[38].i= 290
container[38].j= 10
container[38].angle= 333
container[38].value= 255


container[39].bin= 30
container[39].i= 290
container[39].j= 14
container[39].angle= 153
container[39].value= 255


container[40].bin= 63
container[40].i= 291
container[40].j= 10
container[40].angle= 315
container[40].value= 255


container[41].bin= 63
container[41].i= 291
container[41].j= 11
container[41].angle= 315
container[41].value= 255


container[42].bin= 30
container[42].i= 291
container[42].j= 14
container[42].angle= 153
container[42].value= 255


container[43].bin= 63
container[43].i= 292
container[43].j= 11
container[43].angle= 315
container[43].value= 255


container[44].bin= 63
container[44].i= 292
container[44].j= 12
container[44].angle= 315
container[44].value= 255


container[45].bin= 36
container[45].i= 292
container[45].j= 14
container[45].angle= 180
container[45].value= 255


container[46].bin= 66
container[46].i= 293
container[46].j= 12
container[46].angle= 333
container[46].value= 255


container[47].bin= 63
container[47].i= 294
container[47].j= 13
container[47].angle= 315
container[47].value= 255


container[48].bin= 44
container[48].i= 294
container[48].j= 14
container[48].angle= 224
container[48].value= 255


