container[0].bin= 18
container[0].i= 598
container[0].j= 488
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 598
container[1].j= 492
container[1].angle= 90
container[1].value= 255


container[2].bin= 3
container[2].i= 599
container[2].j= 487
container[2].angle= 18
container[2].value= 255


container[3].bin= 32
container[3].i= 599
container[3].j= 489
container[3].angle= 161
container[3].value= 255


container[4].bin= 0
container[4].i= 599
container[4].j= 491
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 600
container[5].j= 487
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 600
container[6].j= 489
container[6].angle= 180
container[6].value= 255


container[7].bin= 3
container[7].i= 600
container[7].j= 492
container[7].angle= 18
container[7].value= 255


container[8].bin= 5
container[8].i= 601
container[8].j= 487
container[8].angle= 26
container[8].value= 255


container[9].bin= 18
container[9].i= 601
container[9].j= 488
container[9].angle= 90
container[9].value= 255


container[10].bin= 27
container[10].i= 601
container[10].j= 489
container[10].angle= 135
container[10].value= 255


container[11].bin= 18
container[11].i= 601
container[11].j= 490
container[11].angle= 90
container[11].value= 255


container[12].bin= 12
container[12].i= 601
container[12].j= 491
container[12].angle= 63
container[12].value= 255


container[13].bin= 8
container[13].i= 601
container[13].j= 492
container[13].angle= 44
container[13].value= 255


container[14].bin= 30
container[14].i= 601
container[14].j= 494
container[14].angle= 153
container[14].value= 255


container[15].bin= 5
container[15].i= 602
container[15].j= 487
container[15].angle= 26
container[15].value= 255


container[16].bin= 30
container[16].i= 602
container[16].j= 494
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 603
container[17].j= 486
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 603
container[18].j= 494
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 604
container[19].j= 487
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 604
container[20].j= 488
container[20].angle= 270
container[20].value= 255


container[21].bin= 41
container[21].i= 604
container[21].j= 494
container[21].angle= 206
container[21].value= 255


container[22].bin= 63
container[22].i= 605
container[22].j= 489
container[22].angle= 315
container[22].value= 255


container[23].bin= 50
container[23].i= 605
container[23].j= 492
container[23].angle= 251
container[23].value= 255


container[24].bin= 48
container[24].i= 605
container[24].j= 493
container[24].angle= 243
container[24].value= 255


container[25].bin= 44
container[25].i= 605
container[25].j= 494
container[25].angle= 224
container[25].value= 255


container[26].bin= 0
container[26].i= 606
container[26].j= 489
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 607
container[27].j= 489
container[27].angle= 0
container[27].value= 255


container[28].bin= 21
container[28].i= 607
container[28].j= 492
container[28].angle= 108
container[28].value= 255


container[29].bin= 27
container[29].i= 607
container[29].j= 493
container[29].angle= 135
container[29].value= 255


container[30].bin= 0
container[30].i= 608
container[30].j= 489
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 608
container[31].j= 493
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 609
container[32].j= 489
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 609
container[33].j= 493
container[33].angle= 180
container[33].value= 255


container[34].bin= 63
container[34].i= 610
container[34].j= 490
container[34].angle= 315
container[34].value= 255


container[35].bin= 54
container[35].i= 610
container[35].j= 491
container[35].angle= 270
container[35].value= 255


container[36].bin= 54
container[36].i= 610
container[36].j= 492
container[36].angle= 270
container[36].value= 255


container[37].bin= 44
container[37].i= 610
container[37].j= 493
container[37].angle= 224
container[37].value= 255


