container[0].bin= 3
container[0].i= 867
container[0].j= 239
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 867
container[1].j= 240
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 867
container[2].j= 241
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 868
container[3].j= 239
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 869
container[4].j= 242
container[4].angle= 153
container[4].value= 255


container[5].bin= 66
container[5].i= 870
container[5].j= 240
container[5].angle= 333
container[5].value= 255


container[6].bin= 30
container[6].i= 870
container[6].j= 242
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 871
container[7].j= 240
container[7].angle= 0
container[7].value= 255


container[8].bin= 0
container[8].i= 872
container[8].j= 240
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 872
container[9].j= 243
container[9].angle= 135
container[9].value= 255


container[10].bin= 18
container[10].i= 872
container[10].j= 244
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 872
container[11].j= 245
container[11].angle= 90
container[11].value= 255


container[12].bin= 0
container[12].i= 873
container[12].j= 240
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 873
container[13].j= 246
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 874
container[14].j= 240
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 874
container[15].j= 246
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 875
container[16].j= 240
container[16].angle= 0
container[16].value= 255


container[17].bin= 54
container[17].i= 875
container[17].j= 242
container[17].angle= 270
container[17].value= 255


container[18].bin= 30
container[18].i= 875
container[18].j= 247
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 876
container[19].j= 240
container[19].angle= 0
container[19].value= 255


container[20].bin= 68
container[20].i= 876
container[20].j= 243
container[20].angle= 341
container[20].value= 255


container[21].bin= 30
container[21].i= 876
container[21].j= 247
container[21].angle= 153
container[21].value= 255


container[22].bin= 68
container[22].i= 877
container[22].j= 240
container[22].angle= 341
container[22].value= 255


container[23].bin= 3
container[23].i= 877
container[23].j= 243
container[23].angle= 18
container[23].value= 255


container[24].bin= 36
container[24].i= 877
container[24].j= 247
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 878
container[25].j= 241
container[25].angle= 315
container[25].value= 255


container[26].bin= 27
container[26].i= 878
container[26].j= 248
container[26].angle= 135
container[26].value= 255


container[27].bin= 18
container[27].i= 878
container[27].j= 249
container[27].angle= 90
container[27].value= 255


container[28].bin= 66
container[28].i= 879
container[28].j= 242
container[28].angle= 333
container[28].value= 255


container[29].bin= 27
container[29].i= 879
container[29].j= 250
container[29].angle= 135
container[29].value= 255


container[30].bin= 0
container[30].i= 880
container[30].j= 242
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 880
container[31].j= 250
container[31].angle= 180
container[31].value= 255


container[32].bin= 66
container[32].i= 881
container[32].j= 243
container[32].angle= 333
container[32].value= 255


container[33].bin= 36
container[33].i= 881
container[33].j= 250
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 882
container[34].j= 243
container[34].angle= 333
container[34].value= 255


container[35].bin= 36
container[35].i= 882
container[35].j= 250
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 883
container[36].j= 243
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 883
container[37].j= 250
container[37].angle= 180
container[37].value= 255


container[38].bin= 63
container[38].i= 884
container[38].j= 244
container[38].angle= 315
container[38].value= 255


container[39].bin= 36
container[39].i= 884
container[39].j= 250
container[39].angle= 180
container[39].value= 255


container[40].bin= 63
container[40].i= 885
container[40].j= 245
container[40].angle= 315
container[40].value= 255


container[41].bin= 36
container[41].i= 885
container[41].j= 250
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 886
container[42].j= 245
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 886
container[43].j= 250
container[43].angle= 180
container[43].value= 255


container[44].bin= 0
container[44].i= 887
container[44].j= 245
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 887
container[45].j= 250
container[45].angle= 180
container[45].value= 255


container[46].bin= 66
container[46].i= 888
container[46].j= 246
container[46].angle= 333
container[46].value= 255


container[47].bin= 36
container[47].i= 888
container[47].j= 250
container[47].angle= 180
container[47].value= 255


container[48].bin= 0
container[48].i= 889
container[48].j= 246
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 889
container[49].j= 250
container[49].angle= 180
container[49].value= 255


container[50].bin= 68
container[50].i= 890
container[50].j= 246
container[50].angle= 341
container[50].value= 255


container[51].bin= 36
container[51].i= 890
container[51].j= 250
container[51].angle= 180
container[51].value= 255


container[52].bin= 63
container[52].i= 891
container[52].j= 247
container[52].angle= 315
container[52].value= 255


container[53].bin= 36
container[53].i= 891
container[53].j= 250
container[53].angle= 180
container[53].value= 255


container[54].bin= 0
container[54].i= 892
container[54].j= 247
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 892
container[55].j= 250
container[55].angle= 180
container[55].value= 255


container[56].bin= 66
container[56].i= 893
container[56].j= 248
container[56].angle= 333
container[56].value= 255


container[57].bin= 36
container[57].i= 893
container[57].j= 250
container[57].angle= 180
container[57].value= 255


container[58].bin= 66
container[58].i= 894
container[58].j= 248
container[58].angle= 333
container[58].value= 255


container[59].bin= 0
container[59].i= 895
container[59].j= 248
container[59].angle= 0
container[59].value= 255


container[60].bin= 63
container[60].i= 896
container[60].j= 249
container[60].angle= 315
container[60].value= 255


container[61].bin= 44
container[61].i= 896
container[61].j= 250
container[61].angle= 224
container[61].value= 255


