container[0].bin= 18
container[0].i= 95
container[0].j= 429
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 96
container[1].j= 427
container[1].angle= 44
container[1].value= 255


container[2].bin= 12
container[2].i= 96
container[2].j= 428
container[2].angle= 63
container[2].value= 255


container[3].bin= 27
container[3].i= 96
container[3].j= 430
container[3].angle= 135
container[3].value= 255


container[4].bin= 5
container[4].i= 97
container[4].j= 427
container[4].angle= 26
container[4].value= 255


container[5].bin= 30
container[5].i= 97
container[5].j= 431
container[5].angle= 153
container[5].value= 255


container[6].bin= 66
container[6].i= 98
container[6].j= 427
container[6].angle= 333
container[6].value= 255


container[7].bin= 30
container[7].i= 98
container[7].j= 431
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 99
container[8].j= 427
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 99
container[9].j= 432
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 100
container[10].j= 427
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 100
container[11].j= 432
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 101
container[12].j= 427
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 101
container[13].j= 432
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 102
container[14].j= 427
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 102
container[15].j= 432
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 103
container[16].j= 428
container[16].angle= 315
container[16].value= 255


container[17].bin= 41
container[17].i= 103
container[17].j= 432
container[17].angle= 206
container[17].value= 255


container[18].bin= 59
container[18].i= 104
container[18].j= 429
container[18].angle= 296
container[18].value= 255


container[19].bin= 59
container[19].i= 104
container[19].j= 430
container[19].angle= 296
container[19].value= 255


container[20].bin= 48
container[20].i= 104
container[20].j= 431
container[20].angle= 243
container[20].value= 255


container[21].bin= 44
container[21].i= 104
container[21].j= 432
container[21].angle= 224
container[21].value= 255


