container[0].bin= 8
container[0].i= 900
container[0].j= 368
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 900
container[1].j= 369
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 901
container[2].j= 367
container[2].angle= 0
container[2].value= 255


container[3].bin= 63
container[3].i= 902
container[3].j= 368
container[3].angle= 315
container[3].value= 255


container[4].bin= 27
container[4].i= 903
container[4].j= 371
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 904
container[5].j= 369
container[5].angle= 0
container[5].value= 255


container[6].bin= 66
container[6].i= 905
container[6].j= 370
container[6].angle= 333
container[6].value= 255


container[7].bin= 66
container[7].i= 906
container[7].j= 370
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 906
container[8].j= 372
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 907
container[9].j= 370
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 907
container[10].j= 372
container[10].angle= 180
container[10].value= 255


container[11].bin= 68
container[11].i= 908
container[11].j= 370
container[11].angle= 341
container[11].value= 255


container[12].bin= 54
container[12].i= 908
container[12].j= 371
container[12].angle= 270
container[12].value= 255


container[13].bin= 39
container[13].i= 908
container[13].j= 372
container[13].angle= 198
container[13].value= 255


