container[0].bin= 18
container[0].i= 423
container[0].j= 306
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 423
container[1].j= 307
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 424
container[2].j= 305
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 424
container[3].j= 308
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 425
container[4].j= 304
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 425
container[5].j= 308
container[5].angle= 180
container[5].value= 255


container[6].bin= 0
container[6].i= 426
container[6].j= 304
container[6].angle= 0
container[6].value= 255


container[7].bin= 27
container[7].i= 426
container[7].j= 309
container[7].angle= 135
container[7].value= 255


container[8].bin= 21
container[8].i= 426
container[8].j= 310
container[8].angle= 108
container[8].value= 255


container[9].bin= 0
container[9].i= 427
container[9].j= 304
container[9].angle= 0
container[9].value= 255


container[10].bin= 0
container[10].i= 428
container[10].j= 304
container[10].angle= 0
container[10].value= 255


container[11].bin= 63
container[11].i= 429
container[11].j= 305
container[11].angle= 315
container[11].value= 255


container[12].bin= 27
container[12].i= 429
container[12].j= 310
container[12].angle= 135
container[12].value= 255


container[13].bin= 63
container[13].i= 430
container[13].j= 306
container[13].angle= 315
container[13].value= 255


container[14].bin= 32
container[14].i= 430
container[14].j= 310
container[14].angle= 161
container[14].value= 255


container[15].bin= 0
container[15].i= 431
container[15].j= 306
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 431
container[16].j= 310
container[16].angle= 180
container[16].value= 255


container[17].bin= 8
container[17].i= 432
container[17].j= 306
container[17].angle= 44
container[17].value= 255


container[18].bin= 36
container[18].i= 432
container[18].j= 310
container[18].angle= 180
container[18].value= 255


container[19].bin= 8
container[19].i= 433
container[19].j= 305
container[19].angle= 44
container[19].value= 255


container[20].bin= 36
container[20].i= 433
container[20].j= 310
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 434
container[21].j= 304
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 434
container[22].j= 310
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 435
container[23].j= 305
container[23].angle= 315
container[23].value= 255


container[24].bin= 44
container[24].i= 435
container[24].j= 310
container[24].angle= 224
container[24].value= 255


container[25].bin= 18
container[25].i= 435
container[25].j= 314
container[25].angle= 90
container[25].value= 255


container[26].bin= 63
container[26].i= 436
container[26].j= 306
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 436
container[27].j= 309
container[27].angle= 224
container[27].value= 255


container[28].bin= 8
container[28].i= 436
container[28].j= 313
container[28].angle= 44
container[28].value= 255


container[29].bin= 27
container[29].i= 436
container[29].j= 315
container[29].angle= 135
container[29].value= 255


container[30].bin= 0
container[30].i= 437
container[30].j= 306
container[30].angle= 0
container[30].value= 255


container[31].bin= 0
container[31].i= 437
container[31].j= 312
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 437
container[32].j= 315
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 438
container[33].j= 306
container[33].angle= 0
container[33].value= 255


container[34].bin= 0
container[34].i= 438
container[34].j= 312
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 438
container[35].j= 315
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 439
container[36].j= 306
container[36].angle= 0
container[36].value= 255


container[37].bin= 0
container[37].i= 439
container[37].j= 312
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 439
container[38].j= 315
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 440
container[39].j= 306
container[39].angle= 0
container[39].value= 255


container[40].bin= 0
container[40].i= 440
container[40].j= 312
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 440
container[41].j= 315
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 441
container[42].j= 306
container[42].angle= 0
container[42].value= 255


container[43].bin= 27
container[43].i= 441
container[43].j= 309
container[43].angle= 135
container[43].value= 255


container[44].bin= 18
container[44].i= 441
container[44].j= 310
container[44].angle= 90
container[44].value= 255


container[45].bin= 18
container[45].i= 441
container[45].j= 311
container[45].angle= 90
container[45].value= 255


container[46].bin= 8
container[46].i= 441
container[46].j= 312
container[46].angle= 44
container[46].value= 255


container[47].bin= 44
container[47].i= 441
container[47].j= 315
container[47].angle= 224
container[47].value= 255


container[48].bin= 0
container[48].i= 442
container[48].j= 306
container[48].angle= 0
container[48].value= 255


container[49].bin= 44
container[49].i= 442
container[49].j= 314
container[49].angle= 224
container[49].value= 255


container[50].bin= 0
container[50].i= 443
container[50].j= 306
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 443
container[51].j= 313
container[51].angle= 180
container[51].value= 255


container[52].bin= 8
container[52].i= 444
container[52].j= 306
container[52].angle= 44
container[52].value= 255


container[53].bin= 44
container[53].i= 444
container[53].j= 313
container[53].angle= 224
container[53].value= 255


container[54].bin= 8
container[54].i= 445
container[54].j= 305
container[54].angle= 44
container[54].value= 255


container[55].bin= 44
container[55].i= 445
container[55].j= 312
container[55].angle= 224
container[55].value= 255


container[56].bin= 0
container[56].i= 446
container[56].j= 304
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 446
container[57].j= 311
container[57].angle= 180
container[57].value= 255


container[58].bin= 63
container[58].i= 447
container[58].j= 305
container[58].angle= 315
container[58].value= 255


container[59].bin= 54
container[59].i= 447
container[59].j= 306
container[59].angle= 270
container[59].value= 255


container[60].bin= 57
container[60].i= 447
container[60].j= 307
container[60].angle= 288
container[60].value= 255


container[61].bin= 36
container[61].i= 447
container[61].j= 311
container[61].angle= 180
container[61].value= 255


container[62].bin= 36
container[62].i= 448
container[62].j= 311
container[62].angle= 180
container[62].value= 255


container[63].bin= 3
container[63].i= 449
container[63].j= 306
container[63].angle= 18
container[63].value= 255


container[64].bin= 36
container[64].i= 449
container[64].j= 311
container[64].angle= 180
container[64].value= 255


container[65].bin= 68
container[65].i= 450
container[65].j= 306
container[65].angle= 341
container[65].value= 255


container[66].bin= 54
container[66].i= 450
container[66].j= 308
container[66].angle= 270
container[66].value= 255


container[67].bin= 63
container[67].i= 450
container[67].j= 309
container[67].angle= 315
container[67].value= 255


container[68].bin= 27
container[68].i= 450
container[68].j= 312
container[68].angle= 135
container[68].value= 255


container[69].bin= 0
container[69].i= 451
container[69].j= 309
container[69].angle= 0
container[69].value= 255


container[70].bin= 27
container[70].i= 451
container[70].j= 313
container[70].angle= 135
container[70].value= 255


container[71].bin= 0
container[71].i= 452
container[71].j= 309
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 452
container[72].j= 313
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 453
container[73].j= 309
container[73].angle= 315
container[73].value= 255


container[74].bin= 59
container[74].i= 453
container[74].j= 310
container[74].angle= 296
container[74].value= 255


container[75].bin= 54
container[75].i= 453
container[75].j= 311
container[75].angle= 270
container[75].value= 255


container[76].bin= 54
container[76].i= 453
container[76].j= 312
container[76].angle= 270
container[76].value= 255


container[77].bin= 44
container[77].i= 453
container[77].j= 313
container[77].angle= 224
container[77].value= 255


