container[0].bin= 18
container[0].i= 176
container[0].j= 185
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 177
container[1].j= 184
container[1].angle= 44
container[1].value= 255


container[2].bin= 23
container[2].i= 177
container[2].j= 186
container[2].angle= 116
container[2].value= 255


container[3].bin= 27
container[3].i= 177
container[3].j= 187
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 178
container[4].j= 183
container[4].angle= 0
container[4].value= 255


container[5].bin= 30
container[5].i= 178
container[5].j= 187
container[5].angle= 153
container[5].value= 255


container[6].bin= 0
container[6].i= 179
container[6].j= 183
container[6].angle= 0
container[6].value= 255


container[7].bin= 30
container[7].i= 179
container[7].j= 188
container[7].angle= 153
container[7].value= 255


container[8].bin= 0
container[8].i= 180
container[8].j= 183
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 180
container[9].j= 188
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 180
container[10].j= 189
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 181
container[11].j= 183
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 181
container[12].j= 189
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 182
container[13].j= 183
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 182
container[14].j= 190
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 183
container[15].j= 183
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 183
container[16].j= 190
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 184
container[17].j= 184
container[17].angle= 333
container[17].value= 255


container[18].bin= 30
container[18].i= 184
container[18].j= 191
container[18].angle= 153
container[18].value= 255


container[19].bin= 66
container[19].i= 185
container[19].j= 184
container[19].angle= 333
container[19].value= 255


container[20].bin= 30
container[20].i= 185
container[20].j= 191
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 186
container[21].j= 184
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 186
container[22].j= 192
container[22].angle= 153
container[22].value= 255


container[23].bin= 66
container[23].i= 187
container[23].j= 185
container[23].angle= 333
container[23].value= 255


container[24].bin= 30
container[24].i= 187
container[24].j= 192
container[24].angle= 153
container[24].value= 255


container[25].bin= 66
container[25].i= 188
container[25].j= 185
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 188
container[26].j= 193
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 189
container[27].j= 186
container[27].angle= 333
container[27].value= 255


container[28].bin= 27
container[28].i= 189
container[28].j= 193
container[28].angle= 135
container[28].value= 255


container[29].bin= 27
container[29].i= 189
container[29].j= 194
container[29].angle= 135
container[29].value= 255


container[30].bin= 66
container[30].i= 190
container[30].j= 186
container[30].angle= 333
container[30].value= 255


container[31].bin= 30
container[31].i= 190
container[31].j= 194
container[31].angle= 153
container[31].value= 255


container[32].bin= 66
container[32].i= 191
container[32].j= 187
container[32].angle= 333
container[32].value= 255


container[33].bin= 36
container[33].i= 191
container[33].j= 194
container[33].angle= 180
container[33].value= 255


container[34].bin= 66
container[34].i= 192
container[34].j= 187
container[34].angle= 333
container[34].value= 255


container[35].bin= 30
container[35].i= 192
container[35].j= 195
container[35].angle= 153
container[35].value= 255


container[36].bin= 0
container[36].i= 193
container[36].j= 187
container[36].angle= 0
container[36].value= 255


container[37].bin= 30
container[37].i= 193
container[37].j= 195
container[37].angle= 153
container[37].value= 255


container[38].bin= 63
container[38].i= 194
container[38].j= 188
container[38].angle= 315
container[38].value= 255


container[39].bin= 54
container[39].i= 194
container[39].j= 189
container[39].angle= 270
container[39].value= 255


container[40].bin= 54
container[40].i= 194
container[40].j= 190
container[40].angle= 270
container[40].value= 255


container[41].bin= 54
container[41].i= 194
container[41].j= 191
container[41].angle= 270
container[41].value= 255


container[42].bin= 54
container[42].i= 194
container[42].j= 192
container[42].angle= 270
container[42].value= 255


container[43].bin= 54
container[43].i= 194
container[43].j= 193
container[43].angle= 270
container[43].value= 255


container[44].bin= 54
container[44].i= 194
container[44].j= 194
container[44].angle= 270
container[44].value= 255


container[45].bin= 44
container[45].i= 194
container[45].j= 195
container[45].angle= 224
container[45].value= 255


