container[0].bin= 8
container[0].i= 14
container[0].j= 64
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 14
container[1].j= 65
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 15
container[2].j= 63
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 16
container[3].j= 63
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 16
container[4].j= 66
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 17
container[5].j= 63
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 17
container[6].j= 66
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 18
container[7].j= 63
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 18
container[8].j= 66
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 19
container[9].j= 63
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 19
container[10].j= 66
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 20
container[11].j= 63
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 20
container[12].j= 66
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 21
container[13].j= 63
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 21
container[14].j= 66
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 22
container[15].j= 64
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 22
container[16].j= 66
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 23
container[17].j= 64
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 23
container[18].j= 65
container[18].angle= 296
container[18].value= 255


container[19].bin= 44
container[19].i= 23
container[19].j= 66
container[19].angle= 224
container[19].value= 255


