container[0].bin= 18
container[0].i= 351
container[0].j= 618
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 351
container[1].j= 619
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 351
container[2].j= 620
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 352
container[3].j= 617
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 352
container[4].j= 621
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 353
container[5].j= 616
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 353
container[6].j= 621
container[6].angle= 180
container[6].value= 255


container[7].bin= 14
container[7].i= 354
container[7].j= 612
container[7].angle= 71
container[7].value= 255


container[8].bin= 18
container[8].i= 354
container[8].j= 613
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 354
container[9].j= 614
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 354
container[10].j= 615
container[10].angle= 90
container[10].value= 255


container[11].bin= 8
container[11].i= 354
container[11].j= 616
container[11].angle= 44
container[11].value= 255


container[12].bin= 27
container[12].i= 354
container[12].j= 622
container[12].angle= 135
container[12].value= 255


container[13].bin= 0
container[13].i= 355
container[13].j= 611
container[13].angle= 0
container[13].value= 255


container[14].bin= 27
container[14].i= 355
container[14].j= 623
container[14].angle= 135
container[14].value= 255


container[15].bin= 57
container[15].i= 356
container[15].j= 612
container[15].angle= 288
container[15].value= 255


container[16].bin= 63
container[16].i= 356
container[16].j= 613
container[16].angle= 315
container[16].value= 255


container[17].bin= 36
container[17].i= 356
container[17].j= 623
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 357
container[18].j= 613
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 357
container[19].j= 624
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 358
container[20].j= 613
container[20].angle= 0
container[20].value= 255


container[21].bin= 30
container[21].i= 358
container[21].j= 624
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 359
container[22].j= 613
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 359
container[23].j= 624
container[23].angle= 180
container[23].value= 255


container[24].bin= 66
container[24].i= 360
container[24].j= 614
container[24].angle= 333
container[24].value= 255


container[25].bin= 36
container[25].i= 360
container[25].j= 624
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 361
container[26].j= 614
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 361
container[27].j= 615
container[27].angle= 315
container[27].value= 255


container[28].bin= 36
container[28].i= 361
container[28].j= 624
container[28].angle= 180
container[28].value= 255


container[29].bin= 66
container[29].i= 362
container[29].j= 615
container[29].angle= 333
container[29].value= 255


container[30].bin= 36
container[30].i= 362
container[30].j= 624
container[30].angle= 180
container[30].value= 255


container[31].bin= 66
container[31].i= 363
container[31].j= 616
container[31].angle= 333
container[31].value= 255


container[32].bin= 36
container[32].i= 363
container[32].j= 624
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 364
container[33].j= 616
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 364
container[34].j= 624
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 365
container[35].j= 616
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 365
container[36].j= 624
container[36].angle= 180
container[36].value= 255


container[37].bin= 66
container[37].i= 366
container[37].j= 617
container[37].angle= 333
container[37].value= 255


container[38].bin= 36
container[38].i= 366
container[38].j= 624
container[38].angle= 180
container[38].value= 255


container[39].bin= 66
container[39].i= 367
container[39].j= 617
container[39].angle= 333
container[39].value= 255


container[40].bin= 36
container[40].i= 367
container[40].j= 624
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 368
container[41].j= 617
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 368
container[42].j= 624
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 369
container[43].j= 618
container[43].angle= 315
container[43].value= 255


container[44].bin= 54
container[44].i= 369
container[44].j= 619
container[44].angle= 270
container[44].value= 255


container[45].bin= 54
container[45].i= 369
container[45].j= 620
container[45].angle= 270
container[45].value= 255


container[46].bin= 36
container[46].i= 369
container[46].j= 624
container[46].angle= 180
container[46].value= 255


container[47].bin= 63
container[47].i= 370
container[47].j= 621
container[47].angle= 315
container[47].value= 255


container[48].bin= 36
container[48].i= 370
container[48].j= 624
container[48].angle= 180
container[48].value= 255


container[49].bin= 0
container[49].i= 371
container[49].j= 621
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 371
container[50].j= 624
container[50].angle= 180
container[50].value= 255


container[51].bin= 66
container[51].i= 372
container[51].j= 622
container[51].angle= 333
container[51].value= 255


container[52].bin= 36
container[52].i= 372
container[52].j= 624
container[52].angle= 180
container[52].value= 255


container[53].bin= 66
container[53].i= 373
container[53].j= 622
container[53].angle= 333
container[53].value= 255


container[54].bin= 0
container[54].i= 374
container[54].j= 622
container[54].angle= 0
container[54].value= 255


container[55].bin= 63
container[55].i= 375
container[55].j= 623
container[55].angle= 315
container[55].value= 255


container[56].bin= 44
container[56].i= 375
container[56].j= 624
container[56].angle= 224
container[56].value= 255


