container[0].bin= 18
container[0].i= 225
container[0].j= 297
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 226
container[1].j= 296
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 226
container[2].j= 298
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 227
container[3].j= 296
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 227
container[4].j= 298
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 228
container[5].j= 296
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 228
container[6].j= 298
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 228
container[7].j= 299
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 228
container[8].j= 300
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 228
container[9].j= 301
container[9].angle= 90
container[9].value= 255


container[10].bin= 0
container[10].i= 229
container[10].j= 296
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 229
container[11].j= 302
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 230
container[12].j= 296
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 230
container[13].j= 302
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 231
container[14].j= 297
container[14].angle= 315
container[14].value= 255


container[15].bin= 30
container[15].i= 231
container[15].j= 303
container[15].angle= 153
container[15].value= 255


container[16].bin= 63
container[16].i= 232
container[16].j= 298
container[16].angle= 315
container[16].value= 255


container[17].bin= 30
container[17].i= 232
container[17].j= 303
container[17].angle= 153
container[17].value= 255


container[18].bin= 0
container[18].i= 233
container[18].j= 298
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 233
container[19].j= 303
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 234
container[20].j= 299
container[20].angle= 315
container[20].value= 255


container[21].bin= 36
container[21].i= 234
container[21].j= 303
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 235
container[22].j= 300
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 235
container[23].j= 303
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 236
container[24].j= 300
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 236
container[25].j= 303
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 237
container[26].j= 300
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 237
container[27].j= 303
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 238
container[28].j= 300
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 238
container[29].j= 303
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 239
container[30].j= 300
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 239
container[31].j= 303
container[31].angle= 180
container[31].value= 255


container[32].bin= 66
container[32].i= 240
container[32].j= 301
container[32].angle= 333
container[32].value= 255


container[33].bin= 54
container[33].i= 240
container[33].j= 302
container[33].angle= 270
container[33].value= 255


container[34].bin= 41
container[34].i= 240
container[34].j= 303
container[34].angle= 206
container[34].value= 255


container[35].bin= 66
container[35].i= 241
container[35].j= 301
container[35].angle= 333
container[35].value= 255


container[36].bin= 41
container[36].i= 241
container[36].j= 303
container[36].angle= 206
container[36].value= 255


container[37].bin= 0
container[37].i= 242
container[37].j= 301
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 242
container[38].j= 303
container[38].angle= 180
container[38].value= 255


container[39].bin= 0
container[39].i= 243
container[39].j= 301
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 243
container[40].j= 303
container[40].angle= 180
container[40].value= 255


container[41].bin= 0
container[41].i= 244
container[41].j= 301
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 244
container[42].j= 303
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 245
container[43].j= 301
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 245
container[44].j= 303
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 246
container[45].j= 301
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 246
container[46].j= 303
container[46].angle= 180
container[46].value= 255


container[47].bin= 0
container[47].i= 247
container[47].j= 301
container[47].angle= 0
container[47].value= 255


container[48].bin= 36
container[48].i= 247
container[48].j= 303
container[48].angle= 180
container[48].value= 255


container[49].bin= 0
container[49].i= 248
container[49].j= 301
container[49].angle= 0
container[49].value= 255


container[50].bin= 36
container[50].i= 248
container[50].j= 303
container[50].angle= 180
container[50].value= 255


container[51].bin= 0
container[51].i= 249
container[51].j= 301
container[51].angle= 0
container[51].value= 255


container[52].bin= 36
container[52].i= 249
container[52].j= 303
container[52].angle= 180
container[52].value= 255


container[53].bin= 0
container[53].i= 250
container[53].j= 301
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 250
container[54].j= 303
container[54].angle= 180
container[54].value= 255


container[55].bin= 0
container[55].i= 251
container[55].j= 301
container[55].angle= 0
container[55].value= 255


container[56].bin= 36
container[56].i= 251
container[56].j= 303
container[56].angle= 180
container[56].value= 255


container[57].bin= 0
container[57].i= 252
container[57].j= 301
container[57].angle= 0
container[57].value= 255


container[58].bin= 30
container[58].i= 252
container[58].j= 303
container[58].angle= 153
container[58].value= 255


container[59].bin= 0
container[59].i= 253
container[59].j= 301
container[59].angle= 0
container[59].value= 255


container[60].bin= 30
container[60].i= 253
container[60].j= 303
container[60].angle= 153
container[60].value= 255


container[61].bin= 0
container[61].i= 254
container[61].j= 301
container[61].angle= 0
container[61].value= 255


container[62].bin= 5
container[62].i= 255
container[62].j= 301
container[62].angle= 26
container[62].value= 255


container[63].bin= 5
container[63].i= 256
container[63].j= 301
container[63].angle= 26
container[63].value= 255


container[64].bin= 36
container[64].i= 256
container[64].j= 303
container[64].angle= 180
container[64].value= 255


container[65].bin= 0
container[65].i= 257
container[65].j= 300
container[65].angle= 0
container[65].value= 255


container[66].bin= 36
container[66].i= 257
container[66].j= 303
container[66].angle= 180
container[66].value= 255


container[67].bin= 0
container[67].i= 258
container[67].j= 300
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 258
container[68].j= 303
container[68].angle= 180
container[68].value= 255


container[69].bin= 0
container[69].i= 259
container[69].j= 300
container[69].angle= 0
container[69].value= 255


container[70].bin= 36
container[70].i= 259
container[70].j= 303
container[70].angle= 180
container[70].value= 255


container[71].bin= 0
container[71].i= 260
container[71].j= 300
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 260
container[72].j= 303
container[72].angle= 180
container[72].value= 255


container[73].bin= 0
container[73].i= 261
container[73].j= 300
container[73].angle= 0
container[73].value= 255


container[74].bin= 27
container[74].i= 261
container[74].j= 304
container[74].angle= 135
container[74].value= 255


container[75].bin= 66
container[75].i= 262
container[75].j= 301
container[75].angle= 333
container[75].value= 255


container[76].bin= 27
container[76].i= 262
container[76].j= 305
container[76].angle= 135
container[76].value= 255


container[77].bin= 66
container[77].i= 263
container[77].j= 301
container[77].angle= 333
container[77].value= 255


container[78].bin= 36
container[78].i= 263
container[78].j= 305
container[78].angle= 180
container[78].value= 255


container[79].bin= 0
container[79].i= 264
container[79].j= 301
container[79].angle= 0
container[79].value= 255


container[80].bin= 27
container[80].i= 264
container[80].j= 306
container[80].angle= 135
container[80].value= 255


container[81].bin= 0
container[81].i= 265
container[81].j= 301
container[81].angle= 0
container[81].value= 255


container[82].bin= 27
container[82].i= 265
container[82].j= 307
container[82].angle= 135
container[82].value= 255


container[83].bin= 0
container[83].i= 266
container[83].j= 301
container[83].angle= 0
container[83].value= 255


container[84].bin= 36
container[84].i= 266
container[84].j= 307
container[84].angle= 180
container[84].value= 255


container[85].bin= 0
container[85].i= 267
container[85].j= 301
container[85].angle= 0
container[85].value= 255


container[86].bin= 41
container[86].i= 267
container[86].j= 307
container[86].angle= 206
container[86].value= 255


container[87].bin= 68
container[87].i= 268
container[87].j= 301
container[87].angle= 341
container[87].value= 255


container[88].bin= 57
container[88].i= 268
container[88].j= 303
container[88].angle= 288
container[88].value= 255


container[89].bin= 44
container[89].i= 268
container[89].j= 306
container[89].angle= 224
container[89].value= 255


container[90].bin= 44
container[90].i= 268
container[90].j= 307
container[90].angle= 224
container[90].value= 255


container[91].bin= 68
container[91].i= 269
container[91].j= 303
container[91].angle= 341
container[91].value= 255


container[92].bin= 36
container[92].i= 269
container[92].j= 306
container[92].angle= 180
container[92].value= 255


container[93].bin= 63
container[93].i= 270
container[93].j= 304
container[93].angle= 315
container[93].value= 255


container[94].bin= 50
container[94].i= 270
container[94].j= 305
container[94].angle= 251
container[94].value= 255


