container[0].bin= 14
container[0].i= 583
container[0].j= 586
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 583
container[1].j= 587
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 584
container[2].j= 585
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 585
container[3].j= 585
container[3].angle= 0
container[3].value= 255


container[4].bin= 41
container[4].i= 585
container[4].j= 587
container[4].angle= 206
container[4].value= 255


container[5].bin= 18
container[5].i= 586
container[5].j= 583
container[5].angle= 90
container[5].value= 255


container[6].bin= 0
container[6].i= 586
container[6].j= 585
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 586
container[7].j= 587
container[7].angle= 180
container[7].value= 255


container[8].bin= 3
container[8].i= 587
container[8].j= 582
container[8].angle= 18
container[8].value= 255


container[9].bin= 32
container[9].i= 587
container[9].j= 584
container[9].angle= 161
container[9].value= 255


container[10].bin= 36
container[10].i= 587
container[10].j= 587
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 588
container[11].j= 582
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 588
container[12].j= 584
container[12].angle= 180
container[12].value= 255


container[13].bin= 32
container[13].i= 588
container[13].j= 587
container[13].angle= 161
container[13].value= 255


container[14].bin= 18
container[14].i= 588
container[14].j= 588
container[14].angle= 90
container[14].value= 255


container[15].bin= 0
container[15].i= 589
container[15].j= 582
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 589
container[16].j= 584
container[16].angle= 153
container[16].value= 255


container[17].bin= 0
container[17].i= 590
container[17].j= 582
container[17].angle= 0
container[17].value= 255


container[18].bin= 27
container[18].i= 590
container[18].j= 584
container[18].angle= 135
container[18].value= 255


container[19].bin= 21
container[19].i= 590
container[19].j= 585
container[19].angle= 108
container[19].value= 255


container[20].bin= 44
container[20].i= 590
container[20].j= 588
container[20].angle= 224
container[20].value= 255


container[21].bin= 0
container[21].i= 591
container[21].j= 582
container[21].angle= 0
container[21].value= 255


container[22].bin= 44
container[22].i= 591
container[22].j= 587
container[22].angle= 224
container[22].value= 255


container[23].bin= 63
container[23].i= 592
container[23].j= 583
container[23].angle= 315
container[23].value= 255


container[24].bin= 48
container[24].i= 592
container[24].j= 584
container[24].angle= 243
container[24].value= 255


container[25].bin= 48
container[25].i= 592
container[25].j= 585
container[25].angle= 243
container[25].value= 255


container[26].bin= 50
container[26].i= 592
container[26].j= 586
container[26].angle= 251
container[26].value= 255


