container[0].bin= 18
container[0].i= 288
container[0].j= 453
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 289
container[1].j= 452
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 289
container[2].j= 454
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 290
container[3].j= 452
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 290
container[4].j= 454
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 291
container[5].j= 452
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 291
container[6].j= 454
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 292
container[7].j= 452
container[7].angle= 26
container[7].value= 255


container[8].bin= 0
container[8].i= 293
container[8].j= 451
container[8].angle= 0
container[8].value= 255


container[9].bin= 0
container[9].i= 294
container[9].j= 451
container[9].angle= 0
container[9].value= 255


container[10].bin= 0
container[10].i= 295
container[10].j= 451
container[10].angle= 0
container[10].value= 255


container[11].bin= 0
container[11].i= 296
container[11].j= 451
container[11].angle= 0
container[11].value= 255


container[12].bin= 0
container[12].i= 297
container[12].j= 451
container[12].angle= 0
container[12].value= 255


container[13].bin= 30
container[13].i= 297
container[13].j= 454
container[13].angle= 153
container[13].value= 255


container[14].bin= 0
container[14].i= 298
container[14].j= 451
container[14].angle= 0
container[14].value= 255


container[15].bin= 30
container[15].i= 298
container[15].j= 454
container[15].angle= 153
container[15].value= 255


container[16].bin= 0
container[16].i= 299
container[16].j= 451
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 299
container[17].j= 454
container[17].angle= 180
container[17].value= 255


container[18].bin= 8
container[18].i= 300
container[18].j= 451
container[18].angle= 44
container[18].value= 255


container[19].bin= 36
container[19].i= 300
container[19].j= 454
container[19].angle= 180
container[19].value= 255


container[20].bin= 8
container[20].i= 301
container[20].j= 450
container[20].angle= 44
container[20].value= 255


container[21].bin= 30
container[21].i= 301
container[21].j= 455
container[21].angle= 153
container[21].value= 255


container[22].bin= 0
container[22].i= 302
container[22].j= 449
container[22].angle= 0
container[22].value= 255


container[23].bin= 30
container[23].i= 302
container[23].j= 455
container[23].angle= 153
container[23].value= 255


container[24].bin= 18
container[24].i= 303
container[24].j= 444
container[24].angle= 90
container[24].value= 255


container[25].bin= 18
container[25].i= 303
container[25].j= 445
container[25].angle= 90
container[25].value= 255


container[26].bin= 18
container[26].i= 303
container[26].j= 446
container[26].angle= 90
container[26].value= 255


container[27].bin= 18
container[27].i= 303
container[27].j= 447
container[27].angle= 90
container[27].value= 255


container[28].bin= 18
container[28].i= 303
container[28].j= 448
container[28].angle= 90
container[28].value= 255


container[29].bin= 8
container[29].i= 303
container[29].j= 449
container[29].angle= 44
container[29].value= 255


container[30].bin= 30
container[30].i= 303
container[30].j= 456
container[30].angle= 153
container[30].value= 255


container[31].bin= 8
container[31].i= 304
container[31].j= 443
container[31].angle= 44
container[31].value= 255


container[32].bin= 30
container[32].i= 304
container[32].j= 456
container[32].angle= 153
container[32].value= 255


container[33].bin= 0
container[33].i= 305
container[33].j= 442
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 305
container[34].j= 456
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 306
container[35].j= 443
container[35].angle= 315
container[35].value= 255


container[36].bin= 27
container[36].i= 306
container[36].j= 457
container[36].angle= 135
container[36].value= 255


container[37].bin= 63
container[37].i= 307
container[37].j= 444
container[37].angle= 315
container[37].value= 255


container[38].bin= 44
container[38].i= 307
container[38].j= 447
container[38].angle= 224
container[38].value= 255


container[39].bin= 57
container[39].i= 307
container[39].j= 448
container[39].angle= 288
container[39].value= 255


container[40].bin= 27
container[40].i= 307
container[40].j= 458
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 308
container[41].j= 444
container[41].angle= 0
container[41].value= 255


container[42].bin= 68
container[42].i= 308
container[42].j= 449
container[42].angle= 341
container[42].value= 255


container[43].bin= 36
container[43].i= 308
container[43].j= 458
container[43].angle= 180
container[43].value= 255


container[44].bin= 63
container[44].i= 309
container[44].j= 445
container[44].angle= 315
container[44].value= 255


container[45].bin= 44
container[45].i= 309
container[45].j= 446
container[45].angle= 224
container[45].value= 255


container[46].bin= 63
container[46].i= 309
container[46].j= 449
container[46].angle= 315
container[46].value= 255


container[47].bin= 36
container[47].i= 309
container[47].j= 458
container[47].angle= 180
container[47].value= 255


container[48].bin= 68
container[48].i= 310
container[48].j= 449
container[48].angle= 341
container[48].value= 255


container[49].bin= 36
container[49].i= 310
container[49].j= 458
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 311
container[50].j= 449
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 311
container[51].j= 458
container[51].angle= 180
container[51].value= 255


container[52].bin= 0
container[52].i= 312
container[52].j= 449
container[52].angle= 0
container[52].value= 255


container[53].bin= 30
container[53].i= 312
container[53].j= 459
container[53].angle= 153
container[53].value= 255


container[54].bin= 0
container[54].i= 313
container[54].j= 449
container[54].angle= 0
container[54].value= 255


container[55].bin= 30
container[55].i= 313
container[55].j= 459
container[55].angle= 153
container[55].value= 255


container[56].bin= 0
container[56].i= 314
container[56].j= 449
container[56].angle= 0
container[56].value= 255


container[57].bin= 41
container[57].i= 314
container[57].j= 459
container[57].angle= 206
container[57].value= 255


container[58].bin= 0
container[58].i= 315
container[58].j= 449
container[58].angle= 0
container[58].value= 255


container[59].bin= 54
container[59].i= 315
container[59].j= 452
container[59].angle= 270
container[59].value= 255


container[60].bin= 54
container[60].i= 315
container[60].j= 453
container[60].angle= 270
container[60].value= 255


container[61].bin= 54
container[61].i= 315
container[61].j= 454
container[61].angle= 270
container[61].value= 255


container[62].bin= 54
container[62].i= 315
container[62].j= 455
container[62].angle= 270
container[62].value= 255


container[63].bin= 54
container[63].i= 315
container[63].j= 456
container[63].angle= 270
container[63].value= 255


container[64].bin= 41
container[64].i= 315
container[64].j= 459
container[64].angle= 206
container[64].value= 255


container[65].bin= 0
container[65].i= 316
container[65].j= 449
container[65].angle= 0
container[65].value= 255


container[66].bin= 44
container[66].i= 316
container[66].j= 451
container[66].angle= 224
container[66].value= 255


container[67].bin= 63
container[67].i= 316
container[67].j= 457
container[67].angle= 315
container[67].value= 255


container[68].bin= 36
container[68].i= 316
container[68].j= 459
container[68].angle= 180
container[68].value= 255


container[69].bin= 68
container[69].i= 317
container[69].j= 449
container[69].angle= 341
container[69].value= 255


container[70].bin= 39
container[70].i= 317
container[70].j= 451
container[70].angle= 198
container[70].value= 255


container[71].bin= 0
container[71].i= 317
container[71].j= 457
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 317
container[72].j= 459
container[72].angle= 180
container[72].value= 255


container[73].bin= 68
container[73].i= 318
container[73].j= 457
container[73].angle= 341
container[73].value= 255


container[74].bin= 54
container[74].i= 318
container[74].j= 458
container[74].angle= 270
container[74].value= 255


container[75].bin= 39
container[75].i= 318
container[75].j= 459
container[75].angle= 198
container[75].value= 255


