container[0].bin= 18
container[0].i= 552
container[0].j= 510
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 553
container[1].j= 509
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 553
container[2].j= 511
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 554
container[3].j= 508
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 554
container[4].j= 511
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 555
container[5].j= 508
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 555
container[6].j= 511
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 556
container[7].j= 508
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 556
container[8].j= 511
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 557
container[9].j= 508
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 557
container[10].j= 511
container[10].angle= 180
container[10].value= 255


container[11].bin= 5
container[11].i= 558
container[11].j= 508
container[11].angle= 26
container[11].value= 255


container[12].bin= 36
container[12].i= 558
container[12].j= 511
container[12].angle= 180
container[12].value= 255


container[13].bin= 5
container[13].i= 559
container[13].j= 508
container[13].angle= 26
container[13].value= 255


container[14].bin= 36
container[14].i= 559
container[14].j= 511
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 560
container[15].j= 508
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 560
container[16].j= 511
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 561
container[17].j= 508
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 561
container[18].j= 509
container[18].angle= 296
container[18].value= 255


container[19].bin= 54
container[19].i= 561
container[19].j= 510
container[19].angle= 270
container[19].value= 255


container[20].bin= 44
container[20].i= 561
container[20].j= 511
container[20].angle= 224
container[20].value= 255


