container[0].bin= 3
container[0].i= 773
container[0].j= 510
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 773
container[1].j= 511
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 773
container[2].j= 512
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 774
container[3].j= 510
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 774
container[4].j= 512
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 775
container[5].j= 510
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 776
container[6].j= 511
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 776
container[7].j= 512
container[7].angle= 224
container[7].value= 255


