container[0].bin= 8
container[0].i= 319
container[0].j= 321
container[0].angle= 44
container[0].value= 255


container[1].bin= 21
container[1].i= 319
container[1].j= 322
container[1].angle= 108
container[1].value= 255


container[2].bin= 27
container[2].i= 319
container[2].j= 323
container[2].angle= 135
container[2].value= 255


container[3].bin= 18
container[3].i= 319
container[3].j= 324
container[3].angle= 90
container[3].value= 255


container[4].bin= 68
container[4].i= 320
container[4].j= 321
container[4].angle= 341
container[4].value= 255


container[5].bin= 57
container[5].i= 321
container[5].j= 322
container[5].angle= 288
container[5].value= 255


container[6].bin= 44
container[6].i= 321
container[6].j= 324
container[6].angle= 224
container[6].value= 255


