container[0].bin= 18
container[0].i= 626
container[0].j= 138
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 627
container[1].j= 137
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 627
container[2].j= 139
container[2].angle= 161
container[2].value= 255


container[3].bin= 18
container[3].i= 628
container[3].j= 136
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 628
container[4].j= 137
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 628
container[5].j= 139
container[5].angle= 180
container[5].value= 255


container[6].bin= 8
container[6].i= 629
container[6].j= 135
container[6].angle= 44
container[6].value= 255


container[7].bin= 0
container[7].i= 630
container[7].j= 134
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 630
container[8].j= 138
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 631
container[9].j= 135
container[9].angle= 315
container[9].value= 255


container[10].bin= 54
container[10].i= 631
container[10].j= 136
container[10].angle= 270
container[10].value= 255


container[11].bin= 54
container[11].i= 631
container[11].j= 137
container[11].angle= 270
container[11].value= 255


container[12].bin= 44
container[12].i= 631
container[12].j= 138
container[12].angle= 224
container[12].value= 255


