container[0].bin= 8
container[0].i= 122
container[0].j= 152
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 122
container[1].j= 153
container[1].angle= 116
container[1].value= 255


container[2].bin= 23
container[2].i= 122
container[2].j= 154
container[2].angle= 116
container[2].value= 255


container[3].bin= 0
container[3].i= 123
container[3].j= 151
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 123
container[4].j= 155
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 124
container[5].j= 151
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 124
container[6].j= 156
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 125
container[7].j= 151
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 125
container[8].j= 156
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 126
container[9].j= 151
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 126
container[10].j= 156
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 127
container[11].j= 152
container[11].angle= 333
container[11].value= 255


container[12].bin= 36
container[12].i= 127
container[12].j= 156
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 128
container[13].j= 152
container[13].angle= 315
container[13].value= 255


container[14].bin= 59
container[14].i= 128
container[14].j= 153
container[14].angle= 296
container[14].value= 255


container[15].bin= 54
container[15].i= 128
container[15].j= 154
container[15].angle= 270
container[15].value= 255


container[16].bin= 54
container[16].i= 128
container[16].j= 155
container[16].angle= 270
container[16].value= 255


container[17].bin= 44
container[17].i= 128
container[17].j= 156
container[17].angle= 224
container[17].value= 255


