container[0].bin= 18
container[0].i= 812
container[0].j= 233
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 813
container[1].j= 232
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 813
container[2].j= 234
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 814
container[3].j= 232
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 814
container[4].j= 234
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 815
container[5].j= 232
container[5].angle= 341
container[5].value= 255


