container[0].bin= 18
container[0].i= 285
container[0].j= 422
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 285
container[1].j= 423
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 285
container[2].j= 424
container[2].angle= 90
container[2].value= 255


container[3].bin= 8
container[3].i= 286
container[3].j= 416
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 286
container[4].j= 421
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 286
container[5].j= 425
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 287
container[6].j= 420
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 287
container[7].j= 425
container[7].angle= 180
container[7].value= 255


container[8].bin= 63
container[8].i= 288
container[8].j= 416
container[8].angle= 315
container[8].value= 255


container[9].bin= 18
container[9].i= 288
container[9].j= 419
container[9].angle= 90
container[9].value= 255


container[10].bin= 8
container[10].i= 288
container[10].j= 420
container[10].angle= 44
container[10].value= 255


container[11].bin= 27
container[11].i= 288
container[11].j= 426
container[11].angle= 135
container[11].value= 255


container[12].bin= 18
container[12].i= 288
container[12].j= 427
container[12].angle= 90
container[12].value= 255


container[13].bin= 18
container[13].i= 288
container[13].j= 428
container[13].angle= 90
container[13].value= 255


container[14].bin= 68
container[14].i= 289
container[14].j= 417
container[14].angle= 341
container[14].value= 255


container[15].bin= 8
container[15].i= 289
container[15].j= 418
container[15].angle= 44
container[15].value= 255


container[16].bin= 27
container[16].i= 289
container[16].j= 429
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 290
container[17].j= 417
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 290
container[18].j= 429
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 291
container[19].j= 418
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 291
container[20].j= 419
container[20].angle= 270
container[20].value= 255


container[21].bin= 36
container[21].i= 291
container[21].j= 429
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 292
container[22].j= 420
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 292
container[23].j= 429
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 293
container[24].j= 420
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 293
container[25].j= 429
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 294
container[26].j= 421
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 294
container[27].j= 429
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 295
container[28].j= 422
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 295
container[29].j= 429
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 296
container[30].j= 422
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 296
container[31].j= 429
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 297
container[32].j= 423
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 297
container[33].j= 424
container[33].angle= 270
container[33].value= 255


container[34].bin= 54
container[34].i= 297
container[34].j= 425
container[34].angle= 270
container[34].value= 255


container[35].bin= 36
container[35].i= 297
container[35].j= 429
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 298
container[36].j= 426
container[36].angle= 315
container[36].value= 255


container[37].bin= 36
container[37].i= 298
container[37].j= 429
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 299
container[38].j= 426
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 299
container[39].j= 429
container[39].angle= 180
container[39].value= 255


container[40].bin= 63
container[40].i= 300
container[40].j= 427
container[40].angle= 315
container[40].value= 255


container[41].bin= 54
container[41].i= 300
container[41].j= 428
container[41].angle= 270
container[41].value= 255


container[42].bin= 44
container[42].i= 300
container[42].j= 429
container[42].angle= 224
container[42].value= 255


