container[0].bin= 8
container[0].i= 568
container[0].j= 140
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 568
container[1].j= 141
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 569
container[2].j= 139
container[2].angle= 0
container[2].value= 255


container[3].bin= 18
container[3].i= 570
container[3].j= 136
container[3].angle= 90
container[3].value= 255


container[4].bin= 18
container[4].i= 570
container[4].j= 137
container[4].angle= 90
container[4].value= 255


container[5].bin= 18
container[5].i= 570
container[5].j= 138
container[5].angle= 90
container[5].value= 255


container[6].bin= 8
container[6].i= 570
container[6].j= 139
container[6].angle= 44
container[6].value= 255


container[7].bin= 41
container[7].i= 570
container[7].j= 141
container[7].angle= 206
container[7].value= 255


container[8].bin= 8
container[8].i= 571
container[8].j= 135
container[8].angle= 44
container[8].value= 255


container[9].bin= 41
container[9].i= 571
container[9].j= 141
container[9].angle= 206
container[9].value= 255


container[10].bin= 0
container[10].i= 572
container[10].j= 134
container[10].angle= 0
container[10].value= 255


container[11].bin= 39
container[11].i= 572
container[11].j= 140
container[11].angle= 198
container[11].value= 255


container[12].bin= 63
container[12].i= 573
container[12].j= 135
container[12].angle= 315
container[12].value= 255


container[13].bin= 48
container[13].i= 573
container[13].j= 136
container[13].angle= 243
container[13].value= 255


container[14].bin= 54
container[14].i= 573
container[14].j= 137
container[14].angle= 270
container[14].value= 255


container[15].bin= 54
container[15].i= 573
container[15].j= 138
container[15].angle= 270
container[15].value= 255


container[16].bin= 57
container[16].i= 573
container[16].j= 139
container[16].angle= 288
container[16].value= 255


container[17].bin= 30
container[17].i= 573
container[17].j= 141
container[17].angle= 153
container[17].value= 255


container[18].bin= 68
container[18].i= 574
container[18].j= 139
container[18].angle= 341
container[18].value= 255


container[19].bin= 30
container[19].i= 574
container[19].j= 141
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 575
container[20].j= 139
container[20].angle= 0
container[20].value= 255


container[21].bin= 63
container[21].i= 576
container[21].j= 140
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 576
container[22].j= 141
container[22].angle= 224
container[22].value= 255


