container[0].bin= 14
container[0].i= 712
container[0].j= 167
container[0].angle= 71
container[0].value= 255


container[1].bin= 21
container[1].i= 712
container[1].j= 168
container[1].angle= 108
container[1].value= 255


container[2].bin= 3
container[2].i= 713
container[2].j= 166
container[2].angle= 18
container[2].value= 255


container[3].bin= 0
container[3].i= 714
container[3].j= 166
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 714
container[4].j= 168
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 715
container[5].j= 166
container[5].angle= 341
container[5].value= 255


container[6].bin= 21
container[6].i= 715
container[6].j= 169
container[6].angle= 108
container[6].value= 255


container[7].bin= 27
container[7].i= 716
container[7].j= 170
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 717
container[8].j= 168
container[8].angle= 0
container[8].value= 255


container[9].bin= 0
container[9].i= 718
container[9].j= 168
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 718
container[10].j= 171
container[10].angle= 135
container[10].value= 255


container[11].bin= 18
container[11].i= 718
container[11].j= 172
container[11].angle= 90
container[11].value= 255


container[12].bin= 0
container[12].i= 719
container[12].j= 168
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 719
container[13].j= 173
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 720
container[14].j= 168
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 720
container[15].j= 173
container[15].angle= 180
container[15].value= 255


container[16].bin= 63
container[16].i= 721
container[16].j= 169
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 721
container[17].j= 174
container[17].angle= 135
container[17].value= 255


container[18].bin= 63
container[18].i= 722
container[18].j= 170
container[18].angle= 315
container[18].value= 255


container[19].bin= 27
container[19].i= 722
container[19].j= 175
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 723
container[20].j= 170
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 723
container[21].j= 175
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 724
container[22].j= 170
container[22].angle= 0
container[22].value= 255


container[23].bin= 27
container[23].i= 724
container[23].j= 176
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 725
container[24].j= 170
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 725
container[25].j= 177
container[25].angle= 135
container[25].value= 255


container[26].bin= 0
container[26].i= 726
container[26].j= 170
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 726
container[27].j= 177
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 727
container[28].j= 171
container[28].angle= 315
container[28].value= 255


container[29].bin= 54
container[29].i= 727
container[29].j= 172
container[29].angle= 270
container[29].value= 255


container[30].bin= 36
container[30].i= 727
container[30].j= 177
container[30].angle= 180
container[30].value= 255


container[31].bin= 18
container[31].i= 727
container[31].j= 180
container[31].angle= 90
container[31].value= 255


container[32].bin= 63
container[32].i= 728
container[32].j= 173
container[32].angle= 315
container[32].value= 255


container[33].bin= 36
container[33].i= 728
container[33].j= 177
container[33].angle= 180
container[33].value= 255


container[34].bin= 32
container[34].i= 728
container[34].j= 181
container[34].angle= 161
container[34].value= 255


container[35].bin= 0
container[35].i= 729
container[35].j= 173
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 729
container[36].j= 177
container[36].angle= 180
container[36].value= 255


container[37].bin= 36
container[37].i= 729
container[37].j= 181
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 730
container[38].j= 173
container[38].angle= 0
container[38].value= 255


container[39].bin= 27
container[39].i= 730
container[39].j= 178
container[39].angle= 135
container[39].value= 255


container[40].bin= 8
container[40].i= 730
container[40].j= 179
container[40].angle= 44
container[40].value= 255


container[41].bin= 18
container[41].i= 730
container[41].j= 180
container[41].angle= 90
container[41].value= 255


container[42].bin= 30
container[42].i= 730
container[42].j= 181
container[42].angle= 153
container[42].value= 255


container[43].bin= 18
container[43].i= 730
container[43].j= 185
container[43].angle= 90
container[43].value= 255


container[44].bin= 0
container[44].i= 731
container[44].j= 173
container[44].angle= 0
container[44].value= 255


container[45].bin= 30
container[45].i= 731
container[45].j= 181
container[45].angle= 153
container[45].value= 255


container[46].bin= 3
container[46].i= 731
container[46].j= 184
container[46].angle= 18
container[46].value= 255


container[47].bin= 32
container[47].i= 731
container[47].j= 186
container[47].angle= 161
container[47].value= 255


container[48].bin= 0
container[48].i= 732
container[48].j= 173
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 732
container[49].j= 181
container[49].angle= 180
container[49].value= 255


container[50].bin= 0
container[50].i= 732
container[50].j= 184
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 732
container[51].j= 186
container[51].angle= 180
container[51].value= 255


container[52].bin= 66
container[52].i= 733
container[52].j= 174
container[52].angle= 333
container[52].value= 255


container[53].bin= 27
container[53].i= 733
container[53].j= 182
container[53].angle= 135
container[53].value= 255


container[54].bin= 18
container[54].i= 733
container[54].j= 183
container[54].angle= 90
container[54].value= 255


container[55].bin= 8
container[55].i= 733
container[55].j= 184
container[55].angle= 44
container[55].value= 255


container[56].bin= 18
container[56].i= 733
container[56].j= 185
container[56].angle= 90
container[56].value= 255


container[57].bin= 30
container[57].i= 733
container[57].j= 186
container[57].angle= 153
container[57].value= 255


container[58].bin= 66
container[58].i= 734
container[58].j= 174
container[58].angle= 333
container[58].value= 255


container[59].bin= 30
container[59].i= 734
container[59].j= 186
container[59].angle= 153
container[59].value= 255


container[60].bin= 0
container[60].i= 735
container[60].j= 174
container[60].angle= 0
container[60].value= 255


container[61].bin= 36
container[61].i= 735
container[61].j= 186
container[61].angle= 180
container[61].value= 255


container[62].bin= 63
container[62].i= 736
container[62].j= 175
container[62].angle= 315
container[62].value= 255


container[63].bin= 27
container[63].i= 736
container[63].j= 187
container[63].angle= 135
container[63].value= 255


container[64].bin= 63
container[64].i= 737
container[64].j= 176
container[64].angle= 315
container[64].value= 255


container[65].bin= 27
container[65].i= 737
container[65].j= 188
container[65].angle= 135
container[65].value= 255


container[66].bin= 0
container[66].i= 738
container[66].j= 176
container[66].angle= 0
container[66].value= 255


container[67].bin= 36
container[67].i= 738
container[67].j= 188
container[67].angle= 180
container[67].value= 255


container[68].bin= 0
container[68].i= 739
container[68].j= 176
container[68].angle= 0
container[68].value= 255


container[69].bin= 36
container[69].i= 739
container[69].j= 188
container[69].angle= 180
container[69].value= 255


container[70].bin= 0
container[70].i= 740
container[70].j= 176
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 740
container[71].j= 188
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 741
container[72].j= 176
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 741
container[73].j= 188
container[73].angle= 180
container[73].value= 255


container[74].bin= 0
container[74].i= 742
container[74].j= 176
container[74].angle= 0
container[74].value= 255


container[75].bin= 36
container[75].i= 742
container[75].j= 188
container[75].angle= 180
container[75].value= 255


container[76].bin= 0
container[76].i= 743
container[76].j= 176
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 743
container[77].j= 188
container[77].angle= 180
container[77].value= 255


container[78].bin= 0
container[78].i= 744
container[78].j= 176
container[78].angle= 0
container[78].value= 255


container[79].bin= 36
container[79].i= 744
container[79].j= 188
container[79].angle= 180
container[79].value= 255


container[80].bin= 0
container[80].i= 745
container[80].j= 176
container[80].angle= 0
container[80].value= 255


container[81].bin= 30
container[81].i= 745
container[81].j= 189
container[81].angle= 153
container[81].value= 255


container[82].bin= 63
container[82].i= 746
container[82].j= 177
container[82].angle= 315
container[82].value= 255


container[83].bin= 30
container[83].i= 746
container[83].j= 189
container[83].angle= 153
container[83].value= 255


container[84].bin= 63
container[84].i= 747
container[84].j= 178
container[84].angle= 315
container[84].value= 255


container[85].bin= 36
container[85].i= 747
container[85].j= 189
container[85].angle= 180
container[85].value= 255


container[86].bin= 0
container[86].i= 748
container[86].j= 178
container[86].angle= 0
container[86].value= 255


container[87].bin= 36
container[87].i= 748
container[87].j= 189
container[87].angle= 180
container[87].value= 255


container[88].bin= 0
container[88].i= 749
container[88].j= 178
container[88].angle= 0
container[88].value= 255


container[89].bin= 27
container[89].i= 749
container[89].j= 190
container[89].angle= 135
container[89].value= 255


container[90].bin= 0
container[90].i= 750
container[90].j= 178
container[90].angle= 0
container[90].value= 255


container[91].bin= 27
container[91].i= 750
container[91].j= 191
container[91].angle= 135
container[91].value= 255


container[92].bin= 0
container[92].i= 751
container[92].j= 178
container[92].angle= 0
container[92].value= 255


container[93].bin= 36
container[93].i= 751
container[93].j= 191
container[93].angle= 180
container[93].value= 255


container[94].bin= 66
container[94].i= 752
container[94].j= 179
container[94].angle= 333
container[94].value= 255


container[95].bin= 27
container[95].i= 752
container[95].j= 192
container[95].angle= 135
container[95].value= 255


container[96].bin= 66
container[96].i= 753
container[96].j= 179
container[96].angle= 333
container[96].value= 255


container[97].bin= 27
container[97].i= 753
container[97].j= 193
container[97].angle= 135
container[97].value= 255


container[98].bin= 0
container[98].i= 754
container[98].j= 179
container[98].angle= 0
container[98].value= 255


container[99].bin= 36
container[99].i= 754
container[99].j= 193
container[99].angle= 180
container[99].value= 255


container[100].bin= 63
container[100].i= 755
container[100].j= 180
container[100].angle= 315
container[100].value= 255


container[101].bin= 36
container[101].i= 755
container[101].j= 193
container[101].angle= 180
container[101].value= 255


container[102].bin= 63
container[102].i= 756
container[102].j= 181
container[102].angle= 315
container[102].value= 255


container[103].bin= 36
container[103].i= 756
container[103].j= 193
container[103].angle= 180
container[103].value= 255


container[104].bin= 0
container[104].i= 757
container[104].j= 181
container[104].angle= 0
container[104].value= 255


container[105].bin= 36
container[105].i= 757
container[105].j= 193
container[105].angle= 180
container[105].value= 255


container[106].bin= 0
container[106].i= 758
container[106].j= 181
container[106].angle= 0
container[106].value= 255


container[107].bin= 30
container[107].i= 758
container[107].j= 194
container[107].angle= 153
container[107].value= 255


container[108].bin= 0
container[108].i= 759
container[108].j= 181
container[108].angle= 0
container[108].value= 255


container[109].bin= 30
container[109].i= 759
container[109].j= 194
container[109].angle= 153
container[109].value= 255


container[110].bin= 0
container[110].i= 760
container[110].j= 181
container[110].angle= 0
container[110].value= 255


container[111].bin= 36
container[111].i= 760
container[111].j= 194
container[111].angle= 180
container[111].value= 255


container[112].bin= 0
container[112].i= 761
container[112].j= 181
container[112].angle= 0
container[112].value= 255


container[113].bin= 36
container[113].i= 761
container[113].j= 194
container[113].angle= 180
container[113].value= 255


container[114].bin= 0
container[114].i= 762
container[114].j= 181
container[114].angle= 0
container[114].value= 255


container[115].bin= 36
container[115].i= 762
container[115].j= 194
container[115].angle= 180
container[115].value= 255


container[116].bin= 66
container[116].i= 763
container[116].j= 182
container[116].angle= 333
container[116].value= 255


container[117].bin= 36
container[117].i= 763
container[117].j= 194
container[117].angle= 180
container[117].value= 255


container[118].bin= 66
container[118].i= 764
container[118].j= 182
container[118].angle= 333
container[118].value= 255


container[119].bin= 27
container[119].i= 764
container[119].j= 195
container[119].angle= 135
container[119].value= 255


container[120].bin= 0
container[120].i= 765
container[120].j= 182
container[120].angle= 0
container[120].value= 255


container[121].bin= 27
container[121].i= 765
container[121].j= 196
container[121].angle= 135
container[121].value= 255


container[122].bin= 0
container[122].i= 766
container[122].j= 182
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 766
container[123].j= 196
container[123].angle= 180
container[123].value= 255


container[124].bin= 63
container[124].i= 767
container[124].j= 183
container[124].angle= 315
container[124].value= 255


container[125].bin= 30
container[125].i= 767
container[125].j= 197
container[125].angle= 153
container[125].value= 255


container[126].bin= 63
container[126].i= 768
container[126].j= 184
container[126].angle= 315
container[126].value= 255


container[127].bin= 30
container[127].i= 768
container[127].j= 197
container[127].angle= 153
container[127].value= 255


container[128].bin= 0
container[128].i= 769
container[128].j= 184
container[128].angle= 0
container[128].value= 255


container[129].bin= 36
container[129].i= 769
container[129].j= 197
container[129].angle= 180
container[129].value= 255


container[130].bin= 63
container[130].i= 770
container[130].j= 185
container[130].angle= 315
container[130].value= 255


container[131].bin= 27
container[131].i= 770
container[131].j= 198
container[131].angle= 135
container[131].value= 255


container[132].bin= 59
container[132].i= 771
container[132].j= 186
container[132].angle= 296
container[132].value= 255


container[133].bin= 63
container[133].i= 771
container[133].j= 187
container[133].angle= 315
container[133].value= 255


container[134].bin= 27
container[134].i= 771
container[134].j= 199
container[134].angle= 135
container[134].value= 255


container[135].bin= 66
container[135].i= 772
container[135].j= 187
container[135].angle= 333
container[135].value= 255


container[136].bin= 36
container[136].i= 772
container[136].j= 199
container[136].angle= 180
container[136].value= 255


container[137].bin= 0
container[137].i= 773
container[137].j= 187
container[137].angle= 0
container[137].value= 255


container[138].bin= 27
container[138].i= 773
container[138].j= 200
container[138].angle= 135
container[138].value= 255


container[139].bin= 0
container[139].i= 774
container[139].j= 187
container[139].angle= 0
container[139].value= 255


container[140].bin= 27
container[140].i= 774
container[140].j= 201
container[140].angle= 135
container[140].value= 255


container[141].bin= 0
container[141].i= 775
container[141].j= 187
container[141].angle= 0
container[141].value= 255


container[142].bin= 36
container[142].i= 775
container[142].j= 201
container[142].angle= 180
container[142].value= 255


container[143].bin= 63
container[143].i= 776
container[143].j= 188
container[143].angle= 315
container[143].value= 255


container[144].bin= 30
container[144].i= 776
container[144].j= 202
container[144].angle= 153
container[144].value= 255


container[145].bin= 63
container[145].i= 777
container[145].j= 189
container[145].angle= 315
container[145].value= 255


container[146].bin= 30
container[146].i= 777
container[146].j= 202
container[146].angle= 153
container[146].value= 255


container[147].bin= 0
container[147].i= 778
container[147].j= 189
container[147].angle= 0
container[147].value= 255


container[148].bin= 36
container[148].i= 778
container[148].j= 202
container[148].angle= 180
container[148].value= 255


container[149].bin= 66
container[149].i= 779
container[149].j= 190
container[149].angle= 333
container[149].value= 255


container[150].bin= 36
container[150].i= 779
container[150].j= 202
container[150].angle= 180
container[150].value= 255


container[151].bin= 66
container[151].i= 780
container[151].j= 190
container[151].angle= 333
container[151].value= 255


container[152].bin= 36
container[152].i= 780
container[152].j= 202
container[152].angle= 180
container[152].value= 255


container[153].bin= 0
container[153].i= 781
container[153].j= 190
container[153].angle= 0
container[153].value= 255


container[154].bin= 36
container[154].i= 781
container[154].j= 202
container[154].angle= 180
container[154].value= 255


container[155].bin= 63
container[155].i= 782
container[155].j= 191
container[155].angle= 315
container[155].value= 255


container[156].bin= 27
container[156].i= 782
container[156].j= 203
container[156].angle= 135
container[156].value= 255


container[157].bin= 63
container[157].i= 783
container[157].j= 192
container[157].angle= 315
container[157].value= 255


container[158].bin= 27
container[158].i= 783
container[158].j= 204
container[158].angle= 135
container[158].value= 255


container[159].bin= 0
container[159].i= 784
container[159].j= 192
container[159].angle= 0
container[159].value= 255


container[160].bin= 36
container[160].i= 784
container[160].j= 204
container[160].angle= 180
container[160].value= 255


container[161].bin= 63
container[161].i= 785
container[161].j= 193
container[161].angle= 315
container[161].value= 255


container[162].bin= 54
container[162].i= 785
container[162].j= 194
container[162].angle= 270
container[162].value= 255


container[163].bin= 30
container[163].i= 785
container[163].j= 205
container[163].angle= 153
container[163].value= 255


container[164].bin= 63
container[164].i= 786
container[164].j= 195
container[164].angle= 315
container[164].value= 255


container[165].bin= 30
container[165].i= 786
container[165].j= 205
container[165].angle= 153
container[165].value= 255


container[166].bin= 0
container[166].i= 787
container[166].j= 195
container[166].angle= 0
container[166].value= 255


container[167].bin= 36
container[167].i= 787
container[167].j= 205
container[167].angle= 180
container[167].value= 255


container[168].bin= 0
container[168].i= 788
container[168].j= 195
container[168].angle= 0
container[168].value= 255


container[169].bin= 27
container[169].i= 788
container[169].j= 206
container[169].angle= 135
container[169].value= 255


container[170].bin= 0
container[170].i= 789
container[170].j= 195
container[170].angle= 0
container[170].value= 255


container[171].bin= 27
container[171].i= 789
container[171].j= 207
container[171].angle= 135
container[171].value= 255


container[172].bin= 0
container[172].i= 790
container[172].j= 195
container[172].angle= 0
container[172].value= 255


container[173].bin= 36
container[173].i= 790
container[173].j= 207
container[173].angle= 180
container[173].value= 255


container[174].bin= 63
container[174].i= 791
container[174].j= 196
container[174].angle= 315
container[174].value= 255


container[175].bin= 36
container[175].i= 791
container[175].j= 207
container[175].angle= 180
container[175].value= 255


container[176].bin= 63
container[176].i= 792
container[176].j= 197
container[176].angle= 315
container[176].value= 255


container[177].bin= 36
container[177].i= 792
container[177].j= 207
container[177].angle= 180
container[177].value= 255


container[178].bin= 0
container[178].i= 793
container[178].j= 197
container[178].angle= 0
container[178].value= 255


container[179].bin= 36
container[179].i= 793
container[179].j= 207
container[179].angle= 180
container[179].value= 255


container[180].bin= 66
container[180].i= 794
container[180].j= 198
container[180].angle= 333
container[180].value= 255


container[181].bin= 27
container[181].i= 794
container[181].j= 208
container[181].angle= 135
container[181].value= 255


container[182].bin= 66
container[182].i= 795
container[182].j= 198
container[182].angle= 333
container[182].value= 255


container[183].bin= 27
container[183].i= 795
container[183].j= 209
container[183].angle= 135
container[183].value= 255


container[184].bin= 0
container[184].i= 796
container[184].j= 198
container[184].angle= 0
container[184].value= 255


container[185].bin= 36
container[185].i= 796
container[185].j= 209
container[185].angle= 180
container[185].value= 255


container[186].bin= 0
container[186].i= 797
container[186].j= 198
container[186].angle= 0
container[186].value= 255


container[187].bin= 36
container[187].i= 797
container[187].j= 209
container[187].angle= 180
container[187].value= 255


container[188].bin= 0
container[188].i= 798
container[188].j= 198
container[188].angle= 0
container[188].value= 255


container[189].bin= 36
container[189].i= 798
container[189].j= 209
container[189].angle= 180
container[189].value= 255


container[190].bin= 0
container[190].i= 799
container[190].j= 198
container[190].angle= 0
container[190].value= 255


container[191].bin= 36
container[191].i= 799
container[191].j= 209
container[191].angle= 180
container[191].value= 255


container[192].bin= 0
container[192].i= 800
container[192].j= 198
container[192].angle= 0
container[192].value= 255


container[193].bin= 44
container[193].i= 800
container[193].j= 205
container[193].angle= 224
container[193].value= 255


container[194].bin= 54
container[194].i= 800
container[194].j= 206
container[194].angle= 270
container[194].value= 255


container[195].bin= 54
container[195].i= 800
container[195].j= 207
container[195].angle= 270
container[195].value= 255


container[196].bin= 44
container[196].i= 800
container[196].j= 209
container[196].angle= 224
container[196].value= 255


container[197].bin= 0
container[197].i= 801
container[197].j= 198
container[197].angle= 0
container[197].value= 255


container[198].bin= 36
container[198].i= 801
container[198].j= 205
container[198].angle= 180
container[198].value= 255


container[199].bin= 44
container[199].i= 801
container[199].j= 208
container[199].angle= 224
container[199].value= 255


container[200].bin= 0
container[200].i= 802
container[200].j= 198
container[200].angle= 0
container[200].value= 255


container[201].bin= 36
container[201].i= 802
container[201].j= 205
container[201].angle= 180
container[201].value= 255


container[202].bin= 44
container[202].i= 802
container[202].j= 207
container[202].angle= 224
container[202].value= 255


container[203].bin= 63
container[203].i= 803
container[203].j= 199
container[203].angle= 315
container[203].value= 255


container[204].bin= 44
container[204].i= 803
container[204].j= 206
container[204].angle= 224
container[204].value= 255


container[205].bin= 63
container[205].i= 804
container[205].j= 200
container[205].angle= 315
container[205].value= 255


container[206].bin= 36
container[206].i= 804
container[206].j= 205
container[206].angle= 180
container[206].value= 255


container[207].bin= 0
container[207].i= 805
container[207].j= 200
container[207].angle= 0
container[207].value= 255


container[208].bin= 36
container[208].i= 805
container[208].j= 205
container[208].angle= 180
container[208].value= 255


container[209].bin= 0
container[209].i= 806
container[209].j= 200
container[209].angle= 0
container[209].value= 255


container[210].bin= 36
container[210].i= 806
container[210].j= 205
container[210].angle= 180
container[210].value= 255


container[211].bin= 0
container[211].i= 807
container[211].j= 200
container[211].angle= 0
container[211].value= 255


container[212].bin= 36
container[212].i= 807
container[212].j= 205
container[212].angle= 180
container[212].value= 255


container[213].bin= 0
container[213].i= 808
container[213].j= 200
container[213].angle= 0
container[213].value= 255


container[214].bin= 36
container[214].i= 808
container[214].j= 205
container[214].angle= 180
container[214].value= 255


container[215].bin= 63
container[215].i= 809
container[215].j= 201
container[215].angle= 315
container[215].value= 255


container[216].bin= 27
container[216].i= 809
container[216].j= 206
container[216].angle= 135
container[216].value= 255


container[217].bin= 63
container[217].i= 810
container[217].j= 202
container[217].angle= 315
container[217].value= 255


container[218].bin= 27
container[218].i= 810
container[218].j= 207
container[218].angle= 135
container[218].value= 255


container[219].bin= 0
container[219].i= 811
container[219].j= 202
container[219].angle= 0
container[219].value= 255


container[220].bin= 36
container[220].i= 811
container[220].j= 207
container[220].angle= 180
container[220].value= 255


container[221].bin= 66
container[221].i= 812
container[221].j= 203
container[221].angle= 333
container[221].value= 255


container[222].bin= 36
container[222].i= 812
container[222].j= 207
container[222].angle= 180
container[222].value= 255


container[223].bin= 66
container[223].i= 813
container[223].j= 203
container[223].angle= 333
container[223].value= 255


container[224].bin= 36
container[224].i= 813
container[224].j= 207
container[224].angle= 180
container[224].value= 255


container[225].bin= 0
container[225].i= 814
container[225].j= 203
container[225].angle= 0
container[225].value= 255


container[226].bin= 36
container[226].i= 814
container[226].j= 207
container[226].angle= 180
container[226].value= 255


container[227].bin= 63
container[227].i= 815
container[227].j= 204
container[227].angle= 315
container[227].value= 255


container[228].bin= 54
container[228].i= 815
container[228].j= 205
container[228].angle= 270
container[228].value= 255


container[229].bin= 54
container[229].i= 815
container[229].j= 206
container[229].angle= 270
container[229].value= 255


container[230].bin= 44
container[230].i= 815
container[230].j= 207
container[230].angle= 224
container[230].value= 255


