container[0].bin= 18
container[0].i= 207
container[0].j= 563
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 207
container[1].j= 564
container[1].angle= 90
container[1].value= 255


container[2].bin= 21
container[2].i= 207
container[2].j= 565
container[2].angle= 108
container[2].value= 255


container[3].bin= 8
container[3].i= 208
container[3].j= 562
container[3].angle= 44
container[3].value= 255


container[4].bin= 0
container[4].i= 209
container[4].j= 561
container[4].angle= 0
container[4].value= 255


container[5].bin= 39
container[5].i= 209
container[5].j= 564
container[5].angle= 198
container[5].value= 255


container[6].bin= 5
container[6].i= 210
container[6].j= 561
container[6].angle= 26
container[6].value= 255


container[7].bin= 27
container[7].i= 210
container[7].j= 564
container[7].angle= 135
container[7].value= 255


container[8].bin= 23
container[8].i= 210
container[8].j= 565
container[8].angle= 116
container[8].value= 255


container[9].bin= 18
container[9].i= 210
container[9].j= 566
container[9].angle= 90
container[9].value= 255


container[10].bin= 5
container[10].i= 211
container[10].j= 561
container[10].angle= 26
container[10].value= 255


container[11].bin= 27
container[11].i= 211
container[11].j= 567
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 212
container[12].j= 560
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 212
container[13].j= 567
container[13].angle= 180
container[13].value= 255


container[14].bin= 66
container[14].i= 213
container[14].j= 561
container[14].angle= 333
container[14].value= 255


container[15].bin= 27
container[15].i= 213
container[15].j= 568
container[15].angle= 135
container[15].value= 255


container[16].bin= 18
container[16].i= 213
container[16].j= 569
container[16].angle= 90
container[16].value= 255


container[17].bin= 21
container[17].i= 213
container[17].j= 570
container[17].angle= 108
container[17].value= 255


container[18].bin= 66
container[18].i= 214
container[18].j= 561
container[18].angle= 333
container[18].value= 255


container[19].bin= 27
container[19].i= 214
container[19].j= 570
container[19].angle= 135
container[19].value= 255


container[20].bin= 0
container[20].i= 215
container[20].j= 561
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 215
container[21].j= 568
container[21].angle= 180
container[21].value= 255


container[22].bin= 36
container[22].i= 215
container[22].j= 571
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 216
container[23].j= 561
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 216
container[24].j= 568
container[24].angle= 135
container[24].value= 255


container[25].bin= 18
container[25].i= 216
container[25].j= 569
container[25].angle= 90
container[25].value= 255


container[26].bin= 32
container[26].i= 216
container[26].j= 570
container[26].angle= 161
container[26].value= 255


container[27].bin= 0
container[27].i= 217
container[27].j= 561
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 217
container[28].j= 570
container[28].angle= 180
container[28].value= 255


container[29].bin= 8
container[29].i= 217
container[29].j= 590
container[29].angle= 44
container[29].value= 255


container[30].bin= 27
container[30].i= 217
container[30].j= 591
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 218
container[31].j= 561
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 218
container[32].j= 570
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 218
container[33].j= 589
container[33].angle= 0
container[33].value= 255


container[34].bin= 0
container[34].i= 219
container[34].j= 561
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 219
container[35].j= 570
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 219
container[36].j= 589
container[36].angle= 0
container[36].value= 255


container[37].bin= 30
container[37].i= 219
container[37].j= 592
container[37].angle= 153
container[37].value= 255


container[38].bin= 0
container[38].i= 220
container[38].j= 561
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 220
container[39].j= 570
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 220
container[40].j= 589
container[40].angle= 0
container[40].value= 255


container[41].bin= 30
container[41].i= 220
container[41].j= 592
container[41].angle= 153
container[41].value= 255


container[42].bin= 0
container[42].i= 221
container[42].j= 561
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 221
container[43].j= 570
container[43].angle= 180
container[43].value= 255


container[44].bin= 0
container[44].i= 221
container[44].j= 589
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 221
container[45].j= 592
container[45].angle= 180
container[45].value= 255


container[46].bin= 0
container[46].i= 222
container[46].j= 561
container[46].angle= 0
container[46].value= 255


container[47].bin= 36
container[47].i= 222
container[47].j= 570
container[47].angle= 180
container[47].value= 255


container[48].bin= 8
container[48].i= 222
container[48].j= 589
container[48].angle= 44
container[48].value= 255


container[49].bin= 27
container[49].i= 222
container[49].j= 593
container[49].angle= 135
container[49].value= 255


container[50].bin= 0
container[50].i= 223
container[50].j= 561
container[50].angle= 0
container[50].value= 255


container[51].bin= 36
container[51].i= 223
container[51].j= 570
container[51].angle= 180
container[51].value= 255


container[52].bin= 8
container[52].i= 223
container[52].j= 588
container[52].angle= 44
container[52].value= 255


container[53].bin= 27
container[53].i= 223
container[53].j= 594
container[53].angle= 135
container[53].value= 255


container[54].bin= 0
container[54].i= 224
container[54].j= 561
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 224
container[55].j= 570
container[55].angle= 180
container[55].value= 255


container[56].bin= 0
container[56].i= 224
container[56].j= 587
container[56].angle= 0
container[56].value= 255


container[57].bin= 36
container[57].i= 224
container[57].j= 594
container[57].angle= 180
container[57].value= 255


container[58].bin= 63
container[58].i= 225
container[58].j= 562
container[58].angle= 315
container[58].value= 255


container[59].bin= 36
container[59].i= 225
container[59].j= 570
container[59].angle= 180
container[59].value= 255


container[60].bin= 18
container[60].i= 225
container[60].j= 572
container[60].angle= 90
container[60].value= 255


container[61].bin= 18
container[61].i= 225
container[61].j= 586
container[61].angle= 90
container[61].value= 255


container[62].bin= 8
container[62].i= 225
container[62].j= 587
container[62].angle= 44
container[62].value= 255


container[63].bin= 27
container[63].i= 225
container[63].j= 595
container[63].angle= 135
container[63].value= 255


container[64].bin= 18
container[64].i= 225
container[64].j= 596
container[64].angle= 90
container[64].value= 255


container[65].bin= 63
container[65].i= 226
container[65].j= 563
container[65].angle= 315
container[65].value= 255


container[66].bin= 32
container[66].i= 226
container[66].j= 570
container[66].angle= 161
container[66].value= 255


container[67].bin= 27
container[67].i= 226
container[67].j= 571
container[67].angle= 135
container[67].value= 255


container[68].bin= 8
container[68].i= 226
container[68].j= 585
container[68].angle= 44
container[68].value= 255


container[69].bin= 27
container[69].i= 226
container[69].j= 597
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 227
container[70].j= 563
container[70].angle= 0
container[70].value= 255


container[71].bin= 32
container[71].i= 227
container[71].j= 571
container[71].angle= 161
container[71].value= 255


container[72].bin= 0
container[72].i= 227
container[72].j= 584
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 227
container[73].j= 597
container[73].angle= 180
container[73].value= 255


container[74].bin= 66
container[74].i= 228
container[74].j= 564
container[74].angle= 333
container[74].value= 255


container[75].bin= 30
container[75].i= 228
container[75].j= 572
container[75].angle= 153
container[75].value= 255


container[76].bin= 0
container[76].i= 228
container[76].j= 584
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 228
container[77].j= 597
container[77].angle= 180
container[77].value= 255


container[78].bin= 66
container[78].i= 229
container[78].j= 564
container[78].angle= 333
container[78].value= 255


container[79].bin= 30
container[79].i= 229
container[79].j= 572
container[79].angle= 153
container[79].value= 255


container[80].bin= 0
container[80].i= 229
container[80].j= 584
container[80].angle= 0
container[80].value= 255


container[81].bin= 44
container[81].i= 229
container[81].j= 592
container[81].angle= 224
container[81].value= 255


container[82].bin= 63
container[82].i= 229
container[82].j= 593
container[82].angle= 315
container[82].value= 255


container[83].bin= 36
container[83].i= 229
container[83].j= 597
container[83].angle= 180
container[83].value= 255


container[84].bin= 0
container[84].i= 230
container[84].j= 564
container[84].angle= 0
container[84].value= 255


container[85].bin= 36
container[85].i= 230
container[85].j= 572
container[85].angle= 180
container[85].value= 255


container[86].bin= 0
container[86].i= 230
container[86].j= 584
container[86].angle= 0
container[86].value= 255


container[87].bin= 39
container[87].i= 230
container[87].j= 591
container[87].angle= 198
container[87].value= 255


container[88].bin= 30
container[88].i= 230
container[88].j= 598
container[88].angle= 153
container[88].value= 255


container[89].bin= 63
container[89].i= 231
container[89].j= 565
container[89].angle= 315
container[89].value= 255


container[90].bin= 27
container[90].i= 231
container[90].j= 573
container[90].angle= 135
container[90].value= 255


container[91].bin= 18
container[91].i= 231
container[91].j= 574
container[91].angle= 90
container[91].value= 255


container[92].bin= 18
container[92].i= 231
container[92].j= 575
container[92].angle= 90
container[92].value= 255


container[93].bin= 0
container[93].i= 231
container[93].j= 584
container[93].angle= 0
container[93].value= 255


container[94].bin= 39
container[94].i= 231
container[94].j= 589
container[94].angle= 198
container[94].value= 255


container[95].bin= 50
container[95].i= 231
container[95].j= 590
container[95].angle= 251
container[95].value= 255


container[96].bin= 27
container[96].i= 231
container[96].j= 598
container[96].angle= 135
container[96].value= 255


container[97].bin= 23
container[97].i= 231
container[97].j= 599
container[97].angle= 116
container[97].value= 255


container[98].bin= 63
container[98].i= 232
container[98].j= 566
container[98].angle= 315
container[98].value= 255


container[99].bin= 27
container[99].i= 232
container[99].j= 576
container[99].angle= 135
container[99].value= 255


container[100].bin= 0
container[100].i= 232
container[100].j= 584
container[100].angle= 0
container[100].value= 255


container[101].bin= 36
container[101].i= 232
container[101].j= 589
container[101].angle= 180
container[101].value= 255


container[102].bin= 0
container[102].i= 232
container[102].j= 593
container[102].angle= 0
container[102].value= 255


container[103].bin= 27
container[103].i= 232
container[103].j= 600
container[103].angle= 135
container[103].value= 255


container[104].bin= 0
container[104].i= 233
container[104].j= 566
container[104].angle= 0
container[104].value= 255


container[105].bin= 36
container[105].i= 233
container[105].j= 576
container[105].angle= 180
container[105].value= 255


container[106].bin= 0
container[106].i= 233
container[106].j= 584
container[106].angle= 0
container[106].value= 255


container[107].bin= 36
container[107].i= 233
container[107].j= 589
container[107].angle= 180
container[107].value= 255


container[108].bin= 0
container[108].i= 233
container[108].j= 593
container[108].angle= 0
container[108].value= 255


container[109].bin= 36
container[109].i= 233
container[109].j= 600
container[109].angle= 180
container[109].value= 255


container[110].bin= 63
container[110].i= 234
container[110].j= 567
container[110].angle= 315
container[110].value= 255


container[111].bin= 27
container[111].i= 234
container[111].j= 577
container[111].angle= 135
container[111].value= 255


container[112].bin= 0
container[112].i= 234
container[112].j= 584
container[112].angle= 0
container[112].value= 255


container[113].bin= 41
container[113].i= 234
container[113].j= 589
container[113].angle= 206
container[113].value= 255


container[114].bin= 0
container[114].i= 234
container[114].j= 593
container[114].angle= 0
container[114].value= 255


container[115].bin= 27
container[115].i= 234
container[115].j= 601
container[115].angle= 135
container[115].value= 255


container[116].bin= 63
container[116].i= 235
container[116].j= 568
container[116].angle= 315
container[116].value= 255


container[117].bin= 27
container[117].i= 235
container[117].j= 578
container[117].angle= 135
container[117].value= 255


container[118].bin= 0
container[118].i= 235
container[118].j= 584
container[118].angle= 0
container[118].value= 255


container[119].bin= 41
container[119].i= 235
container[119].j= 589
container[119].angle= 206
container[119].value= 255


container[120].bin= 0
container[120].i= 235
container[120].j= 593
container[120].angle= 0
container[120].value= 255


container[121].bin= 27
container[121].i= 235
container[121].j= 602
container[121].angle= 135
container[121].value= 255


container[122].bin= 0
container[122].i= 236
container[122].j= 568
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 236
container[123].j= 578
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 236
container[124].j= 584
container[124].angle= 0
container[124].value= 255


container[125].bin= 36
container[125].i= 236
container[125].j= 588
container[125].angle= 180
container[125].value= 255


container[126].bin= 0
container[126].i= 236
container[126].j= 593
container[126].angle= 0
container[126].value= 255


container[127].bin= 39
container[127].i= 236
container[127].j= 598
container[127].angle= 198
container[127].value= 255


container[128].bin= 50
container[128].i= 236
container[128].j= 599
container[128].angle= 251
container[128].value= 255


container[129].bin= 63
container[129].i= 236
container[129].j= 600
container[129].angle= 315
container[129].value= 255


container[130].bin= 36
container[130].i= 236
container[130].j= 602
container[130].angle= 180
container[130].value= 255


container[131].bin= 66
container[131].i= 237
container[131].j= 569
container[131].angle= 333
container[131].value= 255


container[132].bin= 27
container[132].i= 237
container[132].j= 579
container[132].angle= 135
container[132].value= 255


container[133].bin= 18
container[133].i= 237
container[133].j= 580
container[133].angle= 90
container[133].value= 255


container[134].bin= 0
container[134].i= 237
container[134].j= 584
container[134].angle= 0
container[134].value= 255


container[135].bin= 44
container[135].i= 237
container[135].j= 588
container[135].angle= 224
container[135].value= 255


container[136].bin= 63
container[136].i= 237
container[136].j= 594
container[136].angle= 315
container[136].value= 255


container[137].bin= 54
container[137].i= 237
container[137].j= 596
container[137].angle= 270
container[137].value= 255


container[138].bin= 3
container[138].i= 237
container[138].j= 600
container[138].angle= 18
container[138].value= 255


container[139].bin= 36
container[139].i= 237
container[139].j= 602
container[139].angle= 180
container[139].value= 255


container[140].bin= 66
container[140].i= 238
container[140].j= 569
container[140].angle= 333
container[140].value= 255


container[141].bin= 27
container[141].i= 238
container[141].j= 581
container[141].angle= 135
container[141].value= 255


container[142].bin= 0
container[142].i= 238
container[142].j= 584
container[142].angle= 0
container[142].value= 255


container[143].bin= 44
container[143].i= 238
container[143].j= 587
container[143].angle= 224
container[143].value= 255


container[144].bin= 63
container[144].i= 238
container[144].j= 595
container[144].angle= 315
container[144].value= 255


container[145].bin= 36
container[145].i= 238
container[145].j= 602
container[145].angle= 180
container[145].value= 255


container[146].bin= 0
container[146].i= 239
container[146].j= 569
container[146].angle= 0
container[146].value= 255


container[147].bin= 36
container[147].i= 239
container[147].j= 581
container[147].angle= 180
container[147].value= 255


container[148].bin= 0
container[148].i= 239
container[148].j= 584
container[148].angle= 0
container[148].value= 255


container[149].bin= 0
container[149].i= 239
container[149].j= 595
container[149].angle= 0
container[149].value= 255


container[150].bin= 36
container[150].i= 239
container[150].j= 602
container[150].angle= 180
container[150].value= 255


container[151].bin= 63
container[151].i= 240
container[151].j= 570
container[151].angle= 315
container[151].value= 255


container[152].bin= 27
container[152].i= 240
container[152].j= 582
container[152].angle= 135
container[152].value= 255


container[153].bin= 18
container[153].i= 240
container[153].j= 583
container[153].angle= 90
container[153].value= 255


container[154].bin= 8
container[154].i= 240
container[154].j= 584
container[154].angle= 44
container[154].value= 255


container[155].bin= 68
container[155].i= 240
container[155].j= 595
container[155].angle= 341
container[155].value= 255


container[156].bin= 54
container[156].i= 240
container[156].j= 596
container[156].angle= 270
container[156].value= 255


container[157].bin= 5
container[157].i= 240
container[157].j= 598
container[157].angle= 26
container[157].value= 255


container[158].bin= 27
container[158].i= 240
container[158].j= 603
container[158].angle= 135
container[158].value= 255


container[159].bin= 63
container[159].i= 241
container[159].j= 571
container[159].angle= 315
container[159].value= 255


container[160].bin= 36
container[160].i= 241
container[160].j= 586
container[160].angle= 180
container[160].value= 255


container[161].bin= 68
container[161].i= 241
container[161].j= 597
container[161].angle= 341
container[161].value= 255


container[162].bin= 27
container[162].i= 241
container[162].j= 604
container[162].angle= 135
container[162].value= 255


container[163].bin= 0
container[163].i= 242
container[163].j= 571
container[163].angle= 0
container[163].value= 255


container[164].bin= 36
container[164].i= 242
container[164].j= 586
container[164].angle= 180
container[164].value= 255


container[165].bin= 0
container[165].i= 242
container[165].j= 597
container[165].angle= 0
container[165].value= 255


container[166].bin= 36
container[166].i= 242
container[166].j= 604
container[166].angle= 180
container[166].value= 255


container[167].bin= 63
container[167].i= 243
container[167].j= 572
container[167].angle= 315
container[167].value= 255


container[168].bin= 54
container[168].i= 243
container[168].j= 573
container[168].angle= 270
container[168].value= 255


container[169].bin= 27
container[169].i= 243
container[169].j= 587
container[169].angle= 135
container[169].value= 255


container[170].bin= 18
container[170].i= 243
container[170].j= 588
container[170].angle= 90
container[170].value= 255


container[171].bin= 0
container[171].i= 243
container[171].j= 597
container[171].angle= 0
container[171].value= 255


container[172].bin= 54
container[172].i= 243
container[172].j= 602
container[172].angle= 270
container[172].value= 255


container[173].bin= 27
container[173].i= 243
container[173].j= 605
container[173].angle= 135
container[173].value= 255


container[174].bin= 18
container[174].i= 243
container[174].j= 606
container[174].angle= 90
container[174].value= 255


container[175].bin= 63
container[175].i= 244
container[175].j= 574
container[175].angle= 315
container[175].value= 255


container[176].bin= 27
container[176].i= 244
container[176].j= 589
container[176].angle= 135
container[176].value= 255


container[177].bin= 0
container[177].i= 244
container[177].j= 597
container[177].angle= 0
container[177].value= 255


container[178].bin= 44
container[178].i= 244
container[178].j= 601
container[178].angle= 224
container[178].value= 255


container[179].bin= 63
container[179].i= 244
container[179].j= 603
container[179].angle= 315
container[179].value= 255


container[180].bin= 27
container[180].i= 244
container[180].j= 607
container[180].angle= 135
container[180].value= 255


container[181].bin= 0
container[181].i= 245
container[181].j= 574
container[181].angle= 0
container[181].value= 255


container[182].bin= 36
container[182].i= 245
container[182].j= 589
container[182].angle= 180
container[182].value= 255


container[183].bin= 0
container[183].i= 245
container[183].j= 597
container[183].angle= 0
container[183].value= 255


container[184].bin= 36
container[184].i= 245
container[184].j= 600
container[184].angle= 180
container[184].value= 255


container[185].bin= 5
container[185].i= 245
container[185].j= 603
container[185].angle= 26
container[185].value= 255


container[186].bin= 36
container[186].i= 245
container[186].j= 607
container[186].angle= 180
container[186].value= 255


container[187].bin= 63
container[187].i= 246
container[187].j= 575
container[187].angle= 315
container[187].value= 255


container[188].bin= 32
container[188].i= 246
container[188].j= 589
container[188].angle= 161
container[188].value= 255


container[189].bin= 21
container[189].i= 246
container[189].j= 591
container[189].angle= 108
container[189].value= 255


container[190].bin= 66
container[190].i= 246
container[190].j= 598
container[190].angle= 333
container[190].value= 255


container[191].bin= 27
container[191].i= 246
container[191].j= 601
container[191].angle= 135
container[191].value= 255


container[192].bin= 12
container[192].i= 246
container[192].j= 602
container[192].angle= 63
container[192].value= 255


container[193].bin= 8
container[193].i= 246
container[193].j= 603
container[193].angle= 44
container[193].value= 255


container[194].bin= 30
container[194].i= 246
container[194].j= 608
container[194].angle= 153
container[194].value= 255


container[195].bin= 63
container[195].i= 247
container[195].j= 576
container[195].angle= 315
container[195].value= 255


container[196].bin= 30
container[196].i= 247
container[196].j= 592
container[196].angle= 153
container[196].value= 255


container[197].bin= 66
container[197].i= 247
container[197].j= 598
container[197].angle= 333
container[197].value= 255


container[198].bin= 30
container[198].i= 247
container[198].j= 608
container[198].angle= 153
container[198].value= 255


container[199].bin= 0
container[199].i= 248
container[199].j= 576
container[199].angle= 0
container[199].value= 255


container[200].bin= 36
container[200].i= 248
container[200].j= 592
container[200].angle= 180
container[200].value= 255


container[201].bin= 0
container[201].i= 248
container[201].j= 598
container[201].angle= 0
container[201].value= 255


container[202].bin= 36
container[202].i= 248
container[202].j= 608
container[202].angle= 180
container[202].value= 255


container[203].bin= 66
container[203].i= 249
container[203].j= 577
container[203].angle= 333
container[203].value= 255


container[204].bin= 48
container[204].i= 249
container[204].j= 591
container[204].angle= 243
container[204].value= 255


container[205].bin= 44
container[205].i= 249
container[205].j= 592
container[205].angle= 224
container[205].value= 255


container[206].bin= 63
container[206].i= 249
container[206].j= 599
container[206].angle= 315
container[206].value= 255


container[207].bin= 54
container[207].i= 249
container[207].j= 600
container[207].angle= 270
container[207].value= 255


container[208].bin= 54
container[208].i= 249
container[208].j= 601
container[208].angle= 270
container[208].value= 255


container[209].bin= 57
container[209].i= 249
container[209].j= 602
container[209].angle= 288
container[209].value= 255


container[210].bin= 36
container[210].i= 249
container[210].j= 608
container[210].angle= 180
container[210].value= 255


container[211].bin= 66
container[211].i= 250
container[211].j= 577
container[211].angle= 333
container[211].value= 255


container[212].bin= 44
container[212].i= 250
container[212].j= 590
container[212].angle= 224
container[212].value= 255


container[213].bin= 36
container[213].i= 250
container[213].j= 608
container[213].angle= 180
container[213].value= 255


container[214].bin= 0
container[214].i= 251
container[214].j= 577
container[214].angle= 0
container[214].value= 255


container[215].bin= 36
container[215].i= 251
container[215].j= 589
container[215].angle= 180
container[215].value= 255


container[216].bin= 0
container[216].i= 251
container[216].j= 602
container[216].angle= 0
container[216].value= 255


container[217].bin= 30
container[217].i= 251
container[217].j= 609
container[217].angle= 153
container[217].value= 255


container[218].bin= 63
container[218].i= 252
container[218].j= 578
container[218].angle= 315
container[218].value= 255


container[219].bin= 54
container[219].i= 252
container[219].j= 579
container[219].angle= 270
container[219].value= 255


container[220].bin= 54
container[220].i= 252
container[220].j= 580
container[220].angle= 270
container[220].value= 255


container[221].bin= 36
container[221].i= 252
container[221].j= 589
container[221].angle= 180
container[221].value= 255


container[222].bin= 63
container[222].i= 252
container[222].j= 602
container[222].angle= 315
container[222].value= 255


container[223].bin= 63
container[223].i= 252
container[223].j= 603
container[223].angle= 315
container[223].value= 255


container[224].bin= 27
container[224].i= 252
container[224].j= 609
container[224].angle= 135
container[224].value= 255


container[225].bin= 27
container[225].i= 252
container[225].j= 610
container[225].angle= 135
container[225].value= 255


container[226].bin= 63
container[226].i= 253
container[226].j= 581
container[226].angle= 315
container[226].value= 255


container[227].bin= 36
container[227].i= 253
container[227].j= 589
container[227].angle= 180
container[227].value= 255


container[228].bin= 66
container[228].i= 253
container[228].j= 603
container[228].angle= 333
container[228].value= 255


container[229].bin= 30
container[229].i= 253
container[229].j= 610
container[229].angle= 153
container[229].value= 255


container[230].bin= 0
container[230].i= 254
container[230].j= 581
container[230].angle= 0
container[230].value= 255


container[231].bin= 36
container[231].i= 254
container[231].j= 589
container[231].angle= 180
container[231].value= 255


container[232].bin= 0
container[232].i= 254
container[232].j= 603
container[232].angle= 0
container[232].value= 255


container[233].bin= 36
container[233].i= 254
container[233].j= 610
container[233].angle= 180
container[233].value= 255


container[234].bin= 63
container[234].i= 255
container[234].j= 582
container[234].angle= 315
container[234].value= 255


container[235].bin= 54
container[235].i= 255
container[235].j= 583
container[235].angle= 270
container[235].value= 255


container[236].bin= 27
container[236].i= 255
container[236].j= 590
container[236].angle= 135
container[236].value= 255


container[237].bin= 63
container[237].i= 255
container[237].j= 604
container[237].angle= 315
container[237].value= 255


container[238].bin= 27
container[238].i= 255
container[238].j= 611
container[238].angle= 135
container[238].value= 255


container[239].bin= 18
container[239].i= 255
container[239].j= 612
container[239].angle= 90
container[239].value= 255


container[240].bin= 18
container[240].i= 255
container[240].j= 613
container[240].angle= 90
container[240].value= 255


container[241].bin= 18
container[241].i= 255
container[241].j= 614
container[241].angle= 90
container[241].value= 255


container[242].bin= 63
container[242].i= 256
container[242].j= 584
container[242].angle= 315
container[242].value= 255


container[243].bin= 27
container[243].i= 256
container[243].j= 591
container[243].angle= 135
container[243].value= 255


container[244].bin= 63
container[244].i= 256
container[244].j= 605
container[244].angle= 315
container[244].value= 255


container[245].bin= 27
container[245].i= 256
container[245].j= 615
container[245].angle= 135
container[245].value= 255


container[246].bin= 0
container[246].i= 257
container[246].j= 584
container[246].angle= 0
container[246].value= 255


container[247].bin= 36
container[247].i= 257
container[247].j= 591
container[247].angle= 180
container[247].value= 255


container[248].bin= 0
container[248].i= 257
container[248].j= 605
container[248].angle= 0
container[248].value= 255


container[249].bin= 36
container[249].i= 257
container[249].j= 615
container[249].angle= 180
container[249].value= 255


container[250].bin= 0
container[250].i= 258
container[250].j= 584
container[250].angle= 0
container[250].value= 255


container[251].bin= 36
container[251].i= 258
container[251].j= 591
container[251].angle= 180
container[251].value= 255


container[252].bin= 66
container[252].i= 258
container[252].j= 606
container[252].angle= 333
container[252].value= 255


container[253].bin= 27
container[253].i= 258
container[253].j= 616
container[253].angle= 135
container[253].value= 255


container[254].bin= 18
container[254].i= 258
container[254].j= 617
container[254].angle= 90
container[254].value= 255


container[255].bin= 18
container[255].i= 258
container[255].j= 618
container[255].angle= 90
container[255].value= 255


container[256].bin= 18
container[256].i= 258
container[256].j= 619
container[256].angle= 90
container[256].value= 255


container[257].bin= 0
container[257].i= 259
container[257].j= 584
container[257].angle= 0
container[257].value= 255


container[258].bin= 36
container[258].i= 259
container[258].j= 591
container[258].angle= 180
container[258].value= 255


container[259].bin= 66
container[259].i= 259
container[259].j= 606
container[259].angle= 333
container[259].value= 255


container[260].bin= 27
container[260].i= 259
container[260].j= 620
container[260].angle= 135
container[260].value= 255


container[261].bin= 0
container[261].i= 260
container[261].j= 584
container[261].angle= 0
container[261].value= 255


container[262].bin= 30
container[262].i= 260
container[262].j= 592
container[262].angle= 153
container[262].value= 255


container[263].bin= 0
container[263].i= 260
container[263].j= 606
container[263].angle= 0
container[263].value= 255


container[264].bin= 30
container[264].i= 260
container[264].j= 621
container[264].angle= 153
container[264].value= 255


container[265].bin= 63
container[265].i= 261
container[265].j= 585
container[265].angle= 315
container[265].value= 255


container[266].bin= 54
container[266].i= 261
container[266].j= 586
container[266].angle= 270
container[266].value= 255


container[267].bin= 30
container[267].i= 261
container[267].j= 592
container[267].angle= 153
container[267].value= 255


container[268].bin= 63
container[268].i= 261
container[268].j= 607
container[268].angle= 315
container[268].value= 255


container[269].bin= 54
container[269].i= 261
container[269].j= 608
container[269].angle= 270
container[269].value= 255


container[270].bin= 44
container[270].i= 261
container[270].j= 611
container[270].angle= 224
container[270].value= 255


container[271].bin= 54
container[271].i= 261
container[271].j= 612
container[271].angle= 270
container[271].value= 255


container[272].bin= 63
container[272].i= 261
container[272].j= 613
container[272].angle= 315
container[272].value= 255


container[273].bin= 27
container[273].i= 261
container[273].j= 621
container[273].angle= 135
container[273].value= 255


container[274].bin= 23
container[274].i= 261
container[274].j= 622
container[274].angle= 116
container[274].value= 255


container[275].bin= 63
container[275].i= 262
container[275].j= 587
container[275].angle= 315
container[275].value= 255


container[276].bin= 36
container[276].i= 262
container[276].j= 592
container[276].angle= 180
container[276].value= 255


container[277].bin= 63
container[277].i= 262
container[277].j= 609
container[277].angle= 315
container[277].value= 255


container[278].bin= 0
container[278].i= 262
container[278].j= 613
container[278].angle= 0
container[278].value= 255


container[279].bin= 27
container[279].i= 262
container[279].j= 623
container[279].angle= 135
container[279].value= 255


container[280].bin= 0
container[280].i= 263
container[280].j= 587
container[280].angle= 0
container[280].value= 255


container[281].bin= 36
container[281].i= 263
container[281].j= 592
container[281].angle= 180
container[281].value= 255


container[282].bin= 0
container[282].i= 263
container[282].j= 609
container[282].angle= 0
container[282].value= 255


container[283].bin= 18
container[283].i= 263
container[283].j= 612
container[283].angle= 90
container[283].value= 255


container[284].bin= 8
container[284].i= 263
container[284].j= 613
container[284].angle= 44
container[284].value= 255


container[285].bin= 36
container[285].i= 263
container[285].j= 623
container[285].angle= 180
container[285].value= 255


container[286].bin= 63
container[286].i= 264
container[286].j= 588
container[286].angle= 315
container[286].value= 255


container[287].bin= 27
container[287].i= 264
container[287].j= 593
container[287].angle= 135
container[287].value= 255


container[288].bin= 63
container[288].i= 264
container[288].j= 610
container[288].angle= 315
container[288].value= 255


container[289].bin= 30
container[289].i= 264
container[289].j= 624
container[289].angle= 153
container[289].value= 255


container[290].bin= 63
container[290].i= 265
container[290].j= 589
container[290].angle= 315
container[290].value= 255


container[291].bin= 27
container[291].i= 265
container[291].j= 594
container[291].angle= 135
container[291].value= 255


container[292].bin= 63
container[292].i= 265
container[292].j= 611
container[292].angle= 315
container[292].value= 255


container[293].bin= 30
container[293].i= 265
container[293].j= 624
container[293].angle= 153
container[293].value= 255


container[294].bin= 0
container[294].i= 266
container[294].j= 589
container[294].angle= 0
container[294].value= 255


container[295].bin= 36
container[295].i= 266
container[295].j= 594
container[295].angle= 180
container[295].value= 255


container[296].bin= 66
container[296].i= 266
container[296].j= 612
container[296].angle= 333
container[296].value= 255


container[297].bin= 41
container[297].i= 266
container[297].j= 624
container[297].angle= 206
container[297].value= 255


container[298].bin= 66
container[298].i= 267
container[298].j= 590
container[298].angle= 333
container[298].value= 255


container[299].bin= 27
container[299].i= 267
container[299].j= 595
container[299].angle= 135
container[299].value= 255


container[300].bin= 63
container[300].i= 267
container[300].j= 612
container[300].angle= 315
container[300].value= 255


container[301].bin= 63
container[301].i= 267
container[301].j= 613
container[301].angle= 315
container[301].value= 255


container[302].bin= 41
container[302].i= 267
container[302].j= 624
container[302].angle= 206
container[302].value= 255


container[303].bin= 63
container[303].i= 268
container[303].j= 590
container[303].angle= 315
container[303].value= 255


container[304].bin= 59
container[304].i= 268
container[304].j= 591
container[304].angle= 296
container[304].value= 255


container[305].bin= 27
container[305].i= 268
container[305].j= 596
container[305].angle= 135
container[305].value= 255


container[306].bin= 66
container[306].i= 268
container[306].j= 613
container[306].angle= 333
container[306].value= 255


container[307].bin= 36
container[307].i= 268
container[307].j= 623
container[307].angle= 180
container[307].value= 255


container[308].bin= 63
container[308].i= 269
container[308].j= 592
container[308].angle= 315
container[308].value= 255


container[309].bin= 36
container[309].i= 269
container[309].j= 596
container[309].angle= 180
container[309].value= 255


container[310].bin= 0
container[310].i= 269
container[310].j= 613
container[310].angle= 0
container[310].value= 255


container[311].bin= 36
container[311].i= 269
container[311].j= 623
container[311].angle= 180
container[311].value= 255


container[312].bin= 0
container[312].i= 270
container[312].j= 592
container[312].angle= 0
container[312].value= 255


container[313].bin= 36
container[313].i= 270
container[313].j= 596
container[313].angle= 180
container[313].value= 255


container[314].bin= 66
container[314].i= 270
container[314].j= 614
container[314].angle= 333
container[314].value= 255


container[315].bin= 54
container[315].i= 270
container[315].j= 618
container[315].angle= 270
container[315].value= 255


container[316].bin= 44
container[316].i= 270
container[316].j= 621
container[316].angle= 224
container[316].value= 255


container[317].bin= 54
container[317].i= 270
container[317].j= 622
container[317].angle= 270
container[317].value= 255


container[318].bin= 39
container[318].i= 270
container[318].j= 623
container[318].angle= 198
container[318].value= 255


container[319].bin= 0
container[319].i= 271
container[319].j= 592
container[319].angle= 0
container[319].value= 255


container[320].bin= 36
container[320].i= 271
container[320].j= 596
container[320].angle= 180
container[320].value= 255


container[321].bin= 66
container[321].i= 271
container[321].j= 614
container[321].angle= 333
container[321].value= 255


container[322].bin= 44
container[322].i= 271
container[322].j= 617
container[322].angle= 224
container[322].value= 255


container[323].bin= 63
container[323].i= 271
container[323].j= 619
container[323].angle= 315
container[323].value= 255


container[324].bin= 36
container[324].i= 271
container[324].j= 624
container[324].angle= 180
container[324].value= 255


container[325].bin= 0
container[325].i= 272
container[325].j= 592
container[325].angle= 0
container[325].value= 255


container[326].bin= 36
container[326].i= 272
container[326].j= 596
container[326].angle= 180
container[326].value= 255


container[327].bin= 0
container[327].i= 272
container[327].j= 614
container[327].angle= 0
container[327].value= 255


container[328].bin= 0
container[328].i= 272
container[328].j= 619
container[328].angle= 0
container[328].value= 255


container[329].bin= 39
container[329].i= 272
container[329].j= 623
container[329].angle= 198
container[329].value= 255


container[330].bin= 66
container[330].i= 273
container[330].j= 593
container[330].angle= 333
container[330].value= 255


container[331].bin= 27
container[331].i= 273
container[331].j= 597
container[331].angle= 135
container[331].value= 255


container[332].bin= 18
container[332].i= 273
container[332].j= 598
container[332].angle= 90
container[332].value= 255


container[333].bin= 18
container[333].i= 273
container[333].j= 599
container[333].angle= 90
container[333].value= 255


container[334].bin= 0
container[334].i= 273
container[334].j= 614
container[334].angle= 0
container[334].value= 255


container[335].bin= 63
container[335].i= 273
container[335].j= 620
container[335].angle= 315
container[335].value= 255


container[336].bin= 54
container[336].i= 273
container[336].j= 621
container[336].angle= 270
container[336].value= 255


container[337].bin= 48
container[337].i= 273
container[337].j= 622
container[337].angle= 243
container[337].value= 255


container[338].bin= 44
container[338].i= 273
container[338].j= 623
container[338].angle= 224
container[338].value= 255


container[339].bin= 66
container[339].i= 274
container[339].j= 593
container[339].angle= 333
container[339].value= 255


container[340].bin= 27
container[340].i= 274
container[340].j= 600
container[340].angle= 135
container[340].value= 255


container[341].bin= 0
container[341].i= 274
container[341].j= 614
container[341].angle= 0
container[341].value= 255


container[342].bin= 0
container[342].i= 275
container[342].j= 593
container[342].angle= 0
container[342].value= 255


container[343].bin= 30
container[343].i= 275
container[343].j= 601
container[343].angle= 153
container[343].value= 255


container[344].bin= 0
container[344].i= 275
container[344].j= 614
container[344].angle= 0
container[344].value= 255


container[345].bin= 63
container[345].i= 276
container[345].j= 594
container[345].angle= 315
container[345].value= 255


container[346].bin= 36
container[346].i= 276
container[346].j= 601
container[346].angle= 180
container[346].value= 255


container[347].bin= 0
container[347].i= 276
container[347].j= 614
container[347].angle= 0
container[347].value= 255


container[348].bin= 63
container[348].i= 277
container[348].j= 595
container[348].angle= 315
container[348].value= 255


container[349].bin= 41
container[349].i= 277
container[349].j= 601
container[349].angle= 206
container[349].value= 255


container[350].bin= 0
container[350].i= 277
container[350].j= 614
container[350].angle= 0
container[350].value= 255


container[351].bin= 0
container[351].i= 278
container[351].j= 595
container[351].angle= 0
container[351].value= 255


container[352].bin= 36
container[352].i= 278
container[352].j= 600
container[352].angle= 180
container[352].value= 255


container[353].bin= 0
container[353].i= 278
container[353].j= 614
container[353].angle= 0
container[353].value= 255


container[354].bin= 63
container[354].i= 279
container[354].j= 596
container[354].angle= 315
container[354].value= 255


container[355].bin= 36
container[355].i= 279
container[355].j= 600
container[355].angle= 180
container[355].value= 255


container[356].bin= 0
container[356].i= 279
container[356].j= 614
container[356].angle= 0
container[356].value= 255


container[357].bin= 41
container[357].i= 279
container[357].j= 616
container[357].angle= 206
container[357].value= 255


container[358].bin= 63
container[358].i= 280
container[358].j= 597
container[358].angle= 315
container[358].value= 255


container[359].bin= 36
container[359].i= 280
container[359].j= 600
container[359].angle= 180
container[359].value= 255


container[360].bin= 0
container[360].i= 280
container[360].j= 614
container[360].angle= 0
container[360].value= 255


container[361].bin= 41
container[361].i= 280
container[361].j= 616
container[361].angle= 206
container[361].value= 255


container[362].bin= 0
container[362].i= 281
container[362].j= 597
container[362].angle= 0
container[362].value= 255


container[363].bin= 36
container[363].i= 281
container[363].j= 600
container[363].angle= 180
container[363].value= 255


container[364].bin= 0
container[364].i= 281
container[364].j= 614
container[364].angle= 0
container[364].value= 255


container[365].bin= 36
container[365].i= 281
container[365].j= 616
container[365].angle= 180
container[365].value= 255


container[366].bin= 0
container[366].i= 282
container[366].j= 597
container[366].angle= 0
container[366].value= 255


container[367].bin= 41
container[367].i= 282
container[367].j= 600
container[367].angle= 206
container[367].value= 255


container[368].bin= 0
container[368].i= 282
container[368].j= 614
container[368].angle= 0
container[368].value= 255


container[369].bin= 36
container[369].i= 282
container[369].j= 616
container[369].angle= 180
container[369].value= 255


container[370].bin= 0
container[370].i= 283
container[370].j= 597
container[370].angle= 0
container[370].value= 255


container[371].bin= 41
container[371].i= 283
container[371].j= 600
container[371].angle= 206
container[371].value= 255


container[372].bin= 0
container[372].i= 283
container[372].j= 614
container[372].angle= 0
container[372].value= 255


container[373].bin= 36
container[373].i= 283
container[373].j= 616
container[373].angle= 180
container[373].value= 255


container[374].bin= 0
container[374].i= 284
container[374].j= 597
container[374].angle= 0
container[374].value= 255


container[375].bin= 0
container[375].i= 284
container[375].j= 614
container[375].angle= 0
container[375].value= 255


container[376].bin= 36
container[376].i= 284
container[376].j= 616
container[376].angle= 180
container[376].value= 255


container[377].bin= 63
container[377].i= 285
container[377].j= 598
container[377].angle= 315
container[377].value= 255


container[378].bin= 44
container[378].i= 285
container[378].j= 599
container[378].angle= 224
container[378].value= 255


container[379].bin= 68
container[379].i= 285
container[379].j= 614
container[379].angle= 341
container[379].value= 255


container[380].bin= 54
container[380].i= 285
container[380].j= 615
container[380].angle= 270
container[380].value= 255


container[381].bin= 39
container[381].i= 285
container[381].j= 616
container[381].angle= 198
container[381].value= 255


