container[0].bin= 18
container[0].i= 757
container[0].j= 249
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 758
container[1].j= 248
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 758
container[2].j= 250
container[2].angle= 161
container[2].value= 255


container[3].bin= 18
container[3].i= 759
container[3].j= 246
container[3].angle= 90
container[3].value= 255


container[4].bin= 0
container[4].i= 759
container[4].j= 248
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 759
container[5].j= 250
container[5].angle= 180
container[5].value= 255


container[6].bin= 3
container[6].i= 760
container[6].j= 245
container[6].angle= 18
container[6].value= 255


container[7].bin= 32
container[7].i= 760
container[7].j= 247
container[7].angle= 161
container[7].value= 255


container[8].bin= 36
container[8].i= 760
container[8].j= 250
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 761
container[9].j= 245
container[9].angle= 0
container[9].value= 255


container[10].bin= 27
container[10].i= 761
container[10].j= 247
container[10].angle= 135
container[10].value= 255


container[11].bin= 8
container[11].i= 761
container[11].j= 248
container[11].angle= 44
container[11].value= 255


container[12].bin= 36
container[12].i= 761
container[12].j= 250
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 762
container[13].j= 245
container[13].angle= 0
container[13].value= 255


container[14].bin= 0
container[14].i= 763
container[14].j= 245
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 763
container[15].j= 249
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 764
container[16].j= 245
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 764
container[17].j= 249
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 765
container[18].j= 245
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 765
container[19].j= 249
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 766
container[20].j= 245
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 766
container[21].j= 249
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 767
container[22].j= 246
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 767
container[23].j= 249
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 768
container[24].j= 247
container[24].angle= 315
container[24].value= 255


container[25].bin= 0
container[25].i= 769
container[25].j= 247
container[25].angle= 0
container[25].value= 255


container[26].bin= 66
container[26].i= 770
container[26].j= 248
container[26].angle= 333
container[26].value= 255


container[27].bin= 66
container[27].i= 771
container[27].j= 248
container[27].angle= 333
container[27].value= 255


container[28].bin= 36
container[28].i= 771
container[28].j= 250
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 772
container[29].j= 248
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 772
container[30].j= 250
container[30].angle= 180
container[30].value= 255


container[31].bin= 68
container[31].i= 773
container[31].j= 248
container[31].angle= 341
container[31].value= 255


container[32].bin= 54
container[32].i= 773
container[32].j= 249
container[32].angle= 270
container[32].value= 255


container[33].bin= 39
container[33].i= 773
container[33].j= 250
container[33].angle= 198
container[33].value= 255


