container[0].bin= 18
container[0].i= 309
container[0].j= 507
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 309
container[1].j= 508
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 309
container[2].j= 509
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 309
container[3].j= 510
container[3].angle= 90
container[3].value= 255


container[4].bin= 21
container[4].i= 309
container[4].j= 511
container[4].angle= 108
container[4].value= 255


container[5].bin= 8
container[5].i= 310
container[5].j= 506
container[5].angle= 44
container[5].value= 255


container[6].bin= 0
container[6].i= 311
container[6].j= 505
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 311
container[7].j= 511
container[7].angle= 180
container[7].value= 255


container[8].bin= 66
container[8].i= 312
container[8].j= 506
container[8].angle= 333
container[8].value= 255


container[9].bin= 27
container[9].i= 312
container[9].j= 511
container[9].angle= 135
container[9].value= 255


container[10].bin= 27
container[10].i= 312
container[10].j= 512
container[10].angle= 135
container[10].value= 255


container[11].bin= 63
container[11].i= 313
container[11].j= 506
container[11].angle= 315
container[11].value= 255


container[12].bin= 63
container[12].i= 313
container[12].j= 507
container[12].angle= 315
container[12].value= 255


container[13].bin= 30
container[13].i= 313
container[13].j= 512
container[13].angle= 153
container[13].value= 255


container[14].bin= 66
container[14].i= 314
container[14].j= 507
container[14].angle= 333
container[14].value= 255


container[15].bin= 36
container[15].i= 314
container[15].j= 512
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 315
container[16].j= 507
container[16].angle= 0
container[16].value= 255


container[17].bin= 32
container[17].i= 315
container[17].j= 512
container[17].angle= 161
container[17].value= 255


container[18].bin= 21
container[18].i= 315
container[18].j= 514
container[18].angle= 108
container[18].value= 255


container[19].bin= 0
container[19].i= 316
container[19].j= 507
container[19].angle= 0
container[19].value= 255


container[20].bin= 32
container[20].i= 316
container[20].j= 514
container[20].angle= 161
container[20].value= 255


container[21].bin= 0
container[21].i= 317
container[21].j= 507
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 317
container[22].j= 514
container[22].angle= 180
container[22].value= 255


container[23].bin= 8
container[23].i= 318
container[23].j= 507
container[23].angle= 44
container[23].value= 255


container[24].bin= 44
container[24].i= 318
container[24].j= 514
container[24].angle= 224
container[24].value= 255


container[25].bin= 8
container[25].i= 319
container[25].j= 506
container[25].angle= 44
container[25].value= 255


container[26].bin= 44
container[26].i= 319
container[26].j= 513
container[26].angle= 224
container[26].value= 255


container[27].bin= 0
container[27].i= 320
container[27].j= 505
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 320
container[28].j= 512
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 321
container[29].j= 505
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 321
container[30].j= 513
container[30].angle= 153
container[30].value= 255


container[31].bin= 0
container[31].i= 322
container[31].j= 505
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 322
container[32].j= 513
container[32].angle= 180
container[32].value= 255


container[33].bin= 0
container[33].i= 323
container[33].j= 505
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 323
container[34].j= 513
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 324
container[35].j= 505
container[35].angle= 0
container[35].value= 255


container[36].bin= 54
container[36].i= 324
container[36].j= 509
container[36].angle= 270
container[36].value= 255


container[37].bin= 54
container[37].i= 324
container[37].j= 510
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 324
container[38].j= 511
container[38].angle= 270
container[38].value= 255


container[39].bin= 50
container[39].i= 324
container[39].j= 512
container[39].angle= 251
container[39].value= 255


container[40].bin= 0
container[40].i= 325
container[40].j= 505
container[40].angle= 0
container[40].value= 255


container[41].bin= 44
container[41].i= 325
container[41].j= 508
container[41].angle= 224
container[41].value= 255


container[42].bin= 0
container[42].i= 326
container[42].j= 505
container[42].angle= 0
container[42].value= 255


container[43].bin= 63
container[43].i= 327
container[43].j= 506
container[43].angle= 315
container[43].value= 255


container[44].bin= 44
container[44].i= 327
container[44].j= 507
container[44].angle= 224
container[44].value= 255


