container[0].bin= 18
container[0].i= 43
container[0].j= 203
container[0].angle= 90
container[0].value= 255


container[1].bin= 12
container[1].i= 44
container[1].j= 201
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 44
container[2].j= 202
container[2].angle= 63
container[2].value= 255


container[3].bin= 23
container[3].i= 44
container[3].j= 204
container[3].angle= 116
container[3].value= 255


container[4].bin= 27
container[4].i= 44
container[4].j= 205
container[4].angle= 135
container[4].value= 255


container[5].bin= 8
container[5].i= 45
container[5].j= 200
container[5].angle= 44
container[5].value= 255


container[6].bin= 30
container[6].i= 45
container[6].j= 205
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 46
container[7].j= 200
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 46
container[8].j= 205
container[8].angle= 180
container[8].value= 255


container[9].bin= 63
container[9].i= 47
container[9].j= 200
container[9].angle= 315
container[9].value= 255


container[10].bin= 63
container[10].i= 47
container[10].j= 201
container[10].angle= 315
container[10].value= 255


container[11].bin= 36
container[11].i= 47
container[11].j= 205
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 48
container[12].j= 201
container[12].angle= 315
container[12].value= 255


container[13].bin= 63
container[13].i= 48
container[13].j= 202
container[13].angle= 315
container[13].value= 255


container[14].bin= 36
container[14].i= 48
container[14].j= 205
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 49
container[15].j= 202
container[15].angle= 315
container[15].value= 255


container[16].bin= 59
container[16].i= 49
container[16].j= 203
container[16].angle= 296
container[16].value= 255


container[17].bin= 54
container[17].i= 49
container[17].j= 204
container[17].angle= 270
container[17].value= 255


container[18].bin= 44
container[18].i= 49
container[18].j= 205
container[18].angle= 224
container[18].value= 255


