container[0].bin= 8
container[0].i= 100
container[0].j= 274
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 100
container[1].j= 275
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 100
container[2].j= 276
container[2].angle= 135
container[2].value= 255


container[3].bin= 8
container[3].i= 101
container[3].j= 273
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 101
container[4].j= 274
container[4].angle= 44
container[4].value= 255


container[5].bin= 36
container[5].i= 101
container[5].j= 276
container[5].angle= 180
container[5].value= 255


container[6].bin= 8
container[6].i= 102
container[6].j= 272
container[6].angle= 44
container[6].value= 255


container[7].bin= 44
container[7].i= 102
container[7].j= 276
container[7].angle= 224
container[7].value= 255


container[8].bin= 3
container[8].i= 103
container[8].j= 271
container[8].angle= 18
container[8].value= 255


container[9].bin= 48
container[9].i= 103
container[9].j= 275
container[9].angle= 243
container[9].value= 255


container[10].bin= 68
container[10].i= 104
container[10].j= 271
container[10].angle= 341
container[10].value= 255


container[11].bin= 48
container[11].i= 104
container[11].j= 273
container[11].angle= 243
container[11].value= 255


