container[0].bin= 8
container[0].i= 466
container[0].j= 572
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 466
container[1].j= 573
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 467
container[2].j= 571
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 468
container[3].j= 571
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 469
container[4].j= 571
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 470
container[5].j= 571
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 471
container[6].j= 572
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 471
container[7].j= 573
container[7].angle= 224
container[7].value= 255


