container[0].bin= 8
container[0].i= 544
container[0].j= 354
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 544
container[1].j= 355
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 545
container[2].j= 353
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 546
container[3].j= 353
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 547
container[4].j= 353
container[4].angle= 0
container[4].value= 255


container[5].bin= 63
container[5].i= 548
container[5].j= 354
container[5].angle= 315
container[5].value= 255


container[6].bin= 44
container[6].i= 548
container[6].j= 355
container[6].angle= 224
container[6].value= 255


