container[0].bin= 18
container[0].i= 309
container[0].j= 619
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 310
container[1].j= 618
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 310
container[2].j= 620
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 311
container[3].j= 617
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 311
container[4].j= 620
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 312
container[5].j= 617
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 312
container[6].j= 621
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 312
container[7].j= 622
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 313
container[8].j= 617
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 313
container[9].j= 623
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 314
container[10].j= 617
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 314
container[11].j= 623
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 315
container[12].j= 618
container[12].angle= 315
container[12].value= 255


container[13].bin= 44
container[13].i= 315
container[13].j= 623
container[13].angle= 224
container[13].value= 255


container[14].bin= 63
container[14].i= 316
container[14].j= 619
container[14].angle= 315
container[14].value= 255


container[15].bin= 44
container[15].i= 316
container[15].j= 622
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 317
container[16].j= 619
container[16].angle= 0
container[16].value= 255


container[17].bin= 0
container[17].i= 318
container[17].j= 619
container[17].angle= 0
container[17].value= 255


container[18].bin= 0
container[18].i= 319
container[18].j= 619
container[18].angle= 0
container[18].value= 255


container[19].bin= 0
container[19].i= 320
container[19].j= 619
container[19].angle= 0
container[19].value= 255


container[20].bin= 0
container[20].i= 321
container[20].j= 619
container[20].angle= 0
container[20].value= 255


container[21].bin= 27
container[21].i= 321
container[21].j= 622
container[21].angle= 135
container[21].value= 255


container[22].bin= 18
container[22].i= 321
container[22].j= 623
container[22].angle= 90
container[22].value= 255


container[23].bin= 0
container[23].i= 322
container[23].j= 619
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 322
container[24].j= 624
container[24].angle= 135
container[24].value= 255


container[25].bin= 66
container[25].i= 323
container[25].j= 620
container[25].angle= 333
container[25].value= 255


container[26].bin= 36
container[26].i= 323
container[26].j= 624
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 324
container[27].j= 620
container[27].angle= 315
container[27].value= 255


container[28].bin= 59
container[28].i= 324
container[28].j= 621
container[28].angle= 296
container[28].value= 255


container[29].bin= 36
container[29].i= 324
container[29].j= 624
container[29].angle= 180
container[29].value= 255


container[30].bin= 63
container[30].i= 325
container[30].j= 622
container[30].angle= 315
container[30].value= 255


container[31].bin= 0
container[31].i= 326
container[31].j= 622
container[31].angle= 0
container[31].value= 255


container[32].bin= 63
container[32].i= 327
container[32].j= 623
container[32].angle= 315
container[32].value= 255


container[33].bin= 44
container[33].i= 327
container[33].j= 624
container[33].angle= 224
container[33].value= 255


