container[0].bin= 18
container[0].i= 369
container[0].j= 218
container[0].angle= 90
container[0].value= 255


container[1].bin= 14
container[1].i= 369
container[1].j= 221
container[1].angle= 71
container[1].value= 255


container[2].bin= 21
container[2].i= 369
container[2].j= 222
container[2].angle= 108
container[2].value= 255


container[3].bin= 8
container[3].i= 370
container[3].j= 217
container[3].angle= 44
container[3].value= 255


container[4].bin= 23
container[4].i= 370
container[4].j= 219
container[4].angle= 116
container[4].value= 255


container[5].bin= 21
container[5].i= 370
container[5].j= 220
container[5].angle= 108
container[5].value= 255


container[6].bin= 8
container[6].i= 370
container[6].j= 221
container[6].angle= 44
container[6].value= 255


container[7].bin= 27
container[7].i= 370
container[7].j= 222
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 371
container[8].j= 216
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 371
container[9].j= 223
container[9].angle= 180
container[9].value= 255


container[10].bin= 0
container[10].i= 372
container[10].j= 216
container[10].angle= 0
container[10].value= 255


container[11].bin= 30
container[11].i= 372
container[11].j= 223
container[11].angle= 153
container[11].value= 255


container[12].bin= 0
container[12].i= 373
container[12].j= 216
container[12].angle= 0
container[12].value= 255


container[13].bin= 18
container[13].i= 373
container[13].j= 219
container[13].angle= 90
container[13].value= 255


container[14].bin= 30
container[14].i= 373
container[14].j= 223
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 374
container[15].j= 216
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 374
container[16].j= 223
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 375
container[17].j= 217
container[17].angle= 315
container[17].value= 255


container[18].bin= 41
container[18].i= 375
container[18].j= 223
container[18].angle= 206
container[18].value= 255


container[19].bin= 63
container[19].i= 376
container[19].j= 218
container[19].angle= 315
container[19].value= 255


container[20].bin= 41
container[20].i= 376
container[20].j= 223
container[20].angle= 206
container[20].value= 255


container[21].bin= 0
container[21].i= 377
container[21].j= 218
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 377
container[22].j= 222
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 378
container[23].j= 219
container[23].angle= 315
container[23].value= 255


container[24].bin= 54
container[24].i= 378
container[24].j= 220
container[24].angle= 270
container[24].value= 255


container[25].bin= 54
container[25].i= 378
container[25].j= 221
container[25].angle= 270
container[25].value= 255


container[26].bin= 44
container[26].i= 378
container[26].j= 222
container[26].angle= 224
container[26].value= 255


