container[0].bin= 18
container[0].i= 153
container[0].j= 321
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 154
container[1].j= 320
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 154
container[2].j= 322
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 155
container[3].j= 320
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 155
container[4].j= 322
container[4].angle= 180
container[4].value= 255


container[5].bin= 68
container[5].i= 156
container[5].j= 320
container[5].angle= 341
container[5].value= 255


