container[0].bin= 14
container[0].i= 525
container[0].j= 534
container[0].angle= 71
container[0].value= 255


container[1].bin= 18
container[1].i= 525
container[1].j= 535
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 526
container[2].j= 533
container[2].angle= 44
container[2].value= 255


container[3].bin= 8
container[3].i= 526
container[3].j= 534
container[3].angle= 44
container[3].value= 255


container[4].bin= 27
container[4].i= 526
container[4].j= 536
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 527
container[5].j= 532
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 527
container[6].j= 536
container[6].angle= 180
container[6].value= 255


container[7].bin= 8
container[7].i= 528
container[7].j= 533
container[7].angle= 44
container[7].value= 255


container[8].bin= 8
container[8].i= 528
container[8].j= 534
container[8].angle= 44
container[8].value= 255


container[9].bin= 36
container[9].i= 528
container[9].j= 536
container[9].angle= 180
container[9].value= 255


container[10].bin= 18
container[10].i= 528
container[10].j= 541
container[10].angle= 90
container[10].value= 255


container[11].bin= 8
container[11].i= 529
container[11].j= 532
container[11].angle= 44
container[11].value= 255


container[12].bin= 36
container[12].i= 529
container[12].j= 536
container[12].angle= 180
container[12].value= 255


container[13].bin= 3
container[13].i= 529
container[13].j= 540
container[13].angle= 18
container[13].value= 255


container[14].bin= 32
container[14].i= 529
container[14].j= 542
container[14].angle= 161
container[14].value= 255


container[15].bin= 0
container[15].i= 530
container[15].j= 531
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 530
container[16].j= 536
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 530
container[17].j= 540
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 530
container[18].j= 542
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 531
container[19].j= 532
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 531
container[20].j= 533
container[20].angle= 270
container[20].value= 255


container[21].bin= 36
container[21].i= 531
container[21].j= 536
container[21].angle= 180
container[21].value= 255


container[22].bin= 5
container[22].i= 531
container[22].j= 540
container[22].angle= 26
container[22].value= 255


container[23].bin= 36
container[23].i= 531
container[23].j= 542
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 532
container[24].j= 534
container[24].angle= 315
container[24].value= 255


container[25].bin= 5
container[25].i= 532
container[25].j= 540
container[25].angle= 26
container[25].value= 255


container[26].bin= 0
container[26].i= 533
container[26].j= 534
container[26].angle= 0
container[26].value= 255


container[27].bin= 0
container[27].i= 533
container[27].j= 539
container[27].angle= 0
container[27].value= 255


container[28].bin= 0
container[28].i= 534
container[28].j= 534
container[28].angle= 0
container[28].value= 255


container[29].bin= 27
container[29].i= 534
container[29].j= 537
container[29].angle= 135
container[29].value= 255


container[30].bin= 18
container[30].i= 534
container[30].j= 538
container[30].angle= 90
container[30].value= 255


container[31].bin= 44
container[31].i= 534
container[31].j= 541
container[31].angle= 224
container[31].value= 255


container[32].bin= 0
container[32].i= 535
container[32].j= 534
container[32].angle= 0
container[32].value= 255


container[33].bin= 0
container[33].i= 536
container[33].j= 534
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 536
container[34].j= 539
container[34].angle= 180
container[34].value= 255


container[35].bin= 63
container[35].i= 537
container[35].j= 535
container[35].angle= 315
container[35].value= 255


container[36].bin= 54
container[36].i= 537
container[36].j= 536
container[36].angle= 270
container[36].value= 255


container[37].bin= 54
container[37].i= 537
container[37].j= 537
container[37].angle= 270
container[37].value= 255


container[38].bin= 54
container[38].i= 537
container[38].j= 538
container[38].angle= 270
container[38].value= 255


container[39].bin= 44
container[39].i= 537
container[39].j= 539
container[39].angle= 224
container[39].value= 255


