container[0].bin= 18
container[0].i= 80
container[0].j= 268
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 81
container[1].j= 267
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 81
container[2].j= 269
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 82
container[3].j= 267
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 82
container[4].j= 269
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 83
container[5].j= 267
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 83
container[6].j= 269
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 84
container[7].j= 267
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 84
container[8].j= 269
container[8].angle= 135
container[8].value= 255


container[9].bin= 18
container[9].i= 84
container[9].j= 270
container[9].angle= 90
container[9].value= 255


container[10].bin= 0
container[10].i= 85
container[10].j= 267
container[10].angle= 0
container[10].value= 255


container[11].bin= 27
container[11].i= 85
container[11].j= 271
container[11].angle= 135
container[11].value= 255


container[12].bin= 0
container[12].i= 86
container[12].j= 267
container[12].angle= 0
container[12].value= 255


container[13].bin= 36
container[13].i= 86
container[13].j= 271
container[13].angle= 180
container[13].value= 255


container[14].bin= 0
container[14].i= 87
container[14].j= 267
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 87
container[15].j= 271
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 88
container[16].j= 267
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 88
container[17].j= 271
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 89
container[18].j= 267
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 89
container[19].j= 271
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 90
container[20].j= 267
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 90
container[21].j= 271
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 91
container[22].j= 267
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 91
container[23].j= 271
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 92
container[24].j= 267
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 92
container[25].j= 271
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 93
container[26].j= 268
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 93
container[27].j= 271
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 94
container[28].j= 269
container[28].angle= 315
container[28].value= 255


container[29].bin= 0
container[29].i= 95
container[29].j= 269
container[29].angle= 0
container[29].value= 255


container[30].bin= 63
container[30].i= 96
container[30].j= 270
container[30].angle= 315
container[30].value= 255


container[31].bin= 44
container[31].i= 96
container[31].j= 271
container[31].angle= 224
container[31].value= 255


