container[0].bin= 8
container[0].i= 792
container[0].j= 439
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 792
container[1].j= 440
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 792
container[2].j= 441
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 793
container[3].j= 439
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 793
container[4].j= 441
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 794
container[5].j= 438
container[5].angle= 0
container[5].value= 255


container[6].bin= 41
container[6].i= 794
container[6].j= 441
container[6].angle= 206
container[6].value= 255


container[7].bin= 0
container[7].i= 795
container[7].j= 438
container[7].angle= 0
container[7].value= 255


container[8].bin= 41
container[8].i= 795
container[8].j= 441
container[8].angle= 206
container[8].value= 255


container[9].bin= 0
container[9].i= 796
container[9].j= 438
container[9].angle= 0
container[9].value= 255


container[10].bin= 66
container[10].i= 797
container[10].j= 439
container[10].angle= 333
container[10].value= 255


container[11].bin= 63
container[11].i= 798
container[11].j= 439
container[11].angle= 315
container[11].value= 255


