container[0].bin= 3
container[0].i= 71
container[0].j= 206
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 71
container[1].j= 207
container[1].angle= 71
container[1].value= 255


container[2].bin= 23
container[2].i= 71
container[2].j= 208
container[2].angle= 116
container[2].value= 255


container[3].bin= 0
container[3].i= 72
container[3].j= 206
container[3].angle= 0
container[3].value= 255


container[4].bin= 27
container[4].i= 72
container[4].j= 209
container[4].angle= 135
container[4].value= 255


container[5].bin= 0
container[5].i= 73
container[5].j= 206
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 73
container[6].j= 210
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 74
container[7].j= 206
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 74
container[8].j= 210
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 75
container[9].j= 207
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 75
container[10].j= 211
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 76
container[11].j= 207
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 76
container[12].j= 211
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 77
container[13].j= 208
container[13].angle= 333
container[13].value= 255


container[14].bin= 36
container[14].i= 77
container[14].j= 211
container[14].angle= 180
container[14].value= 255


container[15].bin= 66
container[15].i= 78
container[15].j= 208
container[15].angle= 333
container[15].value= 255


container[16].bin= 36
container[16].i= 78
container[16].j= 211
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 79
container[17].j= 209
container[17].angle= 315
container[17].value= 255


container[18].bin= 59
container[18].i= 80
container[18].j= 210
container[18].angle= 296
container[18].value= 255


