container[0].bin= 8
container[0].i= 825
container[0].j= 402
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 825
container[1].j= 403
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 826
container[2].j= 401
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 827
container[3].j= 401
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 828
container[4].j= 401
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 829
container[5].j= 401
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 830
container[6].j= 401
container[6].angle= 0
container[6].value= 255


container[7].bin= 0
container[7].i= 831
container[7].j= 401
container[7].angle= 0
container[7].value= 255


container[8].bin= 0
container[8].i= 832
container[8].j= 401
container[8].angle= 0
container[8].value= 255


container[9].bin= 63
container[9].i= 833
container[9].j= 402
container[9].angle= 315
container[9].value= 255


container[10].bin= 44
container[10].i= 833
container[10].j= 403
container[10].angle= 224
container[10].value= 255


