container[0].bin= 18
container[0].i= 880
container[0].j= 254
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 881
container[1].j= 253
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 881
container[2].j= 255
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 882
container[3].j= 253
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 882
container[4].j= 255
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 883
container[5].j= 253
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 883
container[6].j= 255
container[6].angle= 180
container[6].value= 255


container[7].bin= 0
container[7].i= 884
container[7].j= 253
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 884
container[8].j= 255
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 885
container[9].j= 253
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 885
container[10].j= 255
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 886
container[11].j= 253
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 886
container[12].j= 255
container[12].angle= 180
container[12].value= 255


container[13].bin= 0
container[13].i= 887
container[13].j= 253
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 887
container[14].j= 255
container[14].angle= 180
container[14].value= 255


container[15].bin= 0
container[15].i= 888
container[15].j= 253
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 888
container[16].j= 255
container[16].angle= 180
container[16].value= 255


container[17].bin= 0
container[17].i= 889
container[17].j= 253
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 889
container[18].j= 255
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 890
container[19].j= 253
container[19].angle= 0
container[19].value= 255


container[20].bin= 36
container[20].i= 890
container[20].j= 255
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 891
container[21].j= 253
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 891
container[22].j= 255
container[22].angle= 180
container[22].value= 255


container[23].bin= 68
container[23].i= 892
container[23].j= 253
container[23].angle= 341
container[23].value= 255


container[24].bin= 54
container[24].i= 892
container[24].j= 254
container[24].angle= 270
container[24].value= 255


container[25].bin= 39
container[25].i= 892
container[25].j= 255
container[25].angle= 198
container[25].value= 255


