container[0].bin= 18
container[0].i= 360
container[0].j= 244
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 360
container[1].j= 245
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 361
container[2].j= 243
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 361
container[3].j= 246
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 362
container[4].j= 242
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 362
container[5].j= 246
container[5].angle= 180
container[5].value= 255


container[6].bin= 66
container[6].i= 363
container[6].j= 243
container[6].angle= 333
container[6].value= 255


container[7].bin= 30
container[7].i= 363
container[7].j= 247
container[7].angle= 153
container[7].value= 255


container[8].bin= 66
container[8].i= 364
container[8].j= 243
container[8].angle= 333
container[8].value= 255


container[9].bin= 30
container[9].i= 364
container[9].j= 247
container[9].angle= 153
container[9].value= 255


container[10].bin= 0
container[10].i= 365
container[10].j= 243
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 365
container[11].j= 247
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 366
container[12].j= 244
container[12].angle= 315
container[12].value= 255


container[13].bin= 36
container[13].i= 366
container[13].j= 247
container[13].angle= 180
container[13].value= 255


container[14].bin= 63
container[14].i= 367
container[14].j= 245
container[14].angle= 315
container[14].value= 255


container[15].bin= 41
container[15].i= 367
container[15].j= 247
container[15].angle= 206
container[15].value= 255


container[16].bin= 0
container[16].i= 368
container[16].j= 245
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 368
container[17].j= 247
container[17].angle= 180
container[17].value= 255


container[18].bin= 68
container[18].i= 369
container[18].j= 245
container[18].angle= 341
container[18].value= 255


