container[0].bin= 3
container[0].i= 218
container[0].j= 214
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 218
container[1].j= 215
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 218
container[2].j= 216
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 219
container[3].j= 214
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 219
container[4].j= 216
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 220
container[5].j= 214
container[5].angle= 0
container[5].value= 255


container[6].bin= 66
container[6].i= 221
container[6].j= 215
container[6].angle= 333
container[6].value= 255


container[7].bin= 66
container[7].i= 222
container[7].j= 215
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 222
container[8].j= 217
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 223
container[9].j= 215
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 223
container[10].j= 217
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 224
container[11].j= 215
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 224
container[12].j= 217
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 225
container[13].j= 215
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 225
container[14].j= 217
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 226
container[15].j= 215
container[15].angle= 0
container[15].value= 255


container[16].bin= 66
container[16].i= 227
container[16].j= 216
container[16].angle= 333
container[16].value= 255


container[17].bin= 63
container[17].i= 228
container[17].j= 216
container[17].angle= 315
container[17].value= 255


