container[0].bin= 8
container[0].i= 599
container[0].j= 578
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 599
container[1].j= 579
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 599
container[2].j= 580
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 600
container[3].j= 578
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 600
container[4].j= 580
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 601
container[5].j= 577
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 601
container[6].j= 581
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 602
container[7].j= 577
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 602
container[8].j= 581
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 603
container[9].j= 577
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 603
container[10].j= 581
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 604
container[11].j= 577
container[11].angle= 0
container[11].value= 255


container[12].bin= 54
container[12].i= 604
container[12].j= 580
container[12].angle= 270
container[12].value= 255


container[13].bin= 44
container[13].i= 604
container[13].j= 581
container[13].angle= 224
container[13].value= 255


container[14].bin= 0
container[14].i= 605
container[14].j= 577
container[14].angle= 0
container[14].value= 255


container[15].bin= 44
container[15].i= 605
container[15].j= 579
container[15].angle= 224
container[15].value= 255


container[16].bin= 0
container[16].i= 606
container[16].j= 577
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 606
container[17].j= 579
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 607
container[18].j= 577
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 607
container[19].j= 579
container[19].angle= 180
container[19].value= 255


container[20].bin= 0
container[20].i= 608
container[20].j= 577
container[20].angle= 0
container[20].value= 255


container[21].bin= 36
container[21].i= 608
container[21].j= 579
container[21].angle= 180
container[21].value= 255


container[22].bin= 0
container[22].i= 609
container[22].j= 577
container[22].angle= 0
container[22].value= 255


container[23].bin= 36
container[23].i= 609
container[23].j= 579
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 610
container[24].j= 577
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 610
container[25].j= 579
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 611
container[26].j= 577
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 611
container[27].j= 579
container[27].angle= 180
container[27].value= 255


container[28].bin= 0
container[28].i= 612
container[28].j= 577
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 612
container[29].j= 579
container[29].angle= 180
container[29].value= 255


container[30].bin= 68
container[30].i= 613
container[30].j= 577
container[30].angle= 341
container[30].value= 255


container[31].bin= 54
container[31].i= 613
container[31].j= 578
container[31].angle= 270
container[31].value= 255


container[32].bin= 39
container[32].i= 613
container[32].j= 579
container[32].angle= 198
container[32].value= 255


