container[0].bin= 8
container[0].i= 76
container[0].j= 280
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 76
container[1].j= 281
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 76
container[2].j= 282
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 77
container[3].j= 280
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 77
container[4].j= 283
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 78
container[5].j= 279
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 78
container[6].j= 283
container[6].angle= 153
container[6].value= 255


container[7].bin= 66
container[7].i= 79
container[7].j= 280
container[7].angle= 333
container[7].value= 255


container[8].bin= 36
container[8].i= 79
container[8].j= 283
container[8].angle= 180
container[8].value= 255


container[9].bin= 66
container[9].i= 80
container[9].j= 280
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 80
container[10].j= 283
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 81
container[11].j= 281
container[11].angle= 333
container[11].value= 255


container[12].bin= 41
container[12].i= 81
container[12].j= 283
container[12].angle= 206
container[12].value= 255


container[13].bin= 63
container[13].i= 82
container[13].j= 281
container[13].angle= 315
container[13].value= 255


container[14].bin= 54
container[14].i= 82
container[14].j= 282
container[14].angle= 270
container[14].value= 255


container[15].bin= 44
container[15].i= 82
container[15].j= 283
container[15].angle= 224
container[15].value= 255


