container[0].bin= 18
container[0].i= 105
container[0].j= 306
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 106
container[1].j= 305
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 106
container[2].j= 307
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 107
container[3].j= 304
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 107
container[4].j= 307
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 108
container[5].j= 305
container[5].angle= 315
container[5].value= 255


container[6].bin= 27
container[6].i= 108
container[6].j= 308
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 108
container[7].j= 309
container[7].angle= 90
container[7].value= 255


container[8].bin= 18
container[8].i= 108
container[8].j= 310
container[8].angle= 90
container[8].value= 255


container[9].bin= 18
container[9].i= 108
container[9].j= 311
container[9].angle= 90
container[9].value= 255


container[10].bin= 18
container[10].i= 108
container[10].j= 312
container[10].angle= 90
container[10].value= 255


container[11].bin= 18
container[11].i= 108
container[11].j= 313
container[11].angle= 90
container[11].value= 255


container[12].bin= 12
container[12].i= 108
container[12].j= 314
container[12].angle= 63
container[12].value= 255


container[13].bin= 21
container[13].i= 108
container[13].j= 315
container[13].angle= 108
container[13].value= 255


container[14].bin= 63
container[14].i= 109
container[14].j= 306
container[14].angle= 315
container[14].value= 255


container[15].bin= 0
container[15].i= 110
container[15].j= 306
container[15].angle= 0
container[15].value= 255


container[16].bin= 36
container[16].i= 110
container[16].j= 315
container[16].angle= 180
container[16].value= 255


container[17].bin= 63
container[17].i= 111
container[17].j= 307
container[17].angle= 315
container[17].value= 255


container[18].bin= 36
container[18].i= 111
container[18].j= 315
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 112
container[19].j= 308
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 112
container[20].j= 315
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 113
container[21].j= 308
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 113
container[22].j= 315
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 114
container[23].j= 308
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 114
container[24].j= 316
container[24].angle= 135
container[24].value= 255


container[25].bin= 18
container[25].i= 114
container[25].j= 317
container[25].angle= 90
container[25].value= 255


container[26].bin= 0
container[26].i= 115
container[26].j= 308
container[26].angle= 0
container[26].value= 255


container[27].bin= 27
container[27].i= 115
container[27].j= 318
container[27].angle= 135
container[27].value= 255


container[28].bin= 0
container[28].i= 116
container[28].j= 308
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 116
container[29].j= 318
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 117
container[30].j= 308
container[30].angle= 0
container[30].value= 255


container[31].bin= 27
container[31].i= 117
container[31].j= 319
container[31].angle= 135
container[31].value= 255


container[32].bin= 18
container[32].i= 117
container[32].j= 320
container[32].angle= 90
container[32].value= 255


container[33].bin= 0
container[33].i= 118
container[33].j= 308
container[33].angle= 0
container[33].value= 255


container[34].bin= 27
container[34].i= 118
container[34].j= 321
container[34].angle= 135
container[34].value= 255


container[35].bin= 0
container[35].i= 119
container[35].j= 308
container[35].angle= 0
container[35].value= 255


container[36].bin= 36
container[36].i= 119
container[36].j= 321
container[36].angle= 180
container[36].value= 255


container[37].bin= 66
container[37].i= 120
container[37].j= 309
container[37].angle= 333
container[37].value= 255


container[38].bin= 27
container[38].i= 120
container[38].j= 322
container[38].angle= 135
container[38].value= 255


container[39].bin= 66
container[39].i= 121
container[39].j= 309
container[39].angle= 333
container[39].value= 255


container[40].bin= 27
container[40].i= 121
container[40].j= 323
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 122
container[41].j= 309
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 122
container[42].j= 323
container[42].angle= 180
container[42].value= 255


container[43].bin= 63
container[43].i= 123
container[43].j= 310
container[43].angle= 315
container[43].value= 255


container[44].bin= 27
container[44].i= 123
container[44].j= 324
container[44].angle= 135
container[44].value= 255


container[45].bin= 18
container[45].i= 123
container[45].j= 325
container[45].angle= 90
container[45].value= 255


container[46].bin= 63
container[46].i= 124
container[46].j= 311
container[46].angle= 315
container[46].value= 255


container[47].bin= 27
container[47].i= 124
container[47].j= 326
container[47].angle= 135
container[47].value= 255


container[48].bin= 0
container[48].i= 125
container[48].j= 311
container[48].angle= 0
container[48].value= 255


container[49].bin= 36
container[49].i= 125
container[49].j= 326
container[49].angle= 180
container[49].value= 255


container[50].bin= 63
container[50].i= 126
container[50].j= 312
container[50].angle= 315
container[50].value= 255


container[51].bin= 54
container[51].i= 126
container[51].j= 313
container[51].angle= 270
container[51].value= 255


container[52].bin= 30
container[52].i= 126
container[52].j= 327
container[52].angle= 153
container[52].value= 255


container[53].bin= 63
container[53].i= 127
container[53].j= 314
container[53].angle= 315
container[53].value= 255


container[54].bin= 30
container[54].i= 127
container[54].j= 327
container[54].angle= 153
container[54].value= 255


container[55].bin= 0
container[55].i= 128
container[55].j= 314
container[55].angle= 0
container[55].value= 255


container[56].bin= 36
container[56].i= 128
container[56].j= 327
container[56].angle= 180
container[56].value= 255


container[57].bin= 63
container[57].i= 129
container[57].j= 315
container[57].angle= 315
container[57].value= 255


container[58].bin= 54
container[58].i= 129
container[58].j= 316
container[58].angle= 270
container[58].value= 255


container[59].bin= 57
container[59].i= 129
container[59].j= 317
container[59].angle= 288
container[59].value= 255


container[60].bin= 27
container[60].i= 129
container[60].j= 328
container[60].angle= 135
container[60].value= 255


container[61].bin= 27
container[61].i= 130
container[61].j= 329
container[61].angle= 135
container[61].value= 255


container[62].bin= 0
container[62].i= 131
container[62].j= 317
container[62].angle= 0
container[62].value= 255


container[63].bin= 36
container[63].i= 131
container[63].j= 329
container[63].angle= 180
container[63].value= 255


container[64].bin= 63
container[64].i= 132
container[64].j= 317
container[64].angle= 315
container[64].value= 255


container[65].bin= 59
container[65].i= 132
container[65].j= 318
container[65].angle= 296
container[65].value= 255


container[66].bin= 36
container[66].i= 132
container[66].j= 329
container[66].angle= 180
container[66].value= 255


container[67].bin= 63
container[67].i= 133
container[67].j= 319
container[67].angle= 315
container[67].value= 255


container[68].bin= 36
container[68].i= 133
container[68].j= 329
container[68].angle= 180
container[68].value= 255


container[69].bin= 0
container[69].i= 134
container[69].j= 319
container[69].angle= 0
container[69].value= 255


container[70].bin= 36
container[70].i= 134
container[70].j= 329
container[70].angle= 180
container[70].value= 255


container[71].bin= 66
container[71].i= 135
container[71].j= 320
container[71].angle= 333
container[71].value= 255


container[72].bin= 36
container[72].i= 135
container[72].j= 329
container[72].angle= 180
container[72].value= 255


container[73].bin= 66
container[73].i= 136
container[73].j= 320
container[73].angle= 333
container[73].value= 255


container[74].bin= 36
container[74].i= 136
container[74].j= 329
container[74].angle= 180
container[74].value= 255


container[75].bin= 0
container[75].i= 137
container[75].j= 320
container[75].angle= 0
container[75].value= 255


container[76].bin= 36
container[76].i= 137
container[76].j= 329
container[76].angle= 180
container[76].value= 255


container[77].bin= 0
container[77].i= 138
container[77].j= 320
container[77].angle= 0
container[77].value= 255


container[78].bin= 27
container[78].i= 138
container[78].j= 330
container[78].angle= 135
container[78].value= 255


container[79].bin= 21
container[79].i= 138
container[79].j= 331
container[79].angle= 108
container[79].value= 255


container[80].bin= 0
container[80].i= 139
container[80].j= 320
container[80].angle= 0
container[80].value= 255


container[81].bin= 0
container[81].i= 140
container[81].j= 320
container[81].angle= 0
container[81].value= 255


container[82].bin= 36
container[82].i= 140
container[82].j= 331
container[82].angle= 180
container[82].value= 255


container[83].bin= 63
container[83].i= 141
container[83].j= 321
container[83].angle= 315
container[83].value= 255


container[84].bin= 30
container[84].i= 141
container[84].j= 331
container[84].angle= 153
container[84].value= 255


container[85].bin= 63
container[85].i= 142
container[85].j= 322
container[85].angle= 315
container[85].value= 255


container[86].bin= 36
container[86].i= 142
container[86].j= 331
container[86].angle= 180
container[86].value= 255


container[87].bin= 0
container[87].i= 143
container[87].j= 322
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 143
container[88].j= 331
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 144
container[89].j= 323
container[89].angle= 315
container[89].value= 255


container[90].bin= 36
container[90].i= 144
container[90].j= 331
container[90].angle= 180
container[90].value= 255


container[91].bin= 59
container[91].i= 145
container[91].j= 324
container[91].angle= 296
container[91].value= 255


container[92].bin= 63
container[92].i= 145
container[92].j= 325
container[92].angle= 315
container[92].value= 255


container[93].bin= 36
container[93].i= 145
container[93].j= 331
container[93].angle= 180
container[93].value= 255


container[94].bin= 0
container[94].i= 146
container[94].j= 325
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 146
container[95].j= 331
container[95].angle= 180
container[95].value= 255


container[96].bin= 68
container[96].i= 147
container[96].j= 325
container[96].angle= 341
container[96].value= 255


container[97].bin= 57
container[97].i= 147
container[97].j= 326
container[97].angle= 288
container[97].value= 255


container[98].bin= 54
container[98].i= 147
container[98].j= 327
container[98].angle= 270
container[98].value= 255


container[99].bin= 30
container[99].i= 147
container[99].j= 332
container[99].angle= 153
container[99].value= 255


container[100].bin= 63
container[100].i= 148
container[100].j= 328
container[100].angle= 315
container[100].value= 255


container[101].bin= 30
container[101].i= 148
container[101].j= 332
container[101].angle= 153
container[101].value= 255


container[102].bin= 0
container[102].i= 149
container[102].j= 328
container[102].angle= 0
container[102].value= 255


container[103].bin= 36
container[103].i= 149
container[103].j= 332
container[103].angle= 180
container[103].value= 255


container[104].bin= 0
container[104].i= 150
container[104].j= 328
container[104].angle= 0
container[104].value= 255


container[105].bin= 27
container[105].i= 150
container[105].j= 333
container[105].angle= 135
container[105].value= 255


container[106].bin= 0
container[106].i= 151
container[106].j= 328
container[106].angle= 0
container[106].value= 255


container[107].bin= 27
container[107].i= 151
container[107].j= 334
container[107].angle= 135
container[107].value= 255


container[108].bin= 0
container[108].i= 152
container[108].j= 328
container[108].angle= 0
container[108].value= 255


container[109].bin= 36
container[109].i= 152
container[109].j= 334
container[109].angle= 180
container[109].value= 255


container[110].bin= 63
container[110].i= 153
container[110].j= 329
container[110].angle= 315
container[110].value= 255


container[111].bin= 54
container[111].i= 153
container[111].j= 330
container[111].angle= 270
container[111].value= 255


container[112].bin= 54
container[112].i= 153
container[112].j= 331
container[112].angle= 270
container[112].value= 255


container[113].bin= 54
container[113].i= 153
container[113].j= 332
container[113].angle= 270
container[113].value= 255


container[114].bin= 63
container[114].i= 154
container[114].j= 333
container[114].angle= 315
container[114].value= 255


container[115].bin= 36
container[115].i= 154
container[115].j= 335
container[115].angle= 180
container[115].value= 255


container[116].bin= 0
container[116].i= 155
container[116].j= 333
container[116].angle= 0
container[116].value= 255


container[117].bin= 36
container[117].i= 155
container[117].j= 335
container[117].angle= 180
container[117].value= 255


container[118].bin= 0
container[118].i= 156
container[118].j= 333
container[118].angle= 0
container[118].value= 255


container[119].bin= 27
container[119].i= 156
container[119].j= 335
container[119].angle= 135
container[119].value= 255


container[120].bin= 0
container[120].i= 157
container[120].j= 333
container[120].angle= 0
container[120].value= 255


container[121].bin= 27
container[121].i= 157
container[121].j= 336
container[121].angle= 135
container[121].value= 255


container[122].bin= 0
container[122].i= 158
container[122].j= 333
container[122].angle= 0
container[122].value= 255


container[123].bin= 36
container[123].i= 158
container[123].j= 336
container[123].angle= 180
container[123].value= 255


container[124].bin= 0
container[124].i= 159
container[124].j= 333
container[124].angle= 0
container[124].value= 255


container[125].bin= 30
container[125].i= 159
container[125].j= 337
container[125].angle= 153
container[125].value= 255


container[126].bin= 0
container[126].i= 160
container[126].j= 333
container[126].angle= 0
container[126].value= 255


container[127].bin= 30
container[127].i= 160
container[127].j= 337
container[127].angle= 153
container[127].value= 255


container[128].bin= 0
container[128].i= 161
container[128].j= 333
container[128].angle= 0
container[128].value= 255


container[129].bin= 36
container[129].i= 161
container[129].j= 337
container[129].angle= 180
container[129].value= 255


container[130].bin= 0
container[130].i= 162
container[130].j= 333
container[130].angle= 0
container[130].value= 255


container[131].bin= 27
container[131].i= 162
container[131].j= 338
container[131].angle= 135
container[131].value= 255


container[132].bin= 18
container[132].i= 162
container[132].j= 339
container[132].angle= 90
container[132].value= 255


container[133].bin= 18
container[133].i= 162
container[133].j= 340
container[133].angle= 90
container[133].value= 255


container[134].bin= 5
container[134].i= 163
container[134].j= 333
container[134].angle= 26
container[134].value= 255


container[135].bin= 27
container[135].i= 163
container[135].j= 341
container[135].angle= 135
container[135].value= 255


container[136].bin= 0
container[136].i= 164
container[136].j= 333
container[136].angle= 0
container[136].value= 255


container[137].bin= 36
container[137].i= 164
container[137].j= 341
container[137].angle= 180
container[137].value= 255


container[138].bin= 66
container[138].i= 165
container[138].j= 333
container[138].angle= 333
container[138].value= 255


container[139].bin= 30
container[139].i= 165
container[139].j= 342
container[139].angle= 153
container[139].value= 255


container[140].bin= 0
container[140].i= 166
container[140].j= 333
container[140].angle= 0
container[140].value= 255


container[141].bin= 30
container[141].i= 166
container[141].j= 342
container[141].angle= 153
container[141].value= 255


container[142].bin= 0
container[142].i= 167
container[142].j= 333
container[142].angle= 0
container[142].value= 255


container[143].bin= 36
container[143].i= 167
container[143].j= 342
container[143].angle= 180
container[143].value= 255


container[144].bin= 63
container[144].i= 168
container[144].j= 334
container[144].angle= 315
container[144].value= 255


container[145].bin= 27
container[145].i= 168
container[145].j= 343
container[145].angle= 135
container[145].value= 255


container[146].bin= 18
container[146].i= 168
container[146].j= 344
container[146].angle= 90
container[146].value= 255


container[147].bin= 63
container[147].i= 169
container[147].j= 335
container[147].angle= 315
container[147].value= 255


container[148].bin= 27
container[148].i= 169
container[148].j= 345
container[148].angle= 135
container[148].value= 255


container[149].bin= 0
container[149].i= 170
container[149].j= 335
container[149].angle= 0
container[149].value= 255


container[150].bin= 36
container[150].i= 170
container[150].j= 345
container[150].angle= 180
container[150].value= 255


container[151].bin= 63
container[151].i= 171
container[151].j= 336
container[151].angle= 315
container[151].value= 255


container[152].bin= 54
container[152].i= 171
container[152].j= 337
container[152].angle= 270
container[152].value= 255


container[153].bin= 54
container[153].i= 171
container[153].j= 342
container[153].angle= 270
container[153].value= 255


container[154].bin= 54
container[154].i= 171
container[154].j= 344
container[154].angle= 270
container[154].value= 255


container[155].bin= 41
container[155].i= 171
container[155].j= 345
container[155].angle= 206
container[155].value= 255


container[156].bin= 59
container[156].i= 172
container[156].j= 338
container[156].angle= 296
container[156].value= 255


container[157].bin= 63
container[157].i= 172
container[157].j= 339
container[157].angle= 315
container[157].value= 255


container[158].bin= 44
container[158].i= 172
container[158].j= 341
container[158].angle= 224
container[158].value= 255


container[159].bin= 63
container[159].i= 172
container[159].j= 343
container[159].angle= 315
container[159].value= 255


container[160].bin= 41
container[160].i= 172
container[160].j= 345
container[160].angle= 206
container[160].value= 255


container[161].bin= 66
container[161].i= 173
container[161].j= 339
container[161].angle= 333
container[161].value= 255


container[162].bin= 36
container[162].i= 173
container[162].j= 341
container[162].angle= 180
container[162].value= 255


container[163].bin= 0
container[163].i= 173
container[163].j= 343
container[163].angle= 0
container[163].value= 255


container[164].bin= 36
container[164].i= 173
container[164].j= 345
container[164].angle= 180
container[164].value= 255


container[165].bin= 68
container[165].i= 174
container[165].j= 339
container[165].angle= 341
container[165].value= 255


container[166].bin= 39
container[166].i= 174
container[166].j= 341
container[166].angle= 198
container[166].value= 255


container[167].bin= 68
container[167].i= 174
container[167].j= 343
container[167].angle= 341
container[167].value= 255


container[168].bin= 54
container[168].i= 174
container[168].j= 344
container[168].angle= 270
container[168].value= 255


container[169].bin= 39
container[169].i= 174
container[169].j= 345
container[169].angle= 198
container[169].value= 255


