container[0].bin= 18
container[0].i= 225
container[0].j= 265
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 226
container[1].j= 264
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 226
container[2].j= 266
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 227
container[3].j= 264
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 227
container[4].j= 266
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 228
container[5].j= 264
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 228
container[6].j= 266
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 228
container[7].j= 267
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 229
container[8].j= 264
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 229
container[9].j= 268
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 230
container[10].j= 264
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 230
container[11].j= 268
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 231
container[12].j= 264
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 231
container[13].j= 269
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 232
container[14].j= 264
container[14].angle= 0
container[14].value= 255


container[15].bin= 23
container[15].i= 232
container[15].j= 270
container[15].angle= 116
container[15].value= 255


container[16].bin= 27
container[16].i= 232
container[16].j= 271
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 233
container[17].j= 264
container[17].angle= 0
container[17].value= 255


container[18].bin= 30
container[18].i= 233
container[18].j= 271
container[18].angle= 153
container[18].value= 255


container[19].bin= 63
container[19].i= 234
container[19].j= 265
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 234
container[20].j= 270
container[20].angle= 270
container[20].value= 255


container[21].bin= 63
container[21].i= 235
container[21].j= 266
container[21].angle= 315
container[21].value= 255


container[22].bin= 44
container[22].i= 235
container[22].j= 269
container[22].angle= 224
container[22].value= 255


container[23].bin= 27
container[23].i= 235
container[23].j= 273
container[23].angle= 135
container[23].value= 255


container[24].bin= 0
container[24].i= 236
container[24].j= 266
container[24].angle= 0
container[24].value= 255


container[25].bin= 0
container[25].i= 236
container[25].j= 271
container[25].angle= 0
container[25].value= 255


container[26].bin= 63
container[26].i= 237
container[26].j= 267
container[26].angle= 315
container[26].value= 255


container[27].bin= 44
container[27].i= 237
container[27].j= 268
container[27].angle= 224
container[27].value= 255


container[28].bin= 66
container[28].i= 237
container[28].j= 272
container[28].angle= 333
container[28].value= 255


container[29].bin= 66
container[29].i= 238
container[29].j= 272
container[29].angle= 333
container[29].value= 255


container[30].bin= 36
container[30].i= 238
container[30].j= 274
container[30].angle= 180
container[30].value= 255


container[31].bin= 0
container[31].i= 239
container[31].j= 272
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 239
container[32].j= 274
container[32].angle= 180
container[32].value= 255


container[33].bin= 68
container[33].i= 240
container[33].j= 272
container[33].angle= 341
container[33].value= 255


container[34].bin= 54
container[34].i= 240
container[34].j= 273
container[34].angle= 270
container[34].value= 255


container[35].bin= 39
container[35].i= 240
container[35].j= 274
container[35].angle= 198
container[35].value= 255


