container[0].bin= 18
container[0].i= 655
container[0].j= 567
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 656
container[1].j= 566
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 656
container[2].j= 568
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 657
container[3].j= 566
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 657
container[4].j= 568
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 658
container[5].j= 566
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 658
container[6].j= 568
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 659
container[7].j= 566
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 659
container[8].j= 568
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 660
container[9].j= 566
container[9].angle= 0
container[9].value= 255


container[10].bin= 0
container[10].i= 661
container[10].j= 566
container[10].angle= 0
container[10].value= 255


container[11].bin= 41
container[11].i= 661
container[11].j= 568
container[11].angle= 206
container[11].value= 255


container[12].bin= 0
container[12].i= 662
container[12].j= 566
container[12].angle= 0
container[12].value= 255


container[13].bin= 41
container[13].i= 662
container[13].j= 568
container[13].angle= 206
container[13].value= 255


container[14].bin= 0
container[14].i= 663
container[14].j= 566
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 663
container[15].j= 568
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 664
container[16].j= 566
container[16].angle= 0
container[16].value= 255


container[17].bin= 30
container[17].i= 664
container[17].j= 568
container[17].angle= 153
container[17].value= 255


container[18].bin= 0
container[18].i= 665
container[18].j= 566
container[18].angle= 0
container[18].value= 255


container[19].bin= 30
container[19].i= 665
container[19].j= 568
container[19].angle= 153
container[19].value= 255


container[20].bin= 0
container[20].i= 666
container[20].j= 566
container[20].angle= 0
container[20].value= 255


container[21].bin= 21
container[21].i= 666
container[21].j= 570
container[21].angle= 108
container[21].value= 255


container[22].bin= 63
container[22].i= 667
container[22].j= 567
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 667
container[23].j= 571
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 668
container[24].j= 569
container[24].angle= 315
container[24].value= 255


container[25].bin= 36
container[25].i= 668
container[25].j= 571
container[25].angle= 180
container[25].value= 255


container[26].bin= 0
container[26].i= 669
container[26].j= 569
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 669
container[27].j= 571
container[27].angle= 180
container[27].value= 255


container[28].bin= 68
container[28].i= 670
container[28].j= 569
container[28].angle= 341
container[28].value= 255


container[29].bin= 54
container[29].i= 670
container[29].j= 570
container[29].angle= 270
container[29].value= 255


container[30].bin= 39
container[30].i= 670
container[30].j= 571
container[30].angle= 198
container[30].value= 255


