container[0].bin= 8
container[0].i= 358
container[0].j= 199
container[0].angle= 44
container[0].value= 255


container[1].bin= 12
container[1].i= 358
container[1].j= 200
container[1].angle= 63
container[1].value= 255


container[2].bin= 27
container[2].i= 358
container[2].j= 201
container[2].angle= 135
container[2].value= 255


container[3].bin= 5
container[3].i= 359
container[3].j= 199
container[3].angle= 26
container[3].value= 255


container[4].bin= 36
container[4].i= 359
container[4].j= 201
container[4].angle= 180
container[4].value= 255


container[5].bin= 63
container[5].i= 360
container[5].j= 199
container[5].angle= 315
container[5].value= 255


container[6].bin= 63
container[6].i= 361
container[6].j= 200
container[6].angle= 315
container[6].value= 255


container[7].bin= 36
container[7].i= 361
container[7].j= 202
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 362
container[8].j= 200
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 362
container[9].j= 202
container[9].angle= 180
container[9].value= 255


container[10].bin= 8
container[10].i= 363
container[10].j= 200
container[10].angle= 44
container[10].value= 255


container[11].bin= 36
container[11].i= 363
container[11].j= 202
container[11].angle= 180
container[11].value= 255


container[12].bin= 8
container[12].i= 364
container[12].j= 199
container[12].angle= 44
container[12].value= 255


container[13].bin= 0
container[13].i= 365
container[13].j= 198
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 365
container[14].j= 201
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 366
container[15].j= 199
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 366
container[16].j= 200
container[16].angle= 270
container[16].value= 255


container[17].bin= 44
container[17].i= 366
container[17].j= 201
container[17].angle= 224
container[17].value= 255


