container[0].bin= 8
container[0].i= 272
container[0].j= 351
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 272
container[1].j= 352
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 272
container[2].j= 353
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 273
container[3].j= 350
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 273
container[4].j= 353
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 274
container[5].j= 350
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 274
container[6].j= 354
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 275
container[7].j= 350
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 275
container[8].j= 354
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 276
container[9].j= 351
container[9].angle= 333
container[9].value= 255


container[10].bin= 30
container[10].i= 276
container[10].j= 355
container[10].angle= 153
container[10].value= 255


container[11].bin= 66
container[11].i= 277
container[11].j= 351
container[11].angle= 333
container[11].value= 255


container[12].bin= 30
container[12].i= 277
container[12].j= 355
container[12].angle= 153
container[12].value= 255


container[13].bin= 66
container[13].i= 278
container[13].j= 352
container[13].angle= 333
container[13].value= 255


container[14].bin= 30
container[14].i= 278
container[14].j= 356
container[14].angle= 153
container[14].value= 255


container[15].bin= 66
container[15].i= 279
container[15].j= 352
container[15].angle= 333
container[15].value= 255


container[16].bin= 30
container[16].i= 279
container[16].j= 356
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 280
container[17].j= 353
container[17].angle= 333
container[17].value= 255


container[18].bin= 36
container[18].i= 280
container[18].j= 356
container[18].angle= 180
container[18].value= 255


container[19].bin= 66
container[19].i= 281
container[19].j= 353
container[19].angle= 333
container[19].value= 255


container[20].bin= 36
container[20].i= 281
container[20].j= 356
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 282
container[21].j= 353
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 282
container[22].j= 356
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 283
container[23].j= 353
container[23].angle= 0
container[23].value= 255


container[24].bin= 30
container[24].i= 283
container[24].j= 357
container[24].angle= 153
container[24].value= 255


container[25].bin= 66
container[25].i= 284
container[25].j= 354
container[25].angle= 333
container[25].value= 255


container[26].bin= 30
container[26].i= 284
container[26].j= 357
container[26].angle= 153
container[26].value= 255


container[27].bin= 66
container[27].i= 285
container[27].j= 354
container[27].angle= 333
container[27].value= 255


container[28].bin= 36
container[28].i= 285
container[28].j= 357
container[28].angle= 180
container[28].value= 255


container[29].bin= 0
container[29].i= 286
container[29].j= 354
container[29].angle= 0
container[29].value= 255


container[30].bin= 30
container[30].i= 286
container[30].j= 358
container[30].angle= 153
container[30].value= 255


container[31].bin= 66
container[31].i= 287
container[31].j= 355
container[31].angle= 333
container[31].value= 255


container[32].bin= 30
container[32].i= 287
container[32].j= 358
container[32].angle= 153
container[32].value= 255


container[33].bin= 66
container[33].i= 288
container[33].j= 355
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 288
container[34].j= 358
container[34].angle= 180
container[34].value= 255


container[35].bin= 66
container[35].i= 289
container[35].j= 356
container[35].angle= 333
container[35].value= 255


container[36].bin= 36
container[36].i= 289
container[36].j= 358
container[36].angle= 180
container[36].value= 255


container[37].bin= 66
container[37].i= 290
container[37].j= 356
container[37].angle= 333
container[37].value= 255


container[38].bin= 0
container[38].i= 291
container[38].j= 356
container[38].angle= 0
container[38].value= 255


container[39].bin= 63
container[39].i= 292
container[39].j= 357
container[39].angle= 315
container[39].value= 255


container[40].bin= 44
container[40].i= 292
container[40].j= 358
container[40].angle= 224
container[40].value= 255


