container[0].bin= 18
container[0].i= 96
container[0].j= 152
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 96
container[1].j= 153
container[1].angle= 90
container[1].value= 255


container[2].bin= 8
container[2].i= 97
container[2].j= 151
container[2].angle= 44
container[2].value= 255


container[3].bin= 27
container[3].i= 97
container[3].j= 154
container[3].angle= 135
container[3].value= 255


container[4].bin= 0
container[4].i= 98
container[4].j= 150
container[4].angle= 0
container[4].value= 255


container[5].bin= 36
container[5].i= 98
container[5].j= 154
container[5].angle= 180
container[5].value= 255


container[6].bin= 63
container[6].i= 99
container[6].j= 151
container[6].angle= 315
container[6].value= 255


container[7].bin= 36
container[7].i= 99
container[7].j= 154
container[7].angle= 180
container[7].value= 255


container[8].bin= 63
container[8].i= 100
container[8].j= 152
container[8].angle= 315
container[8].value= 255


container[9].bin= 0
container[9].i= 101
container[9].j= 152
container[9].angle= 0
container[9].value= 255


container[10].bin= 66
container[10].i= 102
container[10].j= 153
container[10].angle= 333
container[10].value= 255


container[11].bin= 27
container[11].i= 102
container[11].j= 155
container[11].angle= 135
container[11].value= 255


container[12].bin= 66
container[12].i= 103
container[12].j= 153
container[12].angle= 333
container[12].value= 255


container[13].bin= 27
container[13].i= 103
container[13].j= 156
container[13].angle= 135
container[13].value= 255


container[14].bin= 0
container[14].i= 104
container[14].j= 153
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 104
container[15].j= 156
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 105
container[16].j= 153
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 105
container[17].j= 156
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 106
container[18].j= 153
container[18].angle= 0
container[18].value= 255


container[19].bin= 54
container[19].i= 106
container[19].j= 155
container[19].angle= 270
container[19].value= 255


container[20].bin= 39
container[20].i= 106
container[20].j= 156
container[20].angle= 198
container[20].value= 255


container[21].bin= 68
container[21].i= 107
container[21].j= 153
container[21].angle= 341
container[21].value= 255


container[22].bin= 63
container[22].i= 107
container[22].j= 154
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 107
container[23].j= 157
container[23].angle= 180
container[23].value= 255


container[24].bin= 63
container[24].i= 108
container[24].j= 154
container[24].angle= 315
container[24].value= 255


container[25].bin= 63
container[25].i= 108
container[25].j= 155
container[25].angle= 315
container[25].value= 255


container[26].bin= 44
container[26].i= 108
container[26].j= 156
container[26].angle= 224
container[26].value= 255


