container[0].bin= 8
container[0].i= 409
container[0].j= 336
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 409
container[1].j= 337
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 410
container[2].j= 335
container[2].angle= 0
container[2].value= 255


container[3].bin= 18
container[3].i= 411
container[3].j= 334
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 411
container[4].j= 335
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 411
container[5].j= 338
container[5].angle= 135
container[5].value= 255


container[6].bin= 8
container[6].i= 412
container[6].j= 333
container[6].angle= 44
container[6].value= 255


container[7].bin= 27
container[7].i= 412
container[7].j= 339
container[7].angle= 135
container[7].value= 255


container[8].bin= 0
container[8].i= 413
container[8].j= 332
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 413
container[9].j= 339
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 414
container[10].j= 333
container[10].angle= 333
container[10].value= 255


container[11].bin= 27
container[11].i= 414
container[11].j= 340
container[11].angle= 135
container[11].value= 255


container[12].bin= 18
container[12].i= 414
container[12].j= 341
container[12].angle= 90
container[12].value= 255


container[13].bin= 21
container[13].i= 414
container[13].j= 342
container[13].angle= 108
container[13].value= 255


container[14].bin= 66
container[14].i= 415
container[14].j= 333
container[14].angle= 333
container[14].value= 255


container[15].bin= 44
container[15].i= 415
container[15].j= 337
container[15].angle= 224
container[15].value= 255


container[16].bin= 63
container[16].i= 415
container[16].j= 338
container[16].angle= 315
container[16].value= 255


container[17].bin= 27
container[17].i= 415
container[17].j= 342
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 416
container[18].j= 333
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 416
container[19].j= 336
container[19].angle= 180
container[19].value= 255


container[20].bin= 36
container[20].i= 416
container[20].j= 343
container[20].angle= 180
container[20].value= 255


container[21].bin= 0
container[21].i= 417
container[21].j= 333
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 417
container[22].j= 336
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 417
container[23].j= 339
container[23].angle= 315
container[23].value= 255


container[24].bin= 44
container[24].i= 417
container[24].j= 342
container[24].angle= 224
container[24].value= 255


container[25].bin= 0
container[25].i= 418
container[25].j= 333
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 418
container[26].j= 336
container[26].angle= 180
container[26].value= 255


container[27].bin= 54
container[27].i= 418
container[27].j= 340
container[27].angle= 270
container[27].value= 255


container[28].bin= 54
container[28].i= 418
container[28].j= 341
container[28].angle= 270
container[28].value= 255


container[29].bin= 0
container[29].i= 419
container[29].j= 333
container[29].angle= 0
container[29].value= 255


container[30].bin= 36
container[30].i= 419
container[30].j= 336
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 420
container[31].j= 334
container[31].angle= 315
container[31].value= 255


container[32].bin= 54
container[32].i= 420
container[32].j= 335
container[32].angle= 270
container[32].value= 255


container[33].bin= 44
container[33].i= 420
container[33].j= 336
container[33].angle= 224
container[33].value= 255


