container[0].bin= 8
container[0].i= 912
container[0].j= 249
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 912
container[1].j= 250
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 913
container[2].j= 248
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 914
container[3].j= 248
container[3].angle= 0
container[3].value= 255


