container[0].bin= 18
container[0].i= 911
container[0].j= 383
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 911
container[1].j= 384
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 911
container[2].j= 385
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 911
container[3].j= 386
container[3].angle= 90
container[3].value= 255


container[4].bin= 8
container[4].i= 912
container[4].j= 382
container[4].angle= 44
container[4].value= 255


container[5].bin= 27
container[5].i= 912
container[5].j= 387
container[5].angle= 135
container[5].value= 255


container[6].bin= 0
container[6].i= 913
container[6].j= 381
container[6].angle= 0
container[6].value= 255


container[7].bin= 36
container[7].i= 913
container[7].j= 387
container[7].angle= 180
container[7].value= 255


container[8].bin= 0
container[8].i= 914
container[8].j= 381
container[8].angle= 0
container[8].value= 255


container[9].bin= 36
container[9].i= 914
container[9].j= 387
container[9].angle= 180
container[9].value= 255


