container[0].bin= 18
container[0].i= 297
container[0].j= 278
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 298
container[1].j= 277
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 298
container[2].j= 279
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 299
container[3].j= 277
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 299
container[4].j= 279
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 300
container[5].j= 277
container[5].angle= 26
container[5].value= 255


container[6].bin= 18
container[6].i= 300
container[6].j= 278
container[6].angle= 90
container[6].value= 255


container[7].bin= 27
container[7].i= 300
container[7].j= 279
container[7].angle= 135
container[7].value= 255


container[8].bin= 18
container[8].i= 300
container[8].j= 280
container[8].angle= 90
container[8].value= 255


container[9].bin= 5
container[9].i= 301
container[9].j= 277
container[9].angle= 26
container[9].value= 255


container[10].bin= 27
container[10].i= 301
container[10].j= 281
container[10].angle= 135
container[10].value= 255


container[11].bin= 0
container[11].i= 302
container[11].j= 276
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 302
container[12].j= 281
container[12].angle= 180
container[12].value= 255


container[13].bin= 8
container[13].i= 303
container[13].j= 276
container[13].angle= 44
container[13].value= 255


container[14].bin= 27
container[14].i= 303
container[14].j= 282
container[14].angle= 135
container[14].value= 255


container[15].bin= 8
container[15].i= 304
container[15].j= 275
container[15].angle= 44
container[15].value= 255


container[16].bin= 27
container[16].i= 304
container[16].j= 283
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 305
container[17].j= 274
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 305
container[18].j= 283
container[18].angle= 180
container[18].value= 255


container[19].bin= 63
container[19].i= 306
container[19].j= 275
container[19].angle= 315
container[19].value= 255


container[20].bin= 54
container[20].i= 306
container[20].j= 276
container[20].angle= 270
container[20].value= 255


container[21].bin= 36
container[21].i= 306
container[21].j= 283
container[21].angle= 180
container[21].value= 255


container[22].bin= 63
container[22].i= 307
container[22].j= 277
container[22].angle= 315
container[22].value= 255


container[23].bin= 36
container[23].i= 307
container[23].j= 283
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 308
container[24].j= 277
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 308
container[25].j= 283
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 309
container[26].j= 278
container[26].angle= 315
container[26].value= 255


container[27].bin= 54
container[27].i= 309
container[27].j= 279
container[27].angle= 270
container[27].value= 255


container[28].bin= 54
container[28].i= 309
container[28].j= 280
container[28].angle= 270
container[28].value= 255


container[29].bin= 54
container[29].i= 309
container[29].j= 281
container[29].angle= 270
container[29].value= 255


container[30].bin= 63
container[30].i= 310
container[30].j= 282
container[30].angle= 315
container[30].value= 255


container[31].bin= 36
container[31].i= 310
container[31].j= 284
container[31].angle= 180
container[31].value= 255


container[32].bin= 0
container[32].i= 311
container[32].j= 282
container[32].angle= 0
container[32].value= 255


container[33].bin= 36
container[33].i= 311
container[33].j= 284
container[33].angle= 180
container[33].value= 255


container[34].bin= 0
container[34].i= 312
container[34].j= 282
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 312
container[35].j= 284
container[35].angle= 180
container[35].value= 255


container[36].bin= 0
container[36].i= 313
container[36].j= 282
container[36].angle= 0
container[36].value= 255


container[37].bin= 36
container[37].i= 313
container[37].j= 284
container[37].angle= 180
container[37].value= 255


container[38].bin= 0
container[38].i= 314
container[38].j= 282
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 314
container[39].j= 284
container[39].angle= 180
container[39].value= 255


container[40].bin= 68
container[40].i= 315
container[40].j= 282
container[40].angle= 341
container[40].value= 255


container[41].bin= 54
container[41].i= 315
container[41].j= 283
container[41].angle= 270
container[41].value= 255


container[42].bin= 39
container[42].i= 315
container[42].j= 284
container[42].angle= 198
container[42].value= 255


