container[0].bin= 8
container[0].i= 12
container[0].j= 309
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 12
container[1].j= 310
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 13
container[2].j= 308
container[2].angle= 0
container[2].value= 255


container[3].bin= 66
container[3].i= 14
container[3].j= 309
container[3].angle= 333
container[3].value= 255


container[4].bin= 27
container[4].i= 14
container[4].j= 311
container[4].angle= 135
container[4].value= 255


container[5].bin= 18
container[5].i= 14
container[5].j= 312
container[5].angle= 90
container[5].value= 255


container[6].bin= 66
container[6].i= 15
container[6].j= 309
container[6].angle= 333
container[6].value= 255


container[7].bin= 23
container[7].i= 15
container[7].j= 313
container[7].angle= 116
container[7].value= 255


container[8].bin= 23
container[8].i= 15
container[8].j= 314
container[8].angle= 116
container[8].value= 255


container[9].bin= 21
container[9].i= 15
container[9].j= 315
container[9].angle= 108
container[9].value= 255


container[10].bin= 8
container[10].i= 15
container[10].j= 328
container[10].angle= 44
container[10].value= 255


container[11].bin= 21
container[11].i= 15
container[11].j= 329
container[11].angle= 108
container[11].value= 255


container[12].bin= 0
container[12].i= 16
container[12].j= 309
container[12].angle= 0
container[12].value= 255


container[13].bin= 0
container[13].i= 16
container[13].j= 328
container[13].angle= 0
container[13].value= 255


container[14].bin= 36
container[14].i= 16
container[14].j= 330
container[14].angle= 180
container[14].value= 255


container[15].bin= 63
container[15].i= 17
container[15].j= 310
container[15].angle= 315
container[15].value= 255


container[16].bin= 54
container[16].i= 17
container[16].j= 311
container[16].angle= 270
container[16].value= 255


container[17].bin= 54
container[17].i= 17
container[17].j= 312
container[17].angle= 270
container[17].value= 255


container[18].bin= 32
container[18].i= 17
container[18].j= 315
container[18].angle= 161
container[18].value= 255


container[19].bin= 66
container[19].i= 17
container[19].j= 328
container[19].angle= 333
container[19].value= 255


container[20].bin= 27
container[20].i= 17
container[20].j= 330
container[20].angle= 135
container[20].value= 255


container[21].bin= 63
container[21].i= 18
container[21].j= 313
container[21].angle= 315
container[21].value= 255


container[22].bin= 23
container[22].i= 18
container[22].j= 316
container[22].angle= 116
container[22].value= 255


container[23].bin= 23
container[23].i= 18
container[23].j= 317
container[23].angle= 116
container[23].value= 255


container[24].bin= 0
container[24].i= 18
container[24].j= 328
container[24].angle= 0
container[24].value= 255


container[25].bin= 27
container[25].i= 18
container[25].j= 331
container[25].angle= 135
container[25].value= 255


container[26].bin= 3
container[26].i= 19
container[26].j= 313
container[26].angle= 18
container[26].value= 255


container[27].bin= 27
container[27].i= 19
container[27].j= 318
container[27].angle= 135
container[27].value= 255


container[28].bin= 0
container[28].i= 19
container[28].j= 328
container[28].angle= 0
container[28].value= 255


container[29].bin= 36
container[29].i= 19
container[29].j= 331
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 20
container[30].j= 312
container[30].angle= 0
container[30].value= 255


container[31].bin= 59
container[31].i= 20
container[31].j= 315
container[31].angle= 296
container[31].value= 255


container[32].bin= 27
container[32].i= 20
container[32].j= 319
container[32].angle= 135
container[32].value= 255


container[33].bin= 18
container[33].i= 20
container[33].j= 320
container[33].angle= 90
container[33].value= 255


container[34].bin= 18
container[34].i= 20
container[34].j= 321
container[34].angle= 90
container[34].value= 255


container[35].bin= 18
container[35].i= 20
container[35].j= 322
container[35].angle= 90
container[35].value= 255


container[36].bin= 18
container[36].i= 20
container[36].j= 323
container[36].angle= 90
container[36].value= 255


container[37].bin= 5
container[37].i= 20
container[37].j= 328
container[37].angle= 26
container[37].value= 255


container[38].bin= 30
container[38].i= 20
container[38].j= 332
container[38].angle= 153
container[38].value= 255


container[39].bin= 63
container[39].i= 21
container[39].j= 316
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 21
container[40].j= 324
container[40].angle= 135
container[40].value= 255


container[41].bin= 5
container[41].i= 21
container[41].j= 328
container[41].angle= 26
container[41].value= 255


container[42].bin= 30
container[42].i= 21
container[42].j= 332
container[42].angle= 153
container[42].value= 255


container[43].bin= 0
container[43].i= 22
container[43].j= 316
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 22
container[44].j= 324
container[44].angle= 180
container[44].value= 255


container[45].bin= 0
container[45].i= 22
container[45].j= 327
container[45].angle= 0
container[45].value= 255


container[46].bin= 36
container[46].i= 22
container[46].j= 332
container[46].angle= 180
container[46].value= 255


container[47].bin= 63
container[47].i= 23
container[47].j= 317
container[47].angle= 315
container[47].value= 255


container[48].bin= 54
container[48].i= 23
container[48].j= 318
container[48].angle= 270
container[48].value= 255


container[49].bin= 27
container[49].i= 23
container[49].j= 325
container[49].angle= 135
container[49].value= 255


container[50].bin= 18
container[50].i= 23
container[50].j= 326
container[50].angle= 90
container[50].value= 255


container[51].bin= 8
container[51].i= 23
container[51].j= 327
container[51].angle= 44
container[51].value= 255


container[52].bin= 27
container[52].i= 23
container[52].j= 333
container[52].angle= 135
container[52].value= 255


container[53].bin= 18
container[53].i= 23
container[53].j= 334
container[53].angle= 90
container[53].value= 255


container[54].bin= 63
container[54].i= 24
container[54].j= 319
container[54].angle= 315
container[54].value= 255


container[55].bin= 27
container[55].i= 24
container[55].j= 335
container[55].angle= 135
container[55].value= 255


container[56].bin= 0
container[56].i= 25
container[56].j= 319
container[56].angle= 0
container[56].value= 255


container[57].bin= 30
container[57].i= 25
container[57].j= 336
container[57].angle= 153
container[57].value= 255


container[58].bin= 0
container[58].i= 26
container[58].j= 319
container[58].angle= 0
container[58].value= 255


container[59].bin= 36
container[59].i= 26
container[59].j= 336
container[59].angle= 180
container[59].value= 255


container[60].bin= 66
container[60].i= 27
container[60].j= 320
container[60].angle= 333
container[60].value= 255


container[61].bin= 32
container[61].i= 27
container[61].j= 336
container[61].angle= 161
container[61].value= 255


container[62].bin= 66
container[62].i= 28
container[62].j= 320
container[62].angle= 333
container[62].value= 255


container[63].bin= 27
container[63].i= 28
container[63].j= 337
container[63].angle= 135
container[63].value= 255


container[64].bin= 0
container[64].i= 29
container[64].j= 320
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 29
container[65].j= 337
container[65].angle= 180
container[65].value= 255


container[66].bin= 63
container[66].i= 30
container[66].j= 321
container[66].angle= 315
container[66].value= 255


container[67].bin= 27
container[67].i= 30
container[67].j= 338
container[67].angle= 135
container[67].value= 255


container[68].bin= 18
container[68].i= 30
container[68].j= 339
container[68].angle= 90
container[68].value= 255


container[69].bin= 63
container[69].i= 31
container[69].j= 322
container[69].angle= 315
container[69].value= 255


container[70].bin= 27
container[70].i= 31
container[70].j= 340
container[70].angle= 135
container[70].value= 255


container[71].bin= 0
container[71].i= 32
container[71].j= 322
container[71].angle= 0
container[71].value= 255


container[72].bin= 36
container[72].i= 32
container[72].j= 340
container[72].angle= 180
container[72].value= 255


container[73].bin= 63
container[73].i= 33
container[73].j= 323
container[73].angle= 315
container[73].value= 255


container[74].bin= 54
container[74].i= 33
container[74].j= 324
container[74].angle= 270
container[74].value= 255


container[75].bin= 36
container[75].i= 33
container[75].j= 340
container[75].angle= 180
container[75].value= 255


container[76].bin= 18
container[76].i= 33
container[76].j= 342
container[76].angle= 90
container[76].value= 255


container[77].bin= 63
container[77].i= 34
container[77].j= 325
container[77].angle= 315
container[77].value= 255


container[78].bin= 36
container[78].i= 34
container[78].j= 340
container[78].angle= 180
container[78].value= 255


container[79].bin= 32
container[79].i= 34
container[79].j= 343
container[79].angle= 161
container[79].value= 255


container[80].bin= 0
container[80].i= 35
container[80].j= 325
container[80].angle= 0
container[80].value= 255


container[81].bin= 32
container[81].i= 35
container[81].j= 340
container[81].angle= 161
container[81].value= 255


container[82].bin= 36
container[82].i= 35
container[82].j= 343
container[82].angle= 180
container[82].value= 255


container[83].bin= 0
container[83].i= 36
container[83].j= 325
container[83].angle= 0
container[83].value= 255


container[84].bin= 27
container[84].i= 36
container[84].j= 343
container[84].angle= 135
container[84].value= 255


container[85].bin= 0
container[85].i= 37
container[85].j= 325
container[85].angle= 0
container[85].value= 255


container[86].bin= 27
container[86].i= 37
container[86].j= 344
container[86].angle= 135
container[86].value= 255


container[87].bin= 0
container[87].i= 38
container[87].j= 325
container[87].angle= 0
container[87].value= 255


container[88].bin= 36
container[88].i= 38
container[88].j= 344
container[88].angle= 180
container[88].value= 255


container[89].bin= 63
container[89].i= 39
container[89].j= 326
container[89].angle= 315
container[89].value= 255


container[90].bin= 54
container[90].i= 39
container[90].j= 327
container[90].angle= 270
container[90].value= 255


container[91].bin= 54
container[91].i= 39
container[91].j= 328
container[91].angle= 270
container[91].value= 255


container[92].bin= 54
container[92].i= 39
container[92].j= 329
container[92].angle= 270
container[92].value= 255


container[93].bin= 27
container[93].i= 39
container[93].j= 345
container[93].angle= 135
container[93].value= 255


container[94].bin= 18
container[94].i= 39
container[94].j= 346
container[94].angle= 90
container[94].value= 255


container[95].bin= 63
container[95].i= 40
container[95].j= 330
container[95].angle= 315
container[95].value= 255


container[96].bin= 27
container[96].i= 40
container[96].j= 347
container[96].angle= 135
container[96].value= 255


container[97].bin= 0
container[97].i= 41
container[97].j= 330
container[97].angle= 0
container[97].value= 255


container[98].bin= 36
container[98].i= 41
container[98].j= 347
container[98].angle= 180
container[98].value= 255


container[99].bin= 0
container[99].i= 42
container[99].j= 330
container[99].angle= 0
container[99].value= 255


container[100].bin= 30
container[100].i= 42
container[100].j= 348
container[100].angle= 153
container[100].value= 255


container[101].bin= 0
container[101].i= 43
container[101].j= 330
container[101].angle= 0
container[101].value= 255


container[102].bin= 27
container[102].i= 43
container[102].j= 348
container[102].angle= 135
container[102].value= 255


container[103].bin= 18
container[103].i= 43
container[103].j= 349
container[103].angle= 90
container[103].value= 255


container[104].bin= 21
container[104].i= 43
container[104].j= 350
container[104].angle= 108
container[104].value= 255


container[105].bin= 0
container[105].i= 44
container[105].j= 330
container[105].angle= 0
container[105].value= 255


container[106].bin= 32
container[106].i= 44
container[106].j= 350
container[106].angle= 161
container[106].value= 255


container[107].bin= 63
container[107].i= 45
container[107].j= 331
container[107].angle= 315
container[107].value= 255


container[108].bin= 54
container[108].i= 45
container[108].j= 332
container[108].angle= 270
container[108].value= 255


container[109].bin= 27
container[109].i= 45
container[109].j= 351
container[109].angle= 135
container[109].value= 255


container[110].bin= 63
container[110].i= 46
container[110].j= 333
container[110].angle= 315
container[110].value= 255


container[111].bin= 27
container[111].i= 46
container[111].j= 352
container[111].angle= 135
container[111].value= 255


container[112].bin= 0
container[112].i= 47
container[112].j= 333
container[112].angle= 0
container[112].value= 255


container[113].bin= 36
container[113].i= 47
container[113].j= 352
container[113].angle= 180
container[113].value= 255


container[114].bin= 0
container[114].i= 48
container[114].j= 333
container[114].angle= 0
container[114].value= 255


container[115].bin= 27
container[115].i= 48
container[115].j= 353
container[115].angle= 135
container[115].value= 255


container[116].bin= 18
container[116].i= 48
container[116].j= 354
container[116].angle= 90
container[116].value= 255


container[117].bin= 66
container[117].i= 49
container[117].j= 334
container[117].angle= 333
container[117].value= 255


container[118].bin= 27
container[118].i= 49
container[118].j= 355
container[118].angle= 135
container[118].value= 255


container[119].bin= 63
container[119].i= 50
container[119].j= 334
container[119].angle= 315
container[119].value= 255


container[120].bin= 63
container[120].i= 50
container[120].j= 335
container[120].angle= 315
container[120].value= 255


container[121].bin= 36
container[121].i= 50
container[121].j= 355
container[121].angle= 180
container[121].value= 255


container[122].bin= 63
container[122].i= 51
container[122].j= 335
container[122].angle= 315
container[122].value= 255


container[123].bin= 59
container[123].i= 51
container[123].j= 336
container[123].angle= 296
container[123].value= 255


container[124].bin= 54
container[124].i= 51
container[124].j= 337
container[124].angle= 270
container[124].value= 255


container[125].bin= 54
container[125].i= 51
container[125].j= 338
container[125].angle= 270
container[125].value= 255


container[126].bin= 36
container[126].i= 51
container[126].j= 355
container[126].angle= 180
container[126].value= 255


container[127].bin= 59
container[127].i= 52
container[127].j= 339
container[127].angle= 296
container[127].value= 255


container[128].bin= 63
container[128].i= 52
container[128].j= 340
container[128].angle= 315
container[128].value= 255


container[129].bin= 36
container[129].i= 52
container[129].j= 355
container[129].angle= 180
container[129].value= 255


container[130].bin= 0
container[130].i= 53
container[130].j= 340
container[130].angle= 0
container[130].value= 255


container[131].bin= 36
container[131].i= 53
container[131].j= 355
container[131].angle= 180
container[131].value= 255


container[132].bin= 0
container[132].i= 54
container[132].j= 340
container[132].angle= 0
container[132].value= 255


container[133].bin= 36
container[133].i= 54
container[133].j= 355
container[133].angle= 180
container[133].value= 255


container[134].bin= 66
container[134].i= 55
container[134].j= 340
container[134].angle= 333
container[134].value= 255


container[135].bin= 36
container[135].i= 55
container[135].j= 355
container[135].angle= 180
container[135].value= 255


container[136].bin= 0
container[136].i= 56
container[136].j= 340
container[136].angle= 0
container[136].value= 255


container[137].bin= 36
container[137].i= 56
container[137].j= 355
container[137].angle= 180
container[137].value= 255


container[138].bin= 63
container[138].i= 57
container[138].j= 341
container[138].angle= 315
container[138].value= 255


container[139].bin= 54
container[139].i= 57
container[139].j= 342
container[139].angle= 270
container[139].value= 255


container[140].bin= 54
container[140].i= 57
container[140].j= 343
container[140].angle= 270
container[140].value= 255


container[141].bin= 54
container[141].i= 57
container[141].j= 344
container[141].angle= 270
container[141].value= 255


container[142].bin= 30
container[142].i= 57
container[142].j= 356
container[142].angle= 153
container[142].value= 255


container[143].bin= 63
container[143].i= 58
container[143].j= 345
container[143].angle= 315
container[143].value= 255


container[144].bin= 30
container[144].i= 58
container[144].j= 356
container[144].angle= 153
container[144].value= 255


container[145].bin= 0
container[145].i= 59
container[145].j= 345
container[145].angle= 0
container[145].value= 255


container[146].bin= 36
container[146].i= 59
container[146].j= 356
container[146].angle= 180
container[146].value= 255


container[147].bin= 66
container[147].i= 60
container[147].j= 346
container[147].angle= 333
container[147].value= 255


container[148].bin= 36
container[148].i= 60
container[148].j= 356
container[148].angle= 180
container[148].value= 255


container[149].bin= 66
container[149].i= 61
container[149].j= 346
container[149].angle= 333
container[149].value= 255


container[150].bin= 36
container[150].i= 61
container[150].j= 356
container[150].angle= 180
container[150].value= 255


container[151].bin= 0
container[151].i= 62
container[151].j= 346
container[151].angle= 0
container[151].value= 255


container[152].bin= 36
container[152].i= 62
container[152].j= 356
container[152].angle= 180
container[152].value= 255


container[153].bin= 63
container[153].i= 63
container[153].j= 347
container[153].angle= 315
container[153].value= 255


container[154].bin= 36
container[154].i= 63
container[154].j= 356
container[154].angle= 180
container[154].value= 255


container[155].bin= 63
container[155].i= 64
container[155].j= 348
container[155].angle= 315
container[155].value= 255


container[156].bin= 36
container[156].i= 64
container[156].j= 356
container[156].angle= 180
container[156].value= 255


container[157].bin= 66
container[157].i= 65
container[157].j= 349
container[157].angle= 333
container[157].value= 255


container[158].bin= 36
container[158].i= 65
container[158].j= 356
container[158].angle= 180
container[158].value= 255


container[159].bin= 66
container[159].i= 66
container[159].j= 349
container[159].angle= 333
container[159].value= 255


container[160].bin= 36
container[160].i= 66
container[160].j= 356
container[160].angle= 180
container[160].value= 255


container[161].bin= 0
container[161].i= 67
container[161].j= 349
container[161].angle= 0
container[161].value= 255


container[162].bin= 36
container[162].i= 67
container[162].j= 356
container[162].angle= 180
container[162].value= 255


container[163].bin= 0
container[163].i= 68
container[163].j= 349
container[163].angle= 0
container[163].value= 255


container[164].bin= 36
container[164].i= 68
container[164].j= 356
container[164].angle= 180
container[164].value= 255


container[165].bin= 63
container[165].i= 69
container[165].j= 350
container[165].angle= 315
container[165].value= 255


container[166].bin= 36
container[166].i= 69
container[166].j= 356
container[166].angle= 180
container[166].value= 255


container[167].bin= 63
container[167].i= 70
container[167].j= 351
container[167].angle= 315
container[167].value= 255


container[168].bin= 36
container[168].i= 70
container[168].j= 356
container[168].angle= 180
container[168].value= 255


container[169].bin= 0
container[169].i= 71
container[169].j= 351
container[169].angle= 0
container[169].value= 255


container[170].bin= 36
container[170].i= 71
container[170].j= 356
container[170].angle= 180
container[170].value= 255


container[171].bin= 63
container[171].i= 72
container[171].j= 352
container[171].angle= 315
container[171].value= 255


container[172].bin= 36
container[172].i= 72
container[172].j= 356
container[172].angle= 180
container[172].value= 255


container[173].bin= 63
container[173].i= 73
container[173].j= 353
container[173].angle= 315
container[173].value= 255


container[174].bin= 36
container[174].i= 73
container[174].j= 356
container[174].angle= 180
container[174].value= 255


container[175].bin= 0
container[175].i= 74
container[175].j= 353
container[175].angle= 0
container[175].value= 255


container[176].bin= 36
container[176].i= 74
container[176].j= 356
container[176].angle= 180
container[176].value= 255


container[177].bin= 66
container[177].i= 75
container[177].j= 354
container[177].angle= 333
container[177].value= 255


container[178].bin= 27
container[178].i= 75
container[178].j= 357
container[178].angle= 135
container[178].value= 255


container[179].bin= 66
container[179].i= 76
container[179].j= 354
container[179].angle= 333
container[179].value= 255


container[180].bin= 27
container[180].i= 76
container[180].j= 358
container[180].angle= 135
container[180].value= 255


container[181].bin= 0
container[181].i= 77
container[181].j= 354
container[181].angle= 0
container[181].value= 255


container[182].bin= 36
container[182].i= 77
container[182].j= 358
container[182].angle= 180
container[182].value= 255


container[183].bin= 63
container[183].i= 78
container[183].j= 355
container[183].angle= 315
container[183].value= 255


container[184].bin= 54
container[184].i= 78
container[184].j= 356
container[184].angle= 270
container[184].value= 255


container[185].bin= 27
container[185].i= 78
container[185].j= 359
container[185].angle= 135
container[185].value= 255


container[186].bin= 63
container[186].i= 79
container[186].j= 357
container[186].angle= 315
container[186].value= 255


container[187].bin= 27
container[187].i= 79
container[187].j= 360
container[187].angle= 135
container[187].value= 255


container[188].bin= 0
container[188].i= 80
container[188].j= 357
container[188].angle= 0
container[188].value= 255


container[189].bin= 36
container[189].i= 80
container[189].j= 360
container[189].angle= 180
container[189].value= 255


container[190].bin= 63
container[190].i= 81
container[190].j= 358
container[190].angle= 315
container[190].value= 255


container[191].bin= 30
container[191].i= 81
container[191].j= 361
container[191].angle= 153
container[191].value= 255


container[192].bin= 63
container[192].i= 82
container[192].j= 359
container[192].angle= 315
container[192].value= 255


container[193].bin= 30
container[193].i= 82
container[193].j= 361
container[193].angle= 153
container[193].value= 255


container[194].bin= 0
container[194].i= 83
container[194].j= 359
container[194].angle= 0
container[194].value= 255


container[195].bin= 0
container[195].i= 84
container[195].j= 359
container[195].angle= 0
container[195].value= 255


container[196].bin= 27
container[196].i= 84
container[196].j= 362
container[196].angle= 135
container[196].value= 255


container[197].bin= 0
container[197].i= 85
container[197].j= 359
container[197].angle= 0
container[197].value= 255


container[198].bin= 27
container[198].i= 85
container[198].j= 363
container[198].angle= 135
container[198].value= 255


container[199].bin= 68
container[199].i= 86
container[199].j= 359
container[199].angle= 341
container[199].value= 255


container[200].bin= 36
container[200].i= 86
container[200].j= 363
container[200].angle= 180
container[200].value= 255


container[201].bin= 63
container[201].i= 87
container[201].j= 360
container[201].angle= 315
container[201].value= 255


container[202].bin= 59
container[202].i= 87
container[202].j= 361
container[202].angle= 296
container[202].value= 255


container[203].bin= 63
container[203].i= 88
container[203].j= 362
container[203].angle= 315
container[203].value= 255


container[204].bin= 36
container[204].i= 88
container[204].j= 364
container[204].angle= 180
container[204].value= 255


container[205].bin= 0
container[205].i= 89
container[205].j= 362
container[205].angle= 0
container[205].value= 255


container[206].bin= 36
container[206].i= 89
container[206].j= 364
container[206].angle= 180
container[206].value= 255


container[207].bin= 68
container[207].i= 90
container[207].j= 362
container[207].angle= 341
container[207].value= 255


container[208].bin= 54
container[208].i= 90
container[208].j= 363
container[208].angle= 270
container[208].value= 255


container[209].bin= 39
container[209].i= 90
container[209].j= 364
container[209].angle= 198
container[209].value= 255


