container[0].bin= 18
container[0].i= 727
container[0].j= 196
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 728
container[1].j= 195
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 728
container[2].j= 197
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 729
container[3].j= 195
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 729
container[4].j= 197
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 730
container[5].j= 195
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 730
container[6].j= 197
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 731
container[7].j= 195
container[7].angle= 0
container[7].value= 255


container[8].bin= 27
container[8].i= 731
container[8].j= 197
container[8].angle= 135
container[8].value= 255


container[9].bin= 23
container[9].i= 731
container[9].j= 198
container[9].angle= 116
container[9].value= 255


container[10].bin= 18
container[10].i= 731
container[10].j= 199
container[10].angle= 90
container[10].value= 255


container[11].bin= 12
container[11].i= 731
container[11].j= 200
container[11].angle= 63
container[11].value= 255


container[12].bin= 21
container[12].i= 731
container[12].j= 201
container[12].angle= 108
container[12].value= 255


container[13].bin= 0
container[13].i= 732
container[13].j= 195
container[13].angle= 0
container[13].value= 255


container[14].bin= 0
container[14].i= 733
container[14].j= 195
container[14].angle= 0
container[14].value= 255


container[15].bin= 36
container[15].i= 733
container[15].j= 198
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 734
container[16].j= 195
container[16].angle= 0
container[16].value= 255


container[17].bin= 21
container[17].i= 734
container[17].j= 199
container[17].angle= 108
container[17].value= 255


container[18].bin= 18
container[18].i= 734
container[18].j= 200
container[18].angle= 90
container[18].value= 255


container[19].bin= 18
container[19].i= 734
container[19].j= 201
container[19].angle= 90
container[19].value= 255


container[20].bin= 27
container[20].i= 734
container[20].j= 202
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 735
container[21].j= 195
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 735
container[22].j= 202
container[22].angle= 180
container[22].value= 255


container[23].bin= 63
container[23].i= 736
container[23].j= 196
container[23].angle= 315
container[23].value= 255


container[24].bin= 27
container[24].i= 736
container[24].j= 203
container[24].angle= 135
container[24].value= 255


container[25].bin= 63
container[25].i= 737
container[25].j= 197
container[25].angle= 315
container[25].value= 255


container[26].bin= 27
container[26].i= 737
container[26].j= 204
container[26].angle= 135
container[26].value= 255


container[27].bin= 0
container[27].i= 738
container[27].j= 197
container[27].angle= 0
container[27].value= 255


container[28].bin= 36
container[28].i= 738
container[28].j= 204
container[28].angle= 180
container[28].value= 255


container[29].bin= 66
container[29].i= 739
container[29].j= 198
container[29].angle= 333
container[29].value= 255


container[30].bin= 27
container[30].i= 739
container[30].j= 205
container[30].angle= 135
container[30].value= 255


container[31].bin= 18
container[31].i= 739
container[31].j= 206
container[31].angle= 90
container[31].value= 255


container[32].bin= 66
container[32].i= 740
container[32].j= 198
container[32].angle= 333
container[32].value= 255


container[33].bin= 27
container[33].i= 740
container[33].j= 207
container[33].angle= 135
container[33].value= 255


container[34].bin= 0
container[34].i= 741
container[34].j= 198
container[34].angle= 0
container[34].value= 255


container[35].bin= 36
container[35].i= 741
container[35].j= 207
container[35].angle= 180
container[35].value= 255


container[36].bin= 63
container[36].i= 742
container[36].j= 199
container[36].angle= 315
container[36].value= 255


container[37].bin= 27
container[37].i= 742
container[37].j= 208
container[37].angle= 135
container[37].value= 255


container[38].bin= 18
container[38].i= 742
container[38].j= 209
container[38].angle= 90
container[38].value= 255


container[39].bin= 63
container[39].i= 743
container[39].j= 200
container[39].angle= 315
container[39].value= 255


container[40].bin= 27
container[40].i= 743
container[40].j= 210
container[40].angle= 135
container[40].value= 255


container[41].bin= 0
container[41].i= 744
container[41].j= 200
container[41].angle= 0
container[41].value= 255


container[42].bin= 36
container[42].i= 744
container[42].j= 210
container[42].angle= 180
container[42].value= 255


container[43].bin= 0
container[43].i= 745
container[43].j= 200
container[43].angle= 0
container[43].value= 255


container[44].bin= 36
container[44].i= 745
container[44].j= 210
container[44].angle= 180
container[44].value= 255


container[45].bin= 63
container[45].i= 746
container[45].j= 201
container[45].angle= 315
container[45].value= 255


container[46].bin= 54
container[46].i= 746
container[46].j= 202
container[46].angle= 270
container[46].value= 255


container[47].bin= 27
container[47].i= 746
container[47].j= 211
container[47].angle= 135
container[47].value= 255


container[48].bin= 18
container[48].i= 746
container[48].j= 212
container[48].angle= 90
container[48].value= 255


container[49].bin= 18
container[49].i= 746
container[49].j= 213
container[49].angle= 90
container[49].value= 255


container[50].bin= 18
container[50].i= 746
container[50].j= 214
container[50].angle= 90
container[50].value= 255


container[51].bin= 63
container[51].i= 747
container[51].j= 203
container[51].angle= 315
container[51].value= 255


container[52].bin= 27
container[52].i= 747
container[52].j= 215
container[52].angle= 135
container[52].value= 255


container[53].bin= 0
container[53].i= 748
container[53].j= 203
container[53].angle= 0
container[53].value= 255


container[54].bin= 36
container[54].i= 748
container[54].j= 215
container[54].angle= 180
container[54].value= 255


container[55].bin= 63
container[55].i= 749
container[55].j= 204
container[55].angle= 315
container[55].value= 255


container[56].bin= 27
container[56].i= 749
container[56].j= 216
container[56].angle= 135
container[56].value= 255


container[57].bin= 63
container[57].i= 750
container[57].j= 205
container[57].angle= 315
container[57].value= 255


container[58].bin= 27
container[58].i= 750
container[58].j= 217
container[58].angle= 135
container[58].value= 255


container[59].bin= 0
container[59].i= 751
container[59].j= 205
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 751
container[60].j= 217
container[60].angle= 180
container[60].value= 255


container[61].bin= 66
container[61].i= 752
container[61].j= 206
container[61].angle= 333
container[61].value= 255


container[62].bin= 27
container[62].i= 752
container[62].j= 218
container[62].angle= 135
container[62].value= 255


container[63].bin= 18
container[63].i= 752
container[63].j= 219
container[63].angle= 90
container[63].value= 255


container[64].bin= 21
container[64].i= 752
container[64].j= 220
container[64].angle= 108
container[64].value= 255


container[65].bin= 66
container[65].i= 753
container[65].j= 206
container[65].angle= 333
container[65].value= 255


container[66].bin= 27
container[66].i= 753
container[66].j= 220
container[66].angle= 135
container[66].value= 255


container[67].bin= 0
container[67].i= 754
container[67].j= 206
container[67].angle= 0
container[67].value= 255


container[68].bin= 36
container[68].i= 754
container[68].j= 218
container[68].angle= 180
container[68].value= 255


container[69].bin= 36
container[69].i= 754
container[69].j= 221
container[69].angle= 180
container[69].value= 255


container[70].bin= 63
container[70].i= 755
container[70].j= 207
container[70].angle= 315
container[70].value= 255


container[71].bin= 27
container[71].i= 755
container[71].j= 218
container[71].angle= 135
container[71].value= 255


container[72].bin= 18
container[72].i= 755
container[72].j= 219
container[72].angle= 90
container[72].value= 255


container[73].bin= 27
container[73].i= 755
container[73].j= 221
container[73].angle= 135
container[73].value= 255


container[74].bin= 63
container[74].i= 756
container[74].j= 208
container[74].angle= 315
container[74].value= 255


container[75].bin= 27
container[75].i= 756
container[75].j= 222
container[75].angle= 135
container[75].value= 255


container[76].bin= 0
container[76].i= 757
container[76].j= 208
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 757
container[77].j= 222
container[77].angle= 180
container[77].value= 255


container[78].bin= 63
container[78].i= 758
container[78].j= 209
container[78].angle= 315
container[78].value= 255


container[79].bin= 36
container[79].i= 758
container[79].j= 222
container[79].angle= 180
container[79].value= 255


container[80].bin= 63
container[80].i= 759
container[80].j= 210
container[80].angle= 315
container[80].value= 255


container[81].bin= 36
container[81].i= 759
container[81].j= 222
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 760
container[82].j= 210
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 760
container[83].j= 222
container[83].angle= 180
container[83].value= 255


container[84].bin= 66
container[84].i= 761
container[84].j= 211
container[84].angle= 333
container[84].value= 255


container[85].bin= 27
container[85].i= 761
container[85].j= 223
container[85].angle= 135
container[85].value= 255


container[86].bin= 18
container[86].i= 761
container[86].j= 224
container[86].angle= 90
container[86].value= 255


container[87].bin= 18
container[87].i= 761
container[87].j= 225
container[87].angle= 90
container[87].value= 255


container[88].bin= 66
container[88].i= 762
container[88].j= 211
container[88].angle= 333
container[88].value= 255


container[89].bin= 27
container[89].i= 762
container[89].j= 226
container[89].angle= 135
container[89].value= 255


container[90].bin= 0
container[90].i= 763
container[90].j= 211
container[90].angle= 0
container[90].value= 255


container[91].bin= 36
container[91].i= 763
container[91].j= 226
container[91].angle= 180
container[91].value= 255


container[92].bin= 63
container[92].i= 764
container[92].j= 212
container[92].angle= 315
container[92].value= 255


container[93].bin= 36
container[93].i= 764
container[93].j= 226
container[93].angle= 180
container[93].value= 255


container[94].bin= 63
container[94].i= 765
container[94].j= 213
container[94].angle= 315
container[94].value= 255


container[95].bin= 36
container[95].i= 765
container[95].j= 226
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 766
container[96].j= 213
container[96].angle= 0
container[96].value= 255


container[97].bin= 36
container[97].i= 766
container[97].j= 226
container[97].angle= 180
container[97].value= 255


container[98].bin= 66
container[98].i= 767
container[98].j= 214
container[98].angle= 333
container[98].value= 255


container[99].bin= 41
container[99].i= 767
container[99].j= 226
container[99].angle= 206
container[99].value= 255


container[100].bin= 66
container[100].i= 768
container[100].j= 214
container[100].angle= 333
container[100].value= 255


container[101].bin= 41
container[101].i= 768
container[101].j= 226
container[101].angle= 206
container[101].value= 255


container[102].bin= 0
container[102].i= 769
container[102].j= 214
container[102].angle= 0
container[102].value= 255


container[103].bin= 36
container[103].i= 769
container[103].j= 225
container[103].angle= 180
container[103].value= 255


container[104].bin= 63
container[104].i= 770
container[104].j= 215
container[104].angle= 315
container[104].value= 255


container[105].bin= 54
container[105].i= 770
container[105].j= 216
container[105].angle= 270
container[105].value= 255


container[106].bin= 54
container[106].i= 770
container[106].j= 217
container[106].angle= 270
container[106].value= 255


container[107].bin= 44
container[107].i= 770
container[107].j= 225
container[107].angle= 224
container[107].value= 255


container[108].bin= 63
container[108].i= 771
container[108].j= 218
container[108].angle= 315
container[108].value= 255


container[109].bin= 44
container[109].i= 771
container[109].j= 224
container[109].angle= 224
container[109].value= 255


container[110].bin= 0
container[110].i= 772
container[110].j= 218
container[110].angle= 0
container[110].value= 255


container[111].bin= 36
container[111].i= 772
container[111].j= 223
container[111].angle= 180
container[111].value= 255


container[112].bin= 0
container[112].i= 773
container[112].j= 218
container[112].angle= 0
container[112].value= 255


container[113].bin= 36
container[113].i= 773
container[113].j= 223
container[113].angle= 180
container[113].value= 255


container[114].bin= 0
container[114].i= 774
container[114].j= 218
container[114].angle= 0
container[114].value= 255


container[115].bin= 36
container[115].i= 774
container[115].j= 223
container[115].angle= 180
container[115].value= 255


container[116].bin= 0
container[116].i= 775
container[116].j= 218
container[116].angle= 0
container[116].value= 255


container[117].bin= 36
container[117].i= 775
container[117].j= 223
container[117].angle= 180
container[117].value= 255


container[118].bin= 66
container[118].i= 776
container[118].j= 219
container[118].angle= 333
container[118].value= 255


container[119].bin= 54
container[119].i= 776
container[119].j= 220
container[119].angle= 270
container[119].value= 255


container[120].bin= 54
container[120].i= 776
container[120].j= 221
container[120].angle= 270
container[120].value= 255


container[121].bin= 54
container[121].i= 776
container[121].j= 222
container[121].angle= 270
container[121].value= 255


container[122].bin= 41
container[122].i= 776
container[122].j= 223
container[122].angle= 206
container[122].value= 255


container[123].bin= 66
container[123].i= 777
container[123].j= 219
container[123].angle= 333
container[123].value= 255


container[124].bin= 41
container[124].i= 777
container[124].j= 223
container[124].angle= 206
container[124].value= 255


container[125].bin= 0
container[125].i= 778
container[125].j= 219
container[125].angle= 0
container[125].value= 255


container[126].bin= 39
container[126].i= 778
container[126].j= 223
container[126].angle= 198
container[126].value= 255


container[127].bin= 68
container[127].i= 779
container[127].j= 219
container[127].angle= 341
container[127].value= 255


container[128].bin= 54
container[128].i= 779
container[128].j= 220
container[128].angle= 270
container[128].value= 255


container[129].bin= 44
container[129].i= 779
container[129].j= 221
container[129].angle= 224
container[129].value= 255


