container[0].bin= 18
container[0].i= 81
container[0].j= 391
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 82
container[1].j= 390
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 82
container[2].j= 392
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 83
container[3].j= 389
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 83
container[4].j= 392
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 84
container[5].j= 389
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 84
container[6].j= 393
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 85
container[7].j= 389
container[7].angle= 26
container[7].value= 255


container[8].bin= 30
container[8].i= 85
container[8].j= 393
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 86
container[9].j= 388
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 86
container[10].j= 393
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 87
container[11].j= 389
container[11].angle= 333
container[11].value= 255


container[12].bin= 27
container[12].i= 87
container[12].j= 394
container[12].angle= 135
container[12].value= 255


container[13].bin= 18
container[13].i= 87
container[13].j= 395
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 87
container[14].j= 396
container[14].angle= 90
container[14].value= 255


container[15].bin= 18
container[15].i= 87
container[15].j= 397
container[15].angle= 90
container[15].value= 255


container[16].bin= 66
container[16].i= 88
container[16].j= 389
container[16].angle= 333
container[16].value= 255


container[17].bin= 27
container[17].i= 88
container[17].j= 398
container[17].angle= 135
container[17].value= 255


container[18].bin= 0
container[18].i= 89
container[18].j= 389
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 89
container[19].j= 398
container[19].angle= 180
container[19].value= 255


container[20].bin= 63
container[20].i= 90
container[20].j= 390
container[20].angle= 315
container[20].value= 255


container[21].bin= 57
container[21].i= 90
container[21].j= 391
container[21].angle= 288
container[21].value= 255


container[22].bin= 27
container[22].i= 90
container[22].j= 399
container[22].angle= 135
container[22].value= 255


container[23].bin= 0
container[23].i= 91
container[23].j= 389
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 91
container[24].j= 400
container[24].angle= 135
container[24].value= 255


container[25].bin= 3
container[25].i= 92
container[25].j= 390
container[25].angle= 18
container[25].value= 255


container[26].bin= 8
container[26].i= 92
container[26].j= 391
container[26].angle= 44
container[26].value= 255


container[27].bin= 36
container[27].i= 92
container[27].j= 400
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 93
container[28].j= 390
container[28].angle= 315
container[28].value= 255


container[29].bin= 63
container[29].i= 93
container[29].j= 391
container[29].angle= 315
container[29].value= 255


container[30].bin= 30
container[30].i= 93
container[30].j= 401
container[30].angle= 153
container[30].value= 255


container[31].bin= 66
container[31].i= 94
container[31].j= 391
container[31].angle= 333
container[31].value= 255


container[32].bin= 30
container[32].i= 94
container[32].j= 401
container[32].angle= 153
container[32].value= 255


container[33].bin= 0
container[33].i= 95
container[33].j= 391
container[33].angle= 0
container[33].value= 255


container[34].bin= 36
container[34].i= 95
container[34].j= 401
container[34].angle= 180
container[34].value= 255


container[35].bin= 68
container[35].i= 96
container[35].j= 391
container[35].angle= 341
container[35].value= 255


container[36].bin= 57
container[36].i= 96
container[36].j= 393
container[36].angle= 288
container[36].value= 255


container[37].bin= 27
container[37].i= 96
container[37].j= 402
container[37].angle= 135
container[37].value= 255


container[38].bin= 68
container[38].i= 97
container[38].j= 393
container[38].angle= 341
container[38].value= 255


container[39].bin= 27
container[39].i= 97
container[39].j= 403
container[39].angle= 135
container[39].value= 255


container[40].bin= 0
container[40].i= 98
container[40].j= 393
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 98
container[41].j= 403
container[41].angle= 180
container[41].value= 255


container[42].bin= 66
container[42].i= 99
container[42].j= 394
container[42].angle= 333
container[42].value= 255


container[43].bin= 54
container[43].i= 99
container[43].j= 395
container[43].angle= 270
container[43].value= 255


container[44].bin= 54
container[44].i= 99
container[44].j= 397
container[44].angle= 270
container[44].value= 255


container[45].bin= 54
container[45].i= 99
container[45].j= 398
container[45].angle= 270
container[45].value= 255


container[46].bin= 27
container[46].i= 99
container[46].j= 404
container[46].angle= 135
container[46].value= 255


container[47].bin= 18
container[47].i= 99
container[47].j= 405
container[47].angle= 90
container[47].value= 255


container[48].bin= 21
container[48].i= 99
container[48].j= 406
container[48].angle= 108
container[48].value= 255


container[49].bin= 66
container[49].i= 100
container[49].j= 394
container[49].angle= 333
container[49].value= 255


container[50].bin= 44
container[50].i= 100
container[50].j= 396
container[50].angle= 224
container[50].value= 255


container[51].bin= 63
container[51].i= 100
container[51].j= 399
container[51].angle= 315
container[51].value= 255


container[52].bin= 0
container[52].i= 101
container[52].j= 394
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 101
container[53].j= 396
container[53].angle= 180
container[53].value= 255


container[54].bin= 0
container[54].i= 101
container[54].j= 399
container[54].angle= 0
container[54].value= 255


container[55].bin= 36
container[55].i= 101
container[55].j= 406
container[55].angle= 180
container[55].value= 255


container[56].bin= 68
container[56].i= 102
container[56].j= 394
container[56].angle= 341
container[56].value= 255


container[57].bin= 54
container[57].i= 102
container[57].j= 395
container[57].angle= 270
container[57].value= 255


container[58].bin= 39
container[58].i= 102
container[58].j= 396
container[58].angle= 198
container[58].value= 255


container[59].bin= 63
container[59].i= 102
container[59].j= 400
container[59].angle= 315
container[59].value= 255


container[60].bin= 27
container[60].i= 102
container[60].j= 406
container[60].angle= 135
container[60].value= 255


container[61].bin= 23
container[61].i= 102
container[61].j= 407
container[61].angle= 116
container[61].value= 255


container[62].bin= 63
container[62].i= 103
container[62].j= 401
container[62].angle= 315
container[62].value= 255


container[63].bin= 27
container[63].i= 103
container[63].j= 408
container[63].angle= 135
container[63].value= 255


container[64].bin= 0
container[64].i= 104
container[64].j= 401
container[64].angle= 0
container[64].value= 255


container[65].bin= 36
container[65].i= 104
container[65].j= 408
container[65].angle= 180
container[65].value= 255


container[66].bin= 0
container[66].i= 105
container[66].j= 401
container[66].angle= 0
container[66].value= 255


container[67].bin= 30
container[67].i= 105
container[67].j= 409
container[67].angle= 153
container[67].value= 255


container[68].bin= 0
container[68].i= 106
container[68].j= 401
container[68].angle= 0
container[68].value= 255


container[69].bin= 30
container[69].i= 106
container[69].j= 409
container[69].angle= 153
container[69].value= 255


container[70].bin= 0
container[70].i= 107
container[70].j= 401
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 107
container[71].j= 409
container[71].angle= 180
container[71].value= 255


container[72].bin= 66
container[72].i= 108
container[72].j= 402
container[72].angle= 333
container[72].value= 255


container[73].bin= 36
container[73].i= 108
container[73].j= 409
container[73].angle= 180
container[73].value= 255


container[74].bin= 66
container[74].i= 109
container[74].j= 402
container[74].angle= 333
container[74].value= 255


container[75].bin= 36
container[75].i= 109
container[75].j= 409
container[75].angle= 180
container[75].value= 255


container[76].bin= 0
container[76].i= 110
container[76].j= 402
container[76].angle= 0
container[76].value= 255


container[77].bin= 36
container[77].i= 110
container[77].j= 409
container[77].angle= 180
container[77].value= 255


container[78].bin= 5
container[78].i= 111
container[78].j= 402
container[78].angle= 26
container[78].value= 255


container[79].bin= 36
container[79].i= 111
container[79].j= 409
container[79].angle= 180
container[79].value= 255


container[80].bin= 5
container[80].i= 112
container[80].j= 402
container[80].angle= 26
container[80].value= 255


container[81].bin= 36
container[81].i= 112
container[81].j= 409
container[81].angle= 180
container[81].value= 255


container[82].bin= 0
container[82].i= 113
container[82].j= 401
container[82].angle= 0
container[82].value= 255


container[83].bin= 36
container[83].i= 113
container[83].j= 409
container[83].angle= 180
container[83].value= 255


container[84].bin= 0
container[84].i= 114
container[84].j= 401
container[84].angle= 0
container[84].value= 255


container[85].bin= 36
container[85].i= 114
container[85].j= 409
container[85].angle= 180
container[85].value= 255


container[86].bin= 0
container[86].i= 115
container[86].j= 401
container[86].angle= 0
container[86].value= 255


container[87].bin= 36
container[87].i= 115
container[87].j= 409
container[87].angle= 180
container[87].value= 255


container[88].bin= 0
container[88].i= 116
container[88].j= 401
container[88].angle= 0
container[88].value= 255


container[89].bin= 36
container[89].i= 116
container[89].j= 409
container[89].angle= 180
container[89].value= 255


container[90].bin= 66
container[90].i= 117
container[90].j= 402
container[90].angle= 333
container[90].value= 255


container[91].bin= 36
container[91].i= 117
container[91].j= 409
container[91].angle= 180
container[91].value= 255


container[92].bin= 66
container[92].i= 118
container[92].j= 402
container[92].angle= 333
container[92].value= 255


container[93].bin= 36
container[93].i= 118
container[93].j= 409
container[93].angle= 180
container[93].value= 255


container[94].bin= 0
container[94].i= 119
container[94].j= 402
container[94].angle= 0
container[94].value= 255


container[95].bin= 36
container[95].i= 119
container[95].j= 409
container[95].angle= 180
container[95].value= 255


container[96].bin= 0
container[96].i= 120
container[96].j= 402
container[96].angle= 0
container[96].value= 255


container[97].bin= 36
container[97].i= 120
container[97].j= 409
container[97].angle= 180
container[97].value= 255


container[98].bin= 0
container[98].i= 121
container[98].j= 402
container[98].angle= 0
container[98].value= 255


container[99].bin= 36
container[99].i= 121
container[99].j= 409
container[99].angle= 180
container[99].value= 255


container[100].bin= 0
container[100].i= 122
container[100].j= 402
container[100].angle= 0
container[100].value= 255


container[101].bin= 36
container[101].i= 122
container[101].j= 409
container[101].angle= 180
container[101].value= 255


container[102].bin= 63
container[102].i= 123
container[102].j= 403
container[102].angle= 315
container[102].value= 255


container[103].bin= 54
container[103].i= 123
container[103].j= 404
container[103].angle= 270
container[103].value= 255


container[104].bin= 54
container[104].i= 123
container[104].j= 405
container[104].angle= 270
container[104].value= 255


container[105].bin= 36
container[105].i= 123
container[105].j= 409
container[105].angle= 180
container[105].value= 255


container[106].bin= 63
container[106].i= 124
container[106].j= 406
container[106].angle= 315
container[106].value= 255


container[107].bin= 50
container[107].i= 124
container[107].j= 408
container[107].angle= 251
container[107].value= 255


container[108].bin= 44
container[108].i= 124
container[108].j= 409
container[108].angle= 224
container[108].value= 255


container[109].bin= 0
container[109].i= 125
container[109].j= 406
container[109].angle= 0
container[109].value= 255


container[110].bin= 0
container[110].i= 126
container[110].j= 406
container[110].angle= 0
container[110].value= 255


container[111].bin= 21
container[111].i= 126
container[111].j= 408
container[111].angle= 108
container[111].value= 255


container[112].bin= 27
container[112].i= 126
container[112].j= 409
container[112].angle= 135
container[112].value= 255


container[113].bin= 0
container[113].i= 127
container[113].j= 406
container[113].angle= 0
container[113].value= 255


container[114].bin= 36
container[114].i= 127
container[114].j= 409
container[114].angle= 180
container[114].value= 255


container[115].bin= 0
container[115].i= 128
container[115].j= 406
container[115].angle= 0
container[115].value= 255


container[116].bin= 36
container[116].i= 128
container[116].j= 409
container[116].angle= 180
container[116].value= 255


container[117].bin= 63
container[117].i= 129
container[117].j= 407
container[117].angle= 315
container[117].value= 255


container[118].bin= 54
container[118].i= 129
container[118].j= 408
container[118].angle= 270
container[118].value= 255


container[119].bin= 44
container[119].i= 129
container[119].j= 409
container[119].angle= 224
container[119].value= 255


