container[0].bin= 8
container[0].i= 106
container[0].j= 180
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 106
container[1].j= 181
container[1].angle= 90
container[1].value= 255


container[2].bin= 23
container[2].i= 106
container[2].j= 182
container[2].angle= 116
container[2].value= 255


container[3].bin= 8
container[3].i= 107
container[3].j= 179
container[3].angle= 44
container[3].value= 255


container[4].bin= 8
container[4].i= 107
container[4].j= 180
container[4].angle= 44
container[4].value= 255


container[5].bin= 23
container[5].i= 107
container[5].j= 183
container[5].angle= 116
container[5].value= 255


container[6].bin= 23
container[6].i= 107
container[6].j= 184
container[6].angle= 116
container[6].value= 255


container[7].bin= 0
container[7].i= 108
container[7].j= 179
container[7].angle= 0
container[7].value= 255


container[8].bin= 23
container[8].i= 108
container[8].j= 185
container[8].angle= 116
container[8].value= 255


container[9].bin= 27
container[9].i= 108
container[9].j= 186
container[9].angle= 135
container[9].value= 255


container[10].bin= 66
container[10].i= 109
container[10].j= 179
container[10].angle= 333
container[10].value= 255


container[11].bin= 27
container[11].i= 109
container[11].j= 186
container[11].angle= 135
container[11].value= 255


container[12].bin= 27
container[12].i= 109
container[12].j= 187
container[12].angle= 135
container[12].value= 255


container[13].bin= 66
container[13].i= 110
container[13].j= 180
container[13].angle= 333
container[13].value= 255


container[14].bin= 27
container[14].i= 110
container[14].j= 187
container[14].angle= 135
container[14].value= 255


container[15].bin= 27
container[15].i= 110
container[15].j= 188
container[15].angle= 135
container[15].value= 255


container[16].bin= 66
container[16].i= 111
container[16].j= 180
container[16].angle= 333
container[16].value= 255


container[17].bin= 30
container[17].i= 111
container[17].j= 188
container[17].angle= 153
container[17].value= 255


container[18].bin= 66
container[18].i= 112
container[18].j= 181
container[18].angle= 333
container[18].value= 255


container[19].bin= 30
container[19].i= 112
container[19].j= 189
container[19].angle= 153
container[19].value= 255


container[20].bin= 63
container[20].i= 113
container[20].j= 181
container[20].angle= 315
container[20].value= 255


container[21].bin= 63
container[21].i= 113
container[21].j= 182
container[21].angle= 315
container[21].value= 255


container[22].bin= 30
container[22].i= 113
container[22].j= 189
container[22].angle= 153
container[22].value= 255


container[23].bin= 63
container[23].i= 114
container[23].j= 182
container[23].angle= 315
container[23].value= 255


container[24].bin= 63
container[24].i= 114
container[24].j= 183
container[24].angle= 315
container[24].value= 255


container[25].bin= 36
container[25].i= 114
container[25].j= 189
container[25].angle= 180
container[25].value= 255


container[26].bin= 63
container[26].i= 115
container[26].j= 183
container[26].angle= 315
container[26].value= 255


container[27].bin= 63
container[27].i= 115
container[27].j= 184
container[27].angle= 315
container[27].value= 255


container[28].bin= 30
container[28].i= 115
container[28].j= 190
container[28].angle= 153
container[28].value= 255


container[29].bin= 63
container[29].i= 116
container[29].j= 184
container[29].angle= 315
container[29].value= 255


container[30].bin= 63
container[30].i= 116
container[30].j= 185
container[30].angle= 315
container[30].value= 255


container[31].bin= 27
container[31].i= 116
container[31].j= 190
container[31].angle= 135
container[31].value= 255


container[32].bin= 27
container[32].i= 116
container[32].j= 191
container[32].angle= 135
container[32].value= 255


container[33].bin= 66
container[33].i= 117
container[33].j= 185
container[33].angle= 333
container[33].value= 255


container[34].bin= 30
container[34].i= 117
container[34].j= 191
container[34].angle= 153
container[34].value= 255


container[35].bin= 63
container[35].i= 118
container[35].j= 186
container[35].angle= 315
container[35].value= 255


container[36].bin= 30
container[36].i= 118
container[36].j= 192
container[36].angle= 153
container[36].value= 255


container[37].bin= 59
container[37].i= 119
container[37].j= 187
container[37].angle= 296
container[37].value= 255


container[38].bin= 63
container[38].i= 119
container[38].j= 188
container[38].angle= 315
container[38].value= 255


container[39].bin= 27
container[39].i= 119
container[39].j= 192
container[39].angle= 135
container[39].value= 255


container[40].bin= 27
container[40].i= 119
container[40].j= 193
container[40].angle= 135
container[40].value= 255


container[41].bin= 63
container[41].i= 120
container[41].j= 188
container[41].angle= 315
container[41].value= 255


container[42].bin= 59
container[42].i= 120
container[42].j= 189
container[42].angle= 296
container[42].value= 255


container[43].bin= 30
container[43].i= 120
container[43].j= 193
container[43].angle= 153
container[43].value= 255


container[44].bin= 59
container[44].i= 121
container[44].j= 190
container[44].angle= 296
container[44].value= 255


container[45].bin= 63
container[45].i= 121
container[45].j= 191
container[45].angle= 315
container[45].value= 255


container[46].bin= 30
container[46].i= 121
container[46].j= 194
container[46].angle= 153
container[46].value= 255


container[47].bin= 63
container[47].i= 122
container[47].j= 191
container[47].angle= 315
container[47].value= 255


container[48].bin= 63
container[48].i= 122
container[48].j= 192
container[48].angle= 315
container[48].value= 255


container[49].bin= 23
container[49].i= 122
container[49].j= 195
container[49].angle= 116
container[49].value= 255


container[50].bin= 63
container[50].i= 123
container[50].j= 192
container[50].angle= 315
container[50].value= 255


container[51].bin= 23
container[51].i= 123
container[51].j= 196
container[51].angle= 116
container[51].value= 255


container[52].bin= 23
container[52].i= 123
container[52].j= 197
container[52].angle= 116
container[52].value= 255


container[53].bin= 63
container[53].i= 124
container[53].j= 193
container[53].angle= 315
container[53].value= 255


container[54].bin= 63
container[54].i= 124
container[54].j= 194
container[54].angle= 315
container[54].value= 255


container[55].bin= 23
container[55].i= 124
container[55].j= 198
container[55].angle= 116
container[55].value= 255


container[56].bin= 23
container[56].i= 124
container[56].j= 199
container[56].angle= 116
container[56].value= 255


container[57].bin= 66
container[57].i= 125
container[57].j= 194
container[57].angle= 333
container[57].value= 255


container[58].bin= 23
container[58].i= 125
container[58].j= 200
container[58].angle= 116
container[58].value= 255


container[59].bin= 27
container[59].i= 125
container[59].j= 201
container[59].angle= 135
container[59].value= 255


container[60].bin= 66
container[60].i= 126
container[60].j= 195
container[60].angle= 333
container[60].value= 255


container[61].bin= 30
container[61].i= 126
container[61].j= 201
container[61].angle= 153
container[61].value= 255


container[62].bin= 66
container[62].i= 127
container[62].j= 195
container[62].angle= 333
container[62].value= 255


container[63].bin= 36
container[63].i= 127
container[63].j= 201
container[63].angle= 180
container[63].value= 255


container[64].bin= 66
container[64].i= 128
container[64].j= 196
container[64].angle= 333
container[64].value= 255


container[65].bin= 30
container[65].i= 128
container[65].j= 202
container[65].angle= 153
container[65].value= 255


container[66].bin= 66
container[66].i= 129
container[66].j= 196
container[66].angle= 333
container[66].value= 255


container[67].bin= 30
container[67].i= 129
container[67].j= 202
container[67].angle= 153
container[67].value= 255


container[68].bin= 66
container[68].i= 130
container[68].j= 197
container[68].angle= 333
container[68].value= 255


container[69].bin= 44
container[69].i= 130
container[69].j= 202
container[69].angle= 224
container[69].value= 255


container[70].bin= 63
container[70].i= 131
container[70].j= 197
container[70].angle= 315
container[70].value= 255


container[71].bin= 59
container[71].i= 131
container[71].j= 198
container[71].angle= 296
container[71].value= 255


container[72].bin= 54
container[72].i= 131
container[72].j= 199
container[72].angle= 270
container[72].value= 255


container[73].bin= 48
container[73].i= 131
container[73].j= 200
container[73].angle= 243
container[73].value= 255


container[74].bin= 48
container[74].i= 131
container[74].j= 201
container[74].angle= 243
container[74].value= 255


