container[0].bin= 18
container[0].i= 360
container[0].j= 493
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 361
container[1].j= 492
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 361
container[2].j= 494
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 362
container[3].j= 492
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 362
container[4].j= 494
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 363
container[5].j= 492
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 363
container[6].j= 494
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 363
container[7].j= 495
container[7].angle= 90
container[7].value= 255


container[8].bin= 5
container[8].i= 364
container[8].j= 492
container[8].angle= 26
container[8].value= 255


container[9].bin= 27
container[9].i= 364
container[9].j= 496
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 365
container[10].j= 492
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 365
container[11].j= 496
container[11].angle= 180
container[11].value= 255


container[12].bin= 0
container[12].i= 366
container[12].j= 492
container[12].angle= 0
container[12].value= 255


container[13].bin= 27
container[13].i= 366
container[13].j= 497
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 366
container[14].j= 498
container[14].angle= 90
container[14].value= 255


container[15].bin= 5
container[15].i= 367
container[15].j= 492
container[15].angle= 26
container[15].value= 255


container[16].bin= 27
container[16].i= 367
container[16].j= 499
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 368
container[17].j= 491
container[17].angle= 0
container[17].value= 255


container[18].bin= 27
container[18].i= 368
container[18].j= 500
container[18].angle= 135
container[18].value= 255


container[19].bin= 66
container[19].i= 369
container[19].j= 492
container[19].angle= 333
container[19].value= 255


container[20].bin= 27
container[20].i= 369
container[20].j= 501
container[20].angle= 135
container[20].value= 255


container[21].bin= 0
container[21].i= 370
container[21].j= 492
container[21].angle= 0
container[21].value= 255


container[22].bin= 36
container[22].i= 370
container[22].j= 501
container[22].angle= 180
container[22].value= 255


container[23].bin= 0
container[23].i= 371
container[23].j= 492
container[23].angle= 0
container[23].value= 255


container[24].bin= 36
container[24].i= 371
container[24].j= 501
container[24].angle= 180
container[24].value= 255


container[25].bin= 63
container[25].i= 372
container[25].j= 492
container[25].angle= 315
container[25].value= 255


container[26].bin= 59
container[26].i= 372
container[26].j= 493
container[26].angle= 296
container[26].value= 255


container[27].bin= 36
container[27].i= 372
container[27].j= 501
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 373
container[28].j= 494
container[28].angle= 315
container[28].value= 255


container[29].bin= 36
container[29].i= 373
container[29].j= 501
container[29].angle= 180
container[29].value= 255


container[30].bin= 0
container[30].i= 374
container[30].j= 494
container[30].angle= 0
container[30].value= 255


container[31].bin= 36
container[31].i= 374
container[31].j= 501
container[31].angle= 180
container[31].value= 255


container[32].bin= 63
container[32].i= 375
container[32].j= 495
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 375
container[33].j= 496
container[33].angle= 270
container[33].value= 255


container[34].bin= 27
container[34].i= 375
container[34].j= 502
container[34].angle= 135
container[34].value= 255


container[35].bin= 18
container[35].i= 375
container[35].j= 503
container[35].angle= 90
container[35].value= 255


container[36].bin= 63
container[36].i= 376
container[36].j= 497
container[36].angle= 315
container[36].value= 255


container[37].bin= 27
container[37].i= 376
container[37].j= 504
container[37].angle= 135
container[37].value= 255


container[38].bin= 0
container[38].i= 377
container[38].j= 497
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 377
container[39].j= 504
container[39].angle= 180
container[39].value= 255


container[40].bin= 0
container[40].i= 378
container[40].j= 497
container[40].angle= 0
container[40].value= 255


container[41].bin= 36
container[41].i= 378
container[41].j= 504
container[41].angle= 180
container[41].value= 255


container[42].bin= 0
container[42].i= 379
container[42].j= 497
container[42].angle= 0
container[42].value= 255


container[43].bin= 36
container[43].i= 379
container[43].j= 504
container[43].angle= 180
container[43].value= 255


container[44].bin= 0
container[44].i= 380
container[44].j= 497
container[44].angle= 0
container[44].value= 255


container[45].bin= 36
container[45].i= 380
container[45].j= 504
container[45].angle= 180
container[45].value= 255


container[46].bin= 63
container[46].i= 381
container[46].j= 498
container[46].angle= 315
container[46].value= 255


container[47].bin= 54
container[47].i= 381
container[47].j= 499
container[47].angle= 270
container[47].value= 255


container[48].bin= 54
container[48].i= 381
container[48].j= 500
container[48].angle= 270
container[48].value= 255


container[49].bin= 54
container[49].i= 381
container[49].j= 501
container[49].angle= 270
container[49].value= 255


container[50].bin= 54
container[50].i= 381
container[50].j= 502
container[50].angle= 270
container[50].value= 255


container[51].bin= 54
container[51].i= 381
container[51].j= 503
container[51].angle= 270
container[51].value= 255


container[52].bin= 44
container[52].i= 381
container[52].j= 504
container[52].angle= 224
container[52].value= 255


