container[0].bin= 14
container[0].i= 411
container[0].j= 438
container[0].angle= 71
container[0].value= 255


container[1].bin= 12
container[1].i= 411
container[1].j= 439
container[1].angle= 63
container[1].value= 255


container[2].bin= 12
container[2].i= 411
container[2].j= 440
container[2].angle= 63
container[2].value= 255


container[3].bin= 23
container[3].i= 411
container[3].j= 441
container[3].angle= 116
container[3].value= 255


container[4].bin= 23
container[4].i= 411
container[4].j= 442
container[4].angle= 116
container[4].value= 255


container[5].bin= 3
container[5].i= 412
container[5].j= 438
container[5].angle= 18
container[5].value= 255


container[6].bin= 23
container[6].i= 412
container[6].j= 443
container[6].angle= 116
container[6].value= 255


container[7].bin= 27
container[7].i= 412
container[7].j= 444
container[7].angle= 135
container[7].value= 255


container[8].bin= 66
container[8].i= 413
container[8].j= 438
container[8].angle= 333
container[8].value= 255


container[9].bin= 36
container[9].i= 413
container[9].j= 444
container[9].angle= 180
container[9].value= 255


container[10].bin= 66
container[10].i= 414
container[10].j= 439
container[10].angle= 333
container[10].value= 255


container[11].bin= 32
container[11].i= 414
container[11].j= 444
container[11].angle= 161
container[11].value= 255


container[12].bin= 21
container[12].i= 414
container[12].j= 445
container[12].angle= 108
container[12].value= 255


container[13].bin= 18
container[13].i= 414
container[13].j= 446
container[13].angle= 90
container[13].value= 255


container[14].bin= 18
container[14].i= 414
container[14].j= 447
container[14].angle= 90
container[14].value= 255


container[15].bin= 66
container[15].i= 415
container[15].j= 439
container[15].angle= 333
container[15].value= 255


container[16].bin= 23
container[16].i= 415
container[16].j= 448
container[16].angle= 116
container[16].value= 255


container[17].bin= 18
container[17].i= 415
container[17].j= 449
container[17].angle= 90
container[17].value= 255


container[18].bin= 21
container[18].i= 415
container[18].j= 450
container[18].angle= 108
container[18].value= 255


container[19].bin= 5
container[19].i= 416
container[19].j= 439
container[19].angle= 26
container[19].value= 255


container[20].bin= 30
container[20].i= 416
container[20].j= 451
container[20].angle= 153
container[20].value= 255


container[21].bin= 68
container[21].i= 417
container[21].j= 439
container[21].angle= 341
container[21].value= 255


container[22].bin= 54
container[22].i= 417
container[22].j= 441
container[22].angle= 270
container[22].value= 255


container[23].bin= 57
container[23].i= 417
container[23].j= 442
container[23].angle= 288
container[23].value= 255


container[24].bin= 30
container[24].i= 417
container[24].j= 451
container[24].angle= 153
container[24].value= 255


container[25].bin= 36
container[25].i= 418
container[25].j= 451
container[25].angle= 180
container[25].value= 255


container[26].bin= 5
container[26].i= 419
container[26].j= 442
container[26].angle= 26
container[26].value= 255


container[27].bin= 36
container[27].i= 419
container[27].j= 451
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 420
container[28].j= 442
container[28].angle= 315
container[28].value= 255


container[29].bin= 54
container[29].i= 420
container[29].j= 443
container[29].angle= 270
container[29].value= 255


container[30].bin= 54
container[30].i= 420
container[30].j= 445
container[30].angle= 270
container[30].value= 255


container[31].bin= 54
container[31].i= 420
container[31].j= 447
container[31].angle= 270
container[31].value= 255


container[32].bin= 54
container[32].i= 420
container[32].j= 448
container[32].angle= 270
container[32].value= 255


container[33].bin= 54
container[33].i= 420
container[33].j= 449
container[33].angle= 270
container[33].value= 255


container[34].bin= 54
container[34].i= 420
container[34].j= 450
container[34].angle= 270
container[34].value= 255


container[35].bin= 44
container[35].i= 420
container[35].j= 451
container[35].angle= 224
container[35].value= 255


container[36].bin= 63
container[36].i= 421
container[36].j= 444
container[36].angle= 315
container[36].value= 255


container[37].bin= 44
container[37].i= 421
container[37].j= 446
container[37].angle= 224
container[37].value= 255


container[38].bin= 0
container[38].i= 422
container[38].j= 444
container[38].angle= 0
container[38].value= 255


container[39].bin= 36
container[39].i= 422
container[39].j= 446
container[39].angle= 180
container[39].value= 255


container[40].bin= 68
container[40].i= 423
container[40].j= 444
container[40].angle= 341
container[40].value= 255


container[41].bin= 54
container[41].i= 423
container[41].j= 445
container[41].angle= 270
container[41].value= 255


container[42].bin= 39
container[42].i= 423
container[42].j= 446
container[42].angle= 198
container[42].value= 255


