container[0].bin= 8
container[0].i= 267
container[0].j= 192
container[0].angle= 44
container[0].value= 255


container[1].bin= 23
container[1].i= 267
container[1].j= 193
container[1].angle= 116
container[1].value= 255


container[2].bin= 27
container[2].i= 267
container[2].j= 194
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 268
container[3].j= 191
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 268
container[4].j= 194
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 269
container[5].j= 191
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 269
container[6].j= 195
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 270
container[7].j= 191
container[7].angle= 0
container[7].value= 255


container[8].bin= 30
container[8].i= 270
container[8].j= 195
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 271
container[9].j= 191
container[9].angle= 0
container[9].value= 255


container[10].bin= 30
container[10].i= 271
container[10].j= 196
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 272
container[11].j= 191
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 272
container[12].j= 196
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 273
container[13].j= 191
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 273
container[14].j= 197
container[14].angle= 153
container[14].value= 255


container[15].bin= 0
container[15].i= 274
container[15].j= 191
container[15].angle= 0
container[15].value= 255


container[16].bin= 30
container[16].i= 274
container[16].j= 197
container[16].angle= 153
container[16].value= 255


container[17].bin= 66
container[17].i= 275
container[17].j= 192
container[17].angle= 333
container[17].value= 255


container[18].bin= 41
container[18].i= 275
container[18].j= 197
container[18].angle= 206
container[18].value= 255


container[19].bin= 66
container[19].i= 276
container[19].j= 192
container[19].angle= 333
container[19].value= 255


container[20].bin= 44
container[20].i= 276
container[20].j= 196
container[20].angle= 224
container[20].value= 255


container[21].bin= 44
container[21].i= 276
container[21].j= 197
container[21].angle= 224
container[21].value= 255


container[22].bin= 63
container[22].i= 277
container[22].j= 193
container[22].angle= 315
container[22].value= 255


container[23].bin= 54
container[23].i= 277
container[23].j= 194
container[23].angle= 270
container[23].value= 255


container[24].bin= 48
container[24].i= 277
container[24].j= 195
container[24].angle= 243
container[24].value= 255


container[25].bin= 44
container[25].i= 277
container[25].j= 196
container[25].angle= 224
container[25].value= 255


