container[0].bin= 18
container[0].i= 315
container[0].j= 436
container[0].angle= 90
container[0].value= 255


container[1].bin= 8
container[1].i= 316
container[1].j= 435
container[1].angle= 44
container[1].value= 255


container[2].bin= 27
container[2].i= 316
container[2].j= 437
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 317
container[3].j= 434
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 317
container[4].j= 437
container[4].angle= 180
container[4].value= 255


container[5].bin= 0
container[5].i= 318
container[5].j= 434
container[5].angle= 0
container[5].value= 255


container[6].bin= 27
container[6].i= 318
container[6].j= 438
container[6].angle= 135
container[6].value= 255


container[7].bin= 18
container[7].i= 318
container[7].j= 439
container[7].angle= 90
container[7].value= 255


container[8].bin= 0
container[8].i= 319
container[8].j= 434
container[8].angle= 0
container[8].value= 255


container[9].bin= 27
container[9].i= 319
container[9].j= 440
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 320
container[10].j= 434
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 320
container[11].j= 440
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 321
container[12].j= 435
container[12].angle= 315
container[12].value= 255


container[13].bin= 54
container[13].i= 321
container[13].j= 437
container[13].angle= 270
container[13].value= 255


container[14].bin= 54
container[14].i= 321
container[14].j= 439
container[14].angle= 270
container[14].value= 255


container[15].bin= 44
container[15].i= 321
container[15].j= 440
container[15].angle= 224
container[15].value= 255


container[16].bin= 63
container[16].i= 322
container[16].j= 436
container[16].angle= 315
container[16].value= 255


container[17].bin= 44
container[17].i= 322
container[17].j= 438
container[17].angle= 224
container[17].value= 255


container[18].bin= 0
container[18].i= 323
container[18].j= 436
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 323
container[19].j= 438
container[19].angle= 180
container[19].value= 255


container[20].bin= 68
container[20].i= 324
container[20].j= 436
container[20].angle= 341
container[20].value= 255


container[21].bin= 54
container[21].i= 324
container[21].j= 437
container[21].angle= 270
container[21].value= 255


container[22].bin= 39
container[22].i= 324
container[22].j= 438
container[22].angle= 198
container[22].value= 255


