container[0].bin= 18
container[0].i= 905
container[0].j= 406
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 906
container[1].j= 405
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 906
container[2].j= 407
container[2].angle= 161
container[2].value= 255


container[3].bin= 5
container[3].i= 907
container[3].j= 405
container[3].angle= 26
container[3].value= 255


container[4].bin= 30
container[4].i= 907
container[4].j= 407
container[4].angle= 153
container[4].value= 255


container[5].bin= 5
container[5].i= 908
container[5].j= 405
container[5].angle= 26
container[5].value= 255


container[6].bin= 30
container[6].i= 908
container[6].j= 407
container[6].angle= 153
container[6].value= 255


container[7].bin= 0
container[7].i= 909
container[7].j= 404
container[7].angle= 0
container[7].value= 255


container[8].bin= 36
container[8].i= 909
container[8].j= 407
container[8].angle= 180
container[8].value= 255


container[9].bin= 0
container[9].i= 910
container[9].j= 404
container[9].angle= 0
container[9].value= 255


container[10].bin= 39
container[10].i= 910
container[10].j= 407
container[10].angle= 198
container[10].value= 255


container[11].bin= 21
container[11].i= 910
container[11].j= 409
container[11].angle= 108
container[11].value= 255


container[12].bin= 63
container[12].i= 911
container[12].j= 405
container[12].angle= 315
container[12].value= 255


container[13].bin= 50
container[13].i= 911
container[13].j= 406
container[13].angle= 251
container[13].value= 255


container[14].bin= 63
container[14].i= 912
container[14].j= 406
container[14].angle= 315
container[14].value= 255


container[15].bin= 36
container[15].i= 912
container[15].j= 409
container[15].angle= 180
container[15].value= 255


container[16].bin= 0
container[16].i= 913
container[16].j= 406
container[16].angle= 0
container[16].value= 255


container[17].bin= 36
container[17].i= 913
container[17].j= 409
container[17].angle= 180
container[17].value= 255


container[18].bin= 0
container[18].i= 914
container[18].j= 406
container[18].angle= 0
container[18].value= 255


container[19].bin= 36
container[19].i= 914
container[19].j= 409
container[19].angle= 180
container[19].value= 255


