container[0].bin= 8
container[0].i= 656
container[0].j= 522
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 656
container[1].j= 523
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 657
container[2].j= 521
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 658
container[3].j= 521
container[3].angle= 0
container[3].value= 255


container[4].bin= 0
container[4].i= 659
container[4].j= 521
container[4].angle= 0
container[4].value= 255


container[5].bin= 0
container[5].i= 660
container[5].j= 521
container[5].angle= 0
container[5].value= 255


container[6].bin= 63
container[6].i= 661
container[6].j= 522
container[6].angle= 315
container[6].value= 255


container[7].bin= 44
container[7].i= 661
container[7].j= 523
container[7].angle= 224
container[7].value= 255


