container[0].bin= 8
container[0].i= 276
container[0].j= 77
container[0].angle= 44
container[0].value= 255


container[1].bin= 27
container[1].i= 276
container[1].j= 78
container[1].angle= 135
container[1].value= 255


container[2].bin= 0
container[2].i= 277
container[2].j= 76
container[2].angle= 0
container[2].value= 255


container[3].bin= 0
container[3].i= 278
container[3].j= 76
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 278
container[4].j= 79
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 279
container[5].j= 76
container[5].angle= 0
container[5].value= 255


container[6].bin= 30
container[6].i= 279
container[6].j= 79
container[6].angle= 153
container[6].value= 255


container[7].bin= 5
container[7].i= 280
container[7].j= 76
container[7].angle= 26
container[7].value= 255


container[8].bin= 36
container[8].i= 280
container[8].j= 79
container[8].angle= 180
container[8].value= 255


container[9].bin= 5
container[9].i= 281
container[9].j= 76
container[9].angle= 26
container[9].value= 255


container[10].bin= 30
container[10].i= 281
container[10].j= 80
container[10].angle= 153
container[10].value= 255


container[11].bin= 0
container[11].i= 282
container[11].j= 75
container[11].angle= 0
container[11].value= 255


container[12].bin= 30
container[12].i= 282
container[12].j= 80
container[12].angle= 153
container[12].value= 255


container[13].bin= 0
container[13].i= 283
container[13].j= 75
container[13].angle= 0
container[13].value= 255


container[14].bin= 30
container[14].i= 283
container[14].j= 81
container[14].angle= 153
container[14].value= 255


container[15].bin= 5
container[15].i= 284
container[15].j= 75
container[15].angle= 26
container[15].value= 255


container[16].bin= 30
container[16].i= 284
container[16].j= 81
container[16].angle= 153
container[16].value= 255


container[17].bin= 5
container[17].i= 285
container[17].j= 75
container[17].angle= 26
container[17].value= 255


container[18].bin= 30
container[18].i= 285
container[18].j= 82
container[18].angle= 153
container[18].value= 255


container[19].bin= 0
container[19].i= 286
container[19].j= 74
container[19].angle= 0
container[19].value= 255


container[20].bin= 30
container[20].i= 286
container[20].j= 82
container[20].angle= 153
container[20].value= 255


container[21].bin= 0
container[21].i= 287
container[21].j= 74
container[21].angle= 0
container[21].value= 255


container[22].bin= 30
container[22].i= 287
container[22].j= 83
container[22].angle= 153
container[22].value= 255


container[23].bin= 66
container[23].i= 288
container[23].j= 75
container[23].angle= 333
container[23].value= 255


container[24].bin= 30
container[24].i= 288
container[24].j= 83
container[24].angle= 153
container[24].value= 255


container[25].bin= 63
container[25].i= 289
container[25].j= 75
container[25].angle= 315
container[25].value= 255


container[26].bin= 63
container[26].i= 289
container[26].j= 76
container[26].angle= 315
container[26].value= 255


container[27].bin= 36
container[27].i= 289
container[27].j= 83
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 290
container[28].j= 76
container[28].angle= 315
container[28].value= 255


container[29].bin= 63
container[29].i= 290
container[29].j= 77
container[29].angle= 315
container[29].value= 255


container[30].bin= 36
container[30].i= 290
container[30].j= 83
container[30].angle= 180
container[30].value= 255


container[31].bin= 63
container[31].i= 291
container[31].j= 77
container[31].angle= 315
container[31].value= 255


container[32].bin= 63
container[32].i= 291
container[32].j= 78
container[32].angle= 315
container[32].value= 255


container[33].bin= 54
container[33].i= 291
container[33].j= 81
container[33].angle= 270
container[33].value= 255


container[34].bin= 54
container[34].i= 291
container[34].j= 82
container[34].angle= 270
container[34].value= 255


container[35].bin= 44
container[35].i= 291
container[35].j= 83
container[35].angle= 224
container[35].value= 255


container[36].bin= 63
container[36].i= 292
container[36].j= 78
container[36].angle= 315
container[36].value= 255


container[37].bin= 54
container[37].i= 292
container[37].j= 79
container[37].angle= 270
container[37].value= 255


container[38].bin= 48
container[38].i= 292
container[38].j= 80
container[38].angle= 243
container[38].value= 255


