container[0].bin= 3
container[0].i= 353
container[0].j= 486
container[0].angle= 18
container[0].value= 255


container[1].bin= 14
container[1].i= 353
container[1].j= 487
container[1].angle= 71
container[1].value= 255


container[2].bin= 27
container[2].i= 353
container[2].j= 488
container[2].angle= 135
container[2].value= 255


container[3].bin= 0
container[3].i= 354
container[3].j= 486
container[3].angle= 0
container[3].value= 255


container[4].bin= 30
container[4].i= 354
container[4].j= 488
container[4].angle= 153
container[4].value= 255


container[5].bin= 0
container[5].i= 355
container[5].j= 486
container[5].angle= 0
container[5].value= 255


container[6].bin= 0
container[6].i= 356
container[6].j= 486
container[6].angle= 0
container[6].value= 255


container[7].bin= 63
container[7].i= 357
container[7].j= 487
container[7].angle= 315
container[7].value= 255


container[8].bin= 44
container[8].i= 357
container[8].j= 488
container[8].angle= 224
container[8].value= 255


