container[0].bin= 18
container[0].i= 417
container[0].j= 481
container[0].angle= 90
container[0].value= 255


container[1].bin= 18
container[1].i= 417
container[1].j= 482
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 417
container[2].j= 483
container[2].angle= 90
container[2].value= 255


container[3].bin= 14
container[3].i= 417
container[3].j= 486
container[3].angle= 71
container[3].value= 255


container[4].bin= 18
container[4].i= 417
container[4].j= 487
container[4].angle= 90
container[4].value= 255


container[5].bin= 21
container[5].i= 417
container[5].j= 488
container[5].angle= 108
container[5].value= 255


container[6].bin= 8
container[6].i= 418
container[6].j= 480
container[6].angle= 44
container[6].value= 255


container[7].bin= 23
container[7].i= 418
container[7].j= 484
container[7].angle= 116
container[7].value= 255


container[8].bin= 18
container[8].i= 418
container[8].j= 485
container[8].angle= 90
container[8].value= 255


container[9].bin= 27
container[9].i= 418
container[9].j= 488
container[9].angle= 135
container[9].value= 255


container[10].bin= 0
container[10].i= 419
container[10].j= 479
container[10].angle= 0
container[10].value= 255


container[11].bin= 36
container[11].i= 419
container[11].j= 489
container[11].angle= 180
container[11].value= 255


container[12].bin= 63
container[12].i= 420
container[12].j= 480
container[12].angle= 315
container[12].value= 255


container[13].bin= 27
container[13].i= 420
container[13].j= 486
container[13].angle= 135
container[13].value= 255


container[14].bin= 18
container[14].i= 420
container[14].j= 487
container[14].angle= 90
container[14].value= 255


container[15].bin= 27
container[15].i= 420
container[15].j= 489
container[15].angle= 135
container[15].value= 255


container[16].bin= 59
container[16].i= 421
container[16].j= 481
container[16].angle= 296
container[16].value= 255


container[17].bin= 59
container[17].i= 421
container[17].j= 482
container[17].angle= 296
container[17].value= 255


container[18].bin= 27
container[18].i= 421
container[18].j= 490
container[18].angle= 135
container[18].value= 255


container[19].bin= 63
container[19].i= 422
container[19].j= 483
container[19].angle= 315
container[19].value= 255


container[20].bin= 36
container[20].i= 422
container[20].j= 490
container[20].angle= 180
container[20].value= 255


container[21].bin= 66
container[21].i= 423
container[21].j= 484
container[21].angle= 333
container[21].value= 255


container[22].bin= 27
container[22].i= 423
container[22].j= 491
container[22].angle= 135
container[22].value= 255


container[23].bin= 12
container[23].i= 423
container[23].j= 492
container[23].angle= 63
container[23].value= 255


container[24].bin= 21
container[24].i= 423
container[24].j= 493
container[24].angle= 108
container[24].value= 255


container[25].bin= 66
container[25].i= 424
container[25].j= 484
container[25].angle= 333
container[25].value= 255


container[26].bin= 0
container[26].i= 425
container[26].j= 484
container[26].angle= 0
container[26].value= 255


container[27].bin= 36
container[27].i= 425
container[27].j= 493
container[27].angle= 180
container[27].value= 255


container[28].bin= 63
container[28].i= 426
container[28].j= 485
container[28].angle= 315
container[28].value= 255


container[29].bin= 44
container[29].i= 426
container[29].j= 493
container[29].angle= 224
container[29].value= 255


container[30].bin= 59
container[30].i= 427
container[30].j= 486
container[30].angle= 296
container[30].value= 255


container[31].bin= 63
container[31].i= 427
container[31].j= 487
container[31].angle= 315
container[31].value= 255


container[32].bin= 44
container[32].i= 427
container[32].j= 492
container[32].angle= 224
container[32].value= 255


container[33].bin= 66
container[33].i= 428
container[33].j= 487
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 428
container[34].j= 491
container[34].angle= 180
container[34].value= 255


container[35].bin= 0
container[35].i= 429
container[35].j= 487
container[35].angle= 0
container[35].value= 255


container[36].bin= 41
container[36].i= 429
container[36].j= 491
container[36].angle= 206
container[36].value= 255


container[37].bin= 0
container[37].i= 430
container[37].j= 487
container[37].angle= 0
container[37].value= 255


container[38].bin= 41
container[38].i= 430
container[38].j= 491
container[38].angle= 206
container[38].value= 255


container[39].bin= 0
container[39].i= 431
container[39].j= 487
container[39].angle= 0
container[39].value= 255


container[40].bin= 36
container[40].i= 431
container[40].j= 490
container[40].angle= 180
container[40].value= 255


container[41].bin= 63
container[41].i= 432
container[41].j= 488
container[41].angle= 315
container[41].value= 255


container[42].bin= 54
container[42].i= 432
container[42].j= 489
container[42].angle= 270
container[42].value= 255


container[43].bin= 44
container[43].i= 432
container[43].j= 490
container[43].angle= 224
container[43].value= 255


