container[0].bin= 18
container[0].i= 90
container[0].j= 135
container[0].angle= 90
container[0].value= 255


container[1].bin= 3
container[1].i= 91
container[1].j= 134
container[1].angle= 18
container[1].value= 255


container[2].bin= 32
container[2].i= 91
container[2].j= 136
container[2].angle= 161
container[2].value= 255


container[3].bin= 0
container[3].i= 92
container[3].j= 134
container[3].angle= 0
container[3].value= 255


container[4].bin= 36
container[4].i= 92
container[4].j= 136
container[4].angle= 180
container[4].value= 255


container[5].bin= 5
container[5].i= 93
container[5].j= 134
container[5].angle= 26
container[5].value= 255


container[6].bin= 36
container[6].i= 93
container[6].j= 136
container[6].angle= 180
container[6].value= 255


container[7].bin= 5
container[7].i= 94
container[7].j= 134
container[7].angle= 26
container[7].value= 255


container[8].bin= 30
container[8].i= 94
container[8].j= 136
container[8].angle= 153
container[8].value= 255


container[9].bin= 0
container[9].i= 95
container[9].j= 133
container[9].angle= 0
container[9].value= 255


container[10].bin= 36
container[10].i= 95
container[10].j= 136
container[10].angle= 180
container[10].value= 255


container[11].bin= 66
container[11].i= 96
container[11].j= 134
container[11].angle= 333
container[11].value= 255


container[12].bin= 32
container[12].i= 96
container[12].j= 136
container[12].angle= 161
container[12].value= 255


container[13].bin= 21
container[13].i= 96
container[13].j= 137
container[13].angle= 108
container[13].value= 255


container[14].bin= 21
container[14].i= 96
container[14].j= 138
container[14].angle= 108
container[14].value= 255


container[15].bin= 66
container[15].i= 97
container[15].j= 134
container[15].angle= 333
container[15].value= 255


container[16].bin= 27
container[16].i= 97
container[16].j= 138
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 98
container[17].j= 134
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 98
container[18].j= 139
container[18].angle= 180
container[18].value= 255


container[19].bin= 0
container[19].i= 99
container[19].j= 134
container[19].angle= 0
container[19].value= 255


container[20].bin= 18
container[20].i= 99
container[20].j= 137
container[20].angle= 90
container[20].value= 255


container[21].bin= 27
container[21].i= 99
container[21].j= 139
container[21].angle= 135
container[21].value= 255


container[22].bin= 18
container[22].i= 99
container[22].j= 140
container[22].angle= 90
container[22].value= 255


container[23].bin= 0
container[23].i= 100
container[23].j= 134
container[23].angle= 0
container[23].value= 255


container[24].bin= 27
container[24].i= 100
container[24].j= 141
container[24].angle= 135
container[24].value= 255


container[25].bin= 0
container[25].i= 101
container[25].j= 134
container[25].angle= 0
container[25].value= 255


container[26].bin= 36
container[26].i= 101
container[26].j= 141
container[26].angle= 180
container[26].value= 255


container[27].bin= 63
container[27].i= 102
container[27].j= 135
container[27].angle= 315
container[27].value= 255


container[28].bin= 27
container[28].i= 102
container[28].j= 142
container[28].angle= 135
container[28].value= 255


container[29].bin= 63
container[29].i= 103
container[29].j= 136
container[29].angle= 315
container[29].value= 255


container[30].bin= 27
container[30].i= 103
container[30].j= 143
container[30].angle= 135
container[30].value= 255


container[31].bin= 0
container[31].i= 104
container[31].j= 136
container[31].angle= 0
container[31].value= 255


container[32].bin= 36
container[32].i= 104
container[32].j= 143
container[32].angle= 180
container[32].value= 255


container[33].bin= 66
container[33].i= 105
container[33].j= 137
container[33].angle= 333
container[33].value= 255


container[34].bin= 36
container[34].i= 105
container[34].j= 143
container[34].angle= 180
container[34].value= 255


container[35].bin= 66
container[35].i= 106
container[35].j= 137
container[35].angle= 333
container[35].value= 255


container[36].bin= 36
container[36].i= 106
container[36].j= 143
container[36].angle= 180
container[36].value= 255


container[37].bin= 0
container[37].i= 107
container[37].j= 137
container[37].angle= 0
container[37].value= 255


container[38].bin= 36
container[38].i= 107
container[38].j= 143
container[38].angle= 180
container[38].value= 255


container[39].bin= 63
container[39].i= 108
container[39].j= 138
container[39].angle= 315
container[39].value= 255


container[40].bin= 44
container[40].i= 108
container[40].j= 141
container[40].angle= 224
container[40].value= 255


container[41].bin= 54
container[41].i= 108
container[41].j= 142
container[41].angle= 270
container[41].value= 255


container[42].bin= 30
container[42].i= 108
container[42].j= 144
container[42].angle= 153
container[42].value= 255


container[43].bin= 63
container[43].i= 109
container[43].j= 139
container[43].angle= 315
container[43].value= 255


container[44].bin= 30
container[44].i= 109
container[44].j= 144
container[44].angle= 153
container[44].value= 255


container[45].bin= 63
container[45].i= 110
container[45].j= 140
container[45].angle= 315
container[45].value= 255


container[46].bin= 36
container[46].i= 110
container[46].j= 144
container[46].angle= 180
container[46].value= 255


container[47].bin= 59
container[47].i= 111
container[47].j= 141
container[47].angle= 296
container[47].value= 255


container[48].bin= 63
container[48].i= 111
container[48].j= 142
container[48].angle= 315
container[48].value= 255


container[49].bin= 41
container[49].i= 111
container[49].j= 144
container[49].angle= 206
container[49].value= 255


container[50].bin= 66
container[50].i= 112
container[50].j= 142
container[50].angle= 333
container[50].value= 255


container[51].bin= 41
container[51].i= 112
container[51].j= 144
container[51].angle= 206
container[51].value= 255


container[52].bin= 0
container[52].i= 113
container[52].j= 142
container[52].angle= 0
container[52].value= 255


container[53].bin= 36
container[53].i= 113
container[53].j= 144
container[53].angle= 180
container[53].value= 255


container[54].bin= 0
container[54].i= 114
container[54].j= 142
container[54].angle= 0
container[54].value= 255


container[55].bin= 27
container[55].i= 114
container[55].j= 144
container[55].angle= 135
container[55].value= 255


container[56].bin= 18
container[56].i= 114
container[56].j= 145
container[56].angle= 90
container[56].value= 255


container[57].bin= 0
container[57].i= 115
container[57].j= 142
container[57].angle= 0
container[57].value= 255


container[58].bin= 27
container[58].i= 115
container[58].j= 146
container[58].angle= 135
container[58].value= 255


container[59].bin= 0
container[59].i= 116
container[59].j= 142
container[59].angle= 0
container[59].value= 255


container[60].bin= 36
container[60].i= 116
container[60].j= 146
container[60].angle= 180
container[60].value= 255


container[61].bin= 63
container[61].i= 117
container[61].j= 143
container[61].angle= 315
container[61].value= 255


container[62].bin= 27
container[62].i= 117
container[62].j= 147
container[62].angle= 135
container[62].value= 255


container[63].bin= 8
container[63].i= 118
container[63].j= 137
container[63].angle= 44
container[63].value= 255


container[64].bin= 21
container[64].i= 118
container[64].j= 138
container[64].angle= 108
container[64].value= 255


container[65].bin= 27
container[65].i= 118
container[65].j= 139
container[65].angle= 135
container[65].value= 255


container[66].bin= 8
container[66].i= 118
container[66].j= 140
container[66].angle= 44
container[66].value= 255


container[67].bin= 21
container[67].i= 118
container[67].j= 141
container[67].angle= 108
container[67].value= 255


container[68].bin= 63
container[68].i= 118
container[68].j= 144
container[68].angle= 315
container[68].value= 255


container[69].bin= 27
container[69].i= 118
container[69].j= 148
container[69].angle= 135
container[69].value= 255


container[70].bin= 0
container[70].i= 119
container[70].j= 137
container[70].angle= 0
container[70].value= 255


container[71].bin= 36
container[71].i= 119
container[71].j= 142
container[71].angle= 180
container[71].value= 255


container[72].bin= 0
container[72].i= 119
container[72].j= 144
container[72].angle= 0
container[72].value= 255


container[73].bin= 36
container[73].i= 119
container[73].j= 148
container[73].angle= 180
container[73].value= 255


container[74].bin= 66
container[74].i= 120
container[74].j= 137
container[74].angle= 333
container[74].value= 255


container[75].bin= 27
container[75].i= 120
container[75].j= 142
container[75].angle= 135
container[75].value= 255


container[76].bin= 18
container[76].i= 120
container[76].j= 143
container[76].angle= 90
container[76].value= 255


container[77].bin= 8
container[77].i= 120
container[77].j= 144
container[77].angle= 44
container[77].value= 255


container[78].bin= 44
container[78].i= 120
container[78].j= 148
container[78].angle= 224
container[78].value= 255


container[79].bin= 0
container[79].i= 121
container[79].j= 137
container[79].angle= 0
container[79].value= 255


container[80].bin= 44
container[80].i= 121
container[80].j= 147
container[80].angle= 224
container[80].value= 255


container[81].bin= 0
container[81].i= 122
container[81].j= 137
container[81].angle= 0
container[81].value= 255


container[82].bin= 36
container[82].i= 122
container[82].j= 146
container[82].angle= 180
container[82].value= 255


container[83].bin= 63
container[83].i= 123
container[83].j= 138
container[83].angle= 315
container[83].value= 255


container[84].bin= 48
container[84].i= 123
container[84].j= 139
container[84].angle= 243
container[84].value= 255


container[85].bin= 36
container[85].i= 123
container[85].j= 146
container[85].angle= 180
container[85].value= 255


container[86].bin= 66
container[86].i= 124
container[86].j= 141
container[86].angle= 333
container[86].value= 255


container[87].bin= 36
container[87].i= 124
container[87].j= 146
container[87].angle= 180
container[87].value= 255


container[88].bin= 0
container[88].i= 125
container[88].j= 141
container[88].angle= 0
container[88].value= 255


container[89].bin= 36
container[89].i= 125
container[89].j= 146
container[89].angle= 180
container[89].value= 255


container[90].bin= 0
container[90].i= 126
container[90].j= 141
container[90].angle= 0
container[90].value= 255


container[91].bin= 27
container[91].i= 126
container[91].j= 147
container[91].angle= 135
container[91].value= 255


container[92].bin= 0
container[92].i= 127
container[92].j= 141
container[92].angle= 0
container[92].value= 255


container[93].bin= 27
container[93].i= 127
container[93].j= 148
container[93].angle= 135
container[93].value= 255


container[94].bin= 0
container[94].i= 128
container[94].j= 141
container[94].angle= 0
container[94].value= 255


container[95].bin= 30
container[95].i= 128
container[95].j= 149
container[95].angle= 153
container[95].value= 255


container[96].bin= 63
container[96].i= 129
container[96].j= 142
container[96].angle= 315
container[96].value= 255


container[97].bin= 54
container[97].i= 129
container[97].j= 143
container[97].angle= 270
container[97].value= 255


container[98].bin= 57
container[98].i= 129
container[98].j= 144
container[98].angle= 288
container[98].value= 255


container[99].bin= 44
container[99].i= 130
container[99].j= 147
container[99].angle= 224
container[99].value= 255


container[100].bin= 3
container[100].i= 131
container[100].j= 143
container[100].angle= 18
container[100].value= 255


container[101].bin= 8
container[101].i= 131
container[101].j= 144
container[101].angle= 44
container[101].value= 255


container[102].bin= 36
container[102].i= 131
container[102].j= 146
container[102].angle= 180
container[102].value= 255


container[103].bin= 63
container[103].i= 132
container[103].j= 143
container[103].angle= 315
container[103].value= 255


container[104].bin= 63
container[104].i= 132
container[104].j= 144
container[104].angle= 315
container[104].value= 255


container[105].bin= 36
container[105].i= 132
container[105].j= 146
container[105].angle= 180
container[105].value= 255


container[106].bin= 66
container[106].i= 133
container[106].j= 144
container[106].angle= 333
container[106].value= 255


container[107].bin= 0
container[107].i= 134
container[107].j= 144
container[107].angle= 0
container[107].value= 255


container[108].bin= 63
container[108].i= 135
container[108].j= 145
container[108].angle= 315
container[108].value= 255


container[109].bin= 44
container[109].i= 135
container[109].j= 146
container[109].angle= 224
container[109].value= 255


