container[0].bin= 8
container[0].i= 386
container[0].j= 424
container[0].angle= 44
container[0].value= 255


container[1].bin= 18
container[1].i= 387
container[1].j= 427
container[1].angle= 90
container[1].value= 255


container[2].bin= 18
container[2].i= 387
container[2].j= 428
container[2].angle= 90
container[2].value= 255


container[3].bin= 18
container[3].i= 387
container[3].j= 429
container[3].angle= 90
container[3].value= 255


container[4].bin= 21
container[4].i= 387
container[4].j= 430
container[4].angle= 108
container[4].value= 255


container[5].bin= 0
container[5].i= 389
container[5].j= 425
container[5].angle= 0
container[5].value= 255


container[6].bin= 36
container[6].i= 389
container[6].j= 430
container[6].angle= 180
container[6].value= 255


container[7].bin= 66
container[7].i= 390
container[7].j= 426
container[7].angle= 333
container[7].value= 255


container[8].bin= 30
container[8].i= 390
container[8].j= 430
container[8].angle= 153
container[8].value= 255


container[9].bin= 66
container[9].i= 391
container[9].j= 426
container[9].angle= 333
container[9].value= 255


container[10].bin= 36
container[10].i= 391
container[10].j= 430
container[10].angle= 180
container[10].value= 255


container[11].bin= 0
container[11].i= 392
container[11].j= 426
container[11].angle= 0
container[11].value= 255


container[12].bin= 36
container[12].i= 392
container[12].j= 430
container[12].angle= 180
container[12].value= 255


container[13].bin= 63
container[13].i= 393
container[13].j= 427
container[13].angle= 315
container[13].value= 255


container[14].bin= 27
container[14].i= 393
container[14].j= 431
container[14].angle= 135
container[14].value= 255


container[15].bin= 63
container[15].i= 394
container[15].j= 428
container[15].angle= 315
container[15].value= 255


container[16].bin= 27
container[16].i= 394
container[16].j= 432
container[16].angle= 135
container[16].value= 255


container[17].bin= 0
container[17].i= 395
container[17].j= 428
container[17].angle= 0
container[17].value= 255


container[18].bin= 36
container[18].i= 395
container[18].j= 432
container[18].angle= 180
container[18].value= 255


container[19].bin= 68
container[19].i= 396
container[19].j= 428
container[19].angle= 341
container[19].value= 255


container[20].bin= 54
container[20].i= 396
container[20].j= 430
container[20].angle= 270
container[20].value= 255


container[21].bin= 63
container[21].i= 396
container[21].j= 431
container[21].angle= 315
container[21].value= 255


container[22].bin= 66
container[22].i= 397
container[22].j= 431
container[22].angle= 333
container[22].value= 255


container[23].bin= 36
container[23].i= 397
container[23].j= 433
container[23].angle= 180
container[23].value= 255


container[24].bin= 0
container[24].i= 398
container[24].j= 431
container[24].angle= 0
container[24].value= 255


container[25].bin= 36
container[25].i= 398
container[25].j= 433
container[25].angle= 180
container[25].value= 255


container[26].bin= 68
container[26].i= 399
container[26].j= 431
container[26].angle= 341
container[26].value= 255


container[27].bin= 54
container[27].i= 399
container[27].j= 432
container[27].angle= 270
container[27].value= 255


container[28].bin= 39
container[28].i= 399
container[28].j= 433
container[28].angle= 198
container[28].value= 255


